components/tidb_query_executors/src/simple_aggr_executor.rs

Close #11735, Close pingcap/tidb#30923 
For `SimpleAggregation` does not return row if there is no input rows
Tests 
- Unit test
Side effects
```release-note
Fix wrong `any_value` result when there are regions returning empty result 
```

coprocessor: not return rows when there is no input for simple aggregation

---

components/tidb_query_datatype/src/codec/collation/encoding/gbk.rs
components/tidb_query_datatype/src/codec/collation/mod.rs
components/tidb_query_datatype/src/codec/mysql/charset.rs
components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: xiongjiwei <xiongjiwei1996@outlook.com>
Close https://github.com/tikv/tikv/issues/11757
some characters only have lower or upper case under gbk encoding. if so, we should make its lower or upper eq to itself
see https://github.com/pingcap/tidb/pull/28869 for more details
Tests 
- Unit test
```release-note
None
```

coprocesser: implement upper and lower function on GBK charset

---

tests/integrations/resource_metering/test_read_keys.rs

Ignore the read keys test temporarily. The actual optimization of test (with more changes) will be carried out later.
ref #11765
Signed-off-by: mornyx <mornyx.z@gmail.com>
```release-note
None
```

res_meter: ignore the read keys test temporarily

---

components/raftstore/src/store/config.rs
src/config.rs

close #11776
Close #11776  
Tests 
- Unit test
- No code
Side effects
- None
```release-note
None
```

config: relax the bounds of online configurable worker number (#11651)

---

Cargo.lock
components/resource_metering/Cargo.toml
components/resource_metering/src/lib.rs
components/resource_metering/src/recorder/localstorage.rs
components/resource_metering/src/recorder/mod.rs
components/resource_metering/src/recorder/sub_recorder/cpu.rs

close #11835
arc_swap is optimized for read-heavy situations but our case is write-heavy
use atomic_cell
```release-note
None
```

rsmeter: fix perf regression caused by arc swap 

---

components/tikv_util/src/worker/pool.rs
src/server/gc_worker/gc_worker.rs

Closes #11903
1. Callback is always called in `handle_gc_task_schedule_error`, so the `scheduled_tasks` counter is maintained correctly.
2. Allow `unsafe_destroy_range` to schedule even if the worker is full. Then, `unsafe_destroy_range` will still have the chance to execute when the GC worker is busy.
Tests 
- Unit test
```release-note
Fixes the bug that unsafe_destroy_range does not get executed when GC worker is busy
```

gc_worker: fix incorrect scheduled_tasks counting

---

components/engine_panic/src/raft_engine.rs
components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/raft_engine.rs
components/raft_log_engine/src/engine.rs
components/raftstore/src/store/bootstrap.rs
components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/worker/raftlog_gc.rs
components/test_raftstore/src/cluster.rs
components/tikv_util/src/yatp_pool/mod.rs
tests/failpoints/cases/test_snap.rs
tests/failpoints/cases/test_stale_peer.rs
tests/integrations/config/mod.rs
tests/integrations/raftstore/test_snap.rs
tests/integrations/raftstore/test_tombstone.rs

When clearing raft metas, raftstore will scan raft logs and delete them
one by one. Seeking can be slow if there are a lot of tombstone keys.
This PR moves the operation to raft log gc worker to reduce the impact.
The final solution should be also moving remaining IO operations to
async write IO threads.
Close #10210.
Tests 
- Unit test
```release-note
Avoid destroying a peer blocks raftstore thread
```

raftstore: move scan delete to raft log gc worker (#11853)

---

components/tikv_util/src/worker/pool.rs
src/server/gc_worker/gc_worker.rs

cherry-pick #11904 to release-5.1-20220125
Closes #11903
1. Callback is always called in `handle_gc_task_schedule_error`, so the `scheduled_tasks` counter is maintained correctly.
2. Allow `unsafe_destroy_range` to schedule even if the worker is full. Then, `unsafe_destroy_range` will still have the chance to execute when the GC worker is busy.
Tests 
- Unit test
```release-note
Fixes the bug that unsafe_destroy_range does not get executed when GC worker is busy
```

gc_worker: fix incorrect scheduled_tasks counting (#11904)

---

Cargo.toml
src/server/status_server/profile.rs

ref #10658
Make CPU Profiling only happen on x86_64 to avoid crashes. This is a temporary workaround, we're still working on fixing crashes in libgcc/llvm-libunwind/...
```release-note
Prevent TiKV segment fault (but produce an error) when profiling in ARM
```

pprof: ignore cpu profiling on non-x86 arch

---

src/server/gc_worker/gc_worker.rs

Close #11902
Close #11752
What's Changed: Limits the range to scan when processing `GcKeys` tasks in GC Worker. Hopefully this may reduce unnecessary tombstone scan in GcWorker that slows down GC tasks.
Tests 
- Unit test
Side effects
-
```release-note
None
```

gc_worker: Limit the key range to scan for GcKeys tasks

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs

Issue Number: Close #11933 
Remove `StoreMeta.leaders`
```commit-message
Remove `StoreMeta.leaders`
```
Tests 
`cargo check`
```release-note
None
```

raftstore: remove the leaders field of `StoreMeta`

---

components/tidb_query_datatype/src/codec/mysql/time/mod.rs
components/tidb_query_expr/src/impl_arithmetic.rs
components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Issue Number: close #11916
components/tidb_query_datatype/src/codec/mysql/time/mod.rs
components/tidb_query_expr/src/impl_arithmetic.rs
components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs
- Unit test
- [Integration test](https://github.com/tikv/copr-test)
- Manual test
- No side effects.
- Be backward compatibility
- Need TiDB open switch to use this feature.
```release-note
Added support for mod, sysdate push down. [tikv#11916]
```

copr: support push down mod, sysdate to TiKV

---

components/raftstore/src/store/worker/pd.rs
tests/integrations/raftstore/test_stats.rs

- rename `collect_interval` to `collect_tick_interval`
- rename `qps_info_interval` to `load_base_split_check_interval`
- rename `thread_info_interval` to `collect_store_infos_interval`
- add two function 
Tests 
- Unit test
```release-note
None
```

stats_monitor: reformat stats_monitor tick

---

components/raftstore/src/store/worker/split_controller.rs
metrics/grafana/tikv_details.json

Refine the `LOAD_BASE_SPLIT_EVENT ` metrics label definitions to make them more clear to help diagnose.
```commit-message
split_controller: refine the LOAD_BASE_SPLIT_EVENT metrics label definitions
```
Tests 
- Unit test
```release-note
None.
```

split_controller: refine the LOAD_BASE_SPLIT_EVENT metrics label definitions

---

components/raftstore/src/store/worker/split_controller.rs

Issue Number: Close #12012.
```commit-message
split_controller: fix the incorrect sampled key ranges number check
```
- Problem cause: https://github.com/tikv/tikv/pull/11986
Tests 
- Unit test
```release-note
None.
```

split_controller: fix the incorrect sampled key ranges number check

---

components/tidb_query_executors/src/runner.rs

A tiny refactor to extract a function `reschedule` in order to inject a fail point.
```release-note
None
```

copr: extract reschedule to inject a fail point

---

components/raftstore/src/coprocessor/dispatcher.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/store/peer.rs
src/server/raftkv.rs
tests/failpoints/cases/test_replica_read.rs

Issue Number: Close #12109
```commit-message
Consider a reader sends read index to the leader it supposed to be, but when
the leader receives the read index message, it has stepped down to a
follower. Without this commit, a peer will check the locks and re-fill the
read index context with the result no matter what role it is. So, when the
read index request is redirected to the new leader again, it no longer carries
the context of lock checking.
This commmit changes to only do the check when the peer is a leader. Then, the
read index request will remain unchanged before being redirected to the leader.
If the lease of the leader expires, it is still safe to check on the
uncertained leader. If the heartbeat check passes and no new leader is elected,
then the check works …
```

*: check memory locks for replica read only on the leader

---

components/online_config/online_config_derive/src/lib.rs
components/online_config/src/lib.rs
components/server/src/server.rs
components/tikv_util/src/config.rs
src/config.rs
src/storage/config.rs
src/storage/kv/test_engine_builder.rs
tests/integrations/config/mod.rs

Issue Number: Ref #11119
Support deriving `OnlineConfig` on any `Option<T>`. One caveat is such `T` must implement `Default`.
This change is made for #12127.
Tests
- Unit test
```release-note
None
```

config: simplify handling of nullable configurations

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/worker/region.rs
components/test_raftstore/src/cluster.rs
src/import/sst_service.rs
tests/failpoints/cases/test_conf_change.rs
tests/failpoints/cases/test_replica_stale_read.rs
tests/failpoints/cases/test_split_region.rs
tests/integrations/raftstore/test_hibernate.rs
tests/integrations/raftstore/test_merge.rs

Issue Number: Close #12057.
```commit-message
In the past, it relies on base tick to check if a snapshot is applied.
If the base tick is set to a very large value, it will take a long time
to detect snapshot is finished. This PR adds a casual message to notify
peer actively.
```
Tests 
- Unit test
```release-note
None
```

*: notify snapshot apply

---

Cargo.lock
cmd/build.rs
cmd/tikv-ctl/Cargo.toml
cmd/tikv-server/Cargo.toml
components/engine_rocks/Cargo.toml
scripts/check-bins.py

Issue Number: Close #12144
```commit-message
In the past, we rely on librocksdb-sys to include the required stdc++
library. This is not reliable after upgrading grpcio, which also needs
the same library. I suspect it doesn't include all the required symbols.
Anyway, this PR chooses to link to stdc++ explicitly in binary.
```
Tests 
```release-note
None
```

cmd: link c++ explicitly

---

Cargo.lock
components/backup/src/endpoint.rs
components/concurrency_manager/Cargo.toml
components/concurrency_manager/benches/lock_table.rs
components/txn_types/src/lib.rs
components/txn_types/src/lock.rs
src/coprocessor/endpoint.rs
src/server/raftkv.rs
src/storage/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/scanner/backward.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/reader/scanner/mod.rs

Try to support read-consistency read processing with tso checking to optimize the latency.
Ref document: https://github.com/pingcap/tidb/pull/32806
Ref kvproto change: https://github.com/pingcap/kvproto/pull/876
- If the isolation field in a read request is `RcCheckTs`,  return write conflict error directly to the client. The client may retry the whole SQL statement with a new `for_update_ts` fetched from global tso allocator if no data package has been responsed to the MySQL client.
Tests 
- Unit test
Side effects
```release-note
Support read-consistency read with tso checking.
```

txn: support read-consistency read with tso checking

---

components/cdc/tests/integrations/test_cdc.rs
etc/config-template.toml
src/server/lock_manager/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: Close #11452
- PR to update `pingcap/docs`/`pingcap/docs-cn`: https://github.com/pingcap/docs-cn/pull/8645
Tests 
- Unit test
```release-note
None
```

config: enable in-memory pessimistic locks by default

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/tests/failpoints/test_endpoint.rs

Issue Number: Close https://github.com/pingcap/tiflow/issues/4782
CDC shouldn't emit resolved timestamps before incremental scan finished. https://github.com/tikv/tikv/pull/11098 tried to fix the problem but the implementation is wrong. This patch gives a correct solution.
```commit-message
cdc: don't emit resolved timestamps before scan
```
Tests 
Side effects
```release-note
None
```

cdc: don't emit resolved timestamps before scan

---

src/config.rs

ref #11804  
```commit-message
config: limit backup workers cap
```
- None
Tests 
- Manual test,
- use mysql client to test
Side effects
- None
```release-note
None.
```

config: limit backup workers cap

---

Cargo.lock

Issue Number: Close #12180
```commit-message
*: upgrade jemalloc version to fix sampling problem during profiling
```
The lastest jemalloc has fixed one profiling problem https://github.com/tikv/jemalloc/pull/2. 
Tests 
Profiling with this patch, and we can see the profiling result looks good.
[tikv3-2022-03-16-on-the-fly-13G.pdf](https://github.com/tikv/tikv/files/8258408/tikv3-2022-03-16-on-the-fly-13G.pdf)
Side effects
```release-note
NONE
```

*: update jemalloc version to fix profiling problem

---

components/server/src/server.rs
src/config.rs
src/read_pool.rs

close #11781
Close #11781 
Tests 
- Unit test
- No code
Side effects
- None
```release-note
UnifiedReadPool: support adjusting the pool size dynamically
```

UnifiedReadPool: support adjusting the pool size dynamically

---

components/test_raftstore/src/cluster.rs
src/coprocessor/endpoint.rs
tests/integrations/coprocessor/test_select.rs

close #12182
Issue Number: Close #12182
```commit-message
Return the latest buckets version in coprocessor reponses to notify clients to refresh cached buckets information.
```
Tests 
- Unit test
Side effects
```release-note
None
```

copr: return buckets version for unary call

---

components/raftstore/src/store/fsm/peer.rs
tests/failpoints/cases/mod.rs
tests/failpoints/cases/test_hibernate.rs

Issue Number: Close #12166 
Currently it only contains a test case. More commits will be pushed to fix the issue later.
```commit-message
avoit to banish region leaders when rolling upgrade
```
Tests 
Side effects
```release-note
None
```

avoid to banish region leaders when rolling upgrade

---

Cargo.lock
components/engine_panic/src/write_batch.rs
components/engine_rocks/Cargo.toml
components/engine_rocks/src/event_listener.rs
components/engine_rocks/src/raft_engine.rs
components/engine_rocks/src/write_batch.rs
components/engine_traits/src/write_batch.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/store.rs
etc/config-template.toml
src/config.rs
src/server/debug.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: Close https://github.com/tikv/tikv/issues/12059
I refactor the pipelined-write referring the solution of cockroachdb. See the design details in https://github.com/cockroachdb/pebble/blob/master/docs/rocksdb.md#commit-pipeline 
pick https://github.com/tikv/rocksdb/pull/267 to master
Tests 
Side effects
```release-note
* The configure rocksdb.enable-multibatch-write will be discarded.  And if user set both rocksdb.enable-pipelined-write and rocksdb.enable-unordered-write false, TiKV will enable the new pipeline write. Otherwise, …
```

rocksdb: use new pipelined-write to replace multibatch-write

---

src/server/status_server/profile.rs

Add `[vdso]` to the `pprof-rs` blocklist, we "guess" the problem would be the dwarf information in vdso is incorrect. This is a PR to test whether it would work well after blocking the `vdso`.
Issue Number: Close https://github.com/tikv/tikv/issues/9765
```release-note
Fix crash when profiling in Ubuntu 18.04.
```

add vdso to the pprof blocklist

---

components/raftstore/src/coprocessor/config.rs

Issue Number: Close #12235, #12236
```commit-message
Shouldn't report config related errors when bucket is disabled.
```
Tests 
- Unit test
Side effects
```release-note
None
```

raftstore: validate bucket config only when it's enabled

---

components/server/src/server.rs
components/test_raftstore/src/server.rs
components/tikv_util/src/quota_limiter.rs
etc/config-template.toml
src/config.rs
tests/integrations/server/kv_service.rs

Issue Number: Close #12218
```commit-message
Use the results returned by the cpu limiter directly without extra processing
```
- Need to cherry-pick to the release 6.0 branch
Tests 
- Unit test
Side effects
- No
```release-note
None
```

Quota limiter: make method to delay cpu more precise

---

components/resource_metering/src/model.rs
components/resource_metering/src/reporter/mod.rs

Issue Number: close #12234
Signed-off-by: mornyx <mornyx.z@gmail.com>
In the past, we used assertions to ensure that when tagged `Records.records` was empty, untagged `Records.others` must also be empty:
```rust
pub fn is_empty(&self) -> bool {
if self.records.is_empty() {
assert!(self.others.is_empty());
true
} else {
false
}
}
```
This is reasonable in the general case, but will trigger an assertion failure under some special condition...
In a certain round of collection, when we collect tags that exceed the maximum number limit (`max_resource_group`), and all these tags correspond to equal `cpu_time`, then our `records.top_k()` action will get 0 `top` and many `evicted`:
```rust
fn handle_records(&mut self, records: Arc<RawRecords>) {
let ts = records.begin_unix_time_secs;
if …
```

res_meter: fix assertion failure

---

Cargo.lock
Cargo.toml
components/resource_metering/Cargo.toml
components/tikv_util/Cargo.toml
tests/Cargo.toml

FYI https://github.com/tikv/procinfo-rs/pull/12
```commit-message
Update procinfo-rs to support pid status parse in kernel 5.x.
```
- Need to cherry-pick to the release 6.0 branch
Tests 
- Unit test
Side effects
None
```release-note
None
```

Update procinfo-rs to support pid status parse in kernel 5.x

---

components/cdc/src/delegate.rs

https://github.com/tikv/tikv/pull/11896#discussion_r834951841 introduces a critical bug for CDC, which can cause data lost or downstreams blocking forever. Here is how to trigger the bug:
1. multiple downstreams subscribe one region
2. cancel one downstream before the region delegate has been initialized
Then, `Delegate::stop_observing` will be called incorrectly and all change events will be lost.
This PR does
1. correct the bug
2. add a log for `stop_observing`
3. complete unit tests for `Delegate::subscribe` and `Delegate::unsubscribe`.
```commit-message
cdc: remove downstreams correctly when uninitialized
```
Tests 
- Unit test
Side effects …

cdc: remove downstreams correctly when uninitialized

---

components/raftstore/src/store/peer.rs
components/test_raftstore/src/cluster.rs
tests/failpoints/cases/test_merge.rs

Issue Number: Close #12232 
When destroying, only persist merge target if the merge is known to be succeeded
```commit-message
raftstore: only persist merge target if the merge is known to be succeeded
```
Tests 
```release-note
fix tikv panic and peer unexpected destroy due to fake merge target
```

raftstore: only persist merge target if the merge is known to be succeeded

---

Cargo.lock

Issue Number: Close #12204
```commit-message
```
Tests 
- Unit test
```release-note
None
```

engine: update rust-rocksdb

---

components/cdc/src/delegate.rs

Issue Number: Close https://github.com/tikv/tikv/issues/12278
```commit-message
Fix test_delegate_subscribe_unsubscribe flaking test. 
Use the corresponding id, otherwise there will be failures due to concurrent runs of the test. (We will assign downstream ids concurrently).
```
Tests 
- Unit test
Side effects
None
```release-note
None
```

Fix test_delegate_subscribe_unsubscribe flaking test

---

src/storage/txn/store.rs

```
Checking batch length == 1 is what we did when `multi` field of `PointGetter`was not removed and we set 'multi` be false in that case. Now, as `multi` field is removed, it is unnecessary for us to check the length.
```
Tests 
- Unit test
- No code
Side effects
```release-note
If this PR will be picked to release branch, then a release note …
```

txn: remove unnecessary length check in SnapshotStore::batch_get

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/worker/raftlog_gc.rs
tests/failpoints/cases/test_unsafe_recovery.rs
tests/integrations/raftstore/test_unsafe_recovery.rs

Signed-off-by: v01dstar <yang.zhang@pingcap.com>
Issue Number: ref #10483
Raft snapshot apply has a different code path to update the apply index, compare to other types of Raft entry which update apply index in `raftstore/store/fsm/peer.rs:on_apply_res()`. This path was not covered in the initial implementation of "unsafe recovery wait apply", and this PR fixes it.
PR that adds the initial implementation of unsafe recovery wait apply: https://github.com/tikv/tikv/pull/11716
Tests 
Side effects
N/A
```release-note
None
```

raftstore: Make unsafe recovery wait apply cover snapshot apply cases ref #10483

---

src/storage/txn/commands/prewrite.rs

Issue Number: Close https://github.com/pingcap/tidb/issues/34066
```commit-message
If a retried prewrite encounters a newer lock, the result may be not
idempotent.
This happens when the first prewrite succeeds and the transaction
is committed by resolving async-commit locks. Then, TiKV returns
KeyIsLocked in the retry while the first prewrite succeeds.
If the client does not handle it carefully, the client may report a false
commit failure to the user.
This commit fixes the bug, making prewrite idempotent in this case.
```
Tests 
- Unit test
```release-note
Fixes that successfully committed optimistic transactions may report false WriteConflict on network errors.
```

txn: make prewrite idempotent after a new lock is written

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/tests/failpoints/test_endpoint.rs

```commit-message
cdc: advance resolved ts correctly for old clients
```
Tests 
Side effects
```release-note
None
```

cdc: advance resolved ts correctly for old clients

---

tests/integrations/import/util.rs

Issue Number: Close #10549
```commit-message
If running sst_import tests concurrently, different tests will use the same
default listening address 127.0.0.1:20160. And during resource cleanups,
one test may close the connection of another test. This is probably the
cause of #10549.
So, this commit changes the listening address in tests to 127.0.0.1:0.
The operating system unlikely uses the same port after the change.
```
Tests 
I've tried running all tests in `test_sst_service` several times. Before the change,
I always get similar errors in #10549. But now, it never fails. 
```release-note
None
```

tests: use random port for import integration tests

---

Cargo.lock
components/engine_rocks/src/lib.rs
components/engine_rocks/src/perf_context_impl.rs
components/raftstore/src/store/config.rs

Issue Number: ref #12362
```commit-message
PerfFlags provides more fine-grained PerfContext collecting. In this way, we
only collect the duration we really care about. Theoretically, it reduces the
overhead of collecting PerfContext compared to using PerfLevel::EnableTime.
This commit only changes the raftstore part. The read pool part will be done
later.
The default value of raftstore.perf-level is changed to Uninitialized. The
config is not documented before, so I think the change is not so important
to change the default value.
```
Tests 
- Manual test
```release-note
None
```

engine_rocks: replace PerfLevel with PerfFlags in raftstore

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
tests/integrations/raftstore/test_unsafe_recovery.rs

Issue Number: Ref #10483
```commit-message
Force leader is rejected on a peer who is already a leader. For the hibernated leader,
it doesn't step down to follower when quorum is missing due to not ticking election. 
So wait ticks in force leader process for hibernated peers to make sure election ticking
is performed.
```
Tests 
- Unit test
```release-note
None
```

raftstore: Wait ticks for hibernated peer when doing force leader

---

src/coprocessor/error.rs
tests/failpoints/cases/test_coprocessor.rs

Issue Number: Close #12341
```commit-message
The memory lock returned from the leader in replica read is a
tikv_kv::ErrorInner::KeyIsLocked. The conversion from this error to
coprocessor::Error is not implemented, so this error is finally turned
to an other error, which cannot be correctly handled in TiDB.
This commit implements the missing conversion. Now, the memory
lock will be correctly set in the `locked` field in the response.
```
Tests 
```release-note
Fix unhandled KeyIsLocked errors in follower read.
```

copr: return memory locks correctly in replica read

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_split_region.rs
tests/integrations/raftstore/test_split_region.rs

Issue Number: Close #12368
```commit-message
If an uninitialized peer is destroyed during split check, it can either
panic or create stale peer with corrupted state.
```
Tests 
- Unit test
```release-note
fix race between split check and destroy
```

raftstore: fix race between split check and destroy

---

components/server/src/server.rs

Issue Number: Close #12399
```commit-message
Make lock files accessible to all users.
```
- None
Tests 
- Unit test
- No code
Side effects
```release-note
Fix the bug where sometimes tikv-server would not start because it didn't have access to lock files.
```

cmd: make lock files accessible to all users.

---

components/raftstore/src/lib.rs
components/raftstore/src/store/worker/split_controller.rs

Issue Number: Close #12416
```commit-message
split_controller: fix the bug that may cause the stats_monitor to fall into a dead loop
```
Tests 
- Unit test
```release-note
Fix a bug that causes the TiKV thread to fall into a dead loop and then lead to OOM.
```

split_controller: fix the bug that may cause the stats_monitor to fall into a dead loop

---

components/server/src/server.rs

This reverts commit 95c4d0ed36369c254b1bee36eb007004ee834948.
Issue Number: Close #12399
```commit-message
revert #12400. 777 permission is not safe because we cannot assume that all users in the system are trusted.
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

cmd: revert #12400

---

components/raftstore/src/coprocessor/split_check/half.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/worker/split_check.rs

Issue Number: Close #12467
```
It's possible that when the split bucket task runs, the data of end ranges in bucket_range_list have been deleted.
As a result, the buckets generated by scan may miss some bucket ranges. The fix is to add the empty Bucket instances.
Also change the log level to debug for some chatty logs.
```
Tests 
- Unit test
Side effects
```release-note
None
```

raftstore: fix split buckets bug

---

metrics/grafana/tikv_raw.json

Issue Number: #11965
Signed-off-by: pingyu <yuping@pingcap.com>
Issue Number: ref #11965
```commit-message
Add Grafana panels for RawKV causal timestamp.
```
Metrics is added by PR: https://github.com/tikv/tikv/pull/12099
Screenshot of Grafana
No.
No.
Tests 
- No code
Side effects
- No.
```release-note
Add Grafana panels for RawKV causal timestamp.
```

metrics: add grafana panels for RawKV causal timestamp

---

src/storage/txn/actions/prewrite.rs
src/storage/txn/commands/prewrite.rs

Signed-off-by: ekexium <ekexium@gmail.com>
Issue Number: Close #12487 
We enforce a constraint check before the assertion error is returned. If the constraint check failed, return it instead of the assertion failure.
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

txn: do conflict check before returning assertion failure

---

components/pd_client/src/client.rs
components/raftstore/src/store/worker/pd.rs
components/test_raftstore/src/pd.rs
tests/integrations/raftstore/test_replica_read.rs

Signed-off-by: 5kbpers <hustmh@gmail.com>
Issue Number: Close #12478
```commit-message
check store id before sending wakeup message
```
Tests 
- Unit test
```release-note
Fix a bug that sometimes generates a message with zero store id when doing follower read
```

raftstore: check store id before sending wakeup message

---

src/server/gc_worker/rawkv_compaction_filter.rs

Signed-off-by: ystaticy <y_static_y@sina.com>
Issue Number: Ref https://github.com/tikv/tikv/issues/12535
```release-note 
Fix RawKV Compaction filter report total is aways 0
```
Tests 
Test steps as follows:
1. To set api version in tikv.toml as follows:
enable-ttl = true
api-version = 2
2. start tikv cluster.
3. write data until trigger compaction.
4. Observation log output ```total``` value is not always 0.

add RawKV GC metric versions count

---

components/raftstore/src/coprocessor/config.rs
components/raftstore/src/store/config.rs
metrics/grafana/tikv_details.json
src/server/config.rs
tests/integrations/raftstore/test_split_region.rs

Issue Number: Ref #11966
```commit-message
1) update max_snapshot_file_raw_size's validate rule to allow 0
2) update region_bucket_size's default value to 96MB from 128MB
3) add buckets metrics to grafana tikv_details dashboard
```
Tests 
- Manual Test
```release-note
None
```

raftstore: misc changes for dynamic regions

---

Cargo.lock

Issue Number: Close #12543
`fallocate` is not as portable as `posix_fallocate`. The change is at https://github.com/tabokie/fs2-rs/commit/cd503764a19a99d74c1ab424dd13d6bcd093fcae.
```commit-message
Use `posix_fallocate` for space reservation.
```
Tests 
- Unit test
```release-note
Use `posix_fallocate` for space reservation.
```

file_system: update fs2 fork to use posix_fallocate

---

tests/failpoints/cases/test_transaction.rs

Issue Number: Close #12520
```commit-message
This commit intends to make test_atomic_getting_max_ts_and_storing_memory_lock
and test_pessimistic_lock_check_epoch less flaky.
Instead of using pause and sleep to control order, this commit uses channels
and fail::callback_cfg to control the order more deterministically.
```
Tests 
```release-note
None
```

tests: make several txn tests less flaky

---

components/tidb_query_datatype/src/codec/convert.rs

Issue Number: Close #12542
```commit-message
handle invalid utf8 characters in `produce_str_with_specified_tp` func
```
Tests 
- Unit test
```release-note
fix panic when `cast` function pushdown to tikv with invalid utf8 characters.
```

components: handle invalid utf8 characters in `produce_str_with_specified_tp` func

---

src/server/gc_worker/gc_worker.rs

Signed-off-by: ystaticy <y_static_y@sina.com>
Issue Number: Ref https://github.com/tikv/tikv/issues/12557
```release-note 
RawKV GCTask return handled and wasted count
```
Tests 
- Manual test 
If the data is the latest version is deleted or expired and to Compcation,it will trigger ```GcTask::RawGcKeys```
We can get ```tikv_gc_compaction_filter_mvcc_deletion_handled``` value is not ```0``` in grafana

Rawkv gctask metrics

---

components/backup/src/endpoint.rs
components/backup/src/utils.rs

Issue Number: Close #12548 
If backup rawkv from apiv1 to rawv2, the range in BackupResponse files field should be encoded with apiv2 format.
1. If the range is empty, the file range should be [r, s)
2. If the range is not empty, the range shoudl be mce padding of [start_key, end_key).
Tests 
- Unit test
Side effects
- No side effect
```release-note
rawkv apiv2 backup bug fix
```

[backup apiv2] fix file range in backup response

---

components/raftstore/src/store/config.rs

Issue Number: Close #12560
```commit-message
raftstore: enable waterfall metrics by default
```
Tests 
- No code
Side effects
```release-note
raftstore: enable waterfall panel by default
```

raftstore: enable waterfall panel by default

---

components/raftstore/src/store/fsm/peer.rs
tests/integrations/raftstore/test_split_region.rs

Issue Number: Ref #12574
```commit-message
Reset the buckets of target region after the merge, this is to refresh the buckets in-time. 
```
Tests 
- Unit test
Side effects
```release-note
None
```

Raftstore: reset the bucket after the regions merge

---

components/raftstore/src/store/config.rs
components/server/src/server.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/server.rs
src/config.rs

Issue Number: Close #12598
```commit-message
fix the config of region_split_check_diff with min(region_size/16, bucket_size)
```
Tests 
- Unit test
```release-note
None
```

Raftstore: fix the config of region_split_check_diff

---

src/config.rs

Issue Number: #12600
Signed-off-by: pingyu <yuping@pingcap.com>
Issue Number: Close #12600 
```commit-message
Fix startup error when upgrade storage.api-version from 1 to 2.
```
No.
v6.1.0
Tests 
- Unit test
Side effects
- No.
```release-note
Fix startup error when upgrade storage.api-version from 1 to 2.
```

config: fix startup error when upgrade storage.api-version from 1 to 2

---

src/storage/mod.rs
tests/integrations/storage/test_storage.rs

Signed-off-by: ystaticy <y_static_y@sina.com>
Issue Number: Close https://github.com/tikv/tikv/issues/12595
```
If cmd is scan_lock , it will not execute invalid_key_range_mode check.
```
Tests 
- Unit test
```release-note
fix:when enable api v2 , TiDB resolve lock meet error
```

fixbug:when enable api v2 , TiDB resolve lock meet error

---

src/storage/txn/actions/prewrite.rs
src/storage/txn/commands/prewrite.rs

Issue Number: Close #11612
```commit-message
For CDC compatibility, we check conflicts for retried pessimistic
prewrite (#11264). But this may cause false WriteConflict errors
if the commit TS of the record is larger than the start ts but smaller
than the for_update_ts.
So, this commit uses for_update_ts to check conflicts for pessimistic
transactions to avoid returning false errors. And if there really is a
conflicted record, PessimisticLockNotFound is returned to become
more semantically correct.
```
Tests 
- Unit test
- 
```release-note
Prevent false WriteConflict errors in pessimistic transactions.
```

txn: check conflicts for pessimistic prewrite according to for_update_ts

---

Cargo.lock
Cargo.toml
Makefile
cmd/tikv-server/Cargo.toml
components/causal_ts/src/observer.rs
tests/Cargo.toml

Signed-off-by: mornyx <mornyx.z@gmail.com>
Issue Number: Close #12590
In https://github.com/tikv/tikv/pull/12480, we have introduced two mutually exclusive features, `pprof-dwarf` and `pprof-fp`. One of them must exist, otherwise a compilation error will occur. This introduces stricter requirements for feature usage in some modules.
We need to relax them and keep only one `pprof-fp`, anything else should automatically fallback to DWARF-based.
- https://github.com/tikv/pprof-rs/pull/130
```release-note
None
```

*: avoid mutually exclusive features in pprof

---

components/tikv_util/src/quota_limiter.rs

Issue Number: Close #12622
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

quota-limiter: fix panic when set limiter value to 0

---

components/pd_client/src/errors.rs
components/pd_client/src/util.rs
components/resolved_ts/src/advance.rs
components/resolved_ts/src/lib.rs
tests/integrations/pd/test_rpc_client.rs

Issue Number: close #12506 
```commit-message
do not reconnect PD on store tombstone error
```
Tests 
- Unit test
```release-note
Fix the issue that keep retrying reconnecting PD when encounter store tombstone error
```

pd_client: Do not reconnect on store tombstone error

---

components/raftstore/src/coprocessor/config.rs
components/raftstore/src/coprocessor/split_check/keys.rs
components/raftstore/src/coprocessor/split_check/mod.rs
components/raftstore/src/coprocessor/split_check/size.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
tests/integrations/raftstore/test_split_region.rs

Issue Number: Close #12597
```commit-message
1) originally the split by keys only support CheckPolicy::Scan. Add CheckPolicy::Approximate support. 
2) refine the way to use approximate size for split---calculate the actual split count per region size instead of use batch_split_limit
3) refine the bucket_version logic to make it monotonic----basically keep the region_buckets in last_region_buckets on split/merge 
```
Tests 
- Unit test
Side effects
- None
```release-note
None
```

raftstore: bucket and region split bug fix

---

components/raftstore/src/store/fsm/peer.rs
tests/integrations/raftstore/test_unsafe_recovery.rs

Signed-off-by: v01dstar <yang.zhang@pingcap.com>
Issue Number: Close #12644
```commit-message
Cleaning up the unsafe recovery state after exiting previous joint state before proposing the recovery demotion which may return early if any error happens and leave the state untouched. 
```
- PR that adds the recovery logic and introduces the bug: #12022
Tests 
Side effects
N/A
N/A
```release-note
None
```

raftstore: fix the recovery process hanging issue caused orphaned unsafe recovery state

---

components/tidb_query_expr/src/impl_math.rs

Issue Number: Close https://github.com/tikv/tikv/issues/12673
```commit-message
Fix tikv crash when conv empty string
```
Tests 
- Unit test
- No code
Side effects
```release-note
Fix tikv crash when conv empty string
```

expr: fix tikv crash when conv empty string

---

Cargo.lock
components/backup-stream/src/observer.rs
components/causal_ts/Cargo.toml
components/causal_ts/src/observer.rs
components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/coprocessor/region_info_accessor.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs
components/resolved_ts/src/observer.rs
components/test_raftstore/src/server.rs
components/test_raftstore/src/util.rs
src/server/lock_manager/deadlock.rs
tests/failpoints/cases/mod.rs
tests/failpoints/cases/test_rawkv.rs
tests/integrations/raftstore/test_region_change_observer.rs

Signed-off-by: pingyu yuping@pingcap.com
Issue Number: Close #12680
```commit-message
Fix issue #12680.
```
In the scenario of region merge, the target region would merge some entries from source region with larger timestamps, when leader of source region is in another store with larger TSO batch than the store of target region's leader.
So we need a flush after commit merge.
Also see analysis in #12680.
No.
release-6.1
Tests 
- Unit test
Side effects
- No.
```release-note
Fix issue #12680.
```

causal_ts: fix issue #12680

---

components/raft_log_engine/src/engine.rs
components/server/src/server.rs

Issue Number: Close #12698 
```commit-message
Close engine before cleaning up its data during raft engine migration.
```
Tests 
- Unit test
```release-note
None
```

server: fix race during raft data migration

---

components/raftstore/src/coprocessor/config.rs
components/raftstore/src/coprocessor/split_check/half.rs
components/raftstore/src/coprocessor/split_check/keys.rs
components/raftstore/src/coprocessor/split_check/mod.rs
components/raftstore/src/coprocessor/split_check/size.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: ref #12597
```commit-message
When bucket is enabled,  using CheckPolicy::Scan would lead to large amount of read IO after tikv restart. Before this PR, the Scan is used unless the region size reaches 1.5G, which is very rare for a 96 ~ 256MB's region-split-size. After this change, generating bucket won't introduce new scan unless the scan is necessary for splitting region. This can significantly reduce the read IO.
Also refine the logic for the fix of 12597. 
```
Tests 
- Unit test
```release-note
None
```

raftstore: use approximate size to generate bucket unless split region check is needed and scan is used for it.

---

CONTRIBUTING.md
Cargo.toml

Issue Number: Close #12707 
```commit-message
This PR optimize debug build by disabling all debuginfo excepts tests
itself. So that the generated artifacts will be smaller and also speed
up compile time a little.
```
My local tests show that target directory changes from 45GiB to about 9.2GiB. And build time on Linux VM (8 vcores32GiB memory 2200MHz) is changing from 17m22s to 13m46s. The improvement probably comes from writing less data to disk.
Tests 
- Unit test
```release-note
None
```

*: optimize debug build

---

components/backup-stream/src/router.rs
components/backup-stream/tests/mod.rs
components/security/Cargo.toml
components/security/src/lib.rs
components/server/Cargo.toml

Signed-off-by: Yu Juncen <yujuncen@pingcap.com>
Issue Number: Close #12711 
Make `tonic` in `security` crate an optional requirement.
```commit-message
```
Tests 
Now we can run `cargo test` for raftstore. And there is no need for compiling tonic.
- No code
```release-note
none
```

security, server: fix running local test

---

components/api_version/src/api_v1.rs
components/api_version/src/api_v1ttl.rs
components/api_version/src/api_v2.rs
components/api_version/src/lib.rs
components/backup/src/endpoint.rs
components/backup/src/utils.rs
tests/integrations/backup/mod.rs

Issue Number: Close #12758 
Add encoding of key space id in apiv2 key when backup convert.
Tests 
- Unit test
Side effects
```release-note
Add key space id encoding in apiv2 key when backup convert.
```

Reserve key space id encoding in backup convert

---

components/external_storage/src/lib.rs
components/sst_importer/src/sst_importer.rs

Issue Number: Close https://github.com/tikv/tikv/issues/12751
Close https://github.com/tikv/tikv/issues/12750
- It need create subdir("v1/tXXXXX") before downloading kv file on `restore point` with KMS.
- Do not decrypt kv file when download  it because these kv-files are not encrypted when created.
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

log-backup: fix bug about restoring point at TiCloud with KMS

---

components/cdc/src/endpoint.rs
components/sst_importer/src/config.rs
src/config.rs

Issue Number: Close https://github.com/tikv/tikv/issues/12771
do not return error when validation failed. just change the config value to default instead.
```config: change the backup/import/cdc config to default value when input config is invalid.
```
Tests 
- Unit test
set backup.num-threads to 0
check the log.
check the config in log.
Side effects
```release-note
Fix the issue that tikv refused to start when the config of backup/import/cdc is invalid.
```

config: output warn log when some components config invalid

---

etc/config-template.toml
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: Close #12797
```commit-message
Deprecate gc-merge-rewrite option.
```
Tests 
- No code
```release-note
Deprecate gc-merge-rewrite option.
```

engine: deprecate gc-merge-rewrite option

---

components/txn_types/src/types.rs
src/storage/txn/commands/acquire_pessimistic_lock.rs
src/storage/txn/commands/check_secondary_locks.rs
src/storage/txn/commands/check_txn_status.rs
src/storage/txn/commands/commit.rs
src/storage/txn/commands/macros.rs
src/storage/txn/commands/pessimistic_rollback.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/commands/resolve_lock.rs
src/storage/txn/commands/resolve_lock_lite.rs
src/storage/txn/commands/rollback.rs
src/storage/txn/scheduler.rs

Issue Number: close #12803 
```commit-message
In the investigation process, the debug log information helps a lot, but there's still some important information 
missing such as retrying or 1pc flags. 
Changed:
1. Add more useful information displaying commands.
2. Redact necessary parts.
```
Tests 
Side effects
```release-note
NONE
```

txn: add more debug information for the txn commands

---

components/raftstore/src/store/fsm/apply.rs

As the title shown, this commit has fixed the issue:#11044 with resetting the `perf_context` before
applying a `write_batch` to `raftstore`.
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
Issue Number: Close #11044
```Rust
--- a/components/raftstore/src/store/fsm/apply.rs
+++ b/components/raftstore/src/store/fsm/apply.rs
@@ -520,6 +520,7 @@ where
self.pending_ssts = vec![];
}
if !self.kv_wb_mut().is_empty() {
+            self.perf_context.start_observe();
let mut write_opts = engine_traits::WriteOptions::new();
write_opts.set_sync(need_sync);
self.kv_wb().write_opt(&write_opts).unwrap_or_else(|e| {
@@ -3819,7 +3820,6 @@ where
}
update_cfg(&incoming.apply_batch_system);
}
-        self.apply_ctx.perf_context.start_observe();
}
```
```release-note
Fix the issue:#11044 by …
```

raftstore: reset perf context before each apply write

---

components/pd_client/src/errors.rs
components/test_pd/src/mocker/retry.rs

Issue Number: Close #12345
When encounter error like region not found or invalid region epoch, PD returns error type of unknown. For these errors, we don't need to reconnect pd client.
```commit-message
do not reconnect for pd unknown error
```
Tests 
- Unit test
```release-note
Fix bug which causes frequent pd client reconnection
```

pd_client: Do not reconnect for pd unknown error

---

components/raftstore/src/store/local_metrics.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/peer.rs
metrics/grafana/tikv_details.json

Issue Number: Ref #12362 
```commit-message
Our raft implementation has its flow control mechanism to limit the inflight
message number. But we're not able to know whether and when we are
throttled. Then, it's hard for us to know whether we should adjust the
max-inflight-msgs config.
This commit tries to improve this case. It's complex to add hooks to raft-rs
to know how long a message is throttled, but we can do it in the raftstore.
We record the propose time, and consume it and record it in the histogram
when the messages is send through the transport. If flow control takes effect,
the ready will be smaller than all under-replicated logs. So, we can know if
flow control takes effect.
```
Grafana panel looks like:
Tests  …

raftstore: record metrics of proposal send wait duration

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/worker/raftlog_gc.rs
tests/failpoints/cases/test_split_region.rs

Issue Number: Close #12825
```commit-message
Uninitialized peer has not received any logs, so it doesn't need to
clean up any logs.
```
Tests 
- Unit test
```release-note
Fix potential panic when a peer is being split and destroyed at the same time
```

raftstore: skip flushing raft logs for uninitialized peer

---

Cargo.lock
components/engine_panic/src/raft_engine.rs
components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/raft_engine.rs
components/raft_log_engine/src/engine.rs
components/raftstore-v2/Cargo.toml
components/raftstore-v2/src/bootstrap.rs
components/raftstore-v2/src/fsm/mod.rs
components/raftstore-v2/src/fsm/store.rs
components/raftstore-v2/src/lib.rs
components/raftstore-v2/src/raft/mod.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/src/router/message.rs
components/raftstore-v2/tests/failpoints/mod.rs
components/raftstore-v2/tests/failpoints/test_bootstrap.rs
components/test_pd/src/mocker/service.rs
src/server/node.rs

Different from v1, v2 provides a bootstrap struct that can make bootstrapping easier.
The change may also be friendly for third parties like tiflash to reuse raftstore.
V1 may also adapt similar pattern in the future.
```commit-message
```
Tests 
- Unit test
- 
```release-note
None
```

raftstorev2: add bootstrapping

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/router.rs

Issue Number: Close #12903
this PR is cherry-picked by https://github.com/joccau/tikv/pull/13
- store log files by date.
- keep advanced checkpoint-ts as safe point with ttl 12 hours.
```commit-message
1. store log files by date.
2. keep advanced checkpoint-ts as safe point with ttl 12 hours.
```
Tests 
Side effects
```release-note …
```

log-backup: store log files by date and keep advanced checkpoint-ts as safe point with ttl 12 hours

---

components/backup/src/endpoint.rs
components/cdc/src/endpoint.rs
components/engine_rocks/src/config.rs
components/file_system/src/lib.rs
components/online_config/online_config_derive/src/lib.rs
components/online_config/src/lib.rs
components/raftstore/src/store/config.rs
components/raftstore/src/store/worker/split_check.rs
components/raftstore/src/store/worker/split_config.rs
components/resolved_ts/src/endpoint.rs
components/resource_metering/src/config.rs
components/tikv_util/src/config.rs
src/config.rs
src/server/config.rs
src/server/gc_worker/config.rs
src/server/raft_client.rs
src/storage/config_manager.rs
tests/integrations/config/dynamic/gc_worker.rs
tests/integrations/config/test_config_client.rs

Issue Number: Close #12909
```
Replace Into::into with TryInto::try_info to simplify the type conversion of ConfigValue
```
Currently, OnlineConfig depends on `From`/`Into` to convert between `ConfigValue` and the actual config type. For enum types that only accepts some specific string or integer values we have to define a enum variant like `ConfigValue::IOPriority(String)`, `ConfigValue::BlobRunMode(String)`. And the variants count increase linearly with new enum types. 
By changing the type conversion interface from `Into` to `TryInfo`, we can simplify this kind of type into `ConfigValue::String`. 
Tests 
- Unit test
- No code
Side effects
```release-note
None …
```

online_config: allow return error when update config

---

components/keys/src/lib.rs
components/raftstore/src/coprocessor/split_check/half.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_check.rs
components/test_raftstore/src/cluster.rs

Issue Number: Close #12943. This is a sub-PR of https://github.com/tikv/tikv/pull/12593.
```commit-message
Support to split the region on half with the given key range.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: support to split the region on half with the given key range

---

components/raftstore/src/store/metrics.rs
components/raftstore/src/store/worker/pd.rs
metrics/grafana/tikv_details.json

Issue Number: Close #12937.
```commit-message
Add time duration metrics for the Load Base Split.
```
Tests 
- Unit test
```release-note
None.
```

metrics, pd_worker: add time duration metrics for the Load Base Split

---

Cargo.lock
metrics/grafana/tikv_details.json
src/server/metrics.rs
src/server/service/batch.rs
src/server/service/kv.rs
src/storage/mod.rs

Issue Number: Ref #12362
```commit-message
TiKV client can pass request_source through Context. It is
useful for us to know how many requests there are from each
source.
So, this commit collects the count and the total duration by
request source. The source label is not added to the command
type in order to avoid creating too many label combinations.
```
The grafana panel looks like
Tests 
```release-note
None
```

server: collect count and duration by request source

---

src/storage/mod.rs

encode ranges in raw checksum apiv2
Issue Number: Close #12950 
encode key range in raw_checksum interface
Tests 
- Unit test
Side effects
```release-note
None
```

[apiv2] encode key range in raw_checksum interface

---

components/raftstore/src/store/worker/split_config.rs
components/raftstore/src/store/worker/split_controller.rs

```commit-message
Make the gRPC poll busy check to consider the average value to make sure the check is accurate.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: make the gRPC poll busy check to consider the average value

---

components/backup-stream/src/router.rs

Issue Number: Close https://github.com/tikv/tikv/issues/12902
- Store log files by date and hour in sub directory.
- The format changed.
- The old format: "v1/20220625/t00000071/434098800931373064-f0251bd5-1441-499a-8f53-adc0d1057a73.log"
- The new format: "v1/20220625/03/t00000071/434098800931373064-f0251bd5-1441-499a-8f53-adc0d1057a73.log"
```commit-message
```
Tests 
- backup log at up-stream
- create a task for backup log with the command `br log start...`
- run ddl and dml to insert records
- create a full backup with the command `br backup full`
- restore log into down-stream
- run the PiTR restore with the command `br restore point`
- result
- the log is stored by …

log-backup: store log files by date and hour in sub directory

---

Cargo.lock
components/backup/Cargo.toml
components/backup/src/endpoint.rs
components/causal_ts/src/lib.rs
components/cdc/src/endpoint.rs
components/cdc/src/observer.rs
components/cdc/tests/mod.rs
components/server/src/server.rs
components/test_backup/src/lib.rs

Issue Number: Close #12989 
1. Flush causal timestamp before backup start for rawkv apiv2, see issue: https://github.com/tikv/migration/issues/138
2. Address review comments: https://github.com/tikv/tikv/pull/12866#discussion_r904483116
let cdc::Endpoint hold the causal ts provider instead of cdc::Observer. 
Tests 
- Unit test
Side effects
```release-note
None
```

BR: flush causal timestamp before backup start for rawkv apiv2

---

components/backup/src/endpoint.rs

Issue Number: Close #13020 
Do not fill cache when backup rawkv.
Tests 
Side effects
```release-note
None
```

Backup: Do not fill cache when backup rawkv

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/router.rs
components/backup-stream/src/subscription_manager.rs

Issue Number: ref https://github.com/tikv/tikv/issues/12902
- store log files by date/hour/store_id
- remove panic 
```commit-message
```
Tests 
- Unit test
- No code
- backup log at up-stream
- create a task for backup log with the command `br log start...`
- run ddl and dml to insert records
- create a full backup with the command `br backup full`
- restore log into down-stream
- run the PiTR restore with the command `br restore point`
- result
- the log is stored by `v1/${date}/${hour}/${storeID}/t${tableID}`
- restore successfully and data is right.
- The summary about `restore point`
[2022/07/14 …

log-backup: store log files by date/hour/store_id

---

components/raftstore/src/store/metrics.rs
components/raftstore/src/store/worker/split_controller.rs

```commit-message
Only record `UNABLE_TO_SPLIT_CPU_TOP` when the `top_cpu_usage` is not empty.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: only record UNABLE_TO_SPLIT_CPU_TOP when the top_cpu_usage is not empty

---

components/raftstore/src/store/msg.rs
components/raftstore/src/store/transport.rs

Issue Number: Close #12996
Print warning log instead of error log when sending CaptureChange message failed.
```commit-message
```
Tests 
-
Side effects
-
```release-note
None
```

raftstore: Avoid printing error log in case sending CaptureChange message failed

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/router.rs

Issue Number: ref https://github.com/tikv/tikv/issues/12895
- update global-checkpoint to storage Periodically
```commit-message
```
Tests 
- ./bin/br log status -u "X.X.X.X:2379"
● Total 1 Tasks.
> #1 <
name: store-by-storeid
status: ● NORMAL
start: 2022-07-14 20:08:03.268 +0800 CST
end: 2090-11-18 22:07:45.624 +0800 CST
storage: s3://tmp/store-by-storeid/log1
speed(est.): 0.00 ops/s
checkpoint[global]: 2022-07-17 19:36:27.418 +0800 CST; gap=1m11s
- ./bin/br log metadata -s "XXXX"
[2022/07/17 19:37:38.659 +08:00] [INFO] [collector.go:69] ["log metadata"] [log-min-ts=434582449885806593] [log-min-date="2022-07-14 20:08:03.268 +0800 CST"] [log-max-ts=434649900624904193] …

log-backup: update global-checkpoint to storage periodically

---

Cargo.lock
components/backup/Cargo.toml
components/backup/src/endpoint.rs
components/backup/src/writer.rs
components/cloud/aws/src/lib.rs
components/cloud/aws/src/s3.rs
components/external_storage/src/lib.rs
components/external_storage/src/local.rs
tests/integrations/backup/mod.rs

Signed-off-by: Gaoming <zhanggaoming028@gmail.com>
Issue Number: Close #13063
```commit-message
Adjust the backup organization structure and add a store_id related prefix under the backup path.
```
None
Tests 
- run `tiup br backup db` to backup the db to S3.
- `drop` the backup db.
- Run `tiup br restore db` to restore the backup on S3.
- Compatibility Test Case 1: Use the pre-modified `br` for backup, and the after-modified `br` for recovery.
- Compatibility Test Case 2: Use the after-modified `br` for backup, and the pre-modified `br` for recovery.
- the directory
- run `tiup br restore db` successfully.
- Compatibility Test Case 1 passed.
- Compatibility Test Case 2 passed.
```release-note
In the new backup …
```

br: Adjust the backup organization structure

---

cmd/tikv-ctl/src/main.rs
cmd/tikv-ctl/src/util.rs
components/server/src/server.rs
components/server/src/setup.rs
components/tikv_util/src/logger/mod.rs
src/config.rs
src/server/status_server/mod.rs
tests/integrations/config/mod.rs

Issue Number: ref #12986
```
- support dynamically change log level via sql
- fix a bug that can not change log level to a lower level(e.g. info --> debug)
```
The bug was introduced in #4935 as it forgot to remove the redundant call of `filter_level()` with a static level parameter.
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

log: support dynamically change log level via sql

---

components/tidb_query_datatype/src/codec/convert.rs
components/tidb_query_expr/src/impl_cast.rs

Signed-off-by: guo-shaoge <shaoge1994@163.com>
Issue Number: Close #13045
What's Changed: Make `get_valid_int_prefix()` to be compatible with TiDB, i.e. cast function needs to give error/warning when input string is like float('0.3').
Tests 
- Unit test
Side effects
```release-note
copr: fix get_valid_int_prefix() to be compatible with TiDB
```

copr: fix get_valid_int_prefix() to be compatible with TiDB(#13045)

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/metadata/client.rs
components/backup-stream/src/metadata/keys.rs
components/backup-stream/src/metadata/test.rs
components/backup-stream/src/router.rs
components/external_storage/src/local.rs

Issue Number: Close https://github.com/tikv/tikv/issues/13062
The global checkpoint-ts got by command `br log metadata` from externStorage is smaller than the value got by command `br log status` from PD server in upstream-cluster.
- The tikv-server need upload checkpoint-ts(has flushed into externStorage) to pd that can be query by `br log status`.
```commit-message
```
Tests 
- Unit test
- No code
- `br log status -u "x.x.x.x:2379"`
● Total 1 Tasks.
> #1 <
name: store-by-storeid
status: ● NORMAL
start: 2022-07-14 20:08:03.268 +0800 CST
end: 2090-11-18 22:07:45.624 …

log-backup: upload global checkpoint ts to etcd.

---

components/backup-stream/src/endpoint.rs
components/backup-stream/tests/mod.rs
etc/config-template.toml
src/config.rs
tests/integrations/config/mod.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/12895
- remove the config field `use_checkpoint_v3` 
- rename the config field `io_threads` to `work_threads`
- rename the config field `num_threads` to `scan_threads`
- rename the config `temp_file_size_limit_per_task` to `file_size_limit`
Above config items all is applied for log-backup(the new feature pitr is planed to release 6.2).
```commit-message
```
Tests 
- backup log at up-stream
- create a task for backup log with the command `br log start...`
- run ddl and dml to insert records
- create a full backup with the command `br backup full`
- restore log into down-stream
- run …

log-backup: modify the config

---

components/tikv_util/src/logger/mod.rs

Issue Number: ref #12986
```
This PR optimize the performance regression introduced by #12986 by always check global log level filter first. 
```
In my manual test, the slog thread eats up about 10% of total cpu in the cpu perf flamegraph. After this change, the slogger thread is disappeared from the flamegraph which mean the cpu cost should be trivial then.
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

log: optimize log filter

---

components/server/src/server.rs

Issue Number: Close #13055
```commit-message
ThreadTime is collected when the cpu limit in the QuotaLimiter
is not infinity.
#12679 updated the background cpu limit even if auto-tune is off,
which is unnecessary. So, that causes additional cost of collecting
thread CPU time in some critical paths.
This commit sets cpu_time_limit of the QuotaLimiter only if auto-tune
is enabled, so we don't waste effort to collect CPU time when
auto-tune is not enabled.
```
Tests 
`ThreadTime` does not appear on the flamegraph now.
```release-note
None
```

server: do not update background cpu limit when auto-tune is off

---

components/tidb_query_executors/src/runner.rs
components/tikv_util/src/quota_limiter.rs
src/config.rs
src/coprocessor/statistics/analyze.rs
src/storage/mod.rs
src/storage/txn/scheduler.rs

Signed-off-by: BornChanger <dawn_catcher@126.com>
Issue Number: Close #13084 
```
Sample build didn't check if cpu quota is from foreground or background. 
So, if either cpu quota limit is set, cpu sampling would be conducted for both 
foreground and background.  It's not expected and brought overhead.  We 
need to distinguish the cpu quota limit sources.
```
Tests 
- Unit test
Debug to make sure no such contamination any more.
```release-note
None
```

components, src: avoid cpu quota limitation contamination 

---

metrics/grafana/tikv_details.json

Issue Number: Close #13086
```
Fix the wrong expression of `Unified Read Pool CPU`
```
Tests 
- No code
Side effects
```release-note
None
```

metrics: fix a expression error of unified read pool cpu

---

components/error_code/src/pd.rs
components/pd_client/src/client.rs
components/pd_client/src/errors.rs
components/test_pd/src/mocker/service.rs
tests/integrations/pd/test_rpc_client.rs

Issue Number: Close #12934
What's Changed: the error should be  retryable error instead of unkown , this  unkown error will not retry update pd client if the sender failed. 
```commit-message
```
Tests 
Side effects
```release-note
fix the bug that the consume should be refresh if region heartbeat send failed.
```

pd-client:  pd client should update if the grpc stream sender failed.

---

Cargo.lock
components/raftstore-v2/src/batch/apply.rs
components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/bootstrap.rs
components/raftstore-v2/src/fsm/apply.rs
components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/fsm/store.rs
components/raftstore-v2/src/raft/peer.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/src/tablet.rs
components/tikv_util/src/lib.rs

Some cleaning-ups while reading the code.
- Fix the issue that `CachedTablet::latest()` always acquires lock.
- Initialize buffer capacity when creating a `ApplyPoller`.
- Remove util function `check_or_prepare_bootstrap_first_region` for more clarity.
- Minor improvements to function comments.
```commit-message
None
```
Tests 
- Unit test
```release-note
None
```

raftstorev2: fix cached tablet bug

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/store.rs
components/tikv_util/src/mpsc/mod.rs
tests/failpoints/cases/test_split_region.rs

Signed-off-by: 5kbpers <hustmh@gmail.com>
Issue Number: Close #13160
```commit-message
Use force_send to send ApplyRes
```
Tests 
- Unit test
Side effects
```release-note
Fix a bug that regions may be overlapped if raftstore is too busy
```

raftstore: use force_send to send ApplyRes

---

components/tidb_query_datatype/src/codec/collation/encoding/ascii.rs
components/tidb_query_datatype/src/codec/collation/encoding/gbk.rs
components/tidb_query_datatype/src/codec/collation/encoding/mod.rs
components/tidb_query_datatype/src/codec/collation/encoding/utf8.rs
components/tidb_query_datatype/src/codec/error.rs

Signed-off-by: xiongjiwei <xiongjiwei1996@outlook.com>
Issue Number: Close https://github.com/tikv/tikv/issues/13156
Tests 
- Unit test
- No code
```release-note
make the error message of convert charset in tikv more clear
```

charset: update the error message about can not convert error

---

components/error_code/src/pd.rs
components/pd_client/src/client.rs
components/pd_client/src/errors.rs
components/test_pd/src/mocker/service.rs
tests/integrations/pd/test_rpc_client.rs

ref issue #12934, this problem is introduced after #12827
cherry-pick #13094 to release-5.4-20220802
```release-note
fix the bug that the consume should be refresh if region heartbeat send failed.
```

pd-client: pd client should update if the grpc stream sender failed. (#13094)

---

src/server/reset_to_version.rs

Issue Number: Close #13194
judge whether `RocksWriteBatchVec` is empty
6.2  
Tests 
- Unit test
```release-note
None
```

dr-auto-sync: judge whether `RocksWriteBatchVec` is empty

---

Cargo.lock
components/backup-stream/Cargo.toml
components/backup-stream/src/endpoint.rs
components/backup-stream/src/metadata/store/lazy_etcd.rs
components/backup-stream/tests/mod.rs

Issue Number: Close #13251
This PR added timeout for some operations so we won't get stuck if there are some network issues.
Because we cannot collect enough information when log backup get stuck, we add timeout for two places:
- Every RPC call to etcd.
- The handler `on_update_global_checkpoint`. <del>(This also moved it to background.)</del>
This PR also set the `keep_alive_while_idle` for tonic. So PD won't cut down the connection with error `too many pings`.
For adding timeout for the RPCs, we need to cherry-pick some commits from newer version of the etcd client, and for http2 keep alive while idle config, we need a tiny patch, you can check the diff [here](https://github.com/etcdv3/etcd-client/compare/0.7.2...YuJuncen:etcd-client:v0.7.2-patch-extra-options?expand=1). …

log-backup: add timeout for operations that may stuck

---

components/pd_client/src/util.rs
tests/integrations/pd/test_rpc_client.rs

close tikv/tikv#13240
Issue Number: Close https://github.com/tikv/tikv/issues/13240,
```commit-message
using warn to replace panic.
```
Tests 
Side effects
```release-note
None.
```

pd-client: tikv should continue if cluster-id is zero.

---

components/pd_client/src/client.rs
components/pd_client/src/util.rs

Signed-off-by: bufferflies <1045931706@qq.com>
Issue Number: Close #13191
the RWR should be same in all os after https://github.com/rust-lang/rust/issues/93740， so the RWR deadlock   is not potential case in   linux. 
Remove `call_option` avoid to read lock double.
```commit-message
```
Tests 
- No code
TCMS Test：
https://tcms.pingcap.net/dashboard/executions/plan/1082168
Side effects
```release-note
remove call_option to avoid  deadlock(RWR).
```

pd-client:  remove `call_option` to avoid  deadlock(RWR).

---

components/raftstore-v2/src/operation/read/read.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/worker/metrics.rs
components/raftstore/src/store/worker/mod.rs
components/raftstore/src/store/worker/read.rs

Issue Number: Ref #12876 
What's Changed: Use thread-local metrics for local read to simplify code, and theoretically it reduces memory usage and improves cache locality. 
```commit-message
Use tls local read metrics
```
Tests 
- No code
```release-note
None
```

raftstore: Use thread-local metrics for local read 

---

Cargo.lock
components/backup-stream/Cargo.toml
components/backup-stream/src/event_loader.rs
components/backup-stream/tests/mod.rs

Issue Number: Close #13281 
This PR fixed a bug that may cause data loss with the satisfaction of these conditions:
- In the initial scanning stage, if...
- There are more than 1,024 adjacent keys are prewritten but not committed. 
- The values of these keys are all short enough to be inlined in the `write` CF.
("adjacent" means, the initial scanning cannot get any commit entries interleaving them, the `DeltaScanner` emits a batch with 1,024 `Prewrite`s).
- If there are some keys committed BEFORE the initial scanning but NOT YET have been observed, those key would be lost. (For a detailed case, check the integration test `split_txn`).
```commit-message
Fixed a bug that may cause data loss in log backup.
```
- Need to …

log-backup: fix early return

---

Cargo.lock
components/pd_client/src/util.rs
components/tracker/src/lib.rs
components/tracker/src/slab.rs
src/server/lock_manager/mod.rs
src/server/lock_manager/waiter_manager.rs
src/server/service/kv.rs
src/storage/lock_manager.rs
src/storage/txn/scheduler.rs
tests/integrations/server/kv_service.rs

Signed-off-by: OneSizeFitQuorum <tanxinyu@apache.org>
Issue Number: ref #12362
Depends on [pingcap/kvproto#965](https://github.com/pingcap/kvproto/pull/965). There is still some controversy about how to organize the returned metrics in the protobuf.
```commit-message
This commit record the pessimistic_lock_wait time for pessimistic transactions in the
waitManager.
```
Tests 
- Unit test
- No code
```release-note
None
```

storage: record and return pessimistic_lock_wait time

---

components/raftstore/src/store/config.rs
components/raftstore/src/store/worker/pd.rs
components/resolved_ts/tests/failpoints/mod.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/13219
Tests 
- Unit test
```release-note
dr-auto-sync: enable min-resolved-ts report by default
```

dr-auto-sync: enable min-resolved-ts report by default

---

Cargo.lock
components/causal_ts/Cargo.toml
components/causal_ts/benches/tso.rs
components/causal_ts/src/tso.rs
components/test_raftstore/src/pd.rs
components/txn_types/src/lib.rs
components/txn_types/src/timestamp.rs

Issue Number: #12794
Signed-off-by: pingyu <yuping@pingcap.com>
Issue Number: Ref #12794
```commit-message
1. Add benchmark for `causal_ts.BatchTsoProvider`.
2. Change implementation of `TestPdClient.batch_get_tso` to meet interface convention of real PD.
3. Remove "TODO" of making batch removal async for `causal_ts.TsoBatchList`.
```
This is a following PR of #12970. Its original purpose is addressing 2 TODOs ([here](https://github.com/tikv/tikv/blob/90c4a0602040102fabf45ea8e8bfac33f4472d07/components/causal_ts/src/tso.rs#L221) & [here](https://github.com/tikv/tikv/blob/90c4a0602040102fabf45ea8e8bfac33f4472d07/components/causal_ts/src/tso.rs#L257), to make some batch removal operations async and reduce latency.
However, I found that the performance has regressed. See the …

causal_ts: add benchmark

---

Cargo.lock
Cargo.toml
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/util.rs
src/server/metrics.rs
src/server/service/kv.rs
src/storage/txn/commands/mod.rs
src/storage/txn/scheduler.rs
tests/integrations/server/kv_service.rs

Issue Number: ref #13303. Should merge https://github.com/pingcap/kvproto/pull/971 before this PR being merged.
```commit-message
Implement the `kv_flashback_to_version` interface.
```
Tests 
- Unit test
```release-note
None.
```

service: add the kv_flashback_to_version interface

---

components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs

Issue Number: Close #13316
Use a manually written json path parser to parse the path.
Tests
- No code
```release-note
Fix the issue that the json path format is incompatible with MySQL
```

copr: use manually written json path parser

---

Cargo.lock
components/cloud/aws/Cargo.toml
components/cloud/aws/src/s3.rs
components/cloud/aws/src/util.rs
components/cloud/src/metrics.rs
components/tikv_util/src/stream.rs

Issue Number: Close https://github.com/tikv/tikv/issues/13122
1. In EKS environment. we shouldn't let the credential fail back. if we detected the credential provider from k8s env. and if we gets error. just retry it.
2. Add retry time to 14(about 5 mins) for all s3 interface and credentials interface. according to experience the jitter of network could be 1 min
```cloud: retry on web identity provider credentials
```
Tests 
- Unit test
- Manual test
1. create eks cluster.
2. import data.
3. make sure SA with correct role.
4. do backup check the backup succeed
5. bind SA with invalid role
6. do backup and check the error message
it …

cloud: add retry on web identity credentials

---

components/tidb_query_datatype/src/codec/mysql/json/serde.rs

Issue Number: Close #13391 
1. Change the format of json opaque serialization
2. Add more tests about it
Tests 
- No code
```release-note
Fix the issue that the serialization of opaque value is not compatible with MySQL
```

copr: fix wrong json opaque serialization

---

Cargo.lock
Cargo.toml
components/causal_ts/Cargo.toml
components/causal_ts/benches/tso.rs
components/causal_ts/src/observer.rs
components/causal_ts/src/tso.rs
components/cdc/Cargo.toml
components/cdc/src/endpoint.rs
components/cdc/tests/failpoints/test_observe.rs
components/test_pd_client/Cargo.toml
components/test_pd_client/src/lib.rs
components/test_pd_client/src/pd.rs
components/test_raftstore/Cargo.toml
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/lib.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/server.rs
components/test_raftstore/src/util.rs
tests/Cargo.toml
tests/failpoints/cases/test_bootstrap.rs
tests/failpoints/cases/test_replica_stale_read.rs
tests/failpoints/cases/test_sst_recovery.rs
tests/integrations/config/dynamic/pessimistic_txn.rs
tests/integrations/config/dynamic/raftstore.rs
tests/integrations/raftstore/test_bootstrap.rs
tests/integrations/raftstore/test_conf_change.rs

Issue Number: Close #13452 
```
`TestPdClient` is in `test_raftstore` component, which may cause circular dependency. For example, `causal_ts` need `TestPdClient`  and `test_raftstore` depend on `causal_ts`. 
Separate `TestPdClient` from `test_raftstore` component to avoid circular dependency.
```
Tests 
- Unit test
Side effects
```release-note
None
```

test: Separate TestPdClient from test_raftstore component

---

components/engine_tirocks/Cargo.toml
components/engine_tirocks/src/db_vector.rs
components/engine_tirocks/src/engine.rs
components/engine_tirocks/src/engine_iterator.rs
components/engine_tirocks/src/lib.rs
components/engine_tirocks/src/snapshot.rs
components/engine_tirocks/src/util.rs

Issue Number: Ref #13058 
```commit-message
Everything is almost the same as engine_rocks except engine_tirocks
put snapshot into an `Arc`. The old implementation is not safe as the
snapshot can be released while the iterator is still being used.
```
Tests 
- Unit test
- Manual test
```release-note
None
```

engine_tirocks: port iterator and snapshot

---

Cargo.lock
cmd/tikv-ctl/Cargo.toml
components/raft_log_engine/Cargo.toml
etc/config-template.toml
src/config.rs

Issue Number: Ref #11119
We observe on physical disk, overwriting existing log files will generate unnecessary read I/Os (1/5 of write throughput), and even though the `fdatasync` latency is reduced, the duration sum of `fdatasync` and `pwrite` has increased.
```commit-message
```
- Update release note: https://github.com/pingcap/docs-cn/pull/11115/files#r973973335
- Still enable it for TiDB cloud: https://github.com/tidbcloud/tidb-configuration/pull/1233#pullrequestreview-1111851032
- Update docs: TBD
Tests 
- Unit test
```release-note
None
```

engine: disable raft engine log recycling

---

components/server/src/server.rs

only warning in code instead of stop tikv startup.
Issue Number: Close #13497
when tikv 6.3 connect to pd 6.2, only warning in log instead of block tikv startup.
Tests 
- Unit test
1. pd 2.0 with tikv fixed branch2. 
2. start pd and then start tikv3. 
3. tikv is able to startup4. 
Side effects
```release-note
If …
```

br: recovering_mark interface block tikv startup when tikv v6.3.0 connect to pd v6.2.0

---

components/tidb_query_datatype/src/codec/error.rs
components/tidb_query_expr/src/impl_regexp.rs

Issue Number: Close https://github.com/tikv/tikv/issues/13513
Forbid empty pattern for regexp and format some error messages.
```commit-message
```
Tests 
- Unit test
Side effects
- No
```release-note
None.
```

copr: forbid empty pattern for regexp

---

components/raftstore/src/errors.rs
components/raftstore/src/store/fsm/store.rs

Issue Number: Close #13002 
```commit-message
Avoid printing the log about "region not exist but not tombstone" in error level since it may happen in normal cases and confuse users.
```
Tests 
\-
Side effects
\-
```release-note
None
```

raftstore: Do not print error log for "region not exist but not tombstone"

---

components/engine_rocks/src/misc.rs

Issue Number: Close #13534
In #13384, the `roughly_cleanup_ranges` is replaced with less optimized `delete_ranges_cfs`, causing drastic regression in TiKV startup time. This PR restores the original implementation, which is deleting files of different ranges in one batch.
```commit-message
```
- Need to update master branch
Tests 
- Unit test
```release-note
None
```

engine: batch delete files in ranges

---

src/storage/txn/actions/cleanup.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version.rs
src/storage/txn/commands/mod.rs

Issue Number: ref #13303.
```commit-message
Use `ReaderWithStats` in `flashback_to_version` command to collect the statistics info as much as possible.
```
Tests 
- Unit test
```release-note
None.
```

commands: use ReaderWithStats in flashback_to_version command

---

src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version.rs
tests/integrations/raftstore/test_flashback.rs

Issue Number: Close #13493 
```commit-message
Rollback all locks to prevent from losing the pessimistic lock in flashback
```
Tests 
- Unit test
```release-note
None
```

storage: Rollback all locks to prevent from losing the pessimistic lock in flashback

---

src/storage/mvcc/metrics.rs
src/storage/txn/actions/prewrite.rs

Issue Number: Close #13526
```commit-message
It is impossible to get blocked when acquiring a lock from the concurrency
manager when generating async-commit timestamp because the latch
already ensures there can't be race on the same key.
So, the histogram recording the duration is useless and is removed in
this commit.
```
```release-note
None
```

storage: remove histogram about locking key in prewrite

---

components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/read.rs
tests/failpoints/cases/mod.rs
tests/failpoints/cases/test_local_read.rs

Issue Number: Close #https://github.com/tikv/tikv/issues/13553
The current code encounters the case that after passing the lease check and before the acquiring the snapshot, the lease expires.
This PR fixes it by implementing SnapCacheContext which ensures the timestamp used for the lease check is generated before the snapshot acquisition.
Tests 
- Unit test
- No code
```release-note …
```

local_reader: solve the race condition when acquiring the snapshot

---

components/causal_ts/src/config.rs
components/causal_ts/src/tso.rs
components/server/src/server.rs
components/test_raftstore/src/server.rs
tests/integrations/config/mod.rs

Issue Number: #13596
Signed-off-by: pingyu <yuping@pingcap.com>
Issue Number: Close #13596 
```commit-message
Rename `causal-ts.available-interval` to `causal-ts.alloc-ahead-buffer` for more clear meaning.
```
- No
Tests 
- Unit test
Side effects
- No
```release-note
Rename `causal-ts.available-interval` to `causal-ts.alloc-ahead-buffer` for more clear meaning.
```

causal-ts: rename `available-interval` to `alloc-ahead-buffer`

---

components/raftstore/src/store/worker/read.rs

Issue Number: Close #13553
When read_id is not set, we should not use `snap_cache` as it may not be released.
Tests 
- Unit test
- No code
```release-note
None
```

local_reader: release snapshot properly

---

components/raftstore/src/store/fsm/peer.rs

Issue Number: ref #13303
```commit-message
Move `check_flashback_state` to after `check_region_epoch` to make sure the Region Cache on the client-side could be refreshed ASAP.
```
- https://github.com/tikv/client-go/pull/606.
- https://github.com/pingcap/tidb/issues/38475
Tests 
- Unit test
```release-note
None.
```

raftstore: move check_flashback_state to after check_region_epoch

---

components/raftstore/src/store/util.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/tests/failpoints/mod.rs
components/resolved_ts/tests/integrations/mod.rs
components/resolved_ts/tests/mod.rs
tests/failpoints/cases/test_replica_stale_read.rs

Signed-off-by: hehechen <awd123456sss@gmail.com>
Issue Number: Close #13353
```
Update tracked_index in 1PC scenario. If 1PC is not tracked, it may affect the accuracy of stale read after 1PC DML.
```
Tests 
- Unit test
```release-note
Update tracked_index in 1PC scenario.
```

resolved_ts: track 1PC

---

components/raftstore-v2/src/operation/query/local.rs

Issue Number: Close #13625
It fails in CI occasionally.
The main reason for it I think is the lease expires unexpectedly due to the slow execution.
This  PR change the lease from 1 sec to 10 sec and refactor the test to make less thread creation.
Tests 
- Unit test
```release-note
None
```

raftstore-v2: test_read is not stable

---

components/backup-stream/src/router.rs
components/backup-stream/src/utils.rs

Issue Number: N/A
This PR make `flush` stage of log backup using the blocking disk I/O for reading local files. This perhaps would help us get rid of the strange low performance of async disk I/O in tokio.
```commit-message
```
Tests 
```release-note
Fixed a bug that may cause log backup checkpoint lag grow too huge in the GCS external storage.
```

log-backup: using `std::fs` for reading local files

---

components/tikv_util/src/sys/cgroup.rs

Issue Number: Close #13660
```commit-message
fix panic when there are multiple cgroup2 mountinfos
```
Tests 
- Unit test
```release-note
fix panic when there are multiple cgroup2 mountinfos
```

tikv_util: fix panic when there are multiple cgroup2 mountinfos

---

src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/mod.rs

Issue Number: Close #13655 
```commit-message
Log the mvcc key if the default not error happens. Usually, the next step is to locate the key region and 
do an unsafe recovery, so mvcc key format logging is more convenient.
```
Tests 
- Unit test
Side effects
```release-note
NONE
```

mvcc: log the mvcc key if default not found error happens

---

components/raftstore-v2/Cargo.toml
components/raftstore-v2/src/fsm/apply.rs
components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/admin/conf_change.rs
components/raftstore-v2/src/operation/command/admin/mod.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/command/write/mod.rs
components/raftstore-v2/src/operation/command/write/simple_write.rs
components/raftstore-v2/src/operation/mod.rs
components/raftstore-v2/src/operation/ready/async_writer.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/raft/apply.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/src/router/internal_message.rs
components/raftstore-v2/src/router/message.rs
components/raftstore-v2/src/router/mod.rs
components/raftstore-v2/src/router/response_channel.rs
components/raftstore-v2/tests/failpoints/test_basic_write.rs
components/raftstore-v2/tests/integrations/cluster.rs
components/raftstore-v2/tests/integrations/mod.rs
components/raftstore-v2/tests/integrations/test_basic_write.rs
components/raftstore-v2/tests/integrations/test_conf_change.rs
components/raftstore-v2/tests/integrations/test_read.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/region_meta.rs
components/raftstore/src/store/util.rs
tests/integrations/raftstore/test_replication_mode.rs

```commit-message
Most workflow is the same as v1 except if apply failed, v2 will not return apply result
back to raftstore. This behavior is a legacy behavior that only works for conf change
before joint consensus and can be removed now.
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: support conf change

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/util.rs
components/test_raftstore/src/cluster.rs
tests/integrations/raftstore/test_flashback.rs

Issue Number: Close #13643.
```commit-message
* Use `self.region` while executing `PrepareFlashback` command to ensure it gets the latest region meta.
* Check the epoch before executing the `PrepareFlashback`.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: make sure PrepareFlashback will get the latest region meta

---

src/coprocessor_v2/plugin_registry.rs

Issue Number: Close #13708
```commit-message
This commit fixes test `registry_unload_plugin`. The test has been failing
since the example crate renamed its name in #13585.
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

coprocessor_v2: fix incorrect shared library name

---

src/storage/lock_manager/lock_waiting_queue.rs
src/storage/txn/scheduler.rs

Issue Number: Close #13692
```commit-message
Optimize CPU usage of waking up.
1. When popped entries are empty in `on_release_locks`, do not do anything in the high priority pool. This seems to be the reason of the performance regression mentioned in #13692 .
2. Skip waking up if the `LockWaitQueues` is empty.
```
-
Tests 
- Unit test
Side effects
-
```release-note
None
```

scheduler: Optimize CPU usage of waking up

---

src/storage/mvcc/reader/scanner/forward.rs
src/storage/txn/actions/acquire_pessimistic_lock.rs
src/storage/txn/sched_pool.rs
src/storage/txn/scheduler.rs

```commit-message
Some old versions or components (TiKV < 5.0, TiFlash) cannot handle
unknown fields in Lock and Write. To avoid causing unexpected
problems, we add a feature gate to the new field.
We are not going to release this feature in TiKV 6.4, so I directly set
the minimal version to 6.5.
```
Tests 
- Unit test
```release-note
None
```

txn: set last_change_ts only on 6.5+ versions

---

CHANGELOG.md

Issue Number: close #13720
TiDB CHANGELOG.md has been removed via https://github.com/pingcap/tidb/pull/34369 then the current link shows 404.
Tests 
- No code
Side effects
```
None
```

*: Fix link to TiDB Release Notes

---

src/storage/mod.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs

Issue Number: Close #13743.
```commit-message
The original thought is that when a key's latest MVCC record type is DELETE and the corresponding flashback operation is also DELETE, we skip it to avoid duplicated writing.
However, this will cause the flashback to fall into a dead loop since the key doesn't have the written record with the flashback `commit_ts` and the flashback will always try to write it forever.
```
Tests 
- Unit test
```release-note
None.
```

storage: fix the flashback dead loop caused by a deleted key

---

src/storage/mvcc/reader/scanner/forward.rs
src/storage/txn/actions/prewrite.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/store.rs

```commit-message
This commit implements the different cases when last_change_ts
is calculated in prewrite:
1. Inherit from the pessimistic lock
2. Calculate it when checking the new version
3. Amend the pessimistic lock
```
Tests 
- Unit test
```release-note
None
```

storage: calculate last_change_ts in prewrite

---

Cargo.lock

Issue Number: Close https://github.com/tikv/tikv/issues/13751
1. update cargo.lock for rusoto.
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

backup: udpate rusoto to support backup to ap-southeast-3

---

src/server/debug.rs

Issue Number: Close #13515
Moves the function `get_db_from_type` in `Debugger` to a trait, and the tikv instance using Rocksdb as the raftlog backend is specially implemented, so that the compact raft db no longer reports errors.
Maybe I need to explain the following background: In the previous version, according to the description of tikv ctl tool in the official TIDB document, we can manually compact raftdb through the following instructions：
`./tikv-ctl  --host localhost:port compact -d raft`
However, after a version of 5. x, it can no longer be used ,even if we use Rocksdb instead of RaftEngine.
`DebugClient::compact: RpcFailure: 2-UNKNOWN "[src/server/debug.rs:169]: Get raft db is not allowed"`
The reason is that in order to support RaftEngine as an optional raftlog …

debugger: fix compacting raftdb with tikv-ctl

---

src/config.rs
tests/integrations/config/mod.rs

Issue Number: Close #13761 
```commit-message
raw-min-ts-outlier-threshold is marked as deprecated from v6.4. It should be removed from v6.5.
https://docs.pingcap.com/zh/tidb/dev/tikv-configuration-file#raw-min-ts-outlier-threshold-%E4%BB%8E-v620-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5
```
Tests 
- Unit test
Side effects
```release-note
None
```

cdc: remove deprecated config

---

src/storage/txn/actions/check_txn_status.rs
src/storage/txn/commands/check_secondary_locks.rs
src/storage/txn/commands/check_txn_status.rs

```commit-message
This commit supports calculating last_change_ts when writing a new
Rollback record.
To get the correct last_change_ts, we always call seek_write to find the
last write record before start_ts.
```
Tests 
- Unit test
```release-note
None
```

storage: calculate last_change_ts in rollback

---

src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/txn/actions/commit.rs
src/storage/txn/actions/prewrite.rs
src/storage/txn/commands/prewrite.rs

Only a one-line change to the code :)
```commit-message
In this commit, the commit action will save the last_change_ts and
versions_to_last_change in the lock to the write record.
It is unncessary to check the write type because it is checked during prewrite.
So, among the committable locks, only those of Lock type will have
last_change_ts and versions_to_last_change.
```
Tests 
- Unit test
```release-note
None
```

txn: save last change info in write records

---

components/tidb_query_datatype/src/codec/collation/charset.rs
components/tidb_query_datatype/src/codec/collation/mod.rs
components/tidb_query_expr/src/impl_like.rs
components/tidb_query_expr/src/lib.rs

Issue Number: Close https://github.com/tikv/tikv/issues/13769
This PR is a rework for https://github.com/tikv/tikv/pull/13770. As I have force-pushed the branch, github doesn't allow me to reopen the old one :cry: .
If the two charset of arguments are equal, use the charset from arguments to decode the bytes.
I have considered the following cases:
| Ret Collation  | First Arg Charset | Second Arg Charset | Description |
| ------------- | ------------- |------------- |------------- |
| binary  | binary  | binary | It works normally |
| binary  | utf8mb4  | binary | It happened when TiDB didn't push down the collation information. Just decode and compare the string byte by byte. A `_` in pattern will only match one byte in the …

copr: fix _ pattern in like behavior for old collation

---

Cargo.lock
Cargo.toml

Issue: bump version to 5.3.4
What's Changed: version in cargo.toml is 5.3.4
Tests 
Side effects

bump version to 5.3.4

---

Cargo.lock

Issue Number: Close #13815
```commit-message
According to https://github.com/crossbeam-rs/crossbeam/pull/835, spinning at the
sending side is probably a bad idea because of large critical section and it's
fixed in the recent version.
This commit updates crossbeam-channel. It will reduce CPU usage a bit and
improve performance.
```
Spinlock vs mutex is really tricky. Generally, using a mutex is never a bad idea but sometimes spinning improves performance. But in this case, our benchbot doesn't support spinning.
I did A-B-A (where A uses latest crossbeam-channel) tests, the one with latest crossbeam-channel wins consistently.
Tests 
```release-note
None
```

*: update crossbeam-channel to avoid spin at sending side

---

Cargo.lock
components/txn_types/src/lock.rs
components/txn_types/src/write.rs
src/storage/mvcc/mod.rs
src/storage/txn/actions/commit.rs
src/storage/txn/actions/prewrite.rs
src/storage/txn/actions/tests.rs
src/storage/txn/commands/prewrite.rs

Signed-off-by: xiongjiwei <xiongjiwei1996@outlook.com>
Issue Number: ref https://github.com/tikv/tikv/issues/13779
we use `u64` to reserve more space for future use. For now, the upper application is limited to setting this value under `0x80`, so there will no more cost to change it to `u64`
```commit-message
```
Tests 
- Unit test
```release-note
None
```

txn: make `txn_source` be u64 type

---

components/tikv_kv/src/lib.rs
components/tikv_util/src/sys/mod.rs
src/server/raftkv.rs
src/server/service/kv.rs

Issue Number: Ref #13827
```commit-message
flashback is a transaction concept, better make it only interact with
the storage layer instead of raftstore directly.
This PR also converts raftstore errors to region errors for flashback,
so it will can make client retry more reliable.
```
Tests 
- Unit test
```release-note
None
```

*: make flashback not aware of raftstore router

---

src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/txn/actions/check_txn_status.rs
src/storage/txn/commands/check_secondary_locks.rs
src/storage/txn/commands/check_txn_status.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/13694
```commit-message
This commit reverts #13749 (calculate last_change_ts in rollback).
If we calculate last_change_ts, consider the following case:
Key k has a write record with commit_ts = 5.
1. Prewrite k, start_ts = 10
2. Rollback k, start_ts = 30, last_commit_ts = 5.
3. Commit k, start_ts = 10, commit_ts = 20
Then, read with ts = 40, it will get an incorrect last_commit_ts from
the rollback record.
There is no easy way to handle the rollback case. I choose to give up
calculating it.
```
Tests 
- Unit test
```release-note
None
```

txn: revert "calculate last_change_ts in rollback"

---

components/txn_types/src/lock.rs
components/txn_types/src/write.rs
src/storage/mod.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/txn/actions/acquire_pessimistic_lock.rs
src/storage/txn/actions/prewrite.rs

```commit-message
For non-existing keys, we will record last_change_ts as 0 and set a non-zero
versions_to_last_change. So, if we encounter such a write record when reading,
we can quickly know this key does not exist.
```
Tests 
- TODO
```release-note
None
```

storage: skip accumulated locks on non-existing keys

---

components/cdc/src/old_value.rs
components/tikv_kv/src/cursor.rs
components/tikv_kv/src/lib.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/mod.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs

Issue Number: ref #13800.
```commit-message
Introduce `hint_min_ts` during the flashback progress to only flashback those keys that have version changed as much as possible.
```
Tests 
- Unit test
```release-note
None.
```

storage: introduce hint_min_ts to speed up the flashback progress

---

src/coprocessor/endpoint.rs
tests/integrations/coprocessor/test_select.rs

Issue Number: Close #13856 
```commit-message
Fill the batch task response error field properly, the error field should be None if no error happens.
```
Tests 
- Unit test
Side effects
```release-note
None
```

cop: set the error field properly for the batch cop task response

---

src/coprocessor/endpoint.rs

Issue Number: Ref #13858 
```commit-message
Disable the coprocessor cache path for the batched task processing, the derived 
fields from the original task could not be used by the batched tasks.
```
Tests 
- Unit test
Side effects
```release-note
None
```

cop: disable the coprocessor cache path for batched task processing

---

Cargo.lock
components/raftstore/src/store/region_meta.rs
components/server/src/server.rs
components/test_raftstore/src/server.rs
components/test_storage/src/sync_storage.rs
components/tikv_kv/Cargo.toml
components/tikv_kv/src/lib.rs
components/tikv_kv/src/mock_engine.rs
components/tikv_kv/src/raft_extension.rs
components/tikv_kv/src/rocksdb_engine.rs
src/server/gc_worker/gc_worker.rs
src/server/raft_client.rs
src/server/raftkv/mod.rs
src/server/raftkv/raft_extension.rs
src/server/resolve.rs
src/server/server.rs
src/server/service/debug.rs
src/server/service/kv.rs
src/server/snap.rs
src/server/tablet_snap.rs
src/server/transport.rs
tests/failpoints/cases/test_gc_metrics.rs
tests/integrations/config/dynamic/gc_worker.rs
tests/integrations/config/dynamic/snap.rs
tests/integrations/server/raft_client.rs

Issue Number: Ref #13827
```commit-message
So anything related to raft will call raft extension instead of router.
This makes it easier to introduce new raftstore implementations.
```
Tests 
- Unit test
```release-note
None
```

tikv_kv: introduce raft extension

---

components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs
src/storage/mvcc/reader/reader.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs
tests/integrations/server/kv_service.rs

Issue Number: Close #13861  Close https://github.com/pingcap/tiflash/issues/6379 Ref #13800 
```commit-message
SnapshotReader typically uses its own start_ts for something. Since it doesn't need the start_ts of SnapshotReader itself,  
we can unify the reader into MvccReader.
And the start key from the client is actually a range, which is used to limit the upper bound of this flashback when scanning data, so it may not be a real key.
```
Tests 
- Unit test
```release-note
None
```

storage: Unify the flashback reader and fix the start_key bug

---

src/coprocessor/endpoint.rs
src/server/lock_manager/mod.rs
src/server/lock_manager/waiter_manager.rs
src/storage/lock_manager/lock_wait_context.rs
src/storage/lock_manager/lock_waiting_queue.rs
src/storage/lock_manager/mod.rs
src/storage/mod.rs
src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs
src/storage/txn/commands/mod.rs
src/storage/txn/scheduler.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/coprocessor/test_select.rs

Issue Number: Close #13298
```commit-message
scheduler/lock_manager: Handle the corner case that resumable pessimstic lock request is pushed to queue after cancelling.
When a lock-waiting request is woken up and continues its execution, in some cases it's possible that it encounters other transaction's lock agian. In this case, the entry will be put to the lock waiting queue again. However, there might be problem when LockManager tries to cancel the request (due to timeout or other possible errors. This PR handles this case.
```
The detailed time-sequence of this corner case is explained in the comments in the code.
There's also some fixes to the previously merged code.
\-
Tests 
- Unit test
Side effects …

scheduler/lock_manager: Handle the corner case that resumable pessimstic lock request is pushed to queue after cancelling

---

Cargo.lock
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/util.rs
components/raftstore/src/store/worker/read.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs
tests/integrations/raftstore/test_flashback.rs
tests/integrations/server/kv_service.rs

Issue Number: Close #13870.
```commit-message
Because the flashback read request must be proposed after the `PrepareFlashback`
and it won't have any side effects, it's safe to allow a read-only flashback request to
be proposed. In this way, we can also fix #13870.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: allow a read-only flashback request to be propsed

---

src/import/sst_service.rs

Signed-off-by: hillium <yujuncen@pingcap.com>
Issue Number: Close #13874 
This PR made a block thread pool and executes PITR tasks in it for workaround the panic in tokio.
```commit-message
```
Tests 
```release-note
None
```

log_backup: fix pitr panic

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs
tests/integrations/raftstore/test_flashback.rs
tests/integrations/server/kv_service.rs

Issue Number: Close #13868.
```commit-message
- Remove `is_in_flashback` field and use the region meta as the only source of truth in `PeerFSM`.
- Add a corresponding test case.
- Some minor refinement to the code and tests.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: remove is_in_flashback field in peer fsm

---

components/engine_panic/src/raft_engine.rs
components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/raft_engine.rs
components/raft_log_engine/src/engine.rs
components/raftstore-v2/src/bootstrap.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/snap.rs
components/server/src/raft_engine_switch.rs
src/server/debug.rs
tests/integrations/server/kv_service.rs

```commit-message
These methods are defined in log batch already, redefine them again
introduce unnecessary maintenance. And these methods are also
confusing as they don't sync by default, which is very easy to make
mistake.
```
Tests 
- Unit test
```release-note
None
```

raft_engine: remove redundant methods

---

components/backup/src/endpoint.rs
components/raftstore/src/store/fsm/peer.rs
components/tikv_kv/src/lib.rs
components/txn_types/src/types.rs
src/coprocessor/endpoint.rs
src/coprocessor/mod.rs
src/server/raftkv/mod.rs
src/storage/txn/commands/acquire_pessimistic_lock.rs
src/storage/txn/commands/flashback_to_version.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/scheduler.rs
tests/integrations/backup/mod.rs
tests/integrations/raftstore/test_flashback.rs

Issue Number: ref #13787, close https://github.com/pingcap/tidb/issues/39639.
```commit-message
- Allow to backup during the flashback by passing the flashback flag.
- Allow the checksum request to get the snapshot during the flashback progress.
```
Tests 
- Unit test
```release-note
None.
```

backup: allow to backup during the flashback

---

cmd/tikv-ctl/src/executor.rs
components/engine_rocks/src/engine.rs
components/engine_rocks/src/rocks_metrics.rs
components/server/src/raft_engine_switch.rs
components/server/src/server.rs
components/snap_recovery/src/init_cluster.rs
components/test_raftstore/src/common-test.toml
components/test_raftstore/src/util.rs
components/tikv_kv/src/rocksdb_engine.rs
etc/config-template.toml
src/config.rs
src/server/engine_factory.rs
src/server/engine_factory_v2.rs
src/storage/config.rs
src/storage/config_manager.rs
src/storage/kv/test_engine_builder.rs
src/storage/mod.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: Close #12936
There has been 5 months and nobody objects it so let's always enable share block cache.
```commit-message
```
https://github.com/pingcap/docs-cn/pull/12241
Tests 
- Unit test
Side effects
Use separate cache for each CF is not supported anymore.
```release-note
remove the support of specifying separate cache for each CF
```

*: always share block cache

---

src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/mod.rs
tests/failpoints/cases/test_table_properties.rs

Signed-off-by: hillium <yu745514916@live.com>
Issue Number: Close #13909
This PR allows GC to be skipped once the `ratio_threshold` is negative or infinity.
Disabling GC is useful in some abnormal scenarios where the transaction model would be break (e.g. writes with higher commit TS would be written BEFORE writes with lower commit TS, or write data with TS lower than current GC safe point).
Mainly, this is for fixing the data inconsistent found at https://github.com/pingcap/tidb/issues/39602: because PITR would apply unordered writes concurrently, once there are some delete records, GC might ripe them and make the write records (which haven't been restored yet) lives.
```commit-message
GC would be skipped once the `ratio_threshold` is negative or infinity.
```
Tests 
- …

gc_worker: disable gc if have negative ratio

---

components/backup-stream/src/checkpoint_manager.rs
components/backup-stream/src/endpoint.rs
components/backup-stream/src/metadata/client.rs
components/backup-stream/src/metadata/mod.rs
components/backup-stream/src/metadata/store/lazy_etcd.rs
components/backup-stream/src/metadata/test.rs
src/import/sst_service.rs

Issue Number: Close https://github.com/tikv/tikv/issues/13898
Retry to `get tasks` with `etcd-cli` from `etcd` when TiKV starts on the tokio background thread.
```commit-message
```
Tests 
Side effects
```release-note
Retry to get tasks with etcd-cli from etcd when TiKV starts, which fix issues%13898
```

log-backup：Retry to get tasks with etcd-cli from etcd when TiKV starts.

---

Cargo.lock
components/engine_panic/src/raft_engine.rs
components/engine_rocks/src/engine.rs
components/engine_rocks/src/event_listener.rs
components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/flush.rs
components/engine_traits/src/lib.rs
components/engine_traits/src/raft_engine.rs
components/raft_log_engine/Cargo.toml
components/raft_log_engine/src/engine.rs
components/raft_log_engine/src/lib.rs
components/raftstore-v2/src/operation/life.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/tests/integrations/test_life.rs
components/raftstore/src/store/async_io/write.rs
components/raftstore/src/store/async_io/write_tests.rs

```commit-message
Flush state is used to trace persisted apply index. This is the first
PR to remove WAL for raftstore v2.
```
You can checkout the full changes in [here](https://github.com/tikv/tikv/compare/master...BusyJay:tikv:remove-wal-for-v2?expand=1).
Tests 
- Unit test
```release-note
None
```

engine_trait: introduce flush state

---

Cargo.lock
components/raftstore-v2/Cargo.toml
components/raftstore-v2/src/operation/command/admin/split.rs

```
strip ts from split keys before propose
```
Tests 
- Unit test
```release-note
None
```

ratstore-v2: strip ts from split keys before propose

---

components/snap_recovery/src/init_cluster.rs

Issue Number: Close #13955
```commit-message
fix: enlarge the raft client backoff in recovery mode since ebs restore volume very poor during restor
```
Tests 
- Unit test
1. following the instruction https://docs.pingcap.com/zh/tidb-in-kubernetes/v1.4/backup-to-aws-s3-by-snapshot to create a cluster
2. specify 80 tikv nodes, 3 pd and 3 tidb
3. create backup
4. following https://docs.pingcap.com/zh/tidb-in-kubernetes/v1.4/restore-from-aws-s3-by-snapshot to restore the cluster
5. restore success
- No code
Side effects
- Consumes more MEM 
- Breaking backward …

br: enlarge the raft client backoff in recovery mode since ebs restore volume very poor during restore

---

components/backup-stream/src/metadata/store/lazy_etcd.rs

Issue Number: Close #13959
This PR sets [`X509_V_FLAG_PARTIAL_CHAIN`](https://man.openbsd.org/X509_VERIFY_PARAM_set_flags.3#VERIFICATION_FLAGS), so we would trust the CA even there isn't a root CA provided.
Given the CA file is provided by the user, I think it should be fully trusted. Also note that the `grpc-io` library sets this flag by default.
```commit-message
This PR sets X509_V_FLAG_PARTIAL_CHAIN, so we would trust the CA even there isn't a root CA provided.
```
Tests 
We made a binary for testing this, this is the code snippet:
```rust
let cfg = Config::parse();
let security_mgr = Arc::new(
SecurityManager::new(&cfg.clone().into()).expect("failed to create security manager."),
);
println!("using config = {:?}", …
```

log-backup: make PITR available when using partial cert chain

---

src/storage/mod.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs
tests/integrations/server/kv_service.rs

Issue Number: Close #13958
```commit-message
Since the rollback ts for flashback are derived from the ts of the lock, we wrote prewrite lock which start_ts is flashback in Prewrite Phase. 
So the Prewrite lock we wrote in the flashback was rollbacked when we retry prepare. 
This introduces the case mentioned in https://github.com/tikv/tikv/issues/13958
The solution is: if such a lock exists, skip it and go to the Commit Phase.
```
Tests 
- Unit test
```release-note
None
```

Skip write `prewrite_lock` in flashback locks

---

Cargo.lock
cmd/tikv-server/src/main.rs
components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/lib.rs
components/raftstore-v2/src/worker/pd/mod.rs
components/raftstore-v2/src/worker/pd/update_max_timestamp.rs
components/raftstore-v2/tests/integrations/cluster.rs
components/raftstore/src/store/snap.rs
components/server/Cargo.toml
components/server/src/lib.rs
components/server/src/server.rs
components/server/src/server2.rs
components/server/src/server_rn.rs
components/test_raftstore/src/server.rs
components/tikv_util/src/sys/mod.rs
src/server/raftkv2/node.rs
src/server/server.rs
src/server/service/kv.rs
src/server/status_server/mod.rs
tests/integrations/server/status_server.rs

This PR enables start raftkv2 by introducing a new module named server2.rs.
server2.rs is just copied and adjusted from server.rs. For now, I avoid
edit server.rs in place in case introducing bad problems. In the long term,
perhaps next month, I will merge server.rs with server2.rs.
To make review easier, I rename server.rs to server_rn.rs, and server2.rs to server.rs.
So github can display what's missing and changed in server2. I will revert the naming
before merging.
```commit-message
Not all functionality are supported, this is just a naive pure
KV system with transaction support.
```
Tests 
- Unit test
```release-note
None
```

*: support start with raftkv2

---

components/raftstore-v2/src/fsm/apply.rs
components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/command/write/mod.rs
components/raftstore-v2/src/router/internal_message.rs
components/raftstore-v2/src/router/message.rs
src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/gc_worker.rs
src/server/gc_worker/rawkv_compaction_filter.rs
src/server/raftkv2/mod.rs
tests/failpoints/cases/test_gc_worker.rs

```commit-message
We rely on non-concurrent memtable write for dynamic regions to
achieve best performance. This PR makes sure writes of compaction
filter be redirected to apply thread when dynamic regions is enabled.
The solution may miss data if TiKV crashes before writes are flushed
to disk. Note even for v1, it's also possible to leave garbage if writes
to rocksdb fail. We need to scan default CFs and check for orphan
versions.
```
Tests 
- Unit test
```release-note
None
```

*: make gc not write db directly

---

components/cdc/src/observer.rs
components/engine_rocks/src/rocks_metrics.rs
components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/tests/integrations/cluster.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/coprocessor/region_info_accessor.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/snap.rs
components/server/src/server2.rs
src/config/mod.rs
src/coprocessor/tracker.rs
src/server/service/kv.rs
src/server/tablet_snap.rs
src/storage/metrics.rs

```commit-message
Perf context is disabled for now as we don't have shared kv engine.
And fix region info access panic by filter out uninitialized role change.
There are also several other fixes.
```
Tests 
- Unit test
- Manual test
tiup playground
```release-note
None
```

v2: fix several panics

---

components/engine_rocks/src/event_listener.rs
components/engine_traits/src/flush.rs
components/engine_traits/src/tablet.rs
components/raftstore-v2/src/fsm/apply.rs
components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/admin/compact_log.rs
components/raftstore-v2/src/operation/command/admin/conf_change.rs
components/raftstore-v2/src/operation/command/admin/mod.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/command/control.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/ready/apply_trace.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/operation/ready/snapshot.rs
components/raftstore-v2/src/raft/apply.rs
components/raftstore-v2/src/raft/peer.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/src/router/internal_message.rs
components/raftstore-v2/tests/integrations/test_transfer_leader.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/snap.rs
components/server/src/server2.rs
src/config/mod.rs
src/server/raftkv2/node.rs

```commit-message
Whenever timeout, the peer will check for unapplied logs whether
there are pending conf change and trigger heavy reads. So we
wait till most logs are applied before ticking.
It also fix following issues:
- PersistenceListener is not installed
- implementation of persisted_apply_index is wrong
- parse tablet name is wrong
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: avoid ticking when there are many unapplied logs

---

components/engine_panic/src/raft_engine.rs
components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/raft_engine.rs
components/raft_log_engine/src/engine.rs
components/raftstore-v2/src/operation/life.rs
components/raftstore-v2/src/operation/ready/snapshot.rs
components/raftstore/src/store/async_io/write.rs
components/raftstore/src/store/async_io/write_tests.rs
components/raftstore/src/store/entry_storage.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/snap.rs
components/raftstore/src/store/worker/raftlog_gc.rs
components/server/src/raft_engine_switch.rs
tests/integrations/server/kv_service.rs

```commit-message
The API is supposed to be used with `append` but nowhere can we find
the clue. This PR merges `cut_logs` and `append` to reduce confusion
and mistakes.
```
Tests 
- Unit test
```release-note
None
```

raft-engine: remove confusing API cut logs

---

components/engine_panic/src/raft_engine.rs
components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/raft_engine.rs
components/raft_log_engine/src/engine.rs
components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/operation/ready/snapshot.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/src/router/message.rs
components/raftstore-v2/src/worker/tablet_gc.rs

```commit-message
When the tablet contains dirty data right after split, generating snapshot may
just a waste. On the other hand, split usually happens on all peers, so delay
it a bit actually makes all peers more likely to be initialized by split. So
this PR rejects generating snapshot when it detects it still has dirty data.
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: only send clean snapshot

---

components/tikv_util/src/sys/mod.rs
src/server/service/diagnostics/sys.rs

Signed-off-by: Wish <breezewish@outlook.com>
Issue Number: Close https://github.com/tikv/tikv/issues/14033
In https://github.com/tikv/tikv/pull/13385 we upgraded [sysinfo](https://crates.io/crates/sysinfo) dependency from 0.16.4 to 0.26.5.
However, Sysinfo [returns memory in KBs in 0.16.4](https://docs.rs/sysinfo/0.16.4/sysinfo/trait.SystemExt.html#tymethod.get_total_memory) but [returns memory in bytes in 0.26.5](https://docs.rs/sysinfo/0.26.5/sysinfo/trait.SystemExt.html#tymethod.total_memory). This lead to very large default block cache size, causes OOM.
```commit-message
```
Tests 
```release-note
None
```

util: Fix incorrect memory capacity

---

src/storage/txn/actions/acquire_pessimistic_lock.rs

Issue Number: Close #14038 
Close https://github.com/pingcap/tidb/issues/40114
```commit-message
Fixes the problem that when handling repeated acquire_pessimistic_lock requests is recevied, should_not_exist is ignored. 
TiKV provides idempotency for these RPC requests, but for acquire_pessimistic_lock, it ignored the possibility that the client may expect a pessimistic_rollback between two acquire_pessimistic_lock request on the same key. In this case the second request may come from another statement and carries `should_not_exist` that wasn't set in the previously finished pessimistic lock request. If the first request successfully acquired the lock and the pessimistic_rollback failed, TiKV may return a sucessful response, making the client believe that the key doesn't …
```

txn: Do constraint check when handling repeated acqurie_pessimsitic_lock request

---

components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
tests/failpoints/cases/test_witness.rs
tests/integrations/config/mod.rs

ref tikv/tikv#12876
Issue Number: ref #12876 
- Fix panic caused by not initialize `apply_ctx.timer`, the `ApplyPoller` releases the ownership of `ApplyFsm` after skip flushing, and the other `ApplyPoller` gets this `ApplyFsm` then updates `applied_index` and `flush` first, causing the applied index to flip.
- Refactor the logic of notifying the raftstore thread. In the previous method, after calling `finish_for` (which will update the `apply_ctx.applied_res` array), explicitly call `notify_one` to notify `raftstore`, resulting in redundant notifications. Now the notification is done uniformly through `apply_ctx.applied_res`.
- Added a separate configuration to control the interval of request voter_replicated_index …

apply: fix witness raft log gc panic and refactor

---

Cargo.lock
components/error_code/src/pd.rs
components/pd_client/src/client.rs
components/pd_client/src/client_v2.rs
components/pd_client/src/errors.rs
components/pd_client/src/util.rs
components/resource_control/src/resource_group.rs
etc/error_code.toml

Issue Number: Close #14063
```commit-message
make sure kvproto compatibility
```
Tests 
- Unit test
```release-note
None
```

pd_client: fix the kvproto compatibility

---

components/backup-stream/src/metadata/store/lazy_etcd.rs
components/security/src/lib.rs
components/server/src/server.rs

Signed-off-by: hillium <yujuncen@pingcap.com>
Issue Number: Close #14071 
This PR have modified the `LazyEtcd` and made it checks the TLS certification every time when retrieving the client.
Once it find the TLS certification has been modified, it would reconnect to the server.
```commit-message
Log backup would aware TLS certifications changing.
```
It is integrated with etcd, hence hard to make unit tests.
The manual test creates a cluster where *TLS certifications are reloaded every 5 mins* and *all TLS certification lives for 10 mins*.
with the script:
```bash
#! /bin/bash
set -eu
lib=${lib:-/root/lovecloudnative/scripts}
out=${out:-/root/lovecloudnative/ssl} …
```

log-backup: an ad-hoc way for hot reloading TLS certs

---

Cargo.lock
components/tidb_query_executors/src/runner.rs
components/tidb_query_expr/src/impl_op.rs
components/tidb_query_expr/src/lib.rs

Issue Number: Close #14069
Implement the `UnaryNotJSON` defined in https://github.com/pingcap/tipb/pull/289
Related TiDB Implementation: https://github.com/pingcap/tidb/pull/40723
Tests 
- No code
```release-note
Fix the issue that unary not for json value is incompatible with MySQL.
```

json, copr: implement unary not for json

---

components/backup-stream/src/metadata/store/lazy_etcd.rs
components/security/src/lib.rs
components/server/src/server.rs

Signed-off-by: hillium <yujuncen@pingcap.com>
Issue Number: Close #14071 
This PR have modified the `LazyEtcd` and made it checks the TLS certification every time when retrieving the client.
Once it find the TLS certification has been modified, it would reconnect to the server.
```commit-message
Log backup would aware TLS certifications changing.
```
It is integrated with etcd, hence hard to make unit tests.
The manual test creates a cluster where *TLS certifications are reloaded every 5 mins* and *all TLS certification lives for 10 mins*.
with the script:
```bash
#! /bin/bash
set -eu
lib=${lib:-/root/lovecloudnative/scripts}
out=${out:-/root/lovecloudnative/ssl} …
```

log_backup: Cherry pick 14072 to release 6.5

---

components/raftstore/src/store/config.rs
src/config/mod.rs

Issue Number: Close #13586, Close #13752, Ref #14017
What's Changed: Allow starting TiKV nodes with <1 CPU.
Before this change even starting a TiKV node with 0.999 CPU would fail because of rounding.
Tests
- Manual test: started on k8s with 0.3 CPU
```release-note
Bug fix: Allow starting TiKV nodes with <1 CPU
```

config: allow starting TiKV nodes with <1 CPU

---

Cargo.lock
Cargo.toml
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/util.rs
components/raftstore/src/store/worker/read.rs
components/test_raftstore/src/util.rs
components/tikv_kv/src/lib.rs
src/server/raftkv/mod.rs
src/server/raftkv2/mod.rs
src/server/service/kv.rs
tests/integrations/server/kv_service.rs

Issue Number: close #14045. Should merge after https://github.com/pingcap/kvproto/pull/1048.
```commit-message
- Store the flashback `start_ts` in region meta.
- Allow the read request with a smaller ts during flashback.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: allow the read request with a smaller ts during flashback

---

etc/config-template.toml
src/config/mod.rs

Signed-off-by: Qi Xu <tonyxuqqi@outlook.com>
Issue Number: Close #14052
```commit-message
The writecf and defaultcf's default block size is changed to 16KB to improve read performance (reduce read amplification)
```
Tests 
- Unit test
- No code
Side effects
- Consumes more IOPS
```release-note
Change the default value of rocksdb's defaultcf and write fc's SST block size from 64KB to 16KB. 
This change can improve read performance by reducing read amplification and improve the block cache utilization, at the cost of needing more IOPS. It's estimated to …
```

rocksdb: reduce rocksdb block size to 16KB

---

components/raftstore-v2/src/fsm/store.rs
components/raftstore-v2/src/operation/life.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/operation/ready/snapshot.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/src/router/message.rs
components/raftstore-v2/tests/integrations/cluster.rs
components/raftstore-v2/tests/integrations/test_conf_change.rs
components/raftstore/src/store/async_io/read.rs

```commit-message
If it accepts more logs than conf remove itself, applied_index == commit_index
will never be true. So we should check if it's a tombstone already first.
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: fix peer not cleanup when it replicates more logs

---

src/coprocessor/endpoint.rs
tests/integrations/coprocessor/test_select.rs

Issue Number: Close #14109
```
Handle the scan details which are mistakenly discarded before.
```
Tests 
- Unit test
Run a 1,000 rows query in TiDB, check the scan details:
- Before: `scan_detail: {total_process_keys: 91...}`
- After: `scan_detail: {total_process_keys: 1000...}`
Side effects
```release-note
None
```

cop: handle unset scan details in store batch

---

Cargo.lock
cmd/tikv-ctl/src/main.rs
components/engine_rocks/src/logger.rs
components/raft_log_engine/src/engine.rs
components/raftstore-v2/src/operation/ready/mod.rs
src/config/mod.rs
src/server/engine_factory.rs
tests/integrations/storage/test_titan.rs

Issue Number: Ref #12842  
```commit-message
- Update raft-engine to fix data corruption during restart
- Add tablet logger so we can know which tablet the logs belongs to
```
Tests 
- Unit test
Side effects
If a cluster is upgraded to this version, downgrade it may leave garbage in raft engine.
```release-note
None
```

raftstore-v2: add tablet logger and update dep

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/metrics.rs
components/backup-stream/src/subscription_manager.rs
components/backup-stream/src/subscription_track.rs
components/backup-stream/tests/mod.rs
components/server/src/server.rs
components/test_raftstore/src/cluster.rs

Issue Number: Close #14099
This PR added leader resolver to the log backup, it would check the leadership while doing resolving for preventing stale leader advances resolved ts to wrong place.
```commit-message
```
Tests 
- Unit test
```release-note
Fixed a bug that may cause data loss when PITR meet partial network partition (only messages between TiKVs are blocked).
```

log-backup: added check leader call before flushing

---

Cargo.lock
Cargo.toml
components/error_code/src/storage.rs
components/raftstore/src/errors.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/util.rs
components/raftstore/src/store/worker/read.rs
etc/error_code.toml
src/storage/errors.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs
src/storage/txn/mod.rs
tests/integrations/server/kv_service.rs

Issue Number: Close #14143. Should merge after https://github.com/pingcap/kvproto/pull/1054.
```commit-message
As https://github.com/tikv/tikv/issues/14143 mentioned, flashback should not
return `TxnLockNotFound` error to the client if the flashback commit check failed,
which will cause TiDB to retry the flashback forever. This PR changes this error to
`FlashbackNotPrepared` to match the client handling logic.
```
Tests 
- Unit test
```release-note
None.
```

raftstore, storage: return FlashbackNotPrepared error if the flashback commit check failed

---

components/raftstore/src/store/fsm/apply.rs
tests/integrations/raftstore/test_witness.rs

close tikv/tikv#14142
Issue Number: Close #14142
When the peer is a witness, it has no data, so the calculated hash must be different from the one passed by the leader. 
Therefore ignore the compute and verify commands.
```commit-message
apply: ignore compute and verify hash when it's a witness
```
- None
Tests 
Side effects
- None
- None
```release-note
None
```

apply: ignore compute and verify hash when it's a witness

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/errors.rs
components/backup-stream/src/metadata/store/etcd.rs

Signed-off-by: hillium <yujuncen@pingcap.com>
Issue Number: Close https://github.com/tikv/tikv/issues/14159
This PR would report a "canceled" error when the server canceled the watch.
```commit-message
```
Tests 
We executed the following step: 
1. Compact etcd to the latest revision.
2. Restart PD.
3. Pause the task and check whether TiKV can detect the pause task.
With the master version, not all TiKVs have detected the task has been paused.
With this PR, TiKVs can detect the task has been paused.
```release-note
Fixed a bug caused TiKV cannot watch task change after PD restart sometimes.
```

log-backup: report when watch canceled

---

components/engine_rocks/src/event_listener.rs
components/engine_rocks/src/lib.rs
components/engine_traits/src/cf_defs.rs
components/engine_traits/src/flush.rs
components/raftstore-v2/src/operation/command/write/mod.rs
components/raftstore-v2/src/operation/mod.rs
components/raftstore-v2/src/operation/ready/apply_trace.rs
components/raftstore-v2/src/operation/ready/mod.rs

Issue Number: Close #14113 
```commit-message
`OnFlushComplete` can be called out of order. What we can assume is
when a seqno finishes flush, all SSTs have smaller seqno must also
finish flush.
```
Tests 
- Unit test
```release-note
None
```

engine_traits: allow chaos flush notification

---

src/server/raftkv/mod.rs

Issue Number: Close #14191
```commit-message
pass missing resource group name to request header
```
Tests 
```release-note
None
```

resource_control: pass missing resource group name to request header

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/admin/mod.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/mod.rs
components/raftstore-v2/src/router/message.rs
components/raftstore-v2/src/worker/pd/region.rs
tests/integrations/raftstore/test_split_region.rs

```commit-message
Support split operator got from PD.
```
Tests 
- Unit test
```release-note
None
```

Raftstore-v2: support split operator

---

components/test_raftstore-v2/src/node.rs
components/test_raftstore-v2/src/server.rs
tests/integrations/raftstore/test_split_region.rs

```commit-message
use appropriate default region split size when integration test suit start
```
When the appropriate default region split size is used, `test_delay_split_region` can pass using raftstore-v2.
Tests 
- Unit test
```release-note
None
```

Raftstore-v2: use appropriate default region split size when integration test suit start

---

components/sst_importer/src/metrics.rs
components/sst_importer/src/sst_importer.rs

Issue Number: Close #14206
This PR make the downloaded cache file hold lock for itself. So we don't need to rely on the segment lock of the dashmap.
```commit-message
```
Tests 
- Unit test (TBD)
```release-note
Speeded up PITR.
```

log-backup: make the download more finer-grained

---

components/snap_recovery/src/init_cluster.rs

Signed-off-by: fengou1 <feng.ou@pingcap.com>
Issue Number: Close #14017 
ebs volume snapshot support tikv node equipped with 2 cpu or less configuration.
To prevent mistakenly inputting too large values, the rocksdb max background limit is made according to the cpu quota * 10. Notice 10 is only an estimate, not an empirical value.
snapshot recovery mode has rocksdb max background job configured as 32 in recovery mode, which requires min CPU is 4. we change this value as min[32, cpu quota*10] 
Tests 
- Unit test
1. make a docker image
2. create cluster with 2 cpu tikv node
3. backup and restore
- No code
Side …

fix: ebs volume snapshot support tikv node equipped with 2 cpu or less configuration

---

components/raftstore-v2/src/operation/command/admin/mod.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/test_raftstore-v2/src/util.rs
tests/integrations/raftstore/test_snap.rs

```commit-message
snap status should be cleared when sending snapshot failed
```
Tests 
- Unit test
```release-note
None
```

Raftstore-v2: snap status should be cleared when sending snapshot failed

---

Cargo.lock
Cargo.toml
src/coprocessor/statistics/analyze.rs
src/coprocessor/statistics/cmsketch.rs
src/coprocessor/statistics/fmsketch.rs

Signed-off-by: xuyifangreeneyes xuyifangreeneyes@gmail.com
Issue Number: ref #14231
Use https://github.com/tikv/mur3 to calculate fmsketch, which is more efficient.
```
```
Tests 
- Unit test
- No code
Before the PR:
```
test coprocessor::statistics::analyze::benches::bench_collect_column                        ... bench:         215 ns/iter (+/- 29)
test coprocessor::statistics::analyze::benches::bench_collect_column_group                  ... bench:         183 ns/iter (+/- 14)
```
After the PR:
```
test coprocessor::statistics::analyze::benches::bench_collect_column                        ... bench: …
```

coprocessor: use mur3 to calculate fmsketch

---

components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/life.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/tests/failpoints/mod.rs
components/raftstore-v2/tests/failpoints/test_life.rs
components/raftstore-v2/tests/integrations/cluster.rs
components/raftstore-v2/tests/integrations/test_life.rs
components/raftstore/src/store/worker/region.rs

Issue Number: Close #14215
```commit-message
If a peer is marked for destroy, it will skip all apply result, which
will make it never apply to committed index. This PR relaxes the check
to last_applying_index and always process apply result.
It also fixes a bug that new peer created by large ID may not survive
restart.
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: fix destroy blocked by apply progress

---

etc/config-template.toml
src/config/mod.rs

Issue Number: Close #14052
```commit-message
Because of memory fragment issue 16KB causes, we change it to 32KB and the result shows there's no significant memory fragment. 
```
Tests 
- Unit test
```release-note
Change the default value of rocksdb.writecf.block_size and rocksdb.defaultcf.block_size to 32KB (from 16KB)
```

rocksdb: reduce rocksdb block size to 32KB (#14053)

---

etc/config-template.toml
src/config/mod.rs

close tikv/tikv#14052
Because of memory fragment issue 16KB causes, we change it to 32KB and the result shows there's no significant memory fragment.
Issue Number: Close #14052
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
update block-size of writecf and defaultcf to 32K as default  value.
```

rocksdb: reduce rocksdb block size to 32KB (#14053) (#14244)

---

components/raftstore-v2/src/operation/ready/snapshot.rs
tests/integrations/raftstore/test_conf_change.rs

```commit-message
Update peer state after persisting snapshot
```
If peer 1 is added to store 1 before the store1 starts, peer 1 will be in learner state. So after applying the snapshot, we should align the state with region's relevant peer state.
Tests 
- Unit test
- No code
Side effects
```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a …
```

Raftstore-v2: update peer state after persisting snapshot

---

Cargo.lock

Issue Number: Close #14257
TiKV currently use an old version openssl-src 111.20.0+1.1.1o. The bug [cve-2023-0286](https://www.trellix.com/en-us/about/newsroom/stories/research/cve-2023-0286-the-openssl-who-cried-severity-high.html) was fixed in 1.1.1t.
```commit-message
Upgrade openssl-src version to fix CVE-2023-0286.
```
Tests 
Side effects
```release-note
None
```

*: update openssl-src version to fix CVE-2023-0286

---

Cargo.lock
components/raft_log_engine/src/engine.rs
components/raftstore-v2/Cargo.toml
components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/fsm/apply.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/command/write/mod.rs
components/raftstore-v2/src/operation/command/write/simple_write.rs
components/raftstore-v2/src/operation/mod.rs
components/raftstore-v2/src/raft/apply.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/tests/integrations/cluster.rs
components/server/src/server.rs
components/server/src/server2.rs
components/test_raftstore-v2/src/cluster.rs
components/test_raftstore-v2/src/node.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
components/tikv_kv/src/btree_engine.rs
components/tikv_kv/src/lib.rs
src/import/sst_service.rs
src/server/gc_worker/gc_worker.rs
src/server/raftkv/mod.rs
src/server/raftkv2/mod.rs
src/server/raftkv2/node.rs
src/storage/mvcc/reader/reader.rs
tests/integrations/server/kv_service.rs

```commit-message
So that it can support both v1 and v2.
```
To make it work with V2, we still need to use tablet registry.
Tests 
- Unit test
```release-note
None
```

importer: use kv engine instead of raw API

---

components/file_system/src/io_stats/proc.rs
components/tikv_util/src/sys/thread.rs
components/tikv_util/src/yatp_pool/mod.rs

Issue Number: Ref #10867
Previously, if some thread doesn't call `set_io_type`, its I/O will not be traced by the I/O stats collector.
```commit-message
Fix thread I/O not monitored if I/O type isn't set.
```
Tests 
- Unit test
```release-note
None
```

file_system: initialize io stats sentinel on thread start

---

components/tidb_query_executors/src/fast_hash_aggr_executor.rs
components/tidb_query_executors/src/index_scan_executor.rs
components/tidb_query_executors/src/interface.rs
components/tidb_query_executors/src/limit_executor.rs
components/tidb_query_executors/src/projection_executor.rs
components/tidb_query_executors/src/runner.rs
components/tidb_query_executors/src/selection_executor.rs
components/tidb_query_executors/src/simple_aggr_executor.rs
components/tidb_query_executors/src/slow_hash_aggr_executor.rs
components/tidb_query_executors/src/stream_aggr_executor.rs
components/tidb_query_executors/src/table_scan_executor.rs
components/tidb_query_executors/src/top_n_executor.rs
components/tidb_query_executors/src/util/aggr_executor.rs
components/tidb_query_executors/src/util/mock_executor.rs
components/tidb_query_executors/src/util/scan_executor.rs
src/coprocessor/statistics/analyze.rs
tests/benches/coprocessor_executors/util/bencher.rs
tests/benches/coprocessor_executors/util/fixture.rs
tests/failpoints/cases/test_coprocessor.rs

Issue Number: close tikv/tikv#14254, close tikv/tikv#14291
```commit-message
#14209 stop paging when the result set is drained. But when supporting agg paging,
the executors will also return drained when there is enough data returned.
This PR label the drain reasons and stop following paging when the resultset is really drained.
```
Tests 
- Unit test
TPCC prepare success.
Side effects
```release-note
copr: reduce latency and resource usage of the paging protocol by early stop.
```

Cherry pick #14209 and #14292 to 6.5

---

src/coprocessor/statistics/analyze.rs

Issue Number: ref #14231
Implement https://github.com/pingcap/tidb/pull/41931 in the tikv side. For the sinlge-column group, its `fm_sketch` is the same as that of the corresponding column. Hence, we don't maintain its `fm_sketch` in `collect_column_group`. We just copy the corresponding column's `fm_sketch` after iterating all rows. Also, we can directly copy `total_size` and `null_count`.
```commit-message
```
Tests 
Side effects
```release-note
None
```

coprocessor: avoid fmsketch calculation for single-column index

---

Cargo.lock
components/resource_control/src/lib.rs
components/tidb_query_executors/src/runner.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/13936
What's Changed: When find a limit with partition_by field, we treat it as a partitionTopN without order_key.
Tests 
- Unit test has already added in https://github.com/tikv/tikv/pull/14116
Side effects
```release-note
None
```

copr: (enhance) support executor limit with partition_by fields

---

components/raftstore-v2/src/operation/command/admin/split.rs
tests/failpoints/cases/test_split_region.rs

Issue Number: Close #14347
```commit-message
consider None when getting mailbox
```
When the cluster is stopped, mailboxes will be cleared.  However, on_apply_res_split may be executed concurrently, which means we cannot unwrap on `mailbox(xxx)`.
Tests 
- Unit test
- No code
```release-note
None
```

raftstore-v2: consider None when getting mailbox

---

Cargo.lock
Cargo.toml
components/engine_rocks/Cargo.toml
components/engine_rocks/src/raw.rs
components/engine_rocks/src/util.rs
components/engine_test/src/lib.rs
components/engine_traits/src/tablet.rs
components/raftstore-v2/src/worker/tablet_gc.rs
components/tikv_util/src/sys/cgroup.rs
src/config/mod.rs
src/server/engine_factory.rs
src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/rawkv_compaction_filter.rs
src/server/ttl/ttl_compaction_filter.rs
src/storage/kv/test_engine_builder.rs
src/storage/mod.rs
tests/integrations/storage/test_titan.rs

Add a new compaction filter that filters out-of-range keys, and a compaction filter that can composite multiple filters as a stack.
```commit-message
None
```
https://github.com/tikv/rust-rocksdb/pull/738
https://github.com/tikv/tikv/pull/14253
Tests 
- Unit test
```release-note
None
```

raftstore-v2: use compaction filter to trim tablet

---

Cargo.lock
Cargo.toml
components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/fsm/store.rs
components/raftstore-v2/src/operation/command/write/ingest.rs
components/raftstore-v2/src/operation/command/write/mod.rs
components/raftstore-v2/src/router/message.rs
components/raftstore-v2/src/worker/tablet_gc.rs
components/server/src/server.rs
components/server/src/server2.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
src/import/mod.rs
src/import/sst_service.rs

```commit-message
A few behavior changes:
- In v2, normal mode is always used, trying to switch to import mode will get error response.
- A context is added to compact range request. If not compact with region ID, the request will be rejected.
- SSTs are cleaned up immediately if its corresponding regions doesn't exist on the store anymore.
```
Tests 
- Unit test
```release-note
None
```

importer: support raftstore v2

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/peer_storage.rs
tests/failpoints/cases/test_witness.rs

close tikv/tikv#14219
Issue Number: Close #14219 
Removed incorrect conditional judgment. The triggering scenario is:
1. The Voter has received the switch witness request, but has not yet applied it;
2. Raft elections occur, and the Voter is elected to become the leader;
3. After the Voter becomes the leader, the switch witness is applied to become the witness;
This incorrect condition judgment will incorrectly set `wait_data` to `true`, resulting in the incorrect rejection of the transfer leader request sent by PD in the pre_proposal stage, and eventually causing PITR to time out.
The left changes are:
1.  To avoid duplication of request snapshots, which has nothing to do with the scenario described above and was added for convenience;
2. Notify pd immediately, when the …

raftstore: fix incorrect cond judgment leading to rejection of pre_proposal

---

src/coprocessor/statistics/analyze.rs

Issue Number: ref #14231
From the flame graph, creating and dropping `EvalContext` takes up much CPU time since it is called frequently. Hence, the PR reuses `EvalContext` in `collect_column_stats` to reduce the cost.
```commit-message
```
Tests 
- No code
Side effects
```release-note
None
```

coprocessor: reuse EvalContext in collect_column_stats

---

components/raftstore-v2/src/operation/ready/mod.rs
components/test_raftstore-v2/src/cluster.rs
components/test_raftstore-v2/src/lib.rs
components/test_raftstore-v2/src/node.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore-v2/src/transport_simulate.rs
components/test_raftstore-v2/src/util.rs
tests/integrations/raftstore/test_replica_read.rs

Issue Number: Close #14388
```commit-message
filter read index msg when sending from self
```
This PR pick the fix from https://github.com/tikv/tikv/pull/12300, which fixes the case where leader receives a read index msg from itself which is sent when it was  a follower.
To reuse the v1's test, this PR also implments `async_read` API for test cluster.
Tests 
- Unit test
```release-note
None
```

raftstore-v2: filter read index msg when sending from self

---

components/raftstore-v2/src/operation/command/admin/merge/prepare.rs
components/raftstore/src/store/entry_storage.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/util.rs
src/storage/txn/sched_pool.rs

This reverts commit 852af464cd48a97ec2b88c6a183a4f1ec4a84938.
Issue Number: Close #14375 
```commit-message
Revert the parsed entry that may lead to performance regression and disable priority pool for sched worker
```
Tests 
- No code
```release-note
None
```

Revert changes that may cause performance regression introduced by write prioirty scheduling

---

Cargo.lock
components/server/src/server.rs
components/server/src/server2.rs
components/sst_importer/Cargo.toml
components/sst_importer/src/config.rs
components/sst_importer/src/lib.rs
components/sst_importer/src/sst_importer.rs
src/config/mod.rs
src/import/sst_service.rs

Issue Number: Close https://github.com/tikv/tikv/issues/14409
As title.
```commit-message
```
Tests 
```
MySQL [(none)]> show config where type='tikv' and name='import.memory-use-ratio';
+------+-----------------+-------------------------+-------+
| Type | Instance        | Name                    | Value |
+------+-----------------+-------------------------+-------+
| tikv | 10.2.5.31:20162 | import.memory-use-ratio | 0.3   |
| tikv | 10.2.5.11:20160 | import.memory-use-ratio | 0.3   |
| tikv | 10.2.5.18:20161 | import.memory-use-ratio | 0.3   |
+------+-----------------+-------------------------+-------+
MySQL [(none)]> set config tikv `import.memory-use-ratio`=0.1;
MySQL …
```

PITR: support modifying the config tikv.import.memory-use-ratio online when restore point.

---

metrics/grafana/tikv_details.json

Issue Number: Close #14427 
```commit-message
Fix grafana display anomaly.
The `pessimistic lock activities` panel's id is the same as that of  `gRPC resource group QPS` panel
which makes grafana display anomaly. So change the duplicated id.
```
Tests 
```release-note
None
```

grafana: fix grafana display anomaly

---

components/backup-stream/src/checkpoint_manager.rs
components/backup-stream/src/service.rs

Issue Number: Close #14426
This PR make us won't close the grpc server stream when encountered some errors.
```commit-message
```
Tests 
There is a tricky unit test added, these tests can pass, however I'm not sure whether they should be added to the code.
<details><summary>Details</summary>
```diff
diff --git a/components/backup-stream/src/checkpoint_manager.rs b/components/backup-stream/src/checkpoint_manager.rs
index 1191b6010..9d0ac9ea7 100644
--- a/components/backup-stream/src/checkpoint_manager.rs
+++ b/components/backup-stream/src/checkpoint_manager.rs
@@ -51,10 +51,12 @@ impl std::fmt::Debug for CheckpointManager {
enum SubscriptionOp {
Add(Subscription),
Emit(Box<[FlushEvent]>),
+    #[cfg(test)]
+ …
```

backup-stream: don't close the server stream when encountered errors

---

Cargo.lock
Cargo.toml
components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/lib.rs
components/raftstore-v2/src/operation/command/admin/compact_log.rs
components/raftstore-v2/src/operation/command/admin/mod.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/command/admin/transfer_leader.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/raft/peer.rs
components/raftstore-v2/src/worker/mod.rs
components/raftstore-v2/src/worker/tablet_flush.rs
components/raftstore/src/store/fsm/peer.rs
components/test_raftstore-v2/Cargo.toml
components/test_raftstore-v2/src/cluster.rs
components/test_raftstore-v2/src/node.rs
components/test_raftstore/src/node.rs
components/txn_types/src/types.rs
tests/integrations/raftstore/test_split_region.rs

Issue Number: Close #14447
```commit-message
flush memtable before proposing split
```
Split calls `checkpoint` API of RocksDB which can easily cost more than 500ms.
As the main expensive operation of the `checkpoint `is the memtable flush, this PR schedule memtable flush before proposing the split.
So, when split is to be proposed, schedule a memtable flush task to the relevant worker, and at the same time, send raft messages with extra msg to followers to let them flush their memtables.
After the flush task finishes, the split can be proposed, and this time, `checkpoint` will be much more lightweight.
Tests 
- Unit test
- Manual test (add detailed scripts or …

raftstore-v2: flush memtable before proposing split

---

components/backup-stream/src/config.rs
components/backup-stream/src/endpoint.rs
components/backup-stream/src/router.rs
components/server/src/server.rs
src/config/mod.rs
tests/integrations/config/mod.rs

Issue Number: Close https://github.com/tikv/tikv/issues/14433
As title~
```commit-message
```
Tests 
```
MySQL [(none)]> show config where type='tikv' and name='log-backup.max-flush-interval';
+------+-----------------+-------------------------------+-------+
| Type | Instance        | Name                          | Value |
+------+-----------------+-------------------------------+-------+
| tikv | 10.2.5.31:20162 | log-backup.max-flush-interval | 3m    |
| tikv | 10.2.5.11:20160 | log-backup.max-flush-interval | 3m    |
| tikv | 10.2.5.18:20161 | log-backup.max-flush-interval | 3m    |
+------+-----------------+-------------------------------+-------+
MySQL [(none)]> set config …
```

pitr: support modifying the config tikv.log-backup.max-flush-interval online.

---

components/server/src/server.rs
components/test_raftstore/src/server.rs
components/tidb_query_executors/src/runner.rs
components/tikv_util/src/metrics/mod.rs
components/tikv_util/src/quota_limiter.rs
components/tikv_util/src/sys/cpu_time.rs
etc/config-template.toml
src/config.rs
src/coprocessor/endpoint.rs
src/coprocessor/mod.rs
src/coprocessor/statistics/analyze.rs
src/server/service/diagnostics/sys.rs
src/storage/mod.rs
src/storage/txn/scheduler.rs

Issue Number: Close #13084
```
The new parameters are quota.background-cpu-time, quota.background-write-bandwidth and
quota.background-read-bandwidth.
At present, only background-cpu-time can take effect on auto analyze job.  The cpu quota for
auto analyze can adjust according to the TiKV instance workload if quota.enable-auto-tune is
set to true.  A system thread will check the instance status, and could adjust the cpu quota periodically. 
```
Tests 
Verify logic by debug
Side effects
- auto analyze might become slower.
```release-note
None
```

Bg quota limiter auto tune

---

components/cdc/src/endpoint.rs

Issue Number: ref #11993
Close https://github.com/pingcap/tiflow/issues/8561
Batch send resolved ts exponentially to speed up TiCDC resolve lock
```commit-message
cdc: batch send resolved ts exponentially to speed up TiCDC resolve lock
```
Tests 
- Unit test
```release-note
None
```

cdc: batch send resolved ts exponentially to speed up TiCDC resolve lock

---

components/tikv_util/src/sys/cgroup.rs

Issue Number: Close #14538
```commit-message
```
This PR considers that the cgroup path may contains ":" in it.
Tests 
- Unit test
```release-note
None
```

tikv_util: cgroup path parsing fix

---

components/raftstore-v2/src/operation/bucket.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/query/mod.rs
components/raftstore-v2/tests/failpoints/mod.rs
components/raftstore-v2/tests/failpoints/test_bucket.rs
components/raftstore-v2/tests/integrations/cluster.rs
components/raftstore-v2/tests/integrations/mod.rs
components/raftstore/src/store/region_meta.rs

Issue Number: Close #14506
```commit-message
check apply_scheduler before using it in on_refresh_region_buckets.
This is to solve the race condition when the peer is just created by split meanwhile a refresh bucket is called immediately. 
```
Tests 
- Unit test
```release-note
None
```

[raftstore-v2]: check apply_scheduler before using in on_refresh_region_buckets

---

src/import/sst_service.rs

Issue Number: Close #14313
This PR make the default max batch size 1/2 of the max raft command size. (IMO 4 MiB would be a fair choice for batching, even we batch up to 7MiB, perhaps the throughput won't be greatly increased.)
This PR also make the `Collector` try its best to don't make batch greater than `max_raft_cmd_size`. In the past, it fire the batch after noticing the current `unpacked_size` is greater than the max batch size, which make the real batch size will be slightly greater than the real size. After this, it will check the total size BEFORE it add the request.
```commit-message
```
Tests 
- Unit test
```release-note
Fixed a bug that may cause PITR fail when there are too many tiny or huge rows. 
```

log-backup: use conservativer batch strategy

---

Cargo.lock
components/backup-stream/Cargo.toml
components/backup-stream/src/endpoint.rs
components/backup-stream/src/metrics.rs
components/backup-stream/src/observer.rs
components/backup-stream/src/subscription_manager.rs
components/backup-stream/src/subscription_track.rs

Issue Number: Close #14453 
Remove handler for `PrepareMinTsForResolve` when there isn't any task. 
```commit-message
```
Tests 
1. Start a new cluster in master. -- Many logs described in #14453 printed.
2. Start a new cluster in this PR. -- Logs described in #14453 don't print again as long as no log backup task triggered.
```release-note
Fixed a bug that may cause TiKV print too many meanless logs about log backup.
```

log-backup: eliminate some verbose logs

---

Cargo.lock
components/tidb_query_datatype/Cargo.toml
components/tidb_query_datatype/src/codec/row/v2/encoder_for_test.rs

Issue Number: Ref #14528 
Implement the checksum row value encode logic on the tikv side, mainly used for test cases in tikv. 
In the previous design, there was no anticipation of introducing development work related to compatibility. However, testing coverage is still required, especially to verify if row values containing checksum parts can be processed by the decoder with lower versions.
Related to https://github.com/pingcap/tidb/pull/42859
Tests 
- Unit test
Side effects
```release-note
None
```

storage: implement the row value checksum encode logic in tikv side

---

src/server/lock_manager/metrics.rs
src/server/lock_manager/waiter_manager.rs

Issue Number: ref #14497 
```commit-message
Round up last_update_duration_ms, so that duration in (0, 1ms] won't be treated as 0.
```
Tests 
```release-note
None
```

txn: round up last_update_duration_ms

---

components/encryption/src/manager/mod.rs

Issue Number: Close #14585
The old key handling logic is mistakenly reverted in https://github.com/tikv/tikv/pull/8805, restoring them now.
```commit-message
Fix a bug that a newly generated encryption key might erase an old key and make data unreadable
```
Tests 
- Unit test
```release-note
Fix a bug that a newly generated encryption key might erase an old key and make data unreadable
```

encryption: fix key collision handling

---

cmd/tikv-server/src/main.rs
src/storage/config.rs
src/storage/mvcc/txn.rs

```commit-message
Adjust engine type config before running tikv server. Otherwise it will be too late. 
Fix some other compile warnings. 
```
Tests 
```release-note
None
```

fix engine type config on existing cluster

---

components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore/src/store/util.rs
components/test_raftstore-v2/src/server.rs
tests/integrations/raftstore/mod.rs
tests/integrations/raftstore/test_lease_read.rs
tests/integrations/raftstore/test_stale_read.rs

Issue Number: Close #14664
```commit-message
Fix stale read by correct updating peers
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: fix stale read by correct updating peers

---

components/test_coprocessor/src/fixture.rs
components/test_coprocessor/src/store.rs
components/tidb_query_datatype/src/codec/data_type/scalar.rs
components/tidb_query_datatype/src/codec/row/v2/encoder_for_test.rs
components/tidb_query_datatype/src/codec/row/v2/mod.rs
components/tidb_query_datatype/src/codec/row/v2/row_slice.rs
components/tidb_query_datatype/src/def/field_type.rs
src/storage/mvcc/reader/point_getter.rs
tests/integrations/coprocessor/test_select.rs

Issue Number: Ref #14528 
Add checksum calculation logic in `RowSlice`, add `cop` and `kv-get` test cases, the target is to verify the checksum encoding impact on read paths.
Tests 
- Unit test
Side effects
```release-note
None
```

storage: add checksum logic in row slice, add cop and get test cases

---

components/tracker/src/lib.rs
components/txn_types/src/lock.rs
src/server/raftkv/mod.rs
tests/failpoints/cases/test_transaction.rs
tests/integrations/storage/test_raftkv.rs

Issue Number: Close #14715 
Do check memory lock when replica read is used with max ts.
Tests 
- Unit test
Side effects
```release-note
Fix the issue that autocommit point get replica read may break linearizability.
```

txn: check memory lock for max ts replica read

---

Cargo.lock
components/engine_panic/src/sst.rs
components/engine_rocks/src/encryption.rs
components/engine_rocks/src/sst.rs
components/engine_traits/src/sst.rs
components/raftstore/src/store/worker/cleanup_sst.rs
components/sst_importer/Cargo.toml
components/sst_importer/src/import_file.rs
components/sst_importer/src/sst_importer.rs
components/sst_importer/src/sst_writer.rs

Issue Number: Close https://github.com/tikv/tikv/issues/14745
This PR opens the SST while fetching the range of the SST. So we can peoperly query the region bound to the SST meta and clean up SST in time.
```commit-message
```
Tests 
- Unit test
```release-note
Fixed a bug that may cause lightning leak SST files no longer needing to be ingested.
```

sst_importer: load SST start key from sst while cleaning up

---

components/txn_types/src/write.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/txn/actions/acquire_pessimistic_lock.rs
src/storage/txn/actions/common.rs
src/storage/txn/actions/mod.rs
src/storage/txn/actions/prewrite.rs

Issue Number: ref #14780
Cherry pick #14784 
```commit-message
```
Tests 
- Unit test
Side effects
```release-note
Fix the bug that accumulated LOCKs may slow read operations after upgrade.
```

fix: find the correct last_change_ts after upgrade from versions < 6.5

---

src/server/metrics.rs
src/storage/errors.rs

Issue Number: Close #14808
```commit-message
Add more specific error type of raftstore error to metrics 
```
Tests 
- No code
Side effects
```release-note
None
```

add more specific error type in ErrorHeaderKind

---

components/raftstore-v2/src/operation/command/admin/flashback.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/txn_ext.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
src/storage/mvcc/reader/reader.rs
src/storage/txn/commands/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs
tests/integrations/raftstore/test_flashback.rs

Issue Number: ref #13303, close https://github.com/pingcap/tidb/issues/44292.
```commit-message
During the Flashback process, we should prevent any read or write operations on the in-memory pessimistic lock table
and clear it like rolling back other locks to ensure that Flashback can proceed smoothly.
```
Tests 
- Unit test
```release-note
Fix the issue where in-memory pessimistic locks may cause flashback to fail and lead to data inconsistency.
```

raftstore: block in-memory pessimistic locks during the flashback

---

cmd/tikv-ctl/src/executor.rs
cmd/tikv-ctl/src/main.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/14654
```commit-message
recognize engine type by data dir
```
In local mode, now, tikv-ctl can only recognize engine type by tikv config (if `--config` is not specified, default tikv config will be used, so the debugger will be initialzied as v1). It means if we does not pass config path to it, it will use v1's logic to perform tikv control for v2 cluster, which can return misleading results.
As passing config path every time is not convenient, this PR makes it automatically recognize engine type by data dir passed in, which is required in local mode.
Tests 
data dir `tikv-11` …

tikv-ctl: recognize engine type by data dir

---

components/error_code/src/storage.rs
components/test_raftstore/src/util.rs
components/tikv_kv/src/lib.rs
src/server/metrics.rs
src/server/raftkv/mod.rs
src/storage/txn/scheduler.rs
tests/failpoints/cases/test_kv_service.rs
tests/failpoints/cases/test_storage.rs

Issue Number: Ref #14838 
1. Use `must_call` for the `async_write` callback.
2. Add assertion for the path the task is finished unexpectedly and the latch is not released.
Tests 
- Unit test
- Inject the failpoint `applied_cb_return_undetermined_err` and raise a write task, tikv-server panics.
Side effects
```release-note
None
```

scheduler: use must_call for async write callback, add assertion for expected path

---

src/storage/txn/scheduler.rs

Issue Number: Ref #12362
1. Record scheduler process durations and async write durations, and print them in the tikv slow log like
```
[region 40] scheduler handle command: prewrite, ts: 442011940292132869, details: SchedulerDetails { tracker: TrackerToken { shard_id: 58, seq: 21, key: 0 }, stat: Statistics { lock: CfStatistics { processed_keys: 0, get: 1, next: 0, prev: 0, seek: 0, seek_for_prev: 0, over_seek_bound: 0, flow_stats: FlowStatistics { read_keys: 0, read_bytes: 0 }, next_tombstone: 0, prev_tombstone: 0, seek_tombstone: 0, seek_for_prev_tombstone: 0, raw_value_tombstone: 0 }, write: CfStatistics { processed_keys: 0, get: 0, next: 0, prev: 0, seek: 1, seek_for_prev: 0, over_seek_bound: 0, flow_stats: FlowStatistics { read_keys: 1, read_bytes: 151 }, …
```

scheduler: record process and write durtaion details

---

src/storage/txn/actions/prewrite.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/scheduler.rs

…12713) (#12766)
ref tikv/tikv#11612, ref tikv/tikv#12713
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
If this PR will be picked to release branch, then a release note is probably …
```

Cherry pick 4f25a8555b92aeee2b67d4afa6fb6677746efc1c to 6.1 hotfix branch

---

components/backup-stream/Cargo.toml
components/backup-stream/tests/failpoints/mod.rs
components/backup-stream/tests/integration/mod.rs
components/backup-stream/tests/suite.rs

Issue Number: Close #14958 
This PR extracted the Suite of testing, split up cases into two crates.
```commit-message
Now, the `backup-stream` test case should be run by:
FAIL_POINT=1 ./scripts/test --package backup-stream --test failpoints -- all
./scripts/test --package backup-stream --test integration -- all
```
Tests 
- No code
```release-note
None
```

log-backup: split failpoints and integration tests

---

tests/integrations/raftstore/test_flashback.rs

Issue Number: ref #13303, ref https://github.com/pingcap/tidb/issues/44292.
```commit-message
Make `test_flashback_with_in_memory_pessimistic_locks` stable.
```
Tests 
- Unit test
```release-note
None.
```

tests: make test_flashback_with_in_memory_pessimistic_locks stable

---

Cargo.lock
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/initializer.rs
components/cdc/src/service.rs
components/cdc/tests/failpoints/test_endpoint.rs
components/cdc/tests/failpoints/test_observe.rs
components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs

Issue Number: Close #14967 .
* TiCDCs send *version* and *features* headers to TiKVs when establishing a connection;
* add a new TiCDC feature `stream multiplexing`;
```commit-message
```
Tests 
- Unit test
Side effects
```release-note
None
```

cdc: support EventFeedV2 RPC and introduce stream multiplexing

---

components/raftstore-v2/src/operation/query/local.rs

Issue Number: Close #15091
Ref #14997 
```commit-message
Disable coprocessor cache temporarily because of issue #15091
```
Tests 
Enable multi rocksdb and run TiDB cluster.
```release-note
None
```

raftstore-v2: disable coprocessor cache

---

components/pd_client/src/lib.rs
components/raftstore-v2/src/operation/bucket.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore/src/coprocessor/config.rs
components/raftstore/src/store/config.rs
components/raftstore/src/store/worker/split_check.rs

Issue Number: Close #14356
```commit-message
1) avoid sending PeerTick::SplitRegionCheck for each write
2) reduce default bucket size from 96MB to 50MB to reduce chance of client side timeout
3) change the default value of evict-cache-on-memory-ratio to 0.1. 
```
Tests 
- No code
```release-note
1) reduce default bucket size from 96MB to 50MB to reduce chance of client side timeout
2) change the default value of evict-cache-on-memory-ratio to 0.1. 
```

bucket polish and enable evict-cache-on-memory-ratio by default

---

components/raftstore/src/store/peer.rs
tests/integrations/raftstore/test_replication_mode.rs

Issue Number: Close https://github.com/tikv/tikv/issues/14975
```commit-message
raftstore: do not enable group commit when replication mode is SyncRecover
- during DR mode, the SyncRecover state should be committed in majority mode. otherwise, the qps may drop
```
After this change, the `SyncRecover` phase will not enable group commits at first, once the `dr replicas` catch up the logs, then enable the group commits. the region will report as `INTEGRITY_OVER_LABEL` after catching up on the logs, after all, region is in the `INTEGRITY_OVER_LABEL` state, PD will switch the state `SyncRecover` top `Sync` state.
Tests 
- Unit test
```release-note
fix the QPS drop to zero in dr SyncRecovery phase in DR mode
```

raftstore: allow DrAutoSync to majority commit log during SyncRecover phase

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/fsm/store.rs
components/raftstore-v2/src/operation/command/admin/conf_change.rs
components/raftstore-v2/src/operation/command/admin/merge/rollback.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/mod.rs
components/raftstore-v2/src/operation/pd.rs
components/raftstore-v2/src/operation/query/mod.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/operation/unsafe_recovery/force_leader.rs
components/raftstore-v2/src/operation/unsafe_recovery/mod.rs
components/raftstore-v2/src/operation/unsafe_recovery/report.rs
components/raftstore-v2/src/raft/peer.rs
components/raftstore-v2/src/router/imp.rs
components/raftstore-v2/src/router/message.rs
components/raftstore-v2/src/router/mod.rs
components/raftstore-v2/src/worker/pd/mod.rs
components/raftstore-v2/src/worker/pd/store.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/unsafe_recovery.rs
components/raftstore/src/store/worker/pd.rs
components/test_raftstore-v2/src/cluster.rs
src/server/tablet_snap.rs
tests/integrations/raftstore/test_unsafe_recovery.rs

Support force for raftstore v2.
Issue Number: ref #15108
```commit-message
* Add UnsafeRecoveryHandle trait to abstract unsafe recovery APIs
* Implement UnsafeRecoveryHandle for raftstore v1 router
* Implement UnsafeRecoveryHandle for raftstore v2 router
* Add unsafe recovery messages to v2 Store and v2 Peer
* raftstore-v2: implement force leader 
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: implement force leader

---

metrics/grafana/tikv_details.json

Issue Number: ref #15082 
```commit-message
Fix the unintentional changes in #15118: let resolved-ts row be collapsed by default, and put panels in it.
```
Tests 
```release-note
None
```

metric: fix resolved-ts row

---

components/pd_client/src/client.rs
components/pd_client/src/metrics.rs
components/pd_client/src/util.rs

Issue Number: Close https://github.com/tikv/tikv/issues/15184
ref https://github.com/tikv/pd/issues/6556
```commit-message
The store heartbeat will report periodically, no need to do retires
- do not retry the store heartbeat
- change `remain_reconnect_count` as `remain_request_count`
- fix some metrics
```
Tests 
- Unit test
add a fail point `sleep(4s)` in pd server when handle the `store_heartbeat`, run cluster:
```
tiup playground v7.1.0  --tiflash=0 --pd.binpath=./pd-server-failpoint --kv.binpath=./tikv-server-fix
```
we can see:
and the logs like:
```
[2023/07/24 17:14:37.755 +08:00] [ERROR] [util.rs:462] ["request failed, retry"] [err_code=KV:Pd:Grpc] [err="Grpc(RpcFailure(RpcStatus { code: 4-DEADLINE_EXCEEDED, …
```

pd_client: reduce store heartbeat retires to prevent heartbeat storm

---

src/storage/mvcc/reader/reader.rs

Issue Number: Close #15219.
```commit-message
Skip the `WriteType:Lock` and `WriteType::Rollback` record in `scan_latest_user_keys`.
```
Tests 
- Unit test
```release-note
None.
```

storage: skip the lock and rollback record in scan_latest_user_keys

---

Cargo.lock
components/tidb_query_executors/src/runner.rs

Issue Number: Close #15228
Update dependencies to being compiled with Apple M1 chip.
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

deps: catch up protobuf-build and its dependents to support compile with Apple M1 chip

---

components/engine_traits/src/engine.rs
components/raftstore/src/coprocessor/dispatcher.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/store/worker/region.rs
tests/integrations/raftstore/test_snap.rs

Issue Number: Close #15227 ref [tiflash#7855](https://github.com/pingcap/tiflash/issues/7855)
```commit-message
Deliver message to observer when applying snapshot is cancelled
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore: Observe when applying snapshot is cancelled

---

src/storage/txn/actions/common.rs
tests/failpoints/cases/test_transaction.rs

Issue Number: Close #15109
```commit-message
This PR updates the way to calculate the last_change_info, which is not very proper before. This also fixes a assertion failure 
in `next_last_change_info` that might happen when it executes in parallel with GC in compaction filter.
```
- Need to cherry-pick to the release branch 
Tests 
Side effects
(Release note needed as the bug is released in 7.2.0)
```release-note
Fix a panic that may happen in some rare cases that transaction reading old data that's being GC-ed by the compaction filter.
```

txn: Fix possible assertion failure in next_last_change_info

---

components/online_config/online_config_derive/src/lib.rs
components/online_config/src/lib.rs

Issue Number: Close #15310
```commit-message
Rust uses CamelCase for struct names.
And add a test for #[doc(hidden)] field.
```
Tests 
- Unit test
```release-note
None
```

oneline_config: CamelCase encoder name 

---

components/snap_recovery/src/init_cluster.rs

Issue Number: Close #15296
This PR make the config allow_unsafe_vote_after_start to true while we are in recovery mode.
```commit-message
```
Tests 
- No code
**NOTE:** The bug hasn't been released.
```release-note
None
```

snap_restore: fix snapshot recovery leader election

---

components/engine_rocks/src/misc.rs

cherry-pick #13384 to release-5.4
---
Issue Number: Close #12421
Changes are simplified for cherry-pick.
Optimizations:
- Use more accurate bounds to create iterator during `delete_all_in_range_cf_by_ingest`, testing shows it can speed up merge to 10x. (previously we use the max/min of a batch of ranges)
- ~Only call `self.delete_all_in_range` once when cleaning overlap ranges. (previously we delete keys in all overlap ranges, then delete keys in to-apply range)~
- ~When inserting a pending range, only delete files of overlap pending ranges. (previously we also delete keys)~
Refactors:
- ~Change `SnapContext` to a data-only struct `SnapGenContext`. It can be shared by cloning, but fields like `pending_delete_ranges` cannot be …

raftstore: optimize region destroy (#13384)

---

etc/config-template.toml
src/config/mod.rs

Issue Number: Close #15324
```commit-message
Ribbon filter may cause OOM  when compacting a sst with many entries.
See tikv/tikv#15324
```
Tests 
See #15324
```release-note
Fix an issue that TiKV may OOM under heavy write workload 
```

config: disable rocksdb ribbon filter

---

etc/config-template.toml
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

close tikv/tikv#15355
Disable `periodic-compaction` and `ttl` features as default.
Issue Number: Close #15355
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
If this PR will be picked to release branch, then a …
```

[cherry-pick-v6.5]compaction: disable periodic-compaction and ttl as default. (#15359)

---

etc/config-template.toml
src/config/mod.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

close tikv/tikv#15355
Disable `periodic-compaction` and `ttl` features as default.
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
If this PR will be picked to release branch, then a …
```

[cherry-pick-v7.1]compaction: disable periodic-compaction and ttl as default. (#15359)

---

components/resource_metering/src/recorder/sub_recorder/cpu.rs

Issue Number: Close #15304
```commit-message
resource_metering: free leaked thread CPU stats
```
Tests 
```release-note
None
```

resource_metering: free leaked thread CPU stats

---

Cargo.lock
components/engine_rocks/Cargo.toml

Issue Number: Close https://github.com/tikv/tikv/issues/15351
```commit-message
update titan to avoid manifest mutex
```
Tests 
- No code
```release-note
Avoid holding mutex when writing titan manifest
```

titan: update titan to avoid manifest mutex on release-6.5

---

components/tidb_query_datatype/src/codec/collation/collator/mod.rs
components/tidb_query_datatype/src/codec/collation/collator/utf8mb4_uca/mod.rs
components/tidb_query_datatype/src/codec/collation/mod.rs
components/tidb_query_datatype/src/def/field_type.rs
components/tidb_query_expr/src/impl_compare.rs

Issue Number: Close #15397
A new collation utf8mb4_0900_bin is added into TiKV. It's simply an alias of `CollatorUtf8Mb4BinNoPadding`.
Ref, the TiDB's implementation: https://github.com/pingcap/tidb/pull/46269
Tests 
- No code
```release-note
Support the `utf8mb4_0900_bin` collation.
```

charset: implement utf8mb4_0900_bin collation

---

components/raftstore/src/store/fsm/peer.rs

Issue Number: Ref #13311 
```commit-message
Adding more log information for diagnosing the issue where inconsistencies between `region` and `region range` information in the meta may occur during region split and self-destroy scenarios.
```
Tests 
Side effects
```release-note
None
```

raftstore: more log information for region meta

---

Cargo.lock
Cargo.toml
components/resource_metering/Cargo.toml
components/tikv_util/Cargo.toml
tests/Cargo.toml

Issue Number: Close #15413
```commit-message
update procinfo to hanlde no data in context switch metrics panel
```
Now, we can collect the metrics.
Tests 
- Unit test
- No code
```release-note
None
```

tikv_util: update procinfo to hanlde no data in context switch metrics panel

---

src/server/status_server/mod.rs
src/server/status_server/profile.rs

Issue Number: Close #11161 
```commit-message
Add back heap profile HTTP API and make it secure. The API is removed by #11162 due to a 
secure issue that can visit arbitrary files on the server. This PR makes it only show the file 
name instead of the absolute path, and adds a paranoid check to make sure the passed file
name is in the set of heap profiles.
```
Tests 
`heap_list` only outputs file names
`heap` only accepts the file name
```release-note
add back heap profile HTTP API and make it secure
```

server: add back heap profile HTTP API and make it secure

---

src/storage/txn/scheduler.rs

Issue Number: Ref #15202
```commit-message
not panic in the case of unexepected dropped channel when shutting dowm
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

scheduler: not panic in the case of unexepected dropped channel when shutting dowm

---

components/raftstore/src/store/config.rs
src/config/mod.rs

Issue Number: Close #15438
```commit-message
fix unwrap panic of region_compact_redundant_rows_percent
```
Tests 
- Unit test
```release-note
None
```

raftstore: fix unwrap panic of region_compact_redundant_rows_percent

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer_storage.rs
tests/failpoints/cases/test_split_region.rs

Issue Number: Close #13311 
When a replicated uninitialized peer is destroyed when its related new region is also being created by region split at the same time, the region meta information could be inconsistent thus causing tikv panic.
Try to check the meta information when destroying an uninitialized peer, if it's initialized in the meta information delete related information to keep consistency.
```commit-message
Fix the possible meta inconsistency issue.
```
Tests 
- Unit test
Side effects
```release-note
Fix the tikv panic caused by inconsistent region meta information.
```

raftstore: fix meta inconsistency issue

---

components/server/src/common.rs
components/server/src/server.rs
components/server/src/server2.rs
src/config/mod.rs

Issue Number: Close #15424
```
Adjust background compaction count when max-background-jobs or max-background-flushes changed
```
Tests 
- Unit test
Side effects
```release-note
None
```

config: support changed adjust max-background-compactions dynamically

---

components/resolved_ts/src/endpoint.rs
components/resolved_ts/src/errors.rs
components/resolved_ts/src/resolver.rs
components/resolved_ts/src/scanner.rs
components/resolved_ts/tests/integrations/mod.rs
components/resolved_ts/tests/mod.rs
src/config/mod.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: Close #14864
```commit-message
Fix resolved ts OOM caused by Resolver tracking large txns. `ObserveRegion` is
deregistered if it exceeds memory quota. It may cause higher CPU usage because
of scanning locks, but it's better than OOM.
```
Running a transaction that updates 100,000,000 lines.
Left: master branch, right: this PR.
Tests 
Side effects
```release-note
Fix an OOM issue that is caused by stale read tracking large transactions. 
```

resolved_ts: re-register region if memory quota exceeded 

---

components/raftstore-v2/src/operation/command/admin/compact_log.rs
components/raftstore-v2/src/operation/life.rs
components/raftstore-v2/src/raft/peer.rs

```commit-message
- Initialize `persisted_apply_index` on startup.
```
https://github.com/pingcap/tidb/issues/45517
#15332
Tests 
- Unit test
```release-note
None
```

raftstore-v2: init persisted_tablet_index on startup

---

Cargo.lock
Cargo.toml
cmd/tikv-ctl/src/cmd.rs
cmd/tikv-ctl/src/executor.rs
cmd/tikv-ctl/src/main.rs
components/backup-stream/src/subscription_track.rs
components/cdc/src/delegate.rs
components/cdc/src/initializer.rs
components/raftstore/src/store/util.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/src/metrics.rs
components/resolved_ts/src/resolver.rs
components/server/src/server.rs
components/server/src/server2.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
src/server/raftkv2/mod.rs
src/server/service/debug.rs
src/server/service/mod.rs

Issue Number: ref #15082 
```commit-message
Cherry pick #15099 and #15327: add get_region_read_progress command in tikv-ctl
```
Tests 
Side effects
```release-note
Add get_region_read_progress command in tikv-ctl
```

ctl: add get_region_read_progress (release-7.1)

---

components/resolved_ts/src/lib.rs
components/resolved_ts/src/resolver.rs

Issue Number: Close #15458
```commit-message
Resolver owns a hash map to tracking locks and unlock events, and so
for calculating resolved ts. However, it does not shrink map even after
all lock are removed, this may result OOM if there are transactions
that modify many rows across many regions. The total memory usage is
proportional to the number of modified rows.
```
Tests 
- Unit test
```mysql
sysbench --db-driver=mysql --mysql-host=<HOST> --mysql-port=<PORT> --mysql-user=root \
--mysql-db=test --tables=2 --table-size=100000000 --create_secondary=false \
./oltp_update_index prepare
-- warm up cache and others.
update sbtest1 set c='a';
-- sbtest2 leak.
update sbtest2 set …
```

resolved_ts: shrink resolver lock map

---

components/raftstore/src/store/worker/read.rs
tests/failpoints/cases/test_witness.rs

Issue Number: Close #15468
```commit-message
Return `RegionNotFound` while cannot find peer in the current store.
```
Tests 
- Unit test
```release-note
Fixed a bug that may cause slow queries after moving peer while follower read enabled.
```

raftstore: don't return is_witness while region not found

---

components/engine_panic/src/db_options.rs
components/engine_rocks/src/db_options.rs
components/engine_traits/src/db_options.rs
src/config/mod.rs

Issue Number: Close #15503
```commit-message
fix panic of dynamic changing write-buffer-limit
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: fix panic of dynamic changing write-buffer-limit

---

components/test_raftstore-v2/src/util.rs
components/test_raftstore/src/util.rs
tests/failpoints/cases/test_early_apply.rs
tests/failpoints/cases/test_split_region.rs
tests/failpoints/cases/test_stale_read.rs
tests/integrations/raftstore/test_early_apply.rs
tests/integrations/raftstore/test_lease_read.rs

Issue Number: Ref #15409
```commit-message
reuse failpoint tests in test_early_apply
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: reuse failpoint tests in test_early_apply.rs

---

components/engine_traits/src/flush.rs
components/raftstore-v2/src/operation/ready/apply_trace.rs
tests/integrations/raftstore/test_bootstrap.rs

Issue Number: Ref #15461 
```commit-message
limit the flush times during server stop
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: limit the flush times during server stop

---

components/resolved_ts/src/endpoint.rs
components/resolved_ts/src/metrics.rs
components/resolved_ts/src/resolver.rs
components/resolved_ts/src/scanner.rs
components/resolved_ts/tests/failpoints/mod.rs
components/tikv_util/src/memory.rs
metrics/grafana/tikv_details.json

Issue Number: ref #14864
```commit-message
* Fix resolved ts OOM caused by adding large txns locks to `ResolverStatus`.
* Add initial scan backoff duration metrics.
```
Tests 
```release-note
None
```

resolved_ts: track pending lock memory usage

---

components/cdc/src/channel.rs
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/errors.rs
components/cdc/src/initializer.rs
components/cdc/tests/failpoints/mod.rs
components/cdc/tests/failpoints/test_memory_quota.rs
components/cdc/tests/mod.rs
components/resolved_ts/src/resolver.rs

Issue Number: Close #15412 
```commit-message
Similar to resolved-ts endpoint, cdc endpoint maintains resolvers for
subscribed regions. These resolvers also need memory quota, otherwise
they may cause OOM.
This commit lets cdc endpoint deregister regions if they exceed
memory quota.
```
Tests 
```mysql
sysbench --db-driver=mysql --mysql-host=<HOST> --mysql-port=<PORT> --mysql-user=root \
--mysql-db=test --tables=1 --table-size=100000000 --create_secondary=false \
./oltp_update_index prepare
update sbtest1 set c='a';
```
| master branch | this fix |
| -- | -- |
| ![image](https://github.com/tikv/tikv/assets/2150711/e243e055-d0fa-4790-887f-6d31880de9ad) | …

cdc: deregister delegate if memory quota exceeded

---

components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/command/write/ingest.rs
components/raftstore-v2/src/operation/ready/apply_trace.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/raft/apply.rs
components/raftstore-v2/src/router/internal_message.rs
components/raftstore-v2/src/router/mod.rs
tests/failpoints/cases/test_import_service.rs

Issue Number: Close #15461
```
Add ingest sst index to ApplyRes and return it to raftstore and store these ingest index in apply trace. In check advance admin index, if there are and sst ingest before this flush, directly trigger a new flush. And also try to gc stale sst files after the write task is persisted.
```
Tests 
- Unit test
- In my local env, after this change there is no sst files leat in the import dir after br restore. Before this change, there are handreds of ssts there.
- No code
Side effects …

raftstore-v2: persist applied index after ingset sst

---

src/server/status_server/mod.rs

Issue Number: Close #15588
```commit-message
add option to update TiKV config without persist in status API  "POST /config?persist=false|true"
```
Tests 
- Unit test
```release-note
Support update config without actually persisting config to disk. This is to refresh config on container environment when the disk is read-only. 
By default, POST /config would refresh the config and persisting the update to disk. However, if POST /config?persist=false, the persistence to disk would be skipped. 
```

add option to update config without persist

---

Cargo.lock
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_unsafe_recovery.rs

Issue Number: Close #15580
```commit-message
Enable force leader to rollback merges when they are not able to proceed, previously, only regions with quorum can do this.
```
N/A
Tests 
Side effects
n/a
```release-note
None
```

unsafe recovery: Enable force leader to rollback merge

---

components/raftstore-v2/src/worker/tablet.rs

Issue Number: Close #15615
```
Add a loop to wait async pause_background_work task finish before trying to clean up tablet.
The `pause_background_work` task can block tablet's close because it also hold a valid arc reference.
```
Tests 
- Unit test
Side effects
```release-note
None
```

test: make test test_destroy_missing more stable

---

components/raftstore-v2/src/operation/command/admin/merge/commit.rs
components/raftstore-v2/src/operation/command/admin/merge/rollback.rs
components/raftstore-v2/src/raft/peer.rs
tests/failpoints/cases/test_merge.rs

Issue Number: Ref #15242
```commit-message
fix rollback merge and commit merge can happen simultaneously
```
See comments of `test_concurrent_between_transfer_leader_and_merge ` to see the reproduce steps.
Tests 
- Unit test
```release-note
None
```

raftstore-v2: fix rollback merge and commit merge can happen simultaneously

---

components/backup-stream/src/router.rs

Issue Number: Close https://github.com/tikv/tikv/issues/15602
add uuid for temporary files to avoid race as describe in above issue.
```commit-message
```
Tests 
- Unit test
Side effects
```release-note
Fix the issue that log backup may get stuck when flush too frequently.
```

log backup: fix the race of on events and do flush

---

Cargo.lock
components/engine_rocks/src/cf_options.rs
src/config/configurable.rs
src/config/mod.rs

Issue Number: Ref #14320
```commit-message
support online change lock write buffer limit
```
Also, add some tests for change write buffer size.
Tests 
- Unit test
```release-note
None
```

raftstore-v2: support online change lock write buffer limit

---

Cargo.lock
Cargo.toml
components/concurrency_manager/Cargo.toml
components/tikv_util/Cargo.toml

It's a cherry-pick to `release-6.5` from https://github.com/tikv/tikv/pull/15622.
Issue Number: Ref #15621
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

cherry-pick-releases-6.5: upgrade tokio v6.5

---

components/raftstore-v2/src/operation/command/admin/merge/commit.rs
tests/integrations/raftstore/test_merge.rs

Issue Number: Close #15672
```commit-message
This commit addresses the issue of orphan peers remaining in TiKV due to the
absence of GcPeer tick registration after commit merge. The lack of regular
checks on removed_records and merged_records can lead to delays in detecting
and resolving these issues.
To improve this, we have implemented a solution that ensures TiKV registers
the GcPeer tick after commit merge. This change enables regular checks on
the removed_records and merged_records, preventing them from being overlooked
for an extended period.
```
Tests 
```release-note
None
```

raftstore-v2: check gc peer after commit merge

---

components/raftstore/src/store/entry_storage.rs

Issue Number: Close #15289
```commit-message
Remove the incorrect assert. 
In master, the related PR is #15243, but it's too big to cherry-pick. 
```
Tests 
- No code
```release-note
None
```

remove the unhold assert in warmup raft entry

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/life.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/router/message.rs
components/test_pd_client/src/pd.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
components/tikv_kv/src/raft_extension.rs
src/server/lock_manager/deadlock.rs
src/server/lock_manager/mod.rs
src/server/metrics.rs
src/server/raft_client.rs
src/server/raftkv2/raft_extension.rs
src/server/resolve.rs
src/server/server.rs
tests/failpoints/cases/mod.rs
tests/failpoints/cases/test_life.rs
tests/integrations/config/dynamic/pessimistic_txn.rs
tests/integrations/server/raft_client.rs

Issue Number: Close #15669
```commit-message
Let leader directly GC removed_records and merged_records on tombstone store,
instead of sending GcPeerRequests to such store.
```
Tests 
```release-note
None
```

raftstore-v2: gc removed_records and merged_records on tombstone store 

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/event_loader.rs
components/backup-stream/src/subscription_manager.rs
components/backup-stream/src/subscription_track.rs
components/backup-stream/src/utils.rs
components/backup-stream/tests/integration/mod.rs
components/backup-stream/tests/suite.rs
components/raftstore/src/router.rs
src/config/mod.rs

This reverts commit 9b76ac97e1de01c1b0e70af406720b2c368d9624.
Issue Number: Close #15714 
revert 15541 on release-7.4
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
If this PR will be picked to release branch, …
```

Revert "log-bakcup: make initial scan asynchronous (#15541)"

---

Cargo.lock
cmd/tikv-ctl/src/main.rs
src/config/mod.rs
src/server/engine_factory.rs
tests/integrations/storage/test_titan.rs

Issue Number: ref #11470
```
Set a longer rocksdb io limiter smooth window for raft-v2, this can make the compaction io through stabler. Thus, the fore ground qps can also be stabler.
```
Tests 
- Unit test
- In my benchmark, after this change, the qps of sysbench oltp_write_only can be much stabler because the compaction io is stabler. 
Side effects
```release-note
None
```

config: set a longer rocksdb io limiter smooth window for raft-v2

---

components/raftstore/src/coprocessor/config.rs
src/config/mod.rs

Issue Number: Ref #15719
```commit-message
disable region bucket for raftstore v1 by default
```
Tests 
- Unit test
```release-note
None
```

raftstore: disable region bucket for raftstore v1 by default

---

components/raftstore-v2/src/operation/command/admin/merge/commit.rs
components/raftstore-v2/tests/failpoints/test_merge.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_merge.rs

Issue Number: Close #15682
```commit-message
This commit addresses the issue where a "region corrupted" error still
occurs in certain scenarios despite PR #15625 resolving the problem in
the transfer leader scenario. The root cause of the issue is the
non-deterministic nature of commit merge and rollback merge, allowing
transient errors during propose to trigger the problem again.
To fix this issue, the proposed solution ensures that TiKV only
initiates rollback merge when either the target region is not found or
the epoch has increased.
```
Tests 
```release-note
Fix an issue that may cause "region corrupted" panic during region merge.
```

raftstore-v2: fix non-deterministic region merge

---

src/coprocessor/dag/mod.rs

Issue Number: ref #15566
```
Fix the bug that coprocessor may convert DeadlineExceeded error to Other error so tidb can handle backoff correctly.
```
Tests 
- Unit test
Side effects
```release-note
None
```

coprocessor: do not treat deadline exceeded error as other error

---

src/config/mod.rs

Issue Number: ref #14470
In my benchmark in the internal benchbot service(sysbench 32 tables with each 10m rows) , oltp_write_only is 4% better and oltp_insert is about 2% better. The result shows that at least there is no performance regression after this change. And I my previous 10 hours long running benchmarks(oltp_write_only, sysbench prepare), no write stall occured and the pending compaction bytes did not significantly increase.
```
Decrease default rocksdb background compaction threads for raft-v2 to make qps stabler.
```
Tests 
- Unit test
Side effects
```release-note
None
```

raftstore-v2: adjust max-background-flushes default value

---

components/raftstore-v2/src/operation/command/write/mod.rs
components/raftstore-v2/src/operation/mod.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/simple_write.rs
tests/failpoints/cases/test_transaction.rs
tests/integrations/storage/test_raftkv.rs

Issue Number: Ref #14390
```commit-message
avoid follower forwarding propose msg
```
This PR fixes the panic of "txn record found but not expected".
Now, validation and propose may not be atomic, which means a raft message in between with higher term can make the node become follower. So, when it begins to propose, it's not a leader which triggers a msg forward.
Forwarding proposal msg by follower can make proposal be proposed twice which is decribed in the comment
of the test in this PR. So, if a `prewrite` is proposed twice where the `commit` is proposed between them, the lock
with `start_ts` of the comitted txn will lock again, leading to the panic.
The PR also removes the `notify_proposed` in `add_response_channel`, as the propose may fail even it passes the validation …

raftstore-v2: avoid follower forwarding propose msg

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/unsafe_recovery/demote.rs
components/raftstore-v2/src/operation/unsafe_recovery/force_leader.rs
components/raftstore-v2/src/operation/unsafe_recovery/report.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/unsafe_recovery.rs
tests/failpoints/cases/test_unsafe_recovery.rs
tests/integrations/raftstore/test_unsafe_recovery.rs

Issue Number: Close https://github.com/tikv/tikv/issues/15629
```commit-message
Introduce failed state for unsafe recovery to fix rollback merge timeout. 
To rollback merge, it has to be in force leader state when performing online recovery. Force leader state would exit after executing the plan no matter succeeded or failed. While rollback merge is triggered on check merge tick periodically. So there is a chance that check merge can't always be in the time window of being force leader state. To solve that, let it skip exiting force leader state when failed to demote, so later rollback merge can be triggered.
```
Tests 
- Unit test
```release-note
Fix online recovery panic on exit force leader
```

raftstore: Introduce failed state for unsafe recovery to fix rollback merge timeout

---

components/raftstore/src/store/worker/metrics.rs
components/raftstore/src/store/worker/read.rs
tests/failpoints/cases/test_kv_service.rs
tests/failpoints/cases/test_replica_stale_read.rs

Issue Number: Ref #14553 
When the local peer handling the stale read encounters a 'data is not ready' error, if the current local peer is a valid leader, attempt to directly fallback to leader snapshot read processing instead of returning an error directly to the KV client.
Save unnecessary handling of 'data not ready' errors and gRPC request processing, because the KV client will fallback to the leader peer for snapshot read upon receiving a 'data not ready' error too.
From the local test using command
```
mysqlslap --user=root --host=127.0.0.1 --port=4000 --create-schema=test --concurrency=10 --iterations=10000 --query="set tidb_read_staleness = '-5'; use test; select * from sbtest1 where id = 1"
```
Master:
This PR:
- There's no data is not ready error in the kv …

retry leader read when stale read encounters data not ready

---

src/config/mod.rs

Issue Number: ref #14470
```
#15723 change the default rocksdb background compaction threads to cpu-num * 1/8, this default config is too small that it can easily trigger flow control because for a 8c instance there is only 1 compaction thread. If there is a on-going slow compaction, it can block the lockcf's compaction and triggers flow control. This PR changes the default to cpu-num * 1/4
```
Tests 
- Unit test
Side effects
```release-note
None
```

config: adjust rocksdb background compaction threads

---

components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/life.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/router/message.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/local_metrics.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/msg.rs
metrics/grafana/tikv_details.json
src/server/server.rs
tests/failpoints/cases/test_merge.rs

Issue Number: Ref #15175
```commit-message
Add more metrics for slow commit log duration investigation. 
In this PR, it adds raft message process wait duration and exposes raft
message recv by store counter. Together with raft-engine write duration,
we can further narrow reason of the commit log duration. With this PR,
we still cannot tell if the slowness comes from network or
raft-client's (grpc client).  
```
```release-note
None
```

add more metrics for slow commit log diagnostics

---

Cargo.lock
components/engine_rocks/Cargo.toml

Issue Number: Close https://github.com/tikv/tikv/issues/15351
```commit-message
update titan to avoid manifest mutex
```
Tests 
- No code
```release-note
Avoid holding mutex when writing titan manifest
```

titan: update titan to avoid manifest mutex on release-7.1

---

components/cloud/aws/src/s3.rs
components/cloud/src/blob.rs

Issue Number: Close https://github.com/pingcap/tidb/issues/39832
Issue Number: Close https://github.com/tikv/tikv/issues/15781
1. support retrive `session-token` from input. 
2. support assume role with `role-arn` and `extrenal-id` and keep the same behavior with tidb side.
```  
s3: support backup with session token and assume role
```
Tests 
session-token:
1. set env of token.
```
export AWS_ACCESS_KEY_ID="xxx"
export AWS_SECRET_ACCESS_KEY="yyy"
export AWS_SESSION_TOKEN="zzz"
```
2. do a full backup and check backup data in s3.
role-arn:
1. prepare two AWS account (A, B).
2. create a bucket in account A.
3. create a role for …

s3: support backup with session token and assume role

---

components/tikv_util/src/lru.rs

Issue Number: Ref #11187
```commit-message
This PR makes the `LruCache` in `tikv_util` to support customizing how to determine an entries in the cache should be evicted.
This is part of solving the issue #11187, which needs a `TxnStatusCache`. The `TxnStatusCache` is desinged to use `LruCache` internally, with ability to get or insert items without promoting items to the head (most-recently-used) position. This PR adds `get_no_promote` and `insert_if_not_exist` functions to `LruCache`.
```
Tests 
- Unit test
Side effects
\-
```release-note
None
```

tikv_util: Support customizing evict policy and operations without promoting for LruCache

---

components/raftstore-v2/src/operation/command/admin/merge/commit.rs
components/raftstore-v2/src/operation/command/admin/merge/prepare.rs
components/raftstore-v2/src/operation/command/admin/mod.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_unsafe_recovery.rs

Issue Number: Ref #15580
```commit-message
Allow rollback merge during unsafe recovery for raftstore v2
```
Tests 
Side effects
n/a
```release-note
None
```

raftstore-v2: Allow rollback merge during unsafe recovery for raftstore v2

---

metrics/grafana/tikv_details.json

Issue Number: Close #15832
We use regex `/type="([^"]+)"/` to grep the command variables. In cloud env, there is a field called `instance_type` apart from `type`. So it would accidentally grep the name of `instance_type`.
```commit-message
Fix wrong scheduler command variables of grafana in cloud env by adding a `\b` to regex to make sure it's at the word boundary.
```
Tests 
Before
After
```release-note
Fix wrong scheduler command variables of grafana in cloud env
```

grafana: Fix wrong scheduler command variables of grafana in cloud env

---

components/raftstore/src/store/peer.rs
components/test_pd_client/src/pd.rs
tests/integrations/raftstore/test_replication_mode.rs

Issue Number: Close #15817
```commit-message
When splitting a region, group commit is mistakenly enabled in the sync-recover state. 
If the region is in joint state and demoting voter is down, the commit condition can't meet. 
Fix group commit is mistakenly enabled in sync recover state
```
Tests 
- Unit test
```release-note
Fix possible timeout leave joint state for dr auto sync when doing scaling out
```

raftstore: Fix group commit is mistakenly enabled in sync recover state

---

metrics/alertmanager/tikv.accelerate.rules.yml
metrics/alertmanager/tikv.rules.yml
metrics/grafana/performance_read.json
metrics/grafana/tikv_details.json
metrics/grafana/tikv_fast_tune.json
metrics/grafana/tikv_trouble_shooting.json

Issue Number: Close #15859
```
- Fix the incorrect expression on `tikv_futurepool_pending_task_total ` by changing the aggregation function from `rate` to `avg_over_time`
- Fix grafana relate to `tikv_coprocessor_request_wait_seconds_bucket` by add "type=all"
```
Result:
before this change, when running oltp_write_only with 50 threads on a 8c tikv:
after this change:
Tests 
- No code
Side effects
```release-note
None
```

metrics: fix 2 incorrect grafana expression

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

Issue Number: Close #15878
Add the collation information in the execution of `field` function, so that it can compare the string according to the collation.
Tests 
- No code
```release-note
Fix the issue that the result of `field` function is incorrect for non-binary collations.
```

tidb_query_expr: fix the behavior of `field` function

---

Cargo.lock
components/online_config/Cargo.toml
components/online_config/src/lib.rs
components/raftstore/Cargo.toml
components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/worker/compact.rs
components/raftstore/src/store/worker/metrics.rs
components/tikv_util/src/config.rs
tests/integrations/config/mod.rs

Issue number: ref tikv/tikv#12729
Adds the concept of a full compaction: a compaction that compacts
all columns families, ranges, and levels. this has the effect of
deleting all of the tombstone markers.
If ``raftstore.periodic-full-compact-start-times`` is set, run full
compaction only during the hours specified if normal I/O can be handled
and CPU load is low (below ``raftstore.periodic-full-compact-start-max-cpu`` 
which is `0.1` by default.)
The tikv.yaml segment below will run compaction at 03:00 and 23:00
(3am and 11pm respectively) in the tikv nodes' local timezone if CPU
usage is below 90%.
```
[raftstore]
periodic-full-compact-start-max-cpu = 0.9
periodic-full-compact-start-times = ["03:00", "23:00"]
```
If ``raftstore.periodic-full-compact-start-times`` is not set, periodic full …

rafstore, engine_rocks: periodic full compaction (#12729)

---

components/cdc/src/endpoint.rs
components/cdc/src/initializer.rs
src/config/mod.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: Close #11390 
```commit-message
None
```
Tests 
- Unit test
Side effects
```release-note
None
```

cdc: limit cdc event fetching speed to reduce RocksDB read load

---

src/server/service/kv.rs

Issue Number: : ref https://github.com/tikv/tikv/issues/15803
```commit-message
the grpc duration should not  include the stream sink.
```
Tests 
Side effects
```release-note
None
```

server: make grpc metrics consistent

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/pd.rs
tests/integrations/raftstore/test_merge.rs
tests/integrations/raftstore/test_stale_peer.rs

Issue Number: Close #15919
```commit-message
A "stale peer" refers to a peer that still exists on a TiKV node but
has been removed from the raft group, typically through a confchange
operation. TiKV performs regular checks and validations on its peers
to ensure that no such stale peer exists.
However, the current stale peer check is not enough when dealing with
uninitialized stale peers that its region has been merged. These
uninitialized stale peers are left indefinitely, consuming CPU, memory,
and blocking resolved ts.
This commit introduces an in-memory state for peers whose raft messages
create uninitialized stale peers. The stale peer then sends a
MsgCheckStalePeer message to the corresponding peer, validating whether
it should be removed.
```
- PR to update …

raftstore: gc uninitialized stale peer after merge

---

Makefile

Issue Number: ref  #15967
```
Because `cargo test` won't fail the test when a background thread panic,
do not capture the test output can at least make it easier to reason
about some unexpected behavior such as timeout caused by panic.
```
Tests 
- No code
Side effects
```release-note
None
```

test: do not capture test output in make test_with_nextest

---

.dockerignore
Cargo.lock
Cargo.toml
Dockerfile.FIPS
Makefile
cmd/tikv-ctl/Cargo.toml
cmd/tikv-server/Cargo.toml
components/backup-stream/Cargo.toml
components/encryption/Cargo.toml
components/encryption/export/Cargo.toml
components/encryption/src/io.rs
components/engine_rocks/Cargo.toml
scripts/check-bins.py
src/lib.rs

Issue Number: Close #15943
Requires https://github.com/tikv/rust-rocksdb/pull/774
```commit-message
Currently, TiKV binaries are statically linked to the OpenSSL library,
preventing the use of the host system's OpenSSL.
This commit adds an option to build TiKV with dynamic linking of the
OpenSSL library, enabling TiKV to utilize the host system's OpenSSL.
This is particularly useful in FIPS scenarios where TiKV needs to
delegate cryptographic operations to the host FIPS OpenSSL.
By default, this option is disabled, and TiKV continues to statically
link the OpenSSL library.
```
Tests 
`ENABLE_FIPS=0 make docker`
```release-note
none
```

*: allow dynamic link openssl library

---

Makefile

This pr replaces `basename` with `command` to check the path of `python`, to fix the errors printing by `basename`.
Issue Number: Close #15980
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

makefile: polish the validation of python path.

---

Cargo.lock
Cargo.toml
cmd/tikv-ctl/Cargo.toml
cmd/tikv-ctl/src/main.rs
cmd/tikv-server/Cargo.toml
cmd/tikv-server/src/main.rs
components/backup-stream/Cargo.toml
components/cloud/Cargo.toml
components/cloud/azure/Cargo.toml
components/encryption/Cargo.toml
components/encryption/export/Cargo.toml
components/external_storage/Cargo.toml
components/file_system/Cargo.toml
components/fips/Cargo.toml
components/fips/build.rs
components/fips/src/lib.rs
components/raftstore/Cargo.toml
components/server/src/server.rs
components/server/src/server2.rs
components/server/src/setup.rs
components/sst_importer/Cargo.toml
components/tidb_query_expr/Cargo.toml
components/tikv_util/Cargo.toml
scripts/check-bins.py
src/lib.rs

Issue Number: Close #15982
```commit-message
In this commit, a new crate, "fips", is introduced. This crate includes
utilities designed to enable OpenSSL FIPS mode, catering to various OpenSSL
releases. This commit ensures that TiKV starts with OpenSSL FIPS mode
enabled if it is built with an environment variable "ENABLE_FIPS=1".
```
Tests 
- Manual test
```sh
ENABLE_FIPS=1 make docker
cd tikv
docker run --name rock9 -v $(pwd):/tikv -v ~/.cargo:/root/.cargo -v ~/.rustup/:/root/.rustup -d rockylinux:9 bash -c "tail -f -"
dnf install -y openssl-devel gcc gcc-c++ make cmake perl git
ENABLE_FIPS=1 make build
```
```release-note
None
```

fips: enable OpenSSL FIPS mode on TiKV start if it's eligible

---

components/raftstore/src/store/util.rs
components/raftstore/src/store/worker/pd.rs

In previous work and tests, we've found that the `SlowScore` will be impacted
by the duration on `store-wait` progress, which might misleading scheduling on evicting
slow nodes. For example, one TiKV node might has hot regions on WRITE with no delays
or jitters on Disk I/O. But the `store-wait-duration` will be high as there might exists many
pending commands waited to be processed.
So, in this pr, we fine-tunes `SlowScore` to make it focus on the jitters on Disk I/O
when flushing raft logs into disk.
Issue Number: ref #15909
```commit-message
```
Tests 
- Unit test
- No code
Side effects
- Performance …

raftstore: fine-tune SlowScore.

---

components/resource_control/src/resource_group.rs
src/server/service/kv.rs

Issue Number: Close #15994
```
Revert get and set resource_control_context.override_priority at handle gRPC request to avoid performance regression. We move this logic to client-go side so the overall logic keeps the same.
```
Tests 
Side effects
```release-note
None
```

resource_control: do not force set override priority at handle gRPC request

---

Cargo.lock
etc/config-template.toml
src/config/mod.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: Close #15971
```commit-message
fix titan incorrect blob file size metric and change default value
```
Tests 
- No code
```release-note
Fix titan incorrect blob file size metric and change default value
```

titan: update titan to fix incorrect blob file size and change default value

---

Dockerfile.FIPS

Issue Number: Close #16032
Use rocklinux:9 as base image. Because it has fewer security issues than ubi 8.6.
Tests 
- No code
```release-note
None
```

Dockerfile: update base image

---

components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/worker/compact.rs
components/raftstore/src/store/worker/metrics.rs
components/raftstore/src/store/worker/mod.rs
metrics/grafana/tikv_details.json

Issue Number: ref tikv/tikv#15271
```commit-message
Makes full compaction incremental, by range. Currently regions' ranges are used as increments.
Run a predicate ("load-check") function before starting full compaction and between each incremental
range.  If the function evaluates to false, pause with exponential backoff (up to a maximum duration)
until it evaluates to  true. 
If periodic full compaction is enabled, poll process CPU stats every 30 seconds to determine usage for the
"load-check"  function. If usage exceeds a certain threshold before full compaction starts, compaction will
not be started, and if started, full compaction will be paused. This cpu usage is also exported as
``tikv_storage_process_stat_cpu_usage`` gauge metric.
```
* Manual tests.
* Unit test in `compact.rs` …

raftstore: make full compaction incremental, pause when load is high

---

components/raftstore/src/store/config.rs
etc/config-template.toml
src/config/mod.rs

Issue Number: Ref #15282
```commit-message
Change the default value of raftstore.redundant-rows-percent-threshold to 20 from 100. 
This would triggers a compaction when a region has 20% entries as stale MVCC versions. 
```
Tests 
- Unit test
- No code
Side effects
```release-note
Set default value of raftstore.redundant-rows-percent-threshold to 20
```

update default value of region_compact_redundant_rows_percent

---

components/backup-stream/src/subscription_manager.rs
components/cdc/src/endpoint.rs
components/resolved_ts/src/advance.rs
src/server/service/kv.rs

Issue Number: Close #15999
- use smaller timeout when do check_leader, to to reduce the impact of a single TiKV slowing down on the advance resolve_ts of other TiKVs
Tests 
**Before**
**This PR**
Side effects
- N/A
```release-note
None.
```

resolved_ts: use smaller timeout when do check_leader

---

components/cdc/src/endpoint.rs
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: Close #16035
```commit-message
When TiCDC starts changefeed, it may send numerous requests leading to
the creation of numerous scan tasks. However, the initial surge of scan
tasks may cause OOM.
This commit aims to resolve the issue by implementing a mechanism that
allows TiKV to reject requests when the number of pending tasks reaches
a certain limit.
```
Tests 
- Unit test
```release-note
Fix an issue that TiCDC captures large table may cause TiKV OOM
```

cdc: limit pending scan tasks (#16048)

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

Issue Number: Close #16102
```commit-message
Add some necessary filters to filter out unnecessary data in metrics.
```
- PR to update `pingcap/docs`/`pingcap/docs-cn`: None.
- Need to cherry-pick to the release branch: No need
Tests 
- Generate a new `tikv_details.json` with the auto-gen tool
- Load it into grafana.
Side effects
None
```release-note
None
```

metrics: add extra filters to filter out redundant data.

---

.github/pull_request_template.md

Issue Number: Close #15990 
```commit-message
Use checkbox for check list in pull request template
```
Tests 
Side effects
```release-note
None
```

chore: Use checkbox for check list in pull request template

---

components/raftstore/src/store/fsm/peer.rs

Issue Number: ref https://github.com/tikv/tikv/issues/16111
Address comment: https://github.com/tikv/tikv/pull/16112#discussion_r1413779674
Cleanup `destroyed_region_for_snap`.
Tests 
```release-note
None
```

raftstore: clean up destroyed_region_for_snap when a peer is destroyed

---

Cargo.lock
Cargo.toml
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs

Issue Number: Ref #16035 
```commit-message
return server_is_busy to cdc clients if necessary
```
Tests 
Side effects
```release-note
None
```

cdc: return server_is_busy to cdc clients if necessary

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

By this pr, the QPS metric shows the result as expected:
Issue Number: Close #16148
```commit-message
Fix the issue where the filter label of QPS, in the tikv grafana, lacks the label `type`.
```
Tests 
Side effects
```release-note
None.
```

Fix the QPS metrics in tikv_details.json.

---

components/raftstore/src/store/config.rs

Issue Number: Close #15800
```commit-message
setting raftstore.evict-cache-on-memory-ratio = 0.1
```
Tests 
```release-note
setting default value of raftstore.evict-cache-on-memory-ratio to 0.1
```

enable entry cache evict on high cpu

---

components/cdc/src/endpoint.rs
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

This reverts commit 22d397b4e6908e520743a256c7b312a190be1d4b.
```commit-message
```
Tests 
Side effects
```release-note
None
```

revert "cdc: limit pending scan tasks (#16048) (#16054)"

---

Cargo.lock
Cargo.toml
components/engine_panic/src/misc.rs
components/engine_rocks/src/misc.rs
components/engine_traits/src/misc.rs
components/hybrid_engine/Cargo.toml
components/hybrid_engine/src/engine.rs
components/hybrid_engine/src/lib.rs
components/hybrid_engine/src/misc.rs
components/raftstore/src/compacted_event_sender.rs
components/region_cache_memory_engine/Cargo.toml
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/lib.rs
components/server/Cargo.toml
components/server/src/common.rs
components/server/src/server.rs
components/snap_recovery/src/init_cluster.rs
components/snap_recovery/src/region_meta_collector.rs
components/snap_recovery/src/services.rs
src/config/mod.rs

```commit-message
Integrate hybrid engine with TiKV. User can choose to use hybrid engine by set `memory_engine_enabled` in TiKV config.
```
This PR refactors some parts mainly in component/server to replace RocksEngine by generic type implementing KvEngine.
So we can make `HybridEngine` as a specific type that implements KvEngine be used by TiKV server, RaftKv, raftstore and so on.
Tests 
Side effects
```release-note
None
```

In-memory Engine: integrate hybrid engine with TiKV

---

src/coprocessor/endpoint.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/15881
Pick https://github.com/tikv/tikv/pull/15882 to the standalone branch.
```commit-message
Change the coprocessor error response log level to DEBUG.
```
Tests 
```release-note
None
```

coprocessor: change the log level to debug for cop error response

---

src/lib.rs

Issue Number: Close #16200
See #16199
Do not suffix "fips" for tikv version ouput
```commit-message
```
Tests 
- Manual test 
`tikv-server -V`
```release-note
None
```

*: do not suffix "fips" for tikv version ouput

---

components/raftstore/src/store/txn_ext.rs
src/storage/mod.rs
src/storage/mvcc/metrics.rs
src/storage/mvcc/reader/reader.rs
tests/integrations/server/kv_service.rs

Issue Number: Ref #15066 #16158 
```commit-message
Change in-memory pessimsitic locks from hash map to btree map, support collecting pessimistic locks for scan lock command.
Then:
1. GC could collect expired pessimistic locks.
2. Pessimistic rollback could use read scan first and then clean up expired pessimistic locks at one time.
```
From the sysbench `oltp_write_only` tests, there are not much performance difference
PR:
Throughput:
events/s (eps):                      5082.2634
time elapsed:                        600.0055s
total number of events:              3049386
Master:
Throughput:
events/s (eps):                      4971.9635
time elapsed:                        600.0060s
total number of events:              2983208
Besides @zyguan has helped to verify that in …

txn: change memory pessimsitic lock to btree map and support scan

---

Cargo.lock
components/tidb_query_datatype/src/codec/mysql/time/mod.rs

Issue Number: ref #16220 Close pingcap/tidb#49586
```commit-message
Brazil no longer observes DST since 2020[1]. Updating chrono-tz from
0.5.1 to 0.5.2 bumps the timezone database from 2018i to 2020a, which
includes this change, thus fixes the issue.
[1]: https://en.wikipedia.org/wiki/Daylight_saving_time_in_Brazil
```
Tests 
```release-note
Fix an issue about some timezone conversion including Brazil and Egypt.
```

tidb_query_datatype: fix timezone conversion by upgrading chrono-tz

---

components/server/src/server.rs
components/server/src/server2.rs

Issue Number: Close #16236 
```commit-message
Set thread group properties for gRPC threads to avoid panic when checking "is_shutdown".
```
Tests 
Side effects
```release-note
Set thread group properties for gRPC threads to avoid panic when checking "is_shutdown".
```

server: fix panic of gRPC threads due to thread group properties not set

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_controller.rs
tests/integrations/raftstore/test_split_region.rs

Issue Number: Close https://github.com/tikv/tikv/issues/15539
I try to redirect the split command in tikv layer but found it not easy to do because the raftcommand is not designed to send between raft nodes. But using `RaftMessage` should add a new raft message and make it more complex.
On the other hand, the proposal can be a propose on the follower node, and the raft layer will redirect:
https://github.com/tikv/raft-rs/blob/65a00620d80a89603c3358fd4b90265a692ae767/src/raft.rs#L2302-L2315
```commit-message
raftstore: fix load base split cannot works in pure follower/stale read scenario
- allow split command proposal on non leader peer
```
Tests 
Side effects
```release-note
None
```

raftstore: fix load base split cannot works in pure follower/stale read scenario

---

Cargo.lock
src/config/mod.rs
tests/integrations/storage/test_titan.rs

Issue Number: Ref #16245 
```commit-message
Enable titan for newly created instance
```
Tests 
Side effects
```release-note
Enable titan for newly created instance
```

config: Enable titan for newly created instance

---

src/storage/mvcc/reader/reader.rs

Issue Number: Ref #16340
```commit-message
Try to fix the possible deadlock caused by scan lock.
```
Tests 
```rust
#[test]
fn test_rw_lock() {
fn test_check_term_version_status(locks: &PeerPessimisticLocks) -> Result<(), ()> {
let version = locks.version;
Ok(())
}
let peer_locks = PeerPessimisticLocks::from_locks(vec![
lock_with_key(b"key1", false),
lock_with_key(b"key2", false),
lock_with_key(b"key3", false),
]);
let lock = std::sync::Arc::new(RwLock::new(peer_locks));
let running = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(true));
let l_read = lock.clone();
let r = running.clone();
let t0 = std::thread::spawn(move || {
while r.load(Ordering::SeqCst) {
// Impl 1.
// let res = match test_check_term_version_status(&l_read.read()) {
//     Ok(_) => {
// …
```

txn: try to fix the possible deadlock caused by scan lock

---

Cargo.lock

This is a manual cherry-pick of https://github.com/tikv/tikv/pull/16294
Issue Number: close https://github.com/tikv/tikv/issues/16324 ref https://github.com/tikv/raft-engine/pull/346
```commit-message
Update `raft_log_engine` lib to the latest version, to fix some issues, including:
- rewrite: optimize the interval of sync when rewriting memtables #347.
- Return error instead of panicking if rewriting fails #343.
```
Tests 
Side effects
```release-note
None
```

[cherry-pick-7.5] raft_log_engine: update to latest version. (#16294)

---

src/coprocessor/interceptors/concurrency_limiter.rs

```commit-message
The original test use select! to check t1 is finished before t2, but this is unstable when the select! is called when both t1 and t2 is finished. From the rust doc we can see " If multiple futures are ready, one will be pseudo-randomly selected at runtime."
which means if both future is ready, which is polled first is not determined. So this PR uses a atomic value to determine t1's complete to make the result stable.
```
In my local test, I add an extra sleep to emulate `select!` call delay in which case both future are ready.
```
...
let deadline = sleep(Duration::from_millis(1500)).fuse();
futures::pin_mut!(deadline);
// manual add a extra sleep to wait both future ready.
sleep(Duration::from_millis(1000)).await;
loop { …
```

test: fix unstable test test_limit_concurrency

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_controller.rs
tests/integrations/raftstore/test_split_region.rs

This reverts commit defc9338fd9e0539db86e0998e4e889334cc94d4.
Issue Number: Ref https://github.com/tikv/tikv/issues/16314
will use other way to implement.
```commit-message
```
Tests 
Side effects
```release-note
None
```

Revert "raftstore: fix load base split cannot works in pure follower scenario

---

components/cdc/src/delegate.rs
components/cdc/src/initializer.rs
components/tikv_util/src/config.rs

Issue Number: Close #16362 
* make incremental scans use correct ranges instead of snapshot boundaries;
* make timstamp filter of incremental scans use correct ranges instead of snapshot boundaries.
```commit-message
```
Tests 
Side effects
```release-note
None
```

cdc: incremental scans use correct specified ranges

---

components/tikv_util/src/logger/mod.rs

Issue Number: Close #16398 
```commit-message
The current "thread_id" in the log is always 0x5. This is because:
1)TiKV logs asynchronously by sending all log records to a dedicated
thread called "slogger", which is the fifth thread spawned by TiKV;
and 2) "thread_id" is evaluated lazily by the "slogger" thread.
To fix this issue, this commit obtains the "thread_id" before sending
it to the "slogger" thread.
```
Tests 
<details><summary>Logs on master branch</summary>
<p>
```log
[2024/01/03 15:11:49.005 +08:00] [INFO] [lib.rs:88] ["Welcome to TiKV"] [thread_id=0x5]
[2024/01/03 15:11:49.006 +08:00] [INFO] [lib.rs:93] ["Release Version:   7.6.0-alpha"] [thread_id=0x5]
[2024/01/03 15:11:49.006 +08:00] [INFO] [lib.rs:93] ["Edition:           Community"] [thread_id=0x5] …
```

logger: fix thread_id in log

---

components/tidb_query_expr/src/impl_math.rs

Issue Number: Close #16407
When the result of `pow` is out of range, the error message in TiDB looks like this
```
DOUBLE value is out of range in 'pow(-36452.389, 382218415)'
```
But in TiKV, the error message is 
```
DOUBLE value is out of range in '-36452.389.pow(382218415)'
```
It may make some tests fail, this pr change the error format in TiKV
Tests 
Side effects
```release-note
make the error format the same as tidb when the result of `pow` is out of range
```

coprocessor: make the error format the same as tidb

---

Cargo.lock
components/hybrid_engine/src/write_batch.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/write_batch.rs

Issue Number: Ref #16323 
```commit-message
Basic WriteBatch implementation for In-Memory Engine.
```
Tests 
Side effects
```release-note
None
```

In-Memory Engine: WriteBatch implementation.

---

components/raftstore/src/store/fsm/peer.rs
tests/failpoints/cases/test_hibernate.rs

This is a manul cherry-pick of #16408.
Issue Number: Close https://github.com/tikv/tikv/issues/16368
```commit-message
This pull request addresses a corner case where `WakeUp` messages were being
ignored during I/O hang scenarios.
```
Previously, in the nightly branch, there was a possibility of Peers entering the `PreChaos` state by `on_check_peer_stale_state_tick` scheduler before handling `WakeUp` messages. In such cases,
these Peers would ignore `WakeUp` messages triggered by the "awaken hibernate regions" mechanism. 
Consequently, the recovery duration would last longer than expected.
In this pull request, when the `raftstore` forcibly receives `WakeUp` messages -- indicating the presence of I/O hang problems in the cluster -- the relevant `raftstore` will promptly …

[cherry-pick-v6.5] raftstore: address the corner case on WakeUp hibernate regions. (#16408)

---

components/raftstore/src/store/fsm/peer.rs
tests/failpoints/cases/test_hibernate.rs

This is a manul cherry-pick of #16408.
Issue Number: Close https://github.com/tikv/tikv/issues/16368
```commit-message
This pull request addresses a corner case where `WakeUp` messages were being
ignored during I/O hang scenarios.
```
Previously, in the nightly branch, there was a possibility of Peers entering the `PreChaos` state by `on_check_peer_stale_state_tick` scheduler before handling `WakeUp` messages. In such cases,
these Peers would ignore `WakeUp` messages triggered by the "awaken hibernate regions" mechanism. 
Consequently, the recovery duration would last longer than expected.
In this pull request, when the `raftstore` forcibly receives `WakeUp` messages -- indicating the presence of I/O hang problems in the cluster -- the relevant `raftstore` will promptly …

[cherry-pick-v7.1] raftstore: address the corner case on WakeUp hibernate regions. (#16408)

---

components/raftstore/src/store/fsm/peer.rs
tests/failpoints/cases/test_hibernate.rs

This is a manul cherry-pick of #16408.
Issue Number: Close https://github.com/tikv/tikv/issues/16368
```commit-message
This pull request addresses a corner case where `WakeUp` messages were being
ignored during I/O hang scenarios.
```
Previously, in the nightly branch, there was a possibility of Peers entering the `PreChaos` state by `on_check_peer_stale_state_tick` scheduler before handling `WakeUp` messages. In such cases,
these Peers would ignore `WakeUp` messages triggered by the "awaken hibernate regions" mechanism. 
Consequently, the recovery duration would last longer than expected.
In this pull request, when the `raftstore` forcibly receives `WakeUp` messages -- indicating the presence of I/O hang problems in the cluster -- the relevant `raftstore` will promptly …

[cherry-pick-v7.5] raftstore: address the corner case on WakeUp hibernate regions. (#16408)

---

components/txn_types/src/lock.rs

Issue Number: Close #16438 
```commit-message
txn: Reserve lock data prefix `T` for future use
```
Tests 
Side effects
```release-note
None
```

txn: Reserve lock data prefix `T` for future use

---

src/coprocessor/statistics/analyze.rs
src/coprocessor/statistics/cmsketch.rs
src/coprocessor/statistics/fmsketch.rs
src/coprocessor/statistics/histogram.rs

Issue Number: ref https://github.com/tikv/tikv/issues/16463
```commit-message
Use the standard from and into traits.
```
Tests 
Side effects
```release-note
None
```

statistics: use std from trait

---

components/raftstore/src/store/util.rs

Issue Number: Close #16465
```commit-message
improve the remove peer check. Only check when the updating role is voter
```
Tests 
Side effects
```release-note
None
```

raftstore: improve the remove peer check

---

components/raftstore-v2/src/operation/command/admin/conf_change.rs
components/raftstore-v2/src/raft/peer.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/util.rs
tests/integrations/raftstore/test_conf_change.rs

Issue Number: Close #16465
```commit-message
revert the remove peer check. Without this revert, the scale-in will be blocked when there're one slow or down peer in a region of the scale-in node. 
```
Tests 
Side effects
```release-note
None
```

raftstore: Revert remove peer check

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
tests/failpoints/cases/test_pending_peers.rs

Issue Number: Close #16491
This pr is used to fix the issue when starting from no regions (new node from empty), store_heartbeat incorrectly reports `store.is_busy == true`.
Meanwhile, the related codes when reporting `store.is_busy` has been polished.
```commit-message
In this pr, `completed_apply_peers_count` is replaced with `Option<u64>` from `u64`.
When initializing, `completed_apply_peers_count` will be set with `Some(0)`. If the check finds
that the store already finishes its `busy_on_apply` check  with `false` or starting from empty regions, this value
will be reset with `None` to mark the check is finished and no need to keep the check anymore next time.
```
Tests 
After bugfix:
Side effects
```release-note
None.
```

raftstore: fix store_heartbeat incorrectly reporting store.is_busy == true.

---

Cargo.lock
components/engine_rocks/Cargo.toml
components/engine_rocks/src/engine.rs

Issue Number: Ref #16259
```commit-message
Add property test for titan's basic operations: get/put/delete/scan/delete_range
```
Tests 
Side effects
```release-note
None
```

Engine: add basic proptest for titan

---

components/engine_panic/src/compact.rs
components/engine_rocks/src/compact.rs
components/engine_rocks/src/file_system.rs
components/engine_rocks/src/misc.rs
components/engine_rocks_helper/src/sst_recovery.rs
components/engine_traits/src/compact.rs
components/hybrid_engine/src/compact.rs
components/raftstore-v2/src/worker/cleanup/compact.rs
components/raftstore-v2/src/worker/tablet.rs
components/raftstore-v2/tests/failpoints/test_basic_write.rs
components/raftstore/src/store/compaction_guard.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/compact.rs
components/test_raftstore/src/cluster.rs
src/storage/mvcc/reader/reader.rs

Issue Number: Close #15282
```commit-message
use option bottommost_level_compaction = force in the compact_range scheduled by no_valid_split_key.
```
In no_valid_split_key senario, we schedule a compact range for the given region. We shoud also set bottommost_level_compaction = force to avoid the trivial move in the bottommost level so that tombstones can be removed..
Tests 
Side effects
```release-note
None
```

raftstore: use force in compact_range triggered by no valid split key

---

components/raftstore/src/store/snapshot_backup.rs

Issue Number: Close #16518
```commit-message
This PR will pause the `CompactLog` admin command during backing up.
```
Tests 
The code change is small but the impact would be relatively huge.
We have tested this before which shows there wouldn't be snapshot sent during restoring.
We have disabled GC manually for minutes and see there isn't huge impact to TP workloads (But I guess not for every scenario.).
Side effects
```release-note
Speeded up the restoration for newly generated backups.
```

disk_snapshot_backup: pause raft log GC while backing up

---

components/tidb_query_aggr/src/impl_avg.rs
components/tidb_query_aggr/src/impl_bit_op.rs
components/tidb_query_aggr/src/impl_sum.rs

Issue Number: Close https://github.com/tikv/tikv/issues/16531
```commit-message
Fix possible panic when there is illegal push down to Coprocessor related with data type and aggregation.
```
Tests 
Side effects
```release-note
None
```

copr: Fix panic when there is illegal push down

---

components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/worker/compact.rs
components/test_raftstore-v2/src/node.rs
components/test_raftstore/src/common-test.toml
components/test_raftstore/src/node.rs
tests/failpoints/cases/test_split_region.rs

Issue Number: Close #15282
```commit-message
make manual compaction in cleanup worker be able to be ignored dynamically
```
1. This PR provide a way to ignored the manual compaction in cleanup worker.
2. The PR also fixes a bug in the integration test for config manager.
Tests 
Side effects
```release-note
None
```

raftstore: make manual compaction in cleanup worker be able to be ignored dynamically

---

components/pd_client/src/lib.rs
components/raftstore/src/coprocessor/config.rs
components/raftstore/src/coprocessor/dispatcher.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/coprocessor/region_info_accessor.rs
components/raftstore/src/store/worker/pd.rs
components/server/src/server.rs
components/server/src/server2.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
src/server/gc_worker/gc_worker.rs
tests/failpoints/cases/test_gc_metrics.rs
tests/integrations/raftstore/test_region_info_accessor.rs
tests/integrations/storage/test_region_info_accessor.rs

Issue Number: ref #16141, ref #16417,  close #16507 
```commit-message
Add basic load eviction manager for in-memory engine.
```
Tests 
Side effects
```release-note
None
```

In-Memory Engine: region stats manager.

---

Cargo.lock
components/engine_panic/src/db_options.rs
components/engine_rocks/src/db_options.rs
components/engine_traits/src/db_options.rs
src/config/mod.rs

Issue Number: Ref #16549
```commit-message
Expose track-and-verify-wals-in-manifest config.
For further investigating corrupted WAL issue happened during EBS restore process.
```
Tests 
Side effects
```release-note
None
```

rocksdb: Expose track-and-verify-wals-in-manifest config

---

Cargo.lock

Issue Number: Close #16597
```commit-message
Update mio to 0.8.5 to satisfy cargo deny. 
```
Tests 
Side effects
```release-note
Update mio dependency to 0.8.5.
```

Cargo: update mio dependency.

---

src/storage/txn/actions/check_txn_status.rs
src/storage/txn/actions/prewrite.rs
src/storage/txn/commands/flush.rs

Issue Number: ref #16291
```commit-message
Skip assertion checks for pipelined-dml if the lock is already locked by itself.
By design, each key can be asserted only once in a transaction. For
pipelined-DML, a key may be flushed multiple times. Once a mutation with an
assertion is flushed and dropped from client buffer, the following execution
can set a different assertion for the same key. We only check the first
assertion, ignoring the rest.
In addition, we enforce protecting rollbacks of pipelined-DML locks, 
to avoid corner cases where t0.commit_ts = t1.start_ts. 
See comments for details.
```
Tests 
Side effects
```release-note
None
```

txn: skip assertion checks for pipelined-dml

---

src/storage/txn/actions/prewrite.rs
src/storage/txn/commands/flush.rs

Issue Number: ref #16291
```commit-message
Check should_not_exist flag for Flush, even when the lock is written by current transaction itself.
This is for the case:
TiDB flush key K.
TiDB do membuffer.CheckMemExist(K) and gets ErrNotFound because the key is flushed to TiKV. 
In vanilla TiDB it is able to know that the key has been written by membuffer.Get(K), 
but for pipelined DML it is too expensive to do a membuffer.Get because it involves a RPC.
To compensate, in this case we let TiDB attach a PresumeNotExist flag to the mutation.
In the next Flush, the should_not_exist flag is attached, 
and during the Flush we detect that the value is written before and return an AlreadyExist error.
```
Tests 
Side effects
```release-note
None
```

txn: check should_not_exist flag for Flush

---

components/sst_importer/src/sst_importer.rs

`mem_limit` acts as a memory quota which is the same as `tikv_util::memory::MemoryQuota`. 
Tests 
- Unit test
```release-note
None
```

sst_importer: replace mem_limit with MemoryQuota

---

components/tidb_query_expr/src/impl_cast.rs

Issue Number: Close #16616
If the `flen` is unspecified (-1), don't resize the string to try to produce extra zero. ref https://github.com/pingcap/tidb/pull/51586
Tests 
Side effects
```release-note
None
```

copr: don't resize binary opaque when the type flen is unspecified

---

components/backup-stream/src/subscription_manager.rs
components/backup-stream/src/subscription_track.rs

Issue Number: Close #16469, Ref #16554 
This PR rearranged the lifetime of a observed region.
For now, we will try to keep it in subscription tracker from `Start` until `End`, even the start itself is failed.
So the `RefreshObserver` will be able to find and start its observe as expected.
This also added a test case for verifying #16554 has been fixed in master.
```commit-message
```
Tests 
Side effects
```release-note
Fixed a bug that may cause PiTR failed to observe the region.
```

log_backup: store pending region info when giving up retry

---

components/raftstore/src/store/txn_ext.rs

Issue Number: Ref #16158
The memory lock scan would be called by `scan_lock` api used by GC and pessimistic lock rollback read stage, there should be only a few keys in most cases so it's unnecessary to allocate `limit`(256 by default) slots every time it is called.
```commit-message
Reduce memory allocation for scan lock.
```
Tests 
Side effects
```release-note
None
```

txn: reduce allocation for scan lock

---

components/raftstore/src/store/msg.rs

Issue Number: Close https://github.com/tikv/tikv/issues/16639
```commit-message
Fix store msg discriminant out of bound
```
Tests 
Side effects
```release-note
None
```

raftstore: Fix store msg discriminant out of bound

---

Cargo.lock
components/tidb_query_datatype/src/codec/datum.rs
components/tidb_query_datatype/src/codec/mysql/decimal.rs
components/tidb_query_datatype/src/codec/mysql/mod.rs
components/tidb_query_datatype/src/expr/ctx.rs
components/tidb_query_expr/src/impl_arithmetic.rs
components/tidb_query_expr/src/types/test_util.rs

Issue Number: close #16627, ref https://github.com/pingcap/tidb/issues/51501
```commit-message
Add support for div_precision_increment in dag request.
```
Tests 
Side effects
```release-note
None
```

tidb_query_datatype, tidb_query_expr: Add div_precision_increment support in dag request

---

components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/lib.rs
components/region_cache_memory_engine/src/range_manager.rs
components/region_cache_memory_engine/src/region_label.rs
components/region_cache_memory_engine/src/write_batch.rs

```commit-message
remove allow dead_code and unused_variables
```
Tests 
Side effects
```release-note
None
```

In-memory Engine: remove allow dead_code and unused_variables

---

src/storage/txn/scheduler.rs

Issue Number: Close #16442
```commit-message
Enhance unstable test test_pool_available_deadline.
The original logica has 2 factors that makes it not stable:
- Thread scheduling. If the 2nd cmd is scheduled 500ms later than the 1st cmd, then the 2nd task won't meet deadline error.
- Threadpool thread count. The yatp's active thread count is not always ensured, it only ensure that within finite duration, the active thread count will reach the target number. Thus if the 2nd thread is scheduled when there are more than 1 active threads, it won't meet deadline error.
I found there is no easy way to ensure that the active thread number is 1 so just let the cmd timeout before it is scheduled to always trigger the deadline error.
```
Tests 
Side effects
```release-note
None
```

test: enhance unstable test test_pool_available_deadline

---

components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/range_manager.rs

```commit-message
make range delete be handled in background
```
Now, we have background worker, so if the range is evicted and eligible to be removed, delete the range in the background worker.
Tests 
Side effects
```release-note
None
```

In-memory Engine: make range delete be handled in background

---

scripts/deny

Issue Number: Close https://github.com/tikv/tikv/issues/16687
```commit-message
use a fixed version of cargo-deny tool.
```
Tests 
Side effects
```release-note
None
```

fix:  use a fixed version of cargo deny

---

components/collections/src/lib.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_controller.rs

Issue Number: ref #16653
```commit-message
raftstore: optimize AutoSplitController memory usage
* Replaced unbounded channels with bounded channels to prevent unexpected
memory buildup when AutoSplitController runs slowly.
* Implemented reusability of temporary vectors and maps during CPU stats
handling to reduce memory allocation and deallocation overhead, saving
about 10% CPU.
```
Tests shows that it saves about 10% CPU, and memory usage is much stable.
| Header | 2024-03-20 nightly | With this PR |
|--------|--------|--------|
| CPU | ![image](https://github.com/tikv/tikv/assets/2150711/4a7b867e-34ef-4d7a-a086-471d3722d7da)| ![image](https://github.com/tikv/tikv/assets/2150711/9c6a9547-073e-4e5b-8c8a-7ec7944afd6f) |
| Memory\* | …

raftstore: optimize AutoSplitController memory usage

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/snap.rs

Issue Number: Close https://github.com/tikv/tikv/issues/16564
```commit-message
Avoid snapshot IO in raftstore thread
```
This PR does:
- Only check snapshot meta file existence when receiving snapshot message so that don't need to read meta file content 
- Don't calculate checksum when loading snapshot meta, because it would check in `validate`
Tests 
Side effects
```release-note
Avoid snapshot IO in raftstore thread
```

raftstore: Avoid snapshot IO in raftstore thread

---

components/hybrid_engine/src/write_batch.rs

```commit-message
fix panic when write batch callback twice
```
Tests 
Side effects
```release-note
None
```

In-memory engine: fix panic when write batch callback twice

---

components/engine_traits/src/iterable.rs
components/hybrid_engine/src/db_vector.rs
components/hybrid_engine/src/engine_iterator.rs
components/hybrid_engine/src/iterable.rs
components/hybrid_engine/src/lib.rs
components/hybrid_engine/src/snapshot.rs
components/hybrid_engine/src/write_batch.rs

Issue Number: Ref #16141 Close #16684
```commit-message
Implements an iterator for HybridEngineSnapshot and fixes a bug in HybridEngineSnapshot::get_value_opt (memory-engine only supports the data cfs.)
```
Tests 
Tested during TPCC runs in a separate branch.
Side effects
None
-->
```release-note
None
```

In-Memory: implement hybrid snapshot iter

---

components/tidb_query_expr/src/impl_json.rs
components/tidb_query_expr/src/lib.rs

Issue Number: close #16703
```commit-message
```
- [] Need to cherry-pick to the release branch
Tests 
Side effects
```release-note
add json_array_append  to the List of Expressions for Pushdown in https://docs.pingcap.com/tidb/stable/expressions-pushed-down
```

expr: add json_array_append support

---

components/hybrid_engine/src/snapshot.rs
components/hybrid_engine/src/write_batch.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/range_manager.rs
components/region_cache_memory_engine/src/write_batch.rs
tests/failpoints/cases/test_range_cache_engine.rs

```commit-message
simplify load and fix a bug
```
Currently, when the region of the range in `pending_range` splits, the range will also be splitted and scheduled to loading snapshot separately by each splited regions. 
This is unnecessary. **We can guarantee the data completeness as long as the snapshot is loaded and all the writes of the range after the acquirement of the snapshot are consumed, regardless of whether the range has been splitted or not**.
This PR also fixes a bug:
in `group_write_batch_entries`, we should also consider that the range may be evicted. This is to say that the range is loading data at the begin of apply entries. During the apply, the range has finished the load, and even been evicted.
Tests 
Side effects …

In-memory Engine: decouple load with split and fix a bug

---

components/cdc/src/initializer.rs
components/cdc/src/metrics.rs

Issue Number: ref https://github.com/tikv/tikv/issues/12592
Add a new metrics called tikv_cdc_scan_long_duration_region to observe the region count that use too long to do incremental scan.
```commit-message
```
Tests 
Side effects
```release-note
None
```

Add a metrics for cdc to observe the region count that use too long to do incremental scan

---

components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_controller.rs

Issue Number: Close #16716
```commit-message
Fix the bug when the channel is full in `AutoSplitController`.
```
Tests 
Side effects
```release-note
None
```

[Bugfix] raftstore: fix the bug when the channel is full in AutoSplitController.

---

components/hybrid_engine/src/engine.rs
components/hybrid_engine/src/import.rs
components/hybrid_engine/src/snapshot.rs
components/hybrid_engine/src/sst.rs
components/hybrid_engine/src/write_batch.rs
components/raftstore/src/store/worker/read.rs
components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/range_manager.rs
components/region_cache_memory_engine/src/write_batch.rs
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/lib.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/range_cache_engine.rs
components/test_raftstore/src/server.rs
components/test_raftstore/src/util.rs
tests/failpoints/cases/test_range_cache_engine.rs
tests/integrations/raftstore/test_lease_read.rs
tests/integrations/raftstore/test_single.rs
tests/integrations/raftstore/test_split_region.rs

```commit-message
make integration tests reusable for hybrid engine
```
This PR makes integration tests reusable (maybe part of, and with small modification) by in-memory engine by using the procedure macro `test_case` .
This PR makes the tests in `test_single.rs`, `test_lease_read.rs`, and `test_split_region.rs` using in-memory engine.
Tests 
Side effects
```release-note
None
```

In-memory engine: make integration tests reusable for hybrid engine

---

components/raftstore/src/store/fsm/peer.rs
components/test_raftstore/src/cluster.rs
tests/integrations/raftstore/test_life.rs

Issue Number: Close #16504
```commit-message
Fix issue of stale peer block resolve-ts cause by ignore gc message.
```
Tests 
Side effects
```release-note
Fix issue of stale peer block resolve-ts caused by ignore gc message.
```

*: fix issue of stale peer block resolve-ts cause by ignore gc message

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/subscription_manager.rs
components/backup-stream/src/utils.rs

Issue Number: Close #16739
```commit-message
This make `CallbackWaitGroup` returns an equivalent future of the `BoxFuture` returned by `wait`. Also this fixed where a stale notify may also resolve the future.
```
Tests 
I ran the task for 100 times. No error happens anymore.
```fish
for i in (seq 100)
if ! cargo test --package backup-stream --lib -- utils::test::test_wait_group --exact
break
end
echo "passed $i"
end
```
Side effects
```release-note
Fixed a bug where make there are a slight possibility that log backup lost a few records.
```

log_backup: make a more rusty `CallbackWaitGroup`

---

Cargo.lock
Cargo.toml
src/coprocessor/dag/mod.rs
src/server/service/diagnostics/sys.rs
src/server/service/kv.rs
src/server/service/mod.rs

Issue Number: ref #9012 
```commit-message
Return an error instead of panicking when gRPC response size is too large
```
Tests 
Side effects
```release-note
None
```

[Release 5.1 hotfix] copr: avoid panic when response is large

---

Cargo.lock

Issue Number: Close #16768
```commit-message
Update h2 to 0.3.26
```
Tests 
```
make clippy
```
Side effects
```release-note
None
```

Cargo.toml: Fix h2 cargo deny issue.

---

components/raftstore/src/store/async_io/write.rs
components/raftstore/src/store/fsm/apply.rs

It's unnecessary to call `consume_msg_resource` when there is only one resource group
```commit-message
Avoid consuming resource when there is only one resource group
```
Tests 
Side effects
```release-note
None
```

raftstore: Avoid consuming resource when there is only one resource group

---

components/raftstore/src/store/fsm/apply.rs
components/region_cache_memory_engine/src/engine.rs
tests/failpoints/cases/test_range_cache_engine.rs

```commit-message
fix problems of sub range scheduling load task of the whole range
```
This PR fixes a race of sub range scheluding load task of whole range. Say we are to load k1-k10 and k1-k5, and k5-k10 are ranges of two separete regions.
Now, the first one who calls `prepare_for_apply` will schedule the load of k1-k10 which can cause loss of data:
We can see `k1` has not been written in rocksdb before acquiring snapshot and will not be written or cached in the in-memory engine. So it will be lost.
To fix it:
We should split the range of k1-k10 into k1-k5 and k5-k10 and only schedule k5-k10 in apply thread 2.
When k1-k5 calls `prepare_for_apply` again, it schedules the remaining k1-k5. Furthermore, k1-k5 may be splitted before next …

In-memory engine: fix problems of sub range scheduling load task of the whole range

---

src/storage/txn/commands/flush.rs

Issue Number: Close #16810
```commit-message
fix: use u64::MAX as txn_size for Flush commands to avoid unexpected resolve_lock_lite
```
Tests 
- as described in #16810 , with this PR it is all `resolve_lock`s, though it's still too slow for huge transactions.
Side effects
```release-note
None
```

txn: use u64::MAX as txn_size for Flush commands

---

components/resolved_ts/src/cmd.rs

Issue Number: Ref #16818
Add more logs for investigating the panic issue where lock is applied again on the same key having locks already.
```commit-message
```
Tests 
Side effects
```release-note
None
```

txn: add more logs before assertions

---

tests/failpoints/cases/test_rawkv.rs

Issue Number: Close #16825
```commit-message
Fix flaky test_raw_put_key_guard.
```
The issue is caused by peer `0` would not be the leader of region.
Tests 
Side effects
```release-note
None
```

tests: Fix flaky test_raw_put_key_guard

---

components/test_raftstore/src/util.rs
src/storage/errors.rs
src/storage/mod.rs
src/storage/txn/mod.rs
src/storage/txn/scheduler.rs

Issue Number: Close #16789 
```commit-message
Add RawKvMaxTimestampNotSynced error and set message to errorpb.Error.max_ts_not_synced to provide more information.
Retry on max_ts_not_synced error for must_raw_put.
```
The debug string of "max timestamp not synced" region error will be, e.g, `message: "RawKV write fails due to potentially stale max timestamp, region_id: 1"`.
Tests 
Side effects
```release-note
Add RawKvMaxTimestampNotSynced error and set message to errorpb.Error.max_ts_not_synced to provide more information.
Retry on max_ts_not_synced error for must_raw_put.
```

tests,storage: Fix flaky test_rawkv::test_leader_transfer

---

Makefile
scripts/gen-tikv-details-dashboard

Issue Number: ref https://github.com/tikv/tikv/issues/16793
```commit-message
installing third-party tools requires specifying the version to avoid incompatible changes as time goes by.
```
Tests 
Side effects
```release-note
None
```

*: tools in scripts use fixed version to avoid incompatible updates

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

Issue Number: Close https://github.com/tikv/tikv/issues/16837
- Show how many sst files a compaction job involves in the grafana. In this way, large compaction job is easy to be observed.
- None
Tests 
Side effects
- None
```release-note
None
```

grafana: add metric to show how many sst files a compaction job involves

---

components/engine_traits/src/range_cache_engine.rs
components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/range_manager.rs
components/region_cache_memory_engine/src/write_batch.rs

```commit-message
fix missing memory record when snapshot loading
```
Tests 
Side effects
```release-note
None
```

In-memory engine: fix missing memory record when snapshot loading

---

Cargo.lock
components/engine_panic/src/db_options.rs
components/engine_rocks/src/db_options.rs
components/engine_traits/src/db_options.rs
src/config/mod.rs
tests/integrations/config/mod.rs

This is a manual cherry-pick of #16546
Issue Number: Ref #16549
```commit-message
Expose track-and-verify-wals-in-manifest config.
For further investigating corrupted WAL issue happened during EBS restore process.
```
Tests 
Side effects
```release-note
None
```

rocksdb: Expose track-and-verify-wals-in-manifest config 

---

components/engine_traits/src/range_cache_engine.rs
components/region_cache_memory_engine/src/engine.rs

```commit-message
remove out of date pending ranges
```
Tests 
Side effects
```release-note
None
```

In-memory engine: remove out of date pending ranges

---

src/storage/txn/commands/flush.rs
tests/integrations/server/kv_service.rs

Issue Number: Close #16880
```commit-message
The PR fixes the problem that locks written by pipelined-dml block reads.
Now min_commit_ts was set to start_ts + 1 for Flush commands. 
Previously it was set to 0, which disallows pushing min_commit_ts.
```
Tests 
Side effects
```release-note
None
```

txn: use start_ts + 1 as Flush's min_commit_ts

---

components/raftstore/src/store/config.rs
components/raftstore/src/store/peer.rs
components/test_raftstore/src/util.rs
src/config/mod.rs
tests/failpoints/cases/test_async_fetch.rs
tests/failpoints/cases/test_async_io.rs
tests/failpoints/cases/test_early_apply.rs
tests/failpoints/cases/test_unsafe_recovery.rs

Issue Number: ref #16717
```commit-message
Change the default value of `raftstore.max_apply_unpersisted_log_limit` from 0 to 1024 to enable apply committed log before persistence by default.
```
In our internal benchmark, with 3*8c tikv instances, when running sysbench oltp_write_only workload with 100 threads, the performance is almost the same when this feature is enabled/disabled. The result matches our expectation that this feature won't bring any performance impact.
Tests 
Side effects
```release-note
None
```

raftstore: enable apply committed log before persistence by default

---

src/storage/txn/actions/check_txn_status.rs

Issue Number: ref #16291
```commit-message
Add rollback log for pipelined dml for better diagnosis.
```
Tests 
The log be like
```log
[check_txn_status.rs:180] ["flushed lock has been rollbacked"] [current_ts=18446744073709551615] [lock="Lock { lock_type: Put, primary_key: 7480000000000002BF5F698000000000000001037FFFFFFFFF676982038000000000000002, start_ts: TimeStamp(449257004056182793), ttl: 1361000, short_value: 30, for_update_ts: TimeStamp(0), txn_size: 18446744073709551615, min_commit_ts: TimeStamp(449257004056182794), use_async_commit: false, secondaries: [], rollback_ts: [], last_change: Unknown, txn_source: 0, is_locked_with_conflict: false, generation: 1 }"] [thread_id=64]
```
Side effects
```release-note
None
```

txn: add rollback log for pipelined dml

---

Cargo.lock
components/engine_panic/src/misc.rs
components/engine_rocks/src/misc.rs
components/engine_traits/src/misc.rs
components/raftstore/src/store/worker/compact.rs
components/server/src/server.rs

Cherry-pick from #16700.
This is a manual cherry-pick of #16700
Issue Number: Close #16680
```commit-message
Stop background manual compaction before shutdown server.
```
In the current nightly branch (master), if there is a pending manual compaction in the kvdb being executed by the background thread cleanup-worker, the shutdown process gets stuck until the compaction is completed. This manual compaction can be triggered by the tick of `raftstore.region-compact-check-interval`.
As demonstrated in issue #16680, pending compactions not initiated manually by users can enlarge the node restart duration. In this PR, we have disabled manual compaction before stopping the cleanup-worker to address this issue.
Tests 
By testing with the newly introduced ut …

[cherry-pick-6.5] server: stop manual compaction jobs in engines before shutdown

---

components/tidb_query_datatype/src/codec/convert.rs
components/tidb_query_datatype/src/codec/mysql/decimal.rs

Issue Number: Close https://github.com/tikv/tikv/issues/16913
```commit-message
Fix the wrong decimal's result frac in some cases.
```
Tests 
Side effects
```release-note
Fix the wrong decimal's result frac in some cases.
```

expr: fix the wrong decimal's result frac in some cases

---

components/resolved_ts/src/cmd.rs

Issue Number: Ref #16818
Pick https://github.com/tikv/tikv/pull/16829 to release-8.1.
```commit-message
```
Tests 
Side effects
```release-note
None
```

txn: add more log before row lock check

---

components/engine_traits/src/range_cache_engine.rs

```commit-message
manually implement partial_eq for CacheRange to avoid the consideration of tag
```
Manually implement partial_eq for CacheRange to avoid the consideration of tag.
In addition, add some tests.
Tests 
Side effects
```release-note
None
```

In-memory engine: manually implement partial_eq for CacheRange to avoid the consideration of tag

---

Cargo.lock
components/tidb_query_expr/Cargo.toml
components/tidb_query_expr/src/impl_cast.rs

Issue Number: Close #16974
ref https://github.com/pingcap/tidb/pull/53129
```commit-message
expression: fix casting REAL type to STRING type
- unify the behavior of converting real types to strings in tidb#53129 and tikv.
- use ryu lib in tikv to implement casting real type to str type.
- `if abs(num) >= 1e15 or (num is not zero and abs(num) < 1e-15)` then use decimal exponent format 
```
Tests 
Side effects
```release-note
Fix the incorrect result when casting REAL type to STRING type
```

expression: fix casting REAL type to STRING type

---

src/coprocessor/statistics/analyze.rs
src/coprocessor/statistics/analyze_context.rs

Removed some unreachable code. The code is now unreachable as TiDB no longer sends mixed analyze requests to TiKV if the statistics version is set to 2.
You can only find one reference of the mixed request type in TiDB.
You can find it here: https://github.com/pingcap/tidb/blob/12b37d88dceb4eb4da6fe316fb4d0af2024ab58b/pkg/executor/builder.go#L2706
But for version 2, we use `buildAnalyzeSamplingPushdown` to build the analysis task.
Issue Number: Ref https://github.com/tikv/tikv/issues/16463
```commit-message
statistics: remove unreachable code
The code is now unreachable as TiDB no longer
sends mixed analyze requests to TiKV if the
statistics version is set to 2.
```
Tests 
Side effects
```release-note
None
```

statistics: remove unreachable code

---

components/region_cache_memory_engine/src/read.rs

```commit-message
fix seek does not set self.valid properly
```
Tests 
Side effects
```release-note
None
```

In-memory engine: fix seek does not set self.valid properly

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/metadata/client.rs
components/backup-stream/tests/failpoints/mod.rs

Issue Number: Close #17020
```commit-message
Spawn thread from the thread pool directly. (Instead of the thread local runtime handle.)
```
Tests 
Side effects
```release-note
Fixed a bug that might cause TiKV panic when resuming a PiTR task and the connection to PD isn't stable enought.
```

log_backup: fix panic when encountered error during resuming

---

src/server/snap.rs
tests/failpoints/cases/test_snap.rs

Issue Number: Close #16976
```commit-message
The issue is that if a leader fails to send a snapshot, it doesn't delete the 
snapshot file which may accumulate and waste disk space. The idle snapshot 
files will eventually be GCed, but that might take hours. The commit ensures 
that the snapshot file is also deleted on the error path. A new integration 
test was added which would fail without the fix. 
```
Tests 
Side effects
```release-note
None
```

raftstore: fix a bug where snapshot file is not deleted in time

---

components/raftstore/src/store/snap.rs

Issue Number: Ref #15972
```commit-message
This commit starts to introduce a snapshot precheck mechanism to reduce
unnecessary snapshot drops and generations. The mechanism functions as follows: 
Before a leader sends a snapshot to a follower, it first sends a precheck
message. This message serves as a preliminary inquiry to the follower, seeking
confirmation of its readiness to receive a snapshot. Upon receiving the message,
the follower consults its concurrency limiter and returns a response to the
leader. The leader will only proceed to generate the snapshot after the precheck
is passed. 
A passed precheck means the leader has reserved a spot on the follower so the
subsequent snapshot send should succeed. The reservation has a TTL and the
leader is supposed to complete …
```

raftstore: add a concurrency limiter for receiving snapshots

---

components/engine_panic/src/db_options.rs
components/engine_rocks/src/db_options.rs
components/engine_traits/src/db_options.rs
src/config/mod.rs

This is a manual cherry-pick of #16546
Issue Number: Ref #16549
```commit-message
Expose track-and-verify-wals-in-manifest config.
For further investigating corrupted WAL issue happened during EBS restore process.
```
Tests 
Side effects
```release-note
None
```

rocksdb: Expose track-and-verify-wals-in-manifest config (#16546)

---

components/raftstore/src/store/entry_storage.rs

Issue Number: Close #17040, ref #16717
```commit-message
Do not free cached entries if not all of them are persisted. After #16834, it is possible that applying entries are not persisted, so we should avoid evicting these entries while they are not fully persisted.
```
Tests 
Side effects
```release-note
None
```

raftstore: do not free cached entries if not all of them are persisted

---

components/resolved_ts/src/cmd.rs

Issue Number: Ref #16818
```commit-message
Refactor logs for the unexpected path, print both the exsiting row and input key/value.
```
Tests 
Side effects
```release-note
None
```

resolved_ts: refactor log for the unexpected path

---

components/online_config/src/lib.rs
components/tikv_util/src/config.rs
components/tikv_util/src/lib.rs
src/config/mod.rs
tests/integrations/config/test_config_client.rs

Issue Number: Close #17066
```commit-message
fix online config change panic for periodic-full-compact-start-time
```
Tests 
Side effects
```release-note
None
```

raftstore: fix online config change panic for periodic-full-compact-start-time

---

components/cdc/src/endpoint.rs

Issue Number: Close #16444 
```commit-message
cdc: handles region registers correctly after connection deregistered
```
Tests 
Side effects
```release-note
None
```

cdc: handles region registers correctly after connection deregistered

---

components/tikv_util/src/config.rs

Issue Number: Close #17080
```commit-message
* Test both formats +HHMM offsets and as well as +HH:MM for ReadableSchedule.
```
Tests 
Side effects
```release-note
None
```

config: test +HHMM offset in ReadableSchedule

---

Dockerfile
Dockerfile.test
rust-toolchain.toml

Fix `make docker` and `make docker_test`.
Issue Number: Close #17075
Fixed a problem where it was trying to read a non-existent `rust-toolchain` file.
```commit-message
Fix `make docker` and `make docker_test`.
```
Tests 
Side effects
```release-note
None
```

Dockerfile: fix docker build

---

src/coprocessor_v2/plugin_registry.rs

Issue Number: Close #17090 
```commit-message
```
Tests 
Side effects
```release-note
Compatibility with FreeBSD has been restored for coprocessor_v2
```

coprocessor_v2: FreeBSD uses .so

---

Cargo.lock
components/region_cache_memory_engine/Cargo.toml
components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/lib.rs
components/region_cache_memory_engine/src/test_util.rs
components/region_cache_memory_engine/tests/failpoints/mod.rs
components/region_cache_memory_engine/tests/failpoints/test_gc.rs

Issue Number: Close #17060 Ref #16141
```commit-message
mvcc keys with different sequen number should only be handled once in GC
```
Without the patch, the default not found can occur:
If one key in write cf is overwritten, GC can delete the default cf incorrectly, e.g.
safe-point is 10, and there is only one k1 with commit ts less than 10, ex: k1_5_100 (5 is the commit ts, 100 is the seqno)
Now the overwrite happens, k1_5_200.
So now it's k1_5_200, k1_5_100.
The GC will leave the latest put under the safe-point
Here, k1_5_100 was mistakenly GC'd, and the corresponding default cf was deleted where key of this default cf is also the one pointed to by k1_5_200.
Tests 
Side effects
```release-note
None
```

In-memory engine: mvcc keys with different sequence number should only be handled once in GC

---

Cargo.lock
components/engine_traits/src/misc.rs
components/test_storage/Cargo.toml
components/test_storage/src/lib.rs
components/test_storage/src/sync_storage.rs
src/lib.rs
src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/gc_worker.rs

Issue Number: Close #17086 Ref #16141
```commit-message
enable compaction filter for HybridEngine
```
Tests 
Side effects
```release-note
None
```

In-memory engine: enable compaction filter for HybridEngine

---

components/region_cache_memory_engine/src/read.rs

Issue Number: Close #17079 Ref #16141
```commit-message
support reverse direction when iterating
```
Tests 
Side effects
```release-note
None
```

In-memory engine: support changing the direction of iteration

---

components/hybrid_engine/src/write_batch.rs
components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/lib.rs
components/region_cache_memory_engine/src/write_batch.rs
components/region_cache_memory_engine/tests/failpoints/mod.rs
components/region_cache_memory_engine/tests/failpoints/test_memory_engine.rs

Issue Number: Close #17127 Ref #16141
```commit-message
clean lock cf tombstone in a background worker
```
This PR replace the in-place delete of the lock cf with writing tombstones just like what does in rocksdb.
This PR also adds a background task to clean these tombstones to avoid the performance regression.
Tests 
Side effects
```release-note
None
```

In-memory engine: clean lock cf tombstone in a background worker

---

components/region_cache_memory_engine/src/keys.rs

Issue Number: Close #17082
```commit-message
An internal key trailer is `(sequence_number << 8) | value_type as u64`
and it should be encoded in little endian to be consistent with RocksDB.
```
Tests 
- Unit test
```release-note
None
```

In-memory Engine: encode internal key trailer in little endian.

---

Cargo.lock
components/raftstore/src/coprocessor/region_info_accessor.rs
components/region_cache_memory_engine/Cargo.toml
components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/lib.rs
components/region_cache_memory_engine/src/memory_controller.rs
components/region_cache_memory_engine/src/range_stats.rs
components/server/src/common.rs
components/server/src/server.rs
components/test_raftstore/src/util.rs
tests/integrations/storage/test_region_info_accessor.rs

Issue Number: Ref #16764 Ref #16141 
```commit-message
In-Memory Engine: Algorithmic Load and Eviction
```
Tests 
Configure with range cache engine enabled and load a dataset larger than the soft limit.
Side effects
```release-note
None
```

In-Memory Engine: Eviction, Algorithmic loading

---

components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/range_manager.rs
components/region_cache_memory_engine/tests/failpoints/test_memory_engine.rs

Issue Number: Close #17153
```commit-message
evict range should consider loading range
```
Tests 
Side effects
```release-note
None
```

In-memory engine: evict range should consider loading range

---

components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/tests/failpoints/test_memory_engine.rs

Issue Number: Close #17103 Ref #16141
```commit-message
clear write batch when range load failed
```
Tests 
Side effects
```release-note
None
```

In-memory engine: clear write batch when range load failed

---

components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/tests/failpoints/test_memory_engine.rs

```commit-message
set disk engine when start
```
Tests 
Side effects
```release-note
None
```

In-memory engine: set disk engine when start

---

components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/read.rs
components/region_cache_memory_engine/tests/failpoints/test_memory_engine.rs

```commit-message
filter plus one when any key is removed during GC
```
Tests 
Side effects
```release-note
None
```

In-memory engine: `filter` plus one when any key is removed during GC

---

src/server/server.rs

Issue Number: Close #17176
```commit-message
Set compression arguments for TiKV service. The compression arguments are loaded from TiKV config.
It will affect TiKV's response to TiDB.
```
Tests 
Side effects
```release-note
Fix the problem that the compression config of TiKV doesn't affect TiKV service, including its response to TiDB.
```

grpc: set compression args for TiKV service

---

components/region_cache_memory_engine/src/keys.rs
components/region_cache_memory_engine/src/write_batch.rs

Issue Number: Close #17106
```commit-message
fix under-estimate memory size usage of delete entry
```
Tests 
Side effects
```release-note
None
```

In-memory engine: correct under-estimate memory size usage of delete entries.

---

components/raftstore/src/store/worker/region.rs
tests/failpoints/cases/test_merge.rs

Issue Number: Close #17258
```commit-message
This reverts commit 273ec868a794cf4637c9c8c5a2d8bb462d701217.
The previous commit introduced a bug that could result in data loss. 
Specifically, the region worker might delete data from a range where a 
snapshot has just been applied.
```
Tests 
I manually checked that the outputs of the two commands are the same, which means all changes made after the commit are untouched:
1. git diff 273ec86 HEAD^ components/raftstore/src/store/worker/region.rs
2. git diff 273ec86^ HEAD components/raftstore/src/store/worker/region.rs
Side effects
```release-note
None
```

Revert "raftstore: handle region destroy in a separate thread pool (#17121)"

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

Issue Number: ref #16265
This pr is used to fix the incorrect format of the unit in the panel of `grpc source requests' duration`.
Before:
After correction:
```commit-message
Fix incorrect format unit of the `grpc source requests' duration` panel.
```
Tests 
Side effects
```release-note
None
```

metrics: fix incorrect unit of grpc source requests' duration.

---

CONTRIBUTING.md

MacOS does not necessarily need to install gcc to build the project
Issue Number: Close #17265
```release-note
None
```

doc: make c++ complier requirement more accurate

---

clippy.toml
deny.toml

Issue Number: Close https://github.com/tikv/tikv/issues/17291
```commit-message
Ignore RUSTSEC-2024-0357 (unsound `openssl::bio::MemBio::get_buf`) as we
have banned relevant APIs in the TiKV codebase.
Also, TiKV temporarily pins OpenSSL 1.1.1 because OpenSSL 3.0.0 has
performance regressions. See details in deny.toml.
```
Tests 
- No code
```release-note
None
```

*: ignore unsound `openssl::bio::MemBio::get_buf`

---

Cargo.toml
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/raft/peer.rs
components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/peer.rs
metrics/grafana/tikv_details.json
tests/failpoints/cases/test_pending_peers.rs
tests/integrations/config/mod.rs

This pr is used to cp #16239 & #16494 & #16738 to v7.1, used to inspect the gap of each peer's `applied_log_index` and `commit_log_index` when restarting.
And if the gap exceeds the `leader_transfer_max_log_lag`, the related peer will be marked
as `pending for recovery` state. After the gap is less than `leader_transfer_max_log_lag`,
it means that the pending logs is acceptable.
Only if the count of ready peers exceeds the given configuration, that is,
`min_recovery_ready_region_percent`, this store is ready for re-balancing leaders. Before
this stage, the state of this store will be marked `is_busy` to avoid transferring leaders to it.
Issue Number: Ref https://github.com/tikv/tikv/issues/15874
```commit-message
This pr is used to cp #16239 & #16494 & #16738 to v7.1, used …
```

raftstore: cherry-pick #16239 & #16494 & #16738 to v7.1

---

Cargo.toml
components/raftstore/src/router.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/snapshot_backup.rs
components/raftstore/src/store/transport.rs
components/raftstore/src/store/unsafe_recovery.rs
components/raftstore/src/store/worker/cleanup_snapshot.rs
components/raftstore/src/store/worker/pd.rs
components/snap_recovery/src/services.rs
components/test_raftstore/src/router.rs
src/server/server.rs
tests/integrations/raftstore/test_snap_recovery.rs

Issue Number: Close https://github.com/tikv/tikv/issues/16229
```commit-message
Reduce the memory usage of peers' message channel 
```
Tests 
Test with 100k regions, the total memory usage reduce 40% compared to master
- patched: 
- <img width="723" alt="img_v3_02da_f6018662-1da3-4be4-9ddb-14ce1e963adg" src="https://github.com/user-attachments/assets/f2d23596-4205-4eec-af87-fdbfd83e82e5">
- master:
- <img width="718" alt="img_v3_02da_4785f9d6-1845-4699-b2eb-78163f9e39cg" src="https://github.com/user-attachments/assets/1395b1ea-0cca-492c-b81d-d401ccd286fb">
Gain 2% performance improvement on oltp_write_only 
Side effects
```release-note
Reduce considerable memory usage when there are lots of regions on one TiKV instance
```

batch-system: Reduce the memory usage of peers' message channel 

---

components/engine_panic/src/range_cache_engine.rs
components/engine_rocks/src/range_cache_engine.rs
components/engine_traits/src/range_cache_engine.rs
components/hybrid_engine/src/misc.rs
components/hybrid_engine/src/observer.rs
components/hybrid_engine/src/range_cache_engine.rs
components/raftstore/src/coprocessor/region_info_accessor.rs
components/range_cache_memory_engine/src/background.rs
components/range_cache_memory_engine/src/engine.rs
components/range_cache_memory_engine/src/metrics.rs
components/range_cache_memory_engine/src/range_manager.rs
components/range_cache_memory_engine/src/read.rs
components/range_cache_memory_engine/src/write_batch.rs
components/range_cache_memory_engine/tests/failpoints/test_memory_engine.rs
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256
tests/failpoints/cases/test_range_cache_engine.rs

```commit-message
show eviction reasons in metrics
```
Tests 
Side effects
```release-note
None
```

In-memory engine: show eviction reasons in metrics

---

Cargo.lock

Issue Number: Close #17272
```commit-message
TiKV no longer names bloom filter blocks with suffix like "FullBloom" or "Ribbon".
```
Tests 
Side effects
```release-note
1. TiKV no longer names bloom filter blocks with suffix like "FullBloom" or "Ribbon".
2. Use prefix match instead of exact match to determine whether a bloom filter created before can be used (compatible with the new version) to solve the "bloom filters were incorrectly invalidated after upgrade" issue, after all, TiKV only uses RocksDB native bloom filters, i.e. FullBloom, Ribbon, and according to RocksDB's doc, they can be used interchangeably.
```

RocksDB: Fix bloom filter incompatible issue

---

components/raftstore/src/store/snap/io.rs
src/server/snap.rs

```commit-message
Fix io flow stat for snapshot sending. Its io flow is not taken into account previously 
because the io flow is recorded only when using `file_system::File` which is a wrapper of `std::fs::File`.
```
Tests 
Side effects
```release-note
None
```

server: Fix io flow stat for snapshot sending

---

components/cdc/src/channel.rs
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/initializer.rs
components/cdc/src/observer.rs
components/cdc/src/service.rs

Issue Number: Close #17368 
```commit-message
* add one log to indicate the memory quota is freed when drop the `Drain`
* free the truncated scanned event memory quota.
* refactor `finish_scan_lock` method, to remove the else branch.
* row size calculation should also consider old value
* remove some outdate todo
```
Tests 
Side effects
```release-note
None
```

cdc: print log to indicate memory free, and adjust finish_scan_lock method

---

components/engine_rocks/src/properties.rs
components/engine_traits/src/misc.rs
components/raftstore/src/store/worker/compact.rs

Issue Number: Close #17269 
```commit-message
compaction-filter: consider mvcc.delete as redundant key to trigger Rocksdb compaction
```
```release-note
compaction-filter: consider mvcc.delete as redundant key to trigger Rocksdb compaction
```

compaction-filter: consider  mvcc-delete as redundant key to trigger rocksdb compaction

---

components/engine_traits/src/range_cache_engine.rs
components/hybrid_engine/src/observer.rs
components/range_cache_memory_engine/src/metrics.rs

…7237)"
This reverts commit fe7d5232447c5ab8958cccbc666878994230ac3f.
Issue Number: Close #17405
```commit-message
Revert #17237 because cache region can be loaded even when current peer is not leader so we should handle apply snapshot event.
```
Tests 
Side effects
```release-note
None
```

Revert "In-memory Engine: do not evict range on applying snapshot

---

Cargo.lock
Cargo.toml
components/encryption/Cargo.toml
components/encryption/src/lib.rs
components/encryption/src/master_key/kms.rs
components/encryption/src/master_key/mod.rs
tests/failpoints/cases/test_encryption.rs

ref tikv#17410
This commit adds a new test to verify TiKV's recovery after temporary unavailability of the KMS service.
Issue Number: Ref #17410
```commit-message
This commit adds a new test to verify TiKV's recovery after temporary unavailability of the KMS service.
```
Tests 
Side effects
```release-note
no.
```

encryption: add test for temporary KMS service unavailable

---

components/range_cache_memory_engine/src/range_manager.rs
components/range_cache_memory_engine/src/write_batch.rs

Issue Number: Close #17483, close #17484
```commit-message
The PR fix the bug by `amend_pending_region` that causes inconsistency
between regions and regions_by_range because it may change the region
range in metadata but not update the key of regions_by_range. This PR
change the original `amend_pending_region` by first remove the old
region and add a new one.
BTW, this PR also add a `Drop` implementation for `RegionManager` in
test environment to check the consistency between regions and
regions_by_range to find this kind of bug easier.
```
Tests 
Side effects
```release-note
None
```

in-memory-region: fix the inconsistency caused by updating region range

---

components/range_cache_memory_engine/src/background.rs
components/range_cache_memory_engine/src/engine.rs
components/range_cache_memory_engine/src/range_manager.rs
components/range_cache_memory_engine/src/read.rs
components/range_cache_memory_engine/src/write_batch.rs
components/range_cache_memory_engine/tests/failpoints/test_memory_engine.rs
tests/failpoints/cases/test_range_cache_engine.rs

Issue Number: Close #17498 Ref #16141
```commit-message
provide a callback API for eviction
```
Tests 
Side effects
```release-note
None
```

In-memory engine: provide a callback API for eviction

---

src/server/lock_manager/waiter_manager.rs
src/storage/lock_manager/lock_waiting_queue.rs
src/storage/lock_manager/mod.rs
src/storage/txn/scheduler.rs

Issue Number: Close #17394
```commit-message
lock_manager: Skip updating lock wait info for non-fair-locking requests
This is a simpler and lower-risky fix of the OOM issue #17394 for released branches, as an alternative solution to #17451 .
In this way, for acquire_pessimistic_lock requests without enabling fair locking, the behavior of update_wait_for will be a noop. So that if fair locking is globally disabled, the behavior will be equivalent to versions before 7.0.
```
This is a simple alternative solution to #17451 .
For non-fair locking scenario, it's confirmed that the problem can be avoided.
Before:
After: 
Tests 
Side effects
```release-note
Fix an issue that when frequently updating a row while many transaction is waiting on the lock, it might sometimes cause …
```

lock_manager: Skip updating lock wait info for non-fair-locking requests

---

components/cdc/src/errors.rs
components/cdc/tests/failpoints/test_endpoint.rs
components/cdc/tests/failpoints/test_memory_quota.rs
components/cdc/tests/mod.rs

Issue Number: Close #17534
```commit-message
* fix the unstable unit test test_cdc_pipeline_dml
* return `congested` when meet MemoryQuotaExceed error, this happens when push pending locks
```
Tests 
Side effects
```release-note
None
```

cdc: fix unstable test_cdc_pipeline_dml

---

Cargo.lock
components/range_cache_memory_engine/Cargo.toml
components/range_cache_memory_engine/src/background.rs
components/range_cache_memory_engine/src/range_manager.rs

Issue Number: ref #16141
```commit-message
Fix incorrect RANGE_CACHE_COUNT metrics by always set gauge values of all types.
```
Tests 
Side effects
```release-note
None
```

in-memory-engine fix incorrect region count gauge when count becomes 0

---

components/raftstore/src/store/fsm/peer.rs
tests/failpoints/cases/test_split_region.rs

Issue Number: Close #17469
```commit-message
The commit fixes a panic in TiKV that occurs in a rare scenario that
involves region splits and immediate removal of the new peer.
When a region splits, the new peer on a follower can be created in two 
ways: (1) By receiving a Raft message from the new region 
(`fn maybe_create_peer`) (2) By applying the split operation locally 
(`fn on_ready_split_region`). 
Depending on timing, a new peer might first be created by a Raft 
message and then again when the split is applied. This is a known 
situation. When it happens, the second peer replaces the first, and the 
first peer is dicarded. However, the discarded peer may continue 
processing existing messages, leading to unexpected states.
The panic can be reproduced with the …
```

raftstore: fix panic due to stale peer handling snapshot

---

components/engine_traits/src/range_cache_engine.rs
components/range_cache_memory_engine/src/range_manager.rs

Issue Number: Close #17487, Close #17493, Close #17548
```commit-message
Fix the bug that in-memory-engine may panic when load new region whose id is the same with a cached region that is being evicted. This can happen when a region is evicted by region merge, and the merged region is split and then load again while the cached region is still in evicting state.
```
Tests 
Side effects
```release-note
None
```

In-memory Engine: fix panic that new region has the same id with evicting region

---

components/raftstore/src/store/txn_ext.rs
src/server/lock_manager/config.rs
src/server/lock_manager/mod.rs
src/storage/mod.rs
src/storage/txn/scheduler.rs
tests/failpoints/cases/test_merge.rs
tests/failpoints/cases/test_split_region.rs
tests/failpoints/cases/test_transaction.rs
tests/failpoints/cases/test_transfer_leader.rs
tests/integrations/config/dynamic/pessimistic_txn.rs
tests/integrations/config/mod.rs
tests/integrations/raftstore/test_flashback.rs
tests/integrations/raftstore/test_merge.rs
tests/integrations/raftstore/test_multi.rs
tests/integrations/raftstore/test_split_region.rs
tests/integrations/raftstore/test_transfer_leader.rs

Issue Number: Close #17542 
```commit-message
Support changing the in-memory pessimistic lock memory size limit dynamically.
```
Tests 
Side effects
```release-note
Add in-memory pessimistic lock memory size limit configurations and support changing them dynamically.
```

support change in memory pessimistic lock memory size dynamically

---

components/pd_client/src/lib.rs
components/raftstore/src/coprocessor/region_info_accessor.rs

```commit-message
update the calculation of mvcc_amplification
```
Avoid return 0 when processed_ke is 0,  as (next+prev) can be high even processed_key is 0.
Tests 
Side effects
```release-note
None
```

In-memory engine: update the calculation of mvcc_amplification

---

tests/failpoints/cases/test_range_cache_engine.rs

Issue Number: Close #17556
```commit-message
fix flaky test `test_load_with_split`
```
Tests 
Side effects
```release-note
None
```

In-memory engine: fix flaky test `test_load_with_split`

---

components/raftstore-v2/src/operation/command/admin/merge/prepare.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore/src/store/simple_write.rs
components/raftstore/src/store/util.rs

Issue Number: Close #17563
```commit-message
According to the flamegraph, creating a logger takes as much time as
parsing a protobuf message in `get_entry_header`.
As an optimization, skip logger creation since it's only used for panic
logging in `SimpleWriteReqDecoder::new`.
```
Tests 
- Unit test
```release-note
None
```

raftstore: skip create logger in `get_entry_header`

---

Cargo.lock
components/resource_control/src/future.rs
components/tikv_util/Cargo.toml

Issue Number: Close #17612
```commit-message
Fix unstable test test_limited_future due to the configuration change of async-speed-limiter. This PR also update async-speed-limiter to v0.4.2.
```
Tests 
Side effects
```release-note
None
```

test: fix flaky test test_limited_future

---

components/raftstore/src/store/snap/io.rs
components/raftstore/src/store/worker/region.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/17376
This pr is an enhancement for the previous work https://github.com/tikv/tikv/pull/17408.
This pr is introduced to ensure that the state of region and snapshot will be flushed after applying
snapshot.
```commit-message
Ensure that the state of snapshot and region will be flushed into kvdb.
```
Tests 
Side effects
```release-note
None.
```

snap: ensure the state of snapshot flushed after applying snapshots.

---

components/raftstore/src/store/fsm/peer.rs

Issue Number: Ref #15990
```commit-message
Conditionally compile the helper function that only got called in fail-point tests to suppress the warning.
```
Tests 
Side effects
```release-note
None
```

chore: Conditionally compile helper function for failpoints

---

scripts/check-bins.py

Issue Number: Close #17617
```commit-message
Update SSE42 check since RocksDB changed its function name.
```
Tests 
Side effects
```release-note
None
```

Fix SSE42 error

---

Cargo.lock
components/backup-stream/src/router.rs
components/cloud/Cargo.toml
components/cloud/aws/src/s3.rs
components/cloud/azure/src/azblob.rs
components/cloud/gcp/src/gcs.rs
components/cloud/gcp/src/lib.rs
components/cloud/src/blob.rs
components/engine_panic/src/sst.rs
components/engine_rocks/src/sst.rs
components/engine_traits/src/sst.rs
components/external_storage/Cargo.toml
components/external_storage/src/export.rs
components/external_storage/src/hdfs.rs
components/external_storage/src/lib.rs
components/external_storage/src/local.rs
components/external_storage/src/locking.rs
components/external_storage/src/noop.rs
components/tikv_util/src/stream.rs
components/tikv_util/src/sys/mod.rs

Issue Number: Close #17284
```commit-message
- Added `WalkBlobStorage` and implemented it for S3 and GCS.
- Allow the `Read` of the `write` call to borrow local variables.
- Added a new macro `retry_expr!` for retrying.
- Added `Reset` for the reader that generated by `SstWriter`.
```
Tests 
The `WalkBlobStorage` was tested by the following code:
```rust
#[test]
#[ignore]
fn test_somewhat() {
let mut bucket = BucketConf::default(StringNonEmpty::opt("astro".to_owned()).unwrap());
bucket.endpoint = StringNonEmpty::opt("http://minio:9000/".to_owned());
let s3 = Config::default(bucket);
let s3 = Config {
access_key_pair: Some(AccessKeyPair {
access_key: StringNonEmpty::opt("minioadmin".to_owned()).unwrap(),
secret_access_key: …
```

Prepare the external storage interface for compacting log backup

---

components/in_memory_engine/src/write_batch.rs

Issue Number: Close #17630 Ref #16141 
```commit-message
fix save point empty assertion fail
```
Save point empty assertion can fail. For simplifity, does not release evicted region's buffer (it is intended to release memory quickly so that the next region have chances not to be evicted due to memory limit) as eviction during write is rare.
Tests 
Side effects
```release-note
None
```

In-memory engine: fix save point empty assertion fail

---

components/raftstore/src/store/fsm/peer.rs
tests/failpoints/cases/test_hibernate.rs
tests/integrations/raftstore/test_stats.rs

Issue Number: ref #15607
```commit-message
```
Tests 
Side effects
```release-note
None
```

test: fix flaky test test_query_stats and test_store_disconnect_with_hibernate

---

components/in_memory_engine/src/region_stats.rs
components/raftstore/src/coprocessor/region_info_accessor.rs
tests/integrations/storage/test_region_info_accessor.rs

```commit-message
calculating top stats should not consider reach_stop_load
```
This PR also removes get_top_regions with count 0 which is never used now.
Tests 
Side effects
```release-note
None
```

In-memory engine: calculating top stats should not consider reach_stop_load

---

components/hybrid_engine/Cargo.toml

Issue Number: Close #17639 
```commit-message
Fix bugs when building `hybrid-engine` crates with unexpected compilation configurations.
```
Tests 
Side effects
```release-note
Fix bugs when building `hybrid-engine` crates with unexpected compilation configurations.
```

hybrid-engine: fix unexpected compilation behaviors.

---

components/cdc/src/initializer.rs

Issue Number: Close #17669 
```commit-message
before start the incremental scan, check the tasks status, stop it immediately
```
Tests 
Side effects
```release-note
None
```

cdc: cancel incremental scan tasks in time

---

components/in_memory_engine/src/background.rs

Issue Number: Close #17667
```commit-message
Fix the bug that when region is split before gc task start, the gc task
only mark in_gc state for the region with the same id, but will unset
it for all the regions within the given range.
NOTE: for implementation simplicity, after this change, in the condition,
the gc will only run on the region with the same id, other regions in
the same range will skip this GC round.
```
Tests 
Side effects
```release-note
None
```

in_memory_engine: fix the assert panic caused by gc

---

Cargo.lock
components/in_memory_engine/Cargo.toml
components/in_memory_engine/benches/load_region.rs
components/in_memory_engine/src/background.rs
components/in_memory_engine/src/engine.rs
components/in_memory_engine/src/region_manager.rs

Issue Number: ref #16141
```
$ cd components/in_memory_engine && cargo bench --bench load_region
Benchmarking load_region/value size 32: Warming up for 1.0000 ms
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 39.3s.
Benchmarking load_region/value size 32: Collecting 10 samples in estimated 39.30                                                                                load_region/value size 32
time:   [3.6624 s 3.6983 s 3.7351 s]
change: [-0.4625% +0.9910% +2.5652%] (p = 0.24 > 0.05)
No change in performance detected.
Benchmarking load_region/value size 128: Warming up for 1.0000 ms
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 25.0s.
Benchmarking load_region/value size 128: Collecting 10 samples in …
```

in_memory_engine: add a benchmark for region load

---

components/engine_traits/src/region_cache_engine.rs
components/hybrid_engine/src/observer/load_eviction.rs
components/in_memory_engine/src/metrics.rs
components/raftstore/src/coprocessor/dispatcher.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/store/fsm/peer.rs
tests/failpoints/cases/test_in_memory_engine.rs

Issue Number: Close #17644 Ref #16141
```commit-message
Evict region when destroy peer
```
Evict region when destroy peer. Otherwise, the data may be inconsistent "physically" (logically, the data should be consistent due to unreadable for the destroyed range.).
Tests 
Side effects
```release-note
None
```

In-memory engine: evict region when destroy peer

---

Cargo.lock

Issue Number: Close #17691 
```commit-message
Update RocksDB to include fixes for ingestion
* https://github.com/tikv/rocksdb/commit/31eb76b1bc82740c9b85a2462804130857df0577
* https://github.com/tikv/rocksdb/commit/cf9cd5b89217fe49d22194af8ae67aaecf0ba231
```
Tests 
Side effects
```release-note
Fixing SST ingestion slowness after RocksDB upgrading
```

RocksDB: Fix SST ingestion

---

components/raftstore/src/store/worker/compact.rs

Issue Number: Close #17269
```commit-message
add test for triggering compaction in CheckAndCompact
```
Tests 
Side effects
```release-note
None
```

compaction-filter: add test for triggering compaction in CheckAndCompact

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/initializer.rs
components/cdc/src/old_value.rs
components/cdc/tests/failpoints/test_endpoint.rs

Issue Number: Close #16601
Issue Number: Close #17620 
Filter CDC events with the observed range before load old values. This can reduce CPU usage, especially for the situation with lots of continuous RocksDB Tombstones, which are generated from `drop/truncate table/partition` DDLs.
```commit-message
cdc: filter events with the observed range before load old values
```
Tests 
Side effects
```release-note
None
```

cdc: filter events with the observed range before load old values

---

Cargo.lock

Issue Number: Close #17731
```commit-message
Add deprecated RocksDB option to avoid panic upgrading from TiKV 6.1.x to 8.4+
```
Tests 
Side effects
```release-note
None
```

RocksDB: Fix deprecated option

---

src/storage/txn/flow_controller/singleton_flow_controller.rs

Issue Number: Close #17304
```commit-message
Fix unexpected flow control after unsafe destroy range
Flow controller detects pending compaction bytes jump before and after unsafe destroy range. If there is a jump, the controller enters a state that would ignore the high pending compaction bytes until it falls back to normal. Previously, the controller may not enter the state if the pending compaction bytes is lower than the threshold while long term average pending bytes is still high. Then it would trigger flow control mistakenly.
```
Tests 
Side effects
```release-note
Fix the possible flow control after dropping a large table or partition
```

storage: Fix unexpected flow control after unsafe destroy range -- cp to 7.1

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/subscription_manager.rs
components/cdc/src/endpoint.rs
components/resolved_ts/src/advance.rs

close tikv/tikv#15999
Issue Number: Close #15999
```commit-message
use smaller timeout when do check_leader, to to reduce the impact of a single TiKV slowing down on the advance resolve_ts of other TiKVs
```
Tests 
Side effects
```release-note
None
```

resolved_ts: use smaller timeout when do check_leader (#16000) (#16943)

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/subscription_manager.rs
components/backup-stream/tests/suite.rs
components/cdc/src/endpoint.rs
components/cdc/tests/mod.rs
components/server/src/server.rs
components/server/src/server2.rs

Issue Number: Close #17107
```commit-message
Fix the problem that CDC and log-backup didn't use advance-ts-interval to limit the timeout of check_leader
```
Tests 
Side effects
```release-note
Fix the problem that CDC and log-backup didn't use advance-ts-interval to limit the timeout of check_leader.
```

Fix the problem that CDC and log-backup didn't use advance-ts-interval to limit the timeout of check_leader (#17113)

---

Cargo.lock
components/in_memory_engine/Cargo.toml
components/in_memory_engine/src/lib.rs
components/in_memory_engine/src/memory_usage_test.rs
components/in_memory_engine/src/prop_test.rs
components/tikv_alloc/src/jemalloc.rs

Issue Number: Ref #16141 
```commit-message
Add test to simulate insertion of 200MB (logical size) of TiDB unqiue
index and secondary index records and measure SkiplistEngine memory
usage.
Test results:
* For secondary index
* The key-value encoding amplification is approximately 3.10
* SkiplistEngine amplification is approximately 7.66
* For unique index
* The key-value encoding amplification is approximately 3.38
* SkiplistEngine amplification is approximately 8.19
```
Tests 
- Unit test
```release-note
None
```

In-memory Engine: evaluate SkiplistEngine memory usage

---

src/server/metrics.rs
src/storage/errors.rs

Issue Number: Close #14808
```commit-message
Add more specific error type of raftstore error to metrics 
```
Tests 
Side effects
```release-note
None
```

add more specific error type in ErrorHeaderKind (#14809)

---

components/engine_panic/src/import.rs
components/engine_rocks/src/import.rs
components/engine_traits/src/import.rs
tests/failpoints/cases/test_import_service.rs

Issue Number: Close #17711
```commit-message
Deprecate write_global_seq, since it is by default false.
```
Tests 
Side effects
```release-note
None
```

RocksDB: Deprecate write_global_seq

---

components/resolved_ts/src/resolver.rs

Issue Number: Close #17728
By the definition of resolved-ts, we require:
`commit_ts > resolved_ts`, if the commit happens after the calculation of the resolved-ts.
Our implementation uses min_commit_ts to calculate resolved-ts, so that what we have is: 
`commit_ts >= min_commit_ts >= resolved_ts`
`resolved_ts` may be equal to `commit_ts`, which breaks the definition of resolved-ts.
This PR ensures `min_commit_ts > resolved_ts` to fix the problem
```commit-message
Use min_lock_ts-1 as the candidate of resolved-ts, to ensure resolved_ts < lock.min_commit_ts( <= commit_ts).
```
Tests 
Side effects
```release-note
None
```

resolved-ts: use min_lock_ts-1 as the candidate of resolved-ts

---

components/hybrid_engine/src/observer/load_eviction.rs
components/in_memory_engine/src/background.rs
components/in_memory_engine/src/config.rs
components/in_memory_engine/src/memory_controller.rs
components/in_memory_engine/src/write_batch.rs
components/tikv_util/src/config.rs
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256
src/config/mod.rs

Issue Number: ref #16141, close #17762
```commit-message
Let in_memory_engine's config`evict-threshold` and `stop-load-threshold`
default value generated from `capacity`.
```
- in_memory_engine config default value:
- `evict-threshold`: default value set to capacity - min(capacity * 0.1, 200MiB)
- `stop-load-threshold`: default value set to: evict_threshold - min(capacity * 0.15, region_split_size * 2 + 200MiB)
- set the minimal value of `load-evict-interval` to 120s as the background task will skip the check if the interval is small than 90s.
- Demote some logs in `LoadEvictObserver` from info to debug as RegionManager will also output these logs.
- Change 2 IME load/evcit metrics expression from `rate` to `delta` as the rate is too small and we care the actual event …

in_memory_engine: adjust the default config

---

components/hybrid_engine/src/observer/load_eviction.rs
components/raftstore/src/coprocessor/dispatcher.rs
tests/failpoints/cases/test_in_memory_engine.rs
tests/failpoints/cases/test_stale_peer.rs

Issue Number: Close #17767
```commit-message
IME observes all peer destroy events to timely evict regions. By adding
a new peer, the old and uninitialized peer will be destroyed and IME
must not panic in this situation.
```
Tests 
```release-note
None
```

In-memory Engine: fix panic when destroy an uninitialized region

---

Cargo.lock
components/in_memory_engine/src/config.rs
components/in_memory_engine/src/region_stats.rs
deny.toml
src/config/mod.rs

```commit-message
This commit adjusts the following in-memory-engine defaults:
* `capacity`: Now IME uses 10% of the block cache and takes an equal
amount of memory from the system. This is based on tests showing that
the IME rarely fills its full capacity.
* `mvcc_amplification_threshold`: Change from 100 to 10 which benefit
common workloads like TPCc (50 warehouse), saving approximately 20%
of unified read pool CPU usage.
Also, it addresses two security issues:
* Remove ignore of RUSTSEC-2024-0006, as vulnerable shlex 0.1.1 is
removed by #13814
* Upgrade hashbrown from yanked 0.15.0 to 0.15.1
```
Tests 
- Unit test
```release-note
None
```

In-memory Engine: Adjust memory settings based on available memory

---

components/engine_traits/src/region_cache_engine.rs
components/hybrid_engine/src/observer/load_eviction.rs
components/in_memory_engine/src/background.rs
components/in_memory_engine/src/config.rs
components/in_memory_engine/src/engine.rs
components/in_memory_engine/src/memory_controller.rs
components/in_memory_engine/src/region_stats.rs
components/in_memory_engine/src/write_batch.rs
components/raftstore/src/coprocessor/dispatcher.rs
src/config/mod.rs
tests/failpoints/cases/test_in_memory_engine.rs
tests/failpoints/cases/test_stale_peer.rs

Issue Number:
ref #17767 
ref #16141
```commit-message
In-memory engine: handle error when getting regions info (#17805)
ref tikv/tikv#16141
handle error when getting regions info
---
In-memory Engine: Adjust memory settings based on available memory (#17515)
ref tikv/tikv#16141
This commit adjusts the following in-memory-engine defaults:
* `capacity`: Now IME uses 10% of the block cache and takes an equal
amount of memory from the system. This is based on tests showing that
the IME rarely fills its full capacity.
* `mvcc_amplification_threshold`: Change from 100 to 10 which benefit
common workloads like TPCc (50 warehouse), saving approximately 20%
of unified read pool CPU usage.
Also, it addresses two security issues:
* …
```

Rollup of In-memory Engine commits #17805, #17515, #17771, #17763 and #17747

---

components/raftstore/src/store/fsm/peer.rs

Issue Number: Close #17701
```commit-message
add write batch limit for raft command batch
```
Now, the request size in RaftCmdRequest is limited by raft_entry_max_size when batching where raft_entry_max_size can be set to arbitrarily large. 
In this PR, a MAX_BATCH_SIZE_LIMIT is introduced to limit the RaftCmdRequest requests batch.
Tests 
Side effects
```release-note
None
```

raftstore: add write batch limit for raft command batch

---

components/tidb_query_expr/src/impl_math.rs

Issue Number: Close https://github.com/tikv/tikv/issues/17852
1. `radians` changes from `arg * PI / 180` to `arg * (PI / 180)` to avoid infinite float issues. FYI: https://github.com/mysql/mysql-server/blob/ee079e5ca930ce5ed0643326abadeed8cd41fffc/sql/item_func.h#L1556 MySQL also calculate `PI / 180` firstly.
2. The result of `degrees` can be infinite so adding a check for it.
```commit-message
expr: fix panic when using radians and degree
```
Tests 
Side effects
```release-note
None
```

expr: fix panic when using radians and degree

---

src/server/lock_manager/waiter_manager.rs
src/storage/lock_manager/lock_waiting_queue.rs
src/storage/lock_manager/mod.rs
src/storage/txn/scheduler.rs

This PR ports https://github.com/tikv/tikv/pull/17500 to master.
https://github.com/tikv/tikv/pull/17500 was first planned to be used as the fix for versions <= 8.1, however, the complete fix (https://github.com/tikv/tikv/pull/17451) was then still considered too risky. So we decided to also use https://github.com/tikv/tikv/pull/17500 as the fix for master as well as 8.5 branch, and the complete fix will be left and may be considered in the future.
After this fix, there may be a little more false posotive / false negative cases in the deadlock detection under lock contention scenarios.
Issue Number: Close #17394
```commit-message
lock_manager: Skip updating lock wait info for non-fair-locking requests
This is a simpler and lower-risky fix of the OOM issue #17394 for …
```

lock_manager: Skip updating lock wait info for non-fair-locking requests (#17500)

---

components/sst_importer/src/sst_importer.rs

Problem:
Previously, Rusoto’s behavior involved lazy loading of credentials, so this issue never surfaced. However, the new SDK may block during credential loading.
We implemented a DashMap that locks the entry to ensure only one thread can load the credentials at a time. However, if this thread gets blocked during the runtime, it can lead to a deadlock.
block outside of dashmap.
Tests 
Side effects
```release-note
None
```

fix dead lock when create external storage in less threads

---

scripts/deny

Issue Number: Close #17928 
Use `--locked` to make sure `cargo-deny` follows TiKV's `cargo.lock` for dependency 
```commit-message
Fix cargo-deny install for make clippy
```
Tests 
Side effects
```release-note
None
```

clippy: Fix cargo-deny install for make clippy

---

components/raftstore/src/store/fsm/peer.rs
src/server/raftkv/mod.rs

Issue Number: Ref #16818 
For the issue https://github.com/tikv/tikv/issues/16818.
Possible reasons for the occurrence of duplicate `PUT` requests to the lock CF for the same key in a single `RaftCmdRequest` are as follows:
1. **Duplicate Entries in the Proposed `RaftCmdRequest`**:  
The `RaftCmdRequest` being proposed contains duplicate entries. For example, the transaction write command initiated during async write may have duplicate key entries. This is typically unexpected. In TiKV's transaction model, every key being written must acquire a latch before writing. Concurrent writes to the same key are sequenced through the latch and should not end up in the same `RaftCmdRequest`.
2. **Batch Builder Aggregating Writes to the Same Key**:  
During the batch building process …

raftstore: add more duplicate entry check before proposing write command and batching commands

---

Cargo.lock
cmd/tikv-server/src/main.rs
components/server/src/server.rs
deny.toml

Issue Number: ref https://github.com/tikv/tikv/issues/15990.
Fix the newly found vulnerable warning https://rustsec.org/advisories/RUSTSEC-2024-0421.
```commit-message
```
Tests 
Side effects
```release-note
None.
```

*: upgrade url to 2.5.4 to fix RUSTSEC-2024-0421.

---

components/server/src/server.rs
components/server/src/server2.rs
deny.toml
tests/integrations/raftstore/test_stats.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/17939
With https://github.com/tikv/tikv/pull/17947, the checking and updating of the disk_stat has been
unified into the disk-checker by triggering a periodical task.
However, this approach is incompatible with the scenario where `reserve-space` is set
to 0, which prevents the checker from functioning as intended and leads to disk stats not
being updated periodically. This PR addresses and resolves this issue.
```commit-message
This PR addresses and resolves the issue that if `reserver-space` is set to 0, 
the disk stats could not be updated as expected.
```
Tests 
Side effects
```release-note
None.
```

storage: fix the check if `reserve-space` == 0.

---

components/server/src/server.rs
components/server/src/server2.rs
tests/integrations/raftstore/test_stats.rs

This is an manual cherry-pick of #17964
Issue Number: Ref https://github.com/tikv/tikv/issues/17939
With https://github.com/tikv/tikv/pull/17947, the checking and updating of the disk_stat has been
unified into the disk-checker by triggering a periodical task.
However, this approach is incompatible with the scenario where `reserve-space` is set
to 0, which prevents the checker from functioning as intended and leads to disk stats not
being updated periodically. This PR addresses and resolves this issue.
```commit-message
This PR addresses and resolves the issue that if `reserver-space` is set to 0, 
the disk stats could not be updated as expected.
```
Tests 
Side effects
```release-note
None.
```

storage: fix the check if reserve-space == 0. (#17964)

---

components/raftstore/src/store/snap/io.rs
components/raftstore/src/store/worker/region.rs

This is a manual cherry-pick of #17594
Issue Number: Ref https://github.com/tikv/tikv/issues/17376
This pr is an enhancement for the previous work https://github.com/tikv/tikv/pull/17408.
This pr is introduced to ensure that the state of region and snapshot will be flushed after applying
snapshot.
```commit-message
Ensure that the state of snapshot and region will be flushed into kvdb.
```
Tests 
Side effects
```release-note
None.
```

snap: ensure the state of snapshot flushed after applying snapshots. (#17594)

---

Cargo.lock

Issue Number: Close #18003
```commit-message
This pr revert the relevant updates to `titan` and calibrate
the commit-id to a valid version, used to fix the crash bug
when rolling back tikv from v8.1.2-pre to v8.1.0.
```
Tests 
Side effects
```release-note
None.
```

*: update rust-rocksdb to fix crash bugs.

---

src/server/resolve.rs

Issue Number: Close https://github.com/tikv/tikv/issues/17875
```commit-message
This PR optimizes the error handling progress when resolving address returns
by the response from PD. 
If the response contains `store xxx not found`, the resolver could directly returns
the `StoreTombstone` Error to make the raft-client end the retrying loop quickly.
```
Tests 
Side effects
```release-note
This PR optimizes the error handling progress when resolving address returns
by the response from PD. 
```

resolve: returns StoreTombstone directly if PD returns `store not found`.

---

components/server/src/server.rs
components/server/src/server2.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/17939
As the updating interval is `1s`, the logging introduced by https://github.com/tikv/tikv/pull/17964 is too frequent. This PR polishes the logging when periodically updating the disk status.
```commit-message
Polish the logging when periodically updating the disk status.
```
Tests 
Side effects
```release-note
None.
```

server: polish the logging when updating disk status.

---

src/server/raftkv/mod.rs

This reverts commit e7a810b8947ba95117d42f45bf14248eea06a5b5.
Issue Number: ref #16141
```commit-message
This commit rollback PR #17927 as it is not the root cause. This rollback can all use IME for following read scenario. 
NOTE: We decide not cherry-pick it back to v8.5 as there may be other potential issue.
```
Tests 
Side effects
```release-note
None
```

in_memory_engine: do not force disable in memory engine for replica read

---

components/hybrid_engine/src/observer/load_eviction.rs
components/raftstore/src/store/worker/disk_check.rs
tests/failpoints/cases/test_in_memory_engine.rs

Issue Number: Close #18046 
```commit-message
Avoid loading region into IME when it is uninitialized to prevent panic
on encoding region end key. This is because `MsgPreLoadRegionRequest`
is sent before leader issue a transfer leader request.
```
Tests 
```release-note
Fix the issue of unexpected assert failure when TiKV enables In-memory Engine
```

In-memory Engine: fix pre-load uninitialized peer panic

---

metrics/grafana/common.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

Issue Number: Close #18060
```commit-message
Use regex expression in panel seriesOverrides to let it compatible with the optional "additional_groupby" alias.
```
Current:
After this change:
Tests 
Side effects
```release-note
None
```

metrics: let panel series overrides compatible with additional group_by

---

Cargo.lock
components/concurrency_manager/Cargo.toml
components/concurrency_manager/benches/update_max_ts.rs
components/concurrency_manager/src/lib.rs
components/server/src/server.rs
components/server/src/server2.rs
src/storage/config_manager.rs

Issue Number: Close #18055 
```commit-message
concurrency_manager: double check via PD TSO before reporting error of invalid max-ts update
```
Tests 
Side effects
```release-note
None
```

concurrency_manager: double check via PD TSO before reporting error of invalid max-ts update

---

Cargo.lock
components/error_code/src/coprocessor.rs
components/txn_types/Cargo.toml
components/txn_types/src/types.rs
src/coprocessor/endpoint.rs
src/coprocessor/error.rs
src/storage/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/scanner/mod.rs
tests/failpoints/cases/test_coprocessor.rs

Issue Number: Close #18065
The coprocessor path log is like:
```
[ERRO] default not found in coprocessor request processing, reqCtx: ReqContext { tag: select, context: region_id: 1 region_epoch { conf_ver: 1 version: 1 } peer { id: 1 store_id: 1 }, ranges: [start: 7480000000000000055F728000000000000001 end: 7480000000000000055F728000000000000003], deadline: Deadline { deadline: MonotonicCoarse(Timespec { sec: 44231, nsec: 825857275 }) }, peer: Some("ipv4:127.0.0.1:48380"), is_desc_scan: Some(false), txn_start_ts: TimeStamp(6), bypass_locks: Empty, access_locks: Empty, cache_match_version: None, lower_bound: [116, 128, 0, 0, 0, 0, 0, 0, 5, 95, 114, 128, 0, 0, 0, 0, 0, 0, 1], upper_bound: [116, 128, 0, 0, 0, 0, 0, 0, 5, 95, 114, 128, 0, 0, 0, 0, 0, 0, 3], perf_level: Uninitialized, …
```

server: print more information when default not found error is encountered

---

Cargo.lock
components/concurrency_manager/Cargo.toml
components/concurrency_manager/src/lib.rs

Issue Number: ref #18055 
```commit-message
When validating max-ts updates, do not report error or panic unless confirmed by PD TSO.
This reduces both false positive and false negative cases.
```
Tests 
Side effects
```release-note
None
```

concurrency_manager: make max-ts checker more robust

---

components/resolved_ts/src/advance.rs

Issue Number: Close #17989
```commit-message
If tso fetch fails, skip updating last_pd_tso.
```
Tests 
Side effects
```release-note
Fix a potential incorrect metric or log about gaps of resolved-ts
```

resolved-ts: skip updating last_pd_tso if tso fetch fails

---

components/txn_types/src/lock.rs
src/storage/txn/actions/prewrite.rs
src/storage/txn/commands/prewrite.rs

Issue Number: Close #18117 
```commit-message
Introduce a new field `use_one_pc` to the `Lock` struct to indicate whether the txn uses 1pc, and use it to prevent locks from being skipped when reading with max-ts.
```
Tests 
Side effects
```release-note
Fix an issue that reads cannot see previous writes when `tidb_enable_async_commit = 0`, `tidb_enable_1pc = 1` and `storage.enable-async-apply-prewrite = true`.
```

txn: prevent 1pc locks from being skipped when reading with max-ts

---

components/tracker/src/lib.rs

Issue Number: Ref #14474
The request source string does not start with `external` or `internal` but `leader` or `follower`.
```
request context=region_id: 24 region_epoch { conf_ver: 1 version: 71 } peer { id: 25 store_id: 1 } record_time_stat: true record_scan_stat: true ... request_source: \"leader_external_Select\" busy_threshold_ms: 1000 ... cluster_id: 7441927100295800224
```
```commit-message
Fix the request source check logic for external or internal
```
Tests 
Side effects
```release-note
None
```

coprocessor: fix the check logic of external request

---

Cargo.lock
Cargo.toml
deny.toml

Issue Number: Close https://github.com/tikv/tikv/issues/17995
Currently, in TIKV, there are two issues encountered when enabling auto-tuning on WriteAmpBasedRateLimiter in the presence of clock-skew problems:
- The `Request()` operation may experience excessive waiting if the time offset is too large, causing pending compactions to hang unexpectedly.
- The `Tune()` process uses an excessively small value for updated bytes to calculate the next `rate_bytes_per_sec_`. This results in the next `Request()` being starved, as `rate_bytes_per_sec_` becomes significantly smaller than the pending requested bytes.
To address these two issues in the presence of clock-skew problems, this PR introduces the following changes:
- Clamps the wait-time limit between 0 and `refill_period_us_` to prevent …

rocksdb: resolve flow control issues caused by clock-skew problems.

---

components/tidb_query_datatype/src/codec/mysql/time/mod.rs
components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18111
```commit-message
Support scalar function from_unixtime in tikv
```
Tests 
Side effects
```release-note
Support scalar function from_unixtime in tikv.
```

expr: support scalar function from_unixtime in tikv

---

components/concurrency_manager/src/lib.rs
components/raftstore/src/store/peer.rs
components/server/src/server.rs
components/server/src/server2.rs
src/server/raftkv/mod.rs
src/storage/config.rs
src/storage/config_manager.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml
tests/integrations/config/test_config_client.rs

```commit-message
config: rename config items for max-ts checker
```
Tests 
Side effects
```release-note
Rename config items for max-ts checker. Introduce the `storage.max-ts` section.
```

config: rename config items for max-ts checker

---

Cargo.lock

Issue Number: Ref https://github.com/tikv/tikv/issues/17995
Currently, in TIKV, there are two issues encountered when enabling auto-tuning on WriteAmpBasedRateLimiter in the presence of clock-skew problems:
- The `Request()` operation may experience excessive waiting if the time offset is too large, causing pending compactions to hang unexpectedly.
- The `Tune()` process uses an excessively small value for updated bytes to calculate the next `rate_bytes_per_sec_`. This results in the next `Request()` being starved, as `rate_bytes_per_sec_` becomes significantly smaller than the pending requested bytes.
To address these two issues in the presence of clock-skew problems, this PR introduces the following changes:
- Clamps the wait-time limit between 0 and `refill_period_us_` to prevent …

[CP-to-7.1] Update rocksdb to fix clock-skew issues.

---

Cargo.lock
components/backup-stream/src/subscription_manager.rs
components/backup/src/endpoint.rs
components/backup/src/utils.rs
components/sst_importer/src/config.rs
components/sst_importer/src/import_mode.rs
components/sst_importer/src/import_mode2.rs
components/sst_importer/src/sst_importer.rs
components/tikv_util/Cargo.toml
components/tikv_util/src/lib.rs
components/tikv_util/src/resizable_threadpool.rs
components/tikv_util/src/stream.rs
src/import/sst_service.rs

This is a cherry-pick of https://github.com/tikv/tikv/pull/17784
Issue Number: Close https://github.com/tikv/tikv/issues/17807 https://github.com/tikv/tikv/issues/17572
```commit-message
A new version of resizable runtime is added, with same performance but won't block the tikv shutting down.
```
Tests 
Side effects
```release-note
A new version of resizable runtime is added, with same performance but won't block the tikv shutting down.
```

Cherry pick #17784 to hot fix

---

components/cdc/src/delegate.rs
components/cdc/src/initializer.rs
components/cdc/tests/integrations/test_cdc.rs

Issue Number: Close #18142 
#17656 skips to put unobserved events into the `Resolver`. It's incorrect.
This PR fixes this.
```commit-message
cdc: fix the panic introduced by #17656
```
Tests 
Side effects
```release-note
None
```

cdc: fix the panic introduced by #17656

---

components/backup-stream/src/endpoint.rs
components/backup-stream/tests/failpoints/mod.rs
components/backup-stream/tests/integration/mod.rs

Issue Number: Close #18087
```commit-message
This PR makes a task only be unloaded after it reports the state to PD.
```
Tests 
Side effects
```release-note
Fixed a bug that may cause PiTR stop to advance after a PD failure.
```

upload pause state before unloading a task

---

components/cdc/src/delegate.rs
components/cdc/src/initializer.rs
components/cdc/tests/integrations/test_cdc.rs

Issue Number: Close #18142 
It's a cherry-pick of https://github.com/tikv/tikv/pull/18143 .
#17656 skips to put unobserved events into the `Resolver`. It's incorrect.
This PR fixes this.
```commit-message
cdc: fix the panic introduced by #17656
```
Tests 
Side effects
```release-note
None
```

cdc: fix the panic introduced by #17656 (#18143)

---

components/cloud/aws/src/kms.rs
components/cloud/aws/src/s3.rs
components/cloud/aws/src/util.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18159
At an earlier stage, TiKV implemented region name validation to prevent errors caused by users setting random or incorrect region names. While this safeguard was effective in avoiding user mistakes, it also introduced limitations for the system itself.
Specifically, this check can cause backups to fail if new regions are added but the validation logic is not promptly updated to reflect the changes. To ensure greater flexibility and reduce the risk of backup disruptions, it is better to move this check to a more appropriate stage in the process.
```commit-message
s3: remove region check when create storage
```
Tests 
Normally br will check the region at the client side and report dns error
```
[2025/01/21 …
```

aws: remove region check when create s3 storage

---

components/resource_control/src/future.rs

Fix unused warnings when running the following command
```
cargo check --workspace --all-targets
```
Tests 
- Unit test
```release-note
None
```

resource_control: fix unused warnings

---

components/tidb_query_datatype/src/codec/mysql/time/interval.rs
components/tidb_query_datatype/src/codec/mysql/time/mod.rs
components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18184
```commit-message
Support `timestampdiff` expression function
```
Tests 
Side effects
```release-note
Support `timestampdiff` expression function
```

Support `timestampdiff` expression function

---

Cargo.lock

Issue Number: Close #18196
```commit-message
Update RocksDB to include a fix which add enable_multi_thread_write as deprecated option, so that RocksDB won't panic due to unrecognized option. 
```
Tests 
Side effects
```release-note
Update RocksDB to include a fix which add enable_multi_thread_write as deprecated option, so that RocksDB won't panic due to unrecognized option. 
```

RocksDB: Update RocksDB to include fix for deprecated option

---

Cargo.lock
components/tidb_query_datatype/src/codec/mysql/time/tz.rs
components/tidb_query_expr/Cargo.toml
components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Issue Number: Close #18191
```commit-message
```
Tests 
Side effects
```release-note
Support scalar function unix_timestamp in tikv
```

expr: support scalar function unix_timestamp in tikv

---

components/raftstore/src/store/worker/disk_check.rs

Issue Number: ref #17884
```commit-message
Cleanup the useless stub file ".disk_latency_inspector.tmp" when the running is dropped.
```
Tests 
- After this change, there won't be a obsolescent ".disk_latency_inspector.tmp" under tests directory after running integration tests.
Side effects
```release-note
None
```

raftstore: clean up the disk_latency_inspector file at exit

---

components/cloud/azure/src/azblob.rs

Issue Number: Close #18206
```commit-message
Now, azure blob storage authorizates by the client default when there isn't user provided key.
```
Tests 
I ran a full backup / restore / pitr restore with this patch in an azure virtual machine, with permissions provided by the user provided identity.
Side effects
```release-note
Now, azure blob storage authorizates by the client default when there isn't user provided key.
```

use default credential loader when there isn't user specified cred

---

components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_merge.rs

Issue Number: Close #18129
```commit-message
During region merge, the CacheUpLogs phase is used to ensure all peers can replicate all the raft logs even if leader is already merged. The original low bound of these logs is calculated by the min matched index of all peers. But in #9982, the bound is replaced with the min committed index, but this is not correct because committed index can not ensure raft state can be recovered from the CatchUpLogs message when the current leader is restarted after proposing PrepareMerge.
```
Tests 
Side effects
```release-note
None
```

raftstore: do not override min_matched index with min_committed index

---

components/raftstore-v2/src/operation/query/lease.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_replica_stale_read.rs

Issue Number: Close #17497
```commit-message
Fix flaky test by refining checks.
Read index is also used for checking leadership, a slow test (triggers check leader lease tick) may propose a read index req thus causing the test to fail. This PR differentiate read index proposed by followers for read from other read index requests.
```
Tests 
Side effects
```release-note
None
```

tests: Fix flaky stale read test by refining checks

---

components/tidb_query_expr/src/impl_time.rs

Issue Number: Close #18222
```commit-message
```
Tests 
Side effects
```release-note
Make unix_timestamp return 0 when datetime is invalid
```

Make unix_timestamp return 0 when datetime is invalid

---

src/server/gc_worker/gc_manager.rs
src/server/gc_worker/gc_worker.rs

Issue Number: Close #18214
```commit-message
Do not acquire lock in gc task callback when meeting GcWorkerTooBusy.
```
Tests 
Side effects
```release-note
Fix the deadlock issue when gc worker is busy.
```

gc_worker: fix deadlock when gc worker is busy

---

src/storage/mvcc/reader/reader.rs
src/storage/txn/commands/acquire_pessimistic_lock.rs
src/storage/txn/commands/check_secondary_locks.rs
src/storage/txn/commands/commit.rs
src/storage/txn/commands/flush.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/commands/resolve_lock.rs
src/storage/txn/commands/rollback.rs

Issue Number: Close #18208
```commit-message
When the write schedulers need to read multiple keys, it can be done using a cursor, which includes near-seek optimizations.
This PR leverages the cursor to minimize costly seek operations.
```
Tests 
Pipelined DML which resolve 2e8 locks
- nightly: 43m31s
- this PR: 36m51s
Range non-index update on sysbench table (50 continous keys)
- nightly: 4494tps
- this PR: 5624tps
Scheduler prewrite
Scheduler commit
Sysbench bulk insert, the bottleneck is not in the scheduler side, so the result is close. However, the CPU usage in scheduler pool is quite different.
- nightly: 279223tps
- this PR: 284872tps
Side effects
```release-note
Optimize the write performance by using read cursor in transaction scheduler.
```

txn: optimize the performance of schedulers by read cursor

---

src/import/sst_service.rs
tests/failpoints/cases/test_import_service.rs
tests/integrations/import/test_apply_log.rs
tests/integrations/import/test_sst_service.rs

Issue Number: ref https://github.com/tikv/tikv/issues/18124
To prevent TiKV OOM during imports, this PR introduces a memory usage detection mechanism with a limiter. If a TiKV node reaches 90% memory usage, it will reject further import requests to ensure stability.
```commit-message
Add memory limit for importers to prevent OOM in TiKV
```
Tests 
Side effects
```release-note
Add memory limit for importers to prevent OOM in TiKV
```

importer: add memory limit for importers to avoid OOM

---

components/cdc/src/service.rs

Issue Number: Close #18245
```commit-message
This PR ensures that Deregister::Conn(conn_id) is always executed when a CDC connection closes, even if an error occurs in recv_req. Previously, if an error happened early, the deregistration step could be skipped, leading to potential connection leaks.
```
Tests 
Side effects
```release-note
None
```

cdc: ensure `Deregister::Conn` is always triggered

---

src/import/sst_service.rs
tests/failpoints/cases/test_import_service.rs
tests/integrations/import/test_apply_log.rs
tests/integrations/import/test_sst_service.rs

Issue Number: ref https://github.com/tikv/tikv/issues/18124
The previously (https://github.com/tikv/tikv/pull/18192) implemented memory check was too conservative, leading to unnecessary rejections even when there was still available memory.
For example, on an 8GB node, the memory_usage_limit was calculated as 6GB, and applying the 0.9 threshold effectively resulted in a 5.4GB limit, which is only 67.5% of the total memory. This led to premature rejection of import requests, even when the system still had usable memory.
```commit-message
import: make memory check more aggressive.
```
Tests 
- [] Unit test
Side effects
```release-note
None
```

import: relax memory check constraints

---

cmd/tikv-ctl/src/cmd.rs
cmd/tikv-ctl/src/main.rs
components/compact-log-backup/src/exec_hooks/mod.rs
components/compact-log-backup/src/exec_hooks/skip_small_compaction.rs
components/compact-log-backup/src/execute/mod.rs
components/compact-log-backup/src/execute/test.rs

Issue Number: Close #18234
```commit-message
Added `--minimal-compact-size` to `compact-log-backup`.
```
Tests 
Side effects
```release-note
None
```

compact_log_backup: added minimal compactions size

---

components/backup-stream/src/checkpoint_manager.rs
components/backup-stream/src/endpoint.rs
components/backup-stream/tests/failpoints/mod.rs

Issue Number: Close #18262
```commit-message
This will make `force-flush` wait the last flush if there is a running one instead of just return an error.
```
Tests 
Side effects
```release-note
None
```

log_backup: always wait force flush RPCs

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_hibernate.rs

Issue Number: Close #18233
In previous work #16239, we introduced the `busy_on_apply` state to indicate
whether a `Peer` is pending the application of pending Raft logs upon restart.
However, this approach misses a corner case: if the `Peer` quickly enters the
`hibernate` state after restarting, the `busy_on_apply` state may not be updated
in a timely manner. This results in the Node failed to update the count of pending
applying regions, continuously reporting an incorrect `is_busy == true` state to PD. 
Consequently, this can slow down the rolling-restart progress more than expected.
Therefore, this PR addresses this issue by updating the applied state in `on_apply_res`.
```commit-message
Fix the bug where some hibernated peers, marked with `busy_on_apply == true`, …
```

raftstore: avoid early hibernate if pending on applying logs when restart

---

components/concurrency_manager/src/lib.rs
src/server/gc_worker/gc_worker.rs

```commit-message
Fix a fake error log in gc worker.
```
Tests 
- [] No code
Side effects
```release-note
None
```

concurrency-manager: (release-7.5) do not assert in max ts checker

---

components/raftstore/src/store/fsm/apply.rs

Issue Number: close #18275 
Excluding TransferLeader from WAL synchronization, TiKV can reduce unnecessary I/O operations, thereby mitigating latency spikes during leader transfers.
```commit-message
```
Tests 
- Unit test
```release-note
None
```

raftstore: skip sync WAL for transfer leader admin commands

---

components/sst_importer/src/sst_writer.rs
tests/failpoints/cases/test_import_service.rs
tests/integrations/import/test_sst_service.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18279
- Check commit-ts in batch of key-values when write SST in the process of `ingest`.
```commit-message
```
Tests 
Side effects
```release-note
Not.
```

importer: check commit-ts when ingest

---

components/concurrency_manager/src/lib.rs
src/server/gc_worker/gc_worker.rs

```commit-message
Fix a fake error log in gc worker.
```
Tests 
Side effects
```release-note
None
```

concurrency-manager: (release-8.1) do not assert in max ts checker

---

components/concurrency_manager/src/lib.rs
src/server/gc_worker/gc_worker.rs

```commit-message
Fix a fake error log in gc worker.
```
Tests 
Side effects
```release-note
None
```

concurrency-manager: (release-6.5) do not assert in max ts checker

---

components/concurrency_manager/src/lib.rs
src/server/gc_worker/gc_worker.rs

```commit-message
Fix a fake error log in gc worker.
```
Tests 
Side effects
```release-note
None
```

concurrency-manager: (release-7.1) do not assert in max ts checker

---

src/server/gc_worker/gc_worker.rs

Issue Number: ref #18213
```commit-message
Fix a false error log from gc worker
```
Tests 
Side effects
```release-note
Fix a false error log from gc worker
```

gc-worker: (release-8.5) fix the false error log from gc worker

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/tests/failpoints/test_endpoint.rs
components/cdc/tests/mod.rs

Issue Number: Close #18306
```commit-message
Include regions that have not completed scan locking in the unresolved region count.
```
Tests 
Side effects
```release-note
None.
```

cdc: fix unresolved region metrics

---

src/storage/mvcc/reader/reader.rs
src/storage/txn/commands/acquire_pessimistic_lock.rs
src/storage/txn/commands/check_secondary_locks.rs
src/storage/txn/commands/commit.rs
src/storage/txn/commands/flush.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/commands/resolve_lock.rs
src/storage/txn/commands/rollback.rs

Issue Number: Close #18249
```commit-message
This reverts commit 57b0b62c211c3555c16ea9b80babd13676a12e2c because it introduces a consistency issue.
The cursor in the MVCC reader requires stricter usage (the key and timestamp must be monotonic).
However, the complex usage in schedulers does not guarantee this invariant, which leads to the consistency issue.
```
Tests 
Run the bank workload successed.
```
./main
[2025/03/19 17:10:02.993 +08:00] [INFO] [main.go:118] ["Start bank workload"]
[2025/03/19 17:10:02.993 +08:00] [INFO] [main.go:192] ["Setting up bank tables and accounts..."]
[2025/03/19 17:10:03.332 +08:00] [INFO] [main.go:397] ["Balance verification passed"] [total=2000000]
[2025/03/19 17:10:03.333 +08:00] [INFO] [main.go:281] ["Starting bank transfers..."] …
```

txn: revert #18200 to fix the data inconsistency

---

src/import/sst_service.rs
tests/failpoints/cases/test_import_service.rs

Issue Number: Close #18317
and close https://github.com/pingcap/tidb/issues/60140
1. Get memory limit multiple times is unnecessary. 
2. The previous memory checks's granularity was too fine, performing a check on every chunk. Since Lightning writes in 16KB chunks, the frequent checks resulted in noticeable overhead.
1. This PR change the behavior to only get memory limit once at beginning. 
2. This PR adjusts the memory check to be performed per request instead of per chunk
```commit-message
sst_importer: Get Memory limit at the sst service initialization #18321
```
Tests 
Side effects
```release-note
None
```

sst_importer: Get Memory limit at the sst service initialization

---

components/tracker/src/lib.rs
components/tracker/src/slab.rs
src/coprocessor/endpoint.rs
src/storage/mod.rs
src/storage/txn/scheduler.rs

Issue Number: Close #18345
```commit-message
`grpc_process_time` is the time used in TiKV gRPC request processing,
measured from receiving the request to the start of handling the request.
To make it accurate, it should start tracking as early as possible.
```
Tests 
```release-note
None
```

storage,coprocessor: more accurate grpc_process_time

---

components/tikv_util/src/timer.rs

Issue Number: Close #16623 Close #14518
```commit-message
This commit workarounds a panic[^1] in tokio-timer when the clock goes
backward, which is possible in some environments, e.g., aliyun ECS g7.
[^1]: https://github.com/tokio-rs/tokio/pull/515
```
Tests 
- Unit test
```release-note
Fix the issue that TiKV panics due to system clock goes backward
```

tikv_util: fix tokio-timer panic when clock goes backward

---

components/sst_importer/src/sst_importer.rs
tests/failpoints/cases/test_import_service.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18335
Even though each download request is assigned a UUID, duplicate requests can still occur, possibly due to network issues or improper retries. If a duplicate request happens, we might (in the best case) report a download failure. However, in the worst case, the simulated download could corrupt the file, causing TiKV to panic due to a broken checksum in the ingested file.
```commit-message
sst_importer: add lock for ponential duplicate download
```
Tests 
Side effects
```release-note
Fixed a rare issue where duplicate download requests—caused by improper retries due to network issues—could corrupt files and trigger TiKV panic due to checksum mismatch.
```

sst_importer: add lock for ponential duplicate download

---

Cargo.lock
Makefile

Issue Number: ref #17962, ref #18353, ref #18357
```commit-message
*: Fix build on MacOS 15.4 with Apple clang v17.0.0
```
- Upgrade `libz-sys` to fix #17962
- Upgrade `cmake-rs` to fix #18353
- Add `-Wno-error=vla -Wno-vla-extension` to `CFLAGS` & `CXXFLAGS` to disable `-Werror` and enable ` VLAs` for RocksDB build to fix #18357 
Tests 
```
❯ make clean build
...
...
Finished dev [unoptimized] target(s) in 5m 50s
warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.1.0, nom v5.1.0, quick-xml v0.22.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
❯
```
Side effects
```release-note
*: Fix build on MacOS 15.4 with Apple clang v17.0.0 …
```

*: Fix build on MacOS 15.4 with Apple clang v17.0.0

---

Cargo.lock
clippy.toml
components/backup-stream/src/endpoint.rs
deny.toml

Issue Number: Close #18363
```commit-message
deps: Revert openssl changes of #18356
```
Diff with 3eb3439fd88f0db9de06ef92e845e80b32c9b49a: https://github.com/tikv/tikv/compare/3eb3439fd88f0db9de06ef92e845e80b32c9b49a...pingyu:tikv:revert-openssl
- Ignore [RUSTSEC-2025-0022](https://rustsec.org/advisories/RUSTSEC-2025-0022) to avoid upgrade openssl to 3.x.x
- Fix [RUSTSEC-2025-0023](https://rustsec.org/advisories/RUSTSEC-2025-0023) by downgrade `tokio` to `1.38.2`. Upgrade `tokio` to `1.43.2` will recursively upgrade `libc` from `0.2.151` to `0.2.171` which is risky.
Tests 
Regression build test On MacOS:
```
❯ uname -a
Darwin x.x.x.x 24.4.0 Darwin Kernel Version 24.4.0: Wed Mar 19 21:18:00 PDT 2025; root:xnu-11417.101.15~1/RELEASE_ARM64_T8122 arm64
❯ make build
Finished …
```

deps: Revert openssl changes of #18356

---

Cargo.lock
components/crypto/Cargo.toml
components/crypto/build.rs
components/crypto/src/fips.rs

Issue Number: ref #17465
#17466 breaks FIPS compilation unexpectedly by removing the openssl-sys dependency of the crypto crate.
```commit-message
Ensure that the openssl_sys crate is a dependency of this crate, 
so the build script can detect the openssl version, `ossl1` or `ossl3`.
```
Tests 
- Manual test: https://cd.pingcap.net/job/build-common/352568/console
```release-note
None
```

crypto: fix FIPS compilation

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
Fix typo in resolved-ts pending command size metric.
```
Tests 
Side effects
```release-note
None
```

metric: fix typo in resolved-ts pending command size metric

---

Cargo.lock

```
error[yanked]: detected yanked crate (try `cargo update -p crossbeam-channel`)
┌─ /home/jenkins/tikv-src/Cargo.lock:120:1
│
120 │ crossbeam-channel 0.5.13 registry+https://github.com/rust-lang/crates.io-index
│ 
```
```commit-message
Upgrade crossbeam-channel from yanked 0.5.13 to 0.5.15.
```
Tests 
Side effects
```release-note
None
```

chore: Upgrade crossbeam-channel from yanked 0.5.13 to 0.5.15

---

components/error_code/src/sst_importer.rs
components/sst_importer/src/errors.rs
components/sst_importer/src/sst_importer.rs
tests/failpoints/cases/test_import_service.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18335
- In the previous fix, we added a lock to all download requests and returned OK(None) to skip duplicate download attempts. However, in some more extreme scenarios, returning OK(None) is not appropriate, as it can lead to inconsistent outcomes—some peers may successfully complete the download while others fail.
- Historically, BR has relied on the assumption that all peers must either succeed or fail together; partial failures are not acceptable. Therefore, the new code will make duplicated threads wait for origin download finish the request.
```commit-message
sst_importer: make duplicated download report error 
```
Tests 
Side effects
```release-note
None
```

sst_importer: make duplicated download report error

---

components/raftstore/src/store/fsm/store.rs

Issue Number: Close #[18349](https://github.com/tikv/tikv/issues/18349)
```commit-message
compact the write cf before default cf 
```
```release-note
None
```

raftstore/store: compact the write cf before default cf

---

src/storage/txn/txn_status_cache.rs

Issue Number: Close #18384 
```commit-message
Fix the deadlock issue in txn_status_cache.
When both large_txn_cache and normal_cache needs locking, always acquire large_txn_cache first.
```
Tests 
Side effects
```release-note
Fix the deadlock issue in txn_status_cache.
```

txn_status_cache: avoid deadlock in txn_status_cache with Pipelined DML

---

src/config/mod.rs

Issue Number: Close #18383
```commit-message
test_change_memory_config requires memory profile enabled
```
We already have similar requirement for this test: https://github.com/tikv/tikv/blob/b191726a4fcc42543977fe41ab37ad36703fcb11/components/tikv_alloc/src/jemalloc.rs#L534-L535
Our test script already handles this case as well: https://github.com/tikv/tikv/blob/b191726a4fcc42543977fe41ab37ad36703fcb11/scripts/test-all#L17-L20
Tests 
Side effects
```release-note
None
```

tests: fix test_change_memory_config

---

src/server/server.rs

Issue Number: ref #17176, #18079
```commit-message
Fix the issue that TiKV gRPC service responses don't respect the grpc-accept-encoding of clients.
Do not set defualt compression algorithm for grpc channel; set level instead.
The default algorithm won't check whether the algorithm is supported by client.
```
I verified the fix with the following test cases:
Configured TiKV with compression-type = gzip
Packet capture shows TiDB sends grpc-accept-encoding header that accepts gzip
Communication works as expected
Changed TiKV config to use compression-type = deflate
TiDB failed to communicate with error: "rpc error: code = Unimplemented desc = grpc: Decompressor is not installed for grpc-encoding \"deflate\""
TiDB Dashboard couldn't search TiKV logs
Packet capture confirmed …

server: do not set defualt compression algorithm for grpc channel

---

components/compact-log-backup/src/compaction/exec.rs
components/compact-log-backup/src/test_util.rs

… SST verification tests
Issue Number: Close #18390
```commit-message
Fixed a bug that caused the time range of compaction generated SSTs are too huge.
```
Tests 
Side effects
```release-note
Fixed a bug that caused the time range of compaction generated SSTs are too huge.
```

compact_log_backup: correct version assignment in subcompaction metadata

---

Cargo.lock
Cargo.toml
components/sst_importer/src/metrics.rs
components/sst_importer/src/sst_importer.rs

Adapt ignore rules to make the download can skip some keys larger then specify timestamp
Add support for skipping version entries based on boundary timestamps:
- Ignore entries before a specific timestamp — to exclude stale or unfinished versions.
- Ignore entries after a specific timestamp — to avoid restoring data beyond the target restore point.
This filtering should apply independently to each CF (column family) as appropriate.
Issue Number: Close https://github.com/tikv/tikv/issues/18399
```commit-message
sst_importer: support ignore keys by ts during download
```
Tests 
Side effects
```release-note
Make restore support skip keys in sst files by timestamp
```

sst_importer: support ignore keys by ts during download (#17951)

---

Cargo.lock
components/backup-stream/src/utils.rs
components/log_wrappers/Cargo.toml
components/log_wrappers/src/lib.rs
components/online_config/src/lib.rs
components/security/Cargo.toml
components/security/src/lib.rs
components/server/src/server.rs
components/server/src/server2.rs
components/server/src/setup.rs
components/test_util/src/security.rs
components/txn_types/src/lock.rs
src/config/mod.rs
tests/integrations/config/mod.rs

Issue Number: ref #16568 
Allow dynamic(online) configuration for "security.redact_info_log"
**OUTDATED:**
Add 'allow-dynamic-security-config' config switch to allow online changes to security configurations(e.g. security.redact-info-log)
Tests 
Side effects
```release-note
Allow dynamic(online) configuration for "security.redact_info_log"
```
**OUTDATED:**
Add 'allow-dynamic-security-config' config switch to allow online changes to security configurations(e.g. security.redact-info-log)

Config, Security: Allow dynamic configuration for "security.redact_info_log"

---

Cargo.toml
scripts/test
src/server/service/diagnostics/sys.rs
tests/integrations/backup/mod.rs

Issue Number: Close #18383
```commit-message
Some tests don't make sense if they are run in docker or it is hard to write them
This branch introducer `docker-test` feature and enables it if tests are run in docker
like `make docker_test` does
```
Tests 
Side effects
```release-note
None
```

tests: ignore some tests in make docker_test

---

components/raftstore/src/store/fsm/peer.rs
src/server/raftkv/mod.rs

Issue Number: Ref #16818
```commit-message
Remove unused check logic added in previous investigations of #16818.
```
Tests 
Side effects
```release-note
None
```

server: remove unused check added for investigations

---

components/backup-stream/src/metrics.rs

```commit-message
metrics: fix the typo of metrics
```
Tests 
Side effects
```release-note
Fix the issue that metrics cannot shown in the Grafana.
```

metrics: fix the typos of metrics

---

components/raftstore/src/coprocessor/dispatcher.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/store/worker/region.rs

Issue Number: Ref #13855
The current applying snapshot process is:
- Apply the snapshot in raftstore, and set region's state to Applying
- Schedule the region into region worker for ingesting data
- The region worker ingest the data from the snapshot
- The region's state is updated to Normal and is persisted
- The apply snapshot state is changed to FINISHED, and the region can handle normal raft messages
Before the Normal state is persisted, the ingesting phase could be replayed after a restart. However, if we the snapshot is written into other storages such as TiFlash, it becomes a need to know when the state is persisted as Normal, so the snapshot ingestion won't be replayed anymore.
```commit-message
Introduce a new observer `on_apply_snapshot_committed` so that …
```

Introduce a new observer `on_apply_snapshot_committed` to notice the snapshot data is committed on disk

---

scripts/test-all

Issue Number: Close #18383
Use python3 in scripts/test-all as [Dockerfile.test](https://github.com/tikv/tikv/blob/b62da4f8d35793629eb3c12fd65226bc1763b2cb/Dockerfile.test#L12) does not have python anymore
```commit-message
```
Tests 
Side effects
```release-note
None
```

tests: use python3 for scripts/check-bins.py in test-all

---

Cargo.lock
components/test_storage/src/sync_storage.rs
components/tikv_util/src/log.rs
components/txn_types/src/lib.rs
components/txn_types/src/types.rs
src/import/duplicate_detect.rs
src/server/gc_worker/gc_worker.rs
src/storage/errors.rs
src/storage/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/commit.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/actions/mod.rs
src/storage/txn/actions/mvcc.rs
src/storage/txn/commands/commit.rs
src/storage/txn/commands/mod.rs
src/storage/txn/commands/mvcc_by_key.rs
src/storage/txn/commands/mvcc_by_start_ts.rs
src/storage/txn/commands/resolve_lock.rs
src/storage/txn/commands/resolve_lock_lite.rs
src/storage/txn/mod.rs
src/storage/txn/scheduler.rs
src/storage/txn/store.rs
src/storage/types.rs
tests/benches/hierarchy/mvcc/mod.rs
tests/benches/hierarchy/txn/mod.rs
tests/failpoints/cases/test_storage.rs

Issue Number: Close #18425 
```commit-message
txn: collect mvcc for err `TxnLockNotFound` when commit secondary failed
```
Tests 
Side effects
```release-note
None
```

txn: collect mvcc for err `TxnLockNotFound` when commit secondary failed

---

src/storage/errors.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/commit.rs

Issue Number: Close #18441
```commit-message
When the secondary commit failed with error `CommitTsExpired`, collect the MVCC info for debugging.
```
Tests 
Side effects
```release-note
None
```

txn: collect mvcc for error `CommitTsExpired`

---

src/storage/txn/actions/commit.rs

Issue Number: Close #18441
```commit-message
In the previous PR, we only collect mvcc info when `commit_role` is `Secondary` when `commit_ts < min_commit_ts`. However, when resolving a lock, the `commit_role` of `commit` is None and we cannot get any mvcc info when this error happens. This PR does an enhancement and checks whether the resolved key is primary in the lock, if not, it still collect mvcc for further debugging.
```
Tests 
Side effects
```release-note
None
```

txn: return debug info for some error when `commit_role` is unknown

---

components/raftstore/src/store/fsm/store.rs

Issue Number: Ref #18434
```commit-message
Close some background schedulers before shutting down.
We need to restart both the KV engine and the Raft engine in a test to set some non-online configs.
e.g. turning off Titan.
These background workers have references to either the KV engine or the Raft engine, and they are also
self-referencing, causing the KV engine and Raft engine never get closed on shutting down. We need this
to interrupt the infinite loop, and release the DBs' references.
The best way to resolve this would be using tokio's unbound channel which allows downgrade to weak ptr.
However, TiKV just has too many Arc circular dependencies, it is nearly impossible to detangle it.
```
Tests 
Side effects
```release-note
None
```

Raftstore: Close some background schedulers before shutting down

---

components/backup/src/endpoint.rs

Issue Number: Close #18493 
```commit-message
Some of non-fatal error level logs during backing up are now warn level.
```
Tests 
Side effects
```release-note
Some of non-fatal error level logs during backing up are now warn level.
```

backup: move verbose errors to warn level

---

components/pd_client/src/util.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/snap.rs
components/raftstore/src/store/snap/io.rs
components/server/src/server.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/server.rs
src/server/config.rs
src/server/snap.rs
tests/integrations/raftstore/test_snap.rs
tests/integrations/storage/test_titan.rs

This is a manual cherry-pick of #17408
Issue Number: Close #17412, #17376
```commit-message
Previously, snapshots of regions, with the exception of the `lock_cf` column family,
were flushed to SST files, while `lock_cf` was flushed to plain files. This approach could
lead to a high volume of `ingest` tasks for merging regions, especially when the TiKV
node contained a large number of small-sized regions.  As we all know, an excess of `ingest`
tasks can significantly impair the overall performance of the TiKV node.
To address this issue, this pull request introduces a new configuration option called
`snap_min_ingest_size`. When a region's size is below the threshold set by `snap_min_ingest_size`,
its corresponding snapshot will now be applied without `ingest` SST files. …
```

[hotfix-to-7.5.6] raftstore: directly write kvs rather than ingestion when merging small regions. (#17408)

---

Cargo.lock
components/raftstore/src/store/snap.rs
components/raftstore/src/store/worker/metrics.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/region.rs
tests/failpoints/cases/test_stale_peer.rs

This is a manual cherry-pick of #18040
Issue Number: Close #18107, Ref https://github.com/tikv/tikv/issues/18042
This PR mainly contains the following parts for optimization on scaling, used to mitigate the impacts, introduced by unnecessary ingesting sst files:
- Directly clearing stale ranges by DeleteByKeys during the balancing regions process.
- Do not clear data of offline stores during the scale-in process, as this data will be automatically cleared when the corresponding node goes offline.
```commit-message
Optimizing the processing of clearing stale-ranges by DeleteByKeys, rather than ingesting.
This optimization is used to mitigate the impacts, introduced by unnecessary ingesting sst
files on latency when scaling.
```
Tests 
Taking the `grpc messages duration` in …

[hotfix-to-7.5.6] raftstore: remove stale ranges by DeleteByKeys rather than ingesting. (#18040)

---

components/engine_panic/src/misc.rs
components/engine_rocks/src/misc.rs
components/engine_traits/src/misc.rs
src/import/ingest.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18549
To mitigate the latency jitters introduced by `get_sst_key_ranges` if there exists too many L0s in Rocksdb, this PR:
- Removes the logging for "sst ingest is too slow" to avoid latency jitters.
- Removes `get_sst_key_ranges` as this function is deadcode.
```commit-message
Removes the logging for "sst ingest is too slow" to avoid latency jitters.
```
Tests 
Side effects
```release-note
Removes the logging for "sst ingest is too slow" to avoid latency jitters.
```

*: remove the logging for "sst ingest is too slow" to avoid latency jitters.

---

src/config/mod.rs

Issue Number: ref https://github.com/tikv/tikv/issues/18503
The previous https://github.com/tikv/tikv/pull/18505 introduces the inheritage of `region-size` configurations. But it has introduced unexpected changes to `compatible_adjust`, which makes the new config inherit unexpected configurations from the last config file to `RaftstoreConfig`.
This PR is used to fix this issue.
```commit-message
Avoid the inheritage of unexpected configurations from the last config file.
```
Tests 
Side effects
```release-note
Avoid the inheritage of unexpected configurations from the last config file.
```

config: avoid inherting unnecessary configs to RaftstoreConfig from the last config file

---

Cargo.lock
Cargo.toml
deny.toml

Issue Number: Close https://github.com/tikv/tikv/issues/18605
More details can be reviewed in https://github.com/tikv/raft-engine/pull/382.
```commit-message
Optimizes `fetch_entries_to` in Raft-Engine to reduce contention and improve performance under mixed workloads.
```
Tests 
Side effects
```release-note
Optimizes `fetch_entries_to` in Raft-Engine to reduce contention and improve performance under mixed workloads.
```

*: update raft-engine to optimize `fetch_entries_to`.

---

components/engine_panic/src/misc.rs
components/engine_rocks/src/misc.rs
components/engine_traits/src/misc.rs
components/raftstore/src/store/worker/region.rs
components/test_sst_importer/src/util.rs
src/import/ingest.rs
src/import/sst_service.rs
tests/integrations/import/test_sst_service.rs

Issue Number: Close #18452
```commit-message
This patch addresses #18452 by serializing the write stall check using 
a mutex and tracking inflight WriteCF SSTs. This ensures all concurrent
ingests are accounted for, making the L0 check more conservative and 
preventing over-admission.
```
Tests 
- The test failed consistently without this fix.
Side effects
```release-note
Fix over-admission of SST ingest requests in highly concurrent scenarios.
```

import: track inflight ingests during write stall check

---

Cargo.lock
Cargo.toml

Issue Number: Close https://github.com/tikv/tikv/issues/18474
Bump the version of pprof-rs to 0.15
```commit-message
bump the version of pprof-rs to 0.15
```
Tests 
Side effects
```release-note
None
```

*: bump version of pprof-rs to 0.15 (#18485)

---

components/batch-system/src/router.rs

Issue Number: Close #18713
```commit-message
The `check_do` method currently uses get_mut when only read access is
required. This unnecessary mutable borrow may cause severe lock
contention, especially since check_do is a hot path invoked on every
message sent to raftstore. Switching to a read-only borrow reduces
contention and improves tail latency.
```
Tests 
- Unit test
```release-note
None
```

batch-system: fix router `check_do` lock contention

---

components/raftstore/src/store/util.rs
components/raftstore/src/store/worker/read.rs
components/raftstore/src/store/worker/region.rs
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/util.rs
tests/failpoints/cases/test_replica_read.rs

Issue Number: close #18570
```commit-message
Set `read_index_safe_ts` to 0 when `RegionReadProgress` is paused to prevent unsafe follower read.
```
Tests 
Side effects
```release-note
Fix the issue that follower read may get wrong result through follower read cache.
```

raftstore: invalidate follower read cache when region is destroyed

---

components/raftstore-v2/src/operation/command/admin/compact_log.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore/src/store/entry_storage.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/peer_storage.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18588
This PR adds a `TermCache` to store recently accessed or updated Raft log terms, reducing unnecessary I/O reads on RaftEngine when queried log indices are evicted from the EntryCache. (PS: The TermCache introduces minimal additional memory usage—only ~20–30 MiB per TiKV node, even with 300k regions/peers.)
To be briefly:
- For Efficiency & Memory Usage: The `TermCache` maintains a small fixed capacity (8) for optimal performance and low memory overhead. Entries are stored in monotonically increasing order, where the first term is the oldest and the last term is the freshest.
- For Entry Structure: Each entry consists of `(term, start_index_of_this_term)`, ensuring quick lookups for term boundaries.
- For safety …

PeerStorage: add TermCache caching recent terms to avoid unnecessary I/O ops.

---

tests/failpoints/cases/test_memory_usage_limit.rs

Issue Number: Close #18257 
```commit-message
Previously, the test assumed that at most one no-op AppendEntry RPC
would be sent during multiple writes, which occasionally led to test
failures. This assumption does not always hold, so the assertion has
been relaxed to tolerate multiple no-op AppendEntry RPCs.
Multiple no-op entries can be generated in the following scenario:
when the Leader sends a Heartbeat message to a Follower and immediately
follows it with an AppendEntry message, it may receive the Heartbeat
Response before the AppendResponse. If the Leader detects that the
Follower’s log is not matched upon receiving the Heartbeat Response,
it may proactively send a no-op AppendEntry to align logs. If this
pattern occurs repeatedly in tests, it can result in multiple …
```

raftstore: fix flaky test test_evict_early_avoids_reject

---

components/engine_panic/src/compact.rs
components/engine_rocks/src/compact_listener.rs
components/engine_traits/src/compact.rs
components/raftstore-v2/src/batch/store.rs
components/raftstore/src/coprocessor/region_info_accessor.rs
components/raftstore/src/coprocessor/split_check/half.rs
components/raftstore/src/coprocessor/split_check/keys.rs
components/raftstore/src/coprocessor/split_check/size.rs
components/raftstore/src/coprocessor/split_check/table.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/worker/split_check.rs
components/server/src/server.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/server.rs
tests/integrations/config/dynamic/split_check.rs

Issue Number: ref #18532
This PR is an extend of #18565 and introduces `lock-free` handling of `CompactedEvent`, used to optimize the handling of `CompactedEvent`.
```commit-message
Introduces lock-free handling of CompactedEvent to avoid raftstore threads waiting the lock of `StoreMeta`.
```
Tests 
Side effects
```release-note
Introduces lock-free handling of CompactedEvent to avoid raftstore threads waiting the lock of `StoreMeta`.
```

raftstore: use lock-free handling of CompactedEvent

---

tests/failpoints/cases/test_stats.rs

Issue Number: Close #18802 
```commit-message
Remove region idle detection from this test to prevent bucket stats report from being blocked
```
Tests 
Side effects
```release-note
fix flaky test `test_bucket_stats`
```

fix flaky test test_bucket_stats

---

Cargo.lock
components/raftstore/src/coprocessor/region_info_accessor.rs
components/server/src/server.rs
components/test_raftstore/src/server.rs
components/tidb_query_common/Cargo.toml
components/tidb_query_common/src/storage/mod.rs
components/tidb_query_executors/src/runner.rs
components/tikv_kv/src/lib.rs
components/tikv_kv/src/mock_engine.rs
components/tikv_kv/src/rocksdb_engine.rs
components/tikv_util/src/deadline.rs
src/coprocessor/dag/mod.rs
src/coprocessor/endpoint.rs
src/coprocessor/mod.rs
src/coprocessor/tracker.rs
src/import/sst_service.rs
src/server/raftkv/mod.rs
src/server/raftkv2/mod.rs
src/storage/txn/store.rs
tests/benches/coprocessor_executors/integrated/util.rs
tests/benches/coprocessor_executors/util/mod.rs
tests/benches/misc/raftkv/mod.rs
tests/integrations/mod.rs
tests/integrations/raftstore/test_region_info_accessor.rs
tests/integrations/raftstore/test_snap.rs

Issue Number: Close #18812
```commit-message
- Introduce a new trait: `RegionStorageAccessor` to access the snapshot for secondary regions in cop-task
- Add a new function `seek_region` to `Engine` so that it can seek regions when executor is running.
- Introduce `SecondarySnapStoreAccessor` to impl  `RegionStorageAccessor`.
- Make the `ReqContext` a immutable value that can be shared accross threads safely
```
Tests 
Side effects
```release-note
None
```

coprocessor: Add `RegionStorageAccessor` to provide store for secondary regions in cop-task

---

src/storage/txn/flow_controller/singleton_flow_controller.rs

Issue Number: Close #18728
Related PR: #17458
```commit-message
Fixes a corner case where flow control could stay disabled if `unsafe destroy range`
was executed when `pending_compaction_bytes` was zero. In this case, no compaction
events occurred to notify the controller that bytes had reached zero, leaving the
jump-control flag uncleared. Later compaction activity usually reports bytes > 0,
keeping flow control disabled indefinitely.
We now re-enable flow control when both the current and long-term average pending
compaction bytes are below the soft threshold after `unsafe destroy range`.
```
Tests 
Side effects
```release-note
None
```

storage: fix flow control not resuming after unsafe destroy range

---

components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_controller.rs
components/resource_metering/src/lib.rs
components/resource_metering/src/model.rs
components/resource_metering/src/recorder/mod.rs
components/resource_metering/src/recorder/sub_recorder/cpu.rs
components/resource_metering/src/reporter/mod.rs

Issue Number: Close #18844 
```commit-message
Add an aggregator to aggregate RawRecords by the extra tag before picking topN records.
```
Tests 
Test the TPCH10 benchmark, and check the other time drops from 38% to 0.0033%.
Side effects
```release-note
It improves the accuracy of data collected for topsql.
```

resource_metering: Aggregate RawRecords before picking topN records

---

components/compact-log-backup/src/storage.rs

Issue Number: Close #18843
```commit-message
Merge the same meta edit from different migrations instead of replacing.
```
Tests 
Side effects
```release-note
None
```

compact_log_backup: fix compact meta edit filter

---

components/compact-log-backup/src/compaction/meta.rs
components/compact-log-backup/src/exec_hooks/save_meta.rs
components/compact-log-backup/src/execute/hooking.rs
components/compact-log-backup/src/execute/mod.rs
components/compact-log-backup/src/storage.rs

Issue Number: Close #18884
```commit-message
This PR spawns read s3 file tasks to remote threads.
```
Tests 
Before:
```
{"level":"INFO","caller":"save_meta.rs:174","message":"Migration written.","time":"2025/08/26 08:15:25.388 +00:00","thread_id":1,"duration":"878.241073919s"}
```
After:
```
{"level":"INFO","caller":"save_meta.rs:174","message":"Migration written.","time":"2025/08/27 09:11:16.222 +00:00","thread_id":1,"duration":"521.078651373s"}
```
Side effects
```release-note
None
```

compact_log_backup: offload reading meta to diff cpus

---

components/raftstore/src/store/compaction_guard.rs

Issue Number: Close #18912
```commit-message
Fix the incorrect assert of compaction guard introduced by #18866.
```
Tests 
Side effects
```release-note
None
```

rocksdb: fix compaction guard overlap check

---

Cargo.lock
cmd/tikv-server/Cargo.toml

Issue Number: ref https://github.com/tikv/tikv/issues/16328
Fix [RUSTSEC-2025-0055](https://rustsec.org/advisories/RUSTSEC-2025-0055).
```commit-message
Fix RUSTSEC-2025-0055.
```
Tests 
Side effects
```release-note
None
```

cargo deny: fix RUSTSEC-2025-0055.

---

src/server/config.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/18797
```commit-message
Should allow user set inspect_network_interval zero. Zero represents disable inspection.
```
Tests 
Side effects
```release-note
None
```

config: add more check for inspect_network_interval

---

Cargo.lock
components/test_coprocessor/src/dag.rs
components/tidb_query_common/src/execute_stats.rs
components/tidb_query_datatype/src/codec/chunk/chunk.rs
components/tidb_query_datatype/src/codec/chunk/column.rs
components/tidb_query_datatype/src/codec/chunk/mod.rs
components/tidb_query_executors/src/fast_hash_aggr_executor.rs
components/tidb_query_executors/src/index_lookup_executor.rs
components/tidb_query_executors/src/index_scan_executor.rs
components/tidb_query_executors/src/interface.rs
components/tidb_query_executors/src/lib.rs
components/tidb_query_executors/src/limit_executor.rs
components/tidb_query_executors/src/partition_top_n_executor.rs
components/tidb_query_executors/src/projection_executor.rs
components/tidb_query_executors/src/runner.rs
components/tidb_query_executors/src/selection_executor.rs
components/tidb_query_executors/src/simple_aggr_executor.rs
components/tidb_query_executors/src/slow_hash_aggr_executor.rs
components/tidb_query_executors/src/stream_aggr_executor.rs
components/tidb_query_executors/src/table_scan_executor.rs
components/tidb_query_executors/src/top_n_executor.rs
components/tidb_query_executors/src/util/aggr_executor.rs
components/tidb_query_executors/src/util/mock_executor.rs
components/tidb_query_executors/src/util/scan_executor.rs
src/coprocessor/dag/mod.rs
src/coprocessor/endpoint.rs
tests/benches/coprocessor_executors/integrated/util.rs
tests/benches/coprocessor_executors/util/fixture.rs
tests/integrations/coprocessor/test_select.rs

Issue Number: Close #18942
```commit-message
- Add two methods `intermediate_schema` and `take_intermediate_results` to support outputting intermediate results.
- `BatchExecutorsRunner` supports to parse `IndexLookUp` and driving it for intermediate and final results.
- Add some tests
- Rename some struct name from `SecondaryRegionXXXProvider` to `ExtraRegionXXXProvider`, which are left to rename in the previous PR.
```
Tests 
Side effects
```release-note
None
```

coprocessor: support `IndexLookUp` in `BatchExecutorsRunner`

---

components/resource_control/src/lib.rs
components/resource_control/src/resource_group.rs

Issue Number: Close #18939
```commit-message
disable the buggy auto priority quota limiter
```
Tests 
Side effects
```release-note
None
```

resource_control: disable the buggy auto priority quota limiter

---

components/raftstore/src/store/fsm/peer.rs
tests/failpoints/cases/test_stale_read.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18983
Fix the bug introduced by the previous work https://github.com/tikv/tikv/pull/18805, which makes the `raftstore` thread panic on accessing the raft logs already destroyed by `region-worker` in `on_raft_log_gc_tick(...)`, responsible for destroying peer asynchronously.
```commit-message
Address the bug that the `raftstore` thread is panic on accessing raft logs of asynchronously destroyed peer in `on_raft_log_gc_tick()`.
```
Tests 
Side effects
```release-note
None.
```

raftstore: fix abnormally fetching terms when destroy peer asynchronously

---

components/tidb_query_common/src/metrics.rs
components/tidb_query_executors/src/index_lookup_executor.rs
components/tidb_query_executors/src/runner.rs

Issue Number: Close #19007
- Added two types of executors displayed in chart "Total DAG Executors", `batch_index_lookup` indicates the `BatchIndexLookUp` and `batch_index_lookup_table_scan` indicates the `BatchTableScan` built in `BatchIndexLookUp`
- Support to display the right summary (actRows and execution info) of `BatchIndexLookUp` inner `BatchTableScan`:
```commit-message
Support basic summary and metrics for push down IndexLookUp
```
Tests 
Side effects
```release-note
None
```

coprocessor: Support basic summary and metrics for push down IndexLookUp

---

src/coprocessor/endpoint.rs
tests/integrations/raftstore/test_snap.rs

Issue Number: Close #18949
```commit-message
Check the memory locks in `ExtraSnapStoreAccessor:: get_local_region_storage` to make sure the `IndexLookUp` can get the consistency rows for 1pc or async commit.
```
Tests 
Side effects
```release-note
None
```

coprocessor: check memory locks in `ExtraSnapStoreAccessor`
