tikv/tikv

src/storage/metrics.rs, src/storage/mvcc/metrics.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs
@disksing @zhangjinpeng1987 PTAL
=> storage/*: add metrics for txn

src/raftstore/store/debug.rs, src/server/service/debug.rs, tests/raftstore/test_service.rs
This PR impls Debug::raft_log.
=> debug: impl raft_log

etc/config-template.toml, src/raftstore/store/config.rs, src/raftstore/store/store.rs, tests/config/mod.rs, tests/config/test-custom.toml
check if peers need to split after initialization.
=> store: check if peers need to split after initialization

src/coprocessor/dag/expr/mod.rs
=> dag/expr: return other error instead of panic when expression is illegal

Cargo.lock, Cargo.toml
PTAL @BusyJay @zhangjinpeng1987
=> cargo: update version to 1.0.1

src/util/thread_metrics.rs, src/util/time.rs
Fix #2398 and #2397.
CC @odeits
=> util: fix misleading documentation

src/util/macros.rs
=> util/macros: update count_args doc

src/storage/txn/scheduler.rs
`batch_get_snapshot` should record `snapshot` metrics in `SCHED_STAGE_COUNTER_VEC`.
=> scheduler: fix snapshot metrics

Cargo.lock, src/coprocessor/dag/expr/compare.rs, src/coprocessor/dag/expr/fncall.rs
Support pushing  `in` function down to tikv.
PTAL @AndreMouche
=>  coprocessor, dag: implement `in` function.

src/util/macros.rs
=> util/macros: update map doc

etc/config-template.toml, src/coprocessor/endpoint.rs, src/server/config.rs, src/util/threadpool.rs, tests/config/mod.rs, tests/config/test-custom.toml
=> threadpool, coprocessor: set stack size to 10 MB

etc/config-template.toml, src/coprocessor/endpoint.rs, src/server/config.rs, src/util/threadpool.rs, tests/config/mod.rs, tests/config/test-custom.toml
=> threadpool, coprocessor: set stack size to 10 MB (#2430)

src/storage/config.rs, src/storage/mod.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/storage/assert_storage.rs, tests/storage/test_storage.rs
=> storage: limit key size.

src/coprocessor/dag/expr/compare.rs, src/coprocessor/dag/expr/mod.rs
Cherry-pick #2442 from master.
=> coprocessor: fix LIKE behaviour. (#2442)

src/server/server.rs, src/server/transport.rs
If a store is failed to resolved, it should be removed from resolving set.
=> resolve: fix potential dead lock

Cargo.lock, Cargo.toml, README.md
=> Bump to v1.0.2

src/pd/mod.rs, src/pd/util.rs, tests/pd/mock/mocker/retry.rs, tests/pd/test_rpc_client.rs
=> Cherry-pick pd: fix a dead lock (#2489)

Cargo.lock, src/coprocessor/dag/dag.rs, src/coprocessor/endpoint.rs, src/coprocessor/select/select.rs, src/server/config.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/coprocessor/test_select.rs
cherry-pick https://github.com/pingcap/tikv/pull/2476
@hicqu @BusyJay PTAL
=> coprocessor/dag: fix bug caused by check meta in chunk

src/storage/txn/scheduler.rs
PTAL @zhangjinpeng1987 @disksing
=> txn: rename ScheContext to SchedContext

src/coprocessor/endpoint.rs
Now the waiting time is not considered any more.
close #2505
=> endpoint: reduce slow log

src/storage/txn/scheduler.rs
Now the waiting time is not considered any more.
close #2505
=> scheduler: reduce slow log.

src/coprocessor/codec/mysql/decimal.rs
fix issue https://github.com/pingcap/tidb/issues/5271  @BusyJay @coocood PTAL
=> mysql/decimal: fix bug in decode

Cargo.lock, src/config.rs, src/util/rocksdb/mod.rs, tests/config/mod.rs, tests/config/test-custom.toml
This is mainly for test, so I think we don't need to add it to the template.
=> Add config to disable block cache

src/raftstore/store/worker/apply.rs
We need to ensure `post_apply` is called.
=> copr: call post_apply hook

src/raftstore/store/metrics.rs, src/raftstore/store/worker/apply.rs
=> raftstore: add metrics APPLY_TASK_WAIT_TIME_HISTOGRAM.

etc/config-template.toml, src/config.rs, tests/config/mod.rs, tests/config/test-custom.toml
fix issue https://github.com/pingcap/tikv/issues/2553#event-1372612179
=> config: set bytes_per_sync & wal_bytes_per_sync

src/coprocessor/codec/mysql/decimal.rs, src/coprocessor/endpoint.rs, src/storage/mvcc/metrics.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs
Cherry pick several commits from master and prepare to bump 1.0.4
=> Prepare 1.0.4

Cargo.lock, Cargo.toml
=> Cargo.toml: Update version from 1.0.3 to 1.0.4

src/server/errors.rs, src/server/transport.rs, src/util/worker/future.rs, src/util/worker/mod.rs
Now `Scheduler` can call `try_scheduler` if we set `pending_capacity` on it.
=> worker: add pending_capacity for Worker.

Cargo.lock, src/coprocessor/dag/expr/fncall.rs, src/coprocessor/dag/expr/time.rs
=> DateFormat -> DateFormatSig

Cargo.lock, etc/config-template.toml, src/config.rs, src/util/rocksdb/mod.rs, tests/config/mod.rs, tests/config/test-custom.toml
Cherry pick https://github.com/pingcap/tikv/pull/2599 to release 1.0.
=> [cherry-pick] add more args for column family

Cargo.lock, src/pd/client.rs, src/pd/mod.rs, tests/pd/mock/mocker/mod.rs, tests/pd/mock/mocker/service.rs, tests/pd/mock/server.rs, tests/pd/test_rpc_client.rs
Add scatter region RPC to scatter regions across the cluster.
=> Add scatter region RPC

tests/failpoints.rs
CC https://github.com/pingcap/tikv/pull/2545#issuecomment-353917300
=> tests: make failpoints tests more stable

src/coprocessor/dag/executor/table_scan.rs
=> Release 1.0/coprocessor: support key-only in table-scan

src/bin/tikv-server.rs
Cc https://github.com/pingcap/tikv/pull/2656#issuecomment-356561549
=> Enable epollsig on Linux

Cargo.toml
=> Enable Link Time Optimization

src/coprocessor/codec/mysql/decimal.rs
Fixes https://github.com/pingcap/tikv/pull/2617#discussion_r161677251
=> Fix bad lint fix.

src/raftstore/store/store.rs
we can see from the log, there's no need to schedule these task
```
root@july-VirtualBox:/usr/local/tidb-latest-linux-amd64# tail -f /tmp/kv2.log |grep "task async"
2018/01/21 09:13:48.536 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:48.857 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:48.859 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:48.860 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:48.861 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:49.647 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:49.648 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:49.959 mod.rs:147: [DEBUG] scheduling task async …
```
=> raftstore: remove schedule empty apply task

src/bin/signal_handler.rs
Cc: pingcap/rust-prometheus#131
=> bin: ignore prometheus encoding error

Makefile, src/raftstore/store/store.rs, src/util/rocksdb/event_listener.rs, src/util/rocksdb/properties.rs, tests/raftstore_cases/test_update_region_size.rs
Make sure `end_key` in `influenced_regions` are in incremental order, and enhance test to cover it.
=> fix update region size

Cargo.lock, src/pd/client.rs, src/pd/mod.rs, tests/pd/mock/mocker/mod.rs, tests/pd/mock/mocker/service.rs, tests/pd/mock/server.rs, tests/pd/test_rpc_client.rs
Get all stores from PD with gRPC interface.
=> Implement GetAllStores API

src/coprocessor/dag/executor/topn.rs, src/coprocessor/dag/executor/topn_heap.rs
Hi,
This PR will fix issue https://github.com/pingcap/tidb/issues/5773
@BusyJay @hicqu PTAL
=> executor/topn: fix bug caused by limit=0 or without limit

src/storage/mod.rs
add tag `stale_command` in ASYNC_REQUESTS_COUNTER_VEC.
=> add tag `stale_command` in ASYNC_REQUESTS_COUNTER_VEC.

src/coprocessor/codec/table.rs, src/coprocessor/dag/executor/index_scan.rs
=> codec/table: check whether range.start<range.end

src/util/logger.rs
=> util/logger: collects grpc log

tests/raftstore_cases/test_clear_stale_data.rs
This test sometime fails in CI, I'm not sure why yet. But I think it may relate
to the CF_RAFT, because CF_RAFT is writting while the test constructing the
necessary SST files. So I remove the CF_RAFT and CF_WRITE (so we don't need to
care about the SliceTransform).
=> Fix test_server_clear_stale_data

src/coprocessor/dag/executor/topn.rs, src/coprocessor/select/aggregate.rs, src/coprocessor/select/topn_heap.rs
related PR https://github.com/pingcap/tikv/pull/2694 https://github.com/pingcap/tikv/pull/2744 
@BusyJay @hicqu PTAL
=> cherry-pick:executor/aggregate: convert int to decimal in sum

src/raftstore/store/snap.rs
cherry pick cherry pick snapshot #2719 && #2723  @BusyJay @UncP PTAL
=> Release 1.0: cherry pick snapshot #2719 && #2723

src/server/metrics.rs, src/server/raft_client.rs
Add a counter to know the flush frequency. 
Will add the Grafana later. 
PTAL @ngaut @disksing
=> server: add a raft messgae flush metrics

src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/dag/executor/scanner.rs
#2714 doesn't pass mysql_test.
=> coprocessor/dag/executor: handle only one row in stream aggregation

Cargo.lock, Cargo.toml
After #2762 we can support stream aggregation, but I don't update this TiKV version.
So I update this version here.
=> *: update tikv version

docker/rust_dockerfile
These changes except for the formatter were necessary for me to build the dockerfile.
Successfully building `rust_dockerfile` was my test. I also ran `make format` and `make bench` in the container without error.
=> Rust dockerfile update

docker/rust_dockerfile
=> upgrade rust Dockerfile

src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/util.rs, src/raftstore/store/worker/apply.rs
These functions will be used in merge later.
=> raftstore: add several util functions

src/util/config.rs
In the container, a directory may be been mounted in a device which not start with `/dev`,  and do not have related directory in /sys/blocks/ or /sys/blocks/xxx.
In our tests which cover function `get_rotational_info`,  the result maybe not as expected in above environment.  
@BusyJay @disksing PTAL
=> util/config.rs: fix bug in test ssd

src/raftstore/store/peer.rs
Any new command type will make the case fail, so we won't forget to check whether it needs synchronize log.
=> peer: add test for sync log check

Cargo.lock, Cargo.toml, src/coprocessor/statistics/cmsketch.rs
=> apply hot fix for murmur3

src/server/service/kv.rs
=> Remove make_callback in kv.rs

src/coprocessor/codec/convert.rs, src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/decimal.rs, src/coprocessor/codec/table.rs, src/coprocessor/dag/dag.rs, src/coprocessor/dag/executor/aggregate.rs, src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/dag/executor/mod.rs, src/coprocessor/dag/executor/selection.rs, src/coprocessor/dag/executor/topn.rs, src/coprocessor/dag/executor/topn_heap.rs, src/coprocessor/dag/expr/arithmetic.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/builtin_control.rs, src/coprocessor/dag/expr/builtin_op.rs, src/coprocessor/dag/expr/column.rs, src/coprocessor/dag/expr/compare.rs, src/coprocessor/dag/expr/constant.rs, src/coprocessor/dag/expr/fncall.rs, src/coprocessor/dag/expr/json.rs, src/coprocessor/dag/expr/math.rs, src/coprocessor/dag/expr/mod.rs, src/coprocessor/dag/expr/time.rs
prepare for returning warnings in SelectResponse.warnings && StreamRespnse.warnings @BusyJay @hicqu @breeswish PTAL
=> dag/expr:make EvalContext mutable

Cargo.lock, src/coprocessor/dag/dag.rs, src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/dag/executor/limit.rs, src/coprocessor/dag/executor/mod.rs, src/coprocessor/dag/executor/selection.rs, src/coprocessor/dag/executor/topn.rs, src/coprocessor/dag/executor/topn_heap.rs, src/coprocessor/dag/expr/ctx.rs, src/coprocessor/dag/expr/mod.rs, tests/coprocessor/test_select.rs
@hicqu @breeswish @XuHuaiyu PTAL
=> coprocessor: set eval warnings in SelectResponse.warnings or StreamResponse.warnings

tests/failpoints_cases/test_snap.rs
This PR perverts a race condition, removes the on_resolve_fp before the snapshot messages meet the failpoint, that fails the test.
=> test: stable snapshot on resolve failure

Cargo.lock, Cargo.toml
PTAL @BusyJay @zhangjinpeng1987
=> bump 2.0-rc4

Cargo.lock, Cargo.toml, src/bin/tikv-ctl.rs, src/server/debug.rs, src/server/service/kv.rs, src/storage/txn/scheduler.rs, src/storage/types.rs
Adjust the message structure to more accurately reflect the status of mvcc.
The kvproto PR: https://github.com/pingcap/kvproto/pull/247
=> update mvcc debug structure. 

Cargo.lock, Cargo.toml, src/import/errors.rs, src/import/sst_importer.rs, src/import/sst_service.rs, src/raftstore/store/worker/apply.rs, tests/import/sst_service.rs
Process upload stream without token and locking.
=> Simplify the process of ImportSST::Upload API

src/raftstore/store/bootstrap.rs, src/raftstore/store/engine.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/region_snapshot.rs, src/raftstore/store/snap.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/consistency_check.rs, src/server/debug.rs, tests/raftstore_cases/test_split_region.rs, tests/raftstore_cases/test_tombstone.rs
`FnMut` implies mut reference already.
=> engine: remove redundant mut reference

tests/raftstore/server.rs
=> tests: run_node should retry when it meets gRPC bind fail

Cargo.lock, Cargo.toml
=> Bump to 2.0.0-rc.5

src/coprocessor/statistics/analyze.rs
This PR adds total column size in the sample collector, and calculate it when collecting data.
PTAL @lamxTyler @AndreMouche
=> cop/stats: add total column size

src/lib.rs
While I'm not able to reproduce this problem locally @overvenus had this issue as well in https://github.com/pingcap/tikv/commit/641dfd1a48cb024779e45c40a43278585c13c727#diff-b4aea3e418ccdb71239b96952d9cddb6R26.
Fixes #2947.
=> Bump recursion limit to 200

src/coprocessor/endpoint.rs
I have checked code again. It's not a bug. So I add comments and test case.
=> endpoint: add a test case comment code more clearly

Cargo.lock, Cargo.toml
After this PR, we could release 2.0.0-rc6.
=> Bump to 2.0.0-rc.6

Cargo.lock, Cargo.toml, src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/endpoint.rs, src/coprocessor/statistics/analyze.rs, src/lib.rs, src/server/config.rs, src/storage/engine/mod.rs, src/storage/engine/raftkv.rs, src/storage/engine/rocksdb.rs, src/storage/mod.rs, src/util/config.rs, src/util/futurepool.rs, src/util/worker/future.rs, src/util/worker/metrics.rs, src/util/worker/mod.rs, tests/coprocessor/test_select.rs, tests/import/kv_service.rs, tests/pd/mock/server.rs, tests/pd/test_rpc_client.rs, tests/storage_cases/test_storage.rs
Notable changes:
- Reduce lock contention in Worker
- Add metrics to the FuturePool
- Fix misused metrics in coprocessor
=> Merge master to 2.0 rc6

Cargo.lock, Cargo.toml, README.md
So that master version is always greater than release-2.0.
=> *: update development version

CHANGELOG.md, README.md
=> changelog, readme: update wording and format

Cargo.lock, Cargo.toml, src/import/engine.rs, src/import/kv_importer.rs, src/import/kv_server.rs, src/import/kv_service.rs, src/import/sst_importer.rs, src/import/sst_service.rs, src/import/test_helpers.rs, src/raftstore/store/msg.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/apply.rs, src/raftstore/store/worker/cleanup_sst.rs, src/server/server.rs, tests/import/kv_service.rs, tests/import/sst_service.rs
We will add some messages with the same name in ImportKV and
ImportSST, so we split them now.
https://github.com/pingcap/kvproto/pull/255
=> Split importpb into import_kvpb and import_sstpb

src/bin/tikv-ctl.rs
=> bin/tikv-ctl: wrap from_hex into result

Cargo.lock, Cargo.toml, src/bin/tikv-ctl.rs, src/raftstore/store/worker/compact.rs, src/server/debug.rs, src/server/service/debug.rs, src/util/rocksdb/mod.rs, tests/raftstore/cluster.rs
Add a `threads` options to help speed up compaction.
=> tikv-ctl: speed up compaction using multi-threads

src/coprocessor/error.rs, src/coprocessor/mod.rs
Extracted from https://github.com/pingcap/tikv/pull/2896
=> Move errors from coprocessor mod

src/coprocessor/checksum.rs, src/coprocessor/dag/dag.rs, src/coprocessor/endpoint.rs, src/coprocessor/mod.rs, src/coprocessor/statistics/analyze.rs
Extracted from https://github.com/pingcap/tikv/pull/2896
=> Extract RequestHandler trait

Cargo.lock, Cargo.toml, src/raftstore/store/mod.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/server/debug.rs
Latest raft fixes several bugs, let's upgrade it.
Close #3051
=> *: update raft

Cargo.lock, Cargo.toml, src/raftstore/store/mod.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/server/debug.rs
=> *: pick raft update

README.md
This PR attempts to organize the README to be a bit more friendly to people interested in exploring TiKV.
We'd like to ensure that new users and contributors can easily get started on using TiKV. There are several prerequisites to building TiKV successfully, and it would be useful for new users to know common commands (such as `make`).
=> README.md: Refactor the README.md

etc/config-template.toml, src/server/config.rs, src/server/raft_client.rs, tests/config/mod.rs, tests/config/test-custom.toml
Compression is very useful when the network has limited bandwidth.
=> *: support compression

tests/util/mod.rs
Before:  18/05/21 May:05:1526892259.946 peer.rs:1858... ()
After   : 2818/05/21 16:45:51.855 snap.rs:747...
=> fix test log time format and tag prefix.

src/coprocessor/codec/mysql/decimal.rs
fix a bug in do_div_mod when divisor/dividend is 0 with fractional part
=> mysql/decimal: fix a bug in do_div_mod when divisor/dividend is 0 

src/raftstore/store/peer.rs, src/raftstore/store/store.rs, tests/raftstore/pd.rs, tests/raftstore_cases/test_conf_change.rs
cherry pick a bug fix from #3112 .
=> cherry pick #3112

CHANGELOG.md
Add missing changelog for 2.0.2 and for the future release 2.0.3.
=> CHANGELOG: changes for 2.0.2 and 2.0.3

Cargo.lock, Cargo.toml, src/coprocessor/dag/dag.rs, src/coprocessor/dag/expr/arithmetic.rs, src/coprocessor/dag/expr/ctx.rs, src/coprocessor/dag/expr/err.rs, src/coprocessor/dag/expr/fncall.rs, src/coprocessor/dag/expr/mod.rs
@hicqu @breeswish @XuHuaiyu PTAL
=> dag/expr: implement flag DividedByZeroAsWarning

src/coprocessor/codec/mysql/decimal.rs
Hi, 
This PR cherry picks the bug fixed in https://github.com/pingcap/tikv/pull/3145.
@BusyJay @coocood PTAL
=> cherry-pick: decimal: fix bug in do_sub (#3145)

src/storage/engine/mod.rs, src/storage/mvcc/reader.rs, src/storage/types.rs
Cherry-pick https://github.com/pingcap/tikv/pull/3124
=> [release 2.0] cherry-pick: Fix potential back and forward iterating for reverse seek (#3124)

src/coprocessor/dag/expr/arithmetic.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/ctx.rs, src/coprocessor/dag/expr/err.rs
This PR adjusts the error and code for expression.
@hicqu @XuHuaiyu PTAL
=> dag/expr: adjust error and code for expression

Cargo.lock, Cargo.toml, src/bin/tikv-server.rs, src/bin/util/setup.rs, src/config.rs, src/import/import_mode.rs, src/import/mod.rs, src/import/sst_service.rs, src/raftstore/store/store.rs, src/util/rocksdb/mod.rs, tests/raftstore/server.rs
- Switch: switch to normal/import mode
- Compact: compact the specific range for better performance
The import mode argument is removed because we can switch to import mode dynamically now.
=> import: implement Switch and Compact APIs and remove the import mode

Cargo.lock, Cargo.toml, src/import/engine.rs, src/import/sst_service.rs
Switch is a reserved word in Java, we can't use it.
- Bug fix
Just rename things.
No.
No.
=>  import: rename Switch to Enter

src/util/mod.rs
When using the unescape function, strings within the format '\xFF' or
'\xff' will be converted a single byte.
resolves #3149
=> util/unescape: Escape \xFF sequences to a byte.

tests/raftstore_cases/test_conf_change.rs
- improve a test case.
bugfix.
make dev
no
no
=> Fix test_learner_with_slow_snapshot test case

Cargo.lock, Cargo.toml, src/bin/setup.rs, src/bin/tikv-ctl.rs, src/bin/tikv-server.rs, src/config.rs, src/import/engine.rs, src/import/import_mode.rs, src/import/kv_importer.rs, src/import/kv_server.rs, src/import/kv_service.rs, src/import/mod.rs, src/import/sst_importer.rs, src/import/sst_service.rs, src/import/test_helpers.rs, src/raftstore/store/msg.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/apply.rs, src/raftstore/store/worker/cleanup_sst.rs, src/server/debug.rs, src/server/server.rs, src/server/service/debug.rs, src/util/rocksdb/mod.rs, tests/failpoints_cases/test_snap.rs, tests/import/kv_service.rs, tests/import/sst_service.rs, tests/raftstore/cluster.rs, tests/raftstore/server.rs, tests/raftstore_cases/test_conf_change.rs, tests/raftstore_cases/test_split_region.rs
Cherry pick some commits to release-2.0.
- Cherry pick
https://github.com/pingcap/kvproto/pull/276
=> *: cherry pick some commits to release-2.0

CHANGELOG.md, Cargo.lock, Cargo.toml, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs
* Cherry-pick #3187 
* Add change log for v2.0.4
* Update versions in Cargo.toml and Cargo.lock
No.
No.
It should be merged after https://github.com/pingcap/tikv/pull/3211
=> Release 2.0.4

src/raftstore/store/metrics.rs, src/raftstore/store/snap.rs, src/util/mod.rs, src/util/rocksdb/engine_metrics.rs
add metric for ingest sst
add metric for number of files at each level at each cf
Improvement
Just add metric
No
Yes, I will add it later
=> *: add some metrics for rocksdb

src/raftstore/store/metrics.rs
Change a metric for snapshot size.
make dev.
No
No
=> change max buckets of snapshot size from 2G to 1T.

Cargo.lock, Cargo.toml, src/raftstore/store/metrics.rs, src/server/metrics.rs
Upgrade `prometheus-static-metric`, which is the foundation of the subsequent static metric PRs.
Trivial.
No need.
No.
No.
No performance change.
=> Upgrade prometheus-static-metric

src/coprocessor/dag/expr/builtin_arithmetic.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/builtin_compare.rs, src/coprocessor/dag/expr/builtin_control.rs, src/coprocessor/dag/expr/builtin_json.rs, src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/builtin_op.rs, src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/mod.rs, src/coprocessor/dag/expr/scalar_function.rs
This PR does some rename to make the expression module  in correspondence with tidb
unit test
no
no
=> expr/*: do some rename to make it in correspondence with tidb

images/tikv.svg
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Separately describe each logical change and avoid lazy messages (optional)
- Breaking change (fix or feature that would cause existing …
=> Upload TiKV logo image

src/storage/gc_worker.rs, src/storage/mod.rs, src/storage/txn/mod.rs, src/storage/txn/scheduler.rs, tests/storage_cases/test_storage.rs
Commit a95dc9a (Pull request #3119 ) moved GC logic out but didn't remove old code in scheduler. This PR removed them.
Old tests are enough. There are no new code to be tested.
No
No
#3119
=> scheduler: Remove dead code of GC from scheduler

benches/channel/bench_channel.rs, src/util/mpsc.rs
Using bounded channel will create the buffer immediately, which is a waste when there are a lot of channels. So this pr introduces a channel that never pre-allocates but still has boundary check. Although the boundary is checked loosely to get a better performance, which is OK when the boundary is not a hard limit.
```
test channel::bench_channel::bench_crossbeam_channel                 ... bench:          24 ns/iter (+/- 0)
test channel::bench_channel::bench_mio_channel                       ... bench:          89 ns/iter (+/- 4)
test channel::bench_channel::bench_thread_channel                    ... bench:          46 ns/iter (+/- 1)
test channel::bench_channel::bench_util_channel                      ... bench:          24 ns/iter (+/- 0)
test channel::bench_channel::bench_util_loose …
```
=> util: introduce loose channel

README.md, docs/ROADMAP.md, docs/adopters.md
I have added the TiKV adopters and copied the TiKV roadmap to this repo so that TiKV can have its own roadmap
Improvement
N/A
No.
No.
https://github.com/pingcap/docs/pull/525 
No.
N/A
=> docs: add TiKV adopters and Roadmap

docs/adopters.md
Change the project name from TiDB to TiKV in the adopter list.
Improvement
N/A.
N/A.
N/A.
=> docs: change the project name

docs/adopters.md
Fix some links for the adopters' website
Improvement 
N/A
N/A
N/A
=> docs: fix some adopter links

docs/ROADMAP.md
Fix a typo.
Improvement
Integration tests.
N/A
N/A
=> docs: fix a typo

etc/config-template.toml, src/storage/config.rs
Cherry pick https://github.com/pingcap/tikv/pull/3283
CI
No
No
https://github.com/pingcap/tikv/pull/3283
=> [cherry-pick] enlarge scheduler's default total slots

tests/failpoints_cases/test_storage.rs
Previously, in `test_storage_1gc` the fail point will block RaftStore thread, and this will cause leader change to another node.
CI
No
No
=> [release-2.0] fix test_storage_1gc

src/storage/mvcc/reader.rs, src/storage/mvcc/txn.rs
cherry pick https://github.com/pingcap/tikv/pull/3290
CI/Unit Test/TLA+
No
No
https://github.com/pingcap/tikv/pull/3290
=> [release-2.0] cherry-pick collapse continuous rollbacks

src/raftstore/store/worker/compact.rs
beautify task log
Improvement (non-breaking change which is an improvement to an existing feature)
manual test
No
No
before: 
mod.rs:97: handle task CheckAndCompact { cf_names: ["default", "write"], ranges: [[122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 7, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 11, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 15, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 19, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 23, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 27, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 31, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 35, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, …
=> raftstore: beautify task log

src/util/metrics/threads_linux.rs
=> util/metrics: add threads IO metrics

Cargo.lock, Cargo.toml, src/coprocessor/codec/mysql/decimal.rs, src/lib.rs
Cherry picks #3240 to release 2.0.
=> mysql/decimal: fix bug in from_bytes (#3240)

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
* add `crc32` function in `builtin_math.rs`
pass `make expression`
No
No
=> expression: add builtin crc32

src/coprocessor/codec/chunk/chunk.rs, src/coprocessor/codec/chunk/column.rs
1. Add missing docs for coprocessor chunk. 
2. Add inline for some short functions.
No need test
No
No
/cc @AndreMouche @breeswish 
PTAL @queenypingcap
=> coprocessor/chunk: add comments and inline for chunk

CONTRIBUTING.md
Now TiKV enables DCO check, so we need to update the contribution doc for it.
- Contribution
No 
No
No
PTAL @caniszczyk @ceohockey60 @queenypingcap 
BTW, do we need to add a git hook to do it automatically? 
E.g. adding following to the githook commit-msg
```
#!/bin/sh
NAME=$(git config user.name)
EMAIL=$(git config user.email)
if [ -z "$NAME" ]; then
echo "empty git config user.name"
exit 1
fi
if [ -z "$EMAIL" ]; then
echo "empty git config user.email"
exit 1
fi
git interpret-trailers --if-exists doNothing --trailer \
"Signed-off-by: $NAME <$EMAIL>" \
--in-place "$1"
```
=> CONTRIBUTION: update signed-off-by

README.md
Fix typo for README.md
Typo
No.
No.
=> Fix missing paren in README.md

Cargo.lock, Cargo.toml, src/coprocessor/codec/error.rs, src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs, src/lib.rs
expr/builtin_fncall: implement string.UnHex
unit test
no
no
#3275
=> expr/builtin_fncall: implement UnHex

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin function: Pow in coprocessor.
This is for #3275
fix DCO from PR https://github.com/tikv/tikv/pull/3411
Improvement
unittest
no
no
#3275
=> coprocessor/dag/expr: add some un-pushed builtin UDF(Pow) #3411

README.md
=> README: Fix CI badge status

src/raftstore/coprocessor/split_check/keys.rs
Write one key and then flush can lead to too many files, which
is a waste and cause errors for too many fds on some systems.
=> tests/split_observer: fix defective kv flush

CHANGELOG.md, Cargo.lock, Cargo.toml
Add changelog and revise version strings
None
None
None
None
None
None
=> release v2.1.0-rc1

src/pd/client.rs
There are some code in get_region and get_region_info can share a common implementation instead. 
Improvement
Manually against PD server
No
No
=> Change get_region and get_region_info to use a common implementation

CHANGELOG.md
Fix the wrong format in the changelog
No
No
No
=> fix wrong changelog format

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
This PR implements the scalar function Sign
Improvement
unit test
No
No
#3275
=> coprocessor/dag/expr: add un-pushed builtin UDFs(Sign)

etc/config-template.toml
Add keepalive related configurations to config-template.toml. So users can tweak it without looking into codes.
Manual tests.
No.
Yes. /cc @LinuxGit
=> config-template: add keepalive configurations

src/raftstore/store/peer.rs, src/raftstore/store/store.rs, tests/failpoints_cases/mod.rs, tests/failpoints_cases/test_stale_peer.rs
Fix false stale peer alert.
No.
No.
#3384
=> raftstore: fix false stale peer alert

docs/tikv-control.md
Add a document: TiKV Control User Guide
From docs: https://github.com/pingcap/docs/blob/master/tools/tikv-control.md
No.
=> docs: add TiKV Control User Guide

docs/rocksdb-option-configuration.md
Signed-off-by: CaitinChen <chenchun@pingcap.com>
Add RocksDB option config doc
Relevant
=> docs: Add RocksDB option config doc

docs/tikv-coprocessor-config.md
Signed-off-by: CaitinChen <chenchun@pingcap.com>
Add TiKV Coprocessor config doc
Relevant
=> docs: add TiKV Coprocessor config doc

docs/secure-tikv-cluster.md, src/bin/tikv-ctl.rs
Signed-off-by: CaitinChen <chenchun@pingcap.com>
Add the securing TiKV cluster doc
Relevant
=> docs: add securing TiKV cluster doc

Cargo.lock, Cargo.toml, src/coprocessor/dag/expr/builtin_encryption.rs, src/coprocessor/dag/expr/mod.rs, src/coprocessor/dag/expr/scalar_function.rs, src/lib.rs
- implements the scalar function md5
unit test
No
No
#3275
=> coprocessor/dag/expr: add un-pushed builtin UDFs(md5)

src/coprocessor/codec/mysql/time/mod.rs, src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin function:  LastDay  in coprocessor.
https://github.com/tikv/tikv/issues/3275
unittest
=> coprocessor/dag/expr: add lastDay

docs/tikv-storage-config.md, docs/tikv-storage-configuration.md
Signed-off-by: CaitinChen <chenchun@pingcap.com>
Add TiKV storage config doc
Relevant
=> docs: Add TiKV storage config

src/storage/gc_worker.rs
reduce key clone in gc_worker
No need
No
No
=> gc_worker: reduce key clone in gc

docs/label-config.md
Add 1 doc: Label Configuration
Relevant.
No.
=> docs: add label config file

src/raftstore/store/store.rs, tests/raftstore/pd.rs, tests/raftstore/util.rs, tests/raftstore_cases/test_merge.rs, tests/raftstore_cases/test_split_region.rs
cherry-pick #3497 
unit test
No
No
=> [release-2.0] raftstore: update approximate size and keys after merge (#3497)

src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin function: month in coprocessor.
new feature
unittest
no
no
#3275
=> expr: add MONTH function

src/util/threadpool.rs
Add scheduler for thread pools, so we can spawn a task to thread pools from any threads we want.
Unit tests.
No.
No.
=> util/threadpool: add thread pool scheduler

src/storage/txn/mod.rs, src/storage/txn/process.rs, src/storage/txn/scheduler.rs
This PR split a new module process from scheduler. It moves functions and methods that can be called in workers.
Unit tests.
No.
No.
=> txn: split out process module

docs/op-guide/ansible-deployment-scale.md, docs/op-guide/horizontal-scale.md
Add two files about scaling the TiKV cluster.
Relevant
No.
- https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment-scale.md
- https://github.com/pingcap/docs/blob/master/op-guide/horizontal-scale.md
=> docs/op-guide: add two scaling files

src/storage/metrics.rs, src/storage/txn/scheduler.rs
Scheduler takes snapshot via the `async_snapshot` API. 
Unit tests.
No.
No.
#2111
=> scheduler: use async snapshot

src/coprocessor/dag/dag.rs, src/coprocessor/endpoint.rs, src/coprocessor/mod.rs, src/coprocessor/tracker.rs
Based on https://github.com/tikv/tikv/pull/3599, extracted from [Coprocessor Read Pool PR](https://github.com/tikv/tikv/pull/3515)
Simple file move. This is code re-arrangement.
=> Rearrange coprocessor tracker to a standalone file

docs/op-guide/recommendation.md
Add the "Software and Hardware Requirements" file for TiKV.
Relevant.
No.
https://github.com/pingcap/docs/blob/master/op-guide/recommendation.md
=> docs/op-guide: add software and hardware requirements

docs/tools/pd-recover.md
Add "PD Recover User Guide" to docs/tools. 
https://github.com/pingcap/docs/blob/master/tools/pd-recover.md
=> docs/tools: add PD Recover user guide

src/raftstore/store/peer.rs
Fixed a typo
Non-code
No need
No
NO
=> *: Fix a typo in comment

src/coprocessor/dag/expr/builtin_encryption.rs, src/coprocessor/dag/expr/scalar_function.rs
- implements the scalar function sha2
pass make expression
no
no
#3275
=> coprocessor/dag/expr: add builtin function sha2

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin function: radians
- Improvement 
unit test
No
No
#3275
=> expression: add builtin radians

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin math function : conv
Improvement
unit test
No
No
#3275
=> expression: add builtin conv

Cargo.lock, Cargo.toml, components/test_raftstore/Cargo.toml, src/import/kv_service.rs, src/import/sst_service.rs, src/server/raft_client.rs, src/server/service/debug.rs, src/server/service/kv.rs, src/server/snap.rs, tests/pd/mock/server.rs
=> *: upgrade grpcio to v0.4 (#3650)

src/raftstore/store/fsm/store.rs, src/raftstore/store/metrics.rs, src/raftstore/store/msg.rs
Signed-off-by: Tong Zhigao <tongzhigao@pingcap.com>
- cherry pick from [tikv#3657](https://github.com/tikv/tikv/pull/3657)
=> Add tikv_raftstore_event_duration to metrics (#3657)

src/raftstore/store/fsm/store.rs, src/raftstore/store/snap.rs, src/raftstore/store/worker/mod.rs, src/raftstore/store/worker/region.rs, src/util/rocksdb/engine_metrics.rs, src/util/rocksdb/mod.rs
cherry pick https://github.com/tikv/tikv/pull/3606
=> raftstore: check level 0 files before ingest (#3606)

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
implement Trim1Arg, Trim2Args, Trim3Args
Improvement
unit test
No
No
#3275
=> expression: add builtin trim

docs/op-guide/deploy-tikv-using-binary.md
Fix two broken links.
https://github.com/pingcap/docs/pull/687
=> docs/op-guide: fix two broken links

src/coprocessor/codec/mysql/time/mod.rs, src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin function - month_name
- Improvement 
unit test
no
no
[#3275](https://github.com/tikv/tikv/issues/3275)
=> expression:  add builtin_time - month_name

src/coprocessor/endpoint.rs
Log coprocessor errors. 
No
No
No
=> endpoint: log errors (#3731)

CHANGELOG.md, Cargo.lock, Cargo.toml
Pump version to 2.1.0-rc.5 and add changelog.
make dev
no
no
=> Release v2.1.0-rc.5

Cargo.lock
Signed-off-by: DorianZheng <xingzhengde72@gmail.com>
Just Upgrade rocksdb version
- Bug fix
test case
No
No
=> Fix `CompactFiles` bug

Cargo.lock
Signed-off-by: DorianZheng <xingzhengde72@gmail.com>
Just Upgrade rocksdb version
- Bug fix
test case
No
No
=> [release-2.1] Fix `CompactFiles` bug

src/raftstore/store/worker/apply.rs
Omit some logs about `comact raft log`. There are too many such logs, and it's not very useful for debug.
Improvement.
make dev.
No.
No.
=> omit some logs about compact-log.

src/coprocessor/codec/mysql/time/mod.rs, src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin_time - day_name, day_of_month, day_of_week, day_of_year
- Improvement 
unit test
no
no
[#3725](https://github.com/tikv/tikv/issues/3275)
=> Copr: Add day_name, day_of_month, day_of_week, day_of_year

CHANGELOG.md, Cargo.lock, Cargo.toml
Pump version and add change log.
No code changes.
No
No
=> release v2.0.9

docs/tools/tikv-control.md, src/bin/tikv-ctl.rs, src/raftstore/store/snap.rs, src/raftstore/store/util.rs, src/raftstore/store/worker/raftlog_gc.rs, src/util/rocksdb/engine_metrics.rs, src/util/rocksdb/event_listener.rs
The picked commits are listed in the commits in this PR.
=> Cherry pick some commits to release-2.1

src/raftstore/store/fsm/peer.rs, src/raftstore/store/worker/apply.rs
Fix type error
Improvement
None
No
No
=> fix apply typo error

src/coprocessor/codec/mysql/time/mod.rs, src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
This PR add the builtin funtion week_with_mode to Tikv, which is in the list of https://github.com/tikv/tikv/issues/3275, following the document of https://pingcap.com/blog-cn/30mins-become-contributor-of-tikv/.
By unit tests.
No
No
https://github.com/tikv/tikv/issues/3275
=> add coprocessor function week_with_mode

src/bin/tikv-ctl.rs, src/server/debug.rs
This PR cherry-picks #3840 to release-2.1 branch
Later, another PR that will be submitted by @hicqu will also be picked in this PR.
* By manual tests
No
No
=> release-2.1: cherry-pick fixes of help messages of tikv-ctl

src/coprocessor/codec/mysql/time/mod.rs
Cherry pick https://github.com/tikv/tikv/pull/3786
=> Cherry pick: Support ambiguous time

src/util/logger.rs
Collects logs of components.
CI
No.
No.
Close #3858
=> util/logger: collects logs of components

CHANGELOG.md, Cargo.lock, Cargo.toml
Add changelog to prepare releasing v2.1.0
No
No
No
=> Release v2.1.0

src/raftstore/store/fsm/peer.rs
=> raftstore: fix redundant heartbeat (#3864)

components/test_util/src/lib.rs, components/test_util/src/macros.rs, tests/integrations/import/kv_service.rs, tests/integrations/mod.rs
Add a macro `with_retries` to retry some RPCs in case of temporary failures.
Improvement (non-breaking change which is an improvement to an existing feature)
Unit test
No
No
Close https://github.com/tikv/tikv/issues/3830
=> tests: try to make test_kv_service more stable

Cargo.lock, Cargo.toml, components/test_raftstore/Cargo.toml
Updates Raft to 0.4.0.
Closes #3836, #3632.
Improvement
CI
No
No
Closes #3836, #3632.
=> Update Raft to 0.4.0

Cargo.lock, src/coprocessor/dag/dag.rs, src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs, tests/integrations/coprocessor/test_select.rs
https://github.com/pingcap/tipb/commit/a7fd2aaa9719b64c2de3f6c6cd7cb235cb701b56
Upgrade tipb
pass `make dev`
No
No
=> Upgrade tipb to a7fd2aa

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin strcmp function
Improvement
unit test
No
No
#3275
=> implement builtin strcmp function

src/storage/mvcc/txn.rs
make `prewrite` more straightforward and effective.
the original code:
conditions | comparison times | key clone times
---|---| ---
value is none | 2 | 1 
value is some && is short | 2 | 0 
value is some && is long | 3 | 1 
new code:
conditions | comparison times | key clone time s
---|---| --- 
value is none | 1 | 0 
value is some && is short | 2 | 0 
value is some && is long | 2 | 1 
unit test
No
No
=> storage/mvcc/txn: polish prewrite

components/test_raftstore/util.rs, src/raftstore/store/config.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/raftstore_cases/test_conf_change.rs
=> raftstore: reject transfer leader to the recently added peers (#3878)

src/coprocessor/endpoint.rs
This println is introduced by mistake in https://github.com/tikv/tikv/pull/3821
=> Fix unnecessary print in tests

src/raftstore/store/worker/compact.rs
Escape compact range key when logging.
Improvement
No
No
No
=> escape compact range key

src/server/load_statistics/mod.rs
fix build on macOS ( cannot find type `Arc` and `Instant`)
Bug fix
manual
No
No
#3741
=> fix build on macOS

CHANGELOG.md, Cargo.lock, Cargo.toml
Add changelog and update tikv version.
No code changes.
No.
No.
=> add changelog and update version

components/test_coprocessor/src/store.rs, src/import/test_helpers.rs, src/util/rocksdb/event_listener.rs
There is already a mod named `util::collections` that contains faster `HashMap` and `HashSet`, but in some place, we still use `std::collections::HashMap`. This PR checks the whole project, and update it.
pass `cargo check`
No
No
=> *: use util::collections::HashMap/HashSet

src/util/config.rs, tests/config/test-custom.toml
Cherry pick #3687 and adjust a little to make it backward compatible
manual test
No
No
=> Supports day format in ReadableDuration (#3687)

src/raftstore/coprocessor/mod.rs, src/raftstore/coprocessor/split_check/half.rs, src/raftstore/coprocessor/split_check/mod.rs, src/raftstore/coprocessor/split_check/size.rs, src/raftstore/store/util.rs, src/raftstore/store/worker/split_check.rs
=> raftstore/coprocessor: use scan way when approximate way fail

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin string function: Lpad and LpadBinary
Improvement 
Unit Test
No
No
#3275
=> implement builtin lpad & lpad_binary

src/raftstore/store/peer.rs
`propose_snapshot` is no longer needed since #2639 .
No.
No.
No.
=> peer: remove unused `propose_snapshot`

src/pd/client.rs, src/pd/mod.rs, src/pd/pd.rs, src/pd/util.rs
Improve comment for src/pd
No need
No
No
=> pd: add comments

src/import/common.rs, src/import/engine.rs, src/import/import.rs, src/import/kv_importer.rs, src/import/kv_service.rs, src/import/prepare.rs, src/util/file_log.rs
Add annotation for importer
Improvement
No need
No
No
=> importer: add annotation

src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/dag/executor/limit.rs, src/coprocessor/dag/executor/mod.rs, src/coprocessor/dag/executor/selection.rs, src/coprocessor/dag/executor/table_scan.rs, src/coprocessor/dag/executor/topn.rs, src/coprocessor/dag/mod.rs, src/coprocessor/endpoint.rs, src/coprocessor/mod.rs, src/coprocessor/util.rs
This PR mainly adds comments for important modules or structures during Coprocessor calculation.
- Some components that will be rewritten in the near future are not covered.
- Some trivial components are not covered yet. It will be covered in future PRs.
=> Improve coprocessor comments

src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
Regarding  #3275 push down builtin method DateDiff
Improvement
unit test
No
Yes, to make push down works
#3275
=> coprocessor/dag/expr push down builtin method DateDiff

src/util/rocksdb/properties.rs
=> util: remove unused mut

Makefile, src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/duration.rs, src/coprocessor/codec/mysql/time/mod.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/builtin_compare.rs, src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/column.rs, src/coprocessor/dag/expr/constant.rs, src/coprocessor/endpoint.rs
Duration is a simple structure, so let's derive Copy for it for better efficiency.
Extracted from [batch execution PR](https://github.com/tikv/tikv/pull/3898)
Existing unit tests.
No.
No.
https://github.com/tikv/tikv/pull/3898
=> Derive Copy for Duration

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
Implemented `FIELD()` function in MySQL, which correspond to the three functions `FieldInt`, `FieldReal`, `FieldString`.
New feature.
Unit tests as in the source code.
Yes. Please mark this function as resolved in #3275 
No.
=> coprocessor: implemented FIELD() function

src/util/logger/mod.rs
PR https://github.com/tikv/tikv/pull/4008 switched from log to slog. However previously we have removed slog level filter. Consequently, our slog output is not filtered.
This PR fixed it.
Manually.
=> Fix useless log level

src/server/service/kv.rs
Refactor futures in service/kv.rs to make the code more easily to reuse.
Improvement.
Unit tests and integration tests.
It's extracted from #4043 . So please review this first if you want to help me review that.
=> server: refactor futures in service/kv.rs.

src/server/metrics.rs, src/server/raft_client.rs
Add a new metrics for count of delayed raft messages.
Improvement.
unit tests.
=> server: add a new metrics for delayed raft messages.

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
Signed-off-by: gaodayue <gaodayue@meituan.com>
implment builtin string function: Locate2Args & Locate3Args & LocateBinary2Args & LocateBinary3Args
Improvement
unit test
No
No
#3275
=> Implement Locate2Args & Locate3Args & LocateBinary2Args & LocateBinary3Args

src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
Implement add_time_duration_null;
Fix month_name; 
Add more type annotation.
unit-test
no
no
#3275
=> Implement add_time_duration_null; Fix month_name; Add more type annotation

docs/adopters.md
Updated TiKV adopter list to be consistent with TiDB
- Improvement
=> docs: update TiKV adopters to the latest

docs/clients/go-client-api.md
Updated the Go client usage based on [this PR](https://github.com/pingcap/docs/pull/827).
No.
[Related PR](https://github.com/pingcap/docs/pull/827).
=> docs/clients: update go-client usage

CHANGELOG.md, Cargo.lock, Cargo.toml
Bump to 3.0.0-beta, since we has finished major features.
=> Bump to 3.0.0-beta

docs/op-guide/deploy-tikv-using-docker-compose.md
Signed-off-by: JaySon-Huang <jayson.hjs@gmail.com>
Fix some mistake in [Deploy TiKV Using Docker Compose](https://github.com/tikv/tikv/blob/master/docs/op-guide/deploy-tikv-using-docker-compose.md) 
=> op-guide: fix typo in docker-compose

etc/config-template.toml
Add `store-pool-size` configuration to `etc/config-template.toml`.
No
No
No
=> add store pool size configuration to config template file

components/test_util/src/lib.rs
=> test: fix error when Linux kernel doesn't contain epollex engine

docs/clients/go-client-api.md
- Update the Raw Key-Value client method call for TiKV docs
- Improvement
- [tikv: fix rawkv doc #870](https://github.com/pingcap/docs/pull/870)
=> Update Raw KV API Doc

benches/benches.rs, benches/util/mod.rs, benches/util/slice_compare.rs, src/storage/engine/mod.rs, src/storage/engine/raftkv.rs, src/storage/txn/mod.rs, src/storage/txn/store.rs
Cherry-pick https://github.com/tikv/tikv/pull/4013
=> [2.1 cherry-pick] verify scan request range

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to 2.1.3

Cargo.lock, src/util/rocksdb/event_listener.rs
Check status of CompactionJobInfo at first.
- Bug fix 
CI
No
No
=> [cherry-pick-2.0] Fix event listener issue

src/util/config.rs, src/util/macros.rs, src/util/metrics/mod.rs, src/util/mod.rs, src/util/rocksdb_util/engine_metrics.rs, src/util/rocksdb_util/event_listener.rs, src/util/rocksdb_util/metrics_flusher.rs, src/util/rocksdb_util/mod.rs, src/util/time.rs, src/util/transport.rs, src/util/worker/future.rs, src/util/worker/mod.rs
Refactor all logs in util module.
Improvement, for code style.
CI.
NO.
No.
=> util: refactor logs.

src/import/import_mode.rs
Please refer to the original PR for more information: https://github.com/tikv/tikv/pull/4086
=> import: enable auto compactions in import mode (#4086)

Cargo.lock, src/raftstore/store/metrics.rs, src/raftstore/store/snap.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/mod.rs, src/raftstore/store/worker/region.rs, src/util/rocksdb/engine_metrics.rs, src/util/rocksdb/mod.rs
Cherry pick the optimization to release-2.0, check the original commit for more information.
=> raftstore: check level 0 files before ingest

src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
Signed-off-by: caohe <caohe9603@gmail.com>
- Implement builtin function: SubDurationAndDuration in coprocessor.
- Unit test
- No
- No
- #3275
=> coprocessor/dag/expr: implement SubDurationAndDuration

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to 2.1.4

src/coprocessor/codec/batch/mod.rs, src/coprocessor/codec/batch/rows.rs, src/coprocessor/codec/batch/vector.rs
This PR only renames BatchColumn to VectorValue.
Extracted from https://github.com/tikv/tikv/pull/3898
- Engineering
CI
=> Rename BatchColumn to VectorValue

.github/pull_request_template.md
This PR improves the PR category in the PR template, by referring to the categories in the [VSCode ChangeLog](https://code.visualstudio.com/updates/v1_31)
- Removed "Breaking change", which overlaps "New feature", "Improvement" or "Bug fix".
- Introduce "Engineering" and "Misc" for uncovered cases. Examples:
- Code refinement is Engineering, because it does not improve existing feature.
- Adding documentation is Misc.
=> Improve PR category

docs/op-guide/recommendation.md
=> Fix a typo

Cargo.lock, Cargo.toml, src/coprocessor/endpoint.rs, src/coprocessor/mod.rs, src/lib.rs
This PR cherry picks #3821 to release-2.1 branch.
Fix https://github.com/tikv/tikv/issues/4247
=> Cherry pick: Make test_handle_time more stable (#3821)

etc/config-template.toml, src/config.rs
This is a cherry pick, please refer to the original PR #4140 for more information.
=> config: enlarge max-manifest-file-size to 128MB (#4140)

CODE_COMMENT_STYLE.md
- Re-open this PR for approved merge of Code Comment Style in https://github.com/tikv/tikv/pull/4204 
- Improvement
=> tikv: re-add comment style guide for merge

src/raftstore/store/fsm/metrics.rs, src/raftstore/store/fsm/store.rs
Use SeqCst to make things simple in places where called not frequently
Unit tests
No
No
=> use SeqCst to make things simple in places where called not frequently

docs/tools/pd-control.md
"Enviroment" to "Environment" in line 51.
=> Fix typo in pd-control.md

src/server/service/debug.rs, src/server/service/kv.rs
This PR updates log format of the `server/service` directory of the source code.
By CI
No
No
=> server/service: Update log format

src/raftstore/store/fsm/peer.rs, src/util/config.rs
Use the new log format for file fsm/peer.rs.
- Improvement
unit tests
No.
No.
=> raftstore/fsm/peer: use new log format

src/util/metrics/threads_linux.rs
This PR adds new metrics to measure context switches of each thread.
Create a cluster by ansible and check Grafana panels.
No
Yes. I have opened a [PR](https://github.com/pingcap/tidb-ansible/pull/687) to tidb-ansible(add two panels to Grafana).
<https://github.com/tikv/tikv/issues/4273>
=> util/metrics: add thread context switch metrics

src/raftstore/store/util.rs
We need to report store id in v2.1.x too.
- Improvement
No.
No.
#3885
=> raftstore: log not matched store

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to 2.1.5

CONTRIBUTING.md
Add some description of handling CI test.
No.
No.
No.
=> *: update contributing guide

src/raftstore/store/fsm/apply.rs
Refactor logs in fsm/apply.rs.
Misc.
=> raftstore: refactor logs in fsm/apply.rs

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to 2.1.6

src/storage/metrics.rs, src/storage/mod.rs
Signed-off-by: fredchenbj <cfworking@163.com>
Change the global metics to static metrics in raw read.
Manual tests.
No.
no.
=> storage: use static metrics for raw read

docs/adopters.md
- Updated the adopters list
- Improvement
=> adopters: update the adopter list to latest

Cargo.lock
In release mode, compilation time is reduced by one or two minutes. It's
not significant in debug mode though.
- Improvement
unit tests
No.
No.
=> kvproto: update to use lite-runtime

MAINTAINERS.md
=> fix email in maintainers.md

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to 3.0.0-beta.1

src/coprocessor/dag/batch_executor/index_scan_executor.rs, src/coprocessor/dag/batch_executor/mod.rs, src/coprocessor/dag/batch_executor/table_scan_executor.rs, src/coprocessor/dag/builder.rs
This PR adds batch index scan executor.
=> Add batch index scan executor

src/storage/engine/mod.rs
=> engine: fix flow statistics

docs/adopters.md
-  Removed eleme user case because eleme has been acquired by Alibaba
- update
=> docs/adopter: remove eleme user case

src/bin/tikv-ctl.rs, src/bin/tikv-importer.rs, src/bin/tikv-server.rs, src/bin/util/setup.rs
Fatal level is more clear than error when program is about to exit.
manual tests
No.
No.
=> bin: use fatal level when fatal

src/raftstore/store/worker/region.rs
Cherry-pick of #4464 
No
No
No
=> enlarge ingest stall buffer (#4464)

Cargo.lock, Cargo.toml
This PR uprgades Criterion to latest version 0.2.11, prepare for contributors to do https://github.com/tikv/tikv/issues/4508
Simply modifying `Cargo.toml` won't work, so comes this PR.
=> Upgrade to use a later Criterion

CHANGELOG.md, Cargo.lock, Cargo.toml
=> *: Bump to 2.1.8

src/coprocessor/dag/builder.rs, src/coprocessor/dag/handler.rs, src/coprocessor/dag/mod.rs, src/coprocessor/endpoint.rs
Move build related functions to DAGBuilder
Move build related functions to DAGBuilder
Yes
No
No
=> coprocessor: move build related function to DAGBuilder

components/engine/src/rocks/util/engine_metrics.rs, components/engine/src/rocks/util/mod.rs
Export RocksDB number of immutable memtables, this will be used to investigate the reason of write stall.
No
No
No
=> Metrics: rocksdb.num-immutable-mem-table

README.md
-  removed a duplicated paragraph
- Fix
=> readme: remove repeated content

components/engine/src/lib.rs, components/engine/src/rocks/util/event_listener.rs, components/engine/src/rocks/util/stats.rs, components/engine/src/util.rs, src/coprocessor/dag/batch/executors/limit.rs, src/coprocessor/dag/batch/executors/util/mod.rs, src/coprocessor/dag/batch/mod.rs, src/coprocessor/dag/batch/statistics.rs, src/coprocessor/dag/rpn_expr/types/expr_eval.rs
=> engine, coprocessor: update copyright

components/cop_datatype/src/builder/field_type.rs, components/cop_datatype/src/builder/mod.rs, components/cop_datatype/src/lib.rs
This PR adds FieldTypeBuilder so that we can build FieldType more easier.
No.
=> Add field type builder

Cargo.lock, components/test_raftstore/pd.rs, etc/tikv-importer.toml, src/import/client.rs, src/import/config.rs, src/import/engine.rs, src/import/import.rs, src/import/kv_importer.rs, src/import/kv_service.rs, src/import/metrics.rs, src/import/prepare.rs, src/import/stream.rs, src/import/test_helpers.rs, src/pd/client.rs, src/pd/mod.rs, src/pd/util.rs, src/server/resolve.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/pd/mock/server.rs
Cherry-pick 3 PRs (#4349, #4386, #4423) into release 2.1.
Cherry-pick.
- unit test
- integration test
=> cherry-pick 3 PRs (#4349, #4386, #4423) into release 2.1

src/coprocessor/dag/batch/executors/index_scan_executor.rs, src/coprocessor/dag/batch/executors/limit.rs, src/coprocessor/dag/batch/executors/table_scan_executor.rs, src/coprocessor/dag/batch/executors/util/ranges_iter.rs, src/coprocessor/dag/batch/executors/util/scan_executor.rs, src/coprocessor/dag/batch/interface.rs, src/coprocessor/dag/batch/mod.rs
Like https://github.com/tikv/tikv/pull/4547, this PR picks another several engineering improvements:
- Rename expect_rows to scan_rows to be more precise
- Removed some unused
- Rearranged some imports.
No.
=> Several trivial engineering improvements 2

src/bin/tikv-server.rs, src/coprocessor/readpool_impl.rs, src/storage/readpool_impl.rs
In https://github.com/tikv/tikv/pull/4486 we changed store-read-xxx to storage-read-xxx. This PR reverses that change to make metrics compatible.
Manually:
=> Fix read pool names

fuzz/cli.rs
Change the error report when user run fuzz testing before install corresponding fuzzer. See issue #4585.
The original error report:
```
error: no such subcommand: `afl`
Did you mean `doc`?
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "error building afl instrumented binary, exit code Some(101)" }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
And now:
```
Running fuzzer failed: cannot run afl subcommand, please run `cargo install afl` before testing
Error: 1
```
The change to honggfuzz is similar.
Improvement.
It is unrelated to test cases.
No
No
#4585
=> Enhance error report for fuzzing

fuzz/cli.rs, fuzz/targets/mod.rs
Complete fuzz tests listed in #3355 
Some of the new fuzz tests failed. Separated issues will be opened for them.
#4609 
#4610
No.
No.
#3355
#4609
#4610
=> [WIP] Add more fuzz tests

src/raftstore/store/fsm/batch.rs, src/raftstore/store/fsm/router.rs
Otherwise mailbox may not be found and lead to `SendError`.
Close #4244.
- Bug fix
unit tests
No.
No.
=> tests: should register mailbox before sending

src/coprocessor/dag/rpn_expr/impl_op.rs, src/coprocessor/dag/rpn_expr/mod.rs, src/coprocessor/dag/rpn_expr/types/test_util.rs
Extracted from https://github.com/tikv/tikv/pull/3898, this PR implements RPN function LogicalOr.
Also this PR changes test utility to takes a function signature instead of a function, so that the mapping function can be also covered by tests.
Unit test.
=> Add RPN function LogicalOr

src/coprocessor/dag/builder.rs, src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/dag/executor/limit.rs, src/coprocessor/dag/executor/mod.rs, src/coprocessor/dag/executor/scan.rs, src/coprocessor/dag/executor/selection.rs, src/coprocessor/dag/executor/topn.rs, src/coprocessor/dag/handler.rs
Extracted from https://github.com/tikv/tikv/pull/4598
This PR adds support of the execution summary for non-batch executors.
See https://github.com/tikv/tikv/pull/4598
=> Add execution summary framework for non-batch executors

etc/tikv-importer.toml, src/import/engine.rs
Cherry-pick: #4611 to release 2.1
=> Cherry-pick: import: tune SstFileWriter options to reduce CPU usage (#4611)

scripts/check-bins-for-jemalloc.sh
Required for https://github.com/tikv/tikv/pull/4622 to pass CI.
=> Add cop_codegen to tikv_alloc whitelist

CHANGELOG.md, Cargo.lock, Cargo.toml
Bump to v2.1.9 and update the changelog.
=> Bump to v2.1.9

CHANGELOG.md, Cargo.lock
Upgrade raft to v0.4.3
- Bug fix (https://github.com/pingcap/raft-rs/pull/220)
Yes
No.
=> Cargo: upgrade raft to v0.4.3

src/storage/mvcc/reader/scanner/mod.rs
storage: elide unnecessary life type parameter
=> storage: elide unnecessary life type parameter

src/coprocessor/dag/builder.rs
This helps us identify exactly what kind of SQL cannot be batched.
No need.
=> Coprocessor: Output start_ts in Coprocessor batch messages

components/log_wrappers/src/lib.rs, components/test_util/src/logging.rs
Skip double colons.
Unit tests.
No.
No.
=> *: skip double colons

Cargo.lock, Cargo.toml, components/engine/Cargo.toml, components/log_wrappers/Cargo.toml, components/test_coprocessor/Cargo.toml, components/test_raftstore/Cargo.toml, components/test_raftstore/src/util.rs, components/test_storage/Cargo.toml, src/raftstore/store/fsm/apply.rs, src/raftstore/store/peer.rs, src/raftstore/store/worker/read.rs, src/server/service/kv.rs, tests/integrations/server/mod.rs
Upgrade kvproto to release-3.0
Unit tests.
No.
No.
=> Cargo: upgrade kvproto to release-3.0

src/raftstore/store/snap.rs, src/raftstore/store/worker/region.rs
`get_test_db_for_regions` returns `Engines` instead of a db.
Unit tests.
No.
No.
=> raftstore: tiny refactor snapshot tests

components/test_raftstore/src/cluster.rs, components/test_raftstore/src/pd.rs, src/bin/tikv-ctl.rs, src/raftstore/store/bootstrap.rs, src/raftstore/store/mod.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/snap.rs
Move INIT_EPOCH_VER/CONF_VER to peer_storage.
Unit tests.
No.
No.
=> raftstore: move INIT_EPOCH_VER/CONF_VER to peer_storage

src/coprocessor/codec/batch/lazy_column.rs, src/coprocessor/codec/batch/lazy_column_vec.rs
=> coprocessor: fix typo

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to 3.0.0-rc.1

Cargo.lock
Update rust-rocksdb to pick up latest Titan changes.
Improvement
travis
no
no
https://github.com/pingcap/rust-rocksdb/pull/293
=> Update rust-rocksdb to pick up latest Titan changes

src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, tests/raftstore_cases/test_conf_change.rs
=> *: reject transfer leader when the region recently changed config

Cargo.lock, Cargo.toml
cherry-pick #4714
- Bug fix
manual tests
No.
No.
#4714
=> *: fix unknown logs

components/match_template/src/lib.rs, src/coprocessor/codec/mysql/duration.rs, src/coprocessor/dag/batch/executors/fast_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/mod.rs, src/coprocessor/dag/batch/executors/selection_executor.rs, src/coprocessor/dag/batch/executors/simple_aggr_executor.rs, src/coprocessor/dag/batch/executors/slow_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/util/aggr_executor.rs, src/coprocessor/dag/batch/executors/util/hash_aggr_helper.rs, src/coprocessor/dag/batch/executors/util/mod.rs, src/coprocessor/dag/builder.rs, src/coprocessor/dag/rpn_expr/mod.rs, src/coprocessor/dag/rpn_expr/types/expr_builder.rs, src/coprocessor/dag/rpn_expr/types/mod.rs
This PR implements BatchHashAggregationExecutor.
Unit test.
=> Batch Hash Aggregation Executor

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to v3.0.0-rc.2

src/raftstore/store/peer.rs
Cherry pick read index bug fix in https://github.com/tikv/tikv/pull/4765.
No
No
=> [3.0] cherry pick read index bug fix

benches/misc/coprocessor/codec/chunk/mod.rs, src/binutil/server.rs, src/pd/mod.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/peer.rs, tests/failpoints/cases/test_conf_change.rs, tests/integrations/raftstore/test_merge.rs
Fix some typos in #4758 .
`ect` is the abbreviation of `excutor`, it's not a typo.
No.
No.
=> *: Fix some typos (#4758)

src/raftstore/store/fsm/peer.rs, src/raftstore/store/worker/read.rs, tests/integrations/raftstore/test_lease_read.rs
=> raftstore: mark read delegate as invalid correctly (#4765)

src/coprocessor/dag/batch/executors/fast_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/simple_aggr_executor.rs, src/coprocessor/dag/batch/executors/util/aggr_executor.rs, tests/integrations/raftstore/test_lease_read.rs
This PR cherry picks https://github.com/tikv/tikv/pull/4782
=> cop: Support empty aggr fn in batch aggr executor (cheery pick #4782)

tests/integrations/raftstore/test_lease_read.rs
=> stabilize a test case

src/storage/mod.rs, src/storage/txn/scheduler.rs
cherry-pick https://github.com/tikv/tikv/pull/4679
=> [2.1 cherry-pick] scheduler: handle system commands in high priority pool

Cargo.lock, Cargo.toml
=> Cargo: upgrade raft to v0.4.3 (#4653)

GOVERNANCE.md
The current release procedure refers to a VERSION file.  The VERSION file is relevant for Envoy (where this document is based on). Such file does not exist for TiKV, and the version is recorded in Cargo.toml. Updated the instruction to refer to Cargo.toml instead of VERSION.
(No code)
No
No
=> GOVERNANCE.md: fix the release version number check

src/raftstore/store/snap.rs
Synchronous all cf files of received snapshots.
Improvement.
=> raftstore: sync all cf files of received snapshots

CHANGELOG.md
=> [release-2.1] update change log

scripts/check-sse4_2.sh
Signed-off-by: Kaige Ye <ye@kaige.org>
The `gdb` check in PR https://github.com/tikv/tikv/pull/4832 was wrong. That PR was created by myself yesterday, I'm sorry for didn't have a double check, this PR will fix it.
Bug fix
Manual tests finished
No
No
https://github.com/tikv/tikv/issues/4330 https://github.com/tikv/tikv/pull/4832
@overvenus @lonng PTAL, sorry for that.
=> Makefile: fix gdb check

benches/coprocessor_executors/hash_aggr/util.rs, benches/coprocessor_executors/index_scan/util.rs, benches/coprocessor_executors/integrated/fixture.rs, benches/coprocessor_executors/integrated/mod.rs, benches/coprocessor_executors/mod.rs, benches/coprocessor_executors/selection/util.rs, benches/coprocessor_executors/simple_aggr/mod.rs, benches/coprocessor_executors/simple_aggr/util.rs, benches/coprocessor_executors/table_scan/util.rs, benches/coprocessor_executors/top_n/mod.rs, benches/coprocessor_executors/top_n/util.rs, benches/coprocessor_executors/util/executor_descriptor.rs, src/coprocessor/dag/batch/executors/top_n_executor.rs
This PR adds layered benchmarks for Top N executor. Also modified other benchmarks to wrap with a `Box`.
Benchmark result:
```
top_n_1_order_by_1_column_limit_10/normal/rows=5000
time:   [1.8968 ms 1.9085 ms 1.9154 ms]
top_n_1_order_by_1_column_limit_10/batch/rows=5000
time:   [445.93 us 447.36 us 449.69 us]
top_n_1_order_by_1_column_limit_4000/normal/rows=5000
time:   [4.5952 ms 4.6085 ms 4.6161 ms]
top_n_1_order_by_1_column_limit_4000/batch/rows=5000
time:   [2.2452 ms 2.2502 ms 2.2576 ms]
top_n_1_order_by_50_column_limit_10/normal/rows=5000
time:   [6.0711 ms 6.2311 ms 6.3127 ms]
top_n_1_order_by_50_column_limit_10/batch/rows=5000
time:   [2.2924 ms 2.3394 ms 2.4278 ms]
top_n_1_order_by_50_column_limit_4000/normal/rows=5000
time:   [9.1615 ms 9.3537 ms 9.6106 ms] …
```
=> Batch Top N Layered Benchmarks

Makefile
This PR is against the release-3.0 branch.
Cherry-picks dist_release makefile changes from https://github.com/tikv/tikv/pull/4687
See that issue and the corresponding SRE PR for discussion: https://github.com/pingcap/SRE/pull/243
Nothing. Assuming it works as the branch it was cherry-picked from.
Not user-facing docs. It is documented internally. Eventually it will be documented in a developer guide.
No
https://github.com/tikv/tikv/issues/4674
https://github.com/tikv/tikv/pull/4687
https://github.com/pingcap/SRE/pull/243
=> dist_release 3.0

README.md
Signed-off-by: Yukang <moorekang@gmail.com>
Fix broken URL in README.md
- Misc
=> Fix broken url for configuration options

src/storage/txn/latch.rs
For some hot keys, the waiting list in scheduler latch maybe very long, since we use VecDeque as the waiting list(for performance reason), we should shrink the waiting list after elements pop from it.
No
No
No
=> shrink the latch waiting list

Cargo.lock, components/engine/Cargo.toml, components/engine/src/rocks/util/engine_metrics.rs
Export some Titan column family metrics (listed below) for monitoring blob value condition.
- "rocksdb.titandb.live-blob-size"
- "rocksdb.titandb.num-live-blob-file"
- "rocksdb.titandb.num-obsolete-blob-file"
- "rocksdb.titandb.live-blob-file-size"
- "rocksdb.titandb.obsolete-blob-file-size"
unit test
No
Yes, PR later.
=> metrics: add titan metrics

components/engine/src/iterable.rs, components/engine/src/util.rs, src/import/stream.rs, src/raftstore/store/region_snapshot.rs
Check iter status when scanning. This is a supplement of https://github.com/tikv/tikv/pull/4470
No
No
No
=> engine: check iter status when scanning

src/bin/tikv-ctl.rs, src/server/debug.rs
=> improve bad-regions and tombstone subcommands for tikv-ctl

docs/clients/go-client-api.md
Signed-off-by: Kaige Ye <ye@kaige.org>
Add an error hint to go client guide.
Document improvement
N/A
https://github.com/tikv/tikv/pull/4868
No
https://github.com/golang/lint/issues/446#issuecomment-483638233
=> Docs: add error hint for golang lint

src/coprocessor/dag/batch/executors/util/scan_executor.rs
Signed-off-by: jswh <jswh@jswh.me>
set Enum and Set to valid batch types
no
no
https://github.com/tikv/tikv/issues/4762
=> set Enum and Set to valid batch types

src/coprocessor/dag/batch/executors/table_scan_executor.rs, src/coprocessor/error.rs, src/server/debug.rs, src/server/service/kv.rs, src/storage/lock_manager/util.rs, src/storage/metrics.rs, src/storage/mod.rs, src/storage/mvcc/lock.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/reader/scanner/util.rs, src/storage/mvcc/txn.rs, src/storage/txn/process.rs, src/storage/txn/scheduler.rs, src/storage/txn/store.rs, tests/integrations/raftstore/test_service.rs
Cherry-pick https://github.com/tikv/tikv/pull/4589
=> [release 3.0] cherry-pick: support resolve lock lite (#4589)

CHANGELOG.md, components/test_raftstore/src/transport_simulate.rs, src/binutil/setup.rs, src/raftstore/store/fsm/apply.rs, src/raftstore/store/msg.rs, src/raftstore/store/peer.rs, tests/failpoints/cases/test_conf_change.rs, tests/integrations/raftstore/test_lease_read.rs
Cherry-picks two changes to make request latency stable and avoid confusing empty calls.
- Bug fix
integration tests
Release note is updated.
No.
#4734, #4682
=> cherry-pick: changes to make latency stable

Cargo.lock, Cargo.toml, src/server/debug.rs, src/server/metrics.rs, src/server/service/kv.rs, src/storage/lock_manager/deadlock.rs, src/storage/lock_manager/metrics.rs, src/storage/lock_manager/mod.rs, src/storage/lock_manager/util.rs, src/storage/lock_manager/waiter_manager.rs, src/storage/metrics.rs, src/storage/mod.rs, src/storage/mvcc/lock.rs, src/storage/mvcc/metrics.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/txn.rs, src/storage/txn/process.rs, src/storage/txn/scheduler.rs, tests/integrations/raftstore/test_service.rs
Cherry picks 7 pessimistic transaction related PRs from master to release-3.0.
Signed-off-by: youjiali1995 zlwgx1023@gmail.com
=> Cherry-pick pessimistic txn related PR into release-3.0

src/config.rs, src/server/resolve.rs
Validate block-size in RocksDB column family option.
Unit test.
No
No
=> sanitize block size

src/config.rs
Cherry-pick https://github.com/tikv/tikv/pull/4920.
=> [3.0 cherry-pick] sanitize block size (#4920)

src/config.rs
Cherry-pick https://github.com/tikv/tikv/pull/4920.
=> [2.1 cherry-pick] sanitize block-size

components/tikv_util/src/file.rs, src/bin/tikv-ctl.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/metrics.rs, src/raftstore/store/peer.rs, src/raftstore/store/snap.rs, src/server/debug.rs, tests/failpoints/cases/test_stale_read.rs, tests/integrations/raftstore/test_lease_read.rs
cherry pick 3 commits from master:
=> cherry pick some commits from master to release 3.0

CHANGELOG.md, components/engine/src/iterable.rs, components/engine/src/util.rs, src/import/stream.rs, src/raftstore/store/region_snapshot.rs
=> engine: check iter status when scanning (#4863)

Cargo.lock, src/import/stream.rs, src/raftstore/store/region_snapshot.rs, src/storage/engine/mod.rs, src/storage/engine/raftkv.rs, src/storage/engine/rocksdb.rs, src/storage/mod.rs, src/storage/mvcc/reader/backward_scanner.rs, src/storage/mvcc/reader/forward_scanner.rs, src/storage/mvcc/reader/mod.rs, src/storage/mvcc/reader/util.rs, src/storage/txn/store.rs
=> storage: check iter status when invalid

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to v3.0.0-rc.3

components/cop_codegen/src/rpn_function.rs
This PR fixes a broken unit test.
Manually.
=> Fix unit test

etc/config-template.toml
=> fix config syntax

etc/config-template.toml
cherry pick  https://github.com/tikv/tikv/pull/4947
=> [3.0 cherry-pick] fix config syntax (#4947)

src/raftstore/store/peer.rs
=> more check about transferring leader during configuration change (#4799)

Cargo.lock, Cargo.toml, components/tikv_util/Cargo.toml
- update hashbrown 0.1 to 0.5
- NA
- NA
- NA
- NA
- NA
- NA
- NA
- NA
=> update hashbrown to 0.5

CHANGELOG.md, Cargo.lock, Cargo.toml
Release 3.0.0!
- Engineering
All kinds of tests.
Yes and updated.
Yes and will be updated.
=> *: bump 3.0.0

src/storage/txn/scheduler.rs
Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>
Fix a typo in comment
Fix a typo in comment
Misc
Comment change, do not need to run any test.
No
No
NA
NA
NA
=> Fix a typo in comment

src/coprocessor/dag/aggr_fn/parser.rs, src/coprocessor/dag/builder.rs, src/coprocessor/dag/rpn_expr/types/expr_builder.rs
This PR cherry picks #4985 to release-3.0.
=> Cherry pick #4985

CHANGELOG.md
Add changelog for v2.1.14
No
No
No
=> changelog: add v2.1.14 changelog

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md
Add labels in the issue templates. Similar to [tidb/10989](https://github.com/pingcap/tidb/pull/10989).
Misc
No tests required.
No
No
Resolves #5011
=> add labels in issue templates

src/raftstore/store/fsm/apply.rs
Fix duplicated plus assign (Duplicated with L700).
=> raftstore/store: fix duplicated plus assign

README.md
Update README and fix dead link.
Docs
=> Update README and fix dead link.

src/raftstore/store/fsm/apply.rs
Cherry-pick #5038 for release-3.0
=> raftstore/store: fix duplicated plus assign (#5038)

components/engine/src/rocks/util/mod.rs, src/pd/pd.rs
Counting the size of blob files in used size.
No
No
No
=> count size of blob files in used size

docs/how-to/get-started/deploy-using-docker-compose.md
* Fix the format of markdown
* Update the outdated links
manually tested
This PR is about the documentation.
NO
=> docs: fix the markdown format

README.md
-  This PR fixed the link to the documentation wiki.  A fix for issue https://github.com/tikv/tikv/issues/5064
- Bug fix
=> readme: fix links in readme

components/engine/src/errors.rs, src/raftstore/errors.rs
This PR displays error details for RaftStore and Engine errors.
Manually.
=> Display error details in raftstore error and engine error

components/tikv_util/src/logger/mod.rs
Just remove the panic! when failed to log.
Do not panic when failed to write log
https://github.com/tikv/tikv/issues/5042
manually tested
No.
No.
=> Do not panic when failed to write log.

fuzz/targets/mod.rs, src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/decimal.rs, src/coprocessor/dag/expr/builtin_arithmetic.rs, src/coprocessor/dag/rpn_expr/impl_arithmetic.rs, src/coprocessor/dag/rpn_expr/mod.rs
This PR cherry picks https://github.com/tikv/tikv/pull/4983
=> Cherry-pick: add IntDivideInt and IntDivideDecimal

components/tikv_util/src/lib.rs
Cherry-pick of #5053 
No
No
No
=> call _exit instead of exit (#5053)

src/storage/lock_manager/deadlock.rs
cherry-pick https://github.com/tikv/tikv/pull/5079
=> deadlock: improve the performance of detect (#5079)

components/engine/src/rocks/mod.rs, components/engine/src/rocks/util/config.rs, components/engine/src/rocks/util/engine_metrics.rs, components/engine/src/rocks/util/mod.rs, etc/config-template.toml, src/binutil/server.rs, src/config.rs, src/pd/pd.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-custom.toml
What have you changed? (mandatory)
Cherry-pick:
- https://github.com/tikv/tikv/pull/5060
- https://github.com/tikv/tikv/pull/4772
- https://github.com/tikv/tikv/pull/5026
- https://github.com/tikv/tikv/pull/4865
- https://github.com/tikv/tikv/pull/4991
- https://github.com/tikv/tikv/pull/4836
unit-test
No
No
=> Cherry-pick some Titan related commits

CHANGELOG.md, Cargo.toml
Bump version to 3.0.1
- feature
- bug fix
- unit test
- manually test
YES
NO
=> bump version release-3.0.1

docs/reference/tools/tikv-control.md
This PR added a note for running TiKV instance in local mode 
- doc update
=> reference/tikv-ctl: update local mode

src/coprocessor/dag/rpn_expr/impl_cast.rs
Extract a common utility function `is_unsigned`.
Exists unit tests.
=> coprocessor: extract a utility function 'is_unsigned'

src/server/raft_client.rs, tests/integrations/server/raft_client.rs
=> raftclient: add test case for server reconnection (#5030)

CHANGELOG.md, Cargo.lock, Cargo.toml
=> *: bump to v2.1.15

src/raftstore/store/fsm/apply.rs
Signed-off-by: mahjonp <junpeng.man@gmail.com>
fix compilation errors when running 'make fail_release'
Before this pr, running 'make fail_release' will cause a compilation error.
And this pr can fix it.
No
No
This error came from pr: https://github.com/tikv/tikv/pull/4903
And a related report: https://github.com/tikv/tikv/issues/5075#issuecomment-513447324
=> server: fix compilation errors when running 'make fail_release'

Cargo.lock, src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, src/storage/kv/raftkv.rs, tests/failpoints/cases/mod.rs, tests/failpoints/cases/test_replica_read.rs, tests/integrations/storage/test_raftkv.rs
Rename follower read to replica read.
integration test
No.
No.
=> Rename follower read

src/coprocessor/codec/convert.rs, src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/decimal.rs, src/coprocessor/codec/mysql/duration.rs, src/coprocessor/codec/mysql/json/json_cast.rs, src/coprocessor/codec/mysql/time/mod.rs
1. coprocessor: add functions convert * to decimal.
Unit tests
=> coprocessor: add functions convert * to decimal

Dockerfile, Makefile, scripts/check-sse4_2.sh, scripts/gen-dockerfile.sh
Some non Rust files still references the tikv-importer binary, which may break the CI.
N/A
No
No
#5036.
=> *: remove the remaining references of tikv-importer

src/coprocessor/codec/convert.rs, src/coprocessor/codec/data_type/mod.rs, src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/json/json_cast.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/rpn_expr/impl_cast.rs
Use trait to reorganize convert to int/uint functions (To keep this PR small and reviewable, others trait will be implemented in the next PR). 
- Engineering (engineering change which doesn't change any feature or fix any 
Exists unit tests.
=> coprocessor: use trait to reorganize convert to int/uint functions

src/storage/lock_manager/deadlock.rs, src/storage/lock_manager/util.rs
Remove expire-timer in deadlock detector.
=> deadlock: remove expire-timer

src/storage/mvcc/reader/scanner/backward.rs
Speedup test_many_tombstones to fix https://github.com/tikv/tikv/issues/5151
unit test
No
No
=> [test] speed up test_many_tombstones

src/server/node.rs
A change requested after merge in https://github.com/tikv/tikv/pull/4768#discussion_r309033357.
=> Info log for cluster bootstrap

src/coprocessor/local_metrics.rs, src/coprocessor/readpool_impl.rs, src/storage/readpool_impl.rs
Tinily cleanup read flow statistics:
1. Remove unused code
2. Use mem swap to avoid memory clone
Passing CI is fine
No
No
=> *: cleanup read flow statistics

components/test_raftstore/src/cluster.rs, src/raftstore/store/fsm/apply.rs, src/raftstore/store/fsm/mod.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/peer.rs, tests/failpoints/cases/test_merge.rs
Cherry pick of #4595 
unit-tests
=> raftstore, apply: catch up logs for merge through raft (#4595)

Cargo.lock
Cherry-pick of https://github.com/tikv/tikv/pull/5196
No
No
=> [release-3.0] engine: Update rust-rocksdb to improve Titan GC efficiency

Cargo.lock, src/raftstore/store/region_snapshot.rs
Update rust-rocksdb to improve Titan GC efficiency
No
No
No
=> engine: Update rust-rocksdb to improve Titan GC efficiency

components/tidb_query/src/codec/data_type/scalar.rs, components/tidb_query/src/rpn_expr/impl_arithmetic.rs, components/tidb_query/src/rpn_expr/types/test_util.rs
This test simplifies some RPN function test case.
=> Refine some RPN function test

Cargo.toml, benches/deadlock_detector/mod.rs, src/binutil/server.rs, src/storage/lock_manager/deadlock.rs, src/storage/lock_manager/util.rs, src/storage/lock_manager/waiter_manager.rs
Cherry pick  https://github.com/tikv/tikv/pull/5108, https://github.com/tikv/tikv/pull/5156, https://github.com/tikv/tikv/pull/5157, https://github.com/tikv/tikv/pull/5162.
=> Cherry pick lazy expiration of DetectTable

CHANGELOG.md, Cargo.lock, Cargo.toml
This PR bumps version to 3.0.2.
=> *: Bump to 3.0.2

tests/failpoints/cases/test_coprocessor.rs
Fix an import I missed in https://github.com/tikv/tikv/pull/5221
`make dev`
no
no
PTAL @siddontang @breeswish
=> Fix missed tipb import

.github/pull_request_template.md
Fix grammar issues as [Grammarly](https://app.grammarly.com) suggested. Every time I try to open a pull request, Grammarly complains the grammar issues of the pull request template. 
No need to test.
=> docs: Fix grammar issues as Grammarly suggested

src/raftstore/store/peer_storage.rs, tests/failpoints/cases/test_bootstrap.rs, tests/failpoints/cases/test_upgrade.rs
Fix 'boostrap' typo.
make dev (failed)
no
no
=> tests: fix 'boostrap' typo

cmd/src/bin/tikv-ctl.rs
just fix misspelled words in message
no need test, maybe :)
NO
NO
=> tikv-ctl.rs: correct some words in message

src/raftstore/store/peer.rs, tests/failpoints/cases/test_replica_read.rs
Cherry-pick https://github.com/tikv/tikv/pull/5213
=> Cherry-pick: fix duplicate `ctx` of read index

src/raftstore/store/fsm/apply.rs
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
just change string in error message, nothing too big.
no test
NO
NO
=> apply.rs: error message word misspell fix

src/raftstore/store/fsm/store.rs, src/server/node.rs, src/server/server.rs
Call PD put_store API after the store is bootstrapped.
Close #5269 
Improvement.
CI.
=> put store to PD after bootstrap finish

src/raftstore/store/fsm/store.rs, src/server/node.rs, src/server/server.rs
=> cherry pick #5270

components/tidb_query/src/executor/aggregation.rs, components/tidb_query/src/executor/index_scan.rs, components/tidb_query/src/executor/mod.rs, components/tikv_util/src/metrics/threads_dummy.rs, components/tikv_util/src/metrics/threads_linux.rs, src/raftstore/store/fsm/store.rs, tests/integrations/storage/test_raft_storage.rs
- Replace std's HashMap to tikv_util's HashMap
make dev
No.
No.
=> Replace std's HashMap to tikv_util's HashMap

src/storage/txn/process.rs
Just renaming a type.
cargo check
no
no
=> storage: give MultipleReturnValue a meaningful name

CHANGELOG.md, Cargo.lock, Cargo.toml
=> *: bump to v2.1.16

tests/integrations/server/kv_service.rs
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
just fix misspelled word in message.
no need test
NO
NO
=> cleanup: fix typos in panic message

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md, CONTRIBUTING.md, README.md
Make contributing instructions and templates more friendly and welcoming. Also rearranges things a bit to make the README shorter and polishes the English.
PTAL @siddontang @Hoverbear 
N/A
no
no
=> Make the contributing instructions more friendly

cmd/src/server.rs, components/test_raftstore/src/pd.rs, components/test_raftstore/src/server.rs, components/tidb_query/src/aggr_fn/impl_first.rs, components/tidb_query/src/codec/convert.rs, components/tidb_query/src/executor/table_scan.rs, components/tidb_query/src/rpn_expr/types/expr_eval.rs, src/raftstore/store/fsm/apply.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/util.rs, src/server/debug.rs, src/server/raftkv.rs, src/storage/kv/cursor_builder.rs, src/storage/kv/rocksdb_engine.rs
Some minor changes that make supporting Prost easier and which are also fine for rust-protobuf. Not actually supporting Prost.
Existing tests
no
no
PTAL @breeswish @overvenus
=> Some changes to make supporting Prost easier

src/storage/gc_worker.rs, tests/integrations/storage/test_raft_storage.rs
This PR cherry-picks #5212 to release-3.0 branch, which fixes a unstable test about GC. This is manually cherry-picked because conflicts. Cherry-picking this PR is not important. Just to make tests more stable.
For more details of this PR, please refer to #5212 .
By CI.
No.
NO.
=> test: Fix unstable integration test test_auto_gc (#5212)

cmd/src/bin/tikv-ctl.rs, tests/integrations/raftstore/test_bootstrap.rs
Signed-off-by: Sakura longfei.shang@daocloud.io
just fix misspelled word in message.
- Separately describe each logical change (optional)
no need test
Please describe the tests that you ran to verify your changes. Have you added unit or integration tests, or run manual tests? What additional tests would give you greater confidence in this change?
NO
- If there is a document change, please file a PR in …
=> cleanup: fix typos in   test_bootstrap.rs

CHANGELOG.md, Cargo.lock, Cargo.toml, components/engine/Cargo.toml, components/engine/src/rocks/mod.rs, src/storage/config.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-custom.toml
=> Cherry-pick: Exclude shared block cache from core dump

Cargo.lock, src/coprocessor/error.rs, src/server/debug.rs, src/server/service/kv.rs, src/storage/mod.rs, src/storage/mvcc/lock.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/reader/mod.rs, src/storage/mvcc/reader/util.rs, src/storage/mvcc/txn.rs, src/storage/txn/process.rs, src/storage/txn/scheduler.rs, tests/raftstore_cases/test_service.rs
Cherry-pick https://github.com/tikv/tikv/pull/4589
UT & Manual test
No
No
=> [2.1 cherry-pick] resolve specified keys

Dockerfile, scripts/gen-dockerfile.sh
Update scripts/gen-dockerfile.sh and Dockerfile. Now, cmd is included in dependencies and profiling features are removed for all components.
manual test.
No.
No.
Ref #5289
=> scripts: upadte gen-dockerfile.sh

src/bin/tikv-server.rs, src/binutil/server.rs, src/binutil/setup.rs, src/config.rs
Signed-off-by: cwen0 <cwenyin0@gmail.com>
cherry-pick: #5298
=> add `config-check` flag for tikv-server (#5298)

src/raftstore/store/local_metrics.rs, src/raftstore/store/peer.rs, tests/integrations/storage/test_raftkv.rs
Cherry-pick https://github.com/tikv/tikv/pull/5316
=> cherry-pick: return error when read index is dropped due to invaild leader

Cargo.lock, Cargo.toml, Dockerfile, components/backup/Cargo.toml, components/backup/src/errors.rs, components/backup/src/lib.rs, src/server/service/debug.rs
Initial the backup component and add the error type.
Currently, it's dead code, and will be tested in later PRs.
No.
No.
=> backup: add backup component and error type

src/server/service/kv.rs
Most of the methods in BatchCommands don't need peer, so we don't need to clone peer every time. 
Passing CI is fine
No
No
=> service: remove unnecessary peer clone

CHANGELOG.md, Cargo.lock, Cargo.toml
=> *: Bump to 3.0.3

components/pd_client/src/client.rs, components/pd_client/src/lib.rs, components/test_raftstore/src/pd.rs, src/raftstore/store/peer.rs, src/raftstore/store/worker/pd.rs, src/server/resolve.rs, tests/integrations/pd/test_rpc_client.rs, tests/integrations/raftstore/test_region_heartbeat.rs
Report the raft term in region heartbeat.
PD needs this information to tell if the leader of a region has changed. If it is, the stats TiKV reported should be carefully handled because the stats may differ in huge.
- unit tests
NO
NO
- https://github.com/pingcap/kvproto/pull/410
=> pd_client: report term in region heartbeat

src/raftstore/store/fsm/peer.rs
Change to optimize `check snapshot range` debug statement containing `region_ranges `. 
region_ranges contains range info in a TiKV instance and causing performance regression,  as debug logs are always evaluated since `Slog` does filtering after log is generated (due to concept of Drain).
Unit tests
No
No
https://github.com/tikv/tikv/issues/5122
=> optimize check snapshot range debug logging

Cargo.lock, cmd/Cargo.toml, cmd/src/server.rs, cmd/src/setup.rs, components/backup/src/endpoint.rs, components/backup/src/lib.rs
This PR enables the backup feature, removes unused imports and limits backup threads. 
Integration tests.
No.
No.
=> cmd, backup: enable backup feature

src/storage/mvcc/reader/point_getter.rs, src/storage/txn/store.rs
Cherry pick https://github.com/tikv/tikv/pull/5469
Note: There are still some improvements that can be made in #5469, however the performance difference is not notable and best throttle value is not carefully discussed, so as an urgent fix this PR does not include them.
=> [Cherry Pick 3.1] Fix PointGetter performance issue when there are concurrent write

src/storage/mvcc/reader/point_getter.rs, src/storage/txn/store.rs
Cherry pick https://github.com/tikv/tikv/pull/5469
Note: There are still some improvements that can be made in #5469, however the performance difference is not notable and best throttle value is not carefully discussed, so as an urgent fix this PR does not include them.
=> [Cherry Pick 3.0] Fix PointGetter performance issue when there are concurrent write

Cargo.lock, Cargo.toml, components/engine/src/rocks/mod.rs, components/engine/src/rocks/sst.rs, components/engine/src/rocks/util/io_limiter.rs, components/engine/src/rocks/util/mod.rs, components/external_storage/Cargo.toml, components/external_storage/src/lib.rs, components/external_storage/src/local.rs, components/external_storage/src/noop.rs, components/tikv_util/src/file.rs, src/import/test_helpers.rs, src/storage/mvcc/reader/mod.rs, src/storage/mvcc/reader/scanner/mod.rs, src/storage/mvcc/reader/scanner/txn_entry.rs, src/storage/txn/mod.rs, src/storage/txn/store.rs
Cherry pick PRs for backup,
- #5211 
- #5325 
- #5327 
- #5353 
- #5434 
- #5428
=> Rollup of 6 commits

components/tidb_query_codegen/src/rpn_function.rs
Ignore a broken doctest.
make test
no
no
=> tidb_query_codegen: fix doc tests

Cargo.lock, src/server/metrics.rs, src/server/service/kv.rs, src/storage/metrics.rs, src/storage/mod.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/txn.rs, src/storage/txn/process.rs, src/storage/txn/scheduler.rs, tests/integrations/server/mod.rs
This PR cherry-picks #5407 . For more detail please refer to #5407 . This is cherry-picked to 3.0 because it's needed by pessimistic transaction.
By CI
This should be noted in release notes.
No.
=> (3.1) txn: Add txn_heart_beat API (#5407) 

Cargo.lock
Update Titan to cherry-pick changes in https://github.com/pingcap/titan/pull/89
Improvement & Bugfix
CI
No.
No
=> update titan for tikv-3.0

Cargo.lock
Upgrade all non-git dependencies to their latest, updating lockfile.
cargo test --all --features=jemalloc,sse,portable
no
no
=> *: update all registry deps

README.md
-  Updated the link for TiKV WG slack which was outdated
=> readme: update the WG slack link

Cargo.lock, Cargo.toml, cmd/Cargo.toml, cmd/src/server.rs, cmd/src/setup.rs, components/backup/Cargo.toml, components/backup/src/endpoint.rs, components/backup/src/errors.rs, components/backup/src/lib.rs, components/backup/src/metrics.rs, components/backup/src/service.rs, components/backup/src/writer.rs, src/raftstore/coprocessor/mod.rs, src/raftstore/coprocessor/region_info_accessor.rs, src/storage/kv/rocksdb_engine.rs, src/storage/mvcc/mod.rs
Cherry-pick backup commits:
- #5352 
- #5358 
- #5359 
- #5392 
- #5436 
- #5451 
- #5476
=> Rollup of backup commits

CONTRIBUTING.md
Updated documentation to resolve #5492 
No need
no
no
#5492
no
no
=> Correct test command.

Cargo.lock, components/backup/Cargo.toml, components/backup/tests/integrations/mod.rs, components/backup/tests/integrations/test_backup.rs, components/test_raftstore/src/server.rs
=> backup: test backup and import (#5486)

cmd/src/server.rs, components/backup/src/endpoint.rs, components/backup/src/metrics.rs
control backup endpoint's thread pool
No
No
No
=> backup: control backup threads

components/tikv_util/src/mpsc/batch.rs
When `batch::Sender` is dropped, it needs to drop the internal
`crossbeam::Sender` before notify the receiver respectively, 
otherwise the receiver maybe can't know it forever if the receiver
is running in an `Executor` as a future.
Fix a potential resourse leak bug.
Bugfix.
Unit test.
Previously we only test the channel in multi threads, so the bug is very hard to produce. Now we add a case which polls the receiver in `Sender::drop`, so it can be produced 100%.
Close https://github.com/tikv/tikv/issues/5563.
In the issue file descriptors leak because they are associated with some `GrpcCall`s. With this bug some resources can't be released after the `Sender` is dropped, and they could …
=> util: fix a resource leak bug about mpsc::batch

src/storage/config.rs
Signed-off-by: pentium3 <celerond@msn.com>
Changes: Change default value of high_pri_pool_ratio.
Improvement.
Manually tested.
No
No
Test Log: https://internal.pingcap.net/confluence/pages/viewpage.action?pageId=62882849
=> Modify default value of high_pri_pool_ratio

CHANGELOG.md, Cargo.lock, Cargo.toml
Signed-off-by: shirly <AndreMouche@126.com>
Bump to 3.0.4
=> bump to 3.0.4

src/raftstore/coprocessor/properties.rs, src/raftstore/store/region_snapshot.rs, src/storage/kv/mod.rs
print error and panic when getting value encounters an error  
- No code
No
No
=> raftstore: panic when getting value encouters an error

components/test_raftstore/src/cluster.rs, src/pd/pd.rs, src/raftstore/coprocessor/properties.rs, src/raftstore/coprocessor/split_check/half.rs, src/raftstore/coprocessor/split_check/size.rs, src/raftstore/coprocessor/split_check/table.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/worker/split_check.rs, src/server/debug.rs, tests/integrations/raftstore/test_split_region.rs
=> raftstore: reduce the overhead of region heartbeat (#5537)

src/storage/mvcc/reader/point_getter.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/reader/scanner/backward.rs, src/storage/mvcc/reader/scanner/forward.rs, src/storage/mvcc/reader/util.rs, src/storage/mvcc/txn.rs
Cherry pick https://github.com/tikv/tikv/pull/5536
=> mvcc/reader: fix check lock not return the right ts (#5536)

.github/ISSUE_TEMPLATE/performance-challenge-program.md
Signed-off-by: you06 <you1474600@gmail.com>
Add the issue template for performance challenge program.
When create issue, there is an optional template for PCP.
- No code
=> add pcp issue template

CHANGELOG.md, Cargo.lock, Cargo.toml
Signed-off-by: shirly <AndreMouche@126.com>
Bump to v3.0.5
=> release: bump to v3.0.5

Cargo.lock, Cargo.toml, components/backup/src/endpoint.rs, components/backup/src/writer.rs, components/backup/tests/integrations/test_backup.rs, components/cop_datatype/Cargo.toml, components/test_coprocessor/Cargo.toml, components/tikv_util/Cargo.toml, components/tikv_util/src/file.rs, components/tipb_helper/Cargo.toml, src/coprocessor/checksum.rs, src/coprocessor/mod.rs, src/storage/txn/store.rs
=> cherry-pick: improve backup checksum feature

benches/hierarchy/mvcc/mod.rs, src/server/gc_worker.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/txn.rs, src/storage/txn/process.rs
They are not used any more, so simply remove it.
- Unit test
=> Remove bound from MvccReader

CHANGELOG.md, Cargo.lock, Cargo.toml
Signed-off-by: wuxuelian <AndreMouche@126.com>
Bump v2.1.18
=> Bump v2.1.18

components/backup/tests/integrations/test_backup.rs
=> backup: stop test cluster before finishing tests (#5781)

components/tidb_query/src/rpn_expr/impl_op.rs, components/tidb_query/src/rpn_expr/mod.rs
PCP #5751
Vectorize `LogicalXor`
- Unit test
No
No
=> Copr: Vectorize `LogicalXor`

components/test_raftstore/src/server.rs, components/test_storage/src/sync_storage.rs, etc/config-template.toml, src/binutil/server.rs, src/config.rs, src/server/node.rs, src/storage/config.rs, src/storage/gc_worker.rs, src/storage/mod.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-custom.toml, tests/integrations/config/test-default.toml, tests/integrations/storage/test_storage.rs
=> gc_worker: limit the write flow of GC(#5263)

src/server/lock_manager/mod.rs, src/server/lock_manager/waiter_manager.rs
=> lock_manager: make has_waiter accurate (#5518)

Cargo.lock, components/test_storage/src/assert_storage.rs, src/coprocessor/dag/batch/executors/table_scan_executor.rs, src/coprocessor/error.rs, src/server/lock_manager/mod.rs, src/server/lock_manager/waiter_manager.rs, src/server/service/kv.rs, src/storage/lock_manager/mod.rs, src/storage/lock_manager/util.rs, src/storage/mod.rs, src/storage/mvcc/lock.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/reader/point_getter.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/reader/scanner/backward.rs, src/storage/mvcc/reader/scanner/forward.rs, src/storage/mvcc/reader/scanner/mod.rs, src/storage/mvcc/reader/util.rs, src/storage/mvcc/txn.rs, src/storage/txn/process.rs, src/storage/txn/scheduler.rs, src/storage/txn/store.rs
=> pessimistic-txn: support lock wait timeout (#5680)

components/tidb_query/src/rpn_expr/impl_math.rs, components/tidb_query/src/rpn_expr/mod.rs
PCP https://github.com/tikv/tikv/issues/5751
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>
Vectorize `sign` `sqrt`
- Improvement
- Unit test
No
No
=> copr: vectorize Sign Sqrt

components/tidb_query/src/rpn_expr/impl_math.rs, components/tidb_query/src/rpn_expr/mod.rs
PCP https://github.com/tikv/tikv/issues/5751
Vectorize `Pi`
- Unit test
No
No
@lonng @breeswish
=> copr: Vectorize PI

CONTRIBUTING.md
Remove forum link for eventual decommissioning.
Misc
- No code
Nope
Nope
=> Remove discourse

components/tidb_query/src/rpn_expr/impl_op.rs, components/tidb_query/src/rpn_expr/mod.rs
PCP #5751 
add vectorized left_shift
- Unit test
No
No
=> copr: Add vectorized left_shift

components/test_raftstore/src/transport_simulate.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/local_metrics.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/worker/region.rs, tests/failpoints/cases/test_replica_read.rs
This PR adds more condition checks before proposing a raft cmd.
fix https://github.com/tikv/tikv/issues/5875
- Unit test
No.
No.
=> raftstore: more condition checks before proposing raft cmd

components/tidb_query/src/rpn_expr/impl_math.rs, components/tidb_query/src/rpn_expr/mod.rs
Signed-off-by: AerysNan <aerysnan@gmail.com>
PCP #5751
Vectorize radians.
Improvement (a change which is an improvement to an existing feature)
Unit test
No.
No.
=> copr: vectorize radians

src/raftstore/store/peer.rs, src/raftstore/store/worker/region.rs, src/server/snap.rs, tests/failpoints/cases/test_replica_read.rs
Cherry-pick https://github.com/tikv/tikv/pull/5919
=> [Cherry pick 3.1]raftstore: delay replica read when applying snapshot

Makefile
Signed-off-by: mahjonp <junpeng.man@gmail.com>
cherry-pick: #5934
- No code
- No
- No
=> [release-3.0] cherry pick: Makefile: a new rule for CI test 

components/tidb_query/src/rpn_expr/impl_string.rs, components/tidb_query/src/rpn_expr/mod.rs
PCP #5751
Vectorize LocateBinary2Args
- Unit test
No
No
=> Copr: Vectorize LocateBinary2Args

components/tidb_query/src/rpn_expr/impl_math.rs, components/tidb_query/src/rpn_expr/mod.rs
Signed-off-by: gauss <gauss1314@gmail.com>
PCP #5751 
Add vectorized crc32
- Unit test
No
No
=> copr: Add vectorized crc32

components/tidb_query_codegen/src/rpn_function.rs
#5993 changed the rpn_fn macro codegen code but didn't change the unit tests accordingly. This PR fixes it.
Fixes #6033
- Unit test
No
No
=> fix rpn_fn codegen unit test

components/tidb_query/src/expr/builtin_math.rs, components/tidb_query/src/expr_util/conv.rs, components/tidb_query/src/expr_util/mod.rs, components/tidb_query/src/rpn_expr/impl_math.rs, components/tidb_query/src/rpn_expr/mod.rs
Signed-off-by: Zhu Zihao <all_but_last@163.com>
PCP #5751 
Vectorize `conv`
Clean the implementation of non-vectorized one.
- Unit test
No
No
Finish https://github.com/tikv/tikv/pull/5921
=> copr: vectorize `conv`.

components/tidb_query/src/codec/mysql/json/json_modify.rs
Signed-off-by: Wangweizhen <hawking.rei@gmail.com>
add the bad parameter to error message for helping locate the problem.
- Improvement 
- No code
No
No
=> improve: json modify error

Cargo.lock, Cargo.toml, cmd/Cargo.toml, components/backup/Cargo.toml, components/test_raftstore/Cargo.toml, components/tikv_util/Cargo.toml, components/tikv_util/src/file.rs
Use OpenSSL SIMD sha256 implementation to accelerate backup.
- Unit test
No.
No.
=> *: use simd sha256

components/tidb_query/src/rpn_expr/impl_time.rs, components/tidb_query/src/rpn_expr/mod.rs
PCP #5751
Add vectorized month
- Unit test
No
No
#5751
=> copr: Add vectorized month

components/tidb_query/src/rpn_expr/impl_string.rs
Fix code style inconsistency between unit tests for vectorized string fns so as to give contributors a clear example.
- Unit test
=> copr: fix test code style

src/raftstore/store/fsm/store.rs, src/raftstore/store/local_metrics.rs, src/raftstore/store/metrics.rs, src/raftstore/store/peer.rs
cherry-pick: #5440 #5465 
No
No
pingcap/tidb-ansible#577
=> [release-3.1] cherry-pick: add commit log duration metrics

components/tidb_query/src/rpn_expr/impl_time.rs, components/tidb_query/src/rpn_expr/mod.rs
PCP #5751
Add vectorized year
- Unit test
No
No
If there is a configuration ###  Refer to a related PR or issue link (optional)
#5751
=> Add vectorized year

components/tidb_query/src/rpn_expr/impl_string.rs, components/tidb_query/src/rpn_expr/mod.rs
Signed-off-by: tw <t888y@qq.com>
PCP #5751
Add vectorize space
- Unit test
No
No
=> copr: Add vectorize space

Cargo.lock
The `pprof-rs` contains BUG and update to the latest version contained BUG fix.
=> Cargo.lock: update the latest version of pprof-rs

src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs
=> raftstore: attach peer tag to box errors (#6068)

Cargo.lock, components/engine/Cargo.toml, components/engine_rocks/Cargo.toml, src/config.rs, src/raftstore/store/fsm/apply.rs, src/storage/txn/process.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-custom.toml
Add multithread write for perf-4.0
- Unit test
No
No
=> Local perf 4.0

Cargo.toml, cmd/Cargo.toml, components/backup/Cargo.toml, components/codec/Cargo.toml, components/engine/Cargo.toml, components/engine_rocks/Cargo.toml, components/engine_traits/Cargo.toml, components/external_storage/Cargo.toml, components/log_wrappers/Cargo.toml, components/match_template/Cargo.toml, components/pd_client/Cargo.toml, components/sst_importer/Cargo.toml, components/test_coprocessor/Cargo.toml, components/test_raftstore/Cargo.toml, components/test_sst_importer/Cargo.toml, components/test_storage/Cargo.toml, components/test_util/Cargo.toml, components/tidb_query/Cargo.toml, components/tidb_query_codegen/Cargo.toml, components/tidb_query_datatype/Cargo.toml, components/tikv_util/Cargo.toml, components/tipb_helper/Cargo.toml, fuzz/Cargo.toml, fuzz/fuzzer-afl/Cargo.toml, fuzz/targets/Cargo.toml, tests/Cargo.toml
Sort dependencies in Cargo.tomls alphabetically
PTAL @Hoverbear @brson 
=> Sort all deps in Cargo.tomls alphabetically

CHANGELOG.md, Cargo.lock, Cargo.toml
Signed-off-by: shirly AndreMouche@126.com
bump v3.0.6
=> *:bump v3.0.6

components/tidb_query/src/rpn_expr/impl_compare_in.rs
Fix a bug in https://github.com/tikv/tikv/pull/6000 that the optimization is not effective.
- Manual test
=> Fix the bug that IN() optimization is not taking effect

Cargo.toml, cmd/Cargo.toml, components/backup/Cargo.toml, components/test_coprocessor/Cargo.toml, components/test_raftstore/Cargo.toml, components/test_storage/Cargo.toml, tests/Cargo.toml
trying fix #6087  by adding `protobuf-codec` as a default feature, as we need either `protobuf-codec` or `prost-codec` 
- Manually
No
No
#6087
=> fix cargo build

src/coprocessor/endpoint.rs
Relax log level in cop/endpoint.
=> cop/endpoint: relax log level

components/tidb_query/src/rpn_expr/impl_time.rs, components/tidb_query/src/rpn_expr/mod.rs
PCP #5751
Add vectorized year
- Unit test
No
No
for #5751
=> copr: Add vectorize day_of_month

components/tidb_query/src/rpn_expr/impl_encryption.rs, components/tidb_query/src/rpn_expr/mod.rs
Signed-off-by: Zhu Zihao <all_but_last@163.com>
PCP #5751
Vectorize `uncompressed_length`
- Unit test
No
No
=> copr: Vectorize `uncompressed_length`.

Cargo.lock
Update grpc to fix a potencial memory leak issue.
Engineering.
Unit tests.
No.
No.
=> update grpc to fix a potencial memory leak issue

CHANGELOG.md, Cargo.lock, Cargo.toml
bump v3.0.7
@hicqu @youjiali1995 PTAL
=> bump v3.0.7

src/raftstore/store/fsm/peer.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/peer.rs
Ref #6154 
- Improvement
No.
No.
#6154.
=> raftstore: apply early

components/test_storage/src/assert_storage.rs, components/test_storage/src/sync_storage.rs, src/server/service/kv.rs, src/storage/mod.rs, src/storage/mvcc/txn.rs, src/storage/txn/process.rs, tests/integrations/raftstore/test_service.rs, tests/integrations/storage/test_storage.rs
=> parallel-commit: fix batch prewrite and batch commit

components/tidb_query/src/expr/builtin_string.rs, components/tidb_query/src/expr/scalar_function.rs, components/tidb_query/src/rpn_expr/impl_string.rs, components/tidb_query/src/rpn_expr/mod.rs
PCP #5751
implement oct_int
Improvement
- Unit test
No
No
=> copr: implement oct_int

CHANGELOG.md, Cargo.lock, Cargo.toml
+ Support the distributed backup and restore feature [#5532](https://github.com/tikv/tikv/pull/5532)
+ Support the Follower Read feature [#5562](https://github.com/tikv/tikv/pull/5562)
=> Bump v3.1.0-beta

Cargo.lock, components/external_storage/src/lib.rs, src/server/service/diagnostics.rs
1. Update `kvproto`  to the latest version.
2. Support streaming for diagnostics interface
- Unit test
=> support streaming for diagnostics interface

src/import/speed_limiter.rs
This PR cherry picks https://github.com/tikv/tikv/pull/6278
=> [release-3.0] Fix an unstable test

Cargo.lock, etc/config-template.toml, src/server/lock_manager/config.rs, src/server/lock_manager/mod.rs, src/server/lock_manager/waiter_manager.rs, tests/integrations/server/lock_manager.rs
=> lock_manager: polish waiter manager (#6244)

Cargo.lock
cherry-pick: #6064
- Bugfix
- No code
=> [release-3.0] cherry pick: update pprof-rs to v0.3.12

src/server/lock_manager/waiter_manager.rs
Relax constraint in test_waiter_manager_wake_up.
- Unit test
No
No
=> test: fix unstable test_waiter_manager_wake_up

components/tikv_util/src/metrics/threads_linux.rs
This PR tries to stablize `test_thread_io_statistics`.
- Unit test
=> Try to stablize IO test

src/coprocessor/codec/data_type/vector.rs, src/coprocessor/dag/aggr_fn/impl_avg.rs, src/coprocessor/dag/aggr_fn/impl_first.rs, src/coprocessor/dag/aggr_fn/impl_max_min.rs, src/coprocessor/dag/aggr_fn/impl_sum.rs
https://github.com/tikv/tikv/pull/6002 for release-3.1 branch.
=> [release-3.1] Cherry pick #5429

components/tidb_query/src/util.rs
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>
Modify comment of is_prefix_next.
None
None
None
=> copr: modify is_prefix_next fn comment

Cargo.lock, components/engine/src/iterable.rs, components/engine/src/rocks/mod.rs, components/engine/src/util.rs, src/import/sst_importer.rs, src/import/stream.rs, src/raftstore/coprocessor/split_check/table.rs, src/raftstore/store/region_snapshot.rs, src/raftstore/store/worker/split_check.rs, src/server/debug.rs, src/storage/kv/btree_engine.rs, src/storage/kv/mod.rs, src/storage/kv/raftkv.rs, src/storage/kv/rocksdb_engine.rs, src/storage/mod.rs, src/storage/mvcc/reader/point_getter.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/reader/scanner/backward.rs, src/storage/mvcc/reader/scanner/forward.rs, src/storage/mvcc/reader/scanner/txn_entry.rs, src/storage/txn/store.rs
Fix error handling about rocksdb iterator.
Bug fix.
Unit tests.
No.
No.
=> fix error handling about rocksdb iterator

components/tidb_query/src/codec/convert.rs, components/tidb_query/src/codec/mysql/decimal.rs, components/tidb_query/src/expr/builtin_compare.rs, components/tidb_query/src/expr/column.rs, components/tidb_query/src/expr/constant.rs, components/tidb_query/src/rpn_expr/impl_cast.rs, components/tidb_query/src/rpn_expr/impl_op.rs, fuzz/targets/mod.rs
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>
Add `#[derive(Copy)]` for `Decimal`
- Unit test
No
No
=> copr: derive Copy for Decimal

CHANGELOG.md, Cargo.lock, Cargo.toml
=> bump v2.1.19

src/server/service/diagnostics.rs
This PR refactors search log interface of diagnostics service. The previous implementation may return a huge response, which may exceed the limit of the gRPC single package.
=> refactor search log interface of diagnostics service

Cargo.lock, Cargo.toml, src/server/service/diagnostics.rs
This PR simplified the `LogStream` introduced by https://github.com/tikv/tikv/pull/6356
=> Refactor search log batcing

cmd/src/setup.rs, components/tikv_util/src/logger/file_log.rs, components/tikv_util/src/logger/mod.rs
This PR refactored the code style of `components/tikv_util/src/logger/file_log.rs`
=> tikv_util: remove the tedious type parameter

src/storage/kv/cursor_builder.rs, src/storage/mvcc/reader/scanner/mod.rs, src/storage/txn/store.rs
See details in #6291 
Benchmark result shows significant improvement.
No
No
See #6291
=> filter write cf sst by commit ts in incremental backup (#6291)

Cargo.lock, components/external_storage/src/lib.rs, src/import/errors.rs, src/import/sst_importer.rs, src/raftstore/store/worker/split_check.rs
Cherry-pick of https://github.com/tikv/tikv/pull/6225
=> importer: rewrite ts for download SST (#6225)

CHANGELOG.md, Cargo.lock, Cargo.toml
=> bump v3.0.8

src/storage/mvcc/txn.rs
=> txn: use Commit to clean up pessimistic locks (#6353)

components/sst_importer/src/errors.rs, components/sst_importer/src/lib.rs, components/sst_importer/src/metrics.rs, components/sst_importer/src/service.rs, components/sst_importer/src/sst_importer.rs, src/import/sst_service.rs
Signed-off-by: luancheng <luancheng@pingcap.com>
add some metrics for sst_importer
- Unit test
https://github.com/pingcap/tidb-ansible/pull/1091
=> sst_importer: add metrics

docs/V2.1/op-guide/horizontal-scale.md, docs/V2.1/tools/tikv-control.md, docs/how-to/scale/horizontal-scale.md, docs/reference/tools/tikv-control.md
Signed-off-by: yeya24 <yb532204897@gmail.com>
- Separately describe each logical change (optional)
- Unit test
- No code
Only minor change to the doc.
=> Unify tikv port

Cargo.lock, components/pd_client/Cargo.toml, components/pd_client/src/client.rs, components/pd_client/src/lib.rs, components/pd_client/src/util.rs, components/test_raftstore/src/pd.rs, tests/integrations/pd/mock/mocker/service.rs, tests/integrations/pd/mock/server.rs, tests/integrations/pd/test_rpc_client.rs
Support get_tso RPC to get timestamp from PD.
No.
No.
=> pd_client: support get_tso RPC

Cargo.lock, Makefile, tests/Cargo.toml, tests/failpoints/cases/mod.rs, tests/failpoints/cases/test_gc_worker.rs, tests/failpoints/cases/test_storage.rs
Make fail point cases comilable again.
Engineering.
Integration test
No.
No.
=> tests: fix failpoint cases

components/test_raftstore/src/server.rs, components/test_raftstore/src/util.rs, etc/config-template.toml, src/server/lock_manager/config.rs, src/server/lock_manager/mod.rs, tests/integrations/server/lock_manager.rs
=> lock_manager: update default config (#6426)

src/server/lock_manager/deadlock.rs, src/server/lock_manager/mod.rs, tests/integrations/server/lock_manager.rs
=> deadlock: more solid role change observer (#6415)

src/raftstore/store/fsm/peer.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/msg.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/worker/region.rs, tests/integrations/raftstore/test_conf_change.rs
Cherry pick #6421.
- Bugfix
- Unit test
No
No.
#6421, #6420.
=> raftstore: speed up conf change (#6421)

components/tidb_query/src/codec/mysql/time/mod.rs
Check `Date` via `check_datetime`
- Unit test
=> copr: check `Date` via `check_datetime`

Cargo.lock
Update grpcio to shrink internal buffer.
No code.
No.
No.
=> grpc: update grpcio to shrink internal buffer

Cargo.lock, Cargo.toml
Bump v3.0.9
Close https://github.com/tikv/tikv/milestone/18
=> Bump v3.0.9

Cargo.lock, Cargo.toml, Makefile, components/engine/Cargo.toml, components/engine_rocks/Cargo.toml, components/external_storage/Cargo.toml, components/keys/Cargo.toml, components/log_wrappers/Cargo.toml, components/pd_client/Cargo.toml, components/tidb_query/Cargo.toml, components/tidb_query_datatype/Cargo.toml, components/tikv_alloc/Cargo.toml, components/tikv_util/Cargo.toml, components/txn_types/Cargo.toml, scripts/check-udeps.sh
Prune unused dependencies and a script to check unused dependencies by [cargo-udeps](https://github.com/est31/cargo-udeps).
- Unit test
No.
No.
Close https://github.com/tikv/tikv/issues/5236
=> *: prune unused dependencies

tests/integrations/raftstore/test_prevote.rs
Stabilize prevote cases.
Engineering.
Unit test.
No.
No.
=> test: stabilize prevote cases.

CHANGELOG.md, Cargo.lock, Cargo.toml, components/engine/Cargo.toml, components/engine_rocks/Cargo.toml
Bump v4.0.0-beta
Close https://github.com/tikv/tikv/milestone/10
=> Bump v4.0.0-beta

src/raftstore/store/worker/pd.rs
fix log wording
- No code
No
No
None.
None.
None.
=> pd: minor log adjustment

components/cdc/src/delegate.rs, components/cdc/src/endpoint.rs, components/cdc/src/lib.rs, src/storage/mvcc/reader/mod.rs, src/storage/txn/store.rs
This PR implements the `Initializer` that's used by CDC's `Endpoint` to initialize `Delegate`s.  `Endpoint` and `Delegate` are either unimplemented yet on master, so `Initializer` is actually not used for now.
- Unit test
No
No
=> CDC: Implement Initializer of Endpoint

src/config.rs
"true" was misspelled as "ture" in `src/config.rs` 😏.
- None
No
No
=> config: fix a typo (ture -> true)

CHANGELOG.md, Cargo.lock, Cargo.toml
This is not an actual release, it just bump up the master version so that it's larger than any known release.
- Bugfix
- Manual test
No.
No.
=> bump 4.1.0-alpha

cmd/src/server.rs, components/test_raftstore/src/server.rs, etc/config-template.toml, src/raftstore/store/fsm/apply.rs, src/server/lock_manager/config.rs, src/server/node.rs, src/storage/metrics.rs, src/storage/mod.rs, src/storage/txn/commands.rs, src/storage/txn/mod.rs, src/storage/txn/process.rs, src/storage/txn/scheduler.rs
=> txn: pipelined pessimistic lock

components/engine_traits/src/lib.rs
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>
Fix a typo.
- No code
=> engine_traits: fix typo

CHANGELOG.md
=> bump v3.0.5-hotfix

src/bin/util/setup.rs
Fix missing logs by using `OverflowStrategy::Block` strategy.
N/A
Yes
No.
=> bin: slog use block strategy

README.md
Signed-off-by: zhaoyixuan <johnsonqrr@gmail.com>
change readme since the old `build_tikv_master` job is abandoned.
- No code
=> readme: update build job badge url

tests/Cargo.toml, tests/failpoints/cases/test_bootstrap.rs, tests/failpoints/cases/test_gc_worker.rs, tests/failpoints/cases/test_merge.rs, tests/failpoints/cases/test_replica_read.rs, tests/failpoints/cases/test_split_region.rs, tests/failpoints/cases/test_storage.rs, tests/failpoints/cases/test_transfer_leader.rs
#6583 adds extra features that are not enabled by Makefile. This PR makes those features as default test features to enable all tests.
- Bugfix
- Manual test
No
No
#6583
=> fix test target

src/raftstore/store/fsm/apply.rs, src/raftstore/store/metrics.rs, src/raftstore/store/peer.rs, src/storage/metrics.rs, src/storage/mod.rs
I add some metric to help us better to evaluate how we batch `BatchGetCommand` and `RaftCommand`.
- No code
No
=> Metric about batch.

Cargo.lock, src/server/lock_manager/waiter_manager.rs, src/server/service/kv.rs, src/storage/mod.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/txn.rs, src/storage/txn/commands.rs, src/storage/txn/mod.rs, src/storage/txn/process.rs, src/storage/txn/scheduler.rs, src/storage/types.rs, tests/integrations/raftstore/test_service.rs
Pessimistic lock returns mutliple values if no error.
=> txn: pessimistic lock returns multiple values

components/raftstore/src/store/fsm/apply.rs
Close #6649.
- Improvement
- Manual test
No.
No.
#6649
=> apply/yield: remove unnecessary log

src/storage/mvcc/reader/scanner/forward.rs
cherry pick #6655 to release-3.1
- Unit test
=> cherry pick #6655 to release-3.1

CHANGELOG.md, Cargo.lock, Cargo.toml
=> bump v3.0.10

components/tidb_query/src/codec/collation/mod.rs, components/tidb_query/src/codec/collation/utf8mb4.rs, components/tidb_query/src/codec/data_type/scalar.rs
Implement Collator::sort_hash()
- Unit test
=> tidb_query: Implement Collator::sort_hash()

CHANGELOG.md, Cargo.lock, Cargo.toml
Bump version v4.0.0-beta.1
- Unit test
No
No
=> Bump v4.0.0-beta.1

src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, tests/integrations/raftstore/test_replica_read.rs
Pick https://github.com/tikv/tikv/pull/6648
- Unit test
=> raftstore: wake up hibernated leader after failed read index (#6648)

components/test_raftstore/src/transport_simulate.rs, components/test_raftstore/src/util.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, tests/integrations/raftstore/mod.rs, tests/integrations/raftstore/test_hibernate.rs
Pick #6672.
- Bugfix
Yes.
No.
#6672.
=> raftstore/hibernate: wake up for more cases (#6672)

src/raftstore/store/peer.rs, tests/integrations/raftstore/test_hibernate.rs
Pick #6736.
- Bugfix
Yes.
No.
#6736.
=> raftstore/hibernate: wake up on proposal (#6736)

components/test_raftstore/src/transport_simulate.rs, components/test_raftstore/src/util.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, tests/integrations/raftstore/mod.rs, tests/integrations/raftstore/test_hibernate.rs
Pick #6672 and #6736.
- Bugfix
Yes.
No.
#6672.
=> pick #6672 and #6736

cmd/src/bin/tikv-server.rs
Update explanation of `enable-dynamic-config` to the same as PD.
- No code
No
No
=> tikv-server: update explanation of enable-dynamic-config

Cargo.lock, components/raftstore/src/store/config.rs, components/raftstore/src/store/fsm/apply.rs, components/raftstore/src/store/peer_storage.rs, src/config.rs, tests/integrations/config/mod.rs
Add multi batch write for rocksdb. It could make write task more 
- Unit test
No
No
=> multi batch write

components/test_util/src/logging.rs, components/tikv_util/src/logger/mod.rs
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>
Refine some slog relate code.
cargo test --all --no-run
=> tikv_util: refine some slog relate code

CHANGELOG.md, Cargo.lock, Cargo.toml
=> *: bump v3.0.11

cmd/src/bin/tikv-server.rs, cmd/src/server.rs, cmd/src/setup.rs, src/config.rs, tests/integrations/config/dynamic/raftstore.rs
Enable dynamic config by default
No
No
=> config: enable dynamic config by default

CHANGELOG.md
=> *: bump v3.0.5-hotfix

components/tikv_alloc/README.md, components/tikv_alloc/src/error.rs, components/tikv_alloc/src/jemalloc.rs, src/server/status_server.rs
Remove unwrap and refine readme.
- Unit test
#6717
=> tikv_alloc: remove unwrap and refine README.md

CHANGELOG.md, Cargo.lock, Cargo.toml
Bump v3.1.0-beta.2
- Unit test
=> Bump v3.1.0-beta.2

Cargo.lock, src/config.rs, tests/integrations/config/mod.rs
Use merge-operator for titan-gc instead of callback, which could reduce effect to write by apply thread.
- No code
No
No
=> enable merge operator

Cargo.lock, src/server/service/kv.rs, src/storage/mod.rs, src/storage/mvcc/lock.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/txn.rs
cherry-pick #6715 to 3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tikv/tikv/7054)
=> txn: check keys must be not exists (#6715)

components/tikv_util/benches/channel/bench_channel.rs, components/tikv_util/src/mpsc/batch.rs, src/server/raft_client.rs, src/server/service/kv.rs, tests/integrations/server/raft_client.rs
=> raft_client: limit batch size (#6993)

components/tikv_util/benches/channel/bench_channel.rs, components/tikv_util/src/mpsc/batch.rs, src/server/raft_client.rs, src/server/service/kv.rs, tests/integrations/server/raft_client.rs
=> raft_client: limit batch size (#6993) (#7076)

components/backup/src/endpoint.rs, components/backup/src/errors.rs, components/backup/src/lib.rs, components/backup/src/writer.rs, components/backup/tests/integrations/test_backup.rs
Signed-off-by: xinhua5 <xinhua5@163.com>
This PR cherry-picks #6308 to release-3.1 branch.
- Unit test
* No
No
=> backup raw kv (#6308)

Cargo.lock, Cargo.toml, src/raftstore/store/peer_storage.rs
Pick #7072 to release-3.1
- Bugfix
Yes.
No.
=> *: update raft to include aggressive flow control

Cargo.lock, Cargo.toml, cmd/Cargo.toml, components/backup/Cargo.toml, components/engine/Cargo.toml, components/engine_rocks/Cargo.toml, components/pd_client/Cargo.toml, components/raftstore/Cargo.toml, components/sst_importer/Cargo.toml, components/tidb_query/Cargo.toml, components/tikv_util/Cargo.toml, tests/Cargo.toml
Signed-off-by: Renkai <gaelookair@gmail.com>
Use patch instead of replace in `Cargo.toml` & update Prometheus dependency to use the crate-io version.
- Unit test
No
=> use patch instead of replace

CHANGELOG.md, Cargo.lock, Cargo.toml
=> bump v3.0.12

CHANGELOG.md, Cargo.lock, Cargo.toml
Bump v4.0.0-beta.2
- Unit test
=> Bump v4.0.0-beta.2

Cargo.lock, Cargo.toml, components/cop_datatype/Cargo.toml, components/test_coprocessor/Cargo.toml, components/tipb_helper/Cargo.toml
This PR pins tipb:release-3.0 branch.
- Unit test
=> [release-3.0] Pin tipb to release-3.0 branch

components/tidb_query/src/batch/executors/top_n_executor.rs, components/tidb_query/src/codec/data_type/scalar.rs
The comparison of unsigned int was not handled before, and now it is added.
- Unit test
=> copr: add unsigned int comparison

Cargo.lock
Update rust-rocksdb with the following changes:
```
c39275a 2020-03-20 yiwu@pingcap.com     update rocksdb and titan
03edd4d 2020-03-19 bupt2013211450@gma.. new multibatch write (#452)
```
Engineering
CI
No
No
=> *: Update rust-rocksdb

etc/config-template.toml, src/config.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-custom.toml
Add configs for level-merge and gc-merge-rewrite
- No code
No
No
=> add titan related configs

cmd/src/server.rs, cmd/src/setup.rs, components/tikv_util/src/logger/mod.rs, src/lib.rs, src/server/service/diagnostics.rs
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>
UCP https://github.com/tikv/tikv/issues/7069
Add support for slow log searching
- Unit test
=> service: Support slow log searching

tests/integrations/raftstore/test_split_region.rs
Empty append can still be sent when MsgHeartbeatResponse is sent before MsgAppendResponse. This PR relaxes the check to make case stable.
Close #7107.
Tests 
Side effects
None.
=> tests: make test-delay-split-region stable

.github/ISSUE_TEMPLATE/development-task.md, .github/pull_request_template.md
Address comment in #7157.
Issue and pull request template.
Tests 
- No code
Side effects
- No
No
=> .github: update issue and pull request template

MAINTAINERS.md
This PR proposes to add [fredchenbj](https://github.com/fredchenbj) (Fu Chen) as a TIKV maintainer.
Chen Fu is a distributed storage engineer at Yidian Zixun,  an interest-oriented mobile news aggregator company in China. At present, TiKV has been widely used online in Yidian Zixun, with more than 10 clusters and more than 100 machines, covering the company’s core data storage and online services such as user persona and algorithm model. 
In order to be compatible with the existing business access interface, and to improve the performance of cluster access and the efficiency of cluster operation and maintenance, Chen Fu has optimized the function of TiKV in many aspects, including:
- Implement the update interface through RocksDB merge and implement the tikv-proxy component based on TiKV …
=> MAINTAINERS: add Fu Chen as TiKV maintainer

components/cop_datatype/src/def/field_type.rs, src/coprocessor/codec/data_type/scalar.rs, src/coprocessor/dag/batch/executors/top_n_executor.rs
Signed-off-by: zhongzc zhongzc_arch@outlook.com
cherry-pick: #7175
=> tidb_query: fix TopN comparison for release 3.1

components/cop_datatype/src/def/field_type.rs, src/coprocessor/codec/data_type/scalar.rs, src/coprocessor/dag/batch/executors/top_n_executor.rs
What have you changed?
cherry-pick: #7175
=> tidb_query: fix TopN comparison for release 3.0

Cargo.lock, src/import/errors.rs, src/import/sst_service.rs, src/server/status_server.rs, tests/integrations/import/sst_service.rs, tests/integrations/storage/test_raftkv.rs
N/A
Pick https://github.com/tikv/tikv/pull/7126
N/A
Tests 
- Unit test
N/A
=> sst_importer: add error field to DownloadResponse

src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, tests/failpoints/cases/test_replica_read.rs
Pick #7230. 
No.
- Unit test
Side effects
No.
Fix corner cases that replicate read will be delayed by applying snapshot
=> raftstore: apply read after snapshot (#7230)

Cargo.lock, Cargo.toml, components/tidb_query_common/Cargo.toml, components/tidb_query_vec_expr/Cargo.toml
See https://github.com/tikv/rust-prometheus/issues/312.
https://github.com/tikv/rust-prometheus/pull/311
Tests 
- Unit test
Side effects
No.
=> *: update prometheus to fix test coredump

Cargo.lock, components/raftstore/src/store/peer.rs, tests/integrations/raftstore/test_multi.rs
Issue Number: close #6670 
Update raft-rs to use aggressive flow control.
#7072.
Tests 
- Unit test
Make follower catch up logs more aggressively
=> *: update raft-rs to use aggressive flow control

Cargo.lock, components/backup/Cargo.toml, components/backup/src/endpoint.rs, components/backup/src/lib.rs, components/backup/src/service.rs, components/backup/tests/integrations/test_backup.rs, components/external_storage/Cargo.toml, components/external_storage/examples/scli.rs, components/external_storage/src/lib.rs, components/external_storage/src/local.rs, components/external_storage/src/noop.rs, components/external_storage/src/s3.rs, components/external_storage/src/util.rs, components/rusoto_util/Cargo.toml, components/rusoto_util/src/lib.rs, components/sst_importer/src/sst_importer.rs, components/tikv_util/src/file.rs, scripts/check-bins.py
Problem Summary: Cherry-pick recent bugfix to release-4.0
* Speed up backup by release lock as soon as possible.
* Support AWS IAM web identity.
* Fix panic issue of S3 external storage.
=> Rollup backup & restore commits

components/backup/src/endpoint.rs, components/engine/src/iterable.rs, components/raftstore/src/store/region_snapshot.rs, src/server/debug.rs, src/server/raftkv.rs, src/storage/kv/btree_engine.rs, src/storage/kv/cursor.rs, src/storage/kv/mod.rs, src/storage/kv/rocksdb_engine.rs, src/storage/mod.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/reader/scanner/mod.rs, src/storage/txn/store.rs, tests/integrations/storage/test_raftkv.rs
Part of https://github.com/tikv/tikv/issues/6402
Dismantling engine crate
Just removing code.
Tests 
Just type checking.
Side effects
None
=> Remove iterator code from engine crate

components/tikv_util/src/security.rs
Security: work around race condition between threads updating handshakers
pick #7251 
close #7209
=> Cherry-Pick #7251

CHANGELOG.md, Cargo.lock, Cargo.toml
=> *: bump v3.1.0-rc

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump v4.0.0-rc

components/tidb_query_vec_expr/src/lib.rs
Problem Summary: https://github.com/tikv/tikv/pull/7084 removed some signatures by mistake.
What's Changed: Add back removed signatures.
Tests 
=> copr: Add back missing signatures

cmd/src/server.rs
fix lifetime bug for lock file caused by refactoring
Store lock file object into Tikvserver
NO
Tests 
NO
Side effects
NO
NO
=> Protect correct lifetime for lock file

components/cdc/src/delegate.rs, components/cdc/src/endpoint.rs, components/cdc/src/lib.rs, components/cdc/tests/failpoints/test_register.rs, components/cdc/tests/integrations/test_cdc.rs, components/raftstore/src/store/fsm/apply.rs, components/raftstore/src/store/fsm/peer.rs, components/raftstore/src/store/msg.rs, components/resolved_ts/src/lib.rs
Pick https://github.com/tikv/tikv/pull/7233 https://github.com/tikv/tikv/pull/7390 
Tests 
- Unit test
N/A
=> [Cherry-pick] rollup of cdc commits

CHANGELOG.md, Cargo.lock, Cargo.toml
=> *: bump v3.1.0 ga

src/raftstore/store/fsm/apply.rs, src/raftstore/store/fsm/store.rs, tests/integrations/raftstore/test_merge.rs
cherry-pick #7444 and #7416 to release 3.0
=> raftstore: cherry-pick #7444 and #7416 to release 3.0

src/raftstore/store/fsm/apply.rs, tests/integrations/raftstore/test_merge.rs
cherry-pick #7444 to v3.0.12.hotfix
=> raftstore: check state after resuming apply fsm

Cargo.lock
This fixes some undefined behavior, but there's probably no practical impact.
See https://github.com/dtolnay/ryu/issues/24
=> *: update ryu to 1.0.4

src/server/service/diagnostics.rs
Signed-off-by: crazycs <crazycs520@gmail.com>
cherry-pick #7487 to release-4.0
=> diagnose: fix disk used percent information (#7487)

components/configuration/src/lib.rs, components/engine/src/rocks/util/config.rs, components/tikv_util/src/config.rs, components/tikv_util/src/lib.rs, src/config.rs, tests/integrations/config/test_config_client.rs
Write the updated config to the original config file, except the updated config, no other content of the config file will change.
Tests 
- Unit test
TODO:
- add more tests
=> config: write config change to config file

CONTRIBUTING.md
Problem Summary: The documentation points to an incorrect label for help wanted issues. This fixes the link to a search with new label.
N/A
N/A
=> CONTRIBUTING: update help wanted issues label

components/engine/src/rocks/util/engine_metrics.rs, components/engine_rocks/src/rocks_metrics.rs, components/raftstore/src/store/peer.rs
Fix several typos
Tests 
- No code
=> *: fix several typos

Cargo.lock, Cargo.toml, cmd/src/bin/tikv-ctl.rs, cmd/src/server.rs, components/pd_client/src/client.rs, components/test_raftstore/src/node.rs, components/test_raftstore/src/server.rs, etc/config-template.toml, src/config.rs, src/server/debug.rs, src/server/service/debug.rs, src/server/status_server.rs, tests/integrations/config/dynamic/gc_worker.rs, tests/integrations/config/dynamic/pessimistic_txn.rs, tests/integrations/config/dynamic/raftstore.rs, tests/integrations/config/dynamic/split_check.rs, tests/integrations/config/test_config_client.rs
This pr do two things:
- register the status server address to pd
- make tikv-ctl can dynamically modify tikv config
Tests 
- Manual test
=> config: update config through tikv-ctl

CHANGELOG.md, Cargo.lock, Cargo.toml
Bump version v4.0.0-rc.1
Tests 
- Unit test
=> Bump version v4.0.0-rc.1

Cargo.lock, components/tidb_query_normal_expr/Cargo.toml, components/tidb_query_normal_expr/src/builtin_string.rs, components/tidb_query_shared_expr/Cargo.toml, components/tidb_query_shared_expr/src/string.rs, components/tidb_query_vec_expr/Cargo.toml, components/tidb_query_vec_expr/src/impl_string.rs, components/tidb_query_vec_expr/src/lib.rs
- Migrated scalar function `ToBase64` from TiDB
- Unit test
N/A
N/A
resolve #6956
UCP: #6956
N/A
N/A
=> copr: Migrate scalar function `ToBase64` from TiDB

components/configuration/src/lib.rs, components/raftstore/src/coprocessor/config.rs, components/raftstore/src/store/config.rs, components/raftstore/src/store/worker/split_config.rs, src/config.rs, src/server/gc_worker/config.rs, src/server/lock_manager/config.rs
=> config: remove unused code

.github/workflows/assign_sig_project.yml
Assign issues to SIG project automatically
Assign issues to SIG project automatically
- No
- No code
Side effects
- No
=> Assign issues to SIG project automatically

CHANGELOG.md, Cargo.lock, Cargo.toml
=> update change logs and bump to 3.0.14

components/tidb_query_normal_expr/src/builtin_string.rs, components/tidb_query_shared_expr/src/string.rs, components/tidb_query_vec_expr/src/impl_string.rs, components/tidb_query_vec_expr/src/lib.rs
Signed-off-by: Alex Chi iskyzh@gmail.com
UCP #6933
Checklist #5751
Issue Number: close #6933 
Problem Summary: add vectorized FromBase64
* Add vectorized FromBase64
* Move `strip_whitespace` to `tidb_query_shared_expr`
Unit tested.
=> copr: Add vectorized FromBase64

metrics/grafana/tikv_details.json
cherry-pick #7754 to release-4.0
---
close #7520 
Update grafana json file to add encryption panel
Tests 
- No code
- Add encryption panel into grafana template
=> encryption: Update grafana json file to add encryption panel (#7754)

docs/adopters.md
Signed-off-by: Wenting Liu <liuwenting@pingcap.com>
This PR is related to https://github.com/tikv/tikv/pull/7464 and https://github.com/tikv/tikv/pull/7789.  I wrongly deleted my repo so those two could not be merged.
Tests 
- Unit test
- No code
Side effects
=> update TiKV adopters list

CHANGELOG.md, Cargo.lock, Cargo.toml
Bumps version v4.0.0-rc.2
Tests 
- No code
=> Bump version v4.0.0-rc.2

CHANGELOG.md, Cargo.lock, Cargo.toml
Bumps version v4.0.0-ga
Tests 
- No code
=> Bump version v4.0.0-ga

Cargo.lock, components/raftstore/Cargo.toml, components/tidb_query_common/Cargo.toml, components/tidb_query_normal_expr/Cargo.toml, components/tidb_query_shared_expr/Cargo.toml, components/tidb_query_vec_executors/Cargo.toml, components/tidb_query_vec_expr/Cargo.toml, components/tikv_util/Cargo.toml, tests/Cargo.toml, tests/integrations/server/status_server.rs
There are many duplicated dependencies in the dependency graph, which may result in longer compilation time and larger compilation output
update some outdated dependencies
Tests 
- Manual test
Side effects
- None
=> *: prune some duplicated dependencies

components/engine_rocks/src/rocks_metrics.rs
Fix missing titan histogram metrics.
The related code is removed by mistake when resolving conflicts in https://github.com/tikv/tikv/pull/6328, so add it back.
- Fix missing titan histogram metrics
=> Fix missing titan histogram metrics

cmd/src/bin/tikv-ctl.rs, src/server/debug.rs
Support `get_range_properties`.
Tests 
Side effects
=> tikv-ctl: add get_range_properties

components/tidb_query_vec_expr/src/impl_string.rs
Signed-off-by: zhongyang.wu <zhongyang.wu@outlook.com>
Issue Number: close #6946 
Add vectorized function `quote`
Tests 
- Unit test
=> copr: Add vectorized quote function.

CHANGELOG.md, Cargo.lock, Cargo.toml
Bump version v3.1.2
Tests 
- No code
* N/A
=> Bump version v3.1.2

CHANGELOG.md, Cargo.lock, Cargo.toml
Bumps version v3.0.15
Tests 
- No code
* N/A
=> Bump version v3.0.15

.github/workflows/assign_feature_requests.yml
…ects
Automatically assign feature requests to the specified project.
Add GitHub workflow.
- None
- No code
Side effects
- None
=> GitHub workflow: automatically assign feature requests to the specified project

components/tidb_query_vec_expr/src/impl_time.rs, components/tidb_query_vec_expr/src/lib.rs
Signed-off-by: Bartosz Podkanowicz <podkanowicz.bartosz@gmail.com>
vectorize function make_date
Tests 
- Unit test
=> copr: add vectorized make_date

components/tidb_query_vec_aggr/src/impl_max_min.rs
Make it zero cost for the abstraction of MIN / MAX
What's Changed: Make MIN / MAX a generic parameter.
Tests 
- Unit test
(no need)
=> Zero cost MIN / MAX abstraction

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump version v4.0.1

Cargo.lock, components/external_storage/Cargo.toml, components/external_storage/examples/scli.rs, components/external_storage/src/lib.rs, components/external_storage/src/util.rs
The PR #6283 has not been completely cherry-picked to release-4.0. This PR picks the remaining changes.
Tests 
- Unit test
Side effects
- Support GCS destination for backup and restore.
=> external_storage: add GCS support (#6283)

Cargo.lock, components/engine_rocks/src/rocks_metrics.rs
cherry-pick #7943 to release-4.0
---
Fix missing titan histogram metrics.
The related code is removed by mistake when resolving conflicts in https://github.com/tikv/tikv/pull/6328, so add it back.
- Fix missing titan histogram metrics
=> Fix missing titan histogram metrics (#7943)

README.md
Signed-off-by: Wenting Liu <liuwenting@pingcap.com>
update the community meeting video link
Tests 
- Unit test
- No code
Side effects
=> change community meeting video link

Cargo.lock, Cargo.toml, components/tikv_util/Cargo.toml, components/tikv_util/src/trace.rs
Signed-off-by: Renkai <gaelookair@gmail.com>
Bump to `minitrace-rust`
=> bump to minitrace-rust

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump version v4.0.2

CHANGELOG.md, Cargo.lock, Cargo.toml
=> *: bump to 3.0.16
