- src/lib.rs
- src/pd/client.rs
- src/pd/errors.rs
- src/pd/protocol.rs
- src/raft/errors.rs
- src/raft/raw_node.rs
- src/raftstore/errors.rs
- src/raftstore/mod.rs
- src/raftstore/store/bootstrap.rs
- src/raftstore/store/config.rs
- src/raftstore/store/engine.rs
- src/raftstore/store/keys.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/server/errors.rs
- src/server/kv.rs
- src/server/mod.rs
- src/server/node.rs
- src/server/server.rs
- src/server/transport.rs
- src/storage/engine/raftkv.rs
- src/storage/mod.rs
- src/util/macros.rs
- src/util/mod.rs
- tests/raftstore/node.rs
- tests/raftstore/pd.rs
> *: introduce box_err

- src/bin/tikv-server.rs
- src/raftstore/store/mod.rs
- src/raftstore/store/transport.rs
- src/server/conn.rs
- src/server/mod.rs
- src/server/node.rs
- src/server/server.rs
- src/server/transport.rs
- src/storage/engine/raftkv.rs
- tests/raftstore/node.rs
- tests/raftstore/server.rs
> *: clear Transport trait, and split with another RaftHandler trait.

- src/raftstore/coprocessor/dispatcher.rs
- src/raftstore/coprocessor/error.rs
- src/raftstore/coprocessor/mod.rs
- src/raftstore/coprocessor/split_observer.rs
- src/raftstore/errors.rs
- src/raftstore/store/peer.rs
- tests/raftstore/test_split_region.rs
> coprocessor: add error to coprocessor

- src/lib.rs
- src/raft/raft_log.rs
- src/util/macros.rs
- src/util/mod.rs
- src/util/panic_hook.rs
- tests/test_raft.rs
> *: Skip printing stracktrace when using panic::recover

- .travis.yml
cache rocksdb to speed up ci check.
> ci: cache rocksdb at travis build

- README.md
Add a note in README.md to state clearly about the rust version used.
> State clearly about the rust version

- Cargo.lock
- src/raft/raft_log.rs
- src/raft/storage.rs
- src/raftstore/coprocessor/dispatcher.rs
- src/raftstore/coprocessor/split_observer.rs
- src/raftstore/store/keys.rs
- tests/raftstore/cluster.rs
- tests/raftstore/test_compact_log.rs
- tests/raftstore/test_single.rs
- tests/test_raft.rs
- tests/test_raft_paper.rs
- tests/util.rs
bump rustc to `1.9.0-nightly (5ab11d72c 2016-04-02)`
> *: update rustc, libraries and fix clippy warnings

- Cargo.lock
- Makefile
- src/raftstore/store/peer.rs
- src/storage/engine/raftkv.rs
- tests/raftstore/cluster.rs
> storage: add epoch to raftkv

- src/pd/errors.rs
- src/raft/errors.rs
- src/storage/engine/mod.rs
- src/util/codec/mod.rs
For displaying detail message when unwrap result.
> error: Add missing display method.

- benches/channel/bench_channel.rs
- src/bin/tikv-server.rs
- src/raft/raft_log.rs
- src/raftstore/store/engine.rs
- src/raftstore/store/msg.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/raftstore/store/transport.rs
- src/server/server.rs
- src/storage/mod.rs
- src/storage/txn/scheduler.rs
- src/storage/txn/store.rs
- tests/raftstore/cluster.rs
- tests/test_raft.rs
find -name '*.rs' -type f | xargs rustfmt
> Update to latest rustfmt.

- src/util/codec/mod.rs
- src/util/codec/number.rs
> util: add number codec

- src/util/codec/mod.rs
- src/util/codec/number.rs
> util: add var int codecs

- src/util/codec/bytes.rs
@ngaut @qiuyesuifeng @coocood PTAL
> util: add compact bytes codec

- src/pd/client.rs
> pd: extract a function for post msg.

- src/util/codec/mod.rs
- src/util/codec/table.rs
> util: add table codec

- src/pd/client.rs
> pd: support pd list.

- src/server/node.rs
- src/storage/mod.rs
> *: add name for thread.

- Dockerfile
- docker/rust_dockerfile
> *: add docker support.

- tests/raftstore/test_conf_change.rs
- tests/raftstore/util.rs
> tests: fix tests exit failure

- .travis.yml
- Cargo.lock
- Cargo.toml
- Makefile
- benches/benches.rs
- benches/bin/bench-tikv.rs
- src/bin/tikv-server.rs
- src/lib.rs
- tests/tests.rs
> *: add dev feature including clippy.

- Cargo.lock
- src/bin/tikv-server.rs
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/store/peer.rs
- src/server/node.rs
- src/storage/engine/raftkv.rs
- src/storage/mod.rs
- tests/raftstore/server.rs
> [DNM] raftkv: add raftkv snapshot

- src/server/server.rs
- src/util/mod.rs
> *: support to_socket_addr.

- src/util/codec/datum.rs
- src/util/mod.rs
- src/util/xeval/evaluator.rs
- src/util/xeval/mod.rs
> util: add xval

- src/server/kv.rs
- src/storage/engine/mod.rs
- src/storage/mod.rs
- src/storage/mvcc/txn.rs
> [DNM]refactor not leader

- Makefile
> Makefile: make release.

- src/server/kv.rs
- src/storage/engine/mod.rs
> [DNM]return right Request Error

- src/pd/client.rs
> pd: use max retry for sending msg.

- Cargo.lock
- src/server/kv.rs
- src/storage/mod.rs
- src/storage/txn/scheduler.rs
- src/storage/txn/store.rs
@morefreeze @ngaut @siddontang
> storage: batch get command

- Cargo.lock
- src/server/coprocessor.rs
- src/server/mod.rs
- src/server/server.rs
- src/util/codec/datum.rs
- src/util/codec/table.rs
- src/util/xeval/evaluator.rs
- src/util/xeval/mod.rs
> [DNM] add push implement

- Dockerfile
> Dockerfile: use cargo clean instead.

- src/server/coprocessor.rs
- src/server/kv.rs
> kvprc: add key in LockInfo

- src/util/xeval/evaluator.rs
@ngaut @qiuyesuifeng @coocood PTAL
> util: fix and/or with null

- src/raftstore/store/peer_storage.rs
> peer_storage: Log snapshot size and key count.

- src/storage/engine/raftkv.rs
> transport: add timeout

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> store: add some log.

- src/util/xeval/evaluator.rs
> util: support eval_not

- src/raft/raft_log.rs
> raft: fix wrong slice

- src/raftstore/store/mod.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/mod.rs
- src/raftstore/store/worker/snap.rs
- src/raftstore/store/worker/split_check.rs
> raftstore: make snapshot async

- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/compact.rs
- src/raftstore/store/worker/mod.rs
- src/util/xeval/evaluator.rs
- tests/raftstore/test_compact_log.rs
> raftstore: make compact async

- src/bin/tikv-server.rs
> tikv-server: change rocksdb option block_size and target_file_size_base

- src/pd/client.rs
> pd: fix retry

- .travis.yml
- Cargo.lock
- Cargo.toml
- Makefile
- src/bin/tikv-server.rs
- src/lib.rs
- tests/tests.rs
> ci: fix ci on mac

- src/bin/tikv-server.rs
- src/util/codec/datum.rs
- src/util/codec/mod.rs
- src/util/xeval/evaluator.rs
> util: support simple like

- src/server/mod.rs
- src/server/resolve.rs
- src/server/server.rs
- src/server/transport.rs
> server: asynchronous host resolving.

- src/raftstore/store/store.rs
> store: reject stale RequestVote.

- src/server/server.rs
@ngaut @BusyJay 
Now sometimes ci for mac may hang up, and I also meet this in my mac because of resolving localhost failed, it is very strange. 
So we use try_recv and wait a little time to avoid blocking.
> server: fix ci hangup in mac.

- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/storage/mvcc/txn.rs
- src/util/xeval/evaluator.rs
> *: make newest rustfmt happy

- Cargo.lock
- src/lib.rs
- src/util/macros.rs
- tests/tests.rs
bump rustc to `rustc 1.10.0-nightly (576229fea 2016-04-15)`
> *: update rust

- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- tests/raftstore/node.rs
- tests/raftstore/test_split_region.rs
Try to fix https://github.com/pingcap/tikv/issues/413
> *: handle uninitialized peer when splitting

- benches/benches.rs
- benches/bin/bench-tikv.rs
- tests/coprocessor/mod.rs
- tests/coprocessor/test_select.rs
- tests/tests.rs
- tests/util.rs
@ngaut @qiuyesuifeng @coocood PTAL
> coprocessor: add endpoint tests

- src/raftstore/store/worker/compact.rs
- src/raftstore/store/worker/mod.rs
- src/raftstore/store/worker/snap.rs
- src/raftstore/store/worker/split_check.rs
- src/util/panic_hook.rs
> *: add missing license. [ci skip]

- src/raft/status.rs
- src/raftstore/store/config.rs
- src/raftstore/store/store.rs
- tests/raftstore/cluster.rs
- tests/raftstore/test_compact_log.rs
@ngaut @siddontang PTAL
close #424
> raftstore: only compact replicated log

- Cargo.lock
- src/bin/tikv-server.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/server/coprocessor.rs
- disable snappy compression
- add some perf metrics
> [DNM] *: tiny cleanup

- src/bin/tikv-server.rs
> bin: Fix compile.

- src/raftstore/store/store.rs
- tests/raftstore/test_tombstone.rs
> *: update stale message check.

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/util.rs
> handle execute ready results after removing itself

- src/raftstore/errors.rs
- src/raftstore/store/keys.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/worker/split_check.rs
- src/server/coprocessor.rs
- src/server/kv.rs
- src/storage/engine/memory.rs
- src/storage/engine/rocksdb.rs
- src/storage/mod.rs
- src/storage/mvcc/mod.rs
- src/storage/types.rs
- src/util/codec/table.rs
- src/util/mod.rs
- tests/raftstore/pd_ask.rs
> *: make byte array readable

- src/server/coprocessor.rs
- src/util/codec/datum.rs
- src/util/mod.rs
- src/util/xeval/evaluator.rs
- tests/coprocessor/test_select.rs
@ngaut @qiuyesuifeng @coocood PTAL
> copr: support filter before select

- Cargo.lock
- src/server/kv.rs
- src/storage/engine/mod.rs
- src/storage/mod.rs
- src/storage/mvcc/mod.rs
- src/storage/txn/mod.rs
@siddontang @ngaut @morefreeze
> *: update kvrpc response

- Cargo.lock
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/store/engine.rs
- src/storage/engine/rocksdb.rs
> raftstore: update iterator signature

- src/raftstore/store/msg.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/server/conn.rs
- src/server/mod.rs
- src/server/resolve.rs
- src/server/server.rs
- src/server/transport.rs
Fix #442 
Now origin test can covers this, I will add more tests later. 
> *: use another connection for snapshot.

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> raftstore: fix stale leader check

- src/raftstore/store/store.rs
If schedule quickly run, the snap status will be set SnapState::Snap first, and then changed to SnapState::Generating, so we can't do any snapshot later. 
We must set SnapState::Generating before schedule.
Notice: this can't fix whole ci.
> store: fix snap status set order.

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/server/coprocessor.rs
- src/server/server.rs
- tests/coprocessor/test_select.rs
> corp: use thread pool to execute pushdown

- src/raftstore/store/peer.rs
> store: open check quorum default.

- Cargo.lock
- Cargo.toml
- src/bin/tikv-server.rs
> rocksdb: basic tuning

- src/raftstore/store/store.rs
- src/server/coprocessor.rs
- src/util/macros.rs
- src/util/mod.rs
- tests/raftstore/transport_simulate.rs
> *: use slow log to simplify slow operation log.

- src/raftstore/store/store.rs
> store: split on_ready_result.

- src/util/worker/mod.rs
> worker: use slow timer.

- src/raftstore/coprocessor/region_snapshot.rs
- src/storage/engine/raftkv.rs
> raftkv: implement reverse_seek

- Cargo.lock
- src/util/mod.rs
- src/util/xeval/evaluator.rs
> corp: support in push down

- src/bin/tikv-server.rs
- src/util/mod.rs
- src/util/panic_hook.rs
> *: exit process when panic.

- tests/raftstore/server.rs
> raftstore: convert socket timeout error.

- tests/raftstore/cluster.rs
- tests/raftstore/test_multi.rs
drop packet test case should be fixed, almostly, if not absolutely
some other problem in CI 'may' also be fixed
> tests/raftstore: fix CI

- src/server/resolve.rs
- src/server/server.rs
- tests/raftstore/server.rs
> *: cache store address.

- src/storage/engine/mod.rs
> *: display detailed error message

- src/raft/raft.rs
- tests/test_raft.rs
> *: port Etcd randomized election timeout.

- src/raft/raft.rs
- src/raftstore/store/peer.rs
- log message size before sending
- format as dec instead of hex
> *: adjust log

- src/raftstore/store/cmd_resp.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> raftstore: call stale callback

- Cargo.lock
- Cargo.toml
- Makefile
- src/raftstore/store/store.rs
> *: use newest master mio.

- src/bin/tikv-dump.rs
- src/raftstore/coprocessor/split_observer.rs
- src/raftstore/errors.rs
- src/raftstore/store/keys.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/worker/pd.rs
- src/raftstore/store/worker/split_check.rs
- src/server/coprocessor.rs
- src/server/kv.rs
- src/storage/engine/memory.rs
- src/storage/engine/rocksdb.rs
- src/storage/mvcc/mod.rs
- src/storage/types.rs
- src/util/codec/table.rs
- src/util/mod.rs
- tests/raftstore/pd_ask.rs
> util: implement byte array escape

- tests/raftstore/cluster.rs
- tests/raftstore/test_multi.rs
@ngaut @siddontang @tiancaiamao PTAL
> tests: fix random restart

- src/util/mod.rs
- tests/raftstore/cluster.rs
- tests/raftstore/pd_ask.rs
- tests/raftstore/server.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/test_multi.rs
- tests/raftstore/test_split_region.rs
> *: resolve several compile warnings and ci errors

- src/raft/raft.rs
- tests/test_raft.rs
- tests/test_raft_paper.rs
> raft: fix occasionally panic test case

- src/raftstore/store/msg.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/split_check.rs
> store: check epoch in split check result.

- src/raftstore/store/peer.rs
> store: atomically committing and changing storage.

- tests/raftstore/cluster.rs
`leader_of_region` may get None when the region has only one peer but we start more than one nodes.
> tests: fix `leader_of_region`

- src/raftstore/store/msg.rs
- src/storage/engine/raftkv.rs
- src/util/event.rs
- src/util/mod.rs
> util: introduce Event

- src/raftstore/store/store.rs
We should drop the invalid message.
> store: fix panic.

- src/server/kv.rs
> kvserver: return more specific error to ticlient

- src/server/kv.rs
> *: fix ci failure

- src/lib.rs
- src/raftstore/store/msg.rs
- src/storage/engine/raftkv.rs
- src/util/event.rs
> raftkv: make snapshot consistent

- Cargo.lock
- Cargo.toml
- etc/config-template.toml
- src/bin/tikv-server.rs
> bin, etc: support config file.

- src/server/coprocessor.rs
- src/util/codec/datum.rs
- src/util/xeval/evaluator.rs
@ngaut @siddontang @coocood  PTAL
> corp: fix compare null

- src/raftstore/store/config.rs
- src/raftstore/store/msg.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/pd.rs
- src/server/node.rs
- tests/raftstore/mod.rs
- tests/raftstore/test_pd.rs
> *: heart beat pd with PutStore protocol.

- src/lib.rs
- src/util/event.rs
> util: fix event dead lock

- src/raft/log_unstable.rs
- src/raft/raft.rs
- src/raft/raft_log.rs
- src/raft/storage.rs
> raft: clean up

- tests/raftstore/cluster.rs
- tests/raftstore/test_conf_change.rs
> tests: avoid remove probe

- src/server/coprocessor.rs
> coprocessor: Add time consume logs

- src/util/codec/datum.rs
- src/util/codec/number.rs
- src/util/xeval/evaluator.rs
@ngaut @siddontang @coocood PTAL
cc #535
> codec: support float

- Cargo.lock
- Cargo.toml
- src/pd/client.rs
- src/server/mod.rs
For https://github.com/pingcap/kvproto/pull/55
https://github.com/pingcap/pd/pull/98
@ngaut @disksing @qiuyesuifeng
> wrap pd request/response

- src/server/kv.rs
@ngaut @morefreeze @BusyJay PTAL
> kvserver: enumerate all possible paths to extract region error.

- src/bin/tikv-server.rs
- src/server/node.rs
- src/server/transport.rs
- src/storage/engine/raftkv.rs
- src/storage/txn/store.rs
- tests/raftstore/node.rs
- tests/raftstore/server.rs
1. Create EventLoop outer like server, so that we can get the channel directly.
2. Simplify and clean up. 
This change is for following Http refactor.
For @ngaut @BusyJay @disksing @tiancaiamao
> create event loop outer for store. 

- src/raftstore/coprocessor/split_observer.rs
- src/storage/txn/store.rs
> coprocessor: decode/encode in on_split

- src/server/coprocessor.rs
- src/storage/txn/store.rs
- src/util/codec/table.rs
- tests/coprocessor/test_select.rs
@ngaut @qiuyesuifeng @coocood  PTAL
> corp: support limit and reverse scan

- src/util/codec/datum.rs
- src/util/codec/mod.rs
- src/util/codec/mysql/duration.rs
- src/util/codec/table.rs
> util: simplify InvalidDataType error

- src/bin/tikv-server.rs
- src/pd/client.rs
- src/pd/mod.rs
- src/pd/protocol.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/pd.rs
- src/server/node.rs
- src/server/resolve.rs
- tests/raftstore/cluster.rs
- tests/raftstore/node.rs
- tests/raftstore/pd.rs
- tests/raftstore/pd_ask.rs
- tests/raftstore/server.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/test_pd.rs
- tests/raftstore/test_split_region.rs
- tests/raftstore/test_tombstone.rs
> *: cleanup pd interface, remove cluster id.

- src/raft/raft.rs
keep sync with etcd
https://github.com/coreos/etcd/pull/5313/files /cc @xiang90 
@siddontang @BusyJay @ngaut
> raft: simplify leadership transfer

- Cargo.lock
- Cargo.toml
- src/pd/protocol.rs
@ngaut @qiuyesuifeng @disksing @tiancaiamao
> *: cleanup pd

- tests/raftstore/test_compact_log.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/test_multi.rs
- tests/raftstore/test_tombstone.rs
- tests/test_raft.rs
- tests/test_raw_node.rs
> *: update with newest rustfmt.

- src/raftstore/coprocessor/split_observer.rs
- src/storage/engine/mod.rs
- src/storage/types.rs
- src/util/codec/bytes.rs
- src/util/codec/datum.rs
@ngaut @disksing @coocood  PTAL
> codec: add desc bytes encoding

- benches/benches.rs
- benches/bin/mvcc.rs
- src/storage/mvcc/meta.rs
- src/storage/mvcc/mod.rs
- src/storage/mvcc/txn.rs
- src/storage/txn/store.rs
- tests/util.rs
A complement for #558 
@BusyJay @ngaut
> *: fix ts generators in tests

- src/server/coprocessor.rs
- src/util/codec/mysql/types.rs
> corp: detect handle type

- src/server/coprocessor.rs
- src/util/codec/mysql/types.rs
> corp: add missing type check

- src/server/coprocessor.rs
- src/util/codec/mysql/mod.rs
- src/util/codec/mysql/types.rs
> corp: support omitted nullable value

- src/raft/raft.rs
- tests/test_raft.rs
port from etcd https://github.com/coreos/etcd/pull/5366
> raft: do not panic when removing all the nodes from cluster

- tests/raftstore/cluster.rs
- tests/raftstore/node.rs
- tests/raftstore/server.rs
- tests/raftstore/test_multi.rs
- tests/raftstore/transport_simulate.rs
cluster partition API use vector paremeter
remove transport simulator Strategy and use Filter instead
change transport simulator Filter trait to immutable
and several other changes...
> tests/raftstore: refact api, clean up

- src/util/panic_hook.rs
> util: use Once to initialize panic hook

- Cargo.lock
- Cargo.toml
- src/raftstore/coprocessor/mod.rs
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/errors.rs
- src/raftstore/store/cmd_resp.rs
- src/raftstore/store/engine.rs
- src/storage/engine/mod.rs
- src/storage/engine/raftkv.rs
- src/storage/engine/rocksdb.rs
- src/storage/mod.rs
- src/storage/txn/store.rs
This is the first peer for #540.
@ngaut @disksing PTAL
> [DNM] storage: introduce interator

- Cargo.lock
- Cargo.toml
> deps: fix toml deps

- src/server/coprocessor.rs
- src/util/codec/datum.rs
- src/util/codec/mysql/mod.rs
- src/util/codec/mysql/types.rs
- src/util/xeval/evaluator.rs
> corp: fix duration support

- Cargo.lock
- Cargo.toml
- tests/raftstore/pd.rs
@ngaut @qiuyesuifeng @disksing
> *: number -> count.

- Cargo.lock
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/store/engine.rs
- src/server/coprocessor.rs
- src/storage/engine/mod.rs
- src/storage/engine/raftkv.rs
- src/storage/engine/rocksdb.rs
- src/storage/txn/store.rs
> *: reuse iterator

- .travis.yml
- README.md
- travis-build/Makefile
resolve #602 
@ngaut @siddontang @c4pt0r PTAL
> ci: add coverage support

- etc/config-template.toml
- src/bin/tikv-server.rs
> *: simplify metric use.

- travis-build/Makefile
> ci: only collect coverage data in src

- src/raftstore/store/store.rs
- src/server/node.rs
Ident check has already done in node.
> *: remove unnecessary code.

- src/bin/tikv-server.rs
> *: make rustfmt happy.

- src/util/rocksdb_option.rs
> util: make clippy happy.

- tests/raftstore/cluster.rs
> raftstore: fix get_region after split.

- etc/config-template.toml
- src/bin/tikv-server.rs
> *: only use UDP metric.

- src/server/coprocessor.rs
- src/server/kv.rs
- src/server/server.rs
- src/storage/txn/store.rs
- tests/coprocessor/test_select.rs
> copr: batch handle request

- src/util/worker/mod.rs
> util: make worker test more stable

- src/server/kv.rs
- src/server/server.rs
- src/storage/mod.rs
> server: stop store when exit

- src/raftstore/store/store.rs
- src/raftstore/store/worker/pd.rs
> *: add log for change peer and split.

- etc/config-template.toml
- src/bin/tikv-server.rs
- src/server/coprocessor.rs
- src/util/metric/macros.rs
> copr: add metrics

- Cargo.lock
- src/bin/tikv-server.rs
- tests/raftstore/pd.rs
- tests/raftstore/util.rs
> *: update and fix clippy happy.

- src/raft/raft_log.rs
@ngaut @siddontang @tiancaiamao  PTAL
> raft: fix clippy warning

- src/pd/client.rs
- src/raftstore/store/worker/pd.rs
- src/raftstore/store/worker/snap.rs
- src/raftstore/store/worker/split_check.rs
> *: add metric.

- src/server/coprocessor.rs
- src/storage/engine/mod.rs
- src/storage/mvcc/mod.rs
- src/storage/mvcc/txn.rs
- src/storage/txn/store.rs
- src/storage/types.rs
> *: use iter for get when suitable

- Cargo.lock
- src/bin/tikv-server.rs
> bin: append node id to metric prefix

- src/bin/tikv-server.rs
- src/util/metric/mod.rs
> util, bin: add nonblock udp metric

- Cargo.lock
- src/server/coprocessor.rs
> server: add thread pool name

- src/util/metric/mod.rs
> metric: make clippy happy.

- src/storage/engine/mod.rs
> storage: fix near_seek

- tests/raftstore/pd.rs
@BusyJay @disksing @tiancaiamao
> raftstore: must check in region range

- .travis.yml
> ci: use gcc instead

- src/server/coprocessor.rs
- src/storage/txn/store.rs
- tests/coprocessor/test_select.rs
@siddontang @disksing @coocood PTAL
> copr: fix seek

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/raftstore/store/store.rs
- src/util/fs.rs
- src/util/mod.rs
> *: support get disk capacity and available.

- src/util/worker/mod.rs
- tests/raftstore/server.rs
> ci: fix failed tests

- src/bin/tikv-dump.rs
- src/util/mod.rs
> bin: add scan command

- Cargo.lock
- src/bin/tikv-server.rs
- src/raft/progress.rs
- src/raft/raft.rs
- src/raft/storage.rs
- src/raftstore/store/peer_storage.rs
- src/util/codec/mysql/decimal.rs
- tests/raftstore/transport_simulate.rs
rustc 1.11.0-nightly (12238b984 2016-06-04)
> *: update clippy

- tests/raftstore/test_stats.rs
> raftstrore: fix available check.

- src/util/codec/datum.rs
- src/util/codec/mysql/decimal.rs
@coocood @siddontang @disksing PTAL
> copr: fix decimal

- Cargo.lock
- src/raftstore/store/worker/pd.rs
- tests/raftstore/pd.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/test_transfer_leader.rs
- tests/raftstore/util.rs
@ngaut @disksing @BusyJay @tiancaiamao
> *: support transfer leader heartbeat response.

- src/raftstore/store/worker/pd.rs
> worker: make clippy happy.

- src/raft/raft.rs
- src/raft/raft_log.rs
- tests/raftstore/server.rs
> *: use more verbose panic message

- src/raft/raft.rs
- src/raft/raft_log.rs
> raft: remove redundant function

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> store: add slow log for raft ready and destroy.

- Cargo.lock
Avoid log spam when switch to DEBUG_LEVEL.
> *: bump version of cadence

- src/raftstore/store/store.rs
> store: split long on_raft_message function.

- src/util/fs.rs
> test: only check disk stats change instead

- Cargo.lock
- Cargo.toml
- src/server/coprocessor/aggregate.rs
- src/server/coprocessor/endpoint.rs
- src/server/coprocessor/mod.rs
- src/util/codec/datum.rs
- src/util/xeval/evaluator.rs
- tests/coprocessor/test_select.rs
@shenli @coocood @qiuyesuifeng PTAL
> copr: support count

- src/raftstore/store/peer.rs
- tests/raftstore/node.rs
- tests/raftstore/test_split_region.rs
- tests/raftstore/transport_simulate.rs
- tests/raftstore/util.rs
> add split and overlapped snapshot test, fix node test snapshot send bug. 

- src/server/coprocessor/endpoint.rs
- tests/coprocessor/test_select.rs
> copr: fix aggr detection

- src/server/coprocessor/aggregate.rs
- src/server/coprocessor/endpoint.rs
- tests/coprocessor/test_select.rs
> [DNM]copr: use compact result layout

- etc/config-template.toml
@ngaut @c4pt0r @BusyJay @disksing @tiancaiamao
> etc: default advertise addr should be empty.

- Cargo.lock
- etc/config-template.toml
- src/bin/tikv-server.rs
> bin: rocksdb tuning

- src/server/coprocessor/aggregate.rs
- src/server/coprocessor/endpoint.rs
- tests/coprocessor/test_select.rs
> copr: support FirstRow aggregate

- Cargo.lock
- Cargo.toml
- src/bin/tikv-server.rs
@ngaut @siddontang @c4pt0r PTAL
> bin: merge snap and rocksdb data

- tests/raftstore/cluster.rs
- tests/raftstore/test_compact_log.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/test_multi.rs
- tests/raftstore/test_single.rs
- tests/raftstore/test_split_region.rs
- tests/raftstore/test_stats.rs
- tests/raftstore/test_status_command.rs
- tests/raftstore/test_tombstone.rs
- tests/raftstore/test_transfer_leader.rs
- tests/raftstore/test_transport.rs
- tests/raftstore/util.rs
> raftstore: clean up test.

- tests/raftstore/test_snap.rs
> raftstore: pass compile.

- benches/benches.rs
- benches/bin/bench-tikv.rs
- src/raftstore/store/store.rs
- src/server/coprocessor/endpoint.rs
- src/server/node.rs
- src/storage/mod.rs
- src/util/macros.rs
- src/util/mod.rs
- src/util/worker/mod.rs
- tests/coprocessor/test_select.rs
- tests/raftstore/cluster.rs
- tests/raftstore/pd.rs
- tests/raftstore/test_split_region.rs
- tests/raftstore/test_transfer_leader.rs
- tests/raftstore/test_transport.rs
- tests/raftstore/util.rs
- tests/tests.rs
- tests/util.rs
- travis-build/Makefile
- travis-build/test.sh
@ngaut @siddontang @disksing  PTAL
> ci: show failed cases log

- tests/coprocessor/test_select.rs
- tests/tests.rs
- tests/util.rs
> *: support travis fail log setup

- src/raftstore/store/peer.rs
> store: add ready slow log.

- src/server/server.rs
If we meet error, we should close the connection, not ignore the error and only log it. 
> tiny update

- src/server/server.rs
> server: use debug level for connection error.

- src/raftstore/store/store.rs
> store: log store for report snapshot.

- src/raftstore/store/worker/pd.rs
- tests/raftstore/cluster.rs
- tests/raftstore/pd.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/test_tombstone.rs
> ci: fix several randomly failed cases

- Cargo.lock
- Cargo.toml
- src/raftstore/store/store.rs
> *: remove unused proto.

- Cargo.lock
> update rust and clippy.

- Cargo.lock
- src/raftstore/store/snap.rs
- src/raftstore/store/store.rs
- tests/raftstore/test_stats.rs
- tests/raftstore/transport_simulate.rs
> snapshot statistic

- Cargo.lock
- src/raftstore/store/peer_storage.rs
@ngaut @BusyJay @zhangjinpeng1987
> store: don't write when WriteBatch is empty.

- tests/raftstore/cluster.rs
- tests/raftstore/util.rs
> tests: merge `must_get_equal` and `must_get_none`

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/util/metric/mod.rs
> *: add some metrics and update ready slow log.

- etc/config-template.toml
- src/bin/tikv-server.rs
- src/raftstore/store/config.rs
> *: support region split configuration.

- Cargo.lock
- src/pd/mod.rs
- src/pd/protocol.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/pd.rs
- tests/raftstore/pd.rs
- tests/raftstore/test_split_region.rs
@qiuyesuifeng adds the ReportSplit proto for web UI history operation show. 
> *: support pd report split.

- tests/raftstore/cluster.rs
- tests/raftstore/test_split_region.rs
> tests/raftstore: wait some for split count changed.

- src/server/coprocessor/endpoint.rs
- src/util/codec/bytes.rs
- src/util/codec/datum.rs
- src/util/codec/mysql/decimal.rs
- src/util/codec/mysql/mod.rs
- src/util/codec/table.rs
- tests/coprocessor/test_select.rs
refer: https://github.com/pingcap/tidb/pull/1347
> [DNM] copr: store row data in single kv pair

- README.md
- USAGE.md
@ngaut @BusyJay @disksing @zhangjinpeng1987 
/cc @queenypingcap
> add usage document.

- src/raftstore/store/worker/compact.rs
> worker: disable WAL for compact log.

- src/storage/mod.rs
- src/storage/txn/scheduler.rs
> txn: use thread pool for scheduler.

- src/raft/raft.rs
- src/raftstore/coprocessor/dispatcher.rs
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/coprocessor/split_observer.rs
- src/raftstore/store/msg.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/snap.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/mod.rs
- src/raftstore/store/worker/snap.rs
- src/server/node.rs
- src/storage/engine/mod.rs
- src/storage/engine/raftkv.rs
- src/storage/mod.rs
- src/util/worker/mod.rs
- tests/raftstore/node.rs
- tests/raftstore/server.rs
- tests/raftstore/test_snap.rs
refer: https://github.com/pingcap/tikv/issues/594
> raftstore: apply snapshot asynchronously

- etc/config-template.toml
- src/bin/tikv-server.rs
> *: add config flag for pd heartbeat.

- Cargo.lock
- Cargo.toml
- src/raftstore/store/store.rs
- tests/raftstore/test_stats.rs
> *: rename snap stats.

- src/server/coprocessor/endpoint.rs
- src/util/codec/table.rs
> copr: abort cut row when get enough cols

- src/raftstore/store/store.rs
> store: add more logs.

- Cargo.lock
- Cargo.toml
> cargo: disable hyper ssl now.

- travis-build/test.sh
> travis: fix foolish exit bug.

- .travis.yml
- scripts/build_etcd.sh
- travis-build/Makefile
> use etcd v3 binary. 

- benches/bin/mvcc.rs
- src/storage/engine/mod.rs
- src/storage/engine/raftkv.rs
- src/storage/engine/rocksdb.rs
- src/storage/mod.rs
- src/storage/mvcc/txn.rs
- src/storage/txn/store.rs
- tests/coprocessor/test_select.rs
- tests/storage/test_raftkv.rs
@siddontang @BusyJay @ngaut @zhangjinpeng1987
> storage/engine: add cf interface.

- tests/raftstore/test_transfer_leader.rs
> tests: fix transfer leader fail

- src/server/conn.rs
> server: cleanup try_read/write and create_mem_buf.

- benches/bin/bench-tikv.rs
- benches/bin/raftstore.rs
- src/raft/errors.rs
- src/raft/log_unstable.rs
- src/raft/progress.rs
- src/raft/raft.rs
- src/raft/raft_log.rs
- src/raft/raw_node.rs
- src/raft/status.rs
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/coprocessor/split_observer.rs
- src/raftstore/mod.rs
- src/raftstore/store/store.rs
- src/storage/engine/rocksdb.rs
- src/storage/txn/store.rs
- tests/raftstore/cluster.rs
- tests/raftstore/mod.rs
- tests/raftstore/node.rs
- tests/raftstore/pd.rs
- tests/raftstore/util.rs
> *: remove dead code

- src/lib.rs
> *: remove stale features

- src/server/kv.rs
> kvserver: add txn abort log.

- src/lib.rs
- src/util/codec/datum.rs
- src/util/codec/mysql/decimal.rs
- src/util/codec/mysql/duration.rs
- src/util/xeval/evaluator.rs
> copr: support plus

- src/storage/engine/mod.rs
- src/storage/engine/raftkv.rs
- src/storage/engine/rocksdb.rs
> storage/engine: add get_cf for snapshot.

- Cargo.lock
- Cargo.toml
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/raftstore/store/util.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/test_split_region.rs
- tests/raftstore/test_tombstone.rs
> support gc stale peer. 

- Cargo.lock
- Cargo.toml
> Cargo: update kvproto.

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- tests/raftstore/test_split_region.rs
- travis-build/test.sh
> tests: fix leader not found

- src/raft/raw_node.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
> raftstorage: remove rc

- src/util/metric/mod.rs
Performance of the metrics is improved by 27%.
Benchmark:
```sh
$ cargo bench
test tests::bench_single_thread_new_buffer_udp   ... bench:         160 ns/iter (+/- 40)
test tests::bench_single_thread_old_buffer_udp   ... bench:         218 ns/iter (+/- 4)
$ cargo bench
test tests::bench_multi_thread_new_buffer_udp    ... bench:   4,737,403 ns/iter (+/- 266,298)
test tests::bench_multi_thread_old_buffer_udp    ... bench:   6,540,073 ns/iter (+/- 1,081,465)
```
> util: send metrics in a background thread

- src/bin/tikv-server.rs
#795 
PTAL @siddontang @ngaut @BusyJay
> bin: support readable flag

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> store: peer region() returns ref, no need clone.

- src/raft/log_unstable.rs
- src/raftstore/store/store.rs
> *: cleanup

- src/server/coprocessor/aggregate.rs
- src/util/codec/datum.rs
- src/util/xeval/evaluator.rs
- tests/coprocessor/test_select.rs
> copr: support sum

- src/server/coprocessor/endpoint.rs
- tests/coprocessor/test_select.rs
- tests/tests.rs
- tests/util.rs
> copr: make test more readable

- src/util/sockopt.rs
- src/util/worker/mod.rs
- tests/raftstore/cluster.rs
- tests/raftstore/node.rs
- tests/raftstore/server.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/test_split_region.rs
- tests/raftstore/test_tombstone.rs
- tests/raftstore/test_transfer_leader.rs
- tests/raftstore/test_transport.rs
- travis-build/test.sh
> tests: make tests more stable

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/util/macros.rs
- src/util/worker/mod.rs
> *: cleanup slow log usage.

- src/lib.rs
- src/storage/engine/mod.rs
- src/storage/engine/raftkv.rs
- src/storage/engine/rocksdb.rs
- src/storage/mvcc/txn.rs
- src/storage/txn/store.rs
- src/util/worker/mod.rs
> storage: fix clippy warning

- src/raftstore/coprocessor/dispatcher.rs
- src/server/node.rs
- src/util/worker/mod.rs
- travis-build/test.sh
> *: make cleanup reentrant

- src/storage/mvcc/meta.rs
- src/storage/mvcc/txn.rs
> mvcc: commit may fail unexpectedly after meta splits.

- USAGE.md
- scripts/build_rocksdb.sh
@ngaut @BusyJay @shenli @queenypingcap
> *: update  building rocksdb.

- src/server/coprocessor/aggregate.rs
- tests/coprocessor/test_select.rs
> copr: support max/min

- src/raft/raft.rs
- src/raftstore/coprocessor/dispatcher.rs
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/coprocessor/split_observer.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
> store: add tag and id like raft package in log.

- src/raftstore/store/peer.rs
- src/raftstore/store/worker/compact.rs
> raftstore: enable rocksdb's wal

- src/storage/txn/scheduler.rs
- src/util/buf.rs
> util: impl BufRead for PipeBuf

- src/util/codec/datum.rs
- src/util/codec/number.rs
ref: https://github.com/pingcap/tidb/pull/1448
> [DNM] codec: encode i64 to varint if not comparable

- src/server/coprocessor/endpoint.rs
- src/server/coprocessor/mod.rs
- src/server/server.rs
- tests/coprocessor/test_select.rs
> copr: async snap

- Makefile
- scripts/check_req.sh
> scripts: check requirements

- src/bin/tikv-server.rs
- src/raftstore/mod.rs
- src/raftstore/store/mod.rs
- src/raftstore/store/msg.rs
- src/raftstore/store/snap.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/pd.rs
- src/raftstore/store/worker/snap.rs
- src/raftstore/store/worker/split_check.rs
- src/server/coprocessor/mod.rs
- src/server/mod.rs
- src/server/node.rs
- src/server/server.rs
- src/server/snap.rs
- src/server/transport.rs
- src/storage/mod.rs
- src/storage/txn/mod.rs
- src/storage/txn/scheduler.rs
- src/util/mod.rs
- src/util/transport.rs
- tests/raftstore/cluster.rs
- tests/raftstore/node.rs
- tests/raftstore/server.rs
> *: use one sendch

- etc/config-template.toml
- src/bin/tikv-server.rs
- src/pd/etcd.rs
- src/pd/mod.rs
- tests/pd/test_etcd_pd.rs
> *: remove root path flag

- etc/config-template.toml
- src/bin/tikv-server.rs
@ngaut @BusyJay @disksing  @overvenus @zhangjinpeng1987
> *: reduce flag.

- src/bin/tikv-dump.rs
- src/util/rocksdb.rs
> bin: don't create db if missing when dump

- Cargo.lock
- Cargo.toml
> update proto to 1.0.23

- src/bin/tikv-dump.rs
> bin: make region info dump all state

- src/bin/tikv-server.rs
- src/server/node.rs
- src/server/server.rs
- src/server/snap.rs
- src/server/transport.rs
- src/storage/engine/raftkv.rs
- tests/raftstore/node.rs
> server: remove Arc and RwLock for RaftStoreRouter

- src/bin/tikv-server.rs
@ngaut @qiuyesuifeng @iamxy @shenli @BusyJay
> bin: clean flags.

- Makefile
@ngaut @shenli  @BusyJay @disksing @zhangjinpeng1987
> Make build release and copy to bin

- Cargo.lock
- docker/release.sh
- docker/release_dockerfile
@ngaut @siddontang @disksing @zhangjinpeng1987 @iamxy  PTAL
> docker: add static release script

- src/raftstore/store/peer.rs
log all existing regions when staring store. 
> store: add create peer log.

- src/bin/tikv-server.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/raftstore/store/transport.rs
- src/server/coprocessor/endpoint.rs
- src/server/kv.rs
- src/server/node.rs
- src/server/server.rs
- src/server/transport.rs
- src/storage/engine/mod.rs
- src/storage/engine/raftkv.rs
- src/storage/engine/rocksdb.rs
- src/storage/mod.rs
- src/storage/txn/scheduler.rs
- src/util/worker/mod.rs
- tests/coprocessor/test_select.rs
- tests/raftstore/cluster.rs
- tests/raftstore/node.rs
- tests/raftstore/server.rs
- tests/raftstore/transport_simulate.rs
- tests/storage/sync_storage.rs
- tests/storage/test_raftkv.rs
- tests/storage/test_storage.rs
> storage: remove mutex

- src/util/codec/table.rs
> copr: take it easy when encounter unsupported col

- src/server/coprocessor/endpoint.rs
> copr: only decode used cols

- src/bin/tikv-server.rs
- src/raftstore/store/store.rs
- src/server/node.rs
- tests/raftstore/server.rs
- tests/raftstore/test_snap.rs
- tests/raftstore/transport_simulate.rs
ref: https://github.com/pingcap/tikv/issues/866
> raftstore: check pending regions before step

- Cargo.lock
- src/raft/raft.rs
- tests/test_raft.rs
port leader lease from coreos/etcd
https://github.com/coreos/etcd/pull/5468
https://github.com/coreos/etcd/pull/5809
> raft: implemented leader lease when quorum check is on

- etc/config-template.toml
add block-cache-size option to config-file
> etc: add block-cache-size option to config-file

- Cargo.lock
- src/raftstore/store/store.rs
- tests/raftstore/transport_simulate.rs
Now we can use the latest nightly rust (7333c4ac2 2016-07-31).
> *: update deps

- tests/test_raft.rs
port etcd leader lease testcase. https://github.com/coreos/etcd/pull/6070/files
> tests: correct leader lease testcase

- src/raftstore/store/peer.rs
- src/raftstore/store/peer_storage.rs
- tests/raftstore/cluster.rs
- tests/raftstore/test_snap.rs
- tests/raftstore/util.rs
@BusyJay @zhangjinpeng1987 @ngaut @siddontang
> raftstore: delete all cfs' data before applying snapshot.

- src/pd/client.rs
- tests/pd/test_etcd_pd.rs
For [pd #241](https://github.com/pingcap/pd/pull/241).
> pd: send http header on connect.

- src/bin/tikv-server.rs
- src/raftstore/store/store.rs
- src/util/mod.rs
- src/util/time_monitor.rs
Like TiDB time monitor. 
@ngaut @BusyJay @disksing @zhangjinpeng1987 @overvenus
> store: support time monitor.

- tests/test_raft.rs
Port https://github.com/coreos/etcd/pull/6097
@ngaut @BusyJay @disksing @zhangjinpeng1987 @iamxy
> raft: fix leader quorum test

- tests/raftstore/test_down_peers.rs
Increase `max_peer_down_duration`.
> tests: fix test_down_peers.

- src/raftstore/store/store.rs
- tests/raftstore/test_tombstone.rs
ref: https://github.com/pingcap/tikv/issues/805
> store: gc stale peer

- src/raft/raft.rs
- src/raft/raft_log.rs
- src/raft/raw_node.rs
- tests/test_raw_node.rs
> raft: hide Campaign rules on applying all entries

- Cargo.lock
- Cargo.toml
- src/bin/tikv-server.rs
- src/util/file_log.rs
- src/util/mod.rs
> Add file log whichs rotates by day

- src/storage/mvcc/mod.rs
- src/storage/mvcc/reader.rs
- src/storage/mvcc/txn.rs
- src/storage/mvcc/write.rs
@siddontang @zhangjinpeng1987 
The bug is mentioned in #921
> mvcc: check if already rolled back when prewrite.

- src/storage/mvcc/txn.rs
- src/storage/txn/scheduler.rs
> storage/txn: add logs.

- src/server/kv.rs
@shenli @siddontang @zhangjinpeng1987
> kvrpc: do not use proto's has_xx.

- src/server/node.rs
@ngaut @BusyJay @disksing @hhkbp2
> server: update error message.

- src/util/rocksdb.rs
> util: remove unnecessary log.

- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
@ngaut @BusyJay @disksing @hhkbp2 @zhangjinpeng1987
> store: update log.

- etc/config-template.toml
- src/bin/tikv-server.rs
- src/server/config.rs
- src/server/coprocessor/endpoint.rs
- src/server/server.rs
- tests/coprocessor/test_select.rs
> copr: make endpoint threadpool size configurable

- src/server/mod.rs
- src/storage/mod.rs
- src/storage/txn/scheduler.rs
- src/util/transport.rs
> *: log msg before discard

- benches/bin/mvcc.rs
- src/storage/mvcc/mod.rs
- src/storage/mvcc/txn.rs
- src/storage/mvcc/write.rs
- tests/storage/test_storage.rs
@zhangjinpeng1987 @ngaut @siddontang
> storage/txn: add tests.

- src/server/coprocessor/aggregate.rs
- tests/coprocessor/test_select.rs
> copr: skip Null in First aggr

- src/raftstore/store/store.rs
@ngaut @BusyJay @disksing @hhkbp2
> store: log detailed region count when start.

- .travis.yml
- travis-build/Makefile
> ci: fix ci cache rebuild on osx

- src/raftstore/store/util.rs
@ngaut @BusyJay @disksing @hhkbp2
> store: use &str for conf_change_type_str

- src/raftstore/store/store.rs
@ngaut @BusyJay @disksing  @hhkbp2 @zhangjinpeng1987
> store: add log for store clean up.

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> raftstore: use rc

- src/raft/raft.rs
- tests/test_raft.rs
port ectd https://github.com/coreos/etcd/pull/6286
> allow an election immediately after start with checkquorum

- src/storage/mvcc/txn.rs
@zhangjinpeng1987 @ngaut @siddontang
> storage: fix gc issue #1021

- src/bin/tikv-dump.rs
- src/bin/tikv-server.rs
- src/raftstore/coprocessor/dispatcher.rs
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/coprocessor/split_observer.rs
- src/raftstore/store/store.rs
- src/storage/mod.rs
- src/storage/mvcc/txn.rs
- tests/coprocessor/test_select.rs
- tests/raftstore/node.rs
- tests/raftstore/server.rs
> calculate used space correctlly

- src/raft/raft_log.rs
@ngaut @BusyJay @hhkbp2 @zhangjinpeng1987
> raft: fix raft port.

- src/util/codec/datum.rs
- src/util/xeval/evaluator.rs
ref: https://github.com/pingcap/tidb/pull/1667
> copr: fix coerce datum

- src/storage/txn/scheduler.rs
- tests/storage/test_storage.rs
- travis-build/test.sh
> ci: enable clippy check

- src/util/codec/datum.rs
- src/util/codec/mysql/decimal.rs
- src/util/xeval/evaluator.rs
> copr: support dividde

- tests/raftstore/test_multi.rs
warm up network for test read unapplied leader
> warm up network for test read unapplied leader

- src/util/codec/datum.rs
> ci: resolve compilation error

- src/storage/mod.rs
> storage: display context

- Cargo.lock
- Cargo.toml
- src/server/coprocessor/endpoint.rs
- tests/coprocessor/test_select.rs
> copr: use fat bytes array

- Cargo.lock
- travis-build/Makefile
My rustc is updated to `rustc 1.13.0-nightly (cbe4de78e 2016-09-05)`.
> *: update clippy.

- Cargo.lock
- src/storage/metrics.rs
- src/storage/mod.rs
- src/storage/txn/scheduler.rs
PTAL @ngaut @siddontang @zhangjinpeng1987 @overvenus
> storage: add kv metrics.

- src/raft/raft_log.rs
- src/raft/storage.rs
> raft: add panic handling for term() due to iob

- Cargo.lock
- src/raft/raft.rs
- src/raft/raw_node.rs
- tests/test_raft.rs
- tests/test_raw_node.rs
> raft: port raft leader transfer exposure

- Cargo.lock
- src/storage/engine/metrics.rs
- src/storage/engine/mod.rs
- src/storage/engine/raftkv.rs
> *: add metrics for raftkv.

- src/raft/storage.rs
> raft: add comments for raft storage

- src/raftstore/store/engine.rs
- src/raftstore/store/peer_storage.rs
ref: https://github.com/pingcap/tikv/issues/1030
> raftstore: skip deleting when possible

- src/server/metrics.rs
- src/server/resolve.rs
- src/server/server.rs
- src/server/snap.rs
@ngaut @BusyJay @disksing @hhkbp2 @overvenus
> server: add metrics for server.

- src/util/mod.rs
> util: fix escape

- travis-build/Makefile
> *: use rocksdb 4.12

- src/raftstore/store/metrics.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> raftstore: update metrics and log. 

- Cargo.lock
- Cargo.toml
- etc/config-template.toml
- src/bin/tikv-server.rs
- src/util/mod.rs
- travis-build/Makefile
How to:
1. start a prometheus [pushgateway]
2. start a prometheus server and pull metrics from [pushgateway]
3. start a tikv and let `metric.address` be the address of [pushgateway]
[pushgateway]: https://github.com/prometheus/pushgateway
> util, bin: push prometheus metrics

- Cargo.lock
Ref pingcap/rust-prometheus#61
> Cargo: update Cargo.lock

- src/storage/mvcc/txn.rs
- src/storage/txn/scheduler.rs
> storage/txn: tiny cleanup

- Cargo.lock
@BusyJay @disksing @hhkbp2 @overvenus
> Cargo: update prometheus.

- src/raft/log_unstable.rs
- src/raft/raft.rs
- src/raft/raft_log.rs
- tests/test_raft.rs
> raft: add tag for panic messages

- src/raftstore/store/metrics.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> store: add metric for doing raft command.

- Cargo.lock
- src/raftstore/store/engine.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/compact.rs
- src/raftstore/store/worker/region.rs
- src/storage/engine/rocksdb.rs
- src/util/rocksdb.rs
- tests/raftstore/test_compact_log.rs
> *: update rocksdb

- Cargo.lock
@ngaut @BusyJay @disksing @overvenus
> Cargo: update prometheus

- src/raft/log_unstable.rs
- src/raft/mod.rs
- src/raft/progress.rs
- src/raft/raft.rs
- src/raft/raft_log.rs
- src/raft/raw_node.rs
- src/raft/status.rs
- src/raft/storage.rs
> raft: update LICENSE headers

- src/util/codec/mysql/duration.rs
- src/util/codec/mysql/mod.rs
- src/util/codec/mysql/time.rs
- src/util/codec/table.rs
> copr: always check fsp

- src/raftstore/store/metrics.rs
- src/raftstore/store/peer.rs
metric PEER_ADMIN_CMD_COUNTER_VEC can cover
> store: remove unnecessary metric

- Cargo.lock
- src/bin/tikv-server.rs
- src/storage/mod.rs
- src/util/rocksdb.rs
List column families before open db, and drop discarded column families.
> remove discarded cf

- src/pd/client.rs
- src/storage/engine/mod.rs
- src/storage/mvcc/txn.rs
- tests/storage/test_storage.rs
@ngaut @siddontang @zhangjinpeng1987 @BusyJay
> storage: add tests

- Cargo.lock
- src/raftstore/store/peer.rs
- src/server/coprocessor/metrics.rs
- src/server/kv.rs
- src/storage/engine/mod.rs
- src/storage/mod.rs
- src/storage/txn/scheduler.rs
> kvrpc: remove obsolete cmds.

- src/raftstore/store/peer.rs
- src/server/coprocessor/metrics.rs
- src/storage/engine/mod.rs
> raftstore/peer: add metric for raft ready request vote

- tests/raftstore/test_multi.rs
- tests/raftstore/test_snap.rs
- tests/raftstore/test_split_region.rs
- tests/raftstore/test_stale_peer.rs
- tests/raftstore/test_transfer_leader.rs
- tests/raftstore/transport_simulate.rs
> tests: make FilterFactory reuseable

- src/raftstore/store/config.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/region.rs
- tests/raftstore/test_snap.rs
ref: https://github.com/pingcap/tikv/issues/1109
> tests: cover batch size check

- src/storage/mod.rs
improve storage scheduler test coverage
> improve storage scheduler test coverage

- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- tests/raftstore/test_snap.rs
ref: https://github.com/pingcap/tikv/issues/1084
> raftstore: check stale snapshot

- docker/rust_dockerfile
> docker: upgrade rocksdb ver in Dockerfile

- src/raft/errors.rs
- src/raft/log_unstable.rs
- src/raft/raft.rs
- tests/test_raft.rs
> raft: improve test coverage

- src/raftstore/store/worker/region.rs
> raftstore: don't use delete file in range

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/util/panic_hook.rs
> bin: log panic info if possible

- README.md
To fix https://github.com/pingcap/tikv/issues/1132
@c4pt0r @shenli @queenypingcap
> ReadMe: fix build link error.

- Cargo.lock
- Cargo.toml
- src/raftstore/store/util.rs
Upgrade uuid to fix #1134 
@ngaut @iamxy @BusyJay @overvenus
> cargo: update uuid.

- src/raftstore/store/metrics.rs
- src/raftstore/store/store.rs
- src/util/mod.rs
> util/raftstore: add metrics for raft tick and ready total duration.

- docker/rust_dockerfile
> docker: upgrade rust version to date `2016-09-29`

- Cargo.lock
- src/storage/txn/latch.rs
- travis-build/Makefile
rustc: 1.14.0-nightly (ad19c32a5 2016-10-06)
> *: upgrade dev tools

- src/bin/tikv-server.rs
- src/raftstore/errors.rs
- src/server/transport.rs
- tests/raftstore/node.rs
- tests/raftstore/server.rs
Store address cache will be handled in another PR.
Reference Issue: #1153
> server: check store id before sending to raftstore

- src/server/resolve.rs
> server: refresh expired store address on resolve

- src/server/metrics.rs
- src/server/server.rs
- src/server/transport.rs
> server: add some metrics and cleanup logs

- src/raft/raft_log.rs
- src/raft/storage.rs
- src/util/mod.rs
> util: avoid unnecessary reallocate

- Cargo.lock
- src/raftstore/errors.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- tests/raftstore/test_split_region.rs
For https://github.com/pingcap/tikv/issues/974
@ngaut @BusyJay @siddontang
> raftstore: attach new regions' meta along with StaleEpoch error.

- src/bin/tikv-server.rs
- src/raftstore/store/config.rs
- src/raftstore/store/msg.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/compact.rs
- src/raftstore/store/worker/metrics.rs
- tests/raftstore/mod.rs
- tests/raftstore/test_compact_lock_cf.rs
> compact lock cf periodically

- src/raftstore/store/metrics.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> raftstore/peer: add metrics for raft messages

- src/raftstore/store/peer_storage.rs
- tests/raftstore/test_snap.rs
> raftstore: check truncated index when calc last term

- docker/release_dockerfile
> docker: downgrade release docker rustc

- tests/raftstore/test_stale_peer.rs
> test/raftstore: fix test case for stale peer gc

- src/raftstore/store/peer.rs
- src/raftstore/store/peer_storage.rs
PTAL @BusyJay @siddontang @ngaut
> raftstore: fix typos

- etc/config-template.toml
- src/bin/tikv-server.rs
Make column family raft configurable.
> bin/etc: make raft cf configurable

- src/util/codec/datum.rs
- src/util/xeval/evaluator.rs
Support minus, intdiv and mod ops.  Multiply will be supported in next pr, which will also impl Mul for Decimal.
@hhkbp2 @coocood PTAL
> copr: support more ops

- src/util/mod.rs
> util: remove "the"

- src/server/kv.rs
- src/storage/config.rs
- src/storage/mod.rs
- src/storage/txn/scheduler.rs
ref https://github.com/pingcap/tikv/issues/1190
@siddontang @disksing @BusyJay PTAL
> storage/scheduler: flow control

- .travis.yml
- src/bin/tikv-ctl.rs
- travis-build/Makefile
- travis-build/test.sh
Make sure code is formatted properly before creating a pr.
> ci: add format check

- src/storage/txn/scheduler.rs
Add error metrics for scheduler.
@disksing @siddontang PTAL
> add more metrics for scheduler

- src/storage/metrics.rs
- src/storage/txn/scheduler.rs
> scheduler: add timer for latch wait.

- Cargo.lock
- Cargo.toml
- Makefile
ref ngaut/rust-rocksdb#52
@zhangjinpeng1987 @disksing PTAL
> rocksdb: use features to control linking

- src/util/xeval/evaluator.rs
ref #1226 
@coocood @siddontang PTAL
> copr: support case when and coalesce

- src/storage/config.rs
tuning scheduler too busy threshold
> tuning scheduler too busy threshold

- src/bin/tikv-server.rs
PTAL @siddontang @disksing 
cc #1209 and #1206
> bin: update help message

- Cargo.lock
- Cargo.toml
- src/raft/mod.rs
- src/raftstore/store/keys.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- tests/raftstore/test_snap.rs
- tests/raftstore/test_split_region.rs
- tests/raftstore/transport_simulate.rs
> raftstore: check range before replica a peer

- src/bin/tikv-server.rs
- src/util/mod.rs
> bin: add flag to print version information

- src/server/server.rs
Log TiKV ready to serve.
PTAL @siddontang @BusyJay @huachaohuang 
Close #1225
> server: log tikv ready to serve

- src/storage/mvcc/metrics.rs
- src/storage/mvcc/mod.rs
- src/storage/mvcc/txn.rs
@siddontang @ngaut 
Not sure how much this will affect performance.
> mvcc: add metrics for versions

- src/raftstore/store/store.rs
- src/raftstore/store/worker/compact.rs
- src/raftstore/store/worker/mod.rs
- src/raftstore/store/worker/raftlog_gc.rs
> raftstore: separate manual compaction to a different worker.

- src/bin/tikv-server.rs
unified default value and config file
@disksing @siddontang PTAL
> bin: unified default value and config file

- src/bin/tikv-ctl.rs
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/store/bootstrap.rs
- src/raftstore/store/engine.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/region.rs
- src/raftstore/store/worker/split_check.rs
- src/storage/engine/mod.rs
- src/storage/engine/raftkv.rs
- src/storage/engine/rocksdb.rs
- src/storage/mvcc/reader.rs
- tests/raftstore/test_split_region.rs
- tests/storage/test_raftkv.rs
ref https://github.com/pingcap/tikv/issues/1244
@siddontang @BusyJay @disksing PTAL
> rocksdb: scan not fill block-cache

- src/bin/tikv-server.rs
Send SIGUSR1 to dump RocksDB statistics for debugging. 
@ngaut @BusyJay @zhangjinpeng1987
> bin: dump rocksdb statistics

- src/storage/mvcc/metrics.rs
- src/storage/mvcc/txn.rs
Adjust metric buckets and disable unnecessary observe.
@siddontang @ngaut
> storage: adjust mvcc metrics.

- src/raftstore/store/worker/compact.rs
> log: escape string

- tests/storage/mod.rs
- tests/storage/sync_storage.rs
- tests/storage/test_raft_storage.rs
- tests/storage/test_raftkv.rs
- tests/storage/test_storage.rs
Fix #1029 
Result: https://coveralls.io/builds/8621176
@siddontang @zhangjinpeng1987
> storage: improve test coverage

- src/storage/mod.rs
> improve test coverage

- Cargo.lock
- src/raftstore/store/store.rs
To monitor store uptime.
Closes https://github.com/pingcap/tikv/issues/1207
> raftstore/store: add start time

- etc/config-template.toml
- src/bin/tikv-server.rs
- src/pd/client.rs
- src/pd/mod.rs
- src/pd/protocol.rs
- src/server/resolve.rs
- tests/pd/test_rpc_client.rs
- tests/raftstore/pd.rs
Get the cluster ID from PD when create the `RpcClient`.
> [DNM] tikv-server: get cluster id from PD

- src/bin/tikv-ctl.rs
- src/storage/mod.rs
- src/storage/mvcc/lock.rs
- src/storage/mvcc/mod.rs
#1077
Add mvcc decoding support for tiki-ctl
> [DNM] add tikv-ctl support for MVCC

- src/raftstore/mod.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- tests/raftstore/test_tombstone.rs
> raftstore: refactor apply error handle

- Cargo.lock
- Cargo.toml
- src/raftstore/store/store.rs
ref tikv/proto#115
@siddontang @huachaohuang PTAL
> raftstore: add applying snap count

- etc/config-template.toml
- src/bin/tikv-server.rs
We should notify users to update etc/tikv.toml as well as binary.
> bin/etc: refactor rocksdb config

- src/bin/tikv-ctl.rs
> tikv-ctl: add region scan

- src/pd/client.rs
We may fail if we start PD and TiKV together because TiKV cannot get cluster ID from PD.
We can retry for a long time when creating the client.
> pd/client: add more retries

- Cargo.lock
- Cargo.toml
- src/bin/tikv-server.rs
- src/lib.rs
- src/util/config.rs
`validate_addrs` validates a list of addresses. Addresses are formed like "Host:Port".
More details about **Host** and **Port** can be found in RFC3986 section 3.2.2 and 3.2.3.
Close #1274 
> Check pd list format

- tests/raftstore/test_snap.rs
- tests/raftstore/transport_simulate.rs
> tests: make snap gc more stable

- Cargo.lock
- src/pd/errors.rs
- src/pd/protocol.rs
> pd: add region is shutdown error

- src/raftstore/store/metrics.rs
- src/raftstore/store/peer.rs
To see the log size distribution statistics. 
@BusyJay @hhkbp2 @overvenus
> store: add propose log histogram metric

- Makefile
- benches/benches.rs
- benches/bin/bench-tikv.rs
- src/util/config.rs
- tests/tests.rs
- travis-build/Makefile
Sometimes the hard limit meets our requirement but the soft limit. In this case we can update the soft limit directly.
@siddontang @overvenus PTAL
> config: try updating soft limit before failing

- src/raftstore/store/peer.rs
- tests/raftstore/test_multi.rs
> raftstore: check if message is discard after proposal

- src/server/coprocessor/endpoint.rs
- src/server/coprocessor/metrics.rs
- src/server/coprocessor/mod.rs
ref #1305 
@siddontang @shenli @disksing PTAL
> copr: check outdated task

- src/util/worker/metrics.rs
- src/util/worker/mod.rs
> util: add pending task metric for Worker

- etc/config-template.toml
- src/bin/tikv-server.rs
Make max bg flushes configurable.  Increase the bg flushes when load data.
> make max bg flushes configurable

- etc/config-template.toml
- src/bin/tikv-server.rs
> Strict check advertise address

- src/server/coprocessor/endpoint.rs
- src/server/coprocessor/metrics.rs
- src/server/coprocessor/mod.rs
> copr: add running tasks upper bound

- src/raftstore/store/local_metrics.rs
- src/raftstore/store/mod.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
Like other frequent raft metrics, cache propose metric and flush in batch. 
@ngaut @BusyJay @hhkbp2
> store: cache propose metric and flush in batch.

- Cargo.lock
- src/server/kv.rs
- src/storage/mod.rs
- tests/storage/sync_storage.rs
- tests/storage/test_storage.rs
/cc @ngaut @siddontang @zhangjinpeng1987
> kvrpc: add raw kv api.

- src/bin/tikv-server.rs
> bin: remove deprecated option

- Cargo.lock
- src/pd/metrics.rs
- src/raftstore/store/metrics.rs
- src/storage/engine/metrics.rs
- src/storage/mvcc/metrics.rs
Update prometheus and use the newest histogram register macro. 
@BusyJay @disksing @hhkbp2 @overvenus
> *: update prometheus and fix compile error

- src/raftstore/store/metrics.rs
- src/raftstore/store/peer.rs
+ Add more metrics 
+ Enlarge histogram buckets
> store: add get ready and append log metric.

- src/raftstore/store/msg.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/region.rs
> raftstore: fix possible stale snap state

- Cargo.lock
- etc/config-template.toml
- src/bin/tikv-server.rs
> max total wal size

- Cargo.lock
- Cargo.toml
- src/raftstore/store/store.rs
ref pingcap/pd#414 pingcap/kvproto#123
@siddontang @huachaohuang PTAL
> raftstore: report server is busy

- src/raftstore/store/worker/region.rs
> worker: clean up size_cnt  after write.

- src/bin/tikv-server.rs
If tikv-server binds the port too early, a connection will be setup immediately. So sender will append all the messages to SendBuffer. Once receiver accepts the connection, all the messages in buffer will be received at once. It will easily cause channel full and oom.
> tikv-server: bind port lazily

- Cargo.lock
- etc/config-template.toml
- src/bin/tikv-server.rs
Add rocksdb log-dir option.
Pending ngaut/rust-rocksdb#61
PTAL @siddontang @BusyJay @zhangjinpeng1987 
Close #1360
> bin: add rocksdb log-dir option

- Cargo.lock
- etc/config-template.toml
- src/bin/tikv-server.rs
> Revert "bin: add rocksdb log-dir option"

- src/storage/metrics.rs
- src/storage/mod.rs
cc @siddontang @zhangjinpeng1987
> storage: add rawkv metrics.

- src/raftstore/store/store.rs
> raftstore: only delete file when cleaning up

- src/raftstore/store/metrics.rs
- src/raftstore/store/store.rs
@BusyJay @zhangjinpeng1987 @overvenus
> store: support rocksdb memory metrics.

- src/storage/mod.rs
- src/storage/txn/scheduler.rs
> storage: move raw_get to thread pool.

- tests/raftstore/test_region_heartbeat.rs
> tests: wait more time to get down peers reported

- Cargo.lock
- src/raftstore/errors.rs
- src/raftstore/store/store.rs
- tests/storage/test_raft_storage.rs
@disksing @coocood [tidb_issue_2294](https://github.com/pingcap/tidb/issues/2294)
>  return error StoreNotMatch when store id not match

- src/util/codec/convert.rs
Sync with pingcap/tidb#2337
PTAL @BusyJay @coocood @siddontang
> util/codec: fix get valid float

- src/util/xeval/evaluator.rs
Ref https://github.com/pingcap/tidb/pull/2069
@XuHuaiyu @coocood @BusyJay
> distsql: support `IsNull`.

- src/util/xeval/evaluator.rs
Ref https://github.com/pingcap/tidb/pull/1947
@XuHuaiyu @coocood @BusyJay
> distsql: support `If`.

- src/util/xeval/evaluator.rs
Ref https://github.com/pingcap/tidb/pull/2067
@BusyJay @siddontang @coocood
> distsql: support `IfNull`.

- Cargo.lock
- src/raftstore/errors.rs
- src/raftstore/store/store.rs
- tests/storage/test_raft_storage.rs
@zhangjinpeng1987 @disksing [tidb_issue_2294](https://github.com/pingcap/tidb/issues/2294)
> return error StoreNotMatch when store id not match

- .travis.yml
- Cargo.lock
- circle.yml
- travis-build/Makefile
Zlib 1.2.8 is no longer available, upgrade to 1.2.10
> upgrade Zlib

- src/server/coprocessor/endpoint.rs
- src/storage/mvcc/reader.rs
- src/storage/mvcc/txn.rs
- src/storage/txn/scheduler.rs
- src/storage/txn/store.rs
scanner with upper bound.
ref https://github.com/pingcap/tikv/issues/1467
@BusyJay @siddontang PTAL
> scanner with upper bound

- Cargo.lock
- circle.yml
- travis-build/Makefile
Hi,
This PR tries to fix issue #1474
Related to https://github.com/ngaut/rust-rocksdb/pull/75
> upgrade rocksdb version to 5.0.1

- etc/config-template.toml
- src/bin/tikv-server.rs
- src/raftstore/store/config.rs
So we can change ticks without recompilation.
> tikv-server: allow set timeout and hearbeat ticks

- src/bin/tikv-server.rs
PTAL @andelf @siddontang @BusyJay 
cc pingcap/pd#472
> tikv-server: change flag v to V

- src/storage/engine/raftkv.rs
So we can know what's happening under the hook more quickly.
> metrics: add fail reason

- src/raftstore/store/worker/metrics.rs
- src/raftstore/store/worker/region.rs
> [metrics]:add metrics for snapshot(kv-count & size)

- src/storage/mod.rs
- src/storage/txn/scheduler.rs
- tests/storage/mod.rs
- tests/storage/test_raft_storage.rs
- tests/storage/test_storage.rs
- tests/storage/util.rs
> scheduler: allow 1 GC command at the same time.

- src/raftstore/store/local_metrics.rs
- src/raftstore/store/metrics.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> metric: record count of keys have written every round

- src/raftstore/store/metrics.rs
- src/raftstore/store/store.rs
> raftstore: record log lag

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> raftstore: fix append timer metric

- src/server/coprocessor/endpoint.rs
- src/storage/engine/raftkv.rs
- src/storage/mod.rs
Describe more details about errors in metrics.
@siddontang @coocood @zhangjinpeng1987 PTAL
> copr: get detail error type

- Cargo.lock
- src/raftstore/store/local_metrics.rs
- src/raftstore/store/metrics.rs
- src/raftstore/store/store.rs
> raftstore: record ready time as histogram

- src/raftstore/store/metrics.rs
- src/raftstore/store/store.rs
> store: add estimate num keys metric

- src/storage/metrics.rs
- src/storage/mod.rs
- src/storage/txn/scheduler.rs
> scheduler: add metrics and slow log.

- src/server/coprocessor/endpoint.rs
- src/server/coprocessor/metrics.rs
- src/storage/metrics.rs
- src/storage/mod.rs
- src/storage/mvcc/mod.rs
- src/storage/mvcc/reader.rs
- src/storage/txn/scheduler.rs
- src/storage/txn/store.rs
- src/util/thread_metrics.rs
@siddontang @disksing @overvenus PTAL
> copr/metrics: record scan efficiency

- Cargo.lock
Fix zlib include dir error.
@siddontang @BusyJay @disksing PTAL
> upgrade zlib include dir

- src/storage/txn/scheduler.rs
> scheduler: fix resolve locks bug.

- etc/config-template.toml
- src/bin/tikv-server.rs
- src/raftstore/store/config.rs
- src/raftstore/store/store.rs
PTAL @siddontang @BusyJay  @huachaohuang
> *: option capacity, 0 for disk capacity

- Cargo.lock
- Cargo.toml
- src/bin/signal_handler.rs
- src/bin/tikv-server.rs
- src/util/config.rs
- src/util/sockopt.rs
- tests/raftstore/cluster.rs
- tests/raftstore/test_multi.rs
- update rust-rocksdb to latest version
- cleanup some codes
- make `assert_quorum` more informative
After this pr, it should be able to compile TiKV on Windows, not a big deal, but still a nice-to-have. :)
> *: tiny cleanup

- src/storage/txn/scheduler.rs
PTAL @zhangjinpeng1987 @hhkbp2
> sched: add latch test.

- src/bin/tikv-server.rs
PTAL  @siddontang @BusyJay @andelf 
Close #1549
> bin: prints help message when meets unknown arguments

- src/bin/tikv-ctl.rs
> [ti-ctl]:add start_ts as filter in scan & mvcc

- src/storage/mvcc/txn.rs
> no need to overwrite data in prewrite

- tests/storage/assert_storage.rs
- tests/storage/mod.rs
- tests/storage/test_raft_storage.rs
- tests/storage/test_storage.rs
- tests/storage/util.rs
@zhangjinpeng1987 @disksing PTAL
> [tests] add tests for gc on raft storage

- src/storage/metrics.rs
- src/storage/txn/scheduler.rs
@zhangjinpeng1987 @disksing PTAL
> [metrics] count empty range in gc

- src/raftstore/store/local_metrics.rs
- src/raftstore/store/metrics.rs
- src/raftstore/store/msg.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/pd.rs
- src/server/transport.rs
Hi,
This PR tries to fix issue #1562
> raftstore: add request wait time and process time metrics

- src/storage/mvcc/txn.rs
There is no value need to be deleted when rollback lock.
@disksing @AndreMouche PTAL
> there is no value need to be deleted when rollback lock

- src/server/coprocessor/endpoint.rs
> endpoint: adjust scan slow log

- src/bin/tikv-server.rs
#1536 
PTAL @siddontang @shenli
> add http scheme

- src/storage/engine/mod.rs
- src/storage/mvcc/reader.rs
- src/storage/mvcc/txn.rs
> reverse seek write include equal key

- tests/raftstore/test_lease_read.rs
- tests/raftstore/test_transfer_leader.rs
> tests: fix wrong test name and harden lease test

- src/util/worker/mod.rs
Sometimes we need to do some cleanup when worker is shutdown.
@siddontang @disksing @zhangjinpeng1987 PTAL
> worker: support shutdown

- src/server/coprocessor/endpoint.rs
- src/util/codec/table.rs
@BusyJay @disksing PTAL
This PR prepared for PR [Topn](https://github.com/pingcap/tikv/pull/1578/)
> coprocessor:refactor cut_row & cut_idx_key for row value analysis

- src/raftstore/store/store.rs
Some slow check is not necessary, and some are covered by outer slow check. 
@BusyJay @hhkbp2
> raftstore: remove un-ncessary slow check

- src/raftstore/store/local_metrics.rs
- src/raftstore/store/metrics.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
+ remove unnecessary GetReady metric
+ use local histogram for append log
@BusyJay @hhkbp2
> raftstore: tiny update metric

- .travis.yml
- Cargo.lock
- benches/benches.rs
- circle.yml
- docker/release_dockerfile
- docker/rust_dockerfile
- src/lib.rs
- src/raftstore/store/snap.rs
- src/raftstore/store/store.rs
- src/storage/txn/scheduler.rs
- src/util/codec/rpc.rs
- tests/raftstore/pd.rs
- tests/util.rs
- travis-build/Makefile
Update Rustc to latest nightly, clippy to 0.0.114
> Update rustc and clippy

- src/bin/tikv-server.rs
- src/raftstore/store/config.rs
> enlarge raft base tick interval and make it configurable

- tests/raftstore/cluster.rs
- tests/raftstore/test_stale_peer.rs
> tests: wait for region removal

- src/bin/tikv-server.rs
Address comment https://github.com/pingcap/tikv/pull/1614/files#r101453434
PTAL @siddontang @BusyJay @zhangjinpeng1987
> bin: use tikv built-in HashMap

- Cargo.lock
- etc/config-template.toml
- src/bin/tikv-server.rs
- src/raftstore/store/keys.rs
- src/util/rocksdb.rs
raft cf memtable insert with hint prefix extractor.
> raft cf memtable insert with hint prefix extractor

- src/server/coprocessor/endpoint.rs
- tests/coprocessor/test_select.rs
Hi,all,
this PR is used to fix bug in order by primary key.
@disksing @BusyJay PTAL
> topn:fix bug in order by primary key

- src/raftstore/store/store.rs
ref https://github.com/pingcap/tikv/issues/1604
@BusyJay @siddontang @hhkbp2 PTAL
> wait all workers finish

- src/raftstore/store/peer.rs
- src/raftstore/store/peer_storage.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/apply.rs
- src/raftstore/store/worker/mod.rs
- tests/raftstore/pd.rs
- tests/raftstore/test_conf_change.rs
- tests/raftstore/util.rs
After #1533, #1535, #1540, #1560, #1573, #1586, this pr implements the async apply eventually.
ref #1488
> raftstore: async apply

- src/raftstore/store/engine_metrics.rs
- src/raftstore/store/store.rs
> not reset rocksdb's counter

- etc/config-template.toml
- src/bin/tikv-server.rs
> increase the L0 slowdown/stop condition as rocksdb5.1

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/apply.rs
- src/raftstore/store/worker/mod.rs
This pr move all apply related code from `peer.rs` to `apply.rs`.
@siddontang @hhkbp2 @zhangjinpeng1987 PTAL
> raftstore: adjust code

- Cargo.lock
> use rocksdb 5.1.2

- src/raftstore/store/peer.rs
- tests/raftstore/test_multi.rs
ref #1647.
@siddontang @hhkbp2 @disksing PTAL
> raftstore: make apply atomic

- src/storage/txn/scheduler.rs
Fix #1572
/cc @zhangjinpeng1987 @siddontang
> scheduler: add region id to slow log.

- docker/rust_dockerfile
To fix https://github.com/pingcap/tikv/issues/1646
PTAL @iamxy @BusyJay @zhangjinpeng1987
> use rocksdb 5.1.2 for docker

- src/storage/metrics.rs
- src/storage/txn/scheduler.rs
> add metrics for scheduler is busy

- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
> raftstore: notify pd when leader ship changes

- src/bin/tikv-server.rs
@BusyJay @hhkbp2  @zhangjinpeng1987
> bin: add config for scheduler too busy threshold

- src/bin/tikv-ctl.rs
- src/raftstore/coprocessor/region_snapshot.rs
- src/raftstore/store/engine.rs
- src/raftstore/store/worker/region.rs
- src/raftstore/store/worker/split_check.rs
- src/storage/mvcc/reader.rs
@siddontang @zhangjinpeng1987 @disksing PTAL
> iter: tiny cleanup

- src/storage/mod.rs
- src/storage/txn/latch.rs
- src/storage/txn/scheduler.rs
ref https://github.com/pingcap/tikv/issues/1667
@siddontang @AndreMouche PTAL
> scheduler too busy

- etc/config-template.toml
- src/bin/tikv-server.rs
- src/raftstore/store/config.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/apply.rs
- src/util/rocksdb.rs
- tests/raftstore/test_compact_lock_cf.rs
Add a threshold for lock cf's manual compaction. Disable manual compaction for other CFs by default.
ref https://github.com/pingcap/tikv/issues/1663
> reduce manual compaction

- src/raftstore/store/peer.rs
If read index is proposed before a split and applied long after the split, it may generate snapshot contains stale data.
> raftstore: fix possible stale read

- .travis.yml
- travis-build/Makefile
- travis-build/test.sh
Cache more things to speedup travis build.
> travis: update cache

- etc/config-template.toml
- src/bin/tikv-server.rs
PTAL @andelf @BusyJay @zhangjinpeng1987
> don't use underline in TOML

- src/bin/tikv-server.rs
> bin: make lock cf configuable

- Cargo.lock
- etc/config-template.toml
- src/bin/tikv-server.rs
> update rocksdb and remove no need configuration

- src/util/buf.rs
`TryRead` and `TryWrite` are deprecated in mio, let's not depend on it.
> util: remove TryRead/TryWrite

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/raftstore/coprocessor/region_snapshot.rs
- src/server/coprocessor/endpoint.rs
- src/storage/engine/mod.rs
- src/util/buf.rs
- src/util/codec/rpc.rs
TiKV doesn't need bytes any more.
@siddontang @overvenus PTAL
> *: drop bytes dep

- tests/raft/test_raft.rs
Hi,
This PR adds the test case in https://github.com/coreos/etcd/pull/7574
PTAL @siddontang @BusyJay @zhangjinpeng1987
> tests/raft: add read index request test case

- src/raftstore/store/config.rs
- src/server/config.rs
> *: add config validate test

- src/raftstore/store/bootstrap.rs
> raftstore: add bootstrap test

- src/raftstore/store/util.rs
> raftstore: add util test

- travis-build/Makefile
I accidentally delete my fork of kcov, so let's switch to the official release now.
> travis: update kcov

- src/bin/tikv-server.rs
> bin: replace unwrap with unwrap_or_else

- src/storage/mvcc/lock.rs
- src/storage/mvcc/txn.rs
- src/storage/mvcc/write.rs
Hi,
This PR adds some unit test cases for storage/mvcc.
PTAL @AndreMouche @disksing @siddontang
> storage/mvcc: add unit test cases

- circle.yml
This pr is a quick fix for circle ci without merging #1750.
@siddontang @overvenus PTAL
> circleci: fix rustfmt

- Cargo.toml
- Makefile
- travis-build/test.sh
Compilation can fail occasionally in travis.
> travis: limit compilation concurrency

- src/util/file.rs
- tests/raftstore/test_compact_lock_cf.rs
- tests/raftstore/util.rs
test_compact_lock_cf often fails on my machine.
> tests: fix compact byte detection

- Cargo.lock
- Cargo.toml
- src/raftstore/errors.rs
- src/server/coprocessor/endpoint.rs
- src/server/kv.rs
> Add reason for server is busy error

- src/pd/async/client.rs
- src/pd/async/util.rs
PTAL @siddontang @BusyJay @disksing
> pd: refactor unary request retry future

- src/pd/async/client.rs
- src/pd/async/mod.rs
- src/pd/async/util.rs
Moving some functions to `util` for a better mod structure.
> pd: better mod structure

- src/pd/async/util.rs
PTAL @BusyJay @siddontang @andelf
> pd: reduce RwLockReadGuard lifetime

- benches/benches.rs
- benches/serialization/bench_serialization.rs
- benches/serialization/mod.rs
@BusyJay @zhangjinpeng1987 @siddontang PTAL
> bench: add serializtion bench case

- tests/raftstore/test_stats.rs
> tests: check snapshot in all nodes 

- etc/config-template.toml
- src/bin/tikv-server.rs
> tikv-server: cmd line options, deprecate --store, now use --data-dir

- Cargo.lock
> upgrade rocksdb to 5.2.1

- src/raftstore/store/store.rs
- src/util/mod.rs
> store: fix wrong deletion

- Cargo.lock
- etc/config-template.toml
- src/bin/tikv-server.rs
> add writable-file-max-buffer-size option

- src/raftstore/store/worker/apply.rs
PTAL @BusyJay @hhkbp2 @javaforfun
> worker: add log for delegate register and destroy.

- Cargo.lock
- Cargo.toml
Cc #1523
PTAL @siddontang @BusyJay @disksing
> Cargo: enable prometheus process feature

- src/raftstore/coprocessor/dispatcher.rs
- src/raftstore/coprocessor/mod.rs
- src/raftstore/coprocessor/split_observer.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/apply.rs
pre-apply is used to handle custom apply command.
> copr: support pre-apply

- src/storage/metrics.rs
> storage: enlarge histogram max duration

- Cargo.lock
- Cargo.toml
- src/pd/async/client.rs
- src/pd/mod.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/store.rs
- src/raftstore/store/worker/pd.rs
- src/server/resolve.rs
- tests/pd/test_rpc_client.rs
- tests/raftstore/pd.rs
> report written keys to pd

- src/pd/async/util.rs
- src/util/worker/future.rs
Timer will spawn a thread when initialized.
@siddontang @overvenus @disksing PTAL
> pd-client: reuse timer

- src/pd/async/util.rs
PTAL @BusyJay @siddontang @disksing
> pd: check cluster id while connecting to leader

- .travis.yml
- Cargo.lock
- circle.yml
- etc/config-template.toml
- src/bin/tikv-ctl.rs
- src/bin/tikv-server.rs
- src/raft/raft_log.rs
- src/raftstore/store/engine.rs
- src/raftstore/store/snap.rs
- src/raftstore/store/worker/compact.rs
- src/util/config.rs
- src/util/mod.rs
- src/util/rocksdb.rs
- tests/pd/test_rpc_client.rs
- travis-build/Makefile
> rc2.2: pick optimize for rocksdb

- Makefile
@siddontang @BusyJay @zhangjinpeng1987 PTAL
> Makefile: add static_unportable_release support

- .travis.yml
- Cargo.lock
- circle.yml
- docker/release_dockerfile
- docker/rust_dockerfile
- src/bin/tikv-ctl.rs
- src/bin/tikv-server.rs
- src/raft/raft_log.rs
- src/raftstore/store/msg.rs
- src/raftstore/store/peer.rs
- src/raftstore/store/snap.rs
- src/raftstore/store/worker/apply.rs
- src/raftstore/store/worker/compact.rs
- src/raftstore/store/worker/pd.rs
- src/raftstore/store/worker/region.rs
- src/server/coprocessor/endpoint.rs
- src/server/coprocessor/executor/scanner.rs
- src/server/kv.rs
- src/server/snap.rs
- src/storage/mvcc/reader.rs
- src/storage/mvcc/txn.rs
- src/storage/txn/scheduler.rs
- src/util/buf.rs
- src/util/codec/datum.rs
- src/util/config.rs
- tests/raft/test_raft.rs
- tests/raft/test_raw_node.rs
- tests/raftstore/cluster.rs
- tests/storage/test_storage.rs
- travis-build/Makefile
To upgrade rustc, use following command:
```
rustup override set nightly-2017-05-29
```
> *: upgrade rustc and clippy

- etc/config-template.toml
- src/bin/tikv-server.rs
> modify rocksdb default compression

- etc/config-template.toml
- src/bin/tikv-server.rs
PTAL @zhangjinpeng1987 @BusyJay
> add direct io config

- src/lib.rs
> lib.rs: remove unused crate

- src/bin/signal_handler.rs
Some daemon manager tools like goreman, foreman sends SIGHUP to terminate the process. 
PTAL @BusyJay @zhangjinpeng1987
> bin: capture SIGHUP

- src/server/node.rs
- tests/raftstore/test_bootstrap.rs
- tests/raftstore/test_compact_log.rs
On my machine, compaction tests take half time as before.
> tests: speedup compaction tests

- src/server/raft_client.rs
Default size limit of raft entry is 8m, but the default size limit for received message of grpc channel is 4m.
@siddontang @zhangjinpeng1987 @javaforfun PTAL
> transport: set message size limit for client

- Dockerfile
- docker/rust_dockerfile
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
> Dockerfile: use image digests for better determinism

- tests/storage/assert_storage.rs
- tests/storage/test_storage.rs
hi, 
This PR is used to fix test's bug cased by gc with `stale command`, the related issue is https://github.com/pingcap/tikv/issues/1740
@disksing @hhkbp2 PTAL
> tests:fix bug caused by gc with stale command

- src/pd/async/client.rs
Address the comment https://github.com/pingcap/tikv/pull/1712#discussion_r108858534
PTAL @andelf @BusyJay @siddontang
> pd: better Debug format

- tests/raftstore/test_transfer_leader.rs
Ensure follower progress before transferring leader.
close #1918.
> tests: ensure follower progress

- src/util/clocktime.rs
Hi,
This PR adds assert message for clocktime test case.
PTAL @siddontang @BusyJay @zhangjinpeng1987 @javaforfun
> util/clocktime: add assert message for test case

- .travis.yml
- src/raftstore/store/peer_storage.rs
- travis-build/Makefile
- add gperftools to install tcmalloc on macOS
- fix fail snapshot case
> travis: fix fail cases

- src/util/codec/mysql/json/binary.rs
- src/util/codec/mysql/json/comparison.rs
- src/util/codec/mysql/json/json_extract.rs
- src/util/codec/mysql/json/json_modify.rs
- src/util/codec/mysql/json/json_unquote.rs
- src/util/codec/mysql/json/mod.rs
- src/util/codec/mysql/json/path_expr.rs
- src/util/codec/mysql/mod.rs
Hi
This PR refactor directory mysql/json. 
@hhkbp2 @andelf @lishihai9017 PTAL
> mysql/json:refactor

- src/raft/log_unstable.rs
- src/raftstore/coprocessor/mod.rs
- src/util/codec/mysql/decimal.rs
Fixed some typos 
inproper => improper
zeroes => zeros
entris => entries
compareable => comparable
> Fix some typos

- src/raft/raft.rs
- src/raftstore/store/peer.rs
- tests/raft/test_raft.rs
- tests/raft/test_raw_node.rs
> raft: allow skip bcast commit

- src/raftstore/store/worker/metrics.rs
We need larger buckets to handle 1G region.
> metrics: adjust buckets

- src/util/codec/datum.rs
Hi,
This PR do some preparation in datum.rs for evaluate json functions.
@andelf @lishihai9017 @hhkbp2 @hicqu  PTAL
> codec/datum.rs:prepare for eval_json

- Cargo.lock
- src/raftstore/store/snap.rs
> update rocksdb and fix error

- benches/benches.rs
- benches/bin/bench-tikv.rs
- src/bin/tikv-ctl.rs
- src/bin/tikv-server.rs
- src/lib.rs
- tests/tests.rs
Issue https://github.com/Manishearth/rust-clippy/issues/1586 has already been fixed: https://github.com/Manishearth/rust-clippy/pull/1804
> clippy: remove todo about clippy#1586

- src/raftstore/store/transport.rs
- src/server/raft_client.rs
- src/server/transport.rs
- tests/raftstore/server.rs
- tests/raftstore/transport_simulate.rs
> grpc: turn buffer hint on.

- Cargo.lock
- src/bin/tikv-ctl.rs
> tikv-ctl: print region size

- src/server/server.rs
Fix #2008
cc @AndreMouche @javaforfun
> *: fix test_peer_resove test.

- src/raftstore/store/peer.rs
Diff sometimes can be negative. For example, apply a deletion immediately after being restarted.
> raftstore: fix diff hint overflow

- circle.yml
- docker/rust_dockerfile
- travis-build/Makefile
> update RocksDB v5.5.1

- Cargo.lock
- etc/config-template.toml
- src/bin/tikv-server.rs
> Enable pipelined write

- etc/config-template.toml
> add rate limit comment

- Cargo.lock
- etc/config-template.toml
- src/bin/tikv-server.rs
> Support max_compaction_bytes

- src/util/buf.rs
This pr fixes the fail test case reported in #1978.
> util: fix shrink buf

- etc/config-template.toml
- src/bin/tikv-server.rs
- src/util/config.rs
> add compaction priority

- src/raftstore/store/snap.rs
@zhangjinpeng1987 @siddontang @hhkbp2 PTAL
> snap refactor 3: use plain file for CF_LOCK and little tidy up

- src/raftstore/store/snap.rs
@zhangjinpeng1987 @siddontang PTAL
> snap: fix size_track compute

- Cargo.lock
- src/bin/tikv-server.rs
- src/raftstore/store/engine.rs
- src/storage/mvcc/reader.rs
- src/util/rocksdb.rs
> refactor options

- Cargo.lock
- circle.yml
- docker/rust_dockerfile
- etc/config-template.toml
- src/bin/tikv-server.rs
- travis-build/Makefile
@siddontang @zhangjinpeng1987 @follitude PTAL
> upgrade to rocksdb 5.6.1

- etc/config-template.toml
As the same in https://github.com/pingcap/docs-cn/pull/208
> config: update max-background-jobs as in docs-cn

- src/server/grpc_service.rs
- src/storage/mvcc/mod.rs
- src/storage/mvcc/txn.rs
- tests/storage/test_raft_storage.rs
> txn: more detailed errors.

- src/server/transport.rs
> transport: fix possible message delay

- tests/storage/assert_storage.rs
- tests/storage/test_storage.rs
Hi,
This PR fixed bug in `test_txn_store_gc3`, the related issue is https://github.com/pingcap/tikv/issues/1981
@disksing @zhangjinpeng1987 PTAL
> storage/test_storage:fix bug in test_txn_store_gc3

- src/coprocessor/xeval/builtin_math.rs
Implement `ceil_real()` function for `coprocessor/xeval`.
> add ceil_real in coprocessor/xeval

- src/bin/tikv-ctl.rs
Only print specified cf size.
@zhangjinpeng1987 PTAL
> tikv-ctl: print cf size

- Jenkinsfile
> jenkins: update Jenkinsfile to use rc4 branch for CI

- src/coprocessor/executor/index_scan.rs
- tests/coprocessor/test_select.rs
> coprocessor: fix bug caused by use box_try instead of try (#2130)

- src/raftstore/store/store.rs
The log will be very long and hard to see if we log the whole message, so here we just only log message type. 
@BusyJay @javaforfun
> use msg type instead of whole msg in log

- Jenkinsfile
> jenkins: update Jenkinsfile to use rc3 branch for CI

- src/coprocessor/dag/expr/mod.rs
Hi,
This PR updated the basic structure of expression.
@andelf @hicqu @BusyJay PTAL
> expr/mod: update expression

- src/bin/tikv-ctl.rs
@zhangjinpeng1987 @BusyJay PTAL
> tikv-ctl: add diff feature to check difference between two dbs

- src/util/threadpool.rs
@siddontang @BusyJay @zhangjinpeng1987 PTAL
> threadpool: remove unused types

- .travis.yml
- Cargo.lock
- benches/benches.rs
- benches/bin/bench-tikv.rs
- circle.yml
- docker/release_dockerfile
- docker/rust_dockerfile
- src/bin/tikv-server.rs
- src/coprocessor/dag/executor/selection.rs
- src/lib.rs
- tests/tests.rs
To update your local environment, please execute following command in tikv directory.
```
rustup override set nightly-2017-08-09
```
> *: update rustc to nightly-2017-08-09

- src/util/properties.rs
Collect rows count from CF_WRITE.
> add rows properties

- src/raftstore/store/worker/split_check.rs
- tests/raftstore/cluster.rs
- tests/raftstore/test_split_region.rs
Check approximate size before split check.
> Check approximate size before split check

- src/raftstore/store/store.rs
- src/raftstore/store/worker/pd.rs
- src/util/rocksdb/mod.rs
This PR is separated from #2120. 
PTAL @zhangjinpeng1987  @siddontang
> refactor store heartbeat

- Cargo.lock
- src/coprocessor/select/xeval/builtin_math.rs
- src/coprocessor/select/xeval/evaluator.rs
Hi, 
This PR updates tipb to newest version  and adjusts `ScalarFuncSig` in evaluator.
@BusyJay @hicqu @XuHuaiyu PTAL
> cargo:update tipb

- Cargo.lock
- src/util/rocksdb/engine_metrics.rs
> add more histograms

- src/util/rocksdb/engine_metrics.rs
- src/util/rocksdb/metrics_flusher.rs
PTAL @zhangjinpeng1987 @siddontang 
also fix some mistakes
> replace gauge with counter

- src/coprocessor/dag/executor/index_scan.rs
- src/coprocessor/dag/executor/table_scan.rs
> coprocessor: fix bug about reverse scan. (#2204)

- etc/config-template.toml
- src/coprocessor/endpoint.rs
- src/server/config.rs
- src/server/server.rs
- tests/coprocessor/test_select.rs
The value can be different in different situation. So let's make it configurable.
> endpoint: make max tasks configurable

- src/server/resolve.rs
- tests/coprocessor/test_select.rs
- tests/pd/mock/mocker/split.rs
- tests/raft/test_raft.rs
@BusyJay @zhangjinpeng1987 PTAL
> *: remove useless mut

- src/coprocessor/endpoint.rs
@zhangjinpeng1987 @siddontang PTAL
> endpoint: fix a divide zero bug

- tests/raftstore/test_snap.rs
- tests/raftstore/test_transfer_leader.rs
- remove snap_gc_timeout to prevent snapshot from gc too early.
- transfer leader first to make resolving happen early.
> tests: make some cases more stable

- README.md
> README: update status badge to Pre-GA

- src/coprocessor/dag/expr/builtin_op.rs
- src/coprocessor/dag/expr/fncall.rs
@BusyJay @hicqu @XuHuaiyu @hanfei1991 PTAL
> expr/builtin_op: implement bit operation

- src/storage/engine/mod.rs
- src/storage/engine/rocksdb.rs
- src/storage/txn/scheduler.rs
- tests/storage/sync_storage.rs
- tests/storage/test_storage.rs
It's a cherry-pick commit, see more #2253 .
> txn/scheduler: fix unwrap panic (#2253)

- src/coprocessor/dag/expr/builtin_op.rs
- src/coprocessor/dag/expr/fncall.rs
@BusyJay @hicqu @XuHuaiyu @hanfei1991 PTAL
> expr/builtin_op: implement int_as_true, decimal/real_as_false

- src/util/threadpool.rs
> threadpool: fix race (#2266)

- src/coprocessor/dag/expr/builtin_cast.rs
> expr/builtin_cast: fix bug in cast_str_as_int

- src/server/mod.rs
- src/server/server.rs
- src/server/service/kv.rs
- src/server/service/mod.rs
Move `grpc_service.rs` to mod service, futher grpc services can be added to here.
> server: move grpc_service to mod service

- src/raftstore/store/store.rs
The two removed statistics are not useful but may cause overflow, and it's not easy to fix for now, so we remove them.
Close https://github.com/pingcap/tikv/issues/2298
> Remove two overflow statistics

- etc/config-template.toml
- src/raftstore/store/config.rs
PTAL @BusyJay @overvenus @javaforfun
> tikv: use 96MB as the default region size
