src/pd/client.rs, src/util/mod.rs, tests/raftstore/server.rs
We should always call make_std_tcp_conn instead of TcpStream::connect in case we forget to call set_nodelay.
=> util: Add make_std_tcp_conn to create no_delay tcp connection.

src/util/mod.rs
=> util: Call set_nodelay on tcp connection by default.

src/server/kv.rs
Fix build: `Ok(None)` not covered
=> *:Revert last change to kv.rs.

benches/bin/bench-tikv.rs, tests/raftstore/cluster.rs, tests/raftstore/mod.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore/test_multi.rs, tests/raftstore/transport_simulate.rs, tests/tests.rs
SimulateTransport has a bundle of filters, while will do some addition work
before call the the underlying Transport to simulate bad network traffic,
such as Loss packet, Timeout, and so on.
=> tests/raftstore: add SimulateTransport for testing bad network traffic

tests/raftstore/cluster.rs
add a time cost error to check whether `resource temporary Unavailable` is caused by timeout or not. 
Now if we send a command to a not leader peer, the connection will be hung up then meet a timeout error. How do we handle this case in test?
=> raftstore: add cost for call command failed.

src/pd/client.rs, src/pd/mod.rs, src/pd/protocol.rs, src/server/node.rs, tests/raftstore/cluster.rs, tests/raftstore/pd.rs, tests/raftstore/pd_ask.rs, tests/raftstore/test_conf_change.rs
Now pd only supports one cluster, so all our commands should take cluster id.
@ngaut @BusyJay @qiuyesuifeng
=> *: fix pd alloc ID failed.

src/bin/tikv-server.rs, src/server/conn.rs, src/server/mod.rs, src/server/resolve.rs, src/server/server.rs, src/server/transport.rs, tests/raftstore/server.rs
We used pd get_store to get store address in send before, if pd is down, the event loop will be blocked for a long time.
So combine store address getting and host resolving together in another thread worker, and cache the store connection token using store_id. 
=> *: get store address asynchronously.

benches/bin/raftstore.rs, tests/raftstore/cluster.rs, tests/raftstore/test_compact_log.rs, tests/raftstore/test_conf_change.rs, tests/raftstore/test_multi.rs, tests/raftstore/test_single.rs, tests/raftstore/test_split_region.rs, tests/raftstore/test_tombstone.rs
error is usual in a distribute system. if we panic on error, we name
the api must_xxx, so caller won't get a surprise on that behavior.
=> tests/raftstore: rename panic api put/delete/seek etc to must_xxx

src/server/conn.rs, src/server/mod.rs, src/server/server.rs, tests/raftstore/cluster.rs
We can use shutdown write first after receiving the whole snapshot, see http://www.gnu.org/software/libc/manual/html_node/Closing-a-Socket.html .
=> *: use shutdown to close snapshot conn gracefully.

tests/raftstore/transport_simulate.rs
OutOfOrder is never needed before the code become more robust
=> *: surpress build warning

src/raftstore/store/msg.rs, src/raftstore/store/store.rs, src/server/mod.rs, src/server/node.rs, src/server/server.rs, src/server/transport.rs
Old resolving mechanism may cause the message disorder, e.g, we send 1, 2, 3, and 4 to store a.
+ put 1, 2, 3 to resolve thread.
+ resolve store a address successfully for message 1 and notify server.
+ create the token for store a and then send 1.
+ now 4 comes and use token for a directly.
+ 2 and 3 resolve ok and notify server, send 2, 3.
As you see, 4 is sent before 2 and 3.
To solve this, we can introduce a pending list, if the token doesn't exist, we push the message to pending list and then resolve the store address, after resolving ok, we send all messages in pending list first, then following messages using the same token can have the correct order. 
=> server: drop messages and report failed when resolving store address

tests/raftstore/cluster.rs
auto retry if response has error and the error is caused
by leader change or split
=> tests/raftstore: refact call_command_on_leader

src/lib.rs
https://github.com/tailhook/quick-error/issues/22
=> lib: allow define more errors.

src/raft/raft.rs, src/raftstore/store/peer.rs
Currently, the log inside of raft module has no relationship with region. It's hard to find out which region that the raft belongs to. We need a simply way to handle this problem without change the implementation of raft.
=> *: add tag for logging and debugging

tests/raftstore/test_pd.rs
Origin 100ms may be too short, increase to 500ms.
If the following check failure still happens, I will look it again. 
=> raftstore: increase the wait time.

benches/bin/mvcc.rs, src/server/coprocessor.rs, src/server/kv.rs, src/storage/engine/raftkv.rs, src/storage/engine/rocksdb.rs, src/storage/mod.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs, src/storage/txn/store.rs, src/storage/types.rs, tests/coprocessor/test_select.rs
Always encode keys from client, in order to guarantee that the key is memory-comparable and safe to append mvcc ts.
@BusyJay
=> storage: encode keys from client

src/bin/tikv-server.rs, src/pd/mod.rs, src/pd/protocol.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/pd.rs, src/server/node.rs, src/server/resolve.rs, tests/raftstore/cluster.rs, tests/raftstore/node.rs, tests/raftstore/pd.rs, tests/raftstore/pd_ask.rs, tests/raftstore/server.rs, tests/raftstore/test_conf_change.rs, tests/raftstore/test_pd.rs, tests/raftstore/test_split_region.rs, tests/raftstore/test_tombstone.rs
Real RPC pd will handle mutability internally, no need `mut` in trait.
=> *: cleanup pd.

docker/rust_dockerfile
Modified Dockerfile to support rocksdb options tuning of [#597](https://github.com/pingcap/tikv/pull/597)
=> docker: upgrade rocksdb version to 4.5.1, and add lz4 support

src/bin/tikv-server.rs
Set opts.set_max_bytes_for_level_base to 64MB.
Make data importing process stable.
@ngaut
=> tikv-server: Tune rocksdb options

src/storage/engine/mod.rs, src/storage/mvcc/txn.rs
We use dynamic dispatch already, so generic is redundant.
=> storage: cleanup

Cargo.lock, Cargo.toml, etc/config-template.toml, src/bin/tikv-server.rs, src/util/mod.rs, src/util/rocksdb_option.rs
#601 
-----
The getopts in crate.io is outdated, use the latest getopts instead. In the old version getopts, It seems like there is no way to avoid panic if short is not defined.
=> Add rocksdb configs

src/util/metric/macros.rs, src/util/mod.rs
Most of time, we will use time::Duration to timing.
=> *: use duration for metric time.

docker/rust_dockerfile
The current build of librocksdb.so is optimized for the host/kernel on which it is originally built; this can cause problems on a host that doesn't support the same CPU feature set, resulting in core dumps and messages like this in dmesg:
traps: tikv-server[16153] trap invalid opcode ip:7fe833fc9610 sp:7ffccbd12340 error:0 in librocksdb.so.4.5.1[7fe833e80000+373000]
The [official INSTALL.MD](https://github.com/facebook/rocksdb/blob/master/INSTALL.md) talks about this: 
> By default the binary we produce is optimized for the platform you're compiling on (-march=native or the equivalent). If you want to build a portable binary, add 'PORTABLE=1' before your make commands, like this: **PORTABLE=1** make static_lib
=> build portable version of rocksdb's shared library

tests/test_raft.rs
port from etcd https://github.com/coreos/etcd/pull/5414
=> raft: fix tiny mistake of message type

tests/raftstore/cluster.rs, tests/raftstore/server.rs
When retry split, leader may have changed.
=> tests: reset leader when retry split

src/raft/raft.rs, src/raft/raft_log.rs, src/raft/raw_node.rs, src/raft/storage.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/worker/snap.rs, tests/test_raft.rs, tests/test_raw_node.rs
Arc is an unnecessary constraint, so remove it.
And after this pr, RaftStorage becomes clone-able, which will be handy when doing snapshot.
=> raft: remove arc

etc/config-template.toml, src/bin/tikv-server.rs, src/raftstore/store/config.rs, src/raftstore/store/store.rs, src/server/config.rs, src/server/server.rs, tests/raftstore/server.rs, tests/raftstore/util.rs
Default capacity for notify queue is 4096, which is small when region count increase to more than 7000.
=> raftstore: enlarge default notify queue capacity

Cargo.lock, Cargo.toml, src/raftstore/coprocessor/dispatcher.rs, src/raftstore/coprocessor/mod.rs, src/raftstore/coprocessor/region_snapshot.rs, src/raftstore/coprocessor/split_observer.rs, src/raftstore/store/engine.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/snap.rs, src/raftstore/store/worker/snap.rs, src/storage/engine/raftkv.rs, tests/raftstore/cluster.rs, tests/raftstore/mod.rs, tests/raftstore/server.rs, tests/storage/mod.rs, tests/storage/test_raftkv.rs, tests/tests.rs
Remove lifetime of snapshot to make code more clean and make it easy to merge snapshot generation into snapshot manager later.
=> [DNM] *: remove lifetime of snapshot

src/server/conn.rs, src/server/mod.rs, src/server/server.rs, src/server/snap.rs
Currently snap status is reported when all data is received by the follower. But this may lead to generate snapshot multiple times. So we should report status after snapshot is scheduling to store. This will make sure further append message is handled after snapshot is applied.
=> server: report status after snap is scheduling to store

src/raftstore/store/peer.rs, src/raftstore/store/store.rs, tests/raftstore/cluster.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore/test_conf_change.rs, tests/raftstore/test_multi.rs, tests/raftstore/test_split_region.rs, tests/raftstore/test_stats.rs, tests/raftstore/test_transport.rs, tests/raftstore/transport_simulate.rs
When a follower with uncommitted log becomes leader and then propose a message immediately, the callback of the message will be considered as stale callback, which apparently is not.
This pr will take term into consideration, and hold the callback queue when applied entry's term is less than the callback's term.
=> raftstore: fix possiblely calling the wrong callback

src/raftstore/store/config.rs, src/raftstore/store/mod.rs, src/raftstore/store/msg.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/snap.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/snap.rs, src/server/snap.rs, tests/raftstore/cluster.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore/test_snap.rs, tests/raftstore/test_stats.rs, tests/raftstore/transport_simulate.rs, tests/test_raft.rs
It's hard and tricky to make sure snap file not leak when using ref count. So this pr changes to use GC to delete stale snap files.
=> raftstore: use gc to delete snap files

src/raft/log_unstable.rs
See https://github.com/coreos/etcd/pull/5803
=> raft: truncateAndAppend no need the value of 'after' with subbing one

src/raftstore/store/peer.rs, tests/raftstore/pd.rs, tests/raftstore/test_multi.rs, tests/raftstore/test_transport.rs
Clear callback when peer is destroyed, which will make client retry quickly.
=> raftstore: clear callback when destroy peer

src/bin/tikv-server.rs, src/util/metric/mod.rs
A buffered metric sink with a pseudo timeout mechanism.
Benchmark([link](https://gist.github.com/overvenus/31b3adba8d60fbc81325a958a0e9fc9d)):
```
➜  bench_metric git:(master) ✗ cargo bench bench_single                   
Running target/release/bench_metric-b6de8d742c9d8b0f
running 3 tests
test tests::bench_single_thread_block_udp    ... bench:       3,492 ns/iter (+/- 137)
test tests::bench_single_thread_buffer_udp   ... bench:         135 ns/iter (+/- 4)
test tests::bench_single_thread_nonblock_udp ... bench:       3,487 ns/iter (+/- 530)
test result: ok. 0 passed; 0 failed; 0 ignored; 3 measured
```
3 threads send 15000 metrics concurrently.
```
➜  bench_metric git:(master) ✗ cargo bench bench_multi_thread_block_udp
Running target/release/bench_metric-b6de8d742c9d8b0f
running 1 test …
```
=> util: add buffered metric client

src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs
+ Re-add snapshot to SnapState to make snapshot handing simply. 
+ Snapshot use immutable interface. 
I will remove Storage RefCell later, so we don't need to write `get_store().wl()/rl()`, and we can use storage fields like region outer directly, no need clone again. 
=> store: update snapshot, use immutable interface.

src/raft/raft.rs, src/raft/raft_log.rs, src/raft/raw_node.rs, src/raftstore/store/mod.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs
=> raft/raftstore: use PeerStorage directly, remove rl/wl.

src/raftstore/store/store.rs, src/server/resolve.rs, src/server/server.rs, src/util/worker/mod.rs, tests/coprocessor/test_select.rs, tests/raftstore/util.rs
Shutdown all the worker thread and store thread concurrently, which will speed up shutdown and avoid peer timeout when it takes long time to shutdown worker pool.
=> *: speedup shutdown

src/raft/progress.rs
=> raft: do not change RecentActive when resetState for progress.

src/server/conn.rs, src/server/snap.rs, src/util/codec/rpc.rs
Currently, recv buffer will be recreated every time a new message is arrived. This may cause unnecessary allocate and read.
ref: #821 
=> server: reuse recv buffer

.travis.yml, Cargo.lock, etc/config-template.toml, src/bin/tikv-server.rs, src/util/rocksdb.rs, travis-build/Makefile
Rocksdb has many different ways to open a db, let's have a look at the following two ways, 1) open db with the specified "name"; 2) open db with column families. The functions is declared as follows:
```
static Status Open(const Options& options, const std::string& name, DB** dbptr); 
static Status Open(const DBOptions& db_options, const std::string& name,
const std::vector<ColumnFamilyDescriptor>& column_families,
std::vector<ColumnFamilyHandle*>* handles, DB** dbptr);
```
Let's focus on the type of first parameter, they are different. Type Options is a wrapper, it is drived from DBOptions and ColumnFamilyOptions. DBOptions is used to control the behavor of db, like log directory, wal directory, max wal size, max background compaction threads and so on. ColumnFamilyOptions is used to …
=> bin/util: make column families's options work

travis-build/Makefile
The latest rustc-nightly seems consume too much memory and the compiled binary often hangs in ci, so let's keep using a less latest version.
=> ci: use fixed version rustc

src/storage/mvcc/reader.rs, src/storage/mvcc/txn.rs, src/storage/mvcc/write.rs
@siddontang @zhangjinpeng1987
The bug is mentioned in #921
=> storage/txn: append write cf when commit lock-only keys.

Cargo.toml, build.rs, src/bin/tikv-server.rs, src/util/mod.rs
Resolve #950 
This PR uses `build.rs`, however we can compute the build date and hash in Makefile and pass them to tikv as environment variables. I choose `build.rs` because this is how we do things in rust.
=> *: add version information

src/util/codec/datum.rs, src/util/codec/mysql/mod.rs, src/util/codec/mysql/mydecimal.rs
Because TiDB has enable the new decimal implementation but not TiKV, push down won't work when Decimal is involved. This is a quick fix for this incompatibility. But please note that it still won't work when you are using aggregation functions like `sum` or `average`.
=> copr: quick fix for decimal incompatibility

src/storage/types.rs
As I read the source code, I'll keep adding rustdoc for public interfaces and comments for internal implementations. No functional changes.
=> Add rustdoc for core types.

travis-build/test.sh
In case we forget to fix some warnings or the code may not pass the latest rust compiler check or clippy lint, we should treat all warnings as error when checking on CI.
=> ci: treat warning as err on ci

src/bin/tikv-server.rs
write's cf don't need point get, so we remove bloom filter; the amount of data of write cf is according to default cf, so we adjust write cf's block-cache-size according to default cf's block-cache-size(reduce memory usage); write is not heavy for this cf, so the default value of level0_slowdown_writes_trigger&&level0_stop_writes_trigger is enough.
=> tunning write cf

src/util/file_log.rs
Currently the suffix of rotating log file is the day that log file rotation actually happens, which is one day after the logs happen.
```text
-rw-rw-r-- 1 tidb tidb 1978421 8月  30 14:23 pd.log
-rw-rw-r-- 1 tidb tidb   12991 8月  29 23:59 pd.log.20160829
-rw-rw-r-- 1 tidb tidb 2081968 8月  30 14:23 tidb.log
-rw-rw-r-- 1 tidb tidb   53407 8月  29 23:59 tidb.log.20160829
-rw-rw-r-- 1 tidb tidb  429948 8月  30 14:23 tikv.log
-rw-rw-r-- 1 tidb tidb    9731 8月  29 23:59 tikv.log.20160830
```
This PR revises the suffix of rotating log file name for TiKV to the day when logs happen to make it consistent with TiDB and PD.
=> util: fix rotating log file name

src/util/mod.rs
`"`, `\` and `\x5d...\x7e` are overlapped.
=> util: make clippy88 happy

src/storage/txn/mod.rs, src/storage/txn/scheduler.rs, tests/storage/test_storage.rs
If region has no key or key number is multiple of 512, the scan could loop forever.
@siddontang @zhangjinpeng1987
=> gc: stop scan when there is no more keys.

src/raftstore/store/config.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/util.rs, src/raftstore/store/worker/metrics.rs, src/raftstore/store/worker/pd.rs, tests/raftstore/mod.rs, tests/raftstore/test_stale_peer.rs
=> raftstore/*: gc stale peer out of region

Cargo.lock, Cargo.toml, src/bin/tikv-server.rs
ref: https://github.com/pingcap/tikv/issues/1053
=> bin: handle TERM/INT signal

src/bin/tikv-server.rs
Use SIGUSR1 to dump the metrics.
=> bin: use SIGUSR1 to dump metrics.

src/raftstore/store/worker/compact.rs
Before we figure out why data lost when tikv-server been killed, we should enable WAL.
=> worker: enable WAL

src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/mod.rs, src/raftstore/store/worker/region.rs
Currently snapshot worker applies snapshot in single thread, it's safe to just schedule destroy task to that thread too. Hence the raftstore thread won't be blocked when deletion takes too long time to finish.
=> store: async destroy region

Cargo.lock, etc/config-template.toml, src/bin/tikv-server.rs, src/raftstore/store/engine.rs, src/util/config.rs
make rocksdb recovery mode configurable
=> make rocksdb recovery mode configurable

Cargo.lock, src/bin/tikv-server.rs, src/raftstore/coprocessor/region_snapshot.rs, src/raftstore/store/engine.rs, src/raftstore/store/worker/region.rs, src/storage/engine/mod.rs, src/storage/engine/raftkv.rs, src/storage/engine/rocksdb.rs, src/storage/mvcc/reader.rs, tests/storage/test_raftkv.rs
Add upper bound for iterator to speed up region scan when there are a lot of deleted keys.
=> add upper bound for iterator

src/storage/mvcc/reader.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs, src/storage/txn/store.rs
reuse iterator when MvccReader is mainly used for scan
=> reuse iterator when MvccReader is mainly used for scan

src/raftstore/store/metrics.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs
metric tikv_storage_engine_async_request_duration_seconds_bucket can
cover it, duplicated.
@ngaut @BusyJay @disksing @hhkbp2 @overvenus
=> store: clear PEER_DO_COMMAND_HISTOGRAM

Cargo.lock, etc/config-template.toml, src/bin/tikv-server.rs
When debugging performance, we can get more details of rocksdb by enable rocksdb's statistics. 
```
** Level 0 read latency histogram (micros):
Count: 7384 Average: 8.5678  StdDev: 6.53
Min: 0  Median: 7.0683  Max: 212
Percentiles: P50: 7.07 P75: 8.53 P99: 19.55 P99.9: 132.32 P99.99: 212.00
------------------------------------------------------
[       0,       1 )       20   0.271%   0.271%
[       1,       2 )        6   0.081%   0.352%
[       2,       3 )      162   2.194%   2.546%
[       3,       4 )      501   6.785%   9.331% #
[       4,       5 )      294   3.982%  13.313% #
[       5,       6 )     1036  14.030%  27.343% ###
[       6,       7 )     1569  21.249%  48.592% ####
[       7,       8 )     1523  20.626%  69.217% ####
[       8,       9 )      807  10.929%  80.146% ## …
```
=> make rocksdb statistics configurable

src/server/coprocessor/endpoint.rs, src/server/coprocessor/metrics.rs
It only handles response, and is very fast here. So no need using Histogram metric here. 
@BusyJay @hhkbp2 @overvenus @zhangjinpeng1987
=> coprocessor: remove unnecessary metric.

src/storage/mvcc/reader.rs, tests/raftstore/util.rs
=> reuse iterator

src/raftstore/coprocessor/region_snapshot.rs, src/raftstore/store/keys.rs, src/raftstore/store/util.rs, src/server/coprocessor/endpoint.rs, src/storage/engine/mod.rs, src/storage/engine/raftkv.rs, src/storage/engine/rocksdb.rs, src/storage/mod.rs, src/storage/mvcc/reader.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs, src/storage/txn/store.rs, src/util/codec/table.rs, tests/storage/test_raftkv.rs
This pr contains two improvements:
1. When doing heavy scan, the lock cursor will just scan forward(or backward), so we can save some unnecessary backward (or forward) move by checking if current cursor is doing linear seek;
2. Cursor has a consistent view to the underlying data, so once failed to seek a key, any key larger than the key can't be seek too, so we can add a bound check.
=> storage/cursor: add bound and linear check

Makefile
Now the default OSX image [has upgrade to Xcode 7.3](https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/), the SIP [is enabled](https://github.com/travis-ci/travis-ci/issues/5819#issuecomment-212064301) by default, which will wipe out all custom environment variables that starts with `DYLD_` when exec a subshell. So we need to set `DYLD_LIBRARY_PATH` in subshell too.
=> travis: fix linking

src/bin/tikv-server.rs, src/server/config.rs, src/server/mod.rs
Using default cluster id 0 if there is no `cluster-id` present. This allows users to start a tikv without any command line arguments.
PTAL @siddontang @BusyJay 
/cc @iamxy
=> bin, server: using default cluster id

tests/raftstore/test_multi.rs, tests/raftstore/test_snap.rs, tests/raftstore/transport_simulate.rs
=> test/raftstore: add random latency filter for simulation transport

src/raftstore/store/peer_storage.rs
Currently almost every call to term will invoke `rocksdb::get`. This pr reduce the call times by caching the term of last_index. If `truncated_term` is equal to `last_term`, then every entry between truncated_index and last_index should have the same term.
=> raftstore: cache term

Makefile
It is not easy to remember the environments for static build, so we support static build directly in Makefile. 
@ngaut @BusyJay @disksing  @hhkbp2
=> makefile: support static release build.

Cargo.lock, src/server/coprocessor/aggregate.rs, src/server/coprocessor/endpoint.rs, src/util/codec/datum.rs, src/util/codec/mod.rs, src/util/codec/mysql/time.rs, src/util/codec/table.rs, src/util/xeval/evaluator.rs, src/util/xeval/mod.rs
We need to compare string with timestamp sometimes, it will get a wrong result if not taking timezone into consideration.
=> copr: support timezone (fixed offset)

docker/release.sh, docker/release_dockerfile
This pr speeds up release build process by:
1. cache the dependencies needed for building tikv-server, so it doesn't have to download it every time;
2. let user reuse build cache, this will be useful when trying to build a release binary several times.
@siddontang @iamxy PTAL
=> docker: speedup release build

src/raftstore/coprocessor/region_snapshot.rs, src/raftstore/store/keys.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, tests/raftstore/test_stale_peer.rs
Currently when destroying a region, it will not check if itself is initialized. This may delete the whole data on store. To fix this, first we should check if a region is initialized before destroying data; second we should panic when encoding `start_key` or `end_key` for an uninitialized region.
@siddontang @hhkbp2 @zhangjinpeng1987 @disksing PTAL
=> raftstore: avoid deleting other region's data accidentally

src/server/coprocessor/endpoint.rs, src/server/coprocessor/metrics.rs
+ Origin 101 and 102 is not readable in metric, use string instead.
+ Using one metric with two labels is enough. 
@ngaut @BusyJay @hhkbp2  @overvenus
=> coprocessor: simplify metric.

src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/pd.rs, tests/raftstore/test_stale_peer.rs
Now pd support fetch region info via region id, we can use this API to simplify stale region check.
=> raftstore: check stale region with region id

src/lib.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/region.rs
When the applying snapshot job is in queue, it can be canceled directly. So we won't block any rebalance procedure.
@siddontang @hhkbp2 @zhangjinpeng1987  PTAL
=> raftstore: speed up canceling applying snap

etc/config-template.toml, src/storage/config.rs
When drop a table, TiDB will delete all keys in a background worker, every delete task generated by the bg worker contains 1024 keys. Currently the default scheduler's latches size is 1024, this is a bit too small, a delete task might hold all the latches and would block the others write commands.
=> tunning scheduler latches size

src/pd/mod.rs, src/pd/protocol.rs, src/raftstore/store/worker/pd.rs, src/server/resolve.rs, tests/pd/test_rpc_client.rs, tests/raftstore/cluster.rs, tests/raftstore/pd.rs, tests/raftstore/test_conf_change.rs
Currently get_region_by_id will return an empty region if not found, which is very easy to lead to mistake. An explicit Option should be returned instead.
@huachaohuang @siddontang PTAL
=> pdclient: adjust get region by id

src/raftstore/store/snap.rs
If temporary file is not cleaned up and there is no new data written in, the snapshot may not be able to be generated or received again.
=> raftstore: clean temporary file when startup

src/server/conn.rs, src/storage/txn/scheduler.rs
ref https://github.com/pingcap/tikv/issues/1203
Shrink send buffer to default size after a big query has returned.
=> shrink send buffer after a big query

src/server/coprocessor/endpoint.rs, src/storage/mvcc/reader.rs, src/storage/txn/scheduler.rs, src/storage/txn/store.rs
Sometimes values can be too large to do efficient scan. So if we don't need values when doing scan (like just want to get all the handles, naive count or index scan), it will be more efficient to skip fetching values and just scan the WRITE and LOCK cf.
@disksing @zhangjinpeng1987 PTAL
=> storage: skip value when possible

src/bin/tikv-ctl.rs, src/raftstore/store/config.rs, src/raftstore/store/msg.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/compact.rs, tests/raftstore/mod.rs, tests/raftstore/test_compact_after_delete.rs
For issue https://github.com/pingcap/tikv/issues/1179
Note: 
This PR does not count deleted keys when GC executes,  but count it when the raft command applies.
A counter is managed for each Peer and it is checked periodically by RaftStore.
@zhangjinpeng1987 @siddontang @BusyJay
=> raftstore: manually compact region after delete a lot of keys.

etc/config-template.toml, src/bin/tikv-server.rs
1. Split/ChangePeer will be reported to PD immediately.
2. PD's balancer will not schedule the same region in 2 minutes.
So, increase the heartbeat interval to 60s should not affect
the current behavior.
=> config: increase default pd-heartbeat-tick-interval

etc/config-template.toml, src/bin/tikv-server.rs, src/lib.rs, src/server/mod.rs, src/server/resolve.rs, src/storage/engine/mod.rs, src/storage/mod.rs, src/storage/mvcc/txn.rs, tests/coprocessor/test_select.rs
Fix #1206 
PTAL @siddontang @BusyJay 
Note:
After this PR, we should update tikv startup script by removing `-S raftkv`. But you don't have to make changes if use a config file before. @iamxy @nolouch @shenli
=> server: remove local rocksdb dsn.

src/raftstore/store/msg.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/region.rs, tests/raftstore/cluster.rs, tests/raftstore/test_stale_peer.rs
When snapshot is applied successfully asynchronously, it will send back a notification to store. If store is blocked by some work, it will fail to push the notification to queue, which can lead to panic. This pr use atomic flag to control the snapshot progress instead, so snapshot report doesn't have to join the crowded raftstore message queue.
=> raftstore: use atomic to control snapshot progress

etc/config-template.toml, src/bin/tikv-server.rs
ref https://github.com/pingcap/tikv/issues/1214
If RocksDB's max-open-files is -1 (the default value), RocksDB will prefetch index and filter blocks into block cache when open db, this may takes several minutes to startup TiKV when the database has a large working set.
https://github.com/facebook/rocksdb/blob/master/table/block_based_table_reader.h#L88
https://github.com/facebook/rocksdb/blob/master/db/version_set.cc#L2296
=> set max-open-files

src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/compact.rs, tests/raftstore/test_compact_log.rs
Record last compacted position for last raft compact task, so the later compact task no need to seek to first raft entry.
Maybe we need more discussion, @siddontang what's your suggestion? 
@ngaut @siddontang @BusyJay @disksing  PTAL
=> record last compacted position

src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs
When the snapshot can be canceled directly, the peer_storage's snap_state should be updated.
=> raftstore: fix apply check

src/raftstore/store/snap.rs, src/raftstore/store/store.rs
Snapshot directory's size should be included in used size too. Hence the capacity limit won't be violate.
@siddontang @huachaohuang PTAL
=> raftstore: include snap size into used_size

src/raftstore/store/config.rs
Default election timeout is too small. When some peer is slow at some point, an election will occur very quickly, which makes the system not very stable.
=> raftstore: slow down heartbeat and election

src/raftstore/store/peer.rs, tests/raftstore/pd.rs, tests/raftstore/test_snap.rs
In some rare cases, a snapshot and following committed entries will arrived at follower at once. Because we didn't check whether the peer is applying a snapshot when applying committed entries, it may lead to data inconsistency.
=> raftstore: fix potential data inconsistency

src/storage/mod.rs, src/storage/mvcc/reader.rs, src/storage/txn/mod.rs, src/storage/txn/scheduler.rs, tests/storage/test_storage.rs
Resolve locks by batches to avoid generating a too huge write raft command.
=> scheduler: resolve lock by batches.

tests/raftstore/test_stale_peer.rs, tests/raftstore/util.rs
This PR extracts the test raftstore config for peer gc into its `util` contructor.
=> tests/raftstore: add config for test raftstore

src/bin/tikv-ctl.rs, src/storage/mvcc/lock.rs, src/storage/mvcc/write.rs
Sometimes the key we want to use is from the tikv log or rocksdb, add a new flag to support both encoded/unencoded key.
@mrmiywj @BusyJay
=> tikv-ctl: mvcc support both encoded/unencoded key.

src/bin/tikv-server.rs, src/lib.rs, src/util/config.rs
This PR check various system parameters before TiKV startup.
Panic when those check failed:
* the maximum number of open file descriptors
Warn when those check failed:
* net.core.somaxconn
* net.ipv4.tcp_syncookies
* vm.swappiness
Close #1263 
PTAL @siddontang  @BusyJay  @ngaut
=> Check system parameters before startup

src/storage/mvcc/reader.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs, src/storage/txn/store.rs
ref https://github.com/pingcap/tikv/issues/1244
InnoDB use LRU list to cache pages, the LRU list is split into old list and new list two parts, when a page is read from disk, it will be added to the new list, when the page is readed again it will be moved to the old list, SQL like `select * from t` will just flush the new part of LRU, this will not decrease the cache hit rate a lot.
RocksDB use a LRU list to cache blocks, and use `ReadOptions.fill_cache` to control the behavior of fill cache or not. MyRocks has a session variable named `skip_fill_cache`, the default value is false, it means always fill cache, when user set `skip_fill_cache=true`(eg. dump the database), blocks will not fill cache.
Currently we fill cache just depend on the operation's type, if it is a scan operation we …
=> fill cache

.travis.yml, benches/bin/bench-tikv.rs, src/lib.rs, tests/tests.rs, travis-build/Makefile, travis-build/test.sh
`recv_timeout` is not stable in old nightly rustc, so we need to enable the feature explicitly. This pr also add a CI entry to make sure new code should work with old nightly rustc.
=> ci: fix compile error with old nightly rustc

src/raftstore/store/worker/metrics.rs
We don't need const label now.
@BusyJay @overvenus
=> worker: remove unnecessary const label.

src/storage/mvcc/mod.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs, tests/storage/test_storage.rs
To prevent creating a too big raftlog entry.
@siddontang @zhangjinpeng1987
=> scheduler, mvcc: limit writebatch size for ResolveLock and GC command.

src/raftstore/store/peer.rs, tests/raftstore/test_multi.rs
If there is no leader in the raft group or the leader is doing leader transferring, it will drop the proposal silently. If there is no further proposal, the pending command may be kept in queue for ever.
=> raftstore: check if message is discard after proposal

etc/config-template.toml, src/bin/tikv-server.rs
Enlarge scheduler latches bucket. Large bucket is more friendly for load data.
=> enlarge scheduler latches bucket

src/bin/tikv-server.rs
If `addr` is `0.0.0.0` then `advertise-addr` is required.
Also `0.0.0.0` is not allowed in `advertise-addr`.
Close #1332 
=> bin: check listen address and advertise address

src/server/coprocessor/aggregate.rs, tests/coprocessor/test_select.rs
ref: pingcap/tidb#2057
@siddontang @coocood PTAL
=> copr: aggr null for first

src/raftstore/store/peer.rs, src/raftstore/store/store.rs
So we can let all peers send raft message first, then do raft apply.
PTAL @ngaut @BusyJay @hhkbp2 @zhangjinpeng1987
=> raftstore: split handle ready to append + apply

src/storage/engine/metrics.rs
add `le` 4.096 and 8.192 so we can know the long command time better. 
@ngaut @BusyJay @hhkbp2
=> engine: enlarge buckets

src/storage/mvcc/txn.rs, tests/storage/test_storage.rs
If we stop iterating all mvcc versions due to `MAX_TXN_WRITE_SIZE` limit, we should not delete latest delete before safePoint.
/cc @siddontang @zhangjinpeng1987 @ngaut
=> mvcc: fix gc bug.

src/raft/raft.rs, tests/test_raw_node.rs
#1240 
MsgReadIndex, as MsgProp, is to be forwarded to leader.
So we should treat it as local message.
@siddontang  @BusyJay @disksing
=> raft: do no attch term to MsgReadIndex

src/bin/tikv-server.rs
Origin only dump default cf stats, but we need to dump all cf's.
@ngaut @zhangjinpeng1987 @disksing
=> bin: dump all cf stats and db stats.

travis-build/Makefile
So clearing cache won't cause an upgrade of rustfmt.
@siddontang @ngaut PTAL
=> ci: use fixed version rustfmt

Cargo.lock, Cargo.toml, etc/config-template.toml, src/bin/tikv-server.rs, src/raftstore/store/config.rs, src/raftstore/store/engine.rs, src/raftstore/store/metrics.rs, src/raftstore/store/msg.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/consistency_check.rs, src/raftstore/store/worker/metrics.rs, src/raftstore/store/worker/mod.rs, src/raftstore/store/worker/region.rs, tests/raftstore/test_multi.rs
=> raftstore: support consistency check

src/pd/client.rs, src/pd/protocol.rs, tests/pd/test_rpc_client.rs, travis-build/test.sh
`validate_pd_list` only accepts PD endpoints that are in the same PD cluster. It treats a removed PD as an invalied PD node. ~~It only validates once at the beginning of raftkv startup.~~ It validates the list every time when the tikv trys to connect a PD.
---
Let's say there are two PD clusters, one consists three nodes, and the other is a standlone node. Details: 
```
cluster-id: 1
pd1 client urls: "127.0.0.1:12379"
pd2 client urls: "127.0.0.1:22379"
pd3 client urls: "127.0.0.1:32379"
```
```
cluster-id: 1
pd1 client urls: "127.0.0.1:42379"
```
Following are cases tested so far:
``` rust
("127.0.0.1:12379,127.0.0.1:22379,127.0.0.1:32379".to_owned(), true),
("127.0.0.1:12379, 127.0.0.1:22379, 127.0.0.1:32379".to_owned(), true),
("127.0.0.1:12379, 127.0.0.1:22379, …
```
=> pd: validate PD list

etc/config-template.toml, src/bin/tikv-server.rs
So the split interval can be changed without recompilation.
=> raftstore: expose split interval

etc/config-template.toml, src/bin/tikv-server.rs, src/raftstore/store/config.rs, src/raftstore/store/store.rs, tests/raftstore/test_compact_after_delete.rs, tests/raftstore/test_compact_lock_cf.rs
tikv-server will convert all readable int to millis, so we should treat all intervals as millis.
@siddontang @zhangjinpeng1987 @disksing  PTAL
=> config: use millis for all interval

tests/raftstore/cluster.rs
In the past when a command is dropped, it will return NotLeader error and tests will retry in this cases. After pr #1328, StaleCommand is returned instead of NotLeader.
=> tests: retry when get StaleCommand error

src/raftstore/store/store.rs
When want to enable consistency check, it should be registered when startup.
=> raftstore: register consistency check

Cargo.toml
When setting codegen-units, rustc will split the crate into several module and passing it to llvm in parallel. Debug build time is decreased about 15% on my machine, 18% on travis ci.
@siddontang @disksing @iamxy PTAL
=> build: speedup debug build

Cargo.lock, src/pd/mod.rs, src/pd/protocol.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/pd.rs, src/server/resolve.rs, tests/raftstore/mod.rs, tests/raftstore/pd.rs, tests/raftstore/test_region_heartbeat.rs, tests/raftstore/transport_simulate.rs
ref pingcap/pd#124
@siddontang @huachaohuang @hhkbp2 PTAL
=> raftstore: report pending peers

src/util/codec/table.rs, tests/raftstore/test_compact_log.rs, tests/raftstore/test_region_heartbeat.rs
Make clippy happy:
1. called `.get().unwrap()` on a HashMap. Using `[]` is more clear and more concise.
2. remove unused import.
=> make clippy happy

etc/config-template.toml, src/bin/tikv-server.rs
Disable data sync when loading data. The contents of manifest and data files are not synced to stable storage when disable-data-sync is true.
@siddontang @ngaut PTAL
=> Disable data sync when loading data

Cargo.lock, Cargo.toml, src/server/kv.rs, src/storage/mod.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs, tests/storage/sync_storage.rs, tests/storage/test_raft_storage.rs
Skip constraint check for prewrite when loading data.
@siddontang @BusyJay @disksing PTAL
=> txn: skip constraint check for prewrite when loading data

etc/config-template.toml, src/bin/tikv-server.rs
When `cache_index_and_filter_blocks` is off, each `table reader` object will pre-load index/filter block during table initialization, this will takes extra memory to hold the index/filter blocks.
=> cache index and filter blocks in block cache

src/bin/tikv-ctl.rs, src/bin/tikv-server.rs, src/storage/mod.rs, src/storage/mvcc/lock.rs, src/storage/mvcc/reader.rs, src/storage/mvcc/txn.rs, src/storage/mvcc/write.rs
In TiKV's MVCC model, content is stored in `default cf` of rocksdb, and commit info is stored in `write cf` of rocksdb, when the content is very short, the space amplification is no-negligible. The key of table index usually 30 or more bytes, and the value of table index is 1 byte or 8 bytes, the space amplification is about 2. So we store short value along with commit info in `write cf` of rocksdb.
@siddontang @BusyJay @disksing PTAL
=> optimize for short value

src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs
When there are multiple readies to be handled, we can write them to disk at once instead of one per ready.
=> raftstore: handle raft ready in batch

Cargo.lock, src/server/coprocessor/aggregate.rs, src/server/coprocessor/endpoint.rs, src/util/codec/convert.rs, src/util/codec/datum.rs, src/util/codec/mysql/decimal.rs, src/util/codec/number.rs, src/util/xeval/evaluator.rs, tests/coprocessor/test_select.rs
Handle truncate error.
For now the error message sent by tikv is different from tidb's. 
TiDB:
ERROR 1105 (HY000): [1 [types:1265]Data Truncated
TiKV:
ERROR 1105 (HY000): other error: unknown error Codec(Other(StringError("[1265] Data Truncated")))
PTAL @BusyJay @coocood @siddontang 
CC pingcap/tidb#2212
=> *: handle truncate error 

README.md
Improve documentation. Fixed `next steps -> use Docker` link that was broken.
=> README.md : fixed deadlink in next steps

Makefile
In order to accelerate the tikv compilation speed in CI container, we need to separate the target dir from the source path and cache it to a persistent storage.
The command line like:
```
CARGO_TARGET_DIR=/tmp/target make static_release
```
=> Makefile: support for custom CARGO_TARGET_DIR

etc/config-template.toml, src/bin/tikv-server.rs
Enlarge default write-buffer-size to hold more data in write buffer.
Enlarge default target-file-size to reduce total files count.
=> etc/bin: tune default value

src/raftstore/store/metrics.rs, src/raftstore/store/peer_storage.rs
Stale snapshot isn't really a fatal error, it should always be retried.
=> raftstore: don't panic when receiving stale snap

src/server/node.rs
The error stack makes user hard to understand what happen.
=> server/node: exit with error message if cluster id mismatch

.travis.yml, Cargo.lock, Makefile, benches/channel/bench_channel.rs, circle.yml, docker/release_dockerfile, docker/rust_dockerfile, src/lib.rs, src/raftstore/coprocessor/region_snapshot.rs, src/raftstore/store/peer_storage.rs, src/server/coprocessor/aggregate.rs, src/util/codec/table.rs, tests/storage/test_storage.rs, travis-build/test.sh
This pr upgrades rustc to nightly-2016-12-18. You can setup it by
```
tikv $ rustup override set nightly-2016-12-19
```
If you have not installed rustup yet, you can get it from www.rustup.rs. Before installing rustup, you may want to uninstall all rustc installed previously.
=> *: upgrade rustc

src/bin/tikv-server.rs, src/util/file_log.rs, src/util/logger.rs, src/util/mod.rs, tests/util.rs
This pr unify logger's implementations.
1. change logging format to be near the same as pingcap/tidb and pingcap/pd, except that we keep microseconds in time part.
2. make all the loggers inside TiKV project to use the same log format.
ref #1475
=> unify logger

src/raft/raft.rs, tests/test_raft.rs
Hi,
This PR port the promotable checking for MsgTimeoutNow from etcd/raft.
It substitutes #1356
=> raft: port promotable checking for MsgTimeoutNow

src/bin/tikv-server.rs
It's not safe to convert usize to i64 directly.
=> tikv-server: fix assert

travis-build/test.sh
When enable pd tests, travis will fail occasionally. These tests are already covered on circle ic, so disable it when travis is detected.
@huachaohuang @siddontang PTAL
=> ci: skip pd tests in travis

etc/config-template.toml, src/bin/tikv-server.rs, src/raftstore/store/store.rs
Make disable manual compaction configurable, `region-compact-check-interval = 0` will disable manual compaction(except lock cf).
=> make disable manual compaction configurable

src/raftstore/store/worker/split_check.rs, src/storage/mod.rs, tests/raftstore/test_split_region.rs
We only count the kvs in default cf when doing split check, which can lead to a region with too many keys if most values are very small. So we need to count all the kvs in other large cfs too.
=> raftstore: count kvs in other cf when doing split check

src/raft/raft.rs, tests/test_raw_node.rs
Hi,
This PR tries to fix issue #1326. It also includes the test case in https://github.com/coreos/etcd/pull/7121.
=> raft: port pending conf reset when adding node

Makefile, tests/tests.rs, travis-build/Makefile, travis-build/test.sh
Currently fail logs are only be printed in Travis CI. But we may need this too in general development or other CI environment, like reproducing a rare bug. So this pr add a target trace_test to meet this need.
@siddontang @disksing @iamxy PTAL
=> support dump fail log without coupling to travis environment

.travis.yml
OS X build often fails when packaging new caches which is produced during compilation, so remove it to make it easier to finish. Though this will slow down CI check.
=> travis: remove compilation cache

src/storage/txn/scheduler.rs, tests/storage/test_storage.rs
If primary key is locked, other keys should not be submitted before primary key.
@siddontang @BusyJay @zhangjinpeng1987
=> scheduler: fix a bug that happens when prewrite meets locks.

src/server/coprocessor/endpoint.rs, src/server/coprocessor/metrics.rs, src/util/mod.rs
Requests may wait too long in queue before actually being handled, this pr add a metric to trace this problem.
@siddontang @disksing @shenli PTAL
=> copr/metrics: add request wait time

Cargo.lock, Cargo.toml, src/bin/tikv-server.rs, src/util/mod.rs, src/util/thread_metrics.rs
This PR adds a custom prometheus collector, it collects each thread's CPU time. Also this PR updates promethues crate and enables the `process` feature.
PTAL @zhangjinpeng1987 @siddontang @BusyJay 
Close #1481
=> *: enable process collector and add thread collector

Cargo.lock, Cargo.toml
We should enable `process` feature after pingcap/rust-prometheus#96 been merged.
PTAL @siddontang @BusyJay @iamxy
=> Cargo: disable prometheus process feature

src/raft/raw_node.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, tests/test_raw_node.rs
- remove type constraint on store
- make committed entries takable
- remove metrics collect check
There are still several prs follow, which including this are try to split #1488 into small pieces, so it can be more easy to review.
=> raftstore: tiny refactor

Cargo.lock, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs
PeerStorage is not thread-safe, so it we want to do async apply, it's better make apply not depends on PeerStorage.
=> raftstore: make raft log gc not depend on PeerStorage

build.rs, src/bin/tikv-server.rs, src/util/mod.rs
This makes `tikv-server -V` print following message, thus let users know which rustc builds tikv-server binary
```
Git Commit Hash: bf2e5e8e58ce2649385d3ad592ea22652fa1b9ef
UTC Build Time:  2017-01-23 03:46:47
Rustc Version:   1.15.0-nightly (71c06a56a 2016-12-18)
```
=> add rustc version when printing tikv-server version

src/raft/raw_node.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/util/sockopt.rs, tests/raftstore/pd.rs, tests/raftstore/test_conf_change.rs, tests/raftstore/util.rs, tests/test_raw_node.rs
RawNode is not designed to be thread safe, so we should only update RawNode in store thread after confchange is applied.
=> raftstore: update raft only in store thread after confchange

src/lib.rs, src/raftstore/coprocessor/region_snapshot.rs, src/raftstore/store/engine.rs, src/raftstore/store/worker/split_check.rs, src/server/coprocessor/endpoint.rs, src/storage/engine/mod.rs, src/storage/engine/raftkv.rs, src/storage/engine/rocksdb.rs, src/util/codec/datum.rs
Currently tasks in a batch of the same regions will be executed sequentially, we can handle it concurrently.
=> copr: make copr task more concurrent

src/raftstore/store/peer.rs, src/raftstore/store/store.rs
When changing to async applying, it's not easy to update lease from another thread. So we need to move lease updating from applying.
=> raftstore: update lease before applying

src/storage/txn/scheduler.rs, src/util/transport.rs
When stopping TiKV, the `scheduler` thread may be closed before `raftstore` thread, at that point if `raftstore` thread send msg to scheduler will cause panic.
ref https://github.com/pingcap/tikv/issues/1363
@BusyJay @disksing PTAL
=> fix panic when stop

src/raftstore/coprocessor/region_snapshot.rs, src/storage/engine/mod.rs, src/storage/engine/raftkv.rs, src/storage/engine/rocksdb.rs, src/storage/mvcc/reader.rs
Now that rocksdb supports `seek_for_prev`, we can use the API directly. Ref #1416.
=> storage: use seek_for_prev

src/raftstore/store/peer.rs
Many user have been confused by `StaleEpoch` Error log. Stale epoch will not cause error, because ticlient will resend the commad to the correct tikv after received response of stale epoch error.
@BusyJay @siddontang PTAL
=> info StaleEpoch error

src/raftstore/store/peer.rs
=> raftstore: from peer doesn't need to get from cache

src/raftstore/store/config.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, tests/raftstore/test_lease_read.rs, tests/raftstore/util.rs
So when the cluster can be upgraded rollingly as long as new election timeout is larger than old lease.
=> raftstore: use static lease

.travis.yml, src/lib.rs, src/util/codec/rpc.rs
Since we remove the old rustc support, only one linux build needs to be kept. And the legacy feature declare can be removed too.
=> *: tiny cleanup

src/raftstore/store/store.rs
to_peer is the same local peer in the store, we don't need to get it from cache when send message. 
@BusyJay @hhkbp2
=> store: no need to cache local peer

src/raft/raft.rs, src/raft/raw_node.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, tests/raft/test_raft_paper.rs
So handle_raft_ready will be called only when it's necessary.
@siddontang @hhkbp2 @zhangjinpeng1987 PTAL
=> raftstore: check if tick generates any readiness

src/storage/mvcc/reader.rs, tests/storage/test_storage.rs
This PR implement improvement for point get by unique key or pk with tidb.
For `Get` with ts==uint64::max(which means it's a point get by pk or unique_key from tidb),  if  lock exist and current key the primary, return latest committed version instead of ErrorWithLock.  
@disksing @zhangjinpeng1987 PTAL
=> txn:improvement for point get by unique key or pk

Cargo.lock, src/server/coprocessor/endpoint.rs, tests/coprocessor/test_select.rs
When default value is provided in column info, use that value if not found.
=> coprocessor: support default value.

src/bin/tikv-server.rs, src/raft/raft.rs, src/raftstore/store/config.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, tests/raftstore/cluster.rs, tests/raftstore/test_split_region.rs
Hi,
This PR tries to fix issue #1639 
=> raftstore: make the campaign after split happen faster

src/raft/raft.rs, src/raft/read_only.rs, src/raftstore/store/local_metrics.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/mod.rs, tests/raftstore/test_lease_read.rs, tests/raftstore/test_multi.rs
This pr is a clean version for #1628. Original version has too much conflict with master, so I rewrite it again. 
@siddontang @hhkbp2 @zhangjinpeng1987 PTAL
=> raftstore: use read index to serve read request

tests/raftstore/test_stale_peer.rs
Isolated need to be removed first, otherwise no peers can be added due to the healthy check.
=> tests: fix auto remove check

src/raftstore/coprocessor/region_snapshot.rs, src/server/coprocessor/endpoint.rs, src/server/coprocessor/metrics.rs, src/storage/engine/mod.rs, src/storage/metrics.rs, src/storage/mod.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/reader.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs, src/storage/txn/store.rs, tests/storage/test_raftkv.rs
This pr counts all the operation taken when handling a request. The collected result can be used to report Pd or Prometheus.
See also #1548, #1567 and #1555.
=> endpoint: collect scanned key count

src/bin/tikv-server.rs, src/raftstore/store/config.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs, src/raftstore/store/util.rs, src/raftstore/store/worker/apply.rs, src/util/mod.rs, tests/raftstore/test_split_region.rs, tests/raftstore/test_tombstone.rs
If leader starts campaign after split immediately, follower may not apply the split yet. But if the follower is ready to apply the split, leader should probably apply the split already, so it should be more efficient to let follower start campaign than leader.
ref #1639 
=> raftstore: queue vote

tests/raftstore/test_compact_lock_cf.rs
When the interval is too large, the compaction isn't executed in time on my machine. So the case often fails.
=> tests: use a smaller interval

Cargo.lock, Cargo.toml, Makefile
SSE is supported in Intel and AMD CPU, so we can use it directly.
@iamxy @BusyJay @zhangjinpeng1987
=> use SSE by default.

src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/apply.rs, src/util/mod.rs, tests/raftstore/test_lease_read.rs, tests/raftstore/transport_simulate.rs
Callback of read index isn't cleared when the peer is destroyed, which will lead to dead lock.
=> raftstore: clean callback when peer is destroyed

Cargo.lock, etc/config-template.toml, src/bin/tikv-server.rs
When you set the path to rocksdb directory in memory like in /dev/shm,
you need to set the wal_dir and WAL_ttl_seconds options if you want to
recover your in-memory RocksDB database after a machine reboot.
See: https://github.com/facebook/rocksdb/wiki/How-to-persist-in-memory-RocksDB-database
This PR depends on https://github.com/pingcap/rust-rocksdb/pull/29 too.
=> Add RocksDB options for in memory configurations.

src/storage/mod.rs, src/storage/txn/scheduler.rs, src/util/transport.rs
This pr simplify the logic of scheduler by removing the mio dependency. `SendCh` is also refactored in this pr, so it will be also helpful for introducing mio 0.6 later.
@siddontang @disksing @zhangjinpeng1987 PTAL
=> scheduler: remove mio eventloop

src/bin/tikv-server.rs, src/raftstore/store/mod.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/snap.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/region.rs, src/server/server.rs, src/server/snap.rs, tests/raftstore/node.rs, tests/raftstore/server.rs
When `SnapManager` is sync, it will require internal channel to be sync too, which can not be always satisfied (especially when using latest mio). So let's make `SnapManager` not sync.
=> raftstore: make SnapManager not sync

src/server/kv.rs, src/storage/txn/mod.rs, src/storage/txn/scheduler.rs, tests/storage/assert_storage.rs, tests/storage/test_storage.rs
Hi,all,
This PR is used to fix [issue_1688] (https://github.com/pingcap/tikv/issues/1688) and would check tso in commit for transaction. @disksing @zhangjinpeng1987 PTAL
=> check_commit_tso:return error when commit_ts < start_tso

.travis.yml, travis-build/Makefile
So we don't need to uninstall rustc then install it again.
=> travis: specifiy rustc version explicitly

src/raftstore/store/peer.rs, src/raftstore/store/store.rs, tests/raftstore/test_split_region.rs, tests/raftstore/test_transfer_leader.rs
When doing transfer leader, it will need to wait for at most a round of heartbeat to send out the request, during which the old leader will drop all the requests.
=> raftstore: speedup transfer leader

src/storage/config.rs
Enlarge default value from 500 to 1000, that push more write to `raftstore`.
=> enlarge scheduler too busy threshold

src/raftstore/store/peer.rs, src/util/mod.rs
Hi,
This PR use a readable output format for leader lease in log messages, so that it's easier to debug problems related with leader lease, such as https://travis-ci.org/pingcap/tikv/jobs/217020787.
PTAL @zhangjinpeng1987 @BusyJay @siddontang
=> raftstore: use readable format for leader lease in logs

Cargo.lock, circle.yml, travis-build/test.sh
Building rustfmt crate doesn't work sometimes.
=> circleci: use precompiled rustfmt

src/pd/async/client.rs, src/util/mod.rs
This PR fix deadlock pitfall. Reading then writing a `RwLock` in a match block will cause a deadlock.
Demo: 
```rust
use std::sync::RwLock;
fn main() {
let mu = RwLock::new(Some(1));
{
let clone = foo(&mu.read().unwrap());
let mut data = mu.write().unwrap();
*data = Some(2);
println!("none match: {:?}", clone);
}
{
match foo(&mu.read().unwrap()) {
Some(_) | None => {
let mut data = mu.write().unwrap();
*data = Some(2);
println!("in match");
}
}
}
println!("done");
}
fn foo(a: &Option<usize>) -> Option<usize> {
a.clone()
}
```
[Playground](https://play.rust-lang.org/?gist=10e3fc41ce939cc7ab7a1c1341fc59c6&version=stable&backtrace=0)
=> pd: fix a deadlock

src/pd/async/util.rs, tests/pd/test_rpc_client.rs
For one node PD cluster, tikv pd client will fail to make a request if the pd leader restarts. Similarly, if the member response doesn't change, tikv pd client will always skip updating the inner grpc client.
PTAL @siddontang @nolouch @BusyJay @zhangjinpeng1987
=> pd: always update client

src/bin/tikv-server.rs
Enlarge default write-buffer-size and block-cache-size for lock cf.
@siddontang @lishihai9017 PTAL
=> enlarge default write-buffer-size for lock cf

src/raft/raft_log.rs, src/util/mod.rs
This PR tries to split #1797 and do a little improvement that ignores computing size if NO_LIMIT.
In most cases, we will use NO_LIMIT, so we can return the whole entries directly.
=> util: ignore computing size if NO_LIMIT

src/pd/async/util.rs, tests/pd/test_rpc_client.rs
If a request fails, it will retry after 500ms (will not block core). If it fails 5 times, it tries to update client (will block core).
PTAL @siddontang @BusyJay @disksing
=> pd: better sleep mechanism on retry

Cargo.lock, Cargo.toml, src/bin/tikv-ctl.rs, src/bin/tikv-server.rs, src/raftstore/store/engine.rs, src/raftstore/store/snap.rs, src/util/mod.rs, src/util/rocksdb.rs
Hi,
This PR tries to fix the cf disorder problem, which will cause failure on applying sst format snapshot, like these logs indicate:
```
2017/04/26 12:44:01.436 region.rs:241: [ERROR] failed to apply snap: Other(StringError(“Invalid argument: External file column family id dont match”))!!!
2017/04/26 12:44:01.436 region.rs:175: [INFO] [region 885] begin apply snap data
2017/04/26 12:44:01.783 region.rs:241: [ERROR] failed to apply snap: Other(StringError(“Invalid argument: External file column family id dont match”))!!!
```
PTAL @zhangjinpeng1987 @siddontang @BusyJay
=> util: fix cf disorder when creating cfs

src/raftstore/store/snap.rs
Hi,
This PR tries to remove checksum calculation when initializing a V2::Snap. It fixes the CPU high issue happened in the test environment.
=> raftstore: remove checksum calculation when init snapshot

src/util/threadpool.rs
Hi,all,
This PR use channel to reduce lock when a tasks comes. Also it adjust the test to fix https://github.com/pingcap/tikv/issues/1796.
@zhangjinpeng1987 @hhkbp2 PTAL.
=> threadpool:use channel to reduce lock in push new task && adjust test

src/raftstore/store/peer.rs, src/raftstore/store/store.rs
When a peer consider itself stale, its state machine should be "turned off".
Tests will be added after we are able to create a test-only store easily.
=> raftstore: mark peer when trying to do async removal

src/server/grpc_service.rs
This PR contains the implementation of the tikv grpc service, currently not used.
The grpc service handles 5 kinds of requests:
1. kv requests. They are unary calls. We handle them by first creating a `(callback, future)` pair, the _callback_ is sent to _Storage_, after _future_ is resolved, we build the response and send it to the response sink.
2. rawkv requests. Basically the same as kv requests.
3. coprocessor requests. Like kv requests, while the _callback_ is sent to _end_point_scheduler_ instead.
4. raft messages. It is client streaming calls which should never end. We iterate all messages and post them to _ch_.
5. snapshot messages. Like raft messages, but the stream will be closed after all chunks of a snapshot is finished. We redirect snapshot messages to _snap_scheduler_, also …
=> add grpc_service.

Cargo.lock, benches/writebatch/bench_writebatch.rs, src/raftstore/store/peer.rs, src/raftstore/store/worker/apply.rs
=> write batch with capacity

src/bin/profiling.rs, src/bin/signal_handler.rs
Due to lacking support of libc, current usage of realtime signal is not portable (may not work in some architecture and operating system). Hence let's remove it for now.
After merging this pr, profiling can't be disabled during runtime. I think it's acceptable.
=> bin: remove toggle profiling

src/bin/tikv-server.rs
related: https://github.com/pingcap/tidb-ansible/pull/20
If TZ is not set, tikv will stat(/etc/localtime) twice every logging operation.
ref: https://stackoverflow.com/questions/4554271/how-to-avoid-excessive-stat-etc-localtime-calls-in-strftime-on-linux
=> tikv-server: check TZ setting

src/raft/progress.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs
@siddontang @hhkbp2 @javaforfun PTAL
To add a stable test, we need to figure out a way to generate a snapshot without peer and step the store whenever we want.
=> raftstore: fix check pending apply

src/bin/tikv-server.rs, src/util/rocksdb.rs
As I have tested, if a key is not existed, memtable get with bloom filter is much more faster than memtable get without bloom filter.
`MVCC get` always call `load_lock` first, in most cases the lock is not exist, so add bloom filter for memtable of lock cf will benefit a lot.
I have tested that in insert case, this pr also reduce about 5%-10% cpu for `scheduler worker`, since every `prewrite` comand will call `load_lock` that in most cases the lock is not exist.
```
test memtable::bench_memtable::bench_memtable_get_exist_32mb                ... bench:         923 ns/iter (+/- 165)
test memtable::bench_memtable::bench_memtable_get_exist_64mb                ... bench:         899 ns/iter (+/- 250)
test memtable::bench_memtable::bench_memtable_get_exist_with_bloom_32mb     ... bench: …
```
=> add bloom filter for lock cf memtable

src/bin/tikv-server.rs, src/raftstore/store/config.rs
Hi,
This PR enables the sst format snapshot by default.
PTAL @siddontang @BusyJay @zhangjinpeng1987 @javaforfun @lishihai9017
=> raftstore: enable sst format snapshot by default

src/server/grpc_service.rs
Fix https://github.com/pingcap/tidb/issues/3409
The reason is originally added by #1775 , and accidentally removed by #1890.
=> grpc: restore scheudler busy reason.

src/storage/mvcc/reader.rs, src/storage/mvcc/txn.rs
Hi,
This PR fix bug in func `get_txn_commit_info`.  Since `tidb` would do `prewrite`  concurrently, a `rollback` record may do between a `prewrite` and `commit`.  That is when we try to `get_txn_commit_info` with a `start_ts`, the first one from `reverse_seek_write` may not the record with `start_ts`, so we need to go on seek the next util meet the commit with `start_ts` .
Here is the log detail:
```
[pingcap@ip-172-16-10-12 ~]$ ./tikv-ctl -d "/data1/new_deploy1/data/db" mvcc -c write -k "t\\200\\000\\000\\000\\000\\000\\000\\041_r\\200\\000\\000\\000\\002'6\\232"
You are searching Key t\200\000\000\000\000\000\000\041_r\200\000\000\000\002'6\232:
Key: "t\\200\\000\\000\\000\\000\\000\\000\\377!_r\\200\\000\\000\\000\\002\\377\'6\\232\\000\\000\\000\\000\\000\\372"
Type: Put
Start_ts: …
```
=> mvcc:fix bug in get_txn_commit_info

src/server/coprocessor/endpoint.rs, tests/coprocessor/test_select.rs
hi,
If we order by c1 limit int.max, topn will alloc a lot of memory for heap, which leads to oom. This pr fix it.
The related PR in tidb is https://github.com/pingcap/tidb/pull/3392
@BusyJay @andelf PTAL
=> endpoint: avoid allocating a lot of memory at first in topn

src/bin/tikv-server.rs
In most cases raft entries can get from memtable, in another special case that raft log lag is large, scan will used. So bloom filter for raft cf is redundant.
=> remove bloom for raft cf

Cargo.lock, src/raftstore/store/engine.rs, src/server/errors.rs, src/storage/mvcc/reader.rs
the main optimization is using prefix seek instead of total order seek which is already enabled before this pull.
BUT replacing upper bound with prefix bound still can reduce some iterate ops like much del key exist before the bound.
eg. you del a big range of data, and you just want to get the bound value of the deleted range which is not exist.
=> optimize seek write-cf

src/util/codec/mysql/json/json_type.rs, src/util/codec/mysql/json/mod.rs
Hi,
This PR implement `json_type` for  `json`. Since `tidb` haven't implement `json_type` in evaluator, so we would implement this part later. The related source file in `tidb` is (https://github.com/pingcap/tidb/blob/master/util/types/json/functions.go#L25)
@andelf @hhkbp2 @hicqu @lishihai9017 PTAL
=> mysql/json:support json_type

tests/raftstore/test_compact_after_delete.rs, tests/raftstore/test_compact_log.rs, tests/raftstore/test_lease_read.rs, tests/raftstore/test_multi.rs, tests/raftstore/test_stats.rs
Some cases don't have to be run with both node cluster and server cluster.
=> tests: remove redundant cases

src/raftstore/store/peer.rs, src/util/clocktime.rs, src/util/mod.rs
Hi,
This PR revises the format of leader lease in log messages. It reverts the PR #1722. Because the leader lease is a monotonic time since startup time. It's confusing to output it in absolute time format. This PR changes the leader lease format from `"1970/01/01 00:17:01.272"` to `Timespec { sec: 51988, nsec: 392739700 }` for better description.
PTAL @javaforfun @BusyJay @siddontang
=> raftstore/peer: revise leader lease time log

src/util/config.rs
=> util/config: fix #1956 config error printing

src/raftstore/store/worker/apply.rs
Read only command are handled in raftstore directly,  so we don't need to do anything in apply worker.
=> raftstore: skip handling read only command

Cargo.lock, Cargo.toml
Improve performance.
make bench:
1.2:
```
test serialization::bench_serialization::bench_decode_one            ... bench:         516 ns/iter (+/- 1)
test serialization::bench_serialization::bench_decode_two            ... bench:         861 ns/iter (+/- 3)
test serialization::bench_serialization::bench_encode_one            ... bench:         493 ns/iter (+/- 1)
test serialization::bench_serialization::bench_encode_two            ... bench:         783 ns/iter (+/- 3)
```
1.4:
```
test serialization::bench_serialization::bench_decode_one            ... bench:         409 ns/iter (+/- 1)
test serialization::bench_serialization::bench_decode_two            ... bench:         698 ns/iter (+/- 2)
test serialization::bench_serialization::bench_encode_one            ... bench:         494 …
```
=> Cargo: upgrade protobuf to 1.4

src/raftstore/store/worker/pd.rs, src/server/node.rs, tests/raftstore/pd.rs
Test pd client need to be informed before it can handle region heartbeat response callback, so here invoke put store before store thread is actually started.
@disksing is it OK for pd?
close #1982
=> pd: put store before start store thread

src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/apply.rs, src/raftstore/store/worker/metrics.rs, src/raftstore/store/worker/mod.rs
Send proposal callbacks in batch can reduce the invocation of channel send and HashMap queries.
@siddontang @javaforfun PTAL
=> apply: batch register proposal callbacks

src/raftstore/coprocessor/region_snapshot.rs, src/raftstore/store/metrics.rs, src/raftstore/store/mod.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs, src/util/mod.rs
Add cache for fetching log entries, this can reduce the time visiting rocksdb.
=> raftstore: add entry cache

src/util/codec/datum.rs, src/util/xeval/evaluator.rs
Hi,
This PR implement function `json_type` in evaluator, the related PR in `tidb` is https://github.com/pingcap/tidb/pull/3492,
and the related source files in `tidb` are
- https://github.com/pingcap/tidb/blob/master/expression/builtin_json.go
- https://github.com/pingcap/tidb/blob/master/distsql/xeval/eval_json.go
- https://github.com/pingcap/tidb/blob/master/distsql/xeval/eval.go
And the file datum.rs is the same with https://github.com/pingcap/tikv/pull/1996. we should do review after it has been merged.
@hhkbp2 @hicqu @lishihai9017 @andelf PTAL
=> xeval/evaluator: implement json_type

src/pd/async/util.rs
Add a missing metric in async requests.
Note: schedule time will be recorded too.
@siddontang @BusyJay
=> pd: add a missing metric in async requests

src/coprocessor/endpoint.rs, src/coprocessor/metrics.rs
Hi, 
This PR remove `type` from labels in metrics for coprocessor.
@BusyJay @lishihai9017 @hhkbp2 @andelf PTAL.
=> coprocessor/metrics: remove type from labels

src/storage/engine/mod.rs, src/storage/mvcc/mod.rs, src/storage/txn/mod.rs, src/util/codec/mod.rs
This is useful if we want to introduce batch processing to scheduler later.
=> storage: make error cloneable when possible

src/coprocessor/endpoint.rs
Conf version is ignored when requesting snapshot. Since peer id is included, store id is redundant.
=> endpoint: remove unnecessary hash key

src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs, tests/raftstore/test_tombstone.rs
If a region removes a peer on a store, it usually puts a tombstone mark then deletes all meta and data. In some condition, TiKV may exit before clearing meta and data (like killed, core or system shutdown). When it's restarted, data will be cleaned up thanks to our current mechanism, but the meta will remain on disk. If the same region schedules a new peer on it again, the old meta will be picked up, hence we get a corrupted region peer.
This pr tries to resolve it by clearing meta too on start.
=> raftstore: clean up metadata on start

src/server/server.rs
Set region size to 256MB may cause grpc msg length bigger than 128M.
@zhangjinpeng1987 @disksing PTAL
=> server: change MAX_GRPC_SEND_MSG_LEN

src/coprocessor/xeval/evaluator.rs
Hi,
This PR adds the mapping fro function signatures to implementation function for evaluator.
PTAL @XuHuaiyu @AndreMouche @lishihai9017 @andelf
=> coprocessor/xeval: add function signatures mapping

src/raftstore/store/peer.rs
When dealing with snap command, we will generating a region snapshot instead. Hence generate a snapshot early is a waste.
=> raftstore: get snapshot lazily

src/bin/tikv-server.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/snap.rs, src/server/server.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore/test_bootstrap.rs
@siddontang @hhkbp2 @zhangjinpeng1987 PTAL
=> snap refactor 1: remove v1

src/raftstore/store/snap.rs, src/raftstore/store/store.rs
=> snapshot refactor 2: move v2 api to super module

Cargo.lock, src/raftstore/store/engine.rs, src/raftstore/store/engine_metrics.rs, src/raftstore/store/snap.rs, src/util/config.rs, src/util/rocksdb.rs
With latest rust-rocksdb, we will be able to build static link binary without the impact of system's jemalloc.
=> *: update rocksdb

.travis.yml
Looks like clang++ in OSX sometimes doesn't work as expected. So let gcc-rs decide which compiler to use to build cpp wrapper.
=> travis: let gcc decide which compiler to use

src/coprocessor/xeval/builtin_math.rs
Hi,
This PR fixes an issue when the input datum is null. It address
```
select abs(null);
+-----------+
| abs(null) |
+-----------+
|      NULL |
+-----------+
1 row in set (0.00 sec)
```
PTAL @XuHuaiyu @AndreMouche @andelf @BusyJay
=> coprocessor/xeval: add handling for datum null

src/coprocessor/metrics.rs
HI, 
This PR initialize exponential buckets for duration metrics.
@siddontang @andelf @BusyJay PTAL
=> coprocessor/metircs:init exponential buckets for duration

src/coprocessor/codec/mysql/json/json_remove.rs, src/coprocessor/codec/mysql/json/mod.rs, src/coprocessor/xeval/evaluator.rs
Hi,
This PR implement function `json_remove` in coprocessor, the related source code in tidb is
(https://github.com/pingcap/tidb/blob/master/expression/builtin_json.go#L207) , (https://github.com/pingcap/tidb/blob/master/util/types/json/functions.go#L329)
The related mysql document is https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-remove
@hicqu @andelf @BusyJay PTAL
=> coprocessor/*:implement for json_remove

src/bin/tikv-server.rs, src/raftstore/coprocessor/dispatcher.rs, src/server/node.rs, src/server/resolve.rs, src/server/server.rs, src/server/transport.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore/test_bootstrap.rs
This pr stop the resolver thread explicitly instead of relying on drop method. When drop method is called, it's possible that the join method is called inside the resolver thread, which will lead to unexpected panic on Linux.
=> resolver: stop thread explicitly

src/bin/tikv-server.rs, src/lib.rs, src/storage/config.rs, src/storage/mod.rs, tests/raftstore/util.rs
This pr tries to make the storage's configuration field names be consistent with toml.
=> storage: rename configuration field

src/lib.rs, src/util/config.rs
- add serde methods for compression type arrays instead of compression type
- add serde methods for ordermap
- add helper methods for readable types
=> config: add more util methods

Cargo.toml, src/coprocessor/xeval/builtin_math.rs
`jemallocator` depends on libc with default features disabled. But `TiKV` also have several dependencies depend on libc with default features enabled. In this case, cargo will enable default features for all libc dependencies. We were able to get around this by using the built in libc crate. But in the recent nightly release of rustc, there will be two libc crates that will lead to conflict.
So let's disable mem-profiling by default until we find a better solution.
=> disable mem-profiling

src/coprocessor/endpoint.rs, src/coprocessor/metrics.rs
Hi,
This PR removes metrics `tikv_coprocessor_scan_details` to reduce lock conflicts.
=> coprocessor/endpoint:remove metrics for scan_details

src/bin/tikv-server.rs, src/lib.rs, src/util/properties.rs
Collect size properties from CF_DEFAULT and CF_WRITE.
Don't merge until https://github.com/pingcap/tikv/pull/2096 has been merged.
=> Add size properties collector

Cargo.lock, src/pd/async/client.rs, src/pd/mod.rs, src/raftstore/coprocessor/region_snapshot.rs, src/raftstore/store/peer.rs, src/raftstore/store/util.rs, src/raftstore/store/worker/pd.rs
Get approximate region size from user properties.
=> add region approximate size

src/raftstore/store/store.rs
In some rare cases like election or slow hash computation, there may be duplicated consistency verification. We need to skip consistency check in this case, because it's going to fail no matter if the data is consistent with other peers.
=> consistency check: prevent duplicated consistency check

Cargo.lock, circle.yml, docker/rust_dockerfile
RocksDB 5.6.2 has fixed [deletion dropping](https://github.com/facebook/rocksdb/commit/acf935e40f9d6f4c3d13c7d310def7064c1f1c95) in intra-L0.
=> upgrade rocksdb to 5.6.2

src/util/time.rs
It's a quick fix for #2158. `SlowTimer` should not panic again by using millisecond resolution for coarse Instant. 
Fix #2158
=> util/time: use millisecond resolution for coarse Instant

src/util/time.rs
CLOCK_MONOTONIC_COARSE clock time does not guarantee monotonic increase across processors. ~~This PR allow coarse clock to have a kernel specified coarse error.~~ Just ignore the error.
=> util/time: allow coarse error

src/raft/raft.rs, tests/raft/test_raw_node.rs
In some cases, leader can be removed from cluster. If commit is not broadcast, follower will still consider leader is included in the cluster which may affect the quorum calculation. If another node is isolated, election may not succeed any more.
This pr forces broadcasting commit when conf change is detected.
=> raft: bcast when has pending conf change

src/coprocessor/codec/mysql/json/json_modify.rs, src/coprocessor/dag/dag.rs, src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/endpoint.rs, src/raftstore/store/snap.rs, src/raftstore/store/store.rs, src/server/raft_client.rs, src/storage/mvcc/reader.rs, src/storage/txn/scheduler.rs
I use a higher version rustc and it warns me about these `mut`s.
@siddontang @BusyJay PTAL.
=> *: remove all unnecessary mut

src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/compare.rs, src/util/macros.rs
We deal with None a lot in coprocessor, hence I introduce `try_opt` to reduce the duplicate code.
=> copr: introduce try_opt

src/bin/tikv-server.rs, src/util/mod.rs
Add version information in tikv's log and tikv-server -V output.
CC pingcap/tidb#4218
=> util: add release version info

src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/dag/executor/table_scan.rs
There was a bug in dag plan: we supposed the input ranges has already been reversed if we need desc-scan, but it didn't . This PR fix it and add some tests.
@AndreMouche @hicqu @BusyJay PTAL
=> coprocessor: fix bug about reverse scan.

src/coprocessor/dag/expr/builtin_op.rs, src/coprocessor/dag/expr/fncall.rs, src/coprocessor/dag/expr/mod.rs
@andelf @hicqu @AndreMouche @BusyJay PTAL
=> dag: implement builtin UnaryMinus*

src/coprocessor/endpoint.rs, src/coprocessor/metrics.rs, src/storage/engine/mod.rs, src/util/threadpool.rs
@overvenus @siddontang @AndreMouche PTAL
=> coprocessor: add statistics back

src/pd/client.rs, src/pd/mod.rs, src/pd/util.rs
Client may spend a lot to time to reconnect when the pd leader is isolated. Speed it up by adding a timeout.
Also it puts the previous leader at the last when reconnecting.
=> pd: speed up reconnecting to a pd leader

src/pd/client.rs, src/server/server.rs, src/util/logger.rs, tests/pd/mock/server.rs, tests/pd/test_rpc_client.rs, tests/raftstore/server.rs, tests/util.rs
This pr removes log from dependency crates like tokio-core in tests and fix thread name to make sure all logs are shown when a case fails.
=> tests: clean up log

src/coprocessor/dag/expr/builtin_cast.rs
=> expr/builtin_cast: implement test_cast_as_real & test_cast_as_int

src/coprocessor/dag/expr/fncall.rs, src/coprocessor/dag/expr/math.rs, src/coprocessor/dag/expr/mod.rs
So we don't need to write the long match twice.
=> copr: use macro to generate eval function

src/util/time.rs
Calling Instant::now() multiple time may return the same timestamp
on fast machines
=> util/time: fix test

src/storage/engine/mod.rs, src/storage/engine/rocksdb.rs, src/storage/txn/scheduler.rs, tests/storage/sync_storage.rs, tests/storage/test_storage.rs
`finish_with_err()` access `grouped_cmds` for enqueueing
conflicted commands, but the `grouped_cmds` is None.
We should restore `grouped_cmds` before further accessing.
=> txn/scheduler: fix unwrap panic

src/bin/tikv-ctl.rs
currently:  
```shell
$./tikv-ctl -d data/db/ --raftdb data/raft/  raft region
error: Found argument '--raftdb' which wasn't expected, or isn't valid in this context
$ ./tikv-ctl -d data/db/ <raftdb> data/raft/  raft region
-bash: raftdb: No such file or directory
$ ./tikv-ctl -d data/db/  data/raft/  raft region
```
we should make -r work
```shell
$./tikv-ctl -d data/db/ -r data/raft/  raft region
```
=> tikv-ctl: add short name for raftdb

src/bin/tikv-server.rs, src/util/config.rs
This pr tries to enable readable int parsing for args and print error message to stderr when log service is unavailable yet.
=> tikv-server: fix capacity parsing

src/util/panic_hook.rs
New a backtrace ahead for caching necessary elf sections of this
tikv-server, in case it can not open more files during panicking
which leads to no stack info (0x5648bdfe4ff2 - \<no info\>).
The cache takes about 33,936 KB.
=> util/panic_hook: cache elf sections for backtrace

src/storage/txn/scheduler.rs
Quitting scheduler without stopping thread pool can cause potentially coredump.
=> Stop thread pool before quitting scheduler

src/util/panic_hook.rs
Caching is slow, spawn it in another thread to speed up.
=> util/panic_hook: speed up set_exit_hook

src/coprocessor/endpoint.rs, src/coprocessor/mod.rs, src/coprocessor/select/select.rs, src/util/time.rs
@overvenus @BusyJay @hicqu PTAL
=> coprocessor/*: use util:time:instant instead of std::time::instant

src/coprocessor/dag/expr/compare.rs
This pr tries to optimize like by
- reducing recurses as many as possible
- reducing match as many as possible
According to bench, average match time is 2/3 less than before.
=> copr/expr: optimize like

src/raft/raft.rs, tests/raft/test_raft.rs
see https://github.com/coreos/etcd/issues/8553 and https://github.com/coreos/etcd/pull/8339
=> raft: check leader request when become_follower after recv msg with higher term

src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/decimal.rs, src/coprocessor/dag/expr/arithmetic.rs, src/util/macros.rs
From rust 1.7, `overflowing_neg` is supported, so we don't need `opp_neg` anymore.
=> *: remove opp_neg

src/raftstore/store/bootstrap.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/apply.rs
so now we have two rocksdb, we have two WAL.
```
raftsotre.sync-log = true means we need prevent data loss when power failure.
take raft log gc for example, we write kv WAL first, then write raft WAL,
if power failure happen, raft WAL may synced to disk, but kv WAL may not.
so we use sync-log flag here.
```
=> raftstore: enhance sync_log

src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/pd.rs
Get approximate size may block raftstore thread, move it to pd worker.
cherry-pick https://github.com/pingcap/tikv/commit/df6fcae6efcf0231f8523e5c1ce100c445c80270
=> rc4.1: ignore calculate regions size when heartbeat to pd

src/coprocessor/endpoint.rs, src/coprocessor/metrics.rs, src/storage/metrics.rs, src/storage/txn/scheduler.rs
=> src/*: use counter instead of histogram in metrics for`scan_details`

Cargo.lock, Cargo.toml, src/raftstore/store/debug.rs, src/server/service/debug.rs, tests/raftstore/test_service.rs
This PR implements region_info.
=> debug: impl region_info

Cargo.lock, src/server/raft_client.rs
gRPC handles connection internally, so different channels may share the same TCP connection under the hook. But we attempts to maintain the connection by ourselves. I tried to utilize the gRPC implementation but get some wired behavior. I may investigate it further, but let's keep compatible with the old behavior first.
There is no big performance difference in sysbench and pure kv bench after being upgraded, though pure gRPC bench shows a little performance increase in single connection mode.
=> update gRPC to 1.6.1

src/raftstore/store/worker/apply.rs
Use slow log after writing a batch. 
PTAL @BusyJay @javaforfun @overvenus
=> apply: update slow log place

src/raftstore/store/local_metrics.rs, src/raftstore/store/metrics.rs, src/raftstore/store/store.rs
Records dropped raft messages. Please let me know if I am missing something.
=> raftstore: add drop message metrics

src/coprocessor/endpoint.rs, src/raftstore/store/worker/region.rs
Shutdown without stopping thread pool may cause potentially
core dump. However, stopping thread pool before shutdown may slow down
the shutdown process, unless we can cancel the running task, which
seems not easy to do.
=> Stop thread pool on shutdown

src/storage/engine/metrics.rs, src/storage/engine/mod.rs
Hi,
this PR would fix https://github.com/pingcap/tikv/issues/2314
@BusyJay @siddontang @hicqu  PTAL
=> engine/metrics: move CURSOR_OVER_SEEK_BOUND_COUNTER to CFStatistics

src/raftstore/store/store.rs
We should let the leader send message ASAP. Using 100% write YCSB test `ycsb -concurrency 200 -workload=F -duration=10m`, I see that the write performance improve a little. 
The QPS is:
|| no sync| sync|
|-|-|-|
|master| 32041.7 | 24759.2 |
|Flush| 32308.4 | 25089.6 |
I have done many YCSB tests and get the same results, so I think the performance can be improved a little.
PTAL @BusyJay @zhangjinpeng1987
=> raftstore: flush leader message ASAP

src/raftstore/store/msg.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/pd.rs, src/raftstore/store/worker/split_check.rs, src/server/service/kv.rs, tests/raftstore/cluster.rs, tests/raftstore/test_split_region.rs
Remove `SplitCheckResult` for unifying region split messages.
=> *: unified region split message

Cargo.lock, src/raftstore/store/debug.rs, src/raftstore/store/worker/compact.rs, src/server/service/debug.rs, src/util/rocksdb/mod.rs
Add debug API Compact. The Compact is running in `Debugger.CpuPool`.
And this Compact is **by manual** and doesn't have metrics. Do we need to add metrics or share a same metrics with `CompactWorker`?
=> debug: add a new API Compact.

src/bin/tikv-server.rs, src/pd/metrics.rs, src/pd/mod.rs, src/pd/pd.rs, src/raftstore/store/metrics.rs, src/raftstore/store/mod.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/metrics.rs, src/raftstore/store/worker/mod.rs, src/server/node.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore/test_bootstrap.rs
In order to let PD work be able to receive messages from any module, extract it from raftstore. and then I will refactor coprocessor report mechanism in https://github.com/pingcap/tikv/pull/2337
=> *: move out pd work from raftstore

src/bin/tikv-server.rs, src/server/server.rs, src/server/transport.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore/transport_simulate.rs
Now we use raft router and a significant sender to send messages to the raft store, this seems a little duplicated, so here move the significant sender to the raft router, so we can only use the raft router to send messages.
=> *: move significant send to raft router

tests/raftstore/cluster.rs
Split may not succeed, and let it retry if possible.
=> tests: fix split check

src/util/transport.rs
Comment and doc changes only. No logical changes.
=> Fix typos in transport.rs

src/raft/raft.rs
Only affects comments and documentation. No logical changes.
=> Fixes typos in raft.rs

etc/config-template.toml, src/config.rs, tests/config/mod.rs, tests/config/test-custom.toml
Use ycsb `tidb-ycsb -concurrency 200 -workload=F -duration=10m  raw://172.16.20.1:2379`, we can find that using`wal_bytes_per_sync` can improve the 3% QPS if sync = false, but have no big effect if sync = true.
We need to do more benchmark to ensure a suitable value, so here I just add the configuration.
For `bytes_per_sync`, we can use rate limiter which sets `bytes_per_sync` to 1 MB by default.
||Raft 0 MB|Raft 64 KB|Raft 1 MB|
|-|-|-|-|
|KV 1 MB + Sync false|32038.3|32880.7|32938.9|
|KV 0 MB + Sync false|31533.7|32876.3|32742.1|
|KV 0 MB + Sync true|25017.8|24993.2|24492.9|
/cc @zhangjinpeng1987 @huachaohuang
=> config: add wal bytes per sync

src/util/macros.rs
Documenting perhaps counter intuitive behavior of the macro. It is in compliance with the behavior of golangs defer. Confirmed with the experimient here https://play.rust-lang.org/?gist=6cf3013b12610150436c21bc2d5459ad&version=nightly
=> Document defer macro LIFO behavior

src/raftstore/store/local_metrics.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs
If a TiKV is inactive for a while (block on IO for instance), all the replicas on the store may be removed by pd. So when the inactive monitor checks pd and finds out that a replica is removed, it will schedule GC message to raftstore. However, if the replica is applying snapshot at that time, TiKV will panic because a peer in applying state shouldn't be removed for safety.
This pr fixes it by checking if a peer is applying snapshot before accepting GC message.
=> raftstore: fix stale peer check

src/util/mod.rs
removes need to use Iterator::count and allows to not call Vec::truncate
if NO_LIMIT
Fixes pingcap/tikv#2400
=> util: inline get_limit_at_size

src/raft/raft.rs, src/raft/raw_node.rs
=> raft: reduce allocation

src/coprocessor/codec/table.rs
`flatten` and `unflatten` have no effects on Json. This PR remove useless log for that.
=> coprocessor: remove useless log.

src/storage/mvcc/reader.rs
we should count the key length. the index key because some keys encode the value, like index key.
=> mvcc/reader: fix read statistics

Cargo.lock, Cargo.toml, etc/config-template.toml, src/coprocessor/endpoint.rs, src/server/config.rs, src/server/server.rs, src/server/service/kv.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/coprocessor/test_select.rs
This is a rewrite of pr #2424. Instead of checking it in executors, check it at the very beginning of deserialization.
Because pr stepancheg/rust-protobuf#248 is not merged (and released) yet, so use a branch for now.
=> endpoint: add recursion limit check

src/raftstore/store/store.rs, tests/raftstore/test_tombstone.rs
It's possible that the target is not the same as current peer, so remove the assert.
=> raftstore: check gc target

src/raftstore/store/worker/apply.rs, src/util/mod.rs
So that we can reuse `ApplyContext` when implementing merge.
=> raftstore: unify ApplyContext and ExecContext

src/raftstore/store/peer.rs, src/util/mod.rs
Use `recover_safe!` to hide the panic stacktrace and replace more code.
=> cleanup mustconsumevec

src/pd/mod.rs, src/pd/util.rs, tests/pd/mock/mocker/retry.rs, tests/pd/test_rpc_client.rs
Read lock won't be dropped inside of the `match` block.
=> pd: fix a dead lock

src/raftstore/store/store.rs
- raftstore: fix not leader response (#2479)
=> cherry-pick bug fixes for 1.0.3

Makefile
Enable portable binary and SSE4.5 by default.
=> makefile: fix default features

src/storage/mvcc/metrics.rs, src/storage/mvcc/txn.rs
=> mvcc: reduce log.

src/pd/client.rs, src/pd/errors.rs, src/pd/mod.rs, tests/pd/mock/mocker/service.rs, tests/pd/test_rpc_client.rs
We need to know a region's leader when calling some kv RPCs, but the original `get_region` method doesn't return the leader in the response. We can return a region's leader in `get_region`, but it will break a lot of code. Since in most cases, we just need to get the region, I keep the `get_region` method and add another `get_region_info` method for those who need to know the region's leader.
=> Add get_region_info for pd client

src/raftstore/store/store.rs
Fix #2593 and #2487 
Tests will retry when it meets stale epoch error.
=> store: change box err to stale epoch error

src/bin/tikv-fail.rs
addr arg is required now,or it will just show a unwrap error msg
=> tikv-fail: change addr arg to required

src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/dag/executor/table_scan.rs
@BusyJay @hicqu @hanfei1991  PTAL
=> coprocessor/scanner: set key_only=true if needed

src/raftstore/store/store.rs, src/util/mod.rs, src/util/sys/mod.rs
Two requirement:
1) user needs `CAP_SYS_NICE` capability.
2) only support linux platform.
or, nothing will happen.
In order to add `CAP_SYS_NICE` for user tidb, please add following two lines to /etc/security/limits.conf:
tidb        soft        nice          -1
tidb        hard        nice          -1
=> set raftstore thread priority

src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/select/aggregate.rs
corresponding modification for https://github.com/pingcap/tidb/pull/5292
=> coprocessor: Fix return type for builtin aggregation fuction 'AVG' and 'SUM'

tests/failpoints.rs, tests/failpoints_cases/test_storage.rs
CC https://github.com/pingcap/tikv/pull/2545#issuecomment-353917300
=> tests: cacth stale command in txn error

src/raftstore/store/snap.rs, src/util/file.rs, src/util/rocksdb/mod.rs
Add a function to prepare a SST file for ingestion.
The purpose is to make the ingestion retryable when using the `move_files`
option. Things we need to consider here:
1. We need to access the original file on retry, so we should make a clone
before ingestion.
2. `RocksDB` will modified the global seqno of the ingested file, so we need
to modified the global seqno back to 0 so that we can pass the checksum
validation.
3. If the file has been ingested to `RocksDB`, we should not modified the
global seqno directly, because that may corrupt RocksDB's data.
=> Ingest SST with `move_files` option

Cargo.lock, Cargo.toml, src/raftstore/store/worker/region.rs, tests/failpoints_cases/test_pending_peers.rs, tests/failpoints_cases/test_snap.rs, tests/failpoints_cases/test_storage.rs
This PR upgrade fail to 0.2, all failpoints names are changed. 
Our internal stability tests need to a update too. CC @cwen0
=> Upgrade fail to 0.2

src/util/rocksdb/mod.rs
Execute make dev on MacOS will got compile error message: 
```
error[E0432]: unresolved import `std::os::linux`
--> src/util/rocksdb/mod.rs:530:26
|
530 |             use std::os::linux::fs::MetadataExt;
|                          ^^^^^ Could not find `linux` in `os`
error[E0599]: no method named `st_nlink` found for type `std::fs::Metadata` in the current scope
--> src/util/rocksdb/mod.rs:531:52
|
531 |             assert_eq!(fs::metadata(path).unwrap().st_nlink(), nlink);
|                                                    ^^^^^^^^
|
= help: items from traits can only be used if the trait is in scope
= note: the following trait is implemented but not in scope, perhaps add a `use` for it:
candidate #1: `use std::os::macos::fs::MetadataExt;`
error: aborting due to 2 previous errors …
```
=> Fix make dev compile error on Mac

src/coprocessor/endpoint.rs, src/util/worker/mod.rs
The design of `BatchRunnable` contains this code:
```rust
impl<T> BatchRunnable<T> for Runnable<T> {
fn run_batch(&mut self, _: &mut Vec<T>) {}
}
```
But it's confict with
```rust
struct RunnerProxy<T: Display, R: BatchRunnable>(runner: R);
impl<T: Display, R: BatchRunnable<T>> BatchRunnable<T> for RunnerProxy<T, R> {
fn run_batch(&mut self, _: &mut Vec<T>) {}
}
```
I think it's a compiler bug. We can avoid that bug by removing `BatchRunnable` directly.
=> util: Rmove BatchRunnable and use Runnable instead.

src/storage/mvcc/write.rs, src/util/rocksdb/properties.rs
We only need the `WriteType` of the value in the collector, so add a method to parse the `WriteType` instead of the whole value to reduce CPU usage.
=> Optimize write type parsing for mvcc properties collector

Cargo.lock, Cargo.toml
So when using master version of TiKV, the output won't be 1.0.1 anymore, which is very confusing.
Also, I propose to change the version very time a new major/minor version is released. For example, if we are going to release 1.1.0 from master, then we need to
1. checkout release-1.1 branch;
2. release new version on release-1.1 branch;
3. update master version to 1.2.0-dev.
=> *: change version

src/bin/tikv-server.rs
Set gRPC event engine to the epollsig.
=> Specifying gRPC event engine

src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/dag/executor/mod.rs
We will support stream aggregation later, so I rename AggregationExecutor to HashAggExecutor.
=> coprocessor/dag/executor: rename AggregationExecutor to HashAggExecutor

src/bin/tikv-ctl.rs, src/raftstore/store/debug.rs, src/server/service/debug.rs
Old tikv-server run on pb2, but after that we upgrade pb2 to pb3. So use latest tikv-ctl can't always access some old tikv cluster. This PR fix this.
=> cherrypick rafactor tikv-ctl(#2377)

src/pd/client.rs, src/pd/util.rs
This is a quick fix for possible stale heartbeat streaming call.
Streaming call won't report error when messages are dropped silently in network. However there are sync requests in pd client can detect this error by timeout. When the error is detected, client will be refreshed. At that time, streaming call created by old client should be canceled automatically. But this doesn't happen as expected, so this pr cancels it explicitly.
We need to add a test case to tested this with iptables.
The issue needs to be investaged further too. /cc pingcap/grpc-rs#150
=> pd: cancel call when refreshing client

Cargo.lock
Update hyper in order to fix a vulnerability of hyper:
The vulnerability of hyper:
```
ID: RUSTSEC-2017-0002
Crate: hyper
Version: 0.9.10
Date: 2017-01-23
URL: https://github.com/hyperium/hyper/wiki/Security-001
Title: headers containing newline characters can split messages
Solution: upgrade to: >= 0.10.2, < 0.10.0, >= 0.9.18
```
=> Cargo: update hyper to v0.9.18

tests/raftstore/cluster.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore/util.rs
Add `async_command_on_node` for the `Simulator`, so that we can execute commands asynchronously, it is useful in some tests, eg. #2639 .
=> tests: call commands asynchronously

src/coprocessor/dag/executor/aggregate.rs
=> executor/aggregate: convert int to decimal in sum

Cargo.lock, Cargo.toml, etc/config-template.toml, src/bin/tikv-server.rs, src/config.rs, src/import/config.rs, src/import/errors.rs, src/import/metrics.rs, src/import/mod.rs, src/import/service.rs, src/import/sst_importer.rs, src/import/sst_service.rs, src/import/test_helpers.rs, src/import/tests.rs, src/lib.rs, src/server/server.rs, src/util/time.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/import/mod.rs, tests/import/sst_service.rs, tests/integrations.rs, tests/raftstore/server.rs
ImportSST Service provides the feature to import a generated SST file to a
region. The service includes two APIs:
- UploadSST: Upload an SST file to a server
- IngestSST: Ingest an uploaded SST file to a region
This PR implements the UploadSST API. An SST file is identified by its meta data
SSTMeta. When an SST file is uploaded, its length and crc32 checksum will be
validated with the SSTMeta. Then when the SST file is ingested, its length and
crc32 checksum will be validated again, plus its range and the region epoch.
If an SST file is uploaded, but the coresponding region's epoch is changed
before the SST file is ingested, the SST file will be invalid, and can be
cleaned up. However, this PR doesn't contain the logic to clean up invalid SST
files, but it will be added in the other PRs …
=> import: Add ImportSST/UploadSST API

tests/raftstore/cluster.rs
Ignore stale command for fixing split tests.
http://45.249.247.133:8080/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_unit_test/runs/208/nodes/22/steps/31/log/?start=0
=> tests: ignore stale cmmand while splitting

Makefile
Disable portable on MacOS to sidestep the compiler bug in clang 4.9.
=> disable portable on MacOS

src/coprocessor/codec/table.rs, src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/dag/executor/limit.rs, src/coprocessor/dag/executor/mod.rs, src/coprocessor/dag/executor/selection.rs, src/coprocessor/dag/executor/table_scan.rs, src/coprocessor/dag/executor/topn.rs, src/coprocessor/endpoint.rs, src/coprocessor/statistics/analyze.rs, tests/coprocessor/test_analyze.rs, tests/coprocessor/test_select.rs
For coprocessor request with type is dag or analyze, we check req's ranges to make sure the scanned keys should always be table record or index. @BusyJay @hicqu PTAL
=> coprocessor/endpoint: check range for dag and analyze

src/raftstore/store/snap.rs, src/util/rocksdb/mod.rs
Keys in raw KV scenario don't have ts tail, in that situation we can't use region's `end_key` to involve `delete_files_in_range`.
=> fix cleanup for raw kv

src/raftstore/coprocessor/split_check/size.rs, src/raftstore/store/store.rs, src/raftstore/store/util.rs, src/raftstore/store/worker/split_check.rs, src/util/rocksdb/properties.rs, tests/raftstore/cluster.rs, tests/raftstore_cases/test_split_region.rs
The current approximate size can miss the first size handle even if the range covers the whole file. This may not be a problem in practice since we don't need to be that accurate, but it may fail some tests. This PR improve the approximate size by including the size handle before the range start, which may result in larger approximate size, but that's generally desirable.
=> Improve approximate size for small data in tests

src/pd/client.rs, src/pd/mod.rs, src/pd/util.rs, tests/pd/test_rpc_client.rs
This PR adds a handler which will be invoked after the client reconnects to PD.  
It's part of region heartbeat cache #2701, for invalidated region cache.
=> pd: handle reconnect

src/pd/client.rs, src/pd/mod.rs, src/pd/util.rs, src/util/mod.rs, tests/pd/mock/server.rs, tests/pd/test_rpc_client.rs
PdClient may leak gRPC calls if PD leader changes rapidly.
Cc #2669
=> pd: cancel unused region heartbeat rpc

Cargo.lock
Fix a potential segfault when we have a very large number of ranges on stack in https://github.com/pingcap/rust-rocksdb/commit/b127863a82fcf7784d5697261207df827f6c74a0.
=> Update rocksdb: fix a segfault

Cargo.lock
Fix a potential segfault when we have a very large number of ranges on stack in https://github.com/pingcap/rust-rocksdb/commit/b127863a82fcf7784d5697261207df827f6c74a0.
=> [cherry-pick] Update rocksdb: fix a segfault

etc/config-template.toml, src/util/io_limiter.rs
The formal default value for snapshot IO is too conservative. BTW this pr is not related to reducing memory usage.
=> tune default snapshot io limitation

benches/bin/mvcc.rs, etc/config-template.toml, src/bin/tikv-server.rs, src/config.rs, src/server/readpool/mod.rs, src/server/server.rs, src/storage/mod.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/coprocessor/test_select.rs, tests/failpoints_cases/test_storage.rs, tests/raftstore/server.rs, tests/raftstore/util.rs, tests/storage/assert_storage.rs, tests/storage/util.rs, tests/storage_cases/test_storage.rs
Since we will have different read pool instances for storage and coprocessor, config and thread name prefix should be separated.
=> separate read pool config and name_prefix

src/raftstore/store/config.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/raftstore_cases/test_snap.rs, tests/raftstore_cases/test_split_region.rs, tests/raftstore_cases/test_transfer_leader.rs
This pr adds configuration entries for merge. Actual implementation see #2502.
=> raftstore/config: support merge

Cargo.lock, Cargo.toml, src/bin/tikv-server.rs, src/import/errors.rs, src/import/service.rs, src/import/sst_importer.rs, src/import/sst_service.rs, src/raftstore/store/peer.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/apply.rs, src/raftstore/store/worker/cleanup_sst.rs, src/raftstore/store/worker/mod.rs, src/server/node.rs, src/server/server.rs, tests/import/sst_service.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore/util.rs, tests/raftstore_cases/test_bootstrap.rs
An uploaded SST file can be ingested to a region by sending an IngestSST request. The client must guarantee that the SST file has been uploaded to each peer of the region before issuing the IngestSST request. Upon ingestion, the metadata of the SST file will be replicated to the raft group first. Then before the IngestSST command can be applied, the range and the epoch of the metadata must be checked, and the length and checksum of the coresponding SST file must match the metadata too. Finally, the SST file will be deleted after it has been applied.
The coresponding kvproto PR: https://github.com/pingcap/kvproto/pull/224
=> Implement IngestSST API

benches/bin/bench-tikv.rs, tests/failpoints.rs, tests/failpoints_cases/test_pending_peers.rs, tests/failpoints_cases/test_snap.rs, tests/integrations.rs, tests/raftstore/pd.rs, tests/raftstore/util.rs, tests/raftstore_cases/test_clear_stale_data.rs, tests/raftstore_cases/test_conf_change.rs, tests/raftstore_cases/test_lease_read.rs, tests/raftstore_cases/test_region_heartbeat.rs, tests/raftstore_cases/test_snap.rs, tests/raftstore_cases/test_split_region.rs, tests/raftstore_cases/test_stale_peer.rs, tests/raftstore_cases/test_stats.rs, tests/raftstore_cases/test_tombstone.rs, tests/raftstore_cases/test_transfer_leader.rs
In tests, the mock pd-server(TestPdClient::Cluster) does not push region heartbeat responses. This PR try to simulate pushing by polling responses in the background. 
It's part of region heartbeat cache #2701, for fixing tests.
=> tests: poll HeartbeatResponse

build.rs
"%I" lose the information about am or pm, replace it with "%H".
=> fix build.rs: replace "%I" with "%H".

Cargo.lock, src/coprocessor/checksum.rs, src/coprocessor/dag/mod.rs, src/coprocessor/endpoint.rs, src/coprocessor/mod.rs, tests/coprocessor/mod.rs, tests/coprocessor/test_checksum.rs, tests/coprocessor/test_select.rs, tests/integrations.rs
TiDB will support a new command "ADMIN CHECKSUM TABLE tablename", and push down the checksum calculation to TiKV.
The current implementation uses a simple order-independent algorithm to calculate a checksum from all key-values from a table, including records and indices. For every key-value, we first calculate a CRC64 checksum from (key + value), then we XOR all the CRC64 checksums together to get the final checksum.
=> Implement checksum push down request

src/util/config.rs
According `man 3 getmntent`, The pointer returned by `getmntent` points to a static area of memory which is overwritten by subsequent calls. So we use a lock to protect it in order to avoid `make dev` fail.
`libc` doesn't have `getmntent_r`, so we need a explicitly lock.
=> add lock on `get_fs_info`.

src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/apply.rs, src/server/debug.rs, tests/failpoints_cases/test_merge.rs, tests/raftstore_cases/test_merge.rs
Otherwise, gc messages can be skipped when received a stale message, which will lead to orphan replica.
=> apply/merge: use `mark_merge_done`

tests/coprocessor/test_select.rs
Init `endpoint::Host` with default config will spawn too many worker threads, which maybe cause `Resource temporary unavaliable`. This PR fix it by limit the `end-point-concurrency` to 2.
=> Limit end-point-concurrency in coprocessor test.

circle.yml
Cache is saved before tests start on circleci, so everytime tests are run, compilation has to start from scratch. This pr adds build temporary result to cache to speed up ci check.
=> CI: cache build temporary result

etc/config-template.toml, src/raftstore/store/config.rs, src/raftstore/store/msg.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/cleanup_sst.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/import/sst_service.rs
The import SST process is divided into two steps:
1. Upload an SST file to all peers of a region
2. Ingest the SST file to the region with a Raft command
However, since these two steps are not atomic, a lot of reasons can
stop a client from ingesting an uploaded SST file to the region. In
that case, the uploaded SST file will remain in the import
directory. So we need a way to clean up these obsoleted SST files.
Before we can delete an uploaded SST file, we need to make sure that
the SST file will not be ingested anymore.
We need to guarantee one of these:
1. The epoch of the SST is staler than the local region peer
2. The region information from PD shows that the SST does not belong
to the store, and there is no stale peer of that region in the store too.
=> Cleanup import SST files periodically

src/raftstore/store/config.rs, src/raftstore/store/msg.rs, src/raftstore/store/store.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/raftstore/util.rs, tests/raftstore_cases/test_lease_read.rs
In the current implementation, we check peer stale state on every raft tick, which is a little aggressive, and may log a lot of `leader missing longer than max_leader_missing_duration`. It should be relaxed.
=> raftstore: relax abnormal leader missing check

Cargo.lock, src/bin/tikv-server.rs, src/config.rs, src/util/config.rs, tests/config/mod.rs, tests/config/test-custom.toml
Some of these configs may be tuned without restart, but some of them
are hard to be changed on the fly, this is the best we can do for now,
but we will explore the possibilities in the future.
=>  Add import-mode argument to tune configs for importing data

src/coprocessor/endpoint.rs, src/server/mod.rs, src/server/server.rs, src/server/service/kv.rs, tests/coprocessor/test_select.rs
In PR #2827 I attempted to replace CpuPools with a ReadPool (recall that ReadPool is a collection of FuturePools with different priorities).
Because CpuPool is passed from endpoint into outside currently, PR #2827 has to extract the FuturePool from ReadPool for passing out, which is bad because it breaks the encapsulation.
This PR avoids leaking CpuPool out of `endpoint`. Basically the idea behind is to simplify the OnResponse callback. Now `OnResponse::Streaming` is a callback for a `Stream` **which is ready to poll** in Grpc threads. In other words, `OnResponse::Streaming` can be used to build `Stream<Item=Future<Item=T>>` (`OnResponse::Unary` can be used to build `Future<Item=T>`).
@hicqu PTAL
=> Avoid passing CpuPool into OnResponse

tests/failpoints_cases/test_merge.rs, tests/raftstore/util.rs, tests/raftstore_cases/test_merge.rs
Compact log can stop peer from merging, this pr ensures compaction won't get in the way when merge is tested.
=> tests: improve merge tests

tests/raftstore_cases/test_snap.rs
Snapshot can be deleted before it is sent to follower if timeout is too small.
=> tests: increase snap gc timeout

tests/failpoints_cases/test_merge.rs
Synchronize apply result to make sure rollback check always work.
=> tests: make merge rollback tests more stable

Cargo.lock, etc/config-template.toml, src/bin/signal_handler.rs, src/bin/tikv-server.rs, src/import/config.rs, src/import/engine.rs, src/import/errors.rs, src/import/kv_importer.rs, src/import/kv_server.rs, src/import/kv_service.rs, src/import/metrics.rs, src/import/mod.rs, src/import/sst_importer.rs, src/server/service/kv.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/import/kv_service.rs, tests/import/mod.rs
Implement Open/Write/Close APIs to write key-value pairs to import
server.
`Open` opens an engine identified by an UUID.
`Write` creates a write stream to write key-value batch to the opened
engine. Different clients can write to the same engine concurrently.
`Close` closes the engine after all write batches are finished. An
engine can only be closed when all write streams are closed. An engine
can only be closed once, and it can not be opened again once it is
closed.
After these three steps, the data in the engine is ready to be
imported to TiKV, but the `Import` API is not included in this PR.
=> Add ImportKV service

src/util/transport.rs
This was left behind in #2928 because it was changed after the PR was proposed.
=> A remaining IntCounter

src/util/rocksdb/engine_metrics.rs
The TickerType::NoIterators is actually used as a Guage in
RocksDB. When we require an iterator, the ticker increase 1, and when
we release the iterator, the ticker decrease 1. So if we reset the
ticker after we have required an iterator but before we have released
it, the ticker can be negative. Since we don't care about this ticker
yet, I just remove it here.
=> Remove a misused rocksdb ticker

src/raftstore/store/peer.rs
When the queues are not used anymore, they can be shrink to a smaller one to save memory.
=> raftstore: gc queues

src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/dag/executor/table_scan.rs, tests/coprocessor/test_select.rs
There was a bug when collecting coprocessor metrics. The bug would
cause TiKV print wrong logs and return coprocessor Response with
bad `exec_detail`.
=> fix coprocessor metrics collect bug.

Cargo.lock
update rust-rocksdb to the latest version.
=> Rocksdb: update to fix rocksdb direct io

src/util/logger.rs
Since #2774, logger no longer collects raft's log. This PR brings them back.
=> logger: collect raft's log

Cargo.toml
crossbeam-channel uses some new rust features behind nightly gate.
Considering TiKV also uses rust-nightly, let's open the gate.
=> Open nightly feature gate for crossbeam-channel.

src/raftstore/coprocessor/dispatcher.rs, src/raftstore/coprocessor/mod.rs, src/raftstore/coprocessor/split_check/half.rs, src/raftstore/coprocessor/split_check/mod.rs, src/raftstore/coprocessor/split_check/size.rs, src/raftstore/coprocessor/split_check/table.rs, src/raftstore/store/store.rs, src/raftstore/store/worker/split_check.rs
This pr adds a `SplitChecker` trait and `SplitCheckerHost` to abstract the check logic from the split check worker and make things clear. Also the new mechanism is a little more efficient than the original one as table checker can be omitted if suitable.
After this is merged, I will add batch split support.
=> observer/split_check: clean up

src/bin/tikv-importer.rs, src/bin/tikv-server.rs, src/util/panic_hook.rs, tests/failpoints.rs, tests/integrations.rs, tests/util/mod.rs
Panics as aborts, it's helpful for debug. There is a feature `panic=abort` in rust, but unfortunately it does work in tests.
=> util/panic_hook, test: panics as aborts

src/storage/mvcc/reader.rs, tests/storage_cases/test_storage.rs
When we adding an index, the row will be locked with 'lock' type, which means it's not allowed to write.
But the value is not changed. We can continue to read the row without the need to return an lock error when we meet the lock.
@disksing @zhangjinpeng1987 @coocood PTAL
=> mvcc/reader: ignore Lock when lock's type is Lock

src/coprocessor/endpoint.rs
In addition, added special string `[slow_query]` for easier grep.
=> Show wait time and reverse scan in slow log

src/lib.rs, src/raftstore/store/snap.rs, src/server/debug.rs, src/util/file.rs
It's easy to write bug for tracking snapshot size with `RwLock`, especially for now rustc is not smart enough to deconstruct `LockGuard`s ASAP. For example, in function `Snap::save_cf_files` the lock won't be released until the file crc32 is calculated. If the file is large, it will take a long while so that maybe block `raftstore` thread.
This PR fix this issue by replace `RwLock` with `AtomicU64`.
=> Use AtomicU64 instead RwLock for tracking snapshot size.

src/bin/tikv-ctl.rs, src/coprocessor/codec/mysql/json/binary.rs, src/coprocessor/dag/expr/mod.rs, src/util/codec/mod.rs, src/util/codec/number.rs
=> codec/number: decode number by access slice directly

Cargo.toml, src/server/service/kv.rs, src/storage/mod.rs, tests/storage/assert_storage.rs, tests/storage/sync_storage.rs, tests/storage_cases/test_storage.rs
TiDB DDL needs to use this feature.
https://github.com/pingcap/kvproto/pull/258
=> storage: support reverse scan

Cargo.lock, Cargo.toml, benches/benches.rs, benches/bin/bench-tikv.rs, etc/config-template.toml, src/bin/setup.rs, src/bin/tikv-importer.rs, src/bin/tikv-server.rs, src/config.rs, src/lib.rs, src/util/file_log.rs, src/util/logger.rs, tests/config/mod.rs, tests/failpoints.rs, tests/integrations.rs, tests/util/mod.rs
After speaking with @siddontang we think this is a better option than https://github.com/pingcap/tikv/pull/2997.
We noted with some users that logging was taking a considerable amount of time during system operation. This is due to the fact that the `log` crate operates syncronously. We noted when exploring #2997 that moving to asyncronous logging was measurably faster.
During our discussion it was decided that `slog` was a good alternative that offered built in asyncronous logging capabilities. It offers other benefits as well, such as structured logging and fancy terminal output.
This PR moves us to using `slog` via the `slog_stdlog` crate which essentially adapts the `log` based macros to use `slog`. In the future we can place work into migrating to the `slog` based logging macros …
=> *: Use slog

src/raftstore/store/peer.rs, src/raftstore/store/store.rs
It's part of #3045 . We should apply all changes before advancing apply.
=> store: apply all changes before advancing apply

src/raftstore/store/snap.rs
When drop snapshot it shouldn't delete tmp files created by others.
=> Snapshot can only remove tmp files created by itself.

src/server/service/kv.rs, src/storage/mvcc/txn.rs, tests/storage/assert_storage.rs, tests/storage_cases/test_storage.rs
Hi，
This PR adjust `WriteConflict` error in KeyError, it moves from retryable to conflict field. @disksing @tiancaiamao @breeswish PTAL
=> service/kv: adjust WriteConflict error in KeyError

src/coprocessor/codec/chunk/column.rs, src/coprocessor/codec/datum.rs, src/coprocessor/codec/table.rs, src/coprocessor/dag/executor/mod.rs, src/coprocessor/dag/expr/mod.rs, src/raftstore/coprocessor/split_observer.rs, src/raftstore/store/snap.rs, src/storage/mvcc/lock.rs, src/storage/mvcc/write.rs, src/storage/types.rs, src/util/codec/bytes.rs, src/util/codec/number.rs, src/util/rocksdb/properties.rs
Hi, 
This PR removes  the trait `NumberDecoder`.
@hicqu @BusyJay @breeswish PTAL
=> codec/number: remove trait NumberDecoder

src/raftstore/store/metrics.rs, src/server/metrics.rs
For large snapshot or slow network, metrics of sending/generating snapshots need to be increased.
Fix #3085 .
=> increase snapshot send/generate metrics.

Cargo.lock, Cargo.toml, src/bin/tikv-ctl.rs, src/server/debug.rs, src/server/service/debug.rs
The output looks like this:
```
$ bin/tikv-ctl --host 127.0.0.1:20160 region-properties -r 4                                                                                           huachao@Huachao-X1
num_files: 1
num_entries: 384374
num_deletes: 1245
mvcc.min_ts: 400469785325076491
mvcc.max_ts: 400470640006266884
mvcc.num_rows: 383097
mvcc.num_puts: 383115
mvcc.num_versions: 383129
mvcc.max_row_versions: 15
```
=> tikv-ctl: add region-properties

Cargo.lock, Cargo.toml, benches/serialization/bench_serialization.rs, src/coprocessor/statistics/cmsketch.rs, src/coprocessor/statistics/fmsketch.rs, src/lib.rs, src/pd/util.rs, src/raftstore/store/peer.rs, src/server/debug.rs, src/util/collections.rs, tests/pd/mock/mocker/service.rs, tests/raftstore/cluster.rs, tests/raftstore/node.rs, tests/raftstore/pd.rs, tests/raftstore/server.rs, tests/raftstore/transport_simulate.rs, tests/raftstore_cases/test_compact_log.rs
Most of use cases of hashing in our codebase is to hash a u64/i64. fxhash is much faster than fnvhash in this case.
A simple benchmark shows that:
```
test bench_fnv_3  ... bench:           7 ns/iter (+/- 0)
test bench_fnv_5  ... bench:           7 ns/iter (+/- 0)
test bench_fx_3   ... bench:           3 ns/iter (+/- 0)
test bench_fx_5   ... bench:           3 ns/iter (+/- 0)
test bench_iter_3 ... bench:           5 ns/iter (+/- 0)
test bench_iter_5 ... bench:           6 ns/iter (+/- 0)
```
`bench_fnv_3` means querying elements of FnvHashMap which contains 3 elements. `bench_iter_3` means using pure iteration.
close #3032, #2851 and #1843.
=> *: use fxhash

Cargo.lock
Bumps the rocksdb version we use to include a backported patch that
resolves the relevant warnings.
Related:
https://github.com/pingcap/rocksdb/pull/22
https://github.com/pingcap/rust-rocksdb/pull/207
=> Fix C++ 8.1 build errors.

src/coprocessor/codec/mysql/decimal.rs
Hi，
It seems a bug exist according to tidb's implementation: https://github.com/pingcap/tidb/blob/master/types/mydecimal.go#L1519
And the corresponding case is data with lots of suffix 0:
```
3.10000000000-2.00
3.00-2.00000000000
```
@BusyJay @coocood
=> decimal: fix bug in do_sub

src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/region_snapshot.rs, src/raftstore/store/store.rs
Add getter and setter for region, so it is easy to add a hook when we updates Peer's region.
Cc #2639
=> raftstore: getter/setter for region

tests/failpoints_cases/test_snap.rs, tests/raftstore/transport_simulate.rs
This is in preparation for #3133 .
This allows the tester to get notified of any particular message type instead of just Snapshots.
=> Make MessageTypeNotifier generic

src/server/config.rs, src/storage/config.rs, tests/config/mod.rs, tests/config/test-custom.toml
Notify and message per tick are not used in Server, we can remove them.
PTAL @BusyJay @overvenus
=> *: remove unnecessary configs

benches/bin/utils.rs, src/coprocessor/codec/table.rs, src/coprocessor/dag/executor/scanner.rs, src/coprocessor/dag/executor/topn.rs, src/raftstore/coprocessor/split_observer.rs, tests/coprocessor/test_select.rs
Now the function in master is defined as follows:
```
/// `encode_row_key` encodes the table id and record handle into a byte array.
pub fn encode_row_key(table_id: i64, encoded_handle: &[u8]) -> Vec<u8>
```
And this PR defined it like following to make it more easy to use
```
/// `encode_row_key` encodes the table id and record handle into a byte array.
pub fn encode_row_key(table_id: i64, handle: i64) -> Vec<u8>
```
unit test
no
no
https://github.com/pingcap/tikv/issues/3157
@BusyJay @breeswish PTAL
=> codec/table: refactor encode_row_key

tests/raftstore/cluster.rs, tests/raftstore_cases/test_conf_change.rs
- Allow more one snapshots to be sent to fix `test_learner_with_slow_snapshot`
- Enlarge the timeout for `query_leader` to fix "can't get leader of
region xxx" in some tests
- Unit tests
No.
No.
https://github.com/pingcap/tikv/pull/3211
=> tests: fix some tests

tests/util/mod.rs
CaseTraceLogger relies on test's thread name, however slog_async has
its own thread, and the name is "".
TODO: Enable the slog_async when the [Custom test frameworks][1] is mature,
and hook the slog_async logger to every test cases.
[1]: https://github.com/rust-lang/rfcs/blob/master/text/2318-custom-test-frameworks.md
=> tests: fix tracing test

src/coprocessor/codec/table.rs, src/coprocessor/statistics/analyze.rs, tests/coprocessor/test_analyze.rs
In the before, we only record the row count for the whole index, this pr also records the row count for each index prefix. Therefore, for an index (a, b, c), not only could we know the row count for (a = 1 and b = 1 and c = 1), but also the row count for (a = 1) or (a = 1 and b = 1).
unit test and integration test with tidb.
No.
No.
PTAL @AndreMouche @coocood
=> coprocessor: collect row count for each index prefix

src/bin/util/setup.rs
We found that the default size of 128 with DropAndReport creates some
problems for us when there is, for example, high region turnover.
This commit makes the channel (much) bigger and configures the channel
to block when overflowing instead of dropping things.
We discussed that there might be some slowdown with the logging itself but it was not the case.
What are the type of the changes? (mandatory)
How has this PR been tested? (mandatory)
Does this PR affect documentation (docs/docs-cn) update? (mandatory)
Does this PR affect tidb-ansible update? (mandatory)
References:
- N/A
Benchmark Result:
- N/A
Examples/Additional Info:
> N/A
=> logger: Bigger channel and blocks on overflow.

src/coprocessor/codec/mysql/decimal.rs
This PR fix bug in the function `do_mul` of decimal,
The master will panic in the following case:
```
0.00000000000000*0.000000000000000000000000000000000000000000000000000000000000000
```
unit test
no
no
https://github.com/pingcap/tikv/pull/3190
The related code in tidb: https://github.com/pingcap/tidb/blob/master/types/mydecimal.go#L1725
=> decimal:fix bug caused by do_mul

Cargo.lock, Cargo.toml, etc/config-template.toml, etc/tikv-importer.toml, src/import/client.rs, src/import/common.rs, src/import/config.rs, src/import/engine.rs, src/import/errors.rs, src/import/import.rs, src/import/kv_importer.rs, src/import/kv_service.rs, src/import/mod.rs, src/import/prepare.rs, src/import/stream.rs, src/import/test_helpers.rs, src/pd/mod.rs, src/util/security.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/import/kv_service.rs
Implement remained ImportKV APIs.
- SwitchMode: switch the target cluster to normal/import mode
- Compact: compact the target cluster to a specific output level
- Import: import the data in the engine to the target cluster
- Cleanup: clean up the data in the engine
- Unit tests
- Integration tests with tidb-lightning in a test environment
No.
No.
https://github.com/pingcap/kvproto/pull/279
The code in this PR has been used by different users for quite a long time unofficially as a custom tikv-importer binary.
However, this PR is huge and may never be reviewed thoroughly, but customers will use it whenever necessary. Since this PR is only related to tikv-importer and has nothing to do with tikv-server, it will be merged after …
=> import: implement ImportKV APIs

.circleci/config.yml
Specifies the version of Tarpaulin to triage the CI breaking.
See https://circleci.com/gh/pingcap/tikv/11095
You can see that in the last week `cargo-tarpaulin` (https://github.com/xd009642/tarpaulin/releases) updated a few times. This has resulted in a recent build breakage on our particular version of nightly. This might be able to be refined in #3066 .
By the CI (which had a build error!)
I do not expect it to.
It should not.
=> circleci: Specify tarpaulin version

CHANGELOG.md, etc/config-template.toml, src/raftstore/store/config.rs
There is a bug when we enable both check_quorum and prevote, which leads no leader. In order to release a stable 2.1-beta, we should disable prevote temporary.
See more: https://github.com/coreos/etcd/issues/9586
=> raftstore: disable PreVote

etc/config-template.toml, src/storage/config.rs
Enlarge the default value of the latch's total slots.
In loading data scenario, we found the default value of total slots of latch is not large enough, it will limit the loading speed because of waiting latch. After we enlarged the total slots,  it became fast.
Currently, the default value of `scheduler-pending-write-threshold` is 100MB, it means there is at most 100MB bytes data is writing or going to be writing, all of the related keys need to occupy the latch. Let's assume the average size of each key value pair is 64 bytes, there are will be about 1.5 million keys. To reduce the probability of waiting latch, the total slots of the latch should large enough. We enlarge the default value of latch slots to 2 million, the latch takes about 100MB memory.
Improvement
CI
No
No
=> Enlarge the total slots of scheduler latch

.circleci/config.yml, ci-build/test.sh, src/coprocessor/codec/datum.rs, src/raftstore/store/peer.rs, src/util/mpsc.rs
Turns out clippy check is disabled at some point in CI, now I can see several warnings in master branch. This pr enables the check again.
close #3292.
=> ci: enable clippy check

tests/failpoints_cases/test_merge.rs
After split, any node of new region can become leader. So if leader is isolated later, the tests will fail due to the progresses in new leader is always 0. This pr transfers leader immediately after split to guarantee leader won't be isolated.
close #3255.
=> tests: transfer leader before merge

src/util/mpsc.rs
Timeout is not precise on Mac OS. This pr relax it by only checking the lower bound.
Close #3298.
=> tests: relax channel timeout check

tests/raftstore_cases/test_service.rs
The case fails occasionally as it's not written correctly. Snapshot meta will be validated when it's received. However the meta being sent is empty, so it's meant to be rejected, and the RPC should fail eventually. Whether the case fails depends on how the network performs.
Actually the raft and snapshot RPCs are tested in the test_snapshot files already, so here the case is redundant. Let's remove the case instead of fixing it.
Close #3218.
=> tests: remove redundant raft rpc case

benches/bin/raftstore.rs, src/bin/util/signal_handler.rs, src/raftstore/store/bootstrap.rs, src/raftstore/store/mod.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/region_snapshot.rs, src/raftstore/store/store.rs, src/raftstore/store/util.rs, src/raftstore/store/worker/apply.rs, src/raftstore/store/worker/region.rs, src/server/debug.rs, src/server/node.rs, src/server/service/debug.rs, src/util/rocksdb/metrics_flusher.rs, tests/raftstore/cluster.rs, tests/raftstore/node.rs, tests/raftstore/server.rs, tests/raftstore_cases/test_compact_after_delete.rs, tests/raftstore_cases/test_compact_lock_cf.rs, tests/raftstore_cases/test_compact_log.rs, tests/raftstore_cases/test_multi.rs, tests/raftstore_cases/test_split_region.rs, tests/raftstore_cases/test_transport.rs, tests/raftstore_cases/test_update_region_size.rs
This pr cleans up the usage of `Engines`. First, it replaces all places that use both kv and raft engines with `Engines`. Second, it removes the redundant `_engine` suffix.
The changes can also help simplifying `Peer`'s constructor later.
=> *: clean up engines

src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/mod.rs, src/coprocessor/dag/executor/aggregate.rs
fix [issue#6987](https://github.com/pingcap/tidb/issues/6987#event-1717221272)
bit_or doesn't handle decimal
Bug fix
unittest
No.
https://github.com/pingcap/tidb/pull/6994
@breeswish @XuHuaiyu PTAL
=> aggregation: handle non-integer input for bit related  functions

Cargo.lock, Cargo.toml, src/bin/tikv-ctl.rs, src/server/debug.rs, src/server/service/debug.rs
Add a bottommost level compaction option for the compact command to make it more flexible.
TODO
TODO
No.
https://github.com/pingcap/kvproto/pull/284
https://github.com/pingcap/rust-rocksdb/pull/212
=> tikv-ctl: add bottommost level compaction

src/storage/mvcc/mod.rs
It is similar to #3339, escapes raw `Vec<u8>` to `String`,
=> mvcc: escape keys in Error

src/server/service/kv.rs, src/storage/mod.rs, src/storage/mvcc/reader.rs, src/storage/txn/scheduler.rs, tests/storage/assert_storage.rs, tests/storage/sync_storage.rs, tests/storage_cases/test_raft_storage.rs, tests/storage_cases/test_storage.rs
This PR is extracted from the [Mvcc Refine PR](https://github.com/pingcap/tikv/pull/3344). It changes the name `scan_lock` in storage into`scan_locks` to conform existing naming conventions (i.e. we have `scan_keys`, `scan_values_xxx`, etc.)
- Trivial change
Compiler pass
No.
No.
=> Rename scan_lock -> scan_locks

src/storage/mod.rs
This PR is extracted from the [Mvcc Refine PR](https://github.com/pingcap/tikv/pull/3344). It changes the signature of `rawkv_cf` from `String` to `&str`. This can avoid copying cf names when there is no ownership.
Compile.
No.
No.
No benchmark.
=> Accept &str instead of String for rawkv_cf

src/storage/engine/mod.rs, src/storage/mvcc/reader/cf_reader.rs, src/storage/mvcc/reader/forward_scanner.rs, src/storage/mvcc/reader/point_getter.rs, src/storage/types.rs
This PR is an improvement over the proposed [Mvcc refinement PR](https://github.com/tikv/tikv/pull/3344).
It:
- Mostly removes the usage of near_seek in forward scan
- Prevents key clone in more cases
- Adds very verbose comments
CI
No
No
Later.
=> [MVCC PR] Improve forward scan

src/raftstore/store/region_snapshot.rs, src/storage/engine/mod.rs, src/storage/mod.rs, src/storage/mvcc/reader.rs, tests/storage_cases/test_raftkv.rs
Previously our flow statistics is not very accurate. For example, when doing `near_seek`, the read during each `next()` attempt is not counted in the statistics. According to PD developers, these read flows should be counted however. Also, previously we self-implemented some read statistics in raw_scan and raw_batch_scan.
This PR moves the read flow statistics logic from mvcc layer into `Cursor` layer, the same as CFStatistics. In detail, when `key()` or `value()` is called, its read flow is counted. Subsequent calls will not be counted unless the cursor is moved (e.g. by `seek()`, `next()`, etc).
This change is extracted from the [Mvcc Refinement PR](https://github.com/pingcap/tikv/pull/3344).
CI
No.
No. …
=> Move read flow statistics to cursor

src/bin/tikv-ctl.rs
Output Unit "Byte" for tikv-ctl
Improvement
manual tests
no
no
#3186
=> Output Unit "Byte" for tikv-ctl

src/import/client.rs, src/raftstore/coprocessor/split_check/table.rs, src/raftstore/store/region_snapshot.rs, src/raftstore/store/util.rs, src/server/debug.rs, src/storage/mod.rs, src/storage/mvcc/reader.rs, src/storage/types.rs
- add `from_encoded_slice()` that reserve capacity for timestamp
- call `from_encoded_slice()` instead of `from_encoded(xxx.to_vec()/to_own())` in some code place, but not all cause `xxx` maybe timestamped key slice and there is no need to reserve more capacity.
No need
No need
No need
=> util: add from_encoded_slice

src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/worker/apply.rs, src/raftstore/store/worker/read.rs
Remove `pub` for some fields in `PeerStorage`. Users should use set/get to access them.
It's good for adding some follow-up action after we update these fields.
Improvement.
make dev.
No.
No.
=> Use get/set to access peer_storage internal state.

src/storage/engine/mod.rs, src/storage/mvcc/reader/backward_scanner.rs
This PR is merging to #3344 .
In this PR, `near_seek_for_prev` call is removed from `BackwardScanner`. The logic of `near_seek_for_prev` was put in `BackwardScanner` itself.
By already-existed unit tests
No
No
=> reader/backward_scanner: Remove near_seek_for_prev from backward_scanner

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin function: `ASCII`  in `coprocessor`.
This is for #3275
Improvement
unittest
#3275
=> coprocessor/dag/expr: add some un-pushed builtin UDF(ASCII)

src/storage/engine/mod.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/txn.rs
This PR moves and exposes some test utility functions of storage/engine and storage/mvcc, so that other parts can utilize them as well.
This change is extracted from [Mvcc Refinement PR](https://github.com/tikv/tikv/pull/3344).
CI.
No.
No.
=> Expose test utils for engine and mvcc

tests/raftstore_cases/mod.rs, tests/raftstore_cases/test_prevote.rs
Trying to make the `test_prevote` tests reliable on CI, seems it's not possible without changing some behavior around cluster/simulator.
This is not a bug in the code, it's just that we don't have a way to clear a particular send filter, so we can only attach our notifiers after clearing the send filters, meaning that the prevote message could appear before we are detecting it. Several reproductions showed a prevote appearing at the same nanosecond as the notifiers, so we miss it.
The CI
no
no
=> tests: Relax some Prevote tests.

src/coprocessor/dag/executor/scanner.rs, src/coprocessor/util.rs
This PR is extracted from #3344 .
In this PR, calculation of `prefix_next` won't create a new `Vec` and drop the old one. Instead, it does the calculation just on the original `Vec`.
The `is_point` function needs to check if a key is prefix_next of another one. Previously it calculates the prefix_next and compare to the another one. Now there's a new `is_prefix_next` function which can do this without creating a new key.
By new unit tests
No
No
* #3344 
* #3414
=> coprocessor/util: prefix_next optimization

src/bin/tikv-server.rs, src/raftstore/store/store.rs, src/util/config.rs, src/util/sys/mod.rs
When going through the TiKV startup log I saw messages that were difficult to understand. These changes would help me understand the log messages (and code in one case) more quickly.
This change affects log messages, but I don't think we have any contract for those.
`make`. I have not actually looked at the log output after these changes.
no
no
=> add detailed information in error logs

benches/benches.rs, benches/coprocessor/codec/mod.rs, benches/coprocessor/dag/expr/mod.rs, benches/coprocessor/dag/expr/scalar.rs, benches/coprocessor/dag/mod.rs, benches/coprocessor/mod.rs
Add some benchmark cases to ensure whether we need to introduce some optimizations from Go.
In Go, I found that using BigEndian to read u16 is faster than comparing table prefix. And sometimes, using a map is faster than switch-case. 
But in Rust, seem that we don't need these optimizations.
No
No need
No
No
test coprocessor::dag::expr::scalar::bench_get_scalar_args_with_map   ... bench:       7,700 ns/iter (+/- 1,349)
test coprocessor::dag::expr::scalar::bench_get_scalar_args_with_match ... bench:       2,811 ns/iter (+/- 220)
test coprocessor::codec::bench_table_prefix_check                     ... bench:         555 ns/iter (+/- 24)
test coprocessor::codec::bench_table_prefix_start_with                ... bench:         563 ns/iter (+/- 31)
test …
=> benches/coprocessor: add some benchmark cases

src/storage/mvcc/reader/backward_scanner.rs, src/storage/mvcc/reader/forward_scanner.rs
This PR is merging to #3344
There are some places where can be slightly optimized in MVCC scanners.
In this PR:
* In BackwardScanner: removed `last_handled_key` from `reverse_get`, use timestamp compares instead, which is faster than comparing keys.
* Avoid reallocation at `append_ts` in both ForwardScanner and BackwardScanner.
* (Maybe more changes later)
By `make dev`
No
No
#3344
=> [Mvcc refinement]  optimize mvcc scanners

src/coprocessor/codec/convert.rs, src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/json/json_cast.rs, src/coprocessor/dag/dag.rs, src/coprocessor/dag/executor/aggregate.rs, src/coprocessor/dag/expr/builtin_arithmetic.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/ctx.rs, src/coprocessor/dag/expr/mod.rs
- Added `EvalConfigBuilder` described in #3303 
- Replaced some usages of `EvalConfig` with `EvalConfigBuilder`
- Improvement
No test needed since no user-logic is changed.
No.
No.
=> coprocessor: add EvalConfigBuilder

components/test_raftstore/server.rs, src/bin/tikv-server.rs, src/server/server.rs
Change the max-grpc-message-size to i32::MAX.
The old configuration is:
```rust
builder.max_send_message_len(cmp::max(region_split_size * 4, i32::MAX as usize) as i32)
```
The **cmp::max** should be **cmp::min** in fact, so it's a bug. However, set it to `i32::MAX` maybe is more better because if the region doesn't split as expected, and its size grows vary large, a gRPC error will be raised.
So this PR changes it to `i32::MAX`. So we won't meet the error any more. 
Bug fix.
make dev.
No.
No.
=> Set max-message-size to i32::MAX.

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
add some un-pushed builtin UDFs(Sqrt)
This is for #3275
Improvement
unit tests
No
No
#3275
=> coprocessor/dag/expr: add un-pushed builtin UDFs(Sqrt)

src/pd/util.rs, tests/pd/mock/mocker/mod.rs, tests/pd/mock/mocker/retry.rs, tests/pd/test_rpc_client.rs
- return actual err from pd_client, before will return "fail to request" anyway and print error log innerly
- no need to retry errors that from response header
integration-test
No
No
=> pd: return actual err from pd_client

src/raftstore/coprocessor/config.rs, src/raftstore/coprocessor/dispatcher.rs, src/raftstore/coprocessor/split_check/keys.rs, src/raftstore/coprocessor/split_check/size.rs, tests/config/mod.rs, tests/config/test-custom.toml, tests/raftstore_cases/test_split_region.rs
For batch split PR, we just make it possible for split-checker to return multiple keys. But actually the implementation of split-checks doesn't change which is still producing only one key. This PR is support to produce multiple split keys.  
unit-test
New config
=> Split-checkers support produce multiple split keys

src/coprocessor/dag/executor/aggregate.rs, src/coprocessor/dag/executor/aggregation.rs
Associate a buffer to AggFuncExpr so that TiKV won't alloc it for every row.
Improvement.
make dev.
No.
No.
=> associate a buffer to AggFuncExpr to reduce memory alloc.

components/test_raftstore/pd.rs, components/test_raftstore/util.rs, src/raftstore/store/store.rs, tests/raftstore_cases/test_merge.rs, tests/raftstore_cases/test_split_region.rs
After merge set `peer.size_diff_hint` to make sure approximate size and keys updated in time. Due to `split_check_diff`, when there is no write to this region, the size and keys may incorrect and lead to PD produce wrong schedule.
unit test
manual test
No 
No
=> raftstore: update approximate size and keys after merge

src/pd/pd.rs, src/raftstore/store/msg.rs, src/raftstore/store/store.rs, src/raftstore/store/util.rs
escape batch split keys and only print out the first and last split key.
No need
No
No
=> *: escape batch split keys

src/bin/tikv-ctl.rs
Signed-off-by: Xiaoguang Sun <sunxiaoguang@gmail.com>
Print help message when no argument is given to tikv-ctl
Running tikv-ctl without any argument manually gets help message back instead of panicking 
No
No
#3453
=> Print help message when starting tikv-ctl without argument

src/pd/pd.rs, src/raftstore/store/fsm/mod.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/mod.rs, src/raftstore/store/peer.rs, src/raftstore/store/worker/read.rs
This PR divides store module into two parts: one is for overall store
operations, the other is for region related operations. It's very
helpful for threaded raftstore experiment, as it can reduce the conflict
a lot.
=>  raftstore: split store module

docs/clients/go-client-api.md, docs/op-guide/deploy-tikv-using-ansible.md, docs/op-guide/deploy-tikv-using-binary.md, docs/op-guide/deploy-tikv-using-docker-compose.md, docs/op-guide/deploy-tikv-using-docker.md, docs/overview.md
Add the following TiKV documents:
- Overview
- Install and Deploy TiKV
- Install and Deploy TiKV Using Docker Compose
- Install and Deploy TiKV Using Ansible
- Install and Deploy TiKV Using Docker
- Install and Deploy TiKV Using Binary Files
- Client Drivers
- Go
Relevant.
No.
=> docs/*: add overview, op-guide, client

src/raftstore/coprocessor/mod.rs, src/raftstore/coprocessor/split_check/half.rs, src/raftstore/coprocessor/split_check/mod.rs, src/raftstore/coprocessor/split_check/size.rs, src/raftstore/store/util.rs, src/raftstore/store/worker/split_check.rs, src/util/rocksdb/properties.rs
This PR adds a way to get approximate split keys. Note that, when `CheckPolicy::APPROXIMATE`, it will call `approximate_split_keys()`, but now split_check_tick will only produce task of `CheckPolicy::SCAN`, I will adjust it in another PR.
unit-test
No need
No
=> raftstore: add a way to get approximate split keys

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
This PR implements the scalar function Atan1Arg and Atan2Args
Improvement
unit test
No
No
#3275
=> coprocessor/dag/expr: add un-pushed builtin UDFs(Atan1Arg, Atan2Args)

tests/storage_cases/test_raftkv.rs
Stabilize test_batch_snapshot. 250ms for leader lease is too short for the test, and causes test failure. 
Unit test.
No.
No.
Fix #3434 .
=> tests: stabilize test_batch_snapshot

src/raftstore/store/util.rs
Manually `impl Debug for RemoteLease`, and makes expired time human readable. It is convenient for debugging lease read tests.
Unit tests.
No.
No.
#3544
=> store/util: human readable expired time

src/coprocessor/dag/executor/scanner.rs, src/storage/gc_worker.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/reader/mod.rs, src/storage/mvcc/txn.rs, src/storage/txn/scheduler.rs, src/storage/txn/store.rs
Before we move `command` to `Msg::WritePrepareFinished`, but actually we just need `ctx` in `command`. Now we just move ctx to `Msg::WritePrepareFinished`, so make other place no need to clone.
- reduce mutation clone in `process_write_impl()`
- reduce key clone
No need
No
No
=> storage/txn: reduce clone in txn scheduler

etc/config-template.toml, src/raftstore/store/config.rs, src/raftstore/store/peer.rs, tests/config/mod.rs, tests/config/test-custom.toml
When user's disk is very fast, current hard-coded value 10 might not be sufficient. This is a hot fix for a client's problem to make it configurable. However we need better solutions in future.
I also by hand changed some outdated default values appear in config files.
Manually.
No.
https://github.com/pingcap/tidb-ansible/pull/510
=> Allow configuring leader transfer max allowed log lag

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
- add math.Sin, as suggested [here](https://pingcap.github.io/blog/adding-built-in-functions-to-tikv/)
unit test
no
no
https://github.com/tikv/tikv/issues/3275
The related source in tidb: https://github.com/pingcap/tidb/blob/55d8eff75859814114f9c6aa3efe2e3f69f7981f/expression/builtin_math.go#L1676
=> expr/builtin_fncall: implement math.Sin

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin function: `CharLength` in `coprocessor`.
This is for #3275
Improvement
unittest
#3275
=> coprocessor/dag/expr: add some un-pushed builtin UDF(CharLength)

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
This PR implements the scalar function Asin and Acos.
unit test
no
no
#3275
=> coprocessor/dag/expr: add un-pushed builtin UDFs(Asin and Acos)

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
expr/builtin_fncall: implement string.{HexIntArg, HexStrArg}
unit test
no
no
#3275
=> expr/builtin_fncall: implement HexIntArg, HexStrArg

.circleci/config.yml
Currently CI is broken. We attempted to fix it previously in #3241, but it turns out that specifying tarpaulin version is not enough. We need to freeze all versions of all tarpaulin's dependencies as well.
Before [tarpaulin publishes its lock file](https://github.com/xd009642/tarpaulin/issues/147) && (maybe) we upgrade our rust version, we need to install tarpaulin from a git location so that Cargo.lock is respected.
CI: https://circleci.com/gh/tikv/tikv/13810
As you can see, Tarpaulin is successfully installed.
No
No
=> Fix CI by installing tarpaulin from git, so that Cargo.lock is not ignored

Cargo.lock, Cargo.toml, components/test_util/lib.rs, src/raftstore/store/peer.rs, tests/raftstore_cases/test_split_region.rs
TiKV disable broadcast commit by default to reduce messages, which lead
to good overall performance. This option can also lead to delay apply on
all follower nodes. Sometimes it's unexpected for urgent requests like
split or similiar. This PR enables broadcast commit for those requests
temporary.
Close #3578.
=> raftstore: bcast commit for urgent requests

src/coprocessor/dag/dag.rs
`DAGContext` does need to be generic.
Extracted from [Coprocessor ReadPool PR](https://github.com/tikv/tikv/pull/3515).
Compiler.
No.
No.
=> Remove Generic from DAGContext

src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, src/raftstore/store/worker/apply.rs, src/raftstore/store/worker/read.rs, tests/failpoints_cases/test_stale_peer.rs
There is a bug when we  destroy peers asychroniously, because we destroy read delegates right after receiving a GC message, peers may send update(region) to its delegate, but the delegate is destroyed already.
This PR fix the bug by lazy remove ReadDelegate when peer is destroyed asychroniously.
Unit tests.
#2639
=> raftstore: lazy remove ReadDelegate when peer is destroyed asynchronously

Cargo.lock, components/test_util/Cargo.toml, components/test_util/lib.rs, components/test_util/logging.rs, src/bin/tikv-importer.rs, src/bin/tikv-server.rs, src/bin/util/setup.rs, src/util/logger.rs, src/util/panic_hook.rs
Flush remaining logs before tikv exits.
Unit tests.
No.
No.
=> *: flush log before exit

src/raftstore/store/fsm/peer.rs, tests/raftstore_cases/test_merge.rs
Messages come from merged peers maybe are still with `is learner = true`, but it has been already promoted on leader, so the check `peer == msg.get_from_peer()` could fail.
This PR fix it.
Bug fix.
make dev.
=> raftstore: fix a check about messages from merged region.

src/storage/mod.rs, src/storage/txn/process.rs, src/storage/txn/scheduler.rs
This PR reduces scheduler msgs, also offloads some functions from scheduler to workers.
Unit tests and integration tests.
No.
No.
#3581 , #3551 and #3582
Combining these changes #3581, #3551 and #3582, QPS is improved from 40672.1 to 49144.5, and avg latnecy is reduced from 100.6ms to 83.5ms.
=> storage: reduce scheduler msgs

src/raftstore/store/fsm/peer.rs, src/raftstore/store/local_metrics.rs, src/raftstore/store/metrics.rs
Signed-off-by: பாலாஜி ஜின்னா <rbalajis25@gmail.com>
I've added metrics for invalid raft proposal
and also changed RaftMetrics to RefCell RaftMetrics
```rust
// Check store_id, make sure that the msg is dispatched to the right place.
util::check_store_id(msg, self.store_id())?;
if msg.has_status_request() {
// For status commands, we handle it here directly.
let resp = self.execute_status_command(msg)?;
return Ok(Some(resp));
}
// Check whether the store has the right peer to handle the request.
let peer = self.check_propose_peer(msg)?; //immutable borrow
// peer_id must be the same as peer's.
util::check_peer_id(msg, peer.peer_id())?;
// Check whether the term is …
```
=> add invalid propose metrics

benches/raftkv/mod.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/metrics.rs, src/raftstore/store/mod.rs, src/raftstore/store/msg.rs, src/raftstore/store/worker/read.rs, src/server/transport.rs, src/storage/engine/mod.rs, src/storage/engine/raftkv.rs, src/storage/engine/rocksdb.rs, tests/storage_cases/test_raftkv.rs
The async batch snapshot API is obsolete. The coprocessor and scheduler no longer use it, so it can be removed.
Unit tests.
No.
No.
#2107 and #3551
=> *: remove async batch snap

src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin funciton: truncate_real
Improvement
unit test
No
No
#3275 #3532
=> expression: add builtin truncate_real

Cargo.lock, Cargo.toml, Makefile, components/codec/Cargo.toml, components/codec/buffer.rs, components/codec/error.rs, components/codec/lib.rs
Previously we found that [Read trait](https://github.com/tikv/tikv/issues/2989) and [Write trait](https://github.com/tikv/tikv/issues/3345) is not efficient.
This PR proposes `BufferWriter` and `BufferReader` as a high-performance alternative to `Write` and `Read` trait. `BufferWriter` and `BufferReader` provides direct access to the underlying buffer slice so that there will be zero copy when reading or writing. As a trade off, it can only operate on memory buffers and does not support other places like Files.
The idea of `BufferWriter` and `BufferReader` comes from [`bytes::Buf`](https://docs.rs/bytes/0.4.10/bytes/trait.Buf.html). However the interface is simplified to further improve performance (from 4ns to 1ns) because there is no …
=> Provide BufferWriter and BufferReader as alternatives to Read and Write trait

docs/ROADMAP.md
Update the roadmap.
- Documentation
=> Roadmap: improve and update

Cargo.toml
Please see https://github.com/tikv/tikv/issues/3640 for details.
I used our [MVCC benchmark](https://github.com/tikv/tikv/pull/3477) to see the performance impact of codegen-units = 2 vs codegen-units = 1:
```
forward_scan/keys = 5000, versions = 1, key_len = 32, value_len = 5
time:   [3.4019 ms 3.6358 ms 3.8353 ms]
change: [-0.4594% +5.4282% +11.678%] (p = 0.10 > 0.05)
forward_scan/keys = 5000, versions = 1, key_len = 32, value_len = 100
time:   [4.4820 ms 4.5976 ms 4.7174 ms]
change: [-11.861% -8.5681% -5.0378%] (p = 0.00 < 0.05)
forward_scan/keys = 5000, versions = 2, key_len = 32, value_len = 5
time:   [4.2251 ms 4.4809 ms 4.7280 ms]
change: [-1.3413% +2.3642% +5.7073%] (p = 0.23 > 0.05)
forward_scan/keys = 5000, versions = 2, key_len …
```
=> Change codegen-units to 1 && Copy release profile to bench

docs/tools/tikv-control.md
This PR fixes some tikv-ctl parameters in documentation.
Related to pingcap/docs#637.
=> docs: fix some tikv-ctl parameters

src/coprocessor/dag/expr/builtin_miscellaneous.rs, src/coprocessor/dag/expr/scalar_function.rs
This PR implements two builtin functions: `InetAton` and `InetNtoa` in coprocessor.
- Improvement
- Unit test
No
No
#3275.
=> coprocessor/dag/expr: add un-pushed builtin UDFs(InetAton, InetNtoa)

fuzz/Cargo.toml, fuzz/README.md, fuzz/fuzz_targets/codec_number.rs
- add fuzzing for number encoder and decoder in util::codec::number.
not yet
#3355
=> fuzz/fuzz_targets/codec_number: add fuzzing for codec number.

src/util/metrics/mod.rs, src/util/metrics/threads_linux.rs
Export ThreadCollector so that we can use it later in other places (ont only for metrics).
Close #3673 .
Improvement.
unit tests.
No.
No.
=> util: export ThreadCollector to use it later.

CHANGELOG.md, Cargo.lock, Cargo.toml
Add changelog and update versions for v2.0.8
No
No
No
=> *: release v2.0.8

docs/tools/pd-control.md
Update PD Control User Guide to make it up-to-date with the version at https://github.com/pingcap/docs/blob/master/tools/pd-control.md.
- Update operator Region split
- Update the output of command health
- Add topsize command and change the default value of limit
- Add more commands
- Fix operator command
Related PRs in pingcap/docs:
- [tools: update operator Region split #658](https://github.com/pingcap/docs/pull/658)
- [pd-ctl: update the output of command health. #642](https://github.com/pingcap/docs/pull/642)
- [pd-ctl: add topsize command and change the default value of limit to 16 #627](https://github.com/pingcap/docs/pull/627)
- [tools: add more commands in pd-control](https://github.com/pingcap/docs/pull/619)
- [tools: change the …
=> docs/tools: update pd-ctl command health and topsize

src/storage/types.rs, src/util/codec/bytes.rs
Signed-off-by: பாலாஜி ஜின்னா <rbalajis25@gmail.com>
appending timestamp length ot codec has been moved to key type
make test
no
no
#3631
=> codec: move timestamp append to key type.

.dockerignore, Dockerfile
The Dockerfile produces an Alpine Linux image now.
I am trying to make our docker runtime uniform.
The docker-compose repo already uses Alpine with glibc.
https://github.com/pingcap/tidb-docker-compose/blob/master/tikv/Dockerfile
This final image matches our production image other than that it uses UTC for TZ instead of /etc/localtime.
It may be the case that this image is not that useful and should be replaced with a more development oriented Dockerfile: let me know.
I only tested by briefly starting TiKV up. That did point out to me that the git hash was missing, which I corrected by removing .git form the .dockerignore
```
➜ tikv git:(docker-alpine) docker run --rm -it pingcap/tikv
2018/10/22 …
```
=> produce an Alpine Linux image

Cargo.lock, Cargo.toml
Switch to release-2.0 branch with some tiny upstream fixes, check https://github.com/pingcap/rocksdb/pull/58.
=> cargo: update rocksdb

components/test_storage/src/assert_storage.rs, src/server/service/kv.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/txn.rs, tests/storage_cases/test_storage.rs
tidb uses the `start_ts` to track down a specific transaction. It will be more useful to use `start_ts` in the WriteConflict error messages.
Update `WriteConflict` error to include both `start_ts` and `commit_ts`. When convert the error to `kvproto::WriteConflict`, use `start_ts` instead of `commit_ts`.
- make dev
no
no
=> mvcc: record start_ts in write conflict error

Cargo.lock, Cargo.toml, components/test_raftstore/Cargo.toml, src/import/kv_service.rs, src/import/sst_service.rs, src/server/raft_client.rs, src/server/service/debug.rs, src/server/service/kv.rs, src/server/snap.rs, tests/pd/mock/server.rs
This reverts commit 839e4a277220af2e25feaf7242c48bb68f3f9074.
Due to grpc/grpc#17043, grpc server threads may meet segment fault and crash the whole tikv.
To workaround the issue, we regress  grpcio to v0.3.
CC #3744
=> *: regress grpcio to v0.3

etc/config-template.toml
Since delete-range is not a RocksDB's stable feature, we remove it from configuration file to avoid users' misusing.
- Improvement
No
No
No
=> remove use-delete-range from configuration file

Cargo.lock, Cargo.toml, benches/storage/scan.rs, components/test_coprocessor/Cargo.toml, components/test_raftstore/Cargo.toml, components/test_storage/Cargo.toml, components/test_storage/assert_storage.rs, components/test_storage/sync_storage.rs, src/server/service/kv.rs, src/storage/gc_worker.rs, src/storage/mod.rs, tests/storage_cases/test_raft_storage.rs
This PR cherry-picks #3720 to release-2.1 branch.
By CI
No.
No.
=> [release-2.1] cherry-pick: Add end_key limit to kv_scan interface (#3720)

Cargo.lock, src/raftstore/store/snap.rs
Use an optimized version of `ingest_external_file_cf`, which try to prevent ingestion from blocking writes.
Check this PR for more information: https://github.com/pingcap/rust-rocksdb/pull/218
- Unit test
No
No
The left-hand side shows the max write latency with the current master.
The right-hand side shows the max write latency with the optimized version in this PR.
=> raftstore: use an optimized method to ingest snapshots

Cargo.lock, Cargo.toml, benches/bin/mvcc.rs, src/server/service/kv.rs, src/storage/mod.rs, tests/storage/assert_storage.rs, tests/storage/sync_storage.rs, tests/storage_cases/test_raft_storage.rs
This PR cherry picks #3720 (commit 7ee13c3) to release-2.0 branch.
This may helps fixing a bug that when kv_scan goes out of range, TiKV may panic.
This PR requires merging https://github.com/pingcap/kvproto/pull/315 first.
By CI
No
No
https://github.com/pingcap/kvproto/pull/315
=> [release-2.0] Cherry-pick: service/kv: Add end_key limit to kv_scan interface (#3720)

benches/storage/scan.rs, components/test_coprocessor/src/store.rs, components/test_raftstore/src/server.rs, components/test_storage/src/assert_storage.rs, components/test_storage/src/sync_storage.rs, components/test_storage/src/util.rs, src/bin/tikv-server.rs, src/config.rs, src/raftstore/store/peer_storage.rs, src/raftstore/store/snap.rs, src/server/node.rs, src/server/server.rs, src/server/service/kv.rs, src/storage/engine/mod.rs, src/storage/engine/raftkv.rs, src/storage/engine/rocksdb.rs, src/storage/gc_worker.rs, src/storage/mod.rs, src/storage/mvcc/reader/backward_scanner.rs, tests/failpoints_cases/test_storage.rs, tests/import/kv_service.rs, tests/storage_cases/test_raft_storage.rs, tests/storage_cases/test_storage.rs
Use lifetime to manage the start and the stop of `Storage`. Storage will be always stopped once it is destroyed and will be always started once it is created.
Resolve https://github.com/tikv/tikv/issues/3759
Resolve https://github.com/tikv/tikv/issues/3756
Several benefits:
- No undefined behaviour any more caused by double `start()` or double `stop()` or `stop()` before `start()` or `start()` after `stop()`.
- Resource will be never leaked if `stop()` is not called.
After this PR, there will be **no** remaining garbage test directories in temp dir.
This PR also fixes https://github.com/tikv/tikv/issues/3767 by adding `worker.stop()`. However the best solution is fixing https://github.com/tikv/tikv/issues/3768 like what we do in this PR .
- Improvement (non-breaking change which is an …
=> Remove `Storage::start()` and `Storage::stop()`

src/raftstore/store/util.rs, src/raftstore/store/worker/raftlog_gc.rs
Use small write batches during raft log gc to reduce latency.
- Manual test
No
No
The left-hand side shows the write latency and write batch size of the master branch.
The right-hand side shows the write latency and write batch size of the branch in this PR.
As you can see, raft log gc will write large batches during heavy write workload, which will cause high write latency. Using small write batches helps to reduce write latency. You may notice that there are still some large write batches at the beginning with this branch, those are written by appending raft logs because of a lot of logs are accumulated during applying snapshot at the very beginning.
=> raftstore: avoid large write batch during raft log gc

Cargo.toml, benches/coprocessor_executors.rs, components/test_coprocessor/src/table.rs, src/coprocessor/mod.rs
This PR introduces more table scan benchmarks.
```
table_scan_primary_key  time:   [1.8638 us 1.9087 us 1.9560 us]        
table_scan_datum_front  time:   [1.5506 us 1.5698 us 1.5898 us]      
table_scan_datum_multi_front                                                                            
time:   [1.5804 us 1.6001 us 1.6205 us]
table_scan_long_datum_front                                                                             
time:   [2.9741 us 3.0109 us 3.0465 us]
table_scan_datum_multi_front                                                                            
time:   [1.5683 us 1.5876 us 1.6078 us]
table_scan_datum_end    time: …
```
=> More table scan benchmarks

tests/raftstore_cases/test_split_region.rs
This PR stables test_delay_split_region. There is a mistake in the test that we should have sent a new request to original region after split, but instead we send a request to new region. The tests fails when followers send heartbeat responses to leader and the responses arrived after leader sent a new appned to followers. They cause leader sends a new append to followers and advances theirs committed index. 
To stable the test, we should use a large hearbeat timeout and use "k6" instead of "k0".
https://github.com/tikv/tikv/blob/7c8ed8fcdbbf91d81b5e7836cbac959b2fb229ec/tests/raftstore_cases/test_split_region.rs#L327-L335
Unit tests.
No.
No.
Close #3669
=> tests: stable test_delay_split_region

Cargo.lock, benches/misc/mod.rs, benches/raftstore/mod.rs, components/test_util/Cargo.toml, components/test_util/src/kv_generator.rs, components/test_util/src/lib.rs
This PR provides `with_seed` for `KvGenerator` so that it is possible to generate a reproduceable and stable KV pairs. It can eliminate performance jitters in benchmarks.
Extracted from https://github.com/tikv/tikv/pull/3477, also seems to be useful in https://github.com/tikv/tikv/pull/3787.
=> Provide seeded KV generator

src/raftstore/store/fsm/peer.rs
This PR fixes the problem which may send redundant heartbeat to PD. If a peer is the leader, it will call `heartbeat_pd`, which will put the pending peer into `peers_start_pending_time`. And if the `ConfChangeType` is `AddLearnerNode`, it will be pushed again. So it might send two heartbeats to PD at the same time. 
manual tests
=> raftstore: fix redundant heartbeat

src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
Implement builtin function: week_day and week_of_year
- Improvement 
unit test
no
no
[#3275](https://github.com/tikv/tikv/issues/3275)
=> Copr: Add week_day and week_of_year

Cargo.lock, Cargo.toml, src/coprocessor/codec/error.rs, src/coprocessor/dag/expr/builtin_encryption.rs, src/coprocessor/dag/expr/scalar_function.rs, src/lib.rs
implement builtin encryption functions: Compress, Uncompress, UncompressedLength
Improvement
unit test
No
No
#3275
=> implement compress,uncompress,uncompressed_length

Cargo.lock, Cargo.toml, components/test_raftstore/src/pd.rs, src/lib.rs, src/util/collections.rs
According to [hashbrow](https://github.com/Amanieu/hashbrown)'s own description, it around 2x faster than FxHashMap and 8x faster than the standard HashMap. 
Actually, after replacing FxHashMap with it, we get a 0.1% ~ 5% faster TiKV.
unit test
No
No
YCSB test:
```
hashbrown: tikv.type = txn, thread count = 64
INSERT - Takes(s): 495.8, Count: 10000000, OPS: 20169.9, Avg(us): 3117, Min(us): 819, Max(us): 69614, 95th(us): 5000, 99th(us): 18000
hashmap: tikv.type = txn, thread count = 64
INSERT - Takes(s): 496.7, Count: 9999983, OPS: 20133.9, Avg(us): 3124, Min(us): 782, Max(us): 62549, 95th(us): 5000, 99th(us): 18000
hashbrown: tikv.type = txn, thread count = 256 …
```
=> *: replace FxHashMap with Hashbrown

Cargo.lock, Cargo.toml, benches/misc/channel/bench_channel.rs, benches/misc/mod.rs, src/lib.rs, src/util/mpsc.rs, src/util/worker/mod.rs
- remove future support to make performance better
- add half close support
- add several useful APIs
Previous:
```
test channel::bench_channel::bench_crossbeam_channel                  ... bench:          24 ns/iter (+/- 0)
test channel::bench_channel::bench_util_channel                       ... bench:          75 ns/iter (+/- 1)
test channel::bench_channel::bench_util_loose                         ... bench:          90 ns/iter (+/- 5)
```
After:
```
test channel::bench_channel::bench_crossbeam_channel                  ... bench:          27 ns/iter (+/- 0)
test channel::bench_channel::bench_util_channel                       ... bench:          27 ns/iter (+/- 0)
test channel::bench_channel::bench_util_loose                         ... bench:          76 ns/iter (+/- 1)
```
=> util/mpsc: refactor channel

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
Summarize your change (mandatory)
1 I write a builtin function concat_ws(line 82) in builtin_string.rs.
2 And i change builtin_string.rs and scalar_function.rs
3 I write a test in builtin_string.rs(line 937), it works!
Please NOTE that:
This is the first time i try to become a contributor, so please forgiven me if the change is not perfect.
=> Copr: add builtin function "concat_ws"

src/server/service/kv.rs
Cherry-pick https://github.com/tikv/tikv/pull/3891 to release-2.1 branch.
=> [release 2.1] cherry pick: When tikv is closing, should return retryable error to tidb

src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/dag/executor/selection.rs, src/coprocessor/dag/expr/builtin_arithmetic.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/builtin_compare.rs, src/coprocessor/dag/expr/builtin_control.rs, src/coprocessor/dag/expr/builtin_encryption.rs, src/coprocessor/dag/expr/builtin_json.rs, src/coprocessor/dag/expr/builtin_like.rs, src/coprocessor/dag/expr/builtin_miscellaneous.rs, src/coprocessor/dag/expr/builtin_op.rs, src/coprocessor/dag/expr/builtin_other.rs, src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/column.rs, src/coprocessor/dag/expr/constant.rs, src/coprocessor/dag/expr/mod.rs
Some `&mut` are not necessary, this PR substitute them with `&`.
Extracted from https://github.com/tikv/tikv/pull/3898
=> Remove unnecessary &mut in Coprocessor

Cargo.lock, components/cop_datatype/Cargo.toml, components/cop_datatype/src/def/eval_type.rs, components/cop_datatype/src/error.rs, components/cop_datatype/src/lib.rs
This PR substitute quick-error with [Failure](https://github.com/rust-lang-nursery/failure) in cop_datatype, for better error management.
=> Use failure for cop_datatype

components/test_raftstore/transport_simulate.rs, src/pd/pd.rs, src/raftstore/store/fsm/peer.rs, tests/failpoints_cases/test_merge.rs, tests/raftstore_cases/test_snap.rs
cherry pick #3873 
unit-test
No
No
=> raftstore: do not update pending_cross_snap when peer is applying snapshot (#3873)

src/storage/mod.rs, src/storage/txn/process.rs
`ProcessResult::MultiKvpairs`, `ProcessResult::Value`,
`StorageCb::SingleValue` and `StorageCb::KvPairs` are no longer
constructed since https://github.com/tikv/tikv/pull/2713
Unit tests.
No.
No.
=> storage: remove unused variants

Cargo.lock, Cargo.toml, src/bin/tikv-ctl.rs, src/bin/util/profiling.rs, src/lib.rs, src/util/jemalloc.rs
This upgrades jemallocator to the latest published version, changes the code to use the stable allocator API, makes the `mem-profiling` build compile, and updates the codebase to continue working with libfuzzer.
This is part of [upgrading to Rust 2018](https://github.com/tikv/tikv/pull/3952). I've pulled out only the jemalloc changes to try to land them alone, make sure everything continues to work.
Things to note:
- This upgrades to the latest published jemallocator, away from @BusyJay's fork. I suspect that the fixes in BusyJay's fork are incorporated into the latest jemallocator, but don't know for sure.
- jemalloc is used on all Unixes, and nowhere else.
- jemalloc is configured to not prefix its symbols, such that on supported platforms it replaces libc malloc, letting RocksDB and …
=> Upgrade jemalloc, fix mem-profiling build

src/raftstore/store/fsm/router.rs
Because CountScheduler is used as both NormalScheduler and ControlScheduler, so it will be shutdown twice, which can lead to panic occasionally.
Close #3959.
Signed-off-by: Jay Lee <busyjaylee@gmail.com>
=> raftstore/router: stable test

src/coprocessor/dag/expr/builtin_arithmetic.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/builtin_compare.rs, src/coprocessor/dag/expr/builtin_math.rs, src/coprocessor/dag/expr/builtin_op.rs, src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/mod.rs
add an inline helper method `is_unsigned` to `Expression` for convenience. 
although there're other flags, since this is used in so many places, so I think it's can be a start to hide more 'cop_datatype' details for this layer.
Improvement
unit test
No
No
#3803
=> add is_unsigned to Expression

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
1. implement builtin string function `left_binary` and `right_binary`
2. fix the existed `left` and `right` function's length overflow issue
Improvement
Unit Test
No
No
#3275
=> implement builtin string function left_binary and right_binary

src/coprocessor/codec/mysql/time/extension.rs, src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
implement builtin function: ToDays in coprocessor.
[#3275](https://github.com/tikv/tikv/issues/3275)
Improvement
Unit Test
No
No
=> coprocessor/dag/expr: add to_days

src/util/file_log.rs
The original method named `close()`, however,  it doesn't close the file immediately at all.
According to @brson  said: 
> The `rotate` method is renaming a file while holding a file handle to it, which may or may not be ok, but e.g. doesn't generally work on windows.
```rust
fn rotate(&mut self) -> io::Result<()> {
self.close()?;
let new_path = rotation_file_path_with_timestamp(&self.file_path, &Utc::now());
fs::rename(&self.file_path, &new_path)?;
self.update_rotation_time();
self.open()
}
```
So I close the log file explicityly here.
cargo test
No
No
=> util/file_log: close the log file explicitly

components/test_util/src/lib.rs, src/bin/tikv-importer.rs, src/bin/tikv-server.rs, src/util/logger/mod.rs, src/util/mod.rs
Dropping the logger guard replaces the original logger with the `NoGlobalLogger` which panics when we continue log something. So it causes panic in panic and tirggers the `ud2` trap.
This PR replaces the old logger with a terminal logger to avoid panic in panic.
Manual test.
No.
No.
Merge #3987 first.
=> *: install a new logger when panic to avoid no global logger

src/raftstore/store/util.rs, src/util/rocksdb/properties.rs
Suppose that there is a range where no data locates, but if there is a lot of SST cover this range, it may cause an inaccurate approximate size or keys.
So change the way of calculating the approximate distance, use the last index handle before end key instead of the first index handle after end key.
unit-test
No
No
=> util: change the way of calculating the approximate distance

src/raftstore/coprocessor/region_info_accessor.rs
In raftstore `Peer::replicate`, the epoch is initialized with 0 before getting the real epoch. Then in some cases, region_info_accessor may got two overlapping regions, both of which has version 0. So the assertion "Two overlapping regions with different ids must have different versions" fails in this case.
The region information with version `0` is invalid and useless. So in order to fix this panic, we can simply ignore messages with version 0. The region will be created later when the region's epoch is properly set and an Update message was sent.
- Unit test.
No
No
=> raftstore/region_info_accessor: Fix the panic when got overlapping regions with version 0

src/storage/mvcc/txn.rs, src/storage/types.rs
Update the log format and the key format according to the RFCs.
Check the document for how the format work: https://docs.rs/slog/2.0.0-3.1/slog/macro.log.html#values-implementing-fmtdisplay
Unit test
No
No
https://github.com/tikv/rfcs/blob/master/text/2018-12-19-unified-log-format.md
https://github.com/tikv/rfcs/blob/master/text/2018-11-12-unified-key-format.md
=> mvcc/txn: use structured log format and hex key format

Cargo.lock, Cargo.toml, components/test_raftstore/Cargo.toml, src/bin/tikv-ctl.rs, src/bin/tikv-importer.rs, src/bin/tikv-server.rs, src/lib.rs, src/util/logger/mod.rs
We use slog-stdlog to redirect log from the log crate to slog. However, slog-stdlog uses slog-scope internally, while we use slog-global. As a result, 3rd-party logs are just discarded.
This PR fixes it by redirecting log to slog-global.
The corresponding change in slog-global is https://github.com/breeswish/slog-global/pull/1/files which essentially is the same to slog-stdlog but replaced slog-scope with slog-global.
Manually.
=> Redirect 3rd-party's stdlog

src/util/logger/mod.rs
Fix grpc log redirection, `grpc::redirect_log` does not redirect log if the log level does not set. 
Manual testing
No.
No.
=> util/logger: fix grpc log redirection

components/test_util/src/lib.rs, src/bin/tikv-ctl.rs, src/bin/tikv-importer.rs, src/bin/tikv-server.rs, src/bin/util/setup.rs, src/util/mod.rs
Switch grpc event engine from epollsig to epollex, because epollsig is no longer supported in gRPC 1.17.x.
Uint testing
No.
Yes, we must make sure the linux kernel support the epoll `EPOLLEXCLUSIVE` flag.
#4023
=> *: switch grpc event engine from epollsig to epollex

Cargo.lock
Upgrade grpcio to v0.4.2 which uses the gRPC core library v1.17.2.
Integration tests
No.
No.
=> Cargo: upgrade grpcio to v0.4.2

src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/json/json_cast.rs, src/coprocessor/dag/executor/aggregate.rs, src/coprocessor/dag/expr/builtin_cast.rs
This PR cherry-pick #3253 to release-2.0.
This PR adjust the sum operation for aggregate functions(make it keep compatible with TiDB's `calculateSum` function.).
unit test
no
no
The related source in tidb:https://github.com/pingcap/tidb/blob/master/expression/aggregation/util.go#L57
@breeswish @zz-jason PTAL
=> executor/aggregate:adjust sum for aggregate functions (#3253)

src/coprocessor/codec/mysql/time/mod.rs, src/coprocessor/dag/expr/builtin_time.rs, src/coprocessor/dag/expr/scalar_function.rs
Signed-off-by: AndreMouche <AndreMouche@126.com>
This PR cherry-pick #3774 to release-2.1:
1. fix bug in date_format
2. add functions day_name, day_of_month, day_of_week, day_of_year
yes
no
no
@breeswish @DorianZheng PTAL
=> coprocessor:cherry-pick #3774

components/test_util/src/lib.rs
This PR fixes the error which appears on macOS when runs `make test`,
```
E0117 15:57:03.064976000 123145333387264 ev_posix.cc:227]              No event engine could be initialized from epollex
```
by canceling setting `GRPC_POLL_STRATEGY=epollex` to the environment.
manual test.
No
No
=> test: fix epollex error on macOS

src/raftstore/coprocessor/metrics.rs, src/raftstore/coprocessor/region_info_accessor.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/metrics.rs, src/raftstore/store/worker/read.rs
After adding threaded raftstore, it is hard to collect the leader count in raftstore. So record this metrics in `region_info_accessor` which has a global view of all the regions of this store.
manual-test
No
https://github.com/pingcap/tidb-ansible/pull/668
=> raftstore: adjust leader metircs

Cargo.toml, src/lib.rs
Fix complie error on non-Linux by disable the procinfo crate.
Manually, maybe we should test macOS build on CircleCI?
No.
No.
Close #4130.
=> Cargo: disable procinfo on non-Linux

etc/config-template.toml, src/config.rs
There two benefits:
1. Save more versions for debugging when necessary.
2. Avoid rewritting the whole manifest file frequently.
However, a larger manifest file needs more time to recover.
According to test, a 128MB manifest file takes about 4s to recover.
More information about the manifest file: https://github.com/facebook/rocksdb/wiki/MANIFEST
Unit test
No
No
=> config: enlarge max-manifest-file-size to 128MB

tests/integrations/raftstore/test_snap.rs
Stabilize a test case. It was not stable because we do some useless write to raft so that there maybe more new snapshots, so that the assert about no more snapshots fails.
Improvement.
Unit tests.
No.
No.
Close #4127 .
=> test: stabilize test_server_snap_gc

components/test_raftstore/src/pd.rs
the test is failed because the heartbeat of the other region generated from split may not received in time.
```
test raftstore::test_split_region::test_node_half_split_region ... thread 'raftstore::test_split_region::test_node_half_split_region' panicked at 'called `Result::unwrap()` on an `Err` value: Other(StringError("[components/test_raftstore/src/pd.rs:982]: no region contains key \"\""))', src/libcore/result.rs:1009:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
1: std::sys_common::backtrace::_print
at src/libstd/sys_common/backtrace.rs:71
2: std::panicking::default_hook::{{closure}}
at …
```
=> test: fix no region contains key error

src/bin/tikv-importer.rs, src/bin/tikv-server.rs, src/bin/util/mod.rs, src/bin/util/setup.rs, src/config.rs, src/server/config.rs
This makes a run of 'tikv-sever' with no args look like
```
ubuntu@ip-172-30-0-238:~/tikv2$ cargo run --bin tikv-server --
Finished dev [unoptimized + debuginfo] target(s) in 0.28s
Running `target/debug/tikv-server`
[2019/02/01 21:54:14.575 +00:00] [INFO] [mod.rs:25] ["Welcome to TiKV."]
[2019/02/01 21:54:14.575 +00:00] [INFO] [mod.rs:27] []
[2019/02/01 21:54:14.575 +00:00] [INFO] [mod.rs:27] ["Release Version:   3.0.0-beta"]
[2019/02/01 21:54:14.575 +00:00] [INFO] [mod.rs:27] ["Git Commit Hash:   Unknown (env var does not exist when building)"]
[2019/02/01 21:54:14.576 +00:00] [INFO] [mod.rs:27] ["Git Commit Branch: Unknown (env var does not exist when building)"]
[2019/02/01 21:54:14.576 +00:00] [INFO] [mod.rs:27] ["UTC Build Time:    Unknown (env var does not exist when building)"] …
```
=> tikv/src/bin: clean up early errors and logging

Cargo.lock, Cargo.toml, components/test_raftstore/Cargo.toml, src/util/jemalloc.rs, src/util/rocksdb/event_listener.rs
Check status of CompactionJobInfo at first.
- Bug fix 
CI
No
No
=> [cherry-pick-2.1] Fix event listener issue

src/coprocessor/codec/mysql/duration.rs, src/coprocessor/codec/mysql/time/mod.rs, src/coprocessor/dag/expr/builtin_time.rs
Add `checked_add` and `checked_sub` for Mysql Time and Duration.
Like:
- `Time.checked_add(Duration)`
- `Time.checked_sub(Duration)`
- `Duration.checked_add(Duration)`
- `Duration.checked_sub(Duration)`
unit test
no
no
#4097
=> Copr: Implement checked_add and checked_sub for Mysql Time and Duration

src/lib.rs, src/server/server.rs, src/util/mod.rs
This PR make TiKV only listens to given port when it's started. Note that listening to port before everything is prepared is a mistake and can lead to unexpected bugs like #4224.
Binding port before server is started is required by our tests to avoid port conflict. So this PR delays binding port only when it's configured.
manual tests
No.
No.
Close #2999
Close #4224
=> server: bind port lazily when it's configured

tests/failpoints/cases/test_stale_read.rs
Stable test_stale_read_during_merging by sleep an election timeout, so The new leader needs enough time to gether all followers progress, in cause the merge request is reject by log gap too large (min_progress == 0).
Unit tests.
No.
No.
Fixes #4246
=> tests: stable test_stale_read_during_merging

src/bin/tikv-server.rs, src/config.rs, src/raftstore/store/region_snapshot.rs, src/util/mod.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-custom.toml
Previously TiKV will panic when encounter key exceed bound error, add a configuration to control panic or return error in this condition.
Unit test
No
No
=> Add option to decide panic or not when key exceed bound

Cargo.lock, components/log_wrappers/Cargo.toml, components/log_wrappers/src/lib.rs, etc/check-bins-for-jemalloc.sh
This fixes the error generated by check-bins-for-jemalloc.sh
I also added more info to the error message in the script,
indicating how to fix the problem.
Fixes https://github.com/tikv/tikv/issues/4220
=> log_wrappers: add tikv_alloc dep

src/bin/tikv-server.rs, src/bin/util/setup.rs
In the local test, if you want to specify the address of pushgateway, you can only manually create a config file, which is not very convenient. By adding this parameter, you can specify it directly on the command line. This behavior is also consistent with tidb-server and pd-server
Signed-off-by: dongxu <huang@pingcap.com>
=> config: add metrics pushgateway addr parameter

Makefile
Add an audit command as part of #4264 .
Test by running `make audit`, regardless of a `cargo-audit` version being installed. It will install (or update to) the latest, then run audit.
A follow up PR will add this to our CI builds in the SRE repo.
```rust
make audit
```
You can test with or without cargo-audit installed.
=> Add make audit

src/coprocessor/codec/data_type/mod.rs, src/coprocessor/codec/data_type/vector_like.rs
This PR adds VectorLike, which is an enum for vector and scalar that supports index access. When underlying is a scalar, any index access will return the same value. When underlying is a vector, index access will return the corresponding element of the vector. Simply speaking, this provides a unified type for "vector like" types which will act like a vector.
This is extracted from https://github.com/tikv/tikv/pull/3898
=> Introduce VectorLike

src/coprocessor/dag/expr/builtin_string.rs, src/coprocessor/dag/expr/scalar_function.rs
Signed-off-by: TigerInYourDreams <TigerInYourDream@hi.zy>
Implement the function instr_binary which I found in #3275 
Add instr_binary function. 
Add function。
Unit Test。
No.
No
=> implement builtin_string/instr_binary

src/coprocessor/codec/convert.rs, src/coprocessor/codec/data_type/mod.rs, src/coprocessor/codec/data_type/scalar.rs, src/coprocessor/codec/data_type/vector.rs, src/coprocessor/codec/data_type/vector_like.rs, src/coprocessor/codec/mysql/decimal.rs, src/coprocessor/codec/mysql/duration.rs, src/coprocessor/codec/mysql/json/mod.rs, src/coprocessor/codec/mysql/time/mod.rs
AsMySQLBool is a newly added trait that provides interface "as_mysql_bool" for different data types. For selection, we need predicates which is bools from arbitrary data types. This is where AsMySQLBool will be used.
This PR also carries some other data structures needed by vectorization framework, like `Evaluable`.
This is extracted from #3898.
=> Implements AsMySQLBool

etc/tikv-importer.toml, src/import/config.rs
This makes the SST size to upload larger, which reduces the number of SST
files needed to ingested, and improve overall speed.
Tested manually using a data set with size 6.5 TB
No (config for importer isn't documented in this repo 🤔)
Yes (will be filed separately, together with Lightning changes)
Part 1/7 split off from #4245
=> import: increase default region-split-size to 512 MiB

src/import/engine.rs
Before this PR, the block size is very large, causing too much memory to be consumed for each iterator. The approximate size was 1 MB × number of files in L0 (829 for a 703 GB engine file) × number of import jobs (32).
This PR removes the block size setting to reduce the memory usage.
Tested manually using a data set with size 6.5 TB
No
No
Part 5/7 split off from #4245.
=> import: fix #4257, restrict memory usage by RocksDB

Cargo.lock, components/tikv_alloc/Cargo.toml, components/tikv_alloc/src/lib.rs, src/bin/util/setup.rs, src/util/metrics/jemalloc_metrics.rs, src/util/metrics/mod.rs
Exporting 6 jemalloc stats to prometheus. Details of these counters can be found in http://jemalloc.net/jemalloc.3.html (search for, e.g. "stats.allocated"). Rough meaning of them are:
* allocated: how much memory user code (the whole tikv in this case) requested.
* active: how much jemalloc allocated to satisfy the allocation requests (because jemalloc has size classes, e.g. user request for 3.9k memory, and the closest size class is 4k, so jemalloc end up allocate 4k).
* metadata: extra usage by jemalloc itself, e.g. to keep track of allocation size of each item
* resident: close to actual memory used by jemalloc.
These counters should be useful to monitor jemalloc memory fragmentation ratio.
Improvement
Run the code in IDC.
Grafana snapshot:
Not sure if we document exported metrics. …
=> Export jemalloc stats to prometheus

etc/tikv-importer.toml, src/import/client.rs, src/import/config.rs, src/import/engine.rs, src/import/prepare.rs, src/import/test_helpers.rs
Cherry-picks the following 4 PRs for 2.1.6 release:
* #4347 (increase default region-split-size to 512 MiB)
* #4348 (store intermediate SST files on disk instead of memory)
* #4350 (restrict memory usage by RocksDB)
* #4352 (wait after split before scatter)
Tested manually using a data set with size 6.5 TB
No
Yes (will be filed separately, together with Lightning changes)
See above
=> Cherry-pick 4 PRs related to tikv-importer to release-2.1

fuzz/targets/mod.rs, src/coprocessor/codec/batch/lazy_column.rs, src/coprocessor/codec/batch/lazy_column_vec.rs, src/coprocessor/codec/data_type/vector.rs, src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/time/mod.rs, src/coprocessor/codec/mysql/time/tz.rs, src/coprocessor/codec/table.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/builtin_compare.rs, src/coprocessor/dag/expr/ctx.rs, src/coprocessor/dag/expr/mod.rs
Fix issue: https://github.com/tikv/tikv/issues/4341
plenty of functions read `Tz` and use it to construct a correct `Time` by copying them so does `EvalConfig`. No need to copy, just take ownership or use references. But using reference is hard now...
There are too many signatures to modify and it is likely to break lots of API.
reduce the number of `Tz` copy in the stack.
`make test` already.
=> remove unnecessary Copy trait of Tz and EvalConfig

Makefile, etc/check-sse4_2.sh
Check sse4.2 only in the release build, so that `make dev` does not require gdb.
#4330 #4314
=> Makefile: check sse4.2 only in release

src/import/import.rs, src/import/metrics.rs
Jobs are now processed dynamically using a channel instead of predestined,
to prevent a single slow thread blocking the entire process. 
This implement the preemptive concurrency mode.
<details><summary>Before this PR</summary>
parallel for each range of ranges {
create sst channel
create import threads
parallel for each thread of import threads do {
recv sst from sst channel
upload sst
ingest sst
}
loop {
open SSTStreamFile
for each sst from stream {
send sst to sst channel
}
}
}
</details>
<details><summary>After this PR</summary>
create dispatch range channel
create dispatch thread do {
for each range of ranges {
send range to range channel
}
}
create sst channel
create split threads
parallel for each thread of split threads do {
recv range from …
=> import: refactor concurrency mode

src/coprocessor/endpoint.rs
This PR disable batch executor since it is not ready.
@breeswish @rleungx PTAL
=> coprocessor/endpoint:disable batch executor since it is not ready

src/coprocessor/dag/batch_executor/table_scan_executor.rs, src/coprocessor/endpoint.rs
This PR reverts our optimization in the batch table scan executor for default values, because we cannot identify invalid requests actually. For NOT NULL columns created by CREATE TABLE statement, they don't have default values. So when we got a NOT NULL column without default value, it is valid. We should return error only when we additionally indeed got missing data.
CI
=> Fix incorrect default value handling in batch table scan executor

src/raftstore/coprocessor/mod.rs, src/raftstore/coprocessor/region_info_accessor.rs, src/raftstore/store/mod.rs, src/raftstore/store/msg.rs, src/storage/engine/mod.rs, src/storage/gc_worker.rs, tests/integrations/storage/test_seek_region.rs
Seek region required two callbacks and returned an additional result to indicate whether it exceeded the limit or reached the end. It's too complicated and limited. This PR makes it accept an arbitrary closure so that users can do whatever they want without touching RegionInfoAccessor.
- Improvement
unit tests.
No.
No.
=> *: simplify seek region interface

src/bin/util/setup.rs
This clears the slog_global logger before exiting. It should prevent the
process from exiting prior logs all being flushed.
Related to #3387, #4328, #4358
=> Allow logger cleanup on fatal!()

scripts/run-cargo.sh
The -b backs up .cargo/config in case there is some custom config there.
-b doesn't work on macos though so just remove it. The risk of somebody
having their own config there, while also using these custom configs
is low.
=> scripts: Don't cp -b

components/codec/src/byte.rs, src/coprocessor/dag/handler.rs, src/coprocessor/dag/rpn_expr/function.rs, src/coprocessor/dag/rpn_expr/types/expr_builder.rs, src/coprocessor/dag/rpn_expr/types/expr_eval.rs
1. This PR removes those `#[inline(always)]` for the same reason as https://github.com/rust-lang/rust/pull/43367
2. This PR adds check of output offsets to avoid panic when given output offsets are invalid.
Both of the changes are extracted from https://github.com/tikv/tikv/pull/3898
=> Remove #[inline(always)] and check output offsets to avoid panic

src/coprocessor/codec/error.rs, src/coprocessor/error.rs
This PR makes error messages in Coprocessor more user friendly. More technically, prining as `Display` is enough, `Debug` is not necessary.
Before change:
TiDB output to MySQL clients:
```
ERROR 1105 (HY000): other error: unknown error StringError("[src/coprocessor/dag/executor/mod.rs:241]: unknown error StringError(\"[src/coprocessor/codec/mysql/time/mod.rs:104]: \\\'2019-0-0 0:0:0.000000000\\\' is not a valid datetime in specified time zone\")")
```
TiKV output to log:
```
[2019/04/04 17:56:14.780 +08:00] [ERROR] [endpoint.rs:470] [error-response] [err="unknown error StringError(\"[src/coprocessor/dag/executor/mod.rs:241]: unknown error StringError(\\\"[src/coprocessor/codec/mysql/time/mod.rs:104]: \\\\\\'2019-0-0 0:0:0.000000000\\\\\\' …
```
=> More friendly error messages in Coprocessor

src/coprocessor/endpoint.rs, src/server/config.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-custom.toml
Signed-off-by: Shirly <AndreMouche@126.com>
This PR makes `end-point-enable-batch-if-possible` configurable. However, This config will be removed once the batch computation is stable.
unit tests, integration tests, or manual tests
no, we don't want the users to know this config. 
and once the batch computation is ready, this config will be removed.
no
=> coprocessor:make end-point-enable-batch-if-possible configurable

src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs
=> no need to use region peers

.github/ISSUE_TEMPLATE/bug-report.md
The bug report issue template asked for the version of rustc 🙄. I think it  really means the version of TiKV instead.
No code.
No
No
=> .github: ask for the TiKV instead of rustc version in bug-report template

components/engine/src/util.rs, tests/integrations/raftstore/test_single.rs
Delete range as a kv pair is passed to prefix extractor which causes panic, because the key is less than 8 bytes.
This is a temporary workaround, the long term plan is skipping the prefix extractor for delete range in RocksDB side.
Unit tests.
No.
No.
#4461
=> engine: fix prefix extractor panic when delete range

src/coprocessor/dag/batch/executors/index_scan_executor.rs, src/coprocessor/dag/batch/executors/table_scan_executor.rs, src/coprocessor/dag/batch/executors/util/scan_executor.rs, src/coprocessor/dag/builder.rs, src/coprocessor/dag/handler.rs
We have some really complicated checking logic in aggregation executors, so it is no longer suitable to put them together in one function. This PR moves them back to places near the executor itself. This makes it more cohesive.
Additionally, this PR also changes the checking logic from returning a bool to returning a Result, so that the reasons that batch cannot be used can be outputted by simply return the Error.
Extracted from #3898
=>  Move the logic of checking the availability of batch execution to the executor

components/engine/src/rocks/util/mod.rs
Adding test to make sure region snapshot still works after enabling Titan engine.
Context: When enabled, Titan engine adds a wrapper `TitanTableFactory` around `BlockBasedTableFactory`. When generating region snapshot, TiKV needs to use the original `BlockBasedTableFactory` to generate SST file instead of generating blob files. Before https://github.com/pingcap/rocksdb/pull/89, `SstFileWriter` will obtain table factory through `DBOptions::original_table_factory`. After that patch, the original table factory is returned through `GetOptions()` and TiKV can pass the options struct back to `SstFileWriter`. 
engineering
Run the test, and run it after updating rocksdb to contain https://github.com/pingcap/rocksdb/pull/89
no
no
=> engine: add test for preparing SST ingestion from Titan

src/raftstore/store/peer.rs, tests/integrations/raftstore/test_merge.rs
Fix a bug about merge with learner, which is when we check the log gap in all replications, learners should also be considered, otherwise learners could panic.
close #4551 .
Bug fix.
Unit tests.
=> raftstore: learners should be considered when check progresses before merge

components/cop_datatype/src/def/field_type.rs, components/tikv_util/src/lib.rs, src/coprocessor/codec/data_type/scalar.rs, src/coprocessor/codec/data_type/vector.rs, src/coprocessor/dag/rpn_expr/function.rs, src/coprocessor/dag/rpn_expr/types/expr.rs, src/coprocessor/dag/rpn_expr/types/expr_builder.rs, src/coprocessor/dag/rpn_expr/types/expr_eval.rs
This PR extracts some engineering changes from https://github.com/tikv/tikv/pull/3898 where each of them is pretty small.
- Further simplify the building of `ColumnInfo` and `FieldType`.
- Simplify the building of `RpnExpression`.
- Add two additional RpnExpression tests:
- `test_eval_unary_function_raw_column`
- `test_eval_binary_function_raw_column`
- Implement `Clone` for `RpnFunction`
No.
=> Several trivial engineering improvements

src/import/engine.rs, src/import/import.rs
=> Cherry-pick: import: use memory to cache split sst instead of disk file (#4566)

src/coprocessor/dag/aggr_fn/impl_avg.rs, src/coprocessor/dag/batch/executors/index_scan_executor.rs, src/coprocessor/dag/batch/executors/limit.rs, src/coprocessor/dag/batch/executors/selection_executor.rs, src/coprocessor/dag/batch/executors/table_scan_executor.rs, src/coprocessor/dag/batch/executors/util/scan_executor.rs, src/coprocessor/dag/batch/interface.rs, src/coprocessor/dag/batch/statistics.rs, src/coprocessor/dag/builder.rs, src/coprocessor/dag/exec_summary.rs, src/coprocessor/dag/mod.rs
To use `ExecSummary` in normal executors, we need to move it out of `batch` directory.
Also, renamed functions, e.g. "on_start_batch" to "on_start_iterate", so that it is not limited to batch executors.
No need.
=> Rename and move ExecSummary to support non-batch executors

CHANGELOG.md, Cargo.lock, Cargo.toml, components/test_raftstore/Cargo.toml
Update raft to 0.4.2 to fix potential quorum changes when transferring leader.
- Bug fix
unit tests
Yes, CHANGELOG is updated.
No.
pingcap/raft-rs#221
=> update raft to 0.4.2

Cargo.lock, components/engine/src/rocks/mod.rs, components/test_raftstore/src/cluster.rs, components/test_raftstore/src/util.rs, etc/config-template.toml, src/bin/tikv-ctl.rs, src/bin/tikv-server.rs, src/config.rs, src/import/engine.rs, src/raftstore/store/peer_storage.rs, src/storage/config.rs, src/storage/kv/rocksdb_engine.rs, src/storage/mod.rs, tests/failpoints/cases/test_upgrade.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-cache-compatible.toml, tests/integrations/config/test-custom.toml
Add option to share block cache between column families. The goal is to simplify config. It may also improve cache performance if previous config fail to balance cache size well. A previous benchmark indeed show read throughput and latency increases in the specific test scenario (see benchmark result link).
The new config provide a flag to enable sharing block cache, and it is default true. Cache capacity is optional. If it is not provided, it is decided by 
* the sum of cache size of individual column families. and
* In the particular case when cache sizes for all column families are not set, the shared cache size is ~45% of total physical memory.
We also expose more block cache options through the new block cache config.
Config example:
```
[storage.block-cache]
shared = true
capacity = …
```
=> Share block cache among column families (#4563)

etc/tikv-importer.toml, src/import/engine.rs
The `zstd` is a CPU-tense compaction algorithm, which makes other workers have less chance to do some works. CPU will become the bottleneck of TiKV-Importer.
Change the compaction algorithm to `lz4` to make a balance between CPU and bandwidth.
11T test case, index engine file import throughput increase 250MB/s to 1GB/s in our 10G network card.
=> import: tune SstFileWriter options to reduce CPU usage

src/storage/mvcc/txn.rs
Use raw key in `Error::TxnLockNotFound` and use `into_raw()` to reduce copy.
unit tests, intergration tests
no
no
=> mvcc/txn: use raw_key in Error and reduce copy.

src/raftstore/store/fsm/peer.rs, src/raftstore/store/mod.rs, src/raftstore/store/msg.rs
Tick registry is used to avoid schedule a tick twice. It's very useful
when try to schedule tick lazily.
- New feature
unit tests
No.
No.
tikv/rfcs#23, tikv/tikv#4591
=> raftstore: add tick registry

src/coprocessor/dag/executor/metrics.rs, src/coprocessor/local_metrics.rs, src/coprocessor/metrics.rs, src/coprocessor/mod.rs, src/coprocessor/readpool_context.rs, src/coprocessor/tracker.rs
Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>
Add prio label to most coprocessor metrics
Add prior's label to most coprocessor metrics. tikv_coprocessor_outdated_request_wait_seconds and tikv_coprocessor_request_error requires more carefully reviews and therefore not changed at this time. 
unit tests and manual test
NO
NO
=> Add priority label to coprocessor metrics

src/coprocessor/codec/data_type/scalar.rs
Signed-off-by: H-ZeX <hzx20112012@gmail.com>
- in `coprocessors::codec::data_type::scalars::impl_as_ref::ScalarValue::$name`, the `stringify!($tt)`  may be changed to `stringify!($ty)`   
- test using this demo
```rust
macro_rules! my_macro_2 {
($ty: tt) => {
println!("{}", stringify!($ty));
println!("{}", stringify!($tt));
};
}
``` 
- use `rustc -Z unstable-options --pretty expanded scalar.rs > /tmp/3.rs` and analysis the expanded code
no 
no
=> the panic's param may be `$ty` but not `$tt`

benches/misc/raftkv/mod.rs, components/test_raftstore/src/server.rs, components/test_raftstore/src/transport_simulate.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/fsm/router.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/msg.rs, src/raftstore/store/peer.rs, src/server/raft_client.rs, src/server/server.rs, src/server/transport.rs, tests/integrations/server/raft_client.rs
Unreachable report is used to perform traffic control and potential down
node detection. This PR adds more unreachable report by hooking the
connection state and send error in raftstore layer. These can also be
useful when implementing hibernate regions as peers can be woken up when
failure is detected.
- Improvement
unit tests
No.
No.
=> *: report unreachable in more cases

etc/config-template.toml, src/config.rs, tests/integrations/config/test-default.toml
Increase raftdb max-background-job from 2 to 4 and max-sub-compactions from 1 to 2.
It helps to reduce write stall in high-pressure workload.
From raft RocksDB log we find only two threads are not enough, there is no worker to compact level 0 while others are busy with bottom level compaction and flush memtable. This leads to write-stall even if IO usage is not reaching 100%.
Unit tests.
No.
Yes.
=> config: increase raftdb max-background-job and max sub compactions

Cargo.lock, Cargo.toml, components/tipb_helper/Cargo.toml, components/tipb_helper/src/expr_def_builder.rs, components/tipb_helper/src/lib.rs
This PR introduce tipb_helper to build tipb structures more easily.
Extracted from https://github.com/tikv/tikv/pull/3898
No need.
=> Introduce tipb_helper

src/coprocessor/codec/batch/lazy_column.rs, src/coprocessor/codec/batch/lazy_column_vec.rs, src/coprocessor/codec/data_type/vector.rs, src/coprocessor/dag/batch/executors/index_scan_executor.rs, src/coprocessor/dag/batch/executors/limit_executor.rs, src/coprocessor/dag/batch/executors/mod.rs, src/coprocessor/dag/batch/executors/table_scan_executor.rs, src/coprocessor/dag/rpn_expr/types/expr_eval.rs
Thanks to some recent merged PRs, we can now just write `FieldTypeTp::Xxx.into()` in test codes where we want a `FieldType` 
This PR also renames limit.rs to limit_executor.rs to be more unified with others.
No need.
=> Simplify some code using field type converts

components/tikv_util/src/future.rs, components/tikv_util/src/lib.rs, components/tikv_util/src/threadpool.rs, src/coprocessor/dag/batch/executors/selection_executor.rs, src/coprocessor/endpoint.rs, src/coprocessor/mod.rs, src/lib.rs, src/raftstore/store/fsm/apply.rs, src/raftstore/store/fsm/batch.rs, src/raftstore/store/msg.rs, src/server/resolve.rs, src/server/snap.rs, src/storage/kv/mod.rs, src/storage/mod.rs
`FnBox` will never be stabilized. Instead, `Box<dyn FnOnce>` is available now, and is fully usable in 1.35. (https://github.com/rust-lang/rust/pull/59500)
So we can replace all FnBox occurrences with `FnOnce` now. Feature gate of fnbox can be removed as well.
Engineering
`make dev`
No
No
@kennytm
=> *: replace FnBox with FnOnce

components/engine/src/mutable.rs, components/engine/src/util.rs
Skip deleting range check on raftcf, because the encoding of keys in raftcf is different from others, and there is no such usage in TiKV.
No.
No.
No.
=> engine: skip check raft cf in delete range

components/test_raftstore/src/cluster.rs, src/storage/mod.rs, tests/failpoints/cases/test_snap.rs, tests/integrations/raftstore/test_conf_change.rs, tests/integrations/raftstore/test_split_region.rs
This PR changes noisy logs to trace from storage module and updates the
way to refresh leader in tests. The new method only counts quorum and is
expected to return early than before, which counts all the nodes.
- Engineering
unit tests
No.
No.
=> tests: tiny refactor

src/storage/gc_worker.rs
This PR is moved from #4485 , originally authored by @kolbe
The logs complaining about too many version is printed too frequently and is annoying. So move it to debug level.
No.
No.
No.
=> gc_worker: Change logs about plenty versions to debug level

src/coprocessor/codec/mysql/mod.rs
Add unit tests for `coprocessor::codec::mysql::parse_frac` to coverage all path
=> coprocessor: add unit tests to coverage `parse_frac` all path

src/coprocessor/dag/builder.rs, src/coprocessor/dag/executor/limit.rs, src/coprocessor/dag/executor/selection.rs
1. Support exec summary for `Selection` executor
2. Format `Limit` executor to keep the order of the methods in implementation the same as trait declare order.
Manually
Generate some rand data
```shell
tidiff 'create table selection(a bigint(10) not null auto_increment primary key, b varchar(20))'
tidiff '!! {{$count:=count 1000}} insert into selection (a, b) values {{range $index := $count}}(NULL, "{{varchar 20}}") {{if head $index $count}},{{end}} {{end}}'
```
```
TiDB(127.0.0.1:4000)> explain analyze select * from selection where b like "%a%" limit 10
+------------------------------------------------------------------ …
```
=> Support exec summary for Selection executor

src/coprocessor/dag/builder.rs, src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/dag/executor/mod.rs, src/coprocessor/dag/executor/table_scan.rs, src/coprocessor/dag/executor/topn.rs
Add support exec summary for TopN executor
Manually
Generate random data
```shell
tidiff 'create table topn(a bigint(10) not null auto_increment primary key, b varchar(20), c bigint(20))'
tififf '!! {{$count:=count 1000}} insert into topn (a, b, c) values {{range $index := $count}}(NULL, "{{varchar 20}}", {{int 1 1000}}) {{if head $index $count}},{{end}} {{end}}'
```
```
TiDB(127.0.0.1:4000)> explain analyze select * from topn where b like "%a%" order by c limit 10
+------------------------------------------------------------------------------------------------------------------------------------------------+
| id                       | count    | task | operator info                                                 | execution info …
```
=> coprocessor: add support exec summary for TopN executor

Cargo.lock, Cargo.toml
log 0.4 introduces non-static file path and module names. But it seems
to be a feature that most people don't use but break a lot of things.
This PR revert the lifetime back to static so that everything works
again.
Another approach is to update slog to support non-static module name and
file name. But it may lead to unnecessary clone and make things
complicated.
Know that this is just a workaround, we should switch back to crates io
version when slog is compatible with the latest log.
- Bug fix
manual tests
No.
No.
=> *: fix unknown file in log

src/coprocessor/dag/builder.rs, src/coprocessor/dag/executor/aggregation.rs
Add explain analyze support for Aggregation(HashAggregation/StreamAggregation) executor
Manually
- Generate random data
```shell
tidiff 'create table agg(a bigint(10) not null auto_increment primary key, b varchar(20), c bigint(20), key idx_c(c))'
tidiff '! {{$count:=count 1000}} insert into agg (a, b, c) values {{range $index := $count}}(NULL, "{{varchar 20}}", {{int 1 20}}) {{if head $index $count}},{{end}} {{end}}'
```
- StreamAgg
```
TiDB(127.0.0.1:4000)> explain analyze select avg(c) from agg group by c limit 10
+----------------------------------------------------------------------------------------------------------------------------------------+
| id                       | count  | task | …
```
=> coprocessor: add explain analyze support for Aggregation executor

components/test_raftstore/cluster.rs, src/raftstore/store/peer.rs, src/raftstore/store/worker/apply.rs, tests/failpoints_cases/test_merge.rs
There are two bugs of #4581 and #4560 in master which fixed by https://github.com/tikv/tikv/pull/4595. But release-2.1 doesn't suffer from #4581, and to make changes as less as possible, this PR just write tombstone state with writes in one batch when catching up logs for merge instead of catching up logs through raft.
unit-test
=> raftstore: write tombstone state with writes in one batch when catching up logs for merge [release-2.1]

components/test_coprocessor/src/fixture.rs, components/test_raftstore/src/server.rs, src/binutil/server.rs, src/coprocessor/endpoint.rs, src/coprocessor/readpool_impl.rs, src/server/node.rs, src/server/server.rs, src/storage/kv/mod.rs, src/storage/readpool_impl.rs, src/storage/txn/process.rs, src/storage/txn/sched_pool.rs, src/storage/txn/scheduler.rs
#4098 introduces a problem that pending transactions are woken up in apply threads, which causes performance drop. This PR changes the behavior. With the patch pending transactions will be woken up in scheduler workers.
Improvement.
Make dev.
We can see the second and the third results are almost same and better than the latest master.
=> storage: waking up pending transactions shouldn't be done in apply threads

Makefile, src/raftstore/store/fsm/store.rs, tests/failpoints/mod.rs
Currently, `make bench` will fail due to Criterion cannot recognize `--nocapture`. The way to fix this problem is to remove `--nocapture` or explicitly specify the bench target to decide whether it should use `--nocapture`. I'm not sure which way is better actually.
Also, this PR fixes some warning when running `make build` and `make test`.
Edit: 
According to the comments, I am going to remove this target.
- Bug fix
make build, make test
No.
No.
=> *: remove make bench target

src/coprocessor/dag/rpn_expr/impl_arithmetic.rs, src/coprocessor/dag/rpn_expr/mod.rs
This PR adds minus RPN functions for Int, Real, and Decimal. Code and tests are mainly adapted from `builtin_arithmetic.rs.`
- Improvement 
make dev
No.
No.
=> coprocessor: add minus(Int, Real, Decimal) RPN functions

benches/coprocessor_executors/mod.rs, src/coprocessor/dag/batch/executors/fast_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/index_scan_executor.rs, src/coprocessor/dag/batch/executors/limit_executor.rs, src/coprocessor/dag/batch/executors/selection_executor.rs, src/coprocessor/dag/batch/executors/simple_aggr_executor.rs, src/coprocessor/dag/batch/executors/slow_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/table_scan_executor.rs, src/coprocessor/dag/batch/executors/util/aggr_executor.rs, src/coprocessor/dag/batch/executors/util/scan_executor.rs, src/coprocessor/dag/batch/interface.rs, src/coprocessor/dag/builder.rs, src/coprocessor/dag/exec_summary.rs, src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/dag/executor/limit.rs, src/coprocessor/dag/executor/mod.rs, src/coprocessor/dag/executor/scan.rs, src/coprocessor/dag/executor/selection.rs, src/coprocessor/dag/executor/table_scan.rs, src/coprocessor/dag/executor/topn.rs, src/coprocessor/statistics/analyze.rs
Removed the `ExecSummaryCollector` field from *all* Executors and BatchExecutors. Instead, introduced a `WithSummaryCollector<C, T>` struct as a wrapper of the concrete executors, and implement the traits on it.
The main purpose is to factor out the repetition of the pattern `on_start_iterate() ... on_finish_iterate()`.
Note: Currently `WithSummaryCollector` will _always_ execute `summary_collector.collect_into()` inside `collect_statistics()`, but it was not always the case in the original implementation. I'm not sure if this is dedicated or just an oversight. We could add a flag to control this behavior if the omission is indeed dedicated.
```
cargo test -- …
```
=> coprocessor: move ExecSummaryCollector out of Executors into a wrapper struct

src/raftstore/store/fsm/peer.rs, src/raftstore/store/peer.rs, src/raftstore/store/worker/read.rs, tests/integrations/raftstore/test_lease_read.rs
LocalReader uses local caches for read delegates. After a region is destroyed in raftstore thread,  the local caches are not cleared correctly. This PR fix this.
Bug fix.
master：
the patch:
Almost same. So this PR won't introduce any performance drop.
=> raftstore: mark read delegate as invalid correctly

src/coprocessor/dag/batch/executors/fast_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/simple_aggr_executor.rs, src/coprocessor/dag/batch/executors/slow_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/util/aggr_executor.rs
This PR allows no aggr fn in the aggregation request.
This scenario happens for SQLs like:
```sql
SELECT 1 FROM t GROUP BY a
```
However, for simple aggregation executor it is still disallowed (since we now have no group bys as well as no aggregations).
=> cop: Support empty aggr fn in batch aggr executor

components/profiler/Cargo.toml, components/tikv_util/Cargo.toml
When crates don't turn off tikv_alloc's default features it forces jemalloc to be on.
profiler and tikv_util both set "default-features = false" for tikv_alloc. This allows the system profiler or tcmalloc to be used again.
SYSTEM_ALLOC=1 make
TCMALLOC=1 make 
various cargo invocations
no
no
https://github.com/tikv/tikv/issues/4769
=> *: turn off tikv_alloc's default features

components/cop_datatype/src/builder/field_type.rs, components/cop_datatype/src/def/field_type.rs, components/engine/src/rocks/util/config.rs, components/tikv_util/src/config.rs, components/tipb_helper/src/expr_def_builder.rs, src/coprocessor/codec/error.rs, src/coprocessor/codec/mysql/time/mod.rs, src/raftstore/errors.rs, src/server/debug.rs
Lots of code in `TiKV` implement `Into<SomeType>` for AnotherType but not `From<AnotherType>` for SomeType which will automatically implement `Into<SomeType>` and allow more explicitly construction.
=> Replace all `Into` with `From`

src/coprocessor/codec/batch/buffer_vec.rs, src/coprocessor/codec/batch/mod.rs
`BufferVec` is a data structure for efficiently holding multiple binary strings (like `Vec<Vec<u8>>`). Each binary string can be in different length.
`BufferVec` supports random read and sequential write. `BufferVec` does not support random write.
`BufferVec` will be used to support `LazyBatchColumn`, as well as `VectorValue::Bytes` in future may be.
New unit tests.
=> Adds BufferVec

src/coprocessor/dag/executor/aggregation.rs, src/coprocessor/dag/executor/index_scan.rs, src/coprocessor/dag/executor/limit.rs, src/coprocessor/dag/executor/mod.rs, src/coprocessor/dag/executor/selection.rs, src/coprocessor/dag/executor/table_scan.rs, src/coprocessor/dag/executor/topn.rs, src/coprocessor/statistics/analyze.rs
Returns error instead of panic when unexpected take origin
unit tests
=> coprocessor: returns error instead of panic when unexpected take origin

components/cop_datatype/src/def/mod.rs, src/coprocessor/dag/aggr_fn/impl_avg.rs, src/coprocessor/dag/aggr_fn/impl_count.rs, src/coprocessor/dag/aggr_fn/mod.rs, src/coprocessor/dag/aggr_fn/parser.rs, src/coprocessor/dag/aggr_fn/util.rs, src/coprocessor/dag/batch/executors/fast_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/simple_aggr_executor.rs, src/coprocessor/dag/batch/executors/util/aggr_executor.rs, src/coprocessor/dag/rpn_expr/impl_cast.rs, src/coprocessor/dag/rpn_expr/mod.rs, src/coprocessor/dag/rpn_expr/types/expr.rs
This PR adds supports of using all data types in AVG(), by half-implementing CAST functions necessary for these data types. 
Note: These implementations are not fully TiDB compatible. It is only ensured that the behaviour is not worse than existing cast behaviour in non-batch aggregation functions.
New unit tests.
=> coprocessor: Support all data types for AVG()

Cargo.lock, Cargo.toml, src/coprocessor/codec/batch/buffer_vec.rs, src/coprocessor/codec/batch/lazy_column.rs, src/coprocessor/codec/batch/lazy_column_vec.rs, src/coprocessor/codec/batch/mod.rs, src/coprocessor/codec/data_type/vector.rs, src/coprocessor/dag/batch/executors/fast_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/index_scan_executor.rs, src/coprocessor/dag/batch/executors/selection_executor.rs, src/coprocessor/dag/batch/executors/slow_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/table_scan_executor.rs, src/coprocessor/dag/rpn_expr/types/expr_eval.rs
This PR utilizes `BufferVec` in `LazyBatchColumn`, which was added in https://github.com/tikv/tikv/pull/4790 . Also some useless interfaces are removed.
It fixes the performance regression when there are large integers, as well as other cases where datum is small but larger than 10 bytes.
Existing tests.
=> coprocessor: Refine LazyBatchColumn to use BufferVec

src/raftstore/store/peer.rs
We have add a check about tranferring leader during configuration change in #4684 . However if the configuration change is not applied on the leader, new transferring leader proposal can pass the check. This PR makes the check can still work in this case.
Improvement.
make dev.
=> raftstore: more check about transferring leader during configuration change

src/coprocessor/dag/rpn_expr/impl_op.rs, src/coprocessor/dag/rpn_expr/mod.rs
This PR adds UnaryNot RPN function.
New unit test.
=> coprocessor: RPN function UnaryNot

scripts/check-sse4_2.sh
Signed-off-by: Kaige Ye <ye@kaige.org>
I got the same issue with https://github.com/tikv/tikv/issues/4330 when I run `make release`, and I found mine is also caused by missing `gdb`. The message generated by [`scripts/check-sse4_2.sh`](https://github.com/tikv/tikv/blob/3458a0eb46fae8a7f37dca86f4ae07c7911238a8/scripts/check-sse4_2.sh#L43) is **misleading** in this case, so it's better to check if gdb is installed first.
Make sure `gdb` is installed before SSE4.2 check.
Improvement
Manual tests finished
No
No
https://github.com/tikv/tikv/issues/4330
@overvenus PTAL
=> Makefile: make sure gdb is installed before sse4.2 check

components/tikv_util/src/lib.rs, src/coprocessor/codec/batch/lazy_column.rs, src/coprocessor/codec/batch/lazy_column_vec.rs, src/coprocessor/codec/data_type/scalar.rs, src/coprocessor/codec/data_type/vector.rs, src/coprocessor/dag/batch/executors/mod.rs, src/coprocessor/dag/batch/executors/stream_aggr_executor.rs, src/coprocessor/dag/batch/executors/top_n_executor.rs, src/coprocessor/dag/builder.rs, src/coprocessor/dag/rpn_expr/types/expr_eval.rs
This PR adds batch top N executor.
Unit test
=> Batch Top N Executor

src/coprocessor/dag/aggr_fn/impl_bit_op.rs, src/coprocessor/dag/aggr_fn/mod.rs, src/coprocessor/dag/aggr_fn/parser.rs, src/coprocessor/dag/aggr_fn/util.rs
Add batch aggregate function BitAnd/BitOr/BitXor. All related CAST functions don't contain in this PR.
- unit tests
=> coprocessor: add batch aggregate function BitAnd/BitOr/BitXor

src/coprocessor/dag/aggr_fn/impl_max_min.rs, src/coprocessor/dag/aggr_fn/mod.rs, src/coprocessor/dag/aggr_fn/parser.rs
This PR adds MAX/MIN aggregation functions for batch aggregation framework.
Unit tests
=> coprocessor: add batch aggregate function Max/Min

src/coprocessor/dag/rpn_expr/impl_arithmetic.rs, src/coprocessor/dag/rpn_expr/mod.rs
Implements RPN function MultiplyDecimal.
Required for TPC-H Q1, Q6, Q15.
New unit test.
=> Implement RpnFunction MultiplyDecimal

components/tikv_util/src/file.rs, src/raftstore/store/snap.rs
Signed-off-by: Ben Pig Chu <benpichu@gmail.com>
Fix #4846 by add some fsync calls in the snapshot module. Also add util used to call fsync by path
- Bug fix 
Unit test
No
No
=> Add missing fsync calls in the snapshot module

src/raftstore/store/snap.rs, src/util/file.rs
Signed-off-by: Ben Pig Chu <benpichu@gmail.com>
Cherry-pick #4850 to release-2.1, fix #4846 on 2.1.x branch by add some fsync calls in the snapshot module. Also add util used to call fsync by path.
- Bug fix
unit-test
No
No
=> Cherry-pick #4850 to release-2.1

Cargo.lock, Cargo.toml, src/coprocessor/dag/batch/executors/top_n_executor.rs
Replace `std::rc::Rc` in `BatchTopNExecutor` with `servo_arc::Arc`.
Because we don't need the weak count, it's ok to use `servo_arc::Arc`. This also saves one word in `HeapItemUnsafe`.
`servo_arc::Arc<T: Send>` is `Send`, so we don't need to worry about if `Rc`  may break the `Send` property of `BatchTopNExecutor`.
- Improvement
CI
No
No
Top N with lots of rows, few order-bys, few columns and small limit can maximize the impact of changing `Rc` to `Arc`. (Otherwise, evaluating columns or materialization can be the dominant part). Benchmark (run in an IDC machine) shows there's no significant performance impact.
```
top_n_1_order_by_1_column_limit_10/batch/rows=1000000 …
```
=> coprocessor: use servo_arc in BatchTopNExecutor

src/storage/lock_manager/deadlock.rs, src/storage/lock_manager/metrics.rs, src/storage/lock_manager/mod.rs, src/storage/lock_manager/waiter_manager.rs
Added metrics:
* `TASK_COUNTER_VEC`:   count tasks handled.
* ` ERROR_COUNTER_VEC`: count errors.
* ` WAITER_LIFETIME_HISTOGRAM`:  measure how long a waiter is waked up.
* ` DETECT_DURATION_HISTOGRAM`: measure how long detect requests cost, and it can reflect which node is the leader of deadlock detector.
manual test
no
yes. https://github.com/pingcap/tidb-ansible/pull/772
=> pessimistic-txn: add metrics

components/tikv_util/src/lib.rs, src/coprocessor/dag/batch/executors/slow_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/stream_aggr_executor.rs, src/coprocessor/dag/batch/executors/top_n_executor.rs, src/coprocessor/dag/batch/executors/util/aggr_executor.rs, src/coprocessor/dag/rpn_expr/types/expr_eval.rs
In this PR, slow hash aggregation uses a single `Vec` to store all encoded keys. Then, allocations are largely reduced.
`unsafe` is used in this PR. Please carefully review it.
Fix #4756 
Improvement (change which is an improvement to an existing feature)
make dev
No
No
```
hash_aggr_count_1_first_group_by_int_col_real_col/batch/rows=5000                                                                           
time:   [1.6607 ms 1.6980 ms 1.7284 ms]
change: [-19.420% -17.570% -15.802%] (p = 0.00 < 0.05)
Performance has improved.
hash_aggr_count_1_first_group_by_int_col_real_col_2_groups/batch/rows=5000                                                                           
time:   [690.97 us 695.09 us 699.15 us]
change: [-31.231% …
```
=> coprocessor: reduce allocations in slow hash aggregation

src/storage/mvcc/txn.rs
Resolve all optimistic locks when non-pessimistic lock conflict occurs.
manual tests
no
no
=> pessimistic-txn: resolve all optimistic locks when non-pessimistic lock conflict occurs

Dockerfile, Makefile, scripts/gen-dockerfile.sh
1. Add a new rule `build_release` to Makefile
2. Replace `RUN cargo build --no-default-features --release --features "jemalloc portable sse no-fail"` with `RUN make build_release` in script `scripts/gen-dockerfile.sh`  and execute the script to generate a new Dockerfile.
- Improvement
Run `docker build .` on my local MacOS.
No
No
[#4845](https://github.com/tikv/tikv/issues/4845)
=> Dockerfile use the Makefile to build tikv

Cargo.lock
Update vendor to support building on ARM64
Support ARM64 now
Manually
I use AWS ARM64 which doesn't support SSE and must use PORTABLE to build TiKV, the command is:
```
ROCKSDB_SYS_SSE=0 make release
```
No
No
=> support ARM64

src/raftstore/store/fsm/apply.rs, src/raftstore/store/peer.rs, src/raftstore/store/peer_storage.rs
Wait for the current commit index being applied before generating snapshots. It is useful in the request-snapshot scenario, followers always get the latest snapshot.
Unit tests.
No.
No.
=> raftstore: generate snapshot after applying the current commit idx

scripts/check-sse4_2.sh
The original way to check if sse4.2 is enabled is to load the binary
with gdb and then disassemble the symbol, this is slow because gdb is
a dynamic debugger. Replace gdb with objdump which analysis the static
code. It is 25x faster than the way of using gdb.
Another reason to replace gdb is that some versions of gdb can not
recognize the symbol correctly.
* replace gdb with `objdump`
* remove the output of $sym which is a mess of string. I think it is confused.
* output the check result with green color
manually test
- https://github.com/tikv/tikv/issues/4367
- …
=> improvement(scripts): check sse4.2 with objdump

Makefile, scripts/check-sse4_2.sh
Don't run check-sse4_2.sh when SSE4.2 optimizations are disabled.
Fixes https://github.com/tikv/tikv/issues/4900
Note that [encountered an unrelated bug](https://github.com/tikv/tikv/issues/4367#issuecomment-503332664) in this script during testing. cc @shafreeck 
Manual
No
No
Fixes https://github.com/tikv/tikv/issues/4900
Related to https://github.com/tikv/tikv/issues/4367#issuecomment-503332664
=> scripts: Skip sse4.2 check when not enabled

src/storage/gc_worker.rs, src/storage/metrics.rs
This PR cherry-picks PR #4705 which added more metrics for GC.
Manual test, previously tested in #4705
- No
NO
=> storage/gc_worker: Add more metrics (#4705)

CHANGELOG.md, Cargo.lock, components/engine/Cargo.toml
Update rocksdb to with the fix:
```
b4f33387f 2019-06-20 yiwu@pingcap.com     Fix ingested file and direcotry not being sync (#96)
```
Also point change rust-rocksdb to point to tikv-3.0 branch.
Bug fix & Engineering
CI
no
no
=> Update rust-rocksdb and change branch

components/cop_codegen/src/lib.rs, components/cop_codegen/src/rpn_function.rs
cop_codegen: replace 'parse + unwrap' with 'quote!'.
1. Highlight the code
2. Remove the unwrap
3. Fix broken unit test
Exists unit test.
=> cop_codegen: replace 'parse + unwrap' with 'quote!'

Cargo.lock, components/engine/src/iterable.rs, components/engine/src/util.rs, src/config.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-custom.toml
Cause DeleteFilesInRange may expose old blob index keys, setting key only for Titan to avoid referring to missing blob files.
unit-test by https://github.com/tikv/tikv/pull/4946
No
No
=> [release-3.0] engine: add titan key only option

src/coprocessor/dag/aggr_fn/parser.rs, src/coprocessor/dag/builder.rs, src/coprocessor/dag/rpn_expr/types/expr_builder.rs
Logs when batch execution cannot be utilized is not a big deal. This PR adjusts the level and the wording of batch execution log outputs, so that user will won't be worried when seeing these logs.
=> Don't make users worry about logs

src/config.rs, tests/integrations/config/mod.rs, tests/integrations/config/test-custom.toml
Currently titan is disabled for non-default CFs by setting min_blob_size=4GB. Changing to set blob_run_mode=ReadOnly which will disable titan even value size is >4GB (though it will never happen)
Improvement
Manually start tikv-server and check rocksdb log to set blob_run_mode is set.
no
no
=> Set blob_run_mode=ReadOnly for non-default CFs

components/cop_codegen/src/lib.rs, components/cop_codegen/src/rpn_function.rs, src/coprocessor/codec/data_type/mod.rs, src/coprocessor/codec/data_type/scalar.rs, src/coprocessor/codec/data_type/vector.rs, src/coprocessor/dag/aggr_fn/util.rs, src/coprocessor/dag/batch/executors/fast_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/selection_executor.rs, src/coprocessor/dag/batch/executors/simple_aggr_executor.rs, src/coprocessor/dag/batch/executors/slow_hash_aggr_executor.rs, src/coprocessor/dag/batch/executors/stream_aggr_executor.rs, src/coprocessor/dag/batch/executors/top_n_executor.rs, src/coprocessor/dag/batch/executors/util/hash_aggr_helper.rs, src/coprocessor/dag/batch/executors/util/mod.rs, src/coprocessor/dag/rpn_expr/function.rs, src/coprocessor/dag/rpn_expr/impl_arithmetic.rs, src/coprocessor/dag/rpn_expr/impl_cast.rs, src/coprocessor/dag/rpn_expr/impl_compare.rs, src/coprocessor/dag/rpn_expr/impl_control.rs, src/coprocessor/dag/rpn_expr/impl_like.rs, src/coprocessor/dag/rpn_expr/impl_op.rs, src/coprocessor/dag/rpn_expr/mod.rs, src/coprocessor/dag/rpn_expr/types/expr.rs, src/coprocessor/dag/rpn_expr/types/expr_builder.rs, src/coprocessor/dag/rpn_expr/types/expr_eval.rs, src/coprocessor/dag/rpn_expr/types/function.rs, src/coprocessor/dag/rpn_expr/types/mod.rs, src/coprocessor/dag/rpn_expr/types/test_util.rs
This PR adds vargs support to the RPN framework.
It also includes the implementation of `coalesce_xxx` as a demonstration of the vargs support.
New unit tests.
=> cop: Support variable number of arguments

Cargo.lock, src/server/service/kv.rs
Handle `BatchCommandsRequst::Empty`. This message is generally for tests, make us can focus on transport layer instead of backend logics.
- I suggeste to cherry pick it to release-3.0, so that we can do more tests for release-3.0.
=> service: handle BatchCommandsEmptyRequest

src/binutil/server.rs, src/server/status_server.rs
* Adds a `/config` endpoint to `StatusServer` that returns the `TiKvConfig` as json
* Adds a unit test that checks if a `StatusServer` created with a default `TiKvConfig` returns a json string that is the same as serializing a default `TiKvConfig` to a json string directly.
- Manual testing (`curl http://status.server.addr:20180/config`)
- Unit test
#4901
=> Adds /config endpoint to status server that returns the tikv config

Cargo.lock, Cargo.toml, components/test_raftstore/Cargo.toml
* Update rust-rocksdb to branch tikv-2.1.9-desc, which optimize memtable desc scan.
- Improvement 
It has been tested by **_inlineskiplist_test_** in **Rocksdb** repo.
- No
- No
=> optimize memtable desc scan

src/coprocessor/dag/rpn_expr/impl_compare.rs, src/coprocessor/dag/rpn_expr/mod.rs, src/coprocessor/dag/rpn_expr/types/test_util.rs
This PR implements RPN function `IN()`.
New unit tests.
=> cop: RPN function IN()

src/binutil/server.rs
Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>
Check max open files required by titan engine when it is enabled.
Add max open files required by titan engine when it is enabled  
Manually tested
No
No
NA
NA
NA
=> Check max required open files for titan

src/coprocessor/codec/convert.rs, src/coprocessor/codec/data_type/mod.rs, src/coprocessor/codec/datum.rs, src/coprocessor/dag/expr/builtin_cast.rs, src/coprocessor/dag/expr/ctx.rs
1. add functions to retrieve boundary of integer types.
2. add function `convert_*_to_int` and related tests.
3. `convert_json_to_int` directly use `Json::cast_as_int` which behavior is not correct. This will be fixed in the next PR.
Unit tests
=> coprocessor: refine the 'convert_*_to_int' functions

src/raftstore/store/fsm/apply.rs
Remove unnecessary clone.
The currently defined types are listed below, please pick one of the types for this
Existing unit tests.
=> raftstore/store: remove unnecessary clone

components/tikv_util/src/lib.rs
When calling exit() in panic_hook, it triggers global static to destroy, like c++ static dtors, which may cause other threads encounter `pure virtual method call`. So using `_exit` instead of `exit`.
=> tikv_util: call _exit instead of exit in panic hook

src/coprocessor/codec/mysql/duration.rs
There is different behavior in TiDB and Coprocessor when `Duration::parse` input string is empty.
Unit tests
=> coprocessor: fix `Duration::parse` while input is empty

src/storage/mvcc/reader/reader.rs
=> mvcc/reader: scan versions from u64::max to start_ts in get_txn… (#5062)

tests/failpoints/cases/test_merge.rs
test cases::test_merge::test_node_request_snapshot_reject_merge failed while running CI (see https://github.com/tikv/tikv/issues/5054).
I found it may be caused by the variable `notifier` https://github.com/tikv/tikv/blob/c3a8f2152164abe7c2285ee836d087146c7c9422/tests/failpoints/cases/test_merge.rs#L444-L451  sends a message after the variable `rx` was deconstructed. https://github.com/tikv/tikv/blob/c3a8f2152164abe7c2285ee836d087146c7c9422/tests/failpoints/cases/test_merge.rs#L454
Deconstructing `cluster` before the function returns could fix this problem.
=> fix test_node_request_snapshot_reject_merge

src/server/raft_client.rs, tests/integrations/server/raft_client.rs
Signed-off-by: zyh-hust <zhouyuanhui@pingcap.com>
Change error! to warn!.
When Raftclient fails to send a message, it will try again and should prompt warn instead of error.
CI
no
no
=> raftclient: warn instead of  error when send msg failed

src/storage/mvcc/mod.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/txn.rs
Signed-off-by: shirly <AndreMouche@126.com>
This PR removes the unused function `reverse_seek_write` and the related tests in `mvcc/reader/reader.rs`. 
It's in order to make the project more friendly to read.
yes, unit test
no
no
@MyonKeminta @youjiali1995  PTAL
=> mvcc/reader.rs:removes the function `reverse_seek_write`

src/raftstore/store/util.rs, src/util/rocksdb/properties.rs
Cherry-pick of #4017
unit-test
No
No
=> util: change the way of calculating the approximate distance (#4017)

src/storage/lock_manager/deadlock.rs
Optimize `detect`:
* If the path has existed, there is no need to check deadlock.
* Memorize the searching path to avoid duplicate search.
Unit tests
No
No
optimized:
original:
=> deadlock: improve the performance of detect

Cargo.lock
This is a commit for release v3.0.1 to update the cargo lock file which was
forgotten to update when bumping version.
=> build: update cargo lock file for v3.0.1

components/cop_datatype/src/def/field_type.rs, src/coprocessor/dag/rpn_expr/impl_cast.rs
Address the https://github.com/tikv/tikv/pull/5093#discussion_r303737693
=> coprocessor: move 'is_unsigned' to 'FieldTypeAccessor'

src/lib.rs, src/util/logger.rs
This PR cherry picks the unified log format formatter from 3.0 to 2.1.
Note: This PR does not introduce fields for log items.
Manually and unit tests:
```
$ target/debug/tikv-server
[2019/07/13 11:44:14.561 +08:00] [INFO] [mod.rs:26] ["Welcome to TiKV. \nRelease Version:   2.1.14\nGit Commit Hash:   Unknown (env var does not exist when building)\nGit Commit Branch: Unknown (env var does not exist when building)\nUTC Build Time:    Unknown (env var does not exist when building)\nRust Version:      Unknown (env var does not exist when building)"]
[2019/07/13 11:44:14.563 +08:00] [INFO] [config.rs:152] ["no advertise-addr is specified, fall back to addr."]
[2019/07/13 11:44:14.564 +08:00] …
```
=> [release-2.1] Unified Log Format

Cargo.lock, Cargo.toml, Makefile, components/tikv_util/Cargo.toml, components/tikv_util/src/lib.rs, src/lib.rs, src/raftstore/store/fsm/apply.rs, src/raftstore/store/fsm/store.rs, src/server/status_server.rs, src/server/transport.rs, src/storage/kv/rocksdb_engine.rs, tests/failpoints/mod.rs, tests/integrations/raftstore/test_service.rs
This updates tests logic and build helpers to use new logic and
features from latest `fail`.
* Update to `fail` 0.3
* Rename feature to `failpoints`
* Serialize tests via `fail::FailScenario`
```
$ cargo test --test failpoints --features failpoints
...
test result: ok. 35 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
=> tests: update to new fail-rs logic

src/coprocessor/codec/datum.rs, src/coprocessor/codec/mysql/json/binary.rs, src/coprocessor/codec/mysql/json/comparison.rs, src/coprocessor/codec/mysql/time/mod.rs, src/coprocessor/codec/mysql/time/tz.rs, src/coprocessor/codec/table.rs, src/coprocessor/dag/expr/mod.rs, src/storage/lock_manager/deadlock.rs, src/storage/mvcc/lock.rs, src/storage/mvcc/write.rs, src/storage/txn/scheduler.rs
for #4960 , change some error, panic, and log outputs from `Debug` to `Display` in `coprocessor` and `storage`
- Misc (code refine)
This pr just make some output format refine for log / error / panic output. I think it's ok to make the current test base happy.
=> coprocessor, storage: Change error, panic, and log outputs from Debug to Display

src/server/service/kv.rs
Return an RegionError when TiKV is closing to tell the client that this region is unavailable temporarily, the client should retry the request in other TiKVs.
No
No
=> [DNM] 2.1: return region error when TiKV is closing

src/storage/mvcc/mod.rs, src/storage/mvcc/txn.rs
When pessimistic transaction is enabled, transactions' time ranges `[start_ts, commit_ts]` may overlap with each other. In `MvccTxn`'s constraint check, if the first write record it found (`w`) is not `Put` or `Delete`, it will use `w.start_ts` to find further write records. If another transaction is committed between `[w.start_ts, w.commit_ts]`, it will be missed.
This PR fixes this issue and adds a simple test for it.
By unit tests.
No.
No.
=> txn: Fix wrong constraint check when txn is overlapping

Cargo.lock
Update rust-rocksdb to include the following changes, which:
* Avoid build require system zlib
* Fix build error related to jemalloc on Mac
* Fix rocksdb build error with GCC9
```
6ead62c 2019-07-25 yiwu@pingcap.com     Avoid build require system zlib (#303)
9246b9c 2019-07-25 hi@breeswish.org     Skip jemalloc options on specific platform (#324)
a0d3b92 2019-07-23 yiwu@pingcap.com     Update rocksdb with cherry-picks (#323)
```
Fixes #5034 
Bug fix
CI
no
no
=> Update rust-rocksdb with build fixes

components/test_storage/src/assert_storage.rs, src/coprocessor/dag/batch/executors/table_scan_executor.rs, src/coprocessor/error.rs, src/server/service/kv.rs, src/storage/lock_manager/util.rs, src/storage/mvcc/mod.rs, src/storage/mvcc/reader/reader.rs, src/storage/mvcc/reader/scanner/mod.rs, src/storage/mvcc/reader/scanner/util.rs, src/storage/mvcc/txn.rs, src/storage/txn/store.rs
This PR assigns a structure (i.e. `LockInfo`) for holding KeyIsLocked content, so that passing these content do not need to repeatedly write out fields.
As you can see, this change will eliminate total LOC.
Existing tests.
=> Assign a structure for KeyIsLocked content

src/binutil/server.rs, src/storage/lock_manager/deadlock.rs, src/storage/lock_manager/waiter_manager.rs
Use `wait-for-lock-timeout` as the TTL of the detect table. So when waiter timeouts, there is no need to send 'CleanUpWaitFor` request to the deadlock detector.
=> pessimistic-txn: eliminate `CleanUpWaitFor` when waiter timeouts

src/coprocessor/dag/rpn_expr/types/test_util.rs, src/server/node.rs
In some occasion, we need to read the `EvalContext` after we evaluate some `RPN` functions, however, the current `RPN` utils don't allow us to read `EvalContext` instead of constructing an evaluator by owning an `EvalConfig`. This PR adds a new function call `evaluate_ctx` to return an `EvalContext` which enables us to examine the value of `EvalContext`.
`cargo test coprocessor::dag::rpn_expr`
=> Add `evaluate_ctx` which returns EvalContext

components/tidb_query/src/codec/convert.rs, components/tidb_query/src/codec/datum.rs, components/tidb_query/src/codec/mysql/decimal.rs, components/tidb_query/src/codec/mysql/duration.rs, components/tidb_query/src/codec/mysql/json/mod.rs, components/tidb_query/src/codec/mysql/time/mod.rs, components/tidb_query/src/executor/aggregate.rs, components/tidb_query/src/expr/builtin_cast.rs, components/tidb_query/src/expr/mod.rs, components/tidb_query/src/rpn_expr/impl_arithmetic.rs, components/tidb_query/src/rpn_expr/impl_cast.rs, components/tidb_query/src/rpn_expr/impl_compare.rs, fuzz/targets/mod.rs
Implements `ConvertTo<Decimal>` for all evaluable types.
Existing unit tests.
=> coprocessor: add a Convert trait and implement convert to decimal

src/storage/txn/process.rs, src/storage/txn/scheduler.rs
Use INFO log level for some frequent and irrelevant errors.
no test.
no
no
=> storage: adjust log level

src/server/debug.rs
`region size` command doesn't consider the key's size.
unit-test
No
No
=> tikv-ctl: Fix region size command

components/engine/src/rocks/util/engine_metrics.rs, components/engine/src/rocks/util/mod.rs
make STORE_ENGINE_SIZE including the size of memtable and blob files.
manual-test
No
=> engine: Fix STORE_ENGINE_SIZE metrics

src/storage/mvcc/mod.rs, src/storage/mvcc/txn.rs
Cherry picks #5128, which fixes a bug that constraint check at insertion may be incorrect when pessimistic transaction is enabled.
By CI
No
No
=> txn: Fix wrong constraint check when txn is overlapping (#5128)

src/binutil/server.rs, src/coprocessor/readpool_impl.rs, src/pd/mod.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/mod.rs, src/raftstore/store/peer.rs, src/raftstore/store/worker/mod.rs, src/raftstore/store/worker/pd.rs, src/server/node.rs, src/storage/kv/mod.rs, src/storage/mod.rs, src/storage/readpool_impl.rs
This PR tries to refactor PD module so we can move it to the independent crate later. Now, we do the following changes:
1. Let Coprocessor and Storage modules don't depend on PD module (IMO, they should not know PD), the two modules only send read flow statistics to PD, so we can extract this to a trait to decouple PD dependency. 
2. Let PD module not depend on raftstore module, the PD module is a base module that the raftstore should depend on it, not reverse. So we move PD task and runner to raftstore worker directly because only raftstore needs these. 
**Doing this can reduce the compiling time, in my local test with `make unportable_release`, the partial compiling time reduced from 10m12s to 9m27s.**
TODO:
1. Move PD module to the …
=> *: make pd module more independent

Cargo.toml, README.md
This should make line numbers appear on unit test failures. The "test" profile crates in cargo seem to be a superset of the "dev" profile crates, so unit test crates ("test" profile) link to the tikv dev crate. So to see line numbers in tikv itself, they have to be turned on for the dev profile.
Fixes #5049
cc @Connor1996 
Manual verification (in progress).
Only README.md, updated.
No
https://github.com/tikv/tikv/issues/5049
=> *: turn on line numbers for dev builds

Cargo.lock, Cargo.toml, src/raftstore/store/peer.rs
Use raft-rs master branch to include some bug fixes:
* https://github.com/pingcap/raft-rs/pull/269, a bug fix about learner
* https://github.com/pingcap/raft-rs/pull/270, to fix the bug about no raft-rs logs
=> raft: temporarily use raft-rs master branch

src/server/config.rs
Signed-off-by: Ana Hobden <operator@hoverbear.org>
Fix #5273 
Check for `0.0.0.0` instead of `0.` on advertise addr parameter of `tikv-server`.
CI test.
It shouldn't. I actually noticed this when I was looking at https://docs.tidb.cc/Test/180406-TiDB-Domain.html which uses hostnames for advertise-addr.
Nope
https://github.com/tikv/tikv/issues/5273
Nope
This should make `0.tikv.dev`, for example, a valid advertise addr.
=> Check for 0.0.0.0 over 0. in advertise addr.

cmd/src/server.rs, components/test_raftstore/src/server.rs, src/server/mod.rs, src/server/server.rs
Pull registering services outside of `Server::new`. Passing services to `Server::new` is no longer required, it would be easy for us to register more services in the future.
Unit tests.
No.
No.
=> *: register services outside of server

components/codec/src/byte.rs, components/tikv_util/src/lib.rs, components/tikv_util/src/logger/mod.rs, src/raftstore/store/fsm/batch.rs, src/raftstore/store/peer.rs, src/raftstore/store/region_snapshot.rs, src/storage/mod.rs
I notice some clippy lints are actually useless. They can be removed now.
And we'd better follow clippy if there is no special reason. I also fix some of them.
CI
No
No
=> Remove useless clippy hints and fix some issues following clippy lints

cmd/src/bin/tikv-ctl.rs
Signed-off-by: mapleFU <1506118561@qq.com>
This pr changes all "about" prompt message first word to uppercase in `cmd/src/tikv_ctl.rs`
In previous `cmd/src/tikv_ctl.rs` , some prompt message begin with lowercase word. This pr changes all of them to uppercase.
- Misc (update prompt message)
Doesn't need to test.
No.
No.
=> cmd/tikv-ctl: change all "about" prompt message first word to uppercase

cmd/src/bin/tikv-ctl.rs
the misspelled words maybe confusing, it `encoded` or `unencoded` ?
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
fix typos words in help message
local test.
NO
NO
=> tikv-ctl.rs: fix command help message

components/tidb_query/src/codec/mysql/duration.rs, components/tidb_query/src/expr/builtin_control.rs, src/coprocessor/statistics/fmsketch.rs, src/raftstore/store/fsm/peer.rs, src/raftstore/store/fsm/store.rs, src/raftstore/store/worker/cleanup.rs, src/raftstore/store/worker/mod.rs, src/storage/kv/rocksdb_engine.rs, src/storage/mvcc/reader/scanner/backward.rs
For reducing the number of threads in tikv, this PR merges Compact, RaftlogGc, CleanupSST worker into one thread.
CI
No.
No.
=> raftstore: merge Compact, RaftlogGc, CleanupSST worker into one thread

src/storage/mvcc/txn.rs
This PR does some minor changes for MvccTxn's tests.
* Cover the case that a delayed prewrite arrives later than committing.
* Cover the case that rollback is invoked when there is another transaction's lock.
* Merged `test_mvcc_txn_rollback` and `test_mvcc_txn_rollback_err` into one test.
By CI
No 
No
=> txn: Cover more corner cases for optimistic txn's tests
