tikv/tikv

src/coprocessor/readpool_impl.rs
src/coprocessor/tracker.rs
src/storage/gc_worker.rs
src/storage/kv/mod.rs
src/storage/mod.rs
src/storage/readpool_impl.rs
src/storage/txn/process.rs
src/storage/txn/sched_pool.rs

This PR improves the performance by using backlog scan details. Metrics are only updated when it is going to be flushed. Previously we need to calculate hash of each scan detail item for each operation. Now we only need to do it during flush.

Improve performance when collecting scan details

---

cmd/src/setup.rs
components/tikv_util/src/config.rs
components/tikv_util/src/future_pool/builder.rs
components/tikv_util/src/future_pool/mod.rs
src/server/readpool/builder.rs
src/server/readpool/mod.rs
src/storage/txn/process.rs
tests/failpoints/cases/test_coprocessor.rs

This PR moves the task limit functionality from read pool to future pool.
Extracted from https://github.com/tikv/tikv/pull/5220

Move task limit from read pool to future pool

---

components/tidb_query/src/rpn_expr/impl_cast.rs
components/tidb_query/src/rpn_expr/mod.rs
components/tidb_query/src/rpn_expr/types/expr_builder.rs
components/tidb_query/src/rpn_expr/types/expr_eval.rs
components/tidb_query/src/rpn_expr/types/test_util.rs

Map all CAST signatures to RPN function for the batch executor framework
Integration tests.

tidb_query: map CAST signatures to RPN function

---

cmd/src/bin/tikv-ctl.rs
cmd/src/bin/tikv-server.rs

Keep -V behavior same with v2.x
Signed-off-by: lucklove <gnu.crazier@gmail.com>
The -V output format of tikv-server and tikv-ctl.
The output of -V in v2.x is something like:
```
TiKV
Release Version: 2.1.14
Git Commit Hash: 32ca82bc067f7529dc07bf8ddb594b8c060b7f49
Git Commit Branch: HEAD
UTC Build Time: 2019-07-04 10:32:40
Rust Version: rustc 1.29.0-nightly (4f3c7a472 2018-07-17)
```
However, in v3.x, it's something like:
```
TiKV 3.0.2
```
And in the newest master, it's:
```
TiKV 0.0.1
```
We should keep the output format same with v2.x, because the tidb and pd's output format is that. I think they should have a unified behavior.
manual test
No
No

Fix output on short version flag

---

components/tikv_util/src/file.rs

Add a function to calculate CRC32 for byte slice.
Unit test.
No.
No.

tikv_util: calculate CRC32 for byte slice

---

CHANGELOG.md
components/pd_client/src/config.rs
components/tikv_util/src/security.rs
src/config.rs
src/import/config.rs
src/raftstore/coprocessor/config.rs
src/raftstore/store/config.rs
src/server/config.rs
src/storage/config.rs
src/storage/lock_manager/config.rs
tests/integrations/config/mod.rs

This reverts commit 034379605e8805c2ce2016903e21e3bd0521f64e (PR #5190).
n/a
None
None
#5286

Revert "*: deny unknown fields when deserializing config TOML (#5190)"

---

cmd/src/bin/tikv-ctl.rs

Signed-off-by: mahjonp <junpeng.man@gmail.com>
- Fix a tikv-ctl subcommand modify-tikv-config usage tips error. When I operated tikv-ctl according to current usage tips, I got the usage help printed, this is because `-h` is the shortcut of `--help`.
manual test
No.
No.

tikv-ctl: fix a modify-tikv-config usage tips error

---

src/raftstore/store/fsm/peer.rs
src/raftstore/store/fsm/store.rs
src/raftstore/store/worker/cleanup.rs

Previous PR https://github.com/tikv/tikv/pull/5297 merged Compact, RaftlogGc, CleapSST into one thread. But we found that would cause a long-running compaction job blocks raftlog GC, then increase compaction frequency of RaftDB, take up more disk I/O bandwidth.
This PR separates RaftlogGc to an individual thread to fix this problem.
CI
No.
No.

raftstore: separate RaftlogGc to an individual thread

---

benches/coprocessor_executors/util/fixture.rs
components/tidb_query/src/batch/executors/fast_hash_aggr_executor.rs
components/tidb_query/src/batch/executors/index_scan_executor.rs
components/tidb_query/src/batch/executors/limit_executor.rs
components/tidb_query/src/batch/executors/selection_executor.rs
components/tidb_query/src/batch/executors/simple_aggr_executor.rs
components/tidb_query/src/batch/executors/slow_hash_aggr_executor.rs
components/tidb_query/src/batch/executors/stream_aggr_executor.rs
components/tidb_query/src/batch/executors/table_scan_executor.rs
components/tidb_query/src/batch/executors/top_n_executor.rs
components/tidb_query/src/batch/executors/util/aggr_executor.rs
components/tidb_query/src/batch/executors/util/mock_executor.rs
components/tidb_query/src/batch/executors/util/scan_executor.rs
components/tidb_query/src/batch/interface.rs

This is a sub pr for #5361 . This pr:
Implements take_scanned_range for BatchExecutorRunner .
Updated integration test in #5361 .
No.
No.
#5361

Copr: Implements `take_scanned_range` for `BatchExecutorRunner`

---

benches/raftstore/mod.rs

Group the test cases into groups so that the generated output is more clear. Besides, it also allow filtering that a command like `cargo bench raftstore` will only run raftstore related cases.
- Engineering
manual tests
No.
No.

bench: make raftstore cases into group

---

components/backup/src/lib.rs
components/backup/src/metrics.rs
components/backup/src/writer.rs

Add BackupWriter which converts txn entries to SST files.
Unit test.
No.
No.

backup: add BackupWriter which converts txn entries to sst files

---

src/storage/mvcc/reader/reader.rs

Add unit tests for MVCC reader check_lock. The added test covers following cases:
- There is no lock
- Read TS >= lock version (should return lock)
- Read TS < lock version (should ignore)
- Read lock or pessimistic lock (should ignore)
- Encounters primary/secondary locks when reading latest records (`ts == u64::MAX`)
Add tests
CI
No
No

Add unit tests for MVCC reader check_lock

---

components/backup/src/endpoint.rs
components/backup/src/lib.rs
components/backup/src/service.rs
src/raftstore/coprocessor/mod.rs
src/raftstore/coprocessor/region_info_accessor.rs
src/storage/mvcc/mod.rs

Add backup service. It accepts backup requests and forwards to a backup endpoint which does the actual backup. 
Note: The endpoint is a plain stub, and will be implemented in upcoming PRs. 
Unit test.
No.
No.

backup: add backup service

---

src/raftstore/store/worker/apply.rs

There is already a same change in master branch, and it's merged. However the change is not cherry picked from master, because code framework changes too much. Here just re-implement it for release 2.1.

raftstore: don't print log for ComapctLog command

---

Cargo.lock
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

I have added one new memtable structure `DoublySkipList` into Rocksdb, which is similar to 
`InlineSkipList` but optimize performance of `Iterator::Prev()`, which is used in reversed range query.  I add a configuration option to enable this feature.
Unit tests
I have also tested this structure in `RocksDB` repo by unit tests.
Yes.  Set `enable_doubly_skiplist` in  tikv.conf to enable this feature.
No
You can see the details in this PR: [https://github.com/pingcap/rocksdb/pull/116](https://github.com/pingcap/rocksdb/pull/116)

[release-3.0]: config support rocksdb doubly skiplist to optimize reverse-scan

---

Cargo.toml
Makefile
cmd/Cargo.toml

Fixes #5289 by using Default-members and default-run as @brson suggested.
`cargo run` & CI
Nope
Nope
#5289 
N/A
`cargo run`, `cargo run --bin tikv-ctl`

Fix Cargo run workflow

---

Cargo.lock

Upgrade grpcio to v0.3.1, grpcio-sys to v0.3.2 in which fixes a segmentation fault bug in grpc c core.
You can see more details in https://github.com/pingcap/grpc/pull/32
Bugfix
Manual test.
No.
No.
https://github.com/pingcap/grpc-rs/pull/373
https://github.com/pingcap/grpc/pull/32

*: upgrade grpcio to v0.3.1, grpcio-sys to v0.3.2

---

Cargo.lock
components/tidb_query/src/batch/executors/util/mod.rs
components/tidb_query/src/batch/interface.rs
components/tidb_query/src/codec/datum.rs
components/tidb_query/src/codec/mysql/time/mod.rs
components/tidb_query/src/rpn_expr/types/expr_eval.rs
components/tikv_alloc/src/jemalloc.rs
components/tikv_util/Cargo.toml
components/tikv_util/src/lib.rs
components/tikv_util/src/mpsc/batch.rs
components/tikv_util/src/security.rs
components/tikv_util/src/sys/mod.rs
src/coprocessor/endpoint.rs
src/coprocessor/readpool_impl.rs
src/coprocessor/statistics/cmsketch.rs
src/coprocessor/statistics/fmsketch.rs
src/storage/kv/mod.rs
src/storage/mod.rs
src/storage/readpool_impl.rs
src/storage/txn/process.rs
src/storage/txn/sched_pool.rs
src/storage/txn/scheduler.rs

I've reduced our unsafe footprint by removing or restricting some uses of `unsafe`. I've documented some unsafe usage. I've changed some uses of `unsafe` in minor ways to better reflect the actual unsafeness and make it easier to check the necessary invariants. This is not a full audit of our unsafe code, just a small step.
N/A
No
No
PTAL @breeswish @5kbpers

Improve our use of unsafe code

---

src/server/service/kv.rs
tests/integrations/raftstore/test_service.rs

We have supported batch split region since https://github.com/tikv/tikv/pull/5268
But the original PR neglects the fact that the keys sent from TiDB side could be unordered. It causes the problem that some keys be ignored when `raftstore` handling it.
- unit test
- test with tidb using following DDL statements:
```
create table t1 (a int,b int,c int,index(b),index (a),index (c,a));
split table t1 between (0) and (500000000) regions 5;
split table t1 index b  between (0) and (500000000) regions 5;
```
No
No
https://github.com/tikv/tikv/pull/5268
None
None

server/service: adapt unordered split keys

---

src/raftstore/store/fsm/store.rs
src/raftstore/store/peer.rs

- rename lease_time to current_time.
- record current_time after calling RawNode::ready_since to reduce the call to
monotonic_raw_now()
No
No
No
#5440

rename lease_time to current_time

---

src/storage/mvcc/reader/point_getter.rs
src/storage/txn/store.rs

When there are concurrent write, lock CF will likely to contain deleted locks. In this scenario, it is much slower to `seek()` compared to `get_cf()` because internally `seek()` will try its best to find a visible user key and these tombstone keys will be iterated. However we actually don't care about the first key > given seek key. What we care is the key == seek key. For this reason, this PR substitutes the lock cursor with `get_cf()`, which was used in batch get.
This PR also substitutes the default cursor with `get_cf()`, which was used in batch get as well, considering that it is very **unlikely** that the keys given to batch get are very close to each other. While keys are not close to each other, a `near_seek()` in the default CF will simply fallback to a `seek()` eventually, which …

Fix PointGetter performance issue when there are concurrent write

---

src/bin/tikv-ctl.rs
src/bin/tikv-server.rs

Keep -V behavior same with v2.x
Signed-off-by: lucklove <gnu.crazier@gmail.com>
The -V output format of tikv-server and tikv-ctl.
The output of -V in v2.x is something like:
```
TiKV
Release Version: 2.1.14
Git Commit Hash: 32ca82bc067f7529dc07bf8ddb594b8c060b7f49
Git Commit Branch: HEAD
UTC Build Time: 2019-07-04 10:32:40
Rust Version: rustc 1.29.0-nightly (4f3c7a472 2018-07-17)
```
However, in v3.x, it's something like:
```
TiKV 3.0.2
```
And in the newest master, it's:
```
TiKV 0.0.1
```
We should keep the output format same with v2.x, because the tidb and pd's output format is that. I think they should have a unified behavior.
manual test
No
No

Fix output on short version flag (#5348)

---

src/server/service/kv.rs

The txn_heart_beat API, which is part of large transaction, updates wrong metrics in code. Fix it.
None.
No.
No.

service/kv: fix wrong metrics of txn_heart_beat

---

components/tidb_query/src/codec/chunk/chunk.rs
components/tidb_query/src/codec/chunk/column.rs
components/tidb_query/src/codec/data_type/vector.rs
components/tidb_query/src/codec/datum.rs
components/tidb_query/src/codec/mysql/decimal.rs
components/tidb_query/src/codec/mysql/duration.rs
components/tidb_query/src/codec/mysql/json/binary.rs
components/tidb_query/src/codec/mysql/time/mod.rs
components/tidb_query/src/codec/table.rs
components/tidb_query/src/executor/mod.rs
components/tidb_query/src/executor/selection.rs
components/tidb_query/src/executor/topn.rs
components/tidb_query/src/expr/mod.rs

This PR change all the `encode` part using `codec::BufferWriter`.  parts of issue https://github.com/tikv/tikv/issues/4040
Engineering
unit test (make expression)
No
No
https://github.com/tikv/tikv/issues/4040

coprocessor: use BufferWriter for tidb_query component

---

Cargo.lock
src/server/metrics.rs
src/server/service/kv.rs
src/storage/metrics.rs
src/storage/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs
src/storage/txn/process.rs
src/storage/txn/scheduler.rs
tests/integrations/server/mod.rs

This PR cherry-picks #5407 . For more detail please refer to #5407 . This is cherry-picked to 3.0 because it's needed by pessimistic transaction.
By CI
This should be noted in release notes.
No.

(3.0) txn: Add txn_heart_beat API (#5407)

---

Cargo.lock

Upgrade grpcio to v0.4.5. 
- Support resource quota
- Fix a segmentation fault bug in grpc c core
- Support cross-compile for iOS and Android targets
- Support ipv6 host
- Remove tilde requirements `~2.0` of protobuf
in which fixes a segmentation fault bug in grpc c core and adds resource quota support.
New feature (a change which adds functionality)
Bugfix (a change which fixes an issue)
Manual test.
No.
No.
https://github.com/pingcap/grpc-rs/pull/380

*: upgrade grpcio to v0.4.5

---

Cargo.lock
docs/op-guide/grpc-config.md
etc/config-template.toml
src/server/config.rs
src/server/server.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

- support memory quota
- fix grpc coredump issue
- New features
integration tests
Yes.
Yes.

*: support memory quota

---

Cargo.lock
components/tidb_query/Cargo.toml

Attempt to resolve #5509. Hoping for verification from @H-ZeX and @iosmanthus this solves their issue.
As seen in #5509, the user receives this error:
```
/tmp/test_tmp_2/tikv-7cbf045bb6bf7255ddedd44e76beba98efedd2e6/target/debug/deps/libopenssl_sys-40383d0da2264c5e.rlib(asn1_par.o): In function `ASN1_tag2str':
/tmp/test_tmp_2/tikv-7cbf045bb6bf7255ddedd44e76beba98efedd2e6/target/debug/build/openssl-sys-b00afba846c352da/out/openssl-build/build/src/crypto/asn1/asn1_par.c:369: multiple definition of `ASN1_tag2str'
/tmp/test_tmp_2/tikv-7cbf045bb6bf7255ddedd44e76beba98efedd2e6/target/debug/deps/libgrpcio_sys-0b6595ea2a7b83cd.rlib(asn1_par.c.o):/home/hzx/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.5.0-alpha.4/grpc/third_party/boringssl/crypto/asn1/asn1_par.c:61: first defined …
```

Unvendor SSL to remove duplicate OpenSSL fns

---

components/test_raftstore/src/cluster.rs
src/raftstore/store/fsm/apply.rs
src/raftstore/store/peer.rs
tests/failpoints/cases/test_merge.rs
tests/integrations/raftstore/test_merge.rs

cherry-pick of https://github.com/tikv/tikv/pull/5512

Fix commit index is not forwarded when merge entry is empty (#5512)

---

components/tidb_query/src/codec/mysql/binary_literal.rs
components/tidb_query/src/codec/mysql/mod.rs

This PR ports the `BinaryLiteral` from TiDB to the coprocessor. And fix some `FIXME` (e.g: https://github.com/tikv/tikv/pull/5433/files#diff-7b0a1830a6f61d6aedda123d5086c8edR453) after this PR merged.
Unit tests

tidb_query: port the BinaryLiteral from TiDB to the Coprocessor

---

Cargo.lock
components/tidb_query/src/codec/data_type/mod.rs
components/tidb_query/src/rpn_expr/types/function.rs
components/tidb_query_codegen/Cargo.toml
components/tidb_query_codegen/src/aggr_function.rs
components/tidb_query_codegen/src/rpn_function.rs

Made use of compile-time type information given by #[rpn_fn] macro to avoid unnecessary monopolization on rpn_fn functions so as to cut down compilation time consumption.
- Engineering
Unit tests
Reduced compilation time spend on tidb_query submodule from `4m51s` to `1m08s` in release mode on IDC.

tidb_query: avoid unnecessary generic monopolization in rpn_fn

---

components/test_storage/src/assert_storage.rs
components/test_storage/src/sync_storage.rs
src/server/service/kv.rs
src/storage/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs
src/storage/txn/process.rs
src/storage/txn/scheduler.rs
tests/integrations/storage/test_storage.rs

This PR cherry-picks #5471 , which is part of refinement of pessimistic transactions, to release-3.0 branch. For more details please view #5471 .
- Unit test
- No.
No.
* Cherry-picks: #5471 
* Corresponding PR in TiDB: pingcap/tidb#12417

(3.0) txn: Check lock's TTL when doing cleanup (#5471)

---

components/tikv_util/src/mpsc/batch.rs
src/raftstore/store/fsm/batch.rs
src/raftstore/store/fsm/store.rs
src/server/raft_client.rs

cherry-pick #5475 to release-3.1
Technically, a thread only needs to flush messages when it's going to
block. This PR add hooks to every block point instead of flushing at
the end of every ready.
- Improvement
integration tests
No.
No.
Benchmark shows that when there are about 25k idle regions, raftstore CPU is reduced from 55% to 40%, and grpc is reduced from 60% to 40%。

raftstore: reduce message flush (#5475)

---

components/pd_client/src/client.rs
components/pd_client/src/util.rs

`pd_client/lib.rs` has a `PdClient` trait, and `pd_client/util.rs` use `kvproto::pdpb::PdClient`.
This PR rename `kvproto::pdpb:PdClient` to `PdClientStub` in `pd_client/src/util.rs`
- No code
NO
NO
N/A
N/A
N/A

pd_client: rename kvproto::pdpb::PdClient to PdClientStub in pd_client/src/util.rs

---

components/backup/src/endpoint.rs

Update backup task finish condition in forward
if backup_range reached task's end_key, we should set `finished` to true, otherwise next_start will be equal to end_key then cause panic
this case can cause panic
```
task: key range 1 -> 2
region1: 1 -> 3
region2: 3 -> null
```
- Unit test
no
no

backup: fix seek region panic

---

src/storage/mod.rs
src/storage/txn/process.rs

TiKV's scan_lock didn't pass the locks' TTLs. So when GC meets lock, TiDB will get 0 as the TTL, and all locks will be regarded as expired and cleaned up. Unfinished transactions will be aborted.
This PR fixes this problem.
- Unit test
No
No

storage: Fix scan_lock doesn't return lock's TTL

---

src/raftstore/store/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml
tests/integrations/storage/test_raftkv.rs

It has been tested for quite a long time, but it still needs to be
tested in a more widely environment, so enable it by default on master.
- Improvement
No.
No.

raftstore: hibernate by default

---

components/keys/src/types.rs
components/tikv_util/src/codec/bytes.rs

This PR adds a function to check if the encoded and raw format refers to the same key.
The motivation is that we want to know if a lock is a primary lock. However, inside TiKV we use encoded keys while the stored primary key in the lock is in the raw format.
An alternatives are directly passing raw keys into the transaction layer. But this makes the transaction code uglier. The benchmark result below shows that for a typical key length (30 bytes), it takes just less than 10ns and in most cases, two different keys are different in their tails. So the performance impact is quite small.
- Unit test
No
No
https://github.com/tikv/tikv/pull/5575 may utilize it.
```
test codec::bytes::tests::bench_is_encoded_from       ... bench:         949 …
```

util: compare raw and encoded keys without explicit decoding

---

Cargo.lock

criterion-papi previously has a mistake in its build script thus it makes TiKV fail to build on macOS. Now I fix the issue in https://github.com/YangKeao/rust-papi/pull/1. Upgrading to libpapi_sys 0.1.3 fixes it.
It now compiles on my laptop running macOS.
No
No

fix criterion-papi build failure on macOS

---

src/config.rs

Adjust readpool size by the number of cpu core, make it works better under sysbench and other benchmark cases when using default configuration value.
- If there is a document change, please file a PR in ([docs](https://github.com/tikv/website/tree/master/content)) and add the PR number here.
- If this PR should be mentioned in the release note, please update the [release notes](https://github.com/tikv/tikv/blob/master/CHANGELOG.md).
No

adjust readpool size by the number of cpu core

---

Makefile
src/raftstore/store/worker/pd.rs

Currently running the test suite on Mac OS fails. For some users only the pd test fails, for others there are many integration test fails (these are intermittent, but usually 10-30 failures).
This PR fixes the issues and makes the test suite pass on Mac. It should be a productivity boost for all developers using Macs (including me :-) ). This PR skips one test based on the target OS. The number of test threads is set to two, on Mac using one thread per core causes problems due to contention slowing down tests and due to the limit in the number of file descriptors which can be created. I made this change to all platforms, since it is possible that using too many threads will cause problems elsewhere, it probably does not make the tests much slower (due to thread contention on OS/HW …

Pass tests on Mac OS

---

Cargo.lock

Update rust-rocksdb to include fix for Titan missing blob file issue (https://github.com/pingcap/titan/issues/93). Commits of rust-rocksdb included:
```
123e9ed 2019-10-16 yiwu@pingcap.com     Temp fix Titan missing blob issue (#355)
19ac3a9 2019-10-11 bupt2013211450@gma.. add io stall stats interface (#353)
```
Bugfix
Unit test & test cluster
no
no

Fix titan missing blob file issue

---

Cargo.lock

Update rust-rocksdb to pick up the following rocksdb and titan changes. The most notable one is fixing titan missing blob file issue.
rocksdb:
```
7e4e054ae 2019-10-15 yiwu@pingcap.com     Make WaitForFlushMemTable public (#125)
89ff3e3b8 2019-09-29 yiwu@pingcap.com     Lower the risk for users to run options.force_consistency_checks = true (#5744) (#120)
9c5b744ee 2019-09-26 nrc@ncameron.org     Relax warnings as errors so we can build on Clang 11 (#123)
179a8f5e0 2019-09-20 yiwu@pingcap.com     fast look up purge_queue (#5796) (#119)
```
titan:
```
43225d4 2019-10-16 yiwu@pingcap.com     Fix Titan missing blob issue (#97)
```
Bugfix
CI
no
no

cherry-pick titan missing blob file fix and a few other rocksdb changes

---

src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs
src/storage/mvcc/write.rs

Cherry picks #5309, #5575 
- Unit test
Should be mentioned in release notes.
No

txn: protect primary locks of pessimistic transactions from being collapsed

---

components/backup/src/endpoint.rs

cherry-pick this [PR](https://github.com/tikv/tikv/pull/5660) to release-3.1
Change backup_file format from `storeID_regionID_regionVersion` to `storeID_regionID_regionVersion_tableID`,  because one region may contain several tables, when we backup tables one by one, former format could cause `FileAlreadyExists` exception.
- Unit test
no
no

backup: format file name with table_id

---

src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs

As the title.
- No code
I will test it in https://github.com/tikv/tikv/pull/5422.
No
No

txn: fix wrong txn_size in acquire_pessimistic_lock

---

Cargo.lock
Cargo.toml
components/engine/src/rocks/mod.rs
components/engine/src/rocks/sst.rs
src/import/errors.rs
src/import/sst_importer.rs
src/import/sst_service.rs
src/raftstore/store/keys.rs
src/raftstore/store/keys/rewrite.rs
tests/integrations/import/sst_service.rs

Cherry-pick #5581 to release-3.1.
- Unit test
No?
No
#5581

Cherry-pick `sst_importer: download SST from external storage + key rewrite (#5581)` to release-3.1

---

Cargo.lock
Cargo.toml
Makefile
components/engine/Cargo.toml
components/engine_rocks/Cargo.toml

Add `make titan_release` to support building TiKV with specified Titan.
environment variable `TITAN_REPO` and `TITAN_BRANCH` specify the codebase --`https://github.com/{TITAN_REPO}/titan/tree/{TITAN_BRANCH}` to build Titan.
Should merge https://github.com/pingcap/rust-rocksdb/pull/359 first
run `TITAN_REPO=Connor1996 TITAN_BRANCH=delete-files make titan_release` with very verbose output
, and it shows the enviorment variables are correctly passed to `rust-rocksdb` build progress
```
[libtitan_sys 0.0.1] if [ -n "Connor1996" ]; then \
[libtitan_sys 0.0.1]    git config --file=.gitmodules submodule.titan.url https://github.com/Connor1996/titan.git; \ …
```

build: Support building TiKV with specified Titan 

---

Cargo.lock

Update rust-rocksdb to include a change to disable rocksdb intra-L0 compaction. This is a temp fix to avoid data corruption involving intra-L0 compacting ingested file.
Full rust-rocksdb change:
```
81881c1 2019-10-23 yiwu@pingcap.com     Cherry-pick rocksdb change to disable intra-L0 compaction (#360)
d991b34 2019-10-21 kennytm@gmail.com    Export SstFileReader (#347) (#357)
```
Bugfix
CI
Should update release note to mention the fix.
No

Updte rust-rocksdb to avoid intra-L0 compaction issue

---

tests/integrations/raftstore/test_prevote.rs

test `test_prevote_reboot_minority_followers` failed, because a peer unexpected send a `MsgRequestVoteResponse` response to an unexpected pre-condidate which happen because the handle interval of  leader's `Readiness` are much more longer the `election_timeout`(maybe because not enough CPU resource), thus many msgs from leader are send and handle by follower after many `election_tick`. This pr fix it by increase the raft_election_timeout_ticks.
No
No
No
close #5615

tests: fix unstatble test test_prevote_reboot_minority_followers

---

Cargo.lock
src/server/node.rs

The TiKV uses `status_address` to provide HTTP service for external components. But the original store metadata does not contain the `status_address` and `git_hash` information, so the TiDB cannot get the `status_address` from PD via `GetAllStores` gRPC interface. Furthermore, TiDB cannot use the HTTP service provided by TiKV.
This PR adds the support that reports the status_address and git_hash to PD on TiKV startup to make subsequent work easier.

server: report the status_address and git_hash to PD on TiKV startup

---

components/tidb_query/src/batch/executors/fast_hash_aggr_executor.rs
components/tidb_query/src/batch/executors/selection_executor.rs
components/tidb_query/src/rpn_expr/types/expr.rs
components/tidb_query/src/rpn_expr/types/expr_builder.rs

Extracted from https://github.com/tikv/tikv/pull/5755, don't derive `Clone` for `RpnExpressionNode`. It enables an `RpnExpressionNode` to carry non-`Clone` data in the future. It also helps @andylokandy with his bump allocator work.
- Unit test
No
No

tidb_query: make RpnExpressionNode not Clone

---

MAINTAINERS.md

Signed-off-by: winkyao <golangwink@gmail.com>
My Name is Yao Wei, My English name is Wink Yao. I am from PingCAP, and where I help to implement the online schema changed in TiDB, which is inspired by [Online, Asynchronous Schema Change in F1](https://research.google.com/pubs/archive/41376.pdf). 
As part of my involvement with the project, I am currently focusing on the TiKV community. And try to help the TiKV community more active and make our contributors more involved in the TiKV project.
The project maintainer [Siddon Tang](https://github.com/siddontang) inquired if I was interested in becoming a maintainer for the TiKV project. 
This PR adds me to the list of maintainers. I have read and understood the expectations of maintainers described in the GOVERNANCE.md file.

MAINTAINERS: add @winkyao to MAINTAINERS.md

---

README.md

-  This PR update the readme to discontinue the documentation on https://github.com/tikv/tikv/wiki and direct users to tikv.org where necessary. After this update, we will only maintain documentation on tikv.org.  
- No code

Readme: discontinue wiki page and direct users to tikv.org for docs

---

components/keys/src/rewrite.rs
components/sst_importer/src/sst_importer.rs
tests/integrations/import/sst_service.rs

The `ingest()` function expects a closed range instead of half-open range. 
Change the `download()` function to accept and return closed ranges.
- Unit test
No
No

sst_importer: change download() to use closed range

---

Cargo.lock
src/server/service/kv.rs
src/storage/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs
src/storage/txn/process.rs

This PR makes `check_txn_status` supports specifying the behavior when neither commit/rollback record nor lock of a transaction's primary key is found. A new parameter `rollback_if_not_exist` was added. If it's `true`, it will write a rollback record in this case; otherwise, it returns a new error TxnNotFound.
This is part of supporting large transactions.
- Unit test
No
No

txn: check_txn_status Support setting write rollback or not when txn not exist

---

Cargo.lock
Cargo.toml
cmd/Cargo.toml
components/backup/Cargo.toml
components/sst_importer/Cargo.toml
components/test_raftstore/Cargo.toml
components/tikv_util/Cargo.toml

Update GRPC to support GCC 9.2.1 with https://github.com/tikv/grpc-rs/pull/386 which contains https://github.com/pingcap/grpc/pull/33 which is a backport of https://github.com/grpc/grpc/pull/18950 .
Users with Ubuntu 19.10 or similar distros can now build TiKV easily!
Engineering
Manually and by the CI
No
No 
https://github.com/tikv/grpc-rs/pull/386 which contains https://github.com/pingcap/grpc/pull/33 which is a backport of https://github.com/grpc/grpc/pull/18950 .

Update GRPC to fix GCC 9.2.1

---

src/coprocessor/tracker.rs
src/storage/kv/perf_context.rs
src/storage/kv/rocksdb_engine.rs
src/storage/mvcc/reader/scanner/mod.rs

Simple refactoring to remove `Defer` impls, which are bad style to use except for smart pointers, see for example [the std docs](https://doc.rust-lang.org/std/ops/trait.Deref.html).
PTAL @AndreMouche  @MyonKeminta

storage: remove Deref impls

---

src/server/service/kv.rs
tests/integrations/raftstore/test_service.rs

Cherry-pick #5001 #5268 #5466 
unit-tests
NOTE: Does not support new TiDB run with old TiKV. For example, TiDB v3.0.4 + TiKV v3.0.0.
If there is a configuration or metrics change, please file a PR in [tidb-ansible](https://github.com/pingcap/tidb-ansible), and add the PR number here.
#5001 #5268 #5466 
None
None

Support batch split region command and empty batch command (#5470)

---

cmd/src/server.rs
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/util.rs
components/tikv_util/src/config.rs
src/config.rs
tests/integrations/raftstore/test_bootstrap.rs
tests/integrations/storage/mod.rs
tests/integrations/storage/test_turnoff_titan.rs

Check titandb directory is empty (`ls *.blob` count = 0) when titan is disabled. Fatal panic if this check fails, which indicates titan is turned off before all blob files are merged.
- Unit test

Cherry-pick check titandb directory when titan is disabled

---

Cargo.lock
components/tidb_query/src/expr/scalar_function.rs

Improves the error message when TiDB forgets specifying PbCode in some expressions.

Report better error message when PbCode is unspecified

---

src/raftstore/store/fsm/apply.rs

Make make `on_apply_write_cmd` failpoint injectable through http service.
No.
No.

raftstore: make `on_apply_write_cmd` failpoint injectable

---

components/tidb_query/src/rpn_expr/impl_op.rs
components/tidb_query/src/rpn_expr/mod.rs

PCP #5751
Add vectorized BitNegSig
Improvement. Non-vectorized BitNegSig already exists. Just add a vectorized version for better performance.
Unit tested. Will run copr test later.
No. It should not change the behavior.
No.

copr: Add vectorized BitNegSig

---

components/tidb_query/src/rpn_expr/impl_op.rs
components/tidb_query/src/rpn_expr/mod.rs

PCP #5751
Add vectorized BitOrSig
Improvement. Non-vectorized BitOrSig already exists. Just add a vectorized version for better performance.
Unit tested. Will run copr test later.
No. It should not change the behavior.
No.

copr: Add vectorized BitOrSig

---

Cargo.lock

- Upgrade `libpapi_sys`
- Then newest version of `libpapi_sys` fix build time bugs by add `-fPIC` flag into CFLAGS env
- Bugfix
- Manual test (by @breeswish )
No
No

benches/coprocessor_executors: update libpapi_sys to build with -fPIC

---

src/raftstore/store/fsm/store.rs
src/raftstore/store/local_metrics.rs
src/raftstore/store/metrics.rs
src/raftstore/store/peer.rs

cherry-pick: #5440 #5465 
No
No
pingcap/tidb-ansible#577

[release-3.0] cherry pick: add commit log duration metrics

---

Cargo.lock
Cargo.toml
src/server/status_server.rs

Closes #5932
It seems that the build is broken because pprof is a Linux-only crate (because it depends on a function in libc which is not portable). In this PR I make pprof a Linux-only dep and cfg away any usage.
it builds

Build: fix build on Mac OS by cfg'ing away pprof

---

Makefile

Signed-off-by: mahjonp <junpeng.man@gmail.com>
Speed up CI's test through ignore other irrelevant cargo test scripts.
- No code
- No
- No

Makefile: a new rule for CI test

---

components/tidb_query/src/rpn_expr/types/expr_builder.rs
components/tidb_query/src/rpn_expr/types/test_util.rs

Many unit tests in tidb_query use `RpnFnScalarEvaluator` to test rpn functions. Previously, we forgot to generate metadata in `RpnFnScalarEvaluator`, making tests for rpn functions with metadata fail.
This PR makes `RpnFnScalarEvaluator` support metadata.
`RpnFnScalarEvaluator` is tightly coupled with real signatures so it'll be a big change to do unit tests for it. Luckily, this fix should be easily validated by testing rpn functions with metadata later. A manual test with code below can pass:
```rust
fn compare_in_hash_data<T: Evaluable + Hash + Eq>(_expr: &mut tipb::Expr) -> HashSet<T> {
HashSet::default()
}
#[rpn_fn(varg, min_args = 1, capture = [metadata], metadata_ctor = …
```

support rpn_fn metadata in RpnFnScalarEvaluator

---

components/tidb_query/src/rpn_expr/types/expr.rs
components/tidb_query/src/rpn_expr/types/test_util.rs

In `RpnFnScalarEvaluator`, `evaluate_raw` will construct some `Expr` then evaluate it for test, but only `Expr.field_type` is set correctly, `Expr.tp` is left to be default value (`NULL`).
If some builtin_function try to optimize by the expression node's type, then the test will break.
- Unit test
No
No

copr: set Expr.tp in RpnFnScalarEvaluator

---

src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Change configuration to make TiKV could use RocksDB.unodered_write, which could insert keys more effective. But I'm not sure this feature is correctly, so I set `enable_unodered_write` to `false` by default.
- Unit test
No
Yes, I would add one configuration option later after this PR was merged.
https://github.com/tikv/rust-rocksdb/pull/380
More than 20% improve with `bulk_insert`

TiKV supports unordered write

---

benches/coprocessor_executors/util/bencher.rs
components/profiler/examples/prime.rs
components/tidb_query/src/rpn_expr/types/expr_eval.rs

Currently when enabling the profiling feature, related benchmarks will panic:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(InvalidPath, State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:1165:5
```

Fix panic when profiling is enabled

---

components/pd_client/src/client.rs
components/pd_client/src/lib.rs
src/server/lock_manager/deadlock.rs
src/server/lock_manager/mod.rs
src/server/resolve.rs

Don't send clean up requests if a pessimistic transaction doesn't detect deadlocks.
- Unit test
- Manual test
No
No

lock_manager: reduce clean up requests

---

Cargo.lock

Update rust-rocksdb to include two bug fixes
- rocksdb: Fix OnFlushCompleted fired before flush result write to MANIFEST https://github.com/pingcap/rocksdb/pull/130
- titan: Fix status overrided by mistake https://github.com/pingcap/titan/pull/111
Close #5955 
- No code
No
No

engine: update rocksdb and titan

---

src/bin/tikv-ctl.rs
src/server/debug.rs
src/server/server.rs
src/server/service/debug.rs
src/storage/gc_worker.rs
src/storage/mod.rs

gc: config gc io limit dynamically (#5769)

---

Cargo.lock
Cargo.toml
src/server/status_server.rs

cherry-pick: #5697 #5933 
They have just been tested manually :(
No
No
#5666 
Assume that tikv status_server is listening at localhost:8080
```
curl "http://localhost:8080/debug/pprof/profile?frequency=50&seconds=10" # this will start cpu sampler at 10/sec frequency and continues 10 secs.
```
```
curl "http://localhost:8080/debug/pprof/profile?frequency=50&seconds=10" --header  "Content-Type: application/protobuf" # this will return a pprof protobuf
```
The implementation of `rsperftools` is not efficient ([some performance improvement](https://github.com/YangKeao/rsperftools/issues) will land these days). So too high frequency will make it hold lock all the time and may lead to long response …

[release-3.0] cherry pick: Generate flamegraph at runtime

---

src/pd/client.rs
src/pd/mod.rs
src/server/lock_manager/deadlock.rs
src/server/lock_manager/mod.rs
src/server/resolve.rs

Cherry pick #5959 
Don't send clean up requests if a pessimistic transaction doesn't detect deadlocks.
Improvement (a change which is an improvement to an existing feature)
- Unit test
- Manual test
No

lock_manager: reduce clean up requests (#5959)

---

components/tidb_query/src/rpn_expr/types/expr_builder.rs
components/tidb_query/src/rpn_expr/types/expr_eval.rs
components/tidb_query/src/rpn_expr/types/function.rs
components/tidb_query/src/rpn_expr/types/test_util.rs
components/tidb_query_codegen/src/rpn_function.rs

Signed-off-by: TennyZhuang <zty0826@gmail.com>
When use metadata in rpn framework, metadata_ctor may failed due to some expression error.
Now, metadata_ctor return the Metadata directly, It seems that return a Result<Metadata> is better.
- Unit test

copr: metadata_ctor should return Result

---

Cargo.toml
src/coprocessor/codec/data_type/vector.rs
src/coprocessor/dag/aggr_fn/impl_avg.rs
src/coprocessor/dag/aggr_fn/impl_first.rs
src/coprocessor/dag/aggr_fn/impl_max_min.rs
src/coprocessor/dag/aggr_fn/impl_sum.rs
src/server/status_server.rs

Cherry pick #5429 to avoid TiKV panic.
This PR cannot avoid related SQLs to fail. However currently in 3.0 version we do not have easy way to make it work, because of lacking cast functions, unless TiDB uses correct type for `SUM(year)`.

Cherry pick #5429

---

components/tidb_query/src/expr/builtin_string.rs

Signed-off-by: Zhu Zihao <all_but_last@163.com>
Fix the bug introduced by #5999, described in https://github.com/tikv/tikv/pull/5978.
For given SQL statement
```sql
select concat_ws(',', 'abc', NULL);
```
TiKV will return `abc,` but expected `abc`.
- Unit test
No
No

fix(copr): Handle trailing NULL correctly for `concat_ws`.

---

cmd/src/bin/tikv-ctl.rs
cmd/src/server.rs
components/test_raftstore/src/server.rs
src/server/debug.rs
src/server/service/debug.rs
src/storage/gc_worker.rs
src/storage/mod.rs

Cherry pick #5769 
`tikv-ctl` can change gc io limit dynamically now. Usage:
```
tikv-ctl --host=host modify-tikv-config -m server -n gc.max_write_bytes_per_sec -v 10MB
```
It's used to limit the write flow when gc influences normal requests, and remove the limit when there is no influence.
- Unit test

gc: config gc io limit dynamically (#5769) (#5957)

---

Makefile

Fixes #6022, allowing `make dist_release` and `make dist_unportable_release` to build on Mac.
Nope
Nope

Make build_dist_release support Mac

---

fuzz/README.md
fuzz/cli.rs
fuzz/fuzzer-honggfuzz/Cargo.toml

Currently fuzz using AFL will not work, since `cargo afl` always returns exit code 1.
fuzz using Honggfuzz will not work according to README, since it suggests a wrong version.
- Manual test

Fix Fuzzing using AFL and Honggfuzz

---

components/tidb_query/src/codec/mysql/decimal.rs

use `checked_mul` to avoid overflow panic.
Resolve #6044

copr: fix read_decimal multiply overflow panic

---

components/tidb_query/src/batch/executors/fast_hash_aggr_executor.rs
components/tidb_query/src/codec/mysql/decimal.rs
components/tidb_query/src/codec/mysql/time/mod.rs
fuzz/targets/mod.rs

Signed-off-by: TennyZhuang <zty0826@gmail.com>
- Separately describe each logical change (optional)
implement Hash for Decimal and Time
- Unit test
- Fuzz test

copr: implement Hash for Decimal and Time

---

src/coprocessor/statistics/analyze.rs

The TiKV has inconsistent behavior with TiDB about analyzing column. see: 
https://github.com/pingcap/tidb/blob/eae41adc0cd4a617d792a8bb426033c433a70527/statistics/sample.go#L173
The TiDB assumes samples will keep order with the original data order if the samples count greater than the `max_sample_count`. But TiKV replaces the original data if the index conflict, which breaks the assumption.
According to the TiDB logic, we should remove the item which index conflected, and append the new item to the samples.
- Unit test

tidb_query: fix analyze column inconsistent behavior betwen TiDB and TiKV

---

src/raftstore/store/fsm/peer.rs
src/raftstore/store/peer.rs
src/raftstore/store/peer_storage.rs

Attach peer tag to box errors, it is convenient for debugging.
- Unit test
No.
No.

raftstore: attach peer tag to box errors

---

components/backup/src/endpoint.rs

Signed-off-by: luancheng <luancheng@pingcap.com>
use range start_key to build filename during backup, to make filename unique
- Unit test
N/A
N/A

backup: put startKey into backup_file_name to make it unique

---

Cargo.lock
components/tidb_query/src/expr/scalar_function.rs

Signed-off-by: wshwsh12 <793703860@qq.com>
When I update tipb and it will compile error.
```
error[E0004]: non-exhaustive patterns: `TruncateUint`, `AesDecryptIv`, `AesEncryptIv` and 21 more not covered
--> components/tidb_query/src/expr/scalar_function.rs:17:42
|
17 |         let (min_args, max_args) = match sig {
|                                          ^^^ patterns `TruncateUint`, `AesDecryptIv`, `AesEncryptIv` and 21 more not covered
|
= help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
error: aborting due to previous error
```
We should add missing scalar function signature.
- Unit test
https://github.com/pingcap/tipb/pull/155

expression: add missing scalar function signature

---

src/coprocessor/endpoint.rs

A test was failing due to recursion limit being set in configuration which I didn't notice in the Prost PR.
Tests pass
PTAL @Hoverbear @yiwu-arbug

Fix a failing test due to recursion limit

---

src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs

cherry-pick #5737 to release-3.1
If a pessimistic prewrite request arrives and it carries a smaller TTL than that already wrote in the pessimistic lock, keep the pessimistic lock's TTL rather than use the TTL in the reqeust.
for more detail, please check #5737.
- Unit test
Yes
No

txn: Keep pessimistic lock's TTL if it's greater than prewrite… (#6056)

---

src/pd/client.rs
src/pd/mod.rs
src/server/lock_manager/deadlock.rs
src/server/lock_manager/mod.rs
src/server/resolve.rs

Cherry pck #5959 
Don't send clean up requests if a pessimistic transaction doesn't detect deadlocks.
- Unit test
- Manual test
No
No

lock_manager: reduce clean up requests (#5959) (#5965)

---

Cargo.lock
Cargo.toml
src/server/status_server.rs

cherry-pick: #5697  #5933  #6064 
They have just been tested manually :(
No
No
#5666 
Assume that tikv status_server is listening at localhost:8080
```
curl "http://localhost:8080/debug/pprof/profile?frequency=50&seconds=10" # this will start cpu sampler at 10/sec frequency and continues 10 secs.
```
```
curl "http://localhost:8080/debug/pprof/profile?frequency=50&seconds=10" --header  "Content-Type: application/protobuf" # this will return a pprof protobuf
```
The implementation of `rsperftools` is not efficient ([some performance improvement](https://github.com/YangKeao/rsperftools/issues) will land these days). So too high frequency will make it hold lock all the time and may lead to long …

[release-3.1] cherry pick: Generate flamegraph at runtime  (#5697)

---

components/tidb_query/src/batch/executors/table_scan_executor.rs
components/tidb_query/src/batch/interface.rs
components/tidb_query/src/batch/runner.rs
tests/benches/coprocessor_executors/integrated/util.rs

BatchExecutor spends little when collecting execution summary. Thus this PR enables it in all scenarios, so that we can collect the time of each batch executor in later PRs.
- Unit test

Always collect execution summary for BatchExecutor

---

components/test_raftstore/src/pd.rs
components/test_raftstore/src/server.rs
src/pd/mod.rs
src/server/lock_manager/deadlock.rs
src/server/lock_manager/mod.rs
tests/integrations/server/lock_manager.rs
tests/integrations/server/mod.rs

A new peer's region info is not complete until applying snapshot which causes the leader of the deadlock detector stepping down. Only observing valid region can fix it.
- Unit test
Yes
No
Without the fix, the new added test will panic when a new peer is added to the store with the leader of deadlock detector.
```
---- server::lock_manager::test_detect_deadlock_when_shuffle_region stdout ----
thread 'server::lock_manager::test_detect_deadlock_when_shuffle_region' panicked at 'assertion failed: resp.errors[0].has_deadlock()', tests/integrations/server/lock_manager.rs:61:5
stack backtrace:
0: backtrace::backtrace::libunwind::trace
at …
```

deadlock: only observe valid region

---

Cargo.lock

Update `rust-rocksdb`, to make old gcc able to compile titan.
- No code
No
No
https://github.com/tikv/titan/pull/123

fix titan CI

---

components/backup/src/endpoint.rs

Signed-off-by: luancheng <luancheng@pingcap.com>
Cherry-pick #6071 to release-3.1
use range start_key to build filename during backup, to make filename unique
- Unit test
N/A
N/A

backup: put startKey into backup_file_name to make it unique (#6071)

---

src/server/gc_worker.rs
src/storage/kv/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/txn.rs
src/storage/txn/process.rs
src/storage/txn/store.rs
tests/benches/hierarchy/mvcc/mod.rs
tests/benches/hierarchy/txn/mod.rs

The commits stand alone and the descriptions say what they are doing. The first three are fairly trivial tidying up. ~~The forth moves `is_pessimistic_lock` from `Options` to `Command::Prewrite`, which makes sense because that is the only command it is used with.~~
PTAL @MyonKeminta @youjiali1995

txn refactoring: some tidying up

---

src/raftstore/store/fsm/peer.rs
src/raftstore/store/fsm/store.rs
src/raftstore/store/local_metrics.rs
src/raftstore/store/peer.rs

Batch multiple raft command into an entry to reduce raft message between tikv-server.
- No code
No
No

Batch multiple raft command into an entry

---

components/tidb_query/src/expr/builtin_json.rs
components/tidb_query/src/expr/scalar_function.rs

Signed-off-by: Wangweizhen <hawking.rei@gmail.com>
PCP #5751
Add non-vectorized json-depth
- New feature
Unit tested. Will run copr test later.
No. It should not change the behavior.
No.

copr: add non-vectorized json depth

---

src/import/kv_server.rs
tests/import/kv_service.rs

Remove the 32 MB gRPC message size limit from tikv-importer, since some users have a single KV pair of size over 90 MB (cherry-picks tikv/importer#26)
No
No

[2.1] import/kv_server: make the gRPC message size unlimited

---

Cargo.toml
components/tikv_alloc/Cargo.toml

- remove `jemalloc` from default feature
- change default feature of `tikv` from `tikv_alloc/jemalloc` to `jemalloc`
`--no-default-features` is not recursive. So set `jemalloc` as `tikv_alloc`'s default features will block user from constructing tikv with glibc's malloc or tcmalloc.
```
SYSTEM_ALLOC=1 make release
nm target/release/tikv-server -u |grep malloc
```
You will see `U malloc@@GLIBC_2.2.5`
And `TCMALLOC=1 make release` will not get a compile error now.
No
No

Remove jemalloc from default feature of tikv-alloc

---

components/engine_rocks/src/import.rs
components/engine_traits/src/import.rs
src/raftstore/store/snap/io.rs

The rocks bindings contain a function called ingest_external_file_optimized, which does the same thing as ingest_external_file_cf, but has some logic to prevent blocking writers in certain cases. This patch changes engine_traits and engine_rocks to only expose ingest_external_file_cf, implemented using ingest_external_file_optimized.
Fixes https://github.com/tikv/tikv/issues/6162
cargo check --all
https://github.com/tikv/tikv/issues/6162

Always use the optimized version of ingest_external_file_cf

---

components/backup/src/endpoint.rs
components/tikv_util/src/file.rs

cherry-pick #6177 to release-3.1
Signed-off-by: luancheng <luancheng@pingcap.com>
use start key sha256 to replace raw start key, if we use start key as file name we could meet 
"file name too long" error because some index key are longer than 255 bytes
- Unit test
N/A
N/A

backup: hash backup file name 

---

Cargo.lock
components/backup/src/endpoint.rs
components/backup/src/service.rs
components/backup/src/writer.rs
components/backup/tests/integrations/test_backup.rs
components/external_storage/Cargo.toml
components/external_storage/src/lib.rs
components/external_storage/src/local.rs
components/external_storage/src/noop.rs
src/import/sst_importer.rs
src/import/sst_service.rs
tests/integrations/import/sst_service.rs

- Cherry-picks #6186 and pingcap/kvproto#510 to release-3.1
- Unit test
No
No
pingcap/br#88

*: use kvproto::backup::StorageBackend in create_storage (#6186)

---

src/server/service/diagnostics.rs

This PR implements the `Diagnostics` service server information retrieving interface, which is used to retrieve `server load / hardware / system wide` information. And this PR includes the following information:
- Hardware
- CPU
- NIC
- Memory
- Disk
- Load
- CPU
- Memory
- NIC
- IO
- System info
- sysctl
- process list
Some collection functions are implemented in https://github.com/tikv/sysinfo, which contains more general results. And this PR converts them to our protobuf formation.
- Unit test

 server: collect load/hardware/system information

---

components/engine/src/iterable.rs
components/engine/src/rocks/mod.rs
src/storage/mvcc/reader/reader.rs

Signed-off-by: Jiahao Huang <july2993@gmail.com>
pick #6194 
- Add `hint_min_ts` and `hint_max_ts` for `IterOptions`.
- Implements `TableFilter` `TsFilter` which can skip scanning some unrelate SST files.
- Add test `test_ts_filter` to verify the options works for the iterator.
After this pr, we can add the hint option for maximum or minimum commit ts for the iterator, it helps performance by avoiding scan some SST files totally for the rocksdb engine.
- Unit test
no
#6065

Add maximum and minimum timestamp hint for iterator (#6194)

---

components/txn_types/src/lock.rs
components/txn_types/src/write.rs
src/server/gc_worker.rs
src/server/service/kv.rs
src/storage/errors.rs
src/storage/kv/mod.rs
src/storage/lock_manager.rs
src/storage/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/backward.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/reader/scanner/mod.rs
src/storage/mvcc/reader/scanner/txn_entry.rs
src/storage/mvcc/txn.rs
src/storage/readpool_impl.rs
src/storage/txn/commands.rs
src/storage/txn/mod.rs
src/storage/txn/process.rs
src/storage/txn/sched_pool.rs
src/storage/txn/scheduler.rs
src/storage/txn/store.rs
src/storage/types.rs
tests/benches/coprocessor_executors/util/store.rs

Move `commands` and `ProcessResult` from the root of `storage` to `txn` where they are used. Reorganises imports so that items are imported from where they are declared rather than re-exports, etc.
Extracted from #6203
PTAL @AndreMouche  @sticnarf

txn: reorganise a few items and imports

---

tests/integrations/raftstore/test_merge.rs
tests/integrations/raftstore/test_prevote.rs
tests/integrations/raftstore/test_region_heartbeat.rs

Fix a typo in `cfg(feature)`, using an underscore rather than a hyphen.
PTAL @breeswish @overvenus

tests: fix protobuf_codec typo

---

Cargo.lock
components/tidb_query/Cargo.toml
components/tidb_query/src/codec/mysql/decimal.rs
components/tidb_query/src/lib.rs

PCP https://github.com/tikv/tikv/issues/6282
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>
- Use the same memory layout of Decimal as the TiDB's
- Use `memcpy` to read/write Decimal's chunk
- Unit test
No
No

copr: use memcpy in read/write decimal chunk 

---

Makefile

CI always check jemalloc in another step, so no need to check jemalloc inside Makefile.

Remove jemalloc check from ci_test

---

components/engine_rocks/src/table_properties.rs
components/sst_importer/src/sst_importer.rs
src/import/sst_service.rs

- Create sst writer before download to set table properties.
- Unit test

add table properties for br online restore

---

src/raftstore/store/fsm/apply.rs
src/raftstore/store/fsm/peer.rs
src/raftstore/store/peer.rs
src/raftstore/store/worker/region.rs
tests/failpoints/cases/test_snap.rs

cherry-pick https://github.com/tikv/tikv/pull/6004 to release 3.1
No need to send destroy reply to peerfsm if it will be destroyed synchronously. If not, panic will happen because peerfsm is destroyed twice. 
It rarely happens because a destroy can do synchronously only when an applying snapshot is in the pending state. Also, when applying a snapshot, it is not possible to merge or conf change, the other choices are rare, e.g. peer id in msg is bigger than itself, which needs two conf change.
No
No
https://github.com/tikv/tikv/issues/5365

raftstore/apply: skip notification for synchronous destroy

---

src/raftstore/store/config.rs
src/raftstore/store/fsm/peer.rs
src/raftstore/store/fsm/store.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Allow disable early apply on perf branch. So the performance enhancement can still be utilized without worrying the consistency.
- Improvement
No.
No.

raftstore: allow disable early apply

---

src/server/lock_manager/waiter_manager.rs
src/storage/mvcc/txn.rs

txn: use Commit to clean up pessimistic locks (#6353)

---

components/tidb_query/src/rpn_expr/impl_json.rs

The original code checks if an `Option` is not `None` and `unwrap` it later. It leads to a clippy warning. This PR resolves it.
No
No

fix clippy style warning introduced by #5916

---

components/tidb_query/src/codec/mysql/time/mod.rs

Signed-off-by: TennyZhuang <zty0826@gmail.com>
While type of Time is Date, `fsp_tt` field `0b1110` instead of `0b111x`, so that we can obtain deterministic time memory layout.
Related to pingcap/tidb#14191

copr: Time use deterministic fsp_tt while type == Date

---

src/raftstore/store/fsm/apply.rs
src/raftstore/store/fsm/store.rs
src/raftstore/store/worker/split_check.rs
src/server/lock_manager/config.rs

Properly release resource before the end of a test:
- for `BatchSystem` call `shutdown` before exit the test
- for `Worker` call `stop` before exit the test
- move `Arc<DB>` to the test body, so it can drop properly in the end of the test

tests: properly exit tests

---

Makefile

These days I'm working on merging all tikv build jobs from branches into ONE Jenkins CI job, to make our CI neater and manageable.
Since we have  compiled tikv-server with:
- `make dist_release` on master/release-3.x branches
- `make release` on release-2.x branches,which actually equals with `make dist_release` 
This PR adds `dist_release` to Makefile so we can run `make dist_release` on all branches.

Makefile:add dist_release rule which is same with release for CI

---

Cargo.lock
components/sst_importer/src/sst_importer.rs

Some macOS developers report that tikv cannot build after toolchain upgrade. This PR updates bindgen from 0.51.0 to 0.51.1. Let's see if the problem is fixed.
- Manual test
Just compile it on macOS.
No
No

*: update bindgen to 0.51.1 to fix grpcio build

---

src/import/errors.rs
src/import/kv_service.rs
src/import/metrics.rs
src/import/mod.rs
src/import/service.rs
src/import/sst_importer.rs
src/import/sst_service.rs

cherry-pick #6395 to release-3.1
- Separately describe each logical change (optional)
- Unit test
- No code

sst_importer: add metrics (#6395)

---

.github/pull_request_template.md
components/tidb_query/src/rpn_expr/impl_cast.rs
components/tidb_query/src/rpn_expr/types/test_util.rs
components/tidb_query_codegen/src/rpn_function.rs

Fix cast string to real inconsistent with TiDB, the former implementation does not handle the case in which the input parameter is binary string.
- Unit test

tidb_query: fix cast string to real inconsistent with TiDB

---

src/server/lock_manager/deadlock.rs
src/server/lock_manager/metrics.rs
src/server/lock_manager/mod.rs
src/server/lock_manager/waiter_manager.rs

* Add metrics for wait table which record the counts of locks and txns.
* Add heartbeat of the leader of the deadlock detector.
* Remove unused metric.
Because tests are run concurrently and the metrics are global, I can't test it in the test.
No
https://github.com/pingcap/tidb-ansible/pull/1090
Wait table:
Heartbeat of the leader of deadlock detector:

lock_manager: more metrics

---

src/server/lock_manager/deadlock.rs
src/server/lock_manager/metrics.rs
src/server/lock_manager/mod.rs
src/server/lock_manager/waiter_manager.rs

lock_manager: more metrics (#6392)

---

components/tidb_query/src/rpn_expr/impl_math.rs

Fix log_2args rpn function inconsistent with TiDB. reference: https://github.com/pingcap/tidb/blob/8cbacf0d7c4612e6b5fa89836ca170af11eb81b2/expression/builtin_math.go#L882
MySQL
```
mysql> select log(100,1);
+------------+
| log(100,1) |
+------------+
|          0 |
+------------+
1 row in set (0.00 sec)
mysql> select log(0,1);
+----------+
| log(0,1) |
+----------+
|     NULL |
+----------+
1 row in set, 1 warning (0.00 sec)
mysql> select log(1,1);
+----------+
| log(1,1) |
+----------+
|     NULL |
+----------+
1 row in set, 1 warning (0.00 sec)
mysql> select log(1,10);
+-----------+
| log(1,10) |
+-----------+
|      NULL |
+-----------+
1 row in set, 1 warning (0.00 sec)
```
- Unit test

tidb_query: fix log_2args rpn function inconsistent with tidb

---

components/tidb_query/src/codec/convert.rs

Fix `get_valid_int_prefix` in SELECT statement context. The function `get_valid_int_prefix` has different behavior between SELECT and non-SELECT statement context.
See: https://github.com/pingcap/tidb/blob/d006443194ac535efcc312004fe0c8ace8d79e28/types/convert.go#L373
- Unit test

tidb_query: fix get_valid_int_prefix in SELECT statement context

---

components/tidb_query/src/rpn_expr/impl_encryption.rs
src/raftstore/store/fsm/peer.rs
src/raftstore/store/fsm/store.rs
src/raftstore/store/msg.rs
src/raftstore/store/peer.rs
src/raftstore/store/peer_storage.rs
src/raftstore/store/worker/region.rs
tests/integrations/raftstore/test_conf_change.rs

It speeds up conf change by sending more heartbeats. The heartbeats are
not frequent and the overhead is quite small.
- Bugfix
- Unit test
No.
No
Close #6420.

raftstore: speed up conf change

---

Cargo.toml
components/engine/Cargo.toml
components/pd_client/Cargo.toml
components/sst_importer/Cargo.toml
components/tidb_query/Cargo.toml
components/tikv_util/Cargo.toml

This PR fixed the compilation issue that breaks building submodules.
For example, 
```
> cd components/tikv_utils
> cargo check
```
then it comes out
```
error[E0599]: no method named `generate_files` found for type `&Builder` in the current scope
--> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-build-0.10.0/src/lib.rs:56:14
|
56 |         self.generate_files();
|              ^^^^^^^^^^^^^^ method not found in `&Builder`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0599`.
error: could not compile `protobuf-build`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
- Unit test

Enable default proto feature flag

---

components/tidb_query/src/codec/mysql/time/mod.rs

We should check the date validation first and reset the `hms` fields.
- Unit test

tidb_query: reset the hms after validating date

---

src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/reader/scanner/mod.rs

This PR implements a DeltaScanner with the new ForwardScanner framework. This is used for CDC, and this is a substitution of https://github.com/tikv/tikv/pull/5661
In the current implementation:
* Commits whose commit_ts is in (from_ts, ts] is returned
* Locks whose start_ts is in (0, ts] is returned
* Rollbacks are ignored
* Pessimistic locks are not ignored
Please comment if these behaviors needs to be changed.
- Unit test
No
No

mvcc: Implement DeltaScanner in ForwardScanner framework

---

src/storage/mod.rs
src/storage/txn/commands.rs

When intra-TiKV batch is enabled, the keys in `RawGetRequest`s  are also encoded in turning it to a `PointGetCommand`. However, we shouldn't encode keys if it's a raw get. This PR fixes it.
Fix https://github.com/tikv/tikv/issues/6437
- Unit test
No
No

do not encode key in batch raw get

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Signed-off-by: shirly <AndreMouche@126.com>
bump v3.1.0-beta.1
+ backup 
+ Change the name of the backup file from `start_key` to the hash value of `start_key` to reduce the file name's length for easy reading (https://github.com/tikv/tikv/pull/6198)
+ Disable RocksDB's `force_consistency_checks` check to avoid false positives in the consistency check [#6249](https://github.com/tikv/tikv/pull/6249)
+ Add the incremental backup feature [#6286] (https://github.com/tikv/tikv/pull/6286)
+ sst_importer
+ Fix the issue that the SST file does not have MVCC properties during  restoring [#6378](https://github.com/tikv/tikv/pull/6378)
+ Add the monitoring items such as `tikv_import_download_duration`, `tikv_import_download_bytes`, `tikv_import_ingest_duration`, `tikv_import_ingest_bytes`, and …

bump v3.1.0-beta.1

---

components/tidb_query/src/rpn_expr/impl_arithmetic.rs

The logic of handling overflow while plus two real number inconsistent with TiDB, this PR tries to fix it. See: https://github.com/pingcap/tidb/blob/master/expression/builtin_arithmetic.go#L288:L288
- Unit test

tidb_query: fix RealPlus overflow inconsistent with tidb

---

components/tidb_query/src/codec/mysql/time/mod.rs

Fix coprocessor parse time function, which parses string `00:00:00` to time `2000-00-00 00:00:00`.
- Unit test

tidb_query: fix parse time from string in special case 00:00:00

---

components/tidb_query/src/codec/mysql/duration.rs
components/tidb_query/src/rpn_expr/impl_cast.rs

1. This PR fixes convert an integer to the duration while the integer greater than 10000000000, see: https://github.com/pingcap/tidb/blob/master/types/convert.go#L338:L338
2. This PR delete some duplicated test cases.
- Unit test

tidb_query: fix convert integer to duration

---

components/cdc/src/service.rs
src/server/gc_worker/mod.rs

Previously the lint in our CI is not run because commands are ended with `|| true` for reasons I don't know, which simply ignores these errors. Now the lint error is totally reported and we have to fix these lint errors.
- Unit test

Fix clippy issues

---

cmd/src/server.rs
components/cdc/Cargo.toml
tests/integrations/pd/mock/server.rs

Fix the build when `PROST=1`. This is mostly just setting `--no-default-features` for the cdc crate.
I also addressed a Clippy warning in cmd/server.rs, I'm not sure why that has appeared, but I agree with the Clippy suggestion.
PTAL @breeswish  @overvenus 

Fix Prost build

---

components/test_storage/src/assert_storage.rs
components/test_storage/src/sync_storage.rs
src/server/gc_worker/mod.rs
src/server/service/batch.rs
src/server/service/kv.rs
src/storage/mod.rs
src/storage/txn/commands.rs
src/storage/txn/mod.rs
src/storage/txn/process.rs
src/storage/txn/scheduler.rs
src/storage/types.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/storage/test_raft_storage.rs
tests/integrations/storage/test_storage.rs

Following up from earlier refactoring, this PR moves some command functionality around to make things a bit tidier. This is mostly just to move things closer to where there are used/belong. The most interesting change is moving the decoding of protobufs into `Command` objects from server/service/kv to storage/txn/commands, the motivation is that the kv service should be fairly minimal and not have knowledge of storage internals.
In addition I remove one unused command.
Engineering (engineering change which doesn't change any feature or fix any issue)
PTAL @MyonKeminta @youjiali1995

Txn: move some commands functionality around.

---

Cargo.lock
components/tidb_query/Cargo.toml
components/tidb_query/src/codec/mysql/duration.rs

* Remove `nom`
Remove `nom` and fix some bugs of `Duration` parser which are found out by `randgen` test.
- Unit test

copr: refactor `Duration` parser

---

components/cdc/src/endpoint.rs
components/cdc/src/lib.rs
components/cdc/src/observer.rs

Add a specialized Raft role observer for CDC. It observes Raft role change events and apply events(TODO).
- Unit test
No.
No.

cdc: add raft role observer

---

components/tidb_query/src/aggr_fn/util.rs
components/tidb_query/src/rpn_expr/impl_cast.rs
components/tidb_query/src/rpn_expr/types/expr.rs

This PR fixes convert a binary literal to int (the previous implementation ignores the special case and will cause inconsistent with TiDB).
- Unit test

tidb_query: fix CAST binary string as int

---

cmd/src/server.rs
components/tidb_query/src/rpn_expr/impl_arithmetic.rs
components/tikv_util/src/worker/future.rs
components/tikv_util/src/worker/mod.rs
src/raftstore/store/worker/pd.rs
src/server/status_server.rs

This pr add support for getting the current using config (i.e after dynamic changed) through status server.
- Unit test
- Manual test (`curl $status_addr/config`)
No
No

config: get the current using config through status config

---

components/tidb_query/src/codec/mysql/duration.rs
components/tidb_query/src/rpn_expr/impl_cast.rs

This PR fixes the issue that the result inconsistent with TiDB in parsing `Duration` from a string. In the TiDB implementation, parse from string to duration will try to parse to time and convert to duration if the string cannot parse to duration directly.
- Unit test

fix inconsistent with tidb in parsing Duration from String

---

README.md

Fixes https://github.com/tikv/website/issues/116 by adding big links to our website, docs, and chat!

Add prominent docs links to README.

---

tests/failpoints/cases/test_replica_read.rs

Fix unstable test.
- Unit test
No.
No.
https://github.com/tikv/tikv/issues/6083

fix unstable test_replica_read::test_read_after_cleanup_range_for_snap

---

components/txn_types/src/lib.rs
components/txn_types/src/lock.rs
components/txn_types/src/write.rs
src/storage/mvcc/mod.rs
src/storage/txn/store.rs
tests/failpoints/cases/test_storage.rs

Signed-off-by: Steven Gu asongala@163.com
Tries to fix Issue #6467. Reference PR #5979 to fix `tnx_types::Error`.
- Replaces original Error with ErrorInner.
- Defines a new Error as `pub struct Error(pub Box<ErrorInner>)`.
- Fixes the all compiling errors.
- Unit test
No.
No.
Issue #6467 and PR #5979

tnx_types: Reduce Error Size

---

Cargo.lock

Builds are failing due to a (presumably) unintentional downgrade of bindgen.
See d648cd32528745dbdb09bb0583dd7a7b24f06453
This PR reverts that change.
PTAL @yiwu-arbug @siddontang 
Build on Mac OS
no
no

build: fix builds on Mac OS

---

components/backup/src/endpoint.rs
components/test_storage/src/sync_storage.rs
src/raftstore/coprocessor/mod.rs
src/raftstore/coprocessor/region_info_accessor.rs
src/server/gc_worker/mod.rs
src/storage/kv/mod.rs
src/storage/mod.rs
tests/integrations/storage/test_seek_region.rs

`RegionInfoProvider` should be defined in raftstore instead of storage.
- Unit test
No.
No

storage, raftstore: move RegionInfoProvider into raftstore

---

Cargo.lock
components/backup/src/writer.rs
components/external_storage/Cargo.toml
components/external_storage/examples/scli.rs
components/external_storage/src/lib.rs
components/external_storage/src/local.rs
components/external_storage/src/noop.rs
components/external_storage/src/s3.rs
components/tikv_util/src/file.rs

Cherry-pick #6209 to release-3.1, to support backup/restore via BR on S3.
* cargo check
no (?)
no
#6209.

[3.1] external_storage: add S3 support (#6209)

---

src/raftstore/store/peer.rs

raft-rs forbids setting term for MsgTransferLeader, so use log term
instead.
- Bugfix
- Manual test
No.
No.

pre-transfer-leader: use log term instead of term

---

Cargo.lock
src/server/node.rs

This PR is used to resolve the issue https://github.com/pingcap/tidb/issues/14707, and first report the start timestamp to PD. PD will synchronize the start timestamp to TiDB (see: https://github.com/pingcap/pd/pull/2116) 
- Unit test
```
mysql> select * from cluster_info;
+------+-----------------+-----------------+----------------------------------------------+------------------------------------------+---------------------------+-----------------+
| TYPE | INSTANCE        | STATUS_ADDRESS  | VERSION …
```

server: report the start timestamp of current node to PD

---

Cargo.lock
components/engine/Cargo.toml

Cherry-picking rust-rocksdb/rocksdb/titan changes. Also update rust-rocksdb url.
* rust-rocksdb
```
7ec1dbd 2020-02-06 yiwu@pingcap.com     [tikv-3.x] Update to latest Titan and fix submodule url (#433)
ad9f3b6 2020-02-06 kennytm@gmail.com    Mark SequentialFile as Send (#424) (#432)
8116bd6 2020-02-06 sre-bot@pingcap.com  rocksdb: Cherry-pick recent rocksdb fixes from upstream into tikv-3.x branch (#431)
dc92697 2020-01-17 zbk602423539@gmail.. update titan (#423)
a5c19ae 2020-01-17 sre-bot@pingcap.com  rocksdb: Add user priority (#422)
```
* rocksdb
```
b5b81f993 2020-02-04 anand76@devvm1373... Force a new manifest file if append to current one fails (#6331)
50f6b2473 2020-02-04 siying.d@fb.com      Bug when multiple files at one level contains the same smallest key (#6285)
aeabee9a8 …
```

Update rocksdb and titan. Update rust-rocksdb url

---

etc/config-template.toml

This PR adds unified read pool configs to config template. These configs are already supported by TiKV.
- No code
No
The corresponding tidb-ansible PR: https://github.com/pingcap/tidb-ansible/pull/1112

add unified read pool configs to config template

---

Cargo.lock
src/pd/mod.rs
src/server/resolve.rs

We plan to provide a heterogeneous engine with tikv, which may need to use different addresses to provide kv and raft services. Now kvproto has an optional `peer_address` to support this. 
The corresponding tikv modification is: use `peer_address` when connecting other nodes to send raft messages. (for backward compatibility: if `peer_address` is not set, `address` is still used)
- Unit test
No
No
cherry-pick: #5569

raft_client: connect to other stores using peer_address (#5569)

---

cmd/src/bin/tikv-server.rs
cmd/src/setup.rs
src/config.rs
src/server/service/debug.rs

This pr skip some config, these config on the rocksdb config struct are not support dynamic change because these config neither real rocksdb config (can not recognize by rocksdb) or not support dynamic change by rocksdb. This pr also rename `dynamic-config` to `enable-dynamic-config`
No
No
No

config: skip some rocksdb config

---

src/raftstore/store/fsm/peer.rs
src/raftstore/store/fsm/store.rs
src/raftstore/store/local_metrics.rs
src/raftstore/store/peer.rs

Batch small RaftMessage of a region into one Message. We hope which change could reduce 
the number of message in module `raft_store`
- No code
No
No

batch multiple write request into an entry

---

Cargo.lock
Cargo.toml
src/server/node.rs

Signed-off-by: mapleFU <1506118561@qq.com>
This pr is related to [kvproto#551](https://github.com/pingcap/kvproto/pull/551). TiKV need to support upload it's binary path to PD. 
- No code
No
* [kvproto#551](https://github.com/pingcap/kvproto/pull/551)

Server: adding binary_path to store for tikv

---

components/match_template/src/lib.rs
components/tidb_query/src/batch/executors/fast_hash_aggr_executor.rs
components/tidb_query/src/codec/batch/lazy_column.rs
components/tidb_query/src/codec/data_type/mod.rs
components/tidb_query/src/codec/data_type/vector.rs
components/tidb_query/src/expr_util/collation/mod.rs
components/tidb_query/src/lib.rs
components/tidb_query/src/macros.rs
components/tidb_query/src/rpn_expr/mod.rs

1. Add a new pattern to proc macro `match_template`.
For example,
```rust
match_template! {
T = [Foo, Bar => Baz],
match Foo {
EvalType::T => { panic!("{}", EvalType::T); },
}
}
```
generates
```rust
match Foo {
EvalType::Foo => { panic!("{}", EvalType::Foo); },
EvalType::Bar => { panic!("{}", EvalType::Baz); },
}
```
2. Add a new decl macro `match_template_collator!()` which maps collation variant to
a concrete `Collator` type, and it's used as
```rust
fn map_string_compare_sig<Cmp: CmpOp>(ret_field_type: &FieldType) -> RpnFnMeta {
match_template_collator! {
TT, match ret_field_type.as_accessor().collation() {
Collation::TT => compare_fn_meta::<StringComparer<TT, Cmp>>()
}
}
}
```
3. For consistency, make `match_template_evaluable!()` and …

copr: implement macro match_template_collator

---

components/raftstore/src/store/fsm/apply.rs
tests/failpoints/cases/test_merge.rs

Set `wait_merge_state` to none after resuming pending state.
Otherwise, it may cause panic when executing the next commit merge command. 
No.
No.

raftstore: set wait_merge_state to none after resuming pending state

---

etc/config-template.toml
src/config.rs

To encourage people to use the new thread pool for all read requests, this PR modifies the `unify-read-pool` config to `true`.
Enabling the new thread pool at 4.0 pre-GA stage by default helps us find bugs or regressions. The feedbacks will decide whether it can be enabled by default when 4.0 GA is released.
Currently the new thread pool has some functions missing, but PRs are coming with 4.0.0-beta.1 release.
- No code
Yes. I will do it later when pushing the related docs.
Yes. I will also do it later.

*: unify read pools by default

---

components/tidb_query/src/codec/mysql/duration.rs

Fix some edge conditions that causes overflow in `Duration` construction
- Unit test

copr: Fix fuzz error in `codec::Duration`

---

Cargo.lock
Cargo.toml
components/tikv_util/src/lib.rs
components/tikv_util/src/logger/file_log.rs
src/config.rs
src/server/config.rs
src/server/service/diagnostics.rs
src/storage/config.rs

Running the test suite on an AMD processor with Linux kernel 5.3 leads to a few errors.
This PR depends on changes to our fork of sysinfo, it should not land before [this PR](https://github.com/tikv/sysinfo/pull/1) and updating Cargo.toml.
This PR contains a number of small changes:
* update sysinfo so that we can correctly read `/sys/block/.../stat` files (format is changed in modern Linux kernels)
* read the chip vendor_id from (the updated) sysinfo, and where this indicates an AMD chip, skip some parts of a test (due to a different data layout returned by CPUID).
* mark some code in docs as `ignore` so they are ignored by doctests
* change `test_reserve_space_for_recover` to not rely on space available on a disk. Because other processes might write to or delete from the disk, this test …

*: fix some test errors on AMD and/or modern Linux kernels

---

Cargo.lock
Makefile
fuzz/cli.rs
fuzz/targets/Cargo.toml

Fixes a Cargo error and adds a new make target, fuzz.
There is a bit of complexity passing the right features to dependencies when fuzzing. This PR fixes that by adding dependencies to fuzz-targets. I also add a make target to make fuzzing more convenient.
`make test` and `FUZZ_TARGET=fuzz_codec_bytes make test`
no
no
Fixes #6591
PTAL @zhouqiang-cl @breeswish

Make fuzzing work.

---

src/storage/mvcc/reader/scanner/forward.rs

Break loop when met delete version during handle one write key
Backup scanner should skip one key already has delete version, otherwise it will backup the version before delete version.
- Unit test
N/A

backup: break one key scan when met delete version

---

Cargo.lock
components/tidb_query/src/expr/builtin_string.rs
components/tidb_query/src/expr/scalar_function.rs
components/tidb_query/src/rpn_expr/impl_string.rs
components/tidb_query/src/rpn_expr/mod.rs

Signed-off-by: wangwangwar <wangwangwar@gmail.com>
Separate expression signatuer `Upper` to `Upper` and `UpperUtf8`.
Improvement
- Unit test
No. It should not change the behavior.
No

copr: separate expression signature `Upper` to `Upper` and `UpperUtf8`

---

Cargo.lock
components/tidb_query/Cargo.toml
components/tidb_query/src/batch/runner.rs
components/tidb_query/src/error.rs
components/tidb_query/src/metrics.rs
src/coprocessor/dag/mod.rs
src/coprocessor/endpoint.rs
src/coprocessor/error.rs
src/coprocessor/metrics.rs
src/coprocessor/mod.rs
tests/benches/coprocessor_executors/util/mod.rs

In #6582, a request in execution which fails to get a semaphore permit can be cancelled and rerun until a semaphore permit is acquired. However, the problem is that the coprocessor executors have inner state, so it is incorrect to rerun the request handler.
This PR changes the mechanism. The semaphore is passed into the runner. If the execution limit exceeds, the runner blocks itself through the semaphore. Now, the handler is not used more than once.
- Unit test
- Manual test
I reproduced the bug according to #6676 in master. In this fixed version, the problem does not exist.
Need to add this PR to the unified thread pool changelog as well.
No
Should fix #6676

cop: avoid handling requests multiple times

---

src/server/service/diagnostics.rs

This PR adjusts the `end_time` field of `SearchLogRequest` if it is zero.
- Unit test

server: adjust log search end time to i64::MAX if end_time unset

---

components/batch-system/Cargo.toml

Signed-off-by: Aylei <rayingecho@gmail.com>
close #6693 
Specify benchmark target path in `components/batch-system/Cargo.toml` to satisfy cargo when building dependencies during `make docker`.
- Manual test, `make docker` now works
No.
No.
#6693

scripts: fix make docker

---

tests/integrations/raftstore/test_service.rs

It's reported that the `test_physical_scan_lock` in integration tests fails when running test locally. It's because of scanning from wrong key in the test code (scanning from `k3` while the data set is `k10`, `k11`, ..., and it means to scan from `k13`). This makes the test surely to fail, however the CI passed. It's needed to check whether the CI is abnormal.
No
No

tests: Fix failing test_physical_scan_lock

---

src/raftstore/store/fsm/apply.rs
tests/failpoints/cases/test_conf_change.rs
tests/failpoints/cases/test_merge.rs

cherry pick https://github.com/tikv/tikv/pull/6692 to release-3.1
No.
No.

raftstore: destroy apply fsm when pending_remove flag is set during resuming

---

cmd/src/server.rs

Make welcome message be the first message when starting. fix #6702 

server: print welcome msg first when starting

---

components/backup/src/writer.rs
src/storage/txn/store.rs

In incremental backup, delete records will be output and its short value of write cf is empty.
This PR fixes panic after meeting empty short value when updating SST info.
- Unit test
No.
No.

backup: fix panic after meeting empty short value

---

components/backup/src/writer.rs
src/storage/txn/store.rs

Pick https://github.com/tikv/tikv/pull/6718
- Unit test
No.
No.

[Cherry-pick] backup: fix panic after meeting empty short value

---

components/raftstore/src/store/peer.rs
tests/integrations/raftstore/test_hibernate.rs

#6672 breaks hibernate regions by not waking leader up on proposal accidentally. This PR fixes by setting all the missing flags.
- Bugfix
No.
No.
#6672

raftstore/hibernate: wake up on proposal

---

components/raftstore/src/store/worker/region.rs

I've changed the occurrences of `tikv_util::ThreadPool` to ThreadPool provided by `yatp` crate. The only place I was able to find the use of `tikv_util::ThreadPool` was in https://github.com/tikv/tikv/blob/master/components/raftstore/src/store/worker/region.rs. The new code did pass both the unit tests that were present in the same file.
This was done in an attempt to fix #5608 
- Unit test
No
No

Replace the usage of `tikv_util::ThreadPool` with ThreadPool from `yatp` crate

---

README.md

The link for `Try TiKV and TiDB` under [Try TiKV](https://github.com/tikv/tikv#testing-deployment) in  README leads to `404`.
Updated the URL to point to [this](https://tikv.org/docs/3.0/tasks/try/) instead.
- No code
No
No
#6688

Fix broken URL for "Try TiKV and TiDB"

---

components/tidb_query/src/lib.rs
components/tidb_query/src/rpn_expr/types/expr_eval.rs

Eliminate Arc<identical_logical_row> in coprocessor expression.
- Unit test

tidb_query: eliminate Arc<identical_logical_row>

---

components/tidb_query/src/expr/builtin_string.rs

By changing `Cow::Owned(b"".to_vec())` to `Cow::Borrowed(b"")`, we can remove
an unnecessary allocation incurred by `.to_vec()`.
- Engineering
- Unit test
It has not been benchmarked yet. But I don't think there will be an observable difference in performance.
No.
No.

copr/string: remove unnecessary allocation

---

components/backup/src/writer.rs
tests/integrations/raftstore/test_replica_read.rs

TiKV 3.x disables hibernate regions by default.😢
Fix the test by enabling hibernate regions. 
- Unit test
Close #6974

raftstore, backup: fix test_read_hibernated_region & test_writer

---

components/cdc/tests/integrations/mod.rs
components/cdc/tests/integrations/test_cdc.rs

Check failpoints feature for failpoint tests.
Since `test_setup_fail` would hang after adding `-Zprofile` to `RUSTFLAGS`.
- Unit test

cdc: check failpoints feature for failpoint tests

---

Cargo.lock
Cargo.toml
src/raftstore/store/peer_storage.rs

Update raft to introduce aggressive flow control. See also tikv/raft-rs#340 and #6670.
Should be merged after #6993 is ported to release-3.0.
- Bugfix
Yes.
No.
#6670, tikv/raft-rs#340.

*: update raft to include aggressive flow control

---

Cargo.lock
components/external_storage/src/s3.rs
components/tikv_util/Cargo.toml

Cherry-pick #6675 to release-3.1.
- Unit test

tikv_util: fix s3 writer always creating zeroes (#6675)

---

Cargo.lock
components/backup/src/writer.rs
components/backup/tests/integrations/test_backup.rs

Cherry-pick #6664 to release-3.1.
- Unit test
No
No
pingcap/br#163

 backup: do fill in the file size of each SST file in the response (#6664)

---

src/server/service/kv.rs

Fix the wrong metric name of handling batch batch_rollback.
- No code
No. It's trivial.
No

kv_service: fix the wrong metric name of handling batch batch_rollback

---

.github/workflows/assign_failed_test_project.yml

We have created a daily report job to find tests on our CI that fails occasionnally and auto create issures for them. This github workflow will auto assign these issues to `Solid Tests` project so we can manage them easier.
Similar workflow for tidb is [here](https://github.com/pingcap/tidb/blob/master/.github/workflows/assign_project.yml)

test: add github workflow to auto-assign failed test issue to solid tests project

---

Cargo.lock
components/external_storage/Cargo.toml
components/external_storage/examples/scli.rs

According to RUSTSEC-2018-0006, we should not use yaml-rust < 0.4.1,
which is depended by clap. So I rewrite the usage using structopt.
After this PR we can enable audit check in CI again.
Close #7004.
- Bugfix
- Manual test
No.
No.

extern_storage: replace clap yaml with structopt

---

.github/workflows/assign_failed_test_project.yml

In #7102 I add a Github workflow to auto-assign issues for failed test cases in our CI to project `Solid Tests`. Because these issues were created with labels, so I select `created` as trigger event. But after I manually tested in my private repo, It seems Github only recognize `labeled` event for labels even if issues were created with labels.
- Bugfix (fix #7102 )
- Manual test
- No code

test:  fix auto-assign workflow trigger event

---

components/external_storage/examples/scli.rs
components/external_storage/src/s3.rs

Fix "not currently running on the Tokio runtime" crash when read from or write to S3. The problem seems to be rusoto using tokio under the hood, which require use `tokio::runtime::Runtime::block_on` instead of `futures::executor::block_on`.
Also have minor update to the scli tool.
Bugfix
Build the scli tool in example. Tested locally with the following commands:
```
./scli -b yiwu-test -c ~/.aws/credentials -f local.txt -s S3 -n remote.txt -p test -r us-west-2 -e s3.amazonaws.com save
./scli -b yiwu-test -c ~/.aws/credentials -f local_copy.txt -s S3 -n remote.txt -p test -r us-east-1 -e s3.amazonaws.com load
```
No
No

external_storage: fix crash when using s3

---

src/server/service/diagnostics.rs

Signed-off-by: crazycs520 <crazycs520@gmail.com>
Before this PR, memory info unit is KB in hardware info and load info.
This PR change the memory info unit to byte in hardware info and load info, just keep consistent with the disk unit.
- No code
NO
before
```sql
mysql>select * from `CLUSTER_HARDWARE` where device_type="memory"
+------+-----------------+-------------+-------------+----------+-------------+
| TYPE | INSTANCE        | DEVICE_TYPE | DEVICE_NAME | NAME     | VALUE       |
+------+-----------------+-------------+-------------+----------+-------------+
| tidb | 127.0.0.1:10080 | memory      | memory      | capacity | 51539607552 |
| pd   | 127.0.0.1:2379  | memory      | memory      | capacity | …
```

dianostics: change the memory unit to keep consistant with disk

---

Cargo.lock
components/backup/tests/integrations/test_backup.rs
components/external_storage/Cargo.toml
components/external_storage/examples/scli.rs
components/external_storage/src/lib.rs
components/external_storage/src/local.rs
components/external_storage/src/noop.rs
components/external_storage/src/s3.rs
components/external_storage/src/util.rs
components/sst_importer/src/sst_importer.rs
components/tikv_util/src/file.rs

In #7117, the `rusoto` package (for using AWS S3) was upgraded to 0.43.0, which requires Tokio to upgrade from 0.1 to 0.2. This is a major breaking change of Tokio. During adoption of the new API, it seems the writer is broken, in that only the first 512 KB is written out. This has caused BR integration tests to fail in the last few days.
In this PR, we have completely removed the `FramedRead` adapter (which performs the (futures_io AsyncRead → Tokio 0.2 AsyncRead → TryStream of Bytes) conversion), and rather implement an `AsyncReadAsSyncStreamOfBytes` to directly produce a TryStream of Bytes under our control.
This PR also refactored `ExternalStorage::read()` to return a `Box<dyn AsyncRead>` instead of `io::Result<Box<dyn AsyncRead>>`. This allows the S3 reader to be truly async.
- …

external_storage: fix sst writer error with s3 storage, plus refactoring

---

components/backup/src/endpoint.rs

Backup is designed with concurrency in mind, TiKV allows running backup in multi-threads. However recent change makes workers hold a lock during the entire backup, as a result, workers are blocked by each other.
Run `br backup full -s "local://tmp"`
No.
No.

backup: unblock worker by releasing lock as soon as possible

---

components/backup/src/endpoint.rs
tests/integrations/raftstore/test_lease_read.rs

Fix unstable test:
fix #7082 test_thread_pool_shutdown_when_idle: this test failed because the thread pool did not shutdown immediately after the configured time, but the test did take in count of the task process time, this pr fix it by first wait the task finish and have a more relax check.
fix #5163 test_thread_pool_shutdown_when_idle: this test failed because can not transfer leader, which happened because read index may propose an empty entry and the transferee did not have new enough log + leader can not receive `MsgAppendResponse` because filter, this pr fix it by skip `MsgAppendResponse` in filter.
- Unit test
No
No

tests: Fix unstable tests test_read_index_when_transfer_leader_1 and test_thread_pool_shutdown_when_idle

---

components/cdc/src/endpoint.rs
components/pd_client/src/client.rs
components/pd_client/src/lib.rs
components/test_raftstore/src/pd.rs

Issue Number: close https://github.com/tikv/tikv/issues/7124
Problem Summary: CDC endpoint creates a tick for getting tso periodically by using pd client. When the connection to pd is broken, it will try to reconnect and wait for the response, but the action for reconnecting is at the same thread, then this thread will be blocked forever.
Create a new thread for retrying to reconnect and waiting for the response.
Tests 
I don't see any way to verify it by the unit test.
Fix the bug that causes the pd client is blocked forever when the pd leader is restarted or transferred.

cdc: fix pd client was blocked by get_tso

---

components/tidb_query_datatype/src/codec/data_type/scalar.rs
components/tidb_query_vec_executors/src/fast_hash_aggr_executor.rs
components/tidb_query_vec_executors/src/slow_hash_aggr_executor.rs
components/tidb_query_vec_executors/src/stream_aggr_executor.rs

close pingcap/tidb#15488
At pingcap/tidb#15541, @tangenta attempted to eliminate the GROUP BY expression to resolve the problem, as I indicated in the issue. However, we later found that the behaviors are unexpected when the table is empty.
So, I chose to let tikv copr support GROUP BY a constant now.
- Remove the check for Scalar being GROUP BY expression.
- Support Scalar(constant) as a group key.
Tests 
- Unit test

tidb_query: supports group by a constant

---

components/test_raftstore/src/common-test.toml
etc/config-template.toml
src/server/lock_manager/config.rs
src/server/lock_manager/deadlock.rs
src/server/lock_manager/mod.rs
src/server/lock_manager/waiter_manager.rs
tests/integrations/config/dynamic/pessimistic_txn.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

UCP #7143 
Signed-off-by: ssebo <ssebo.zzz@gmail.com>
change wake-up-delay-duration and wait-for-lock-timeout from u64 to ReadableDuration
CI
no
https://github.com/pingcap/tidb-ansible/pull/1216
https://github.com/tikv/tikv/issues/7143

ucp 7143 wait-for-lock-timeout and wake-up-delay-duration readable

---

Cargo.lock

Issue Number: closes #7258 
Problem Summary: #6981 updates yatp to a version that would almost always skip rescheduling. It makes the unified read pool unable to schedule among big and small requests.
And this upgrading also fixes a deadlock bug in yatp. See https://github.com/tikv/yatp/pull/33 for the deadlock bug detail.
Update yatp to the latest version which includes two bugfix PRs https://github.com/tikv/yatp/pull/34 and https://github.com/tikv/yatp/pull/33.
Tests
Run big and small queries and I can see the unified read pool can work again.
The deadlock bug is hard to reproduce. It's only covered in the unit test added in https://github.com/tikv/yatp/pull/33.
Side effects
- Performance …

*: update yatp to fix #7258

---

MAINTAINERS.md

Remove the Senior Maintainer role as it has not been defined in the governance.
https://github.com/tikv/community/pull/19
Tests 
- Unit test
- No code
Side effects

MAINTAINER: remove senior maintainer role

---

Cargo.lock
cmd/Cargo.toml
cmd/src/bin/tikv-ctl.rs
cmd/src/server.rs
components/encryption/src/manager/mod.rs
components/engine_rocks/src/encryption.rs

Small refactor to store `encryption::DataKeyManager` in `TiKVServer`. The key manager can later be shared by snapshot and backup logic to take care of encryptions.
small refactor.
Tests 
manual test run tikv with encryption enabled and with go-ycsb workload

Store encryption_key_manager in TiKVServer

---

Cargo.lock
src/coprocessor/dag/expr/builtin_op.rs
src/coprocessor/dag/expr/scalar_function.rs

cherry-pick https://github.com/tikv/tikv/pull/5005
TiPB change: https://github.com/pingcap/tipb/pull/149
TiDB change: https://github.com/pingcap/tidb/pull/15915

coprocessor: differentiate real/int/decimal for `not` expression (#5005)

---

cmd/src/server.rs
components/engine_panic/src/cf_options.rs
components/engine_rocks/src/cf_options.rs
components/engine_traits/src/cf_options.rs
components/test_raftstore/src/server.rs
src/config.rs
src/import/sst_service.rs
src/server/gc_worker/gc_worker.rs

Part of https://github.com/tikv/tikv/issues/6402
Replace uses of engine::DB with engine_rocks::RocksEngine.
cargo test --all --no-run

Replace uses of DB with RocksEngine in tikv

---

src/storage/mvcc/reader/reader.rs
src/storage/mvcc/txn.rs

Closes https://github.com/tikv/tikv/issues/7364
`MvccTxn::check_txn_status_missing_lock()` now writes protected on rollback.
Tests 
- Unit test

txn: write protected rollback when cleanup with missing lock

---

src/storage/mvcc/txn.rs

cherry-pick #7365 to release-3.0
---
Closes https://github.com/tikv/tikv/issues/7364
`MvccTxn::check_txn_status_missing_lock()` now writes protected on rollback.
Tests 
- Unit test
Fix the bug that a repeated "resolve lock" request may break the atomicity of transactions.

txn: write protected rollback when cleanup with missing lock (#7365)

---

components/tidb_query/src/batch/executors/fast_hash_aggr_executor.rs
components/tidb_query/src/batch/executors/slow_hash_aggr_executor.rs
components/tidb_query/src/batch/executors/stream_aggr_executor.rs
components/tidb_query/src/codec/data_type/scalar.rs

Solve CI errors of PRs which cherry-pick to release 4.0
cherry-pick #7238
Tests 
- Unit test
- Fixed a bug that SQL may be failed with "group by constant" error

cherry-pick 4.0: tidb_query supports group by a constant

---

components/tikv_util/src/future_pool/mod.rs

Issue Number: close #7393 
Problem Summary: After #7348, tikv_util::future_pool::test_tick fails occasionally. It's because the handle returned by `spawned_handle` is ready before `on_tick` is executed.
What's Changed: Use `recv_timeout` instead of the original `try_recv` because the `on_tick` function may be executed after trying to fetch values from the channel.
Tests 
- Unit test
I run `repeat 100 { cargo test --package tikv_util --lib -- future_pool::tests::test_tick --exact & }` and all succeed.

util: stablize test tikv_util::future_pool::test_tick

---

components/sst_importer/src/sst_importer.rs

Issue Number: close https://github.com/pingcap/br/issues/163
* when we perform rewrite in download sst, the length of sstMeta will change, so it will cause panic in next vaildation.
This PR skip validation before ingest sst, so we can avoid panic since file length doesn't match.
Tests 
- Unit test
Side effects

sst_importer: skip validation in ingest temporary

---

src/raftstore/store/peer.rs
src/raftstore/store/read_queue.rs
tests/integrations/raftstore/test_replica_read.rs

cherry-pick https://github.com/tikv/tikv/pull/7372 to release 3.1
TiKV may panic in raft-rs because of tikv/raft-rs#346 and the subtle hack code.
Some details in https://github.com/tikv/tikv/issues/7353#issuecomment-608247067
Tests 
Side effects
No

raftstore: set term in read index response

---

Cargo.lock
components/cdc/Cargo.toml
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/lib.rs
components/cdc/src/metrics.rs
components/cdc/src/observer.rs
components/cdc/tests/failpoints/mod.rs
components/cdc/tests/failpoints/test_observe.rs
components/cdc/tests/failpoints/test_register.rs
components/cdc/tests/failpoints/test_resolve.rs
components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs
components/raftstore/src/coprocessor/dispatcher.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/mod.rs
components/resolved_ts/Cargo.toml
components/resolved_ts/src/lib.rs

Issue Number: close https://github.com/tikv/tikv/issues/7325
Problem Summary: TiKV may OOM or panic while running cdc.
* Remove the scan cache for reducing the memory usage
* Add ObserveID to region `Delegate`, `Initializer`, `CmdBatch` for check stale observe cmd and stale resolver
* Add more metrics
- Unit test
N/A

[cherry-pick] cdc: remove scan cache & add observe id (#7278)

---

cmd/src/server.rs
components/cdc/src/endpoint.rs
components/cdc/src/metrics.rs
components/cdc/src/observer.rs
components/cdc/tests/integrations/test_cdc.rs
components/raftstore/src/store/fsm/apply.rs

1. cdc: deregister region only when ObserveID matches
2. cdc: add a metric that record captured region number 
3. cdc: support cancel incremental scan
Tests 
- Unit test
Fix deregister ABA problem and support cancel incremental scan.

cdc: fix deregister ABA problem and support cancel incremental scan 

---

src/server/service/diagnostics.rs

Signed-off-by: crazycs520 <crazycs520@gmail.com>
before
```sql
mysql>select * from `CLUSTER_HARDWARE` where device_type="disk" and type='tikv' and name like "%percent%"
+------+-----------------+-------------+-------------+--------------+--------+
| TYPE | INSTANCE        | DEVICE_TYPE | DEVICE_NAME | NAME         | VALUE  |
+------+-----------------+-------------+-------------+--------------+--------+
| tikv | 127.0.0.1:20160 | disk        | mac         | free-percent | 0.26   |
| tikv | 127.0.0.1:20160 | disk        | mac         | used-percent | 0.26   | -- It's wrong.
+------+-----------------+-------------+-------------+--------------+--------+
```
Tests 
- No code
Side effects
- No

diagnose: fix disk used percent information

---

cmd/src/server.rs

To allow multiple users create tikv and get rid of permission problem.
close #7462 
Add UID for each TIKV_LOCK_FILES directory
- Need to cherry-pick to the release 4.0
- Unit test
Side effects
No

cmd: add uid flag for TIKV_LOCK_FILES

---

src/server/service/kv.rs
src/server/service/mod.rs
tests/integrations/server/kv_service.rs

Issue Number: close #7493 
When request's delay is 0, it's possible that tokio-timer calls notify directly inside notify, which leads to deadlock. This PR fixes the issue by returning the result directly when delay is small.
To prevent all these problems, it's a good practice to avoid poll in place. In place polling is source of most the lock issues. Even only polling once can still lead to deadlock, see tikv/grpc-rs#395. The permanent fix for similar issue is removing `BatchCommandsNotify` and find a better way to reduce context switch.
Tests 
- Unit test
kv_service: fix deadlock when batch empty requests with zero delay is handled

kv_service: fix batch empty request deadlock

---

src/config.rs
src/server/raft_client.rs

Calculate batch raft message size more approximately. Try best to avoid error like:
```
["RPC batch_raft fail"] [err="Some(RpcFailure(RpcStatus { status: ResourceExhausted, details: Some(\"Sent message larger than max (10525503 vs. 10485760)\") }))"] [sink_err=Some(RemoteStopped)] [to_addr=10.240.97.140:20160]
```
Enlarge the batch buff from 4k to 64k, and consider size of `RaftMessage` itself.
Tests 
- Unit test
Side effects

raft_client: calculate batch size more approximately

---

components/tidb_query_datatype/src/codec/data_type/mod.rs

Signed-off-by: zhongzc zhongzc_arch@outlook.com
Fix compatibility with MySQL.
See: pingcap/tidb#16014
Bytes is converted to an `f64` type instead of an int type to determine the bool value.

tidb_query: fix converting bytes to bool

---

src/server/raft_client.rs

Signed-off-by: qupeng qupeng@pingcap.com
Cherry pick #7522.
Enlarge batch raft message buffer to avoid too long messages

raft_client: enlarge batch raft message buffer (#7522)

---

components/sst_importer/src/util.rs

Issue Number: 
Problem Summary: On macOS `sst_importer/util.rs` cannot be built due to an unnecessary `?` (which was cfg'ed out on Linux which is why it was not caught by CI).
The `#[cfg]` causing this error is too restrictive. Relaxing it from Linux-only to Unix-only, so macOS and Linux share the same code.
Furthermore, removed the separate non-Unix implementation to share as much code as possible to reduce copy-and-paste typo.
Tests 
- Unit test
Side effects
N/A

sst_importer: enable the hard link check on all Unix systems

---

src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs
src/storage/txn/process.rs

cherry-pick #7494 to release-3.0
---
Issue Number: close #7490 
Problem Summary: rollback calls cleanup and it writes protected rollback record for all non-exsitent keys which may causes performance regression in heavy contention workload with optimistic transaction. See #7435
What's Changed: Only cleanup or check_txn_status need to write the protected rollback record.
Tests 
- Unit test
Do not protect rollback records written by BatchRollback to improve performance when there are many write conflicts in optimistic transactions.

txn: don't protect rollback for BatchRollback

---

benches/misc/storage/key.rs
benches/misc/storage/mod.rs
src/server/lock_manager/mod.rs
src/storage/lock_manager/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs
src/storage/txn/process.rs
src/storage/types.rs

cherry-pick #7379 to release-3.0
---
TiKV will wake up waiters as long as it receives requests that may release locks, e.g., `pessimistic_rollback`, `rollback`, `commit`. If a request doesn't release locks, typically the lock doesn't exist, it needn't wake up waiters.
In TiDB, if a pessimistic DML meets write conflict, it will use `pessimistic_rollback` to clean up all locks it needs to lock in this DML and then retry the DML. If a transaction is waked up and there are other transactions waiting for the lock, these transactions will be waked up by `pessimistic_rollback` one by one. It dramatically affects performance and results in useless retry.
Only wake up waiters when locks are indeed released and small …

txn: only wake up waiters when locks are indeed released (#7379)

---

components/encryption/src/manager/mod.rs
components/encryption/src/master_key/mem.rs
components/encryption/src/master_key/metadata.rs
components/encryption/src/master_key/mod.rs

Fixing two issues with encryption:
1. TiKV will crash with protobuf error when disable encryption using the following config
```
[encryption]
data-encryption-method: plaintext
[encryption.previous-master-key]
{...master key config here}
```
The problem is that when TiKV initialize encryption and try to read `key_dict`, in the first round plaintext backend is used, since no master key is specified. Plaintext backend cannot tell if the content feed to it should plaintext or not, and return `WrongMasterKey` error properly.
2. TiKV will crash when change encryption method and restart. That's caused by tikv reusing the same data key before restart, even when encryption method had changed. The key is send to rocksdb for new files, and rocksdb will return key length mismatch …

encryption: Fix crash after disable encryption or change encryption method

---

Cargo.lock

Address OpenSSL issue CVE-2020-1967 https://www.openssl.org/news/secadv/20200421.txt
Address OpenSSL issue CVE-2020-1967

Cargo: upgrade openssl to 1.1.1g

---

components/raftstore/src/store/config.rs
tests/integrations/raftstore/test_region_heartbeat.rs
tests/integrations/raftstore/test_replica_read.rs

Hibernate region is still experimenting and can be conflict with replication mode. So disable it by default.
Tests 
- Unit test
Side effects
Disable hibernate region by default

raftstore: disable hibernate region by default

---

src/storage/txn/process.rs

Now we use one MvccTxn to process resolve lock requests. The write size shouldn't be accumulated.
Don't accumulate write size of resolve lock.
It's introduced in #7379. I have fixed it when cherry pick it to release branches, so needn't cherry pick this PR.
Tests 
- No code

storage: fix wrong write size of resolve lock

---

Cargo.lock
Cargo.toml
components/external_storage/src/s3.rs

Pass sse_kms_key_id when backup to S3. This is to support using user owned KMS key for server-side encryption.
Pass sse_kms_key_id when backup to S3.
depends on kvproto change: https://github.com/pingcap/kvproto/pull/607
Tests 
Manual test with BR.
Support using user owned KMS key for server-side encryption when backup to S3.

external_storage: pass sse_kms_key_id to S3

---

Cargo.lock
components/external_storage/src/s3.rs

cherry-pick #7627 to release-4.0
---
Pass sse_kms_key_id when backup to S3. This is to support using user owned KMS key for server-side encryption.
Pass sse_kms_key_id when backup to S3.
depends on kvproto change: https://github.com/pingcap/kvproto/pull/607
Tests 
Manual test with BR.
Support using user owned KMS key for server-side encryption when backup to S3.

external_storage: pass sse_kms_key_id to S3 (#7627)

---

components/txn_types/src/timestamp.rs
src/server/service/kv.rs
src/storage/mvcc/txn.rs
tests/integrations/raftstore/test_service.rs

TiDB uses max u64 as start ts when doing point get in the autocommit transaction. If it meets locks, it will lead to `min_commit_ts` overflow. See https://github.com/pingcap/tidb/issues/16778.
Don't push `min_commit_ts` if `caller_start_ts` is max u64.
Tests 
- Unit test
Side effects
Fix the issue that the min commit timestamp of a transaction may overflows which breaks data safety.

txn: don't push min_commit_ts if caller_start_ts is max u64

---

cmd/src/server.rs
components/pd_client/src/client.rs
components/pd_client/src/lib.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/replication_mode.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/pd.rs
components/test_raftstore/src/server.rs
src/server/node.rs
src/server/resolve.rs
tests/integrations/raftstore/test_bootstrap.rs

Part of #7097.
This PR adds a global group registry that stores the group ID of every met store. The information will be used for further implement of label based replication.
Tests 
- Unit test

Support replication mode control

---

components/raftstore/src/store/worker/pd.rs

close: https://github.com/tikv/tikv/issues/7653
TiFlash do not know the `Split` command.
Tests 
- Unit test

raftstore: use batch split for auto-split

---

src/server/service/diagnostics.rs

These numbers are not particularly useful and are not available in upstream sysinfo (because they are Linux-only, as far as I can tell).
PTAL @lonng @overvenus

server: remove number of compressed packets from diagnostics

---

Cargo.lock
Cargo.toml
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs
tests/integrations/raftstore/test_merge.rs

A stale peer will not be destroyed in such conditions
1. Be isolated
2. Be the last removed peer in its peer list
3. Then its region merges to another region.
In this case, PD can not give any help because this region has merged and some related data has been deleted.
After isolation disappears, this peer will send vote msg to other peers in its peer list. But the other peers will ignore this msg and they still think this peer is valid because it exists in their peer list.
This PR introduces a new method to figure out the problem.
Add two new extra message type. `MsgCheckStalePeer` and `MsgCheckStalePeerResponse`.
`MsgCheckStalePeer` is split from `MsgRegionWakeUp`.
The peer can get the newer peer list from …

raftstore: poll the newer peer list to check stale peer

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/service.rs
components/cdc/tests/failpoints/test_observe.rs
components/cdc/tests/failpoints/test_register.rs
components/cdc/tests/failpoints/test_resolve.rs
components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs
components/raftstore/src/store/fsm/apply.rs

Sometimes the ordering of read requests will be changed.
Check observe id for rejecting stale observe cmd.
Tests 
- Unit test
N/A

cdc: check observe id before starting to observe

---

components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/worker/pd.rs

In tests, store heartbeat interval can be very small that cause dividing
zero error.
Tests 
- Unit test

pd_worker: skip collecting load in tests

---

Cargo.lock

When shutdown, TiKV can panic occasionally. When running tests, a stacktrace can also show up occasionally.
Ref tikv/yatp#36.
Tests 
- Unit test
Fixed joining panic during shutdown

*: update yatp to fix joining panic

---

components/tidb_query_vec_executors/src/slow_hash_aggr_executor.rs

This fixes undefined behavior in tidb_query_vec_executors. Miri reports a [stacked borrowing] error as described below.
[stacked borrowing]: https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md
Note that stacked borrowing is a way to model Rust's use of unsafe pointers, but is not officially part of Rust's memory model. Thus, this is not truly undefined behavior today, but could be eventually.
I don't understand the stacked borrowing rules enough to understand why the
existing code is a violation. It is creating a mutable unsafe pointer; then
taking some immutable borrows to the same data while doing nothing with that
pointer; then later using the pointer.
Simply moving the creation of the unsafe pointer to immediately before it
is used removes the error. …

tidb_query_vec_executors: Fixed stack-borrowing undefined-behavior

---

components/encryption/src/config.rs
components/encryption/src/master_key/file.rs
components/encryption/src/master_key/kms.rs

KMS backend should provide master key ID in order to validate ciphertext and key ID are matched. 
Also, it hides access_key and secret_access_key as they are not supposed to config manually in most cases.
- Fixes #7687 
Tests 
- Unit test
Fix encryption at rest KMS key validation.

encryption: validate KMS key id

---

Cargo.lock
components/tidb_query_vec_executors/Cargo.toml
components/tidb_query_vec_executors/src/top_n_executor.rs

servo_arc contains undefined behavior that surfaces in our test suite, as
reported by miri:
> https://github.com/servo/servo/issues/26358
This fixes the problem by using the standard Arc type. This means that these Arcs will be larger to make room for weak pointers.
In the linked issue I have suggested that servo publish an updated servo_arc.

tidb_query_vec_executors: Replace servo_arc with std Arc

---

components/tidb_query_datatype/src/codec/row/v2/row_slice.rs
fuzz/targets/mod.rs

Issue Number: close #7613 
From stdlib doc:
> Behavior is undefined if any of the following conditions are violated:
> * data must be valid for reads for len * mem::size_of::<T>() many bytes, and it must be properly __aligned__.
> * ...
We didn't provide this promise.
Introduce a new type `LEBytes`. Implement `binary_search` for this type by explicitly calling `std::ptr::read_unaligned`.
Tests 
- Unit test

tidb_query: fix UB causing by `from_raw_parts`

---

components/cdc/src/endpoint.rs
components/raftstore/src/router.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/read_queue.rs
components/raftstore/src/store/region_snapshot.rs
components/raftstore/src/store/transport.rs
components/raftstore/src/store/worker/consistency_check.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/read.rs
components/raftstore/src/store/worker/region.rs
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/router.rs
components/test_raftstore/src/server.rs
components/test_raftstore/src/transport_simulate.rs
components/test_raftstore/src/util.rs
src/server/gc_worker/gc_worker.rs
src/server/raftkv.rs
src/server/server.rs
src/storage/kv/cursor.rs
src/storage/mvcc/reader/reader.rs
tests/benches/misc/raftkv/mod.rs
tests/integrations/storage/test_titan.rs

This is some cleanup work. After @Little-Wallace removed the engine type parameter from the Snapshot trait, many raftstore types no longer need to know about engines.
This begins removing `KvEngine` typarams from raftstore in favor of `Snapshot` typarams. There's more to do here, but the patch is starting to bitrot, so I want to land what I have.

raftstore: Replace KvEngine type parameters with Snapshot typarams

---

components/external_storage/src/gcs.rs
components/external_storage/src/util.rs
components/sst_importer/src/errors.rs
components/sst_importer/src/sst_importer.rs

Issue Number: close #7625
It was found that the GCS external_storage can only download 8 KB of data. This PR fixes the issue.
Additionally, tame_gcs hard-coded the request URLs, making the custom endpoint ineffective (EmbarkStudios/tame-gcs#21). This PR also workarounds the issue through URL rewriting.
The problem is caused by using `block_on_external_io` recursively. This seems to break Tokio's executor and caused the download stream to end after a single call of `poll_read` (where the buffer size is 8 KB). 
This PR fixes the problem by removing all nested `block_on_external_io` and replace them by `async fn`.
* need to cherry-pick to release-4.0.
Tests 
* …

external_storage: fix GCS download error, support GCS endpoints, and refactoring

---

Makefile
scripts/run-cargo.sh

Remove unstable build option `-Zconfig-profile` as this option is already stabled by https://github.com/rust-lang/cargo/pull/7823 in [1.43.0](https://github.com/XAMPPRocky/rust/blob/master/RELEASES.md)
```
$ make dist_release
error: unknown `-Z` flag specified: config-profile
```
fix build script by remove outdated build option
Tests 
- Unit test
- No code
Side effects

build: remove unstable build option -Zconfig-profile

---

tests/integrations/storage/test_raftkv.rs

Issue Number: close #6072 
When region is hibernated, first replica read after restart can fail.
Tests 
- Unit test

tests: make read_on_replica stable

---

cmd/src/server.rs
cmd/src/setup.rs
components/tikv_util/src/logger/mod.rs
src/lib.rs
src/server/service/diagnostics.rs

Cherry pick log searching relate commits #7085 #7273 #7541 #7437 to 4.0 release manually
Close https://github.com/tikv/tikv/pull/7606
Fixed a bug that TiKV slow log cannot be searched via diagnotics API.

Cherry-pick #7085 #7273 #7541 #7437

---

components/tikv_util/src/metrics/threads_linux.rs

There was [a PR](https://github.com/tikv/tikv/pull/7306) fixing the memory fragmentation issue. However there is a bug in the PR that the defragmentation will not be very effective after running for a long time. This PR fixes it.
What's Changed: Bug fix.
- Manual test: Tested a cluster that has been started for > 1 day, confirmed that `sys_getdents` are now called by 10 minutes interval, instead of 15 secods.
```
[pid 64038] 15:24:16.579973 getdents(556</data3/wenxuan_kv1_exp/data/snap>, /* 2 entries */, 32768) = 48 <0.000037>
[pid 64038] 15:24:16.580232 getdents(556</data3/wenxuan_kv1_exp/data/snap>, /* 0 entries */, 32768) = 0 <0.000027>
[pid 64039] 15:25:16.582008 …
```

Improve memory defragmentation

---

metrics/alertmanager/tikv.rules.yml

Remove an incorrect alert rule about coprocessor wait second
- Release 4.0
Tests 
- No code
Side effects

*: Remove incorrect alert rule about coprocessor wait second

---

Cargo.lock

close #7312 
update grpcio version to 0.5.3 and enable ALPN
None
1. compile the tikv binary to compare
2. the tikv with this branch can work with TLS but master version log "trying to connect http/1.x"
Side effects
None
- Enable ALPN protocol for TiKV

Update grpcio to enable ALPN

---

components/tidb_query_vec_expr/src/impl_compare.rs
components/tidb_query_vec_expr/src/lib.rs

UCP: #6743 
Issue Number: close #6743 
Port the function `GreatestInt` (Vectorize) from TiDB to coprocessor.
* Add vectorized GreatestInt
* Add vectorized GreatestInt unit tests
Tests
- Unit test

UCP: Migrate `GreatestInt` (Vectorize) from TiDB

---

src/raftstore/store/config.rs
src/raftstore/store/fsm/apply.rs
src/raftstore/store/fsm/batch.rs
src/raftstore/store/fsm/metrics.rs
src/raftstore/store/fsm/router.rs
src/raftstore/store/fsm/store.rs
src/raftstore/store/metrics.rs
src/raftstore/store/peer.rs
tests/integrations/config/mod.rs

Cherry-pick some code of https://github.com/tikv/tikv/pull/7702
Make yield and reschedule counter configurable
Add more metrics
No.
Tests 
- No code
Side effects
No.

raftstore: add metrics for observing apply for 3.0.5.hotfix

---

components/tidb_query_vec_expr/src/impl_compare.rs
components/tidb_query_vec_expr/src/lib.rs

UCP: #6747 
Issue Number: close #6747 
Port the function `GreatestTime` (Vectorize) from TiDB to coprocessor.
* Add vectorized GreatestTime
* Add vectorized GreatestTime unit tests
Tests 
- Unit test

UCP: Migrate scalar function `GreatestTime` (Vectorize) from TiDB

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/service.rs
components/cdc/tests/failpoints/test_register.rs
components/cdc/tests/integrations/test_cdc.rs
components/raftstore/src/store/fsm/peer.rs

TiKV would return `duplicated error` after a pending downstream was unsubscribed.
Cleanup the information of an unsubscribed downstream correctly in `on_region_ready`.
Tests 
- Unit test
* Bugfix for TiKV returns `duplicated error` to TiCDC.

cdc: unsubscribe pending downstream from conn

---

components/backup/src/endpoint.rs
components/backup/tests/integrations/test_backup.rs
components/engine/src/lib.rs

Remove duplicate definition of `DATA_KEY_PREFIX_LEN` from engine crate in favor of engine_traits crate.
https://github.com/tikv/tikv/issues/6402

engine: Remove duplicate DATA_KEY_PREFIX_LEN definition

---

tests/integrations/config/dynamic/pessimistic_txn.rs
tests/integrations/config/dynamic/raftstore.rs

Issue Number: close #7643 close #7644 
`test_update_raftstore_config` and `test_update_apply_store_config` are unstable, because the tests may run long enough to trigger region heartbeat and call on `PdClient` but the `MockPdClient` did not implement the methods.
Replace `MockPdClient` with `TestPdClient`
Tests 
- Unit test

test: fix unstatble test test_update_raftstore_config and test_update_apply_store_config

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/peer_storage.rs

Signed-off-by: Rustin-liu <rustin.liu@gmail.com>
Issue Number: part of #7686
We need a way to calculate memory occupation of messages in FSM's mailbox.
add APPLY_PENDING_BYTES_GAUGE metric.
None
Tests 
None
Side effects

raftstore: add APPLY_PENDING_BYTES_GAUGE metric

---

components/cdc/src/delegate.rs

Key::to_raw usage can be replaced by Key::into_raw and save allocation.
Tests 
- Unit test

cdc: replace Key::to_raw with Key::into_raw to reduce allocation

---

src/server/service/diagnostics/sys.rs

Signed-off-by: Kaige Ye <yekaige2010@gmail.com>
`pnet_datalink::NetworkInterface::mac_address()` will panic if the NIC doesn't have a mac address. For example, a point-to-point link doesn't have mac address.
Return a string "none" when the `NIC.mac` is `None` 
Tests
- Manual test
* add a point-to-point interface (e.g. with `WireGuard` or `OpenVPN` or just `ip tunnel add`)
* run `tiup playground`
* visit http://localhost:2379/dashboard/#cluster-info/host
* check tikv logs
- without this patch, tikv panics
- with this patch, no panic any more

diagnostics: Fix panic when a NIC doesn't have a mac address

---

components/raftstore/src/store/fsm/peer.rs

Scheduling tick failure is verbose and has not ever helped in diagnostics. So set it to debug to make logs less verbose.
Tests 
- Manual test
- change schedule tick failure log to debug level to make logs less verbose

raftstore: make log less verbose

---

components/tidb_query_datatype/src/def/field_type.rs

Signed-off-by: bb7133 <bb7133@gmail.com>
Issue Number: close #7914
TiDB allows `ascii_bin` and `latin1_bin` collation when the new collation framework is enabled, however TiKV does not recognize their IDs(-65 and -47). An error is reported when they're pushed-down to TiKV.
It is quite easy to support them: we use the `Utf8Mb4Bin` collator to handle them, just like what we did for `utf8_bin`.
Tests 
- To be added
Side effects
- None
- Fix the issue that `ascii_bin` and `latin1_bin` is not supported by TiKV for new collation framework.

tidb_query: add missing collation id for ascii_bin and latin1_bin

---

cmd/src/bin/tikv-ctl.rs

close #7886 
relative path cannot be key in encryption dictionary, let's canonicalize it.
canonicalize `kv_path` and `raft_path`
None
Tests 
Side effects
No
- Fix bug where tikv-ctl does not support relative path

Make tikv-ctl used via relative path when encryption is enabled

---

components/raftstore/src/coprocessor/properties.rs
src/storage/mvcc/reader/reader.rs
src/storage/txn/store.rs

Cherrypick #7935.
Delete key must be considered when calculating max ts and min ts in
order to prevent seeing GCed records, otherwise it causes
DefaultNotFound error or seeing inconsistent data.
Tests 
- Unit test
Side effects
- Fix the issue of backup fails with DefaultNotFound error.

mvcc, backup: consider deleted key when calculating max ts and min ts (#7935)

---

Cargo.lock

Signed-off-by: YKG <yekaige2010@gmail.com>
Issue Number: close https://github.com/tidb-challenge-program/bug-hunting-issue/issues/96
Implemenation of `sysinfo::get_used_memory()` was incorrect before version `0.14.2`, and the issue has been fixed since `0.14.3`. Currently TiKV is using the `0.14.1` version.
Update sysinfo version to `0.14.3`~~.(use git ref instead because this version hasn't  been released)~~
Tests 
- Manual test

Update sysinfo version to fix wrong memory usage

---

Cargo.lock
components/tidb_query_codegen/src/rpn_function.rs
components/tidb_query_vec_executors/src/selection_executor.rs
components/tidb_query_vec_expr/Cargo.toml
components/tidb_query_vec_expr/src/impl_arithmetic.rs
components/tidb_query_vec_expr/src/impl_cast.rs
components/tidb_query_vec_expr/src/impl_compare.rs
components/tidb_query_vec_expr/src/impl_compare_in.rs
components/tidb_query_vec_expr/src/impl_control.rs
components/tidb_query_vec_expr/src/impl_encryption.rs
components/tidb_query_vec_expr/src/impl_json.rs
components/tidb_query_vec_expr/src/impl_like.rs
components/tidb_query_vec_expr/src/impl_math.rs
components/tidb_query_vec_expr/src/impl_miscellaneous.rs
components/tidb_query_vec_expr/src/impl_op.rs
components/tidb_query_vec_expr/src/impl_other.rs
components/tidb_query_vec_expr/src/impl_string.rs
components/tidb_query_vec_expr/src/impl_time.rs
components/tidb_query_vec_expr/src/types/expr_builder.rs
components/tidb_query_vec_expr/src/types/expr_eval.rs
components/tidb_query_vec_expr/src/types/function.rs

Signed-off-by: Alex Chi iskyzh@gmail.com
**Problem Summary**
This PR changes all vectorized functions to have signature like `do_something(a: Option<&Int>, b: Option<&Json>`.
**Overview**
In [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/files), we proposed a `ChunkedVec` struct to support Chunk-based computing. We plan to:
1. Migrate current co-processor framework to use interface compatible with `ChunkedVec`. 
This is done by adding new functionalities on current `Vec<Option<T>>`. The detailed plan can be found at [Full Chunk-based Computing PR Roadmap](https://github.com/skyzh/tikv/issues/2).
2. Introduce `ChunkedVec`.
After migrating co-processor to have interface compatible with proposed `ChunkedVec`, we can introduce `ChunkedVec` into TiKV. …

copr: migrate `rpn_fn` interface to be compatible with proposed `ChunkedVec`

---

cmd/src/bin/tikv-server.rs
cmd/src/server.rs
cmd/src/setup.rs
src/config.rs
src/server/config.rs
src/server/node.rs
src/server/status_server/mod.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml
tests/integrations/server/status_server.rs

Issue Number: close #7920 
Instead of the status server's listening address, using an advertise address to register to `PD` for outer communication.
Add `--advertise-status-addr` flag to `tikv-server`, if not specified it will be set to the `status-addr` and it will be used to register to `PD`.
Tests 
- Manual test
- Add `--advertise-status-addr` flag to specify the status address to advertise

server: Add advertise status addr

---

Cargo.lock
components/encryption/Cargo.toml
components/external_storage/Cargo.toml
components/rusoto_util/Cargo.toml
components/rusoto_util/src/lib.rs

- Update rusoto v0.43 ~> v0.44.
- WebIdentityProvider::from_k8s_env() instead of coded logic for self procuring env variables.
rusoto crates updated to latest release. Use of from_k8s_env which manages logic of getting env variables.
Tests 
```
Running target/debug/deps/tikv_ctl-e75f90565218c988
running 2 tests
test tests::test_from_hex ... ok
test tests::test_gen_random_bytes ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

update: rusoto crate and use from_k8s_env()

---

src/storage/txn/commands.rs

Minor refactor in `storage/txn/command.rs`.
`ScanLock`'s code seems the same as the `command!` macro generates, and for consistency, maybe we should using that macro instead of manually write it.
Tests 
- Unit test

txn: use command! macro on ScanLock command

---

Makefile
src/server/status_server/mod.rs

close #7956 
Removed the `mem-profiling` feature of the default tests
Tests 
- Unit test
- No code
Side effects
No
- Fix the bug that `Makefile` cannot run tests

Makefile: fix test failure issue

---

Cargo.lock
Cargo.toml
components/pd_client/Cargo.toml
components/pd_client/src/client.rs
components/pd_client/src/lib.rs
components/pd_client/src/util.rs
components/raftstore/src/store/worker/pd.rs
components/test_raftstore/src/pd.rs
tests/Cargo.toml
tests/integrations/pd/mock/mocker/service.rs
tests/integrations/pd/test_rpc_client.rs

PD distributes cluster version to TiKVs. So that TiKV can do some special things when rolling update.
Tests 
- Unit test
Side effects

server: support cluster_version

---

components/sst_importer/src/import_mode.rs
components/test_sst_importer/src/lib.rs

"Import mode" was used by TiKV Importer to speed up import by skewing the balance towards write speed. It works by dynamically changing these 5 CF options:
* block_cache_size
* level0_stop_writes_trigger
* level0_slowdown_writes_trigger
* soft_pending_compaction_bytes_limit
* hard_pending_compaction_bytes_limit
Previously, these are hard-coded as [4 GiB, 1 GiB, 1 GiB, 0, 0] respectively. However, there is a bug in TiKV which prevents lowered block_cache_size from restored to a higher value when shared cache was enabled. This makes switching to import mode permanently lose write efficiency.
Setting block_cache_size to 4 GiB was originally an attempt to prevent OOM due to too many L0 files back in TiKV 2.0. We are now 2 major versions later and probably this is no longer needed. So we just …

sst_importer: do not change block_cache_size in import mode

---

metrics/grafana/tikv_details.json

Signed-off-by: Liu Cong <liucong@pingcap.com>
Fix the wrong block cache hit rate display in Grafana.
In Grafana, if we choose one specific instance in Grafana/tikv-detail, then the data of Block cache hit panel will be not right, the reason is the queries missed part of the filters by instance.
Add filter conditions to responsive Grafana queries.
This is a related fix of https://github.com/pingcap/tidb-ansible/pull/1312
Tests 
- No code
- Grafana: fix queries of block cache hit panel

Grafana: fix queries of block cache hit panel

---

src/storage/txn/commands.rs
src/storage/txn/process.rs

move several functions to each command
Minor refactor in `src/txn/commands.rs`.
Move `readonly` & `is_sys_cmd` & `requires_pessimistic_txn` & `can_pipelined` to `CommandExt` trait.
Tests 
- Unit test

txn: move several functions to each command

---

Cargo.lock

Problem Summary: cherry-pick fix for #7939 
What's Changed: cherry-pick fix for #7939 
N/A
CI
* Fix potential wrong result read from ingested file.

rust-rocksdb: rocksdb: avoid `IterKey::UpdateInternalKey()` in `BlockIter`

---

Cargo.lock
Cargo.toml
cmd/src/server.rs
components/pd_client/src/client.rs
components/pd_client/src/lib.rs
components/test_raftstore/src/server.rs
components/test_storage/src/sync_storage.rs
src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/config.rs
src/server/gc_worker/gc_manager.rs
src/server/gc_worker/gc_worker.rs
src/server/gc_worker/mod.rs
src/server/server.rs
tests/failpoints/cases/test_gc_worker.rs
tests/integrations/config/dynamic/gc_worker.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

TiKV can't enable compaction filter during rolling update.
Only enable compaction filter after cluster-version reaches specified point.
Tests 
- Unit test
Side effects

gc: only run compaction filter if cluster version is ok

---

src/server/service/diagnostics/ioload.rs
src/server/service/diagnostics/sys.rs

`tikv::server::service::diagnostics::test_load_info` previously use an incorrect `#[cfg()]`. As a result, io and net stats are not collected on Linux. But actually the test has a problem that it forgot to refresh network list. This PR fixes it.
Collecting IO statistics fails on Linux 4.19+ because some new stats are added. This PR also make it work for Linux 4.19+.
Tests 
- Unit tes
Fix network and IO statistics on Linux 4.19+.

test: fix tikv::server::service::diagnostics::test_load_info on Linux

---

Cargo.lock
cmd/src/server.rs
components/backup/Cargo.toml
components/backup/src/endpoint.rs
components/backup/tests/integrations/test_backup.rs
etc/config-template.toml
src/config.rs
src/lib.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: close pingcap/br#394, close #8076. 
This is the companion PR of pingcap/br#396. 
In #5553, the `backup` component gained ability to an adjustable thread pool size. The size is provided via the incoming gRPC request. Given [how the ThreadPool is implemented in TiKV](https://github.com/tikv/tikv/blob/b45e052df8fb5d66aa8b3a77b5c992ddbfbb79df/components/tikv_util/src/threadpool.rs#L204-L219), a user can easily (accidentally) DoS all TiKV servers by setting the thread pool size to a huge number like 2<sup>32</sup>-1. 
Furthermore, when we provide the thread pool size through gRPC, the backup client (BR) must determine the suitable concurrency number in some ad-hoc way. 
This PR solves both issue by moving the thread pool size back as a TiKV config:
```toml …
```

backup,config: set backup thread pool size via config instead of gRPC

---

components/raftstore/src/coprocessor/split_check/table.rs
components/raftstore/src/store/bootstrap.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/worker/consistency_check.rs
components/raftstore/src/store/worker/raftlog_gc.rs
components/raftstore/src/store/worker/read.rs

Removing uses of raw rocksdb APIs per https://github.com/tikv/tikv/issues/6402.
This replaces a few uses of raw_util::new_engine with util::new_engine.
The only remaining uses of raw rocksdb apis in raftstore are tied to "properties collectors", like RangePropertiesCollector, MvccPropertiesCollector.
Type checking.

raftstore: Replace uses of raw_util::new_engine with util::new_engine

---

components/tidb_query_vec_executors/src/table_scan_executor.rs

`BatchTableScanExecutor` ignores point get while encounter common handles keys.
Tests 
- Unit test
* `BatchTableScanExecutor` ignores point get while encountering common handle keys.

copr: table scan ignores point get while encounter common handle

---

src/storage/mod.rs
src/storage/txn/commands.rs
src/storage/txn/process.rs

The only field in `Command` struct is `kind: CommandKind`, so we can use `CommandKind`(should be renamed into `Command`) directly.
Rename the old CommandKind into Command and use it to replace the old Command struct, which only field is the CommandKind.
Tests 
- Unit test

txn: Remove Command and rename CommandKind to Command

---

components/tidb_query_datatype/src/codec/batch/lazy_column.rs
components/tidb_query_datatype/src/codec/data_type/not_chunked_vec.rs

As the proposed `ChunkedVec` only support append, we cannot implement replace on `ChunkedVec` interface.
Proposal: [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/)
Related Issue: #7724
* Remove `replace` from `ChunkedVec` interface.
* Pre-build bitmap before decoding column.
Tests 
- Unit test

copr: remove `replace` from ChunkedVec interface

---

cmd/src/server.rs
components/test_raftstore/src/server.rs
components/test_storage/src/sync_storage.rs
src/server/gc_worker/gc_worker.rs
src/server/lock_manager/config.rs
src/server/node.rs
src/server/server.rs
src/storage/errors.rs
src/storage/mod.rs
src/storage/txn/process.rs
src/storage/txn/scheduler.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/config/mod.rs

Signed-off-by: Boyang Chen <boyang@confluent.io>
Issue Number: close #7652 
The existing code maintains a useless configuration to enable pessimistic transaction. Trying to deprecate the config as well as simplify the codebase.
- Remove if condition for the "enabled" config
- Remove Option type for lock manager in general
None
Tests  
- Existing unit test coverage
Side effects
Nope

Config: deprecate pessimistic transaction "enabled" config to always enable 

---

Makefile

Makefile commands like `make clippy` don't work on arm targets.
When the host is an ARM host, turn off SSE. This won't work in cross-compile scenarios, but I imagine the Makefile doesn't support cross-compiling at present.

Makefile: don't try to use SSE on ARM

---

Cargo.lock
cmd/src/server.rs
components/pd_client/src/client.rs
components/pd_client/src/lib.rs
components/test_raftstore/src/server.rs
components/test_storage/Cargo.toml
components/test_storage/src/assert_storage.rs
components/test_storage/src/sync_storage.rs
src/server/gc_worker/gc_worker.rs
src/server/node.rs
src/server/server.rs
src/server/service/batch.rs
src/server/service/kv.rs
src/storage/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/txn.rs
src/storage/txn/commands/mod.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/commands/prewrite_pessimistic.rs
src/storage/txn/mod.rs
src/storage/txn/process.rs
src/storage/txn/scheduler.rs
src/storage/txn/store.rs
src/storage/types.rs
tests/benches/hierarchy/mvcc/mod.rs
tests/benches/hierarchy/txn/mod.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/storage/test_raft_storage.rs

This PR is ready to land (I hope) but not ready for use. I'm submitting now to get early feedback that the logic is correct, that it is low risk (i.e., if the client is not setting `use_async_commit`, then we are not doing anything differently, and that it is heading in the right direction.
This PR updates kvproto to a version with the async commit fields. Propagates them to the `Prewrite` command (optimistic transactions only for now), propagates a pd client through various layers to `MvccTxn` and uses that to get a timestamp from PD. It saves the secondary keys and timestamp to the lock of the primary key.
PTAL @youjiali1995 @MyonKeminta 
Release note

storage: implement async commit prewrite (initial work)

---

components/tidb_query_codegen/src/rpn_function.rs
components/tidb_query_vec_executors/src/selection_executor.rs
components/tidb_query_vec_expr/src/impl_arithmetic.rs
components/tidb_query_vec_expr/src/impl_cast.rs
components/tidb_query_vec_expr/src/impl_compare.rs
components/tidb_query_vec_expr/src/impl_compare_in.rs
components/tidb_query_vec_expr/src/impl_control.rs
components/tidb_query_vec_expr/src/impl_encryption.rs
components/tidb_query_vec_expr/src/impl_json.rs
components/tidb_query_vec_expr/src/impl_like.rs
components/tidb_query_vec_expr/src/impl_math.rs
components/tidb_query_vec_expr/src/impl_miscellaneous.rs
components/tidb_query_vec_expr/src/impl_op.rs
components/tidb_query_vec_expr/src/impl_other.rs
components/tidb_query_vec_expr/src/impl_string.rs
components/tidb_query_vec_expr/src/impl_time.rs
components/tidb_query_vec_expr/src/types/expr_builder.rs
components/tidb_query_vec_expr/src/types/expr_eval.rs
components/tidb_query_vec_expr/src/types/function.rs

`non-null` is now by default for `rpn_fn` macro. If needs manually handle None case, we should add `nullable` in attributes.
Proposal: [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/)
Related Issue: #7724
* `non-null` by default, add `nullable` attribute in `rpn_fn`
* All functions are refactored to be `nullable`, except for some arithmetic ones.
* In `expr_eval.rs` tests, we modified a cast function to be non-nullable.
Tests 
- Unit test

copr: non-null rpn_fn by default

---

components/tidb_query_codegen/src/rpn_function.rs
components/tidb_query_datatype/src/codec/data_type/chunked_vec_bytes.rs
components/tidb_query_datatype/src/codec/data_type/mod.rs
components/tidb_query_vec_expr/src/impl_string.rs
components/tidb_query_vec_expr/src/lib.rs

**Problem Summary**
Now we can use writer / guard for efficient writing `Bytes` to `ChunkedVec` in vectorized functions.
Proposal: [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/)
Related Issue: close #7724
* add a new vectorized function `repeat`
* add `BytesWriter`, `BytesGuard`, `PartialBytesWriter` for `ChunkedVecBytes`
* add `writer` support for `rpn_fn`
Now all of the items listed in RFC has been implemented. Later I'll update documentation.
Tests 
- Unit test

copr: support writer-guard pattern for Bytes

---

metrics/grafana/tikv_details.json

Append log/Apply log/Commit log duration metrics are actually showing p99 latency of each raft IO stage. 
What's Changed: update the metrics titles.
no
Tests 
eyeball
* No release notes.

metrics: update title of some raft IO metrics

---

components/tidb_query_vec_expr/src/impl_like.rs

Signed-off-by: TennyZhuang <zty0826@gmail.com>
Remove Option from `like` signature.
Tests 
- Unit test
This can be a template PR for community to paticipate.

copr: remove nullable signature for expression `like`

---

Cargo.lock
cmd/Cargo.toml
cmd/src/bin/tikv-ctl.rs
cmd/src/server.rs
components/backup/src/endpoint.rs
components/engine_traits/src/metrics_flusher.rs
components/raftstore/Cargo.toml
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/region.rs
components/tikv_alloc/Cargo.toml
components/tikv_alloc/src/default.rs
components/tikv_alloc/src/jemalloc.rs
components/tikv_alloc/src/lib.rs
components/tikv_util/src/future_pool/mod.rs
components/tikv_util/src/metrics/mod.rs
components/tikv_util/src/threadpool.rs
components/tikv_util/src/time.rs
components/tikv_util/src/timer.rs
components/tikv_util/src/worker/future.rs
components/tikv_util/src/worker/mod.rs
src/import/sst_service.rs
src/read_pool.rs
src/server/debug.rs
src/server/gc_worker/gc_manager.rs
src/server/snap.rs

Issue Number: close #8235
Problem Summary: We are trying to add a proper handle function to create a pointer structure to access the memory usage for running threads on TiKV.
The debug test output looks like:
```
Memory stats by thread:
Thread [store-read-high-5]: allocated: 13665168, deallocated: 9401128.
Thread [sched-worker-pool-1]: allocated: 13665336, deallocated: 9401296.
Thread [store-read-low-3]: allocated: 13665504, deallocated: 9401464.
Thread [sched-worker-pool-2]: allocated: 13665672, deallocated: 9401632.
Thread [store-read-high-1]: allocated: 13665840, deallocated: 9401800.
Thread [unified-read-pool-4]: allocated: 13666008, deallocated: 9401968.
Thread [snapshot-worker]: allocated: 13666176, deallocated: 9402136.
Thread [raft-gc-worker]: allocated: 13666344, deallocated: …
```

tikv_alloc: collect per thread memory allocation for debugging

---

components/tidb_query_vec_expr/src/impl_arithmetic.rs
components/tidb_query_vec_expr/src/lib.rs

copr: remove nullable `arithmetic_with_ctx`
* Replace `arithmetic_with_ctx` with `arithmetic_with_ctx_nonnull`
* Rewrite `int_divide_decimal`
Tests 
- Unit test

copr: remove nullable arithmetic_with_ctx 

---

tests/integrations/server/gc_worker.rs

Issue Number: close https://github.com/tikv/tikv/issues/8261 
The test fails frequently when adds a new peer. The reason is PD's default operator already adds a new peer to the newly added store.
Disable the default operator.
Tests 
- Unit test

test: stablize test_applied_lock_collector

---

components/test_raftstore/src/cluster.rs
components/test_raftstore/src/transport_simulate.rs
src/raftstore/store/fsm/apply.rs
src/raftstore/store/fsm/peer.rs
src/raftstore/store/fsm/store.rs
src/raftstore/store/mod.rs
src/raftstore/store/msg.rs
src/raftstore/store/peer.rs
src/raftstore/store/peer_storage.rs
src/raftstore/store/worker/region.rs
tests/failpoints/cases/test_merge.rs
tests/integrations/raftstore/test_merge.rs

Due to https://github.com/tikv/tikv/issues/8373 is caused by #8301, this PR reverts it.

Revert "raftstore: make destroy overlapped regions and apply snapshot atomically"

---

src/storage/mod.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/txn.rs
src/storage/txn/commands/mod.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/commands/prewrite_pessimistic.rs
tests/failpoints/cases/test_storage.rs

In this PR, pessimistic prewrite will write secondary keys to the primary lock.
Tests 
- Unit test
Support async commit for pessimistic transactions

txn: support async commit for pessimistic transactions

---

README.md

Readme links pointing to old 3.0 links does not work, updating them all to point to version 4.0 of the docs.

readme: updated docs links to point to version 4.0

---

components/tikv_util/src/sys/cgroup.rs
components/tikv_util/src/sys/mod.rs
src/config.rs
src/server/config.rs
src/storage/config.rs

Issue Number: close #8423 
The CPU quota set in cgroup can be an arbitrary float but we don't handle it. TiKV considers the CPU quota is 0 if the quota is less than 1.
Let `cpu_cores_quota` just return an `f64` and change calculations just use the float cpu quota.
Coprocessor max_concurrency is also set to not less than 4. Such a number should not cause OOM.
Tests 
- Set cgroup cpu quota to a float and see the calculated thread number. For example, set cgroup cpu quota to 6.5 cores, then the default coprocessor pool should have 5 threads (previously 4).
- Set cgroup cpu quota to a very small number, `end_point_max_concurrency` will be at least 4.
Support float …

util: support float cgroup cpu quota

---

src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/gc_worker.rs
src/server/gc_worker/mod.rs
src/server/raftkv.rs
src/storage/kv/btree_engine.rs
src/storage/kv/mod.rs
src/storage/kv/rocksdb_engine.rs

Previous commits introduce `Engine::kv_engine` for return a `RocksEngine` with concrete type.
Make the return type of `Engine::kv_engine` generic.
Tests 
- Unit test
* N/A

storage: make Engine::kv_engine generic

---

cmd/src/server.rs
src/server/metrics.rs
src/server/mod.rs

Signed-off-by: Howard Lau <howardlau1999@hotmail.com>
PD needs the CPU cores quota info of the TiKV server for auto-scaling.
The TiKV server will now report a new Gauge metric `tikv_server_cpu_cores_quota` to Prometheus. The metric value is set to `SysQuota::new().cpu_cores_quota()` on server startup.
Tests 
- No code
Reports CPU cores quota to Prometheus.

server: report cpu cores quota to Prometheus

---

src/server/gc_worker/gc_manager.rs

Issue Number: Fixes #8294 
Distributed GC may print some annoying error logs about GC failures, but in most cases these are not errors. This PR changes the log level to warn.
- release-4.0, release-3.1, release-3.0
Tests 
- No code
Side effects

gc_worker: Change log about gc failure to warn level

---

components/txn_types/src/lock.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs

In some rare cases, a rollback may happen between another transaction's prewrite and commit on some key. In this case, the rollback have no chance to push the another transaction's commit_ts, so if the second transaction commits with a calculated commit ts (currently only possible in async commit), it may overwrite the rollback. We don't want to check write cf if there's a rollback when committing, since it harms performance greatly. But when doing rollback, we can let it record its ts in the second transaction's lock, so the second transaction can check it from the lock and needn't to read write cf.
Closes https://github.com/tikv/sig-transaction/issues/46 , I think.
When (protected) rolling back a key, if the key is already locked by  another transaction, put the ts to the lock. When …

txn: Store rollback ts in the lock when the key is locked by another transaction

---

src/storage/mod.rs
src/storage/mvcc/txn.rs

This  PR adds a check to check_txn_status that prevents it from misusing that may push `min_commit_ts` of async commit transactions.
- No
Tests 
- **Unit test will be added after merging https://github.com/tikv/tikv/pull/8349 , which added some test utility for async commit.**

txn: Forbit pushing min_commit_ts of async commit transaction

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
tests/failpoints/cases/test_split_region.rs

Fix #8456, request vote messages are lost during split.
This PR improve TiDB 99.999% Txn duration from 15s to 1s.
Cache vote message into pending votes, so that new peer can response ASAP.
Tests 
* Fix lost request vote messages during split.

raftstore: fix lost request vote messages during split

---

src/storage/mod.rs

Issue Number: close #8426
`Context` is taken from the request before, so `req.get_context()` returns a default `Context`. This leads to high failure rate and cause the performance regression.
Tests 
Previously, there were a lot of `Store Not Match` errors. With this PR there shouldn't be.
Fix wrong context in batch_get_commands

storage: fix wrong context in batch_get_commands

---

components/tidb_query_datatype/src/codec/batch/lazy_column.rs
components/tidb_query_datatype/src/codec/data_type/logical_rows.rs
components/tidb_query_datatype/src/codec/data_type/mod.rs
components/tidb_query_vec_executors/src/fast_hash_aggr_executor.rs
components/tidb_query_vec_executors/src/selection_executor.rs
components/tidb_query_vec_executors/src/slow_hash_aggr_executor.rs
components/tidb_query_vec_executors/src/util/hash_aggr_helper.rs
components/tidb_query_vec_expr/src/types/expr_eval.rs

Signed-off-by: Alex Chi <iskyzh@gmail.com>
Previously in https://github.com/tikv/tikv/pull/8189 , we introduced a bitmap for decoding columns in sequence. And in https://github.com/tikv/tikv/pull/8345 , we introduced a enum type `LogicalRows`, which distinguishes identical row mapping and logical ones. Now, we add fast path for decoding identical logical rows.
* Add fast path for identical logical rows.
**A SIDE NOTE** When working on this feature, I found integration test constantly fails, though my code seems very reasonable. (Refer to first commit, I just moved LogicalRows from one module to another, and this simple change causes the test to fail.) In my opinion, there might be some `unsafe` part that caused this issue. This may need further …

copr: add fast path for ensure_decoded

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/util.rs
components/test_raftstore/src/cluster.rs

Add a cmd epoch checker that is used for checking each proposal's epoch before really proposing it. In other words, this PR moves the epoch check before applying to before proposing, which reduces the extra overhead.
If the normal proposal is rejected by the epoch checker, the epoch checker will save it and callback until the last admin command that conflicts with it has applied. The behavior is almost the same as the previous implementation. The only slight difference is that its callback is called in apply fsm and now it is called in peer fsm.
Also, this work is part of #7980.
Add a cmd epoch checker to eliminate the proposals' failure due to epoch not match during applying.
Tests 
- Unit test
Side effects
No. …

raftstore: add epoch checker to eliminate the proposals' failure due to epoch not match during applying

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_snap.rs

Issue Number: close https://github.com/tikv/tikv/issues/8433
Destroy process must be asynchronous if peer is initialized.
The details is in https://github.com/tikv/tikv/issues/8433.
described above
Tests 
Side effects
No
* Fix a panic issue if a TiKV runs very slow during conf change.

raftstore: destroy process must be asynchronous if peer is initialized

---

src/coprocessor/metrics.rs
src/coprocessor/tracker.rs
src/server/metrics.rs
src/storage/kv/stats.rs
src/storage/metrics.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/backward.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/reader/scanner/mod.rs
tests/integrations/coprocessor/test_select.rs

This PR fixed incorrect processed_keys / total_keys passed to TiDB, as well as missing RocksDB metrics.
1. Changed processed -> processed_versions (number of visible versions in write CF)
2. Changed total -> total_versions (**approximate** number of all meet versions in write CF)
3. Added RocksDB PerfContext to the Coprocessor response.
Tests 
- Manual test: WIP
- Report RocksDB metrics to TiDB
- Fix incorrect process_keys and total_keys

Fix incorrect processed / total keys counter

---

cmd/src/server.rs
components/cdc/src/endpoint.rs
components/cdc/src/observer.rs
components/cdc/tests/mod.rs
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Several problems for CDC:
* the interval of advancing resolved ts is hard-coded
* panic caused by prefix checking of lower bound in `seek_to_first` when seeking for old value
* pick #8434 for supporting config file
* disable prefix checking for old value iterator
Tests 
- Unit test
* N/A

[4.0] cdc: cherry pick bug fixes to release-4.0

---

Cargo.lock
components/tidb_query_vec_executors/Cargo.toml
components/tidb_query_vec_executors/src/runner.rs
tests/failpoints/cases/test_coprocessor.rs

Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
This pull request fixes a fail test related to coprocessor request's deadline detection: https://github.com/tikv/tikv/blob/1ebd3e2178bcea0543bb356d80e521bc1bc44782/tests/failpoints/cases/test_coprocessor.rs#L39
This pull request checks the deadline at 3 points to ensure that we could ensure the request stepping over the deadline confidently.
1. At the time that the request handler begins to execute.
2. At the time that the batch executor runner fetches a batch of data from the executors.
3. At the time that the batch executor finishes the response encoding.
Tests 
- Unit test
Side effects
- Fix deadline detection of …

copr: fix deadline detection test: `test_deadline_3`

---

tests/integrations/raftstore/test_merge.rs
tests/integrations/raftstore/test_transfer_leader.rs

Closes #8516 and closes #8505 
`test_sync_max_ts_after_region_merge` and `test_sync_max_ts_after_leader_transfer` assumed the region 1 leader is on node 1. However it's not true. So this PR transfer the leader to region 1 first.
Tests 
This PR is to stablize tests.

tests: transfer leader to node 1 first to make sync max ts tests stable

---

src/storage/errors.rs
src/storage/mod.rs

Locks in the storage module should be in the form of `Error(box ErrorInner::Txn(TxnError(box TxnErrorInner::Mvcc(MvccError(
box MvccErrorInner::KeyIsLocked(info))))))`. However, previously memory locks are transformed to `Error(box ErrorInner::Mvcc(MvccError(box MvccErrorInner::KeyIsLocked(info))))`, which makes `extract_key_error` fail to extract key error from it. This PR lets `extract_key_error` support the other form.
_Another solution is to change the error type, but it will lead to an extra box. The solution in this PR also prevents similar mistakes in the future._
Tests 
- Unit test
Part of async commit

storage: fix that extract_key_error fails to extract memory locks

---

Cargo.lock
cmd/src/bin/tikv-ctl.rs
cmd/src/server.rs
components/engine_rocks/src/engine.rs
components/engine_rocks/src/raft_engine.rs
components/engine_rocks/src/util.rs
components/engine_traits/src/engine.rs
components/engine_traits/src/engines.rs
components/engine_traits/src/metrics_flusher.rs
components/engine_traits/tests/src/test_metrics_fluster.rs
components/raftstore/src/store/bootstrap.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/snap.rs
components/raftstore/src/store/worker/region.rs
components/test_raftstore/src/util.rs
src/server/debug.rs
src/storage/kv/rocksdb_engine.rs
tests/integrations/config/dynamic/raftstore.rs
tests/integrations/raftstore/test_bootstrap.rs
tests/integrations/storage/test_titan.rs

Use `RaftEngine` instead of `KvEngine` in `MetricsFlusher`.
Tests 
- Unit test
Side effects

remove shared_block_cache from engines

---

components/cdc/src/endpoint.rs

Resolved ts was advanced periodically by getting tso and waiting for timeout simultaneously, which makes tso delayed.
Get tso after timeout.
Tests 
- Unit test
* N/A

cdc: fix incorrect resolved ts timeout

---

etc/config-template.toml
src/server/config.rs
src/storage/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

We have switched the implementation of the lock table to a lock-free skip list. Therefore, it shouldn't add much latency if the memory lock is always checked. 
I think we can allow async commit and check the memory locks by default.
Tests 
Part of the async commit feature

txn: allow async commit by default

---

components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs
etc/config-template.toml
src/config.rs
tests/integrations/config/dynamic/raftstore.rs
tests/integrations/config/mod.rs
tests/integrations/config/test_config_client.rs

If `sync-log` is set to `false`, there is chance that data will be loss.
Make this option true always.
- Set sync-log true always.

Remove sync-log config option

---

components/test_raftstore/src/util.rs
etc/config-template.toml
src/raftstore/store/config.rs
src/raftstore/store/fsm/apply.rs
src/raftstore/store/fsm/store.rs
src/raftstore/store/peer.rs
tests/integrations/config/mod.rs

Migrate #8631
- Set sync-log true always.

Remove sync-log config option (migrate #8631)

---

Cargo.lock

Issue Number: close https://github.com/tikv/tikv/issues/8478
Problem Summary: Panic when parsing responses with missing reason phrases
update httparse.
Tests 
- Unit test
- No code
- Fix the bug that TiKV will panic when parsing responses with missing reason phrases

Fix parsing responses panic bug

---

src/server/service/kv.rs
src/storage/txn/commands/check_txn_status.rs
tests/integrations/server/kv_service.rs

The `min_commit_ts` of an async commit lock is never pushed. Previously we could return `MinCommitTsPushed` action even if the lock is an async commit lock. Then, the client would think the lock was pushed and ignore the lock by mistake.
Never return `MinCommitTsPushed` when the lock is an async commit lock.
Tests 
- Unit test
* Part of async commit.

txn: fix returned action in check async commit txn status

---

src/server/status_server/mod.rs

Issue Number: close https://github.com/tikv/tikv/issues/8641
When TLS fail, the connection is permanently shutdown. This is unreasonable, because the failure of TLS handshake does not mean the failure of TCP.
Tests 
- Unit test
- No code
- Fix the bug that status server shutdown when the TLS handshake fails.

Status Server: avoid server shutdown caused by TLS handshake failure

---

components/cdc/src/service.rs
src/storage/mvcc/txn.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/commands/prewrite_pessimistic.rs

The `min_commit_ts` returned by prewrite was incorrect. This may make the client commit with a commit_ts smaller than expected.
It can happen when the `min_commit_ts` of a pessimistic lock is pushed forward and the new `min_commit_ts` is even larger `max_read_ts`.
Correct the `min_commit_ts` returned by prewrite.
This PR also ensures `min_commit_ts` does not regress in prewriting multiple keys.
Tests 
- Unit test
* Part of async commit

txn: fix the wrong min_commit_ts returned by prewrite

---

src/server/service/kv.rs

In #8494 the histogram statistic name is modified to a wrong name.
- None

Fix histogram name for unsafe_destroy_range

---

Cargo.lock
components/sst_importer/src/sst_importer.rs

part of PiTR(https://github.com/pingcap/br/issues/325), we should let tikv sst_importer handle delete type key.
block on https://github.com/pingcap/kvproto/pull/676/files
if write a key without value. change it to a `WriteType:Delete` record.
Tests 
Side effects

sst_importer: write delete type key for sst service

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/worker/raftlog_gc.rs

When apply-thread receive a  `CompactLog` entry, it will change apply_state and write it into `RocksDB` with `sync`. But when there are a lot of writing regions, apply-thread will sync WAL frequently, and this will hurt performance if the disk is not very good.
This PR will not sync WAL in apply-thread for `CompactLog` but sync it in raft-log-gc thread. If we want to delete entries before some index, we will make sure that all data before this index has been persisted on disk. Because we can do it in batch, so the frequency of sync will be low.
Tests 
- Unit …

raftstore: do not sync wal in apply when compact log

---

src/storage/mod.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/commands/prewrite_pessimistic.rs

https://github.com/tikv/tikv/pull/8657 introduces a bug that the inequality is reversed... `min_commit_ts` always returns 0 after that PR.
This bug exposed that some code is not covered by tests. This PR mainly adds a test covering it besides fixing the bug.
Tests 
- Unit test
Part of async commit.

txn: fix min_commit_ts calculation in prewrite

---

Cargo.lock
Cargo.toml
components/cdc/Cargo.toml
components/pd_client/Cargo.toml
components/raftstore/Cargo.toml
components/test_pd/Cargo.toml
components/test_raftstore/Cargo.toml
components/test_util/Cargo.toml
components/tidb_query_vec_executors/Cargo.toml
components/tikv_util/Cargo.toml
src/storage/kv/mod.rs
src/storage/mod.rs
src/storage/mvcc/txn.rs
tests/Cargo.toml
tests/failpoints/cases/test_transaction.rs

Just add more tests for async commit.
This PR adds failpoints tests for three requirements:
* **It is atomic to getting max ts and store the memory lock.**
In the test there is a sleep between getting the latest max ts and storing the lock. If the whole process was not atomic, a reader read at the same time, then the lock might be invisible to the reader but its min_commit_ts was smaller than the read ts.
* **Max TS is updated before getting the snapshot.**
In the test there is a sleep after getting the snapshot. And a prewrite request completes during this sleep. If we didn't update max ts before the snapshot, `min_commit_ts` in the prewritten lock could be smaller than the read ts while the reader also could not see the lock, which was unacceptable.
* **Max TS is updated before scanning …

tests: add some failpoints tests for updating max ts and setting memory lock 

---

src/storage/kv/mod.rs
src/storage/mod.rs

A few lines of docs are moved to the kv submodule, obviously the docs there need improvement later.
PTAL @youjiali1995 
Our horrible documentation situation (a baby step towards solving).
Adds some docs to the storage module
Tests 
- No code

storage: add some top-level docs

---

tests/integrations/server/raft_client.rs

Issue Number: close https://github.com/tikv/tikv/issues/8666
This PR make sure that original server is shutdown. Otherwise, subsequent request may not be sent because the raft client use same `Conn`.
- None

Fix test_raft_client_reconnect by shutdown mockserver before restart

---

Cargo.lock
cmd/Cargo.toml
cmd/src/dump.rs
cmd/src/lib.rs
cmd/src/server.rs
components/keys/src/lib.rs
src/config.rs

When users enable raft-engine on the old database, it needs to dump data from old raftdb into new raft-engine.
scan keys from raftdb and judge the type of value through suffix, convert it to protobuf data format and save into raft-engine.
- Implement dump from raftdb to raft-engine.

raft-engine: implement dump from old raftdb

---

components/sst_importer/src/errors.rs
components/sst_importer/src/sst_importer.rs
etc/error_code.toml
tests/integrations/import/sst_service.rs

Issue Number: close #7266
Recently #7266 happens again, with call stack involving these blocks:
https://github.com/tikv/tikv/blob/ed93f82480798d3badca3b324e40fab4c36fa84d/tests/integrations/import/sst_service.rs#L313-L315
https://github.com/tikv/tikv/blob/ed93f82480798d3badca3b324e40fab4c36fa84d/tests/integrations/import/sst_service.rs#L132-L133
Here, the call to `send_upload_sst()` is expected to error with FileExists, but previously it should only happen on line 315. Likely due to the async/await refactoring in #8550, the same error sometimes is emitted on line 313 instead, which caused the panic.
1. Merged the 3 `block_on` calls into a single `async` block and allow every future to propagate the error.
2. Tightened the …

test: try to make test `import::sst_service` more robust

---

Cargo.lock
components/encryption/Cargo.toml
components/external_storage/Cargo.toml
components/rusoto_util/Cargo.toml
components/rusoto_util/src/lib.rs

`rusoto_util::DefaultCredentialsProvider::credentials()` is implemented by forwarding the call to each of the inner credentials providers successively. But if both failed, the errors are both ignored and only a generic message `Couldn't find AWS credentials in default sources or k8s environment.` remains.
This PR inserts the origin error messages back into the final error to aid diagnosis.
Additionally, updated rusoto deps from 0.44 to 0.45.
* Cherry-pick this and #8066 together to release-4.0.
Tests 
- Unit test
Side effects

rusoto_util: keep the original error in DefaultCredentialsProvider

---

src/server/service/kv.rs

Previously `split_region` and `read_index` RPC calls return a grpc error when re-directing the request to backend raft regions, which will make TiDBs retry the request on the same store. So the `split-region` command could never success.
This PR changes to return `RegionNotFound`, which will make TiDB try other stores if necessary.
Tests 
Side effects

change error for split_region and read_index

---

src/server/raft_client.rs

When I ran `make test` I would get a failure because indentation is assumed to be a doc test. This fixes it. Common Mark does not require indentation of lists although I didn't verify the actual doc output of this.

fix doc tests

---

components/tikv_alloc/src/jemalloc.rs

Memory profiling can only be triggered by `write` instead of `update`.
Tests 
- Unit test
Side effects
- Fix generating memory profile

tikv_alloc: fix profiling

---

components/tikv_util/src/yatp_pool/future_pool.rs

https://github.com/tikv/tikv/issues/7393
`future_pool::tests::test_tick` is still a flaky test.
As I explained in https://github.com/tikv/tikv/pull/8323#discussion_r464775141, the root of the flakiness is that calling the tick method and receiving the tick can be in parallel.
This PR spawns a future to receive the tick. Because the pool has only one thread, the new future must be executed later than the tick is triggered. So the problem is completely solved without tricky timeouts.
Tests 
- Unit test

test: stablize future_pool::tests::test_tick again

---

components/tikv_util/src/sys/mod.rs
src/server/service/diagnostics/mod.rs
src/server/service/diagnostics/sys.rs

`sysinfo::System` shouldn't be created multiple times. It should be created once and for all. See https://github.com/GuillaumeGomez/sysinfo/issues/345#issuecomment-658624786. 
BTW, `sysinfo` will create the same number of threads as the number of CPUs available due to `rayon`.
Use a singleton `sysinfo::System`. It's protected by a mutex which may affect performance, but I think it's acceptable because it's seldom used.
Tests 
- No code
Side effects

tikv_util: use singleton sysinfo::System

---

Makefile

Previously we introduced an `error-code` pre-condition of every build command in Makefile, which makes the build process slower.
Remove the `error-code` pre-condition in Makefile.
Tests 
- No code
* N/A

Makefile: do not gen error code before build

---

metrics/grafana/tikv_fast_tune.json

Signed-off-by: Liu Cong <innerr@gmail.com>
Fastly detect write performance issue caused by batch-size
Add 2 panels for Fast-Tune page.
- Fast Tune: https://github.com/tikv/tikv/pull/8798
Tests 
- No code
Side effects
- None
- None

metrics: add write-batch-size-too-big panels to Fast-Tune

---

.github/ISSUE_TEMPLATE/question.md
CONTRIBUTING.md
README.md

Issue Number: N/A
Problem Summary: Outdated docs links and some poor format
- Update several outdated or broken doc links
- Update mail address format
- Make capitalization style consistent and standard
- Remove the deprecated link of TiKV forum
- PR to update `pingcap/docs`/`pingcap/docs-cn`: N/A
- PR to update `pingcap/tidb-ansible`: N/A
- Need to cherry-pick to the release branch: @dcalvin What do you think?
Tests 
- No code
N/A

*: update and fix docs links and format

---

tests/failpoints/cases/test_merge.rs

Issue Number: close https://github.com/tikv/tikv/issues/8246
Fix test_node_merge_crash_when_snapshot test
Change `transfer_leader` to `must_transfer_leader` otherwise the next proposals may be rejected due to ongoing leader transfer.
- No
Tests 
- No code
Side effects
- No

test: fix test_node_merge_crash_when_snapshot test

---

Cargo.lock
Cargo.toml
components/batch-system/Cargo.toml
components/cdc/Cargo.toml
components/encryption/Cargo.toml
components/encryption/src/manager/mod.rs
components/raftstore/Cargo.toml
components/raftstore/src/errors.rs
components/raftstore/src/router.rs
components/raftstore/src/store/transport.rs
components/raftstore/src/store/worker/read.rs
components/tikv_util/Cargo.toml
tests/Cargo.toml

cherry-pick #8805 to release-4.0
Issue Number: close #8761
Problem Summary: Mutex conflict of encryption makes pd-worker deal with heartbeat slow
- Remove the IO operation from the file_dict mutex.
- Create background thread to do rotation of key.
- Fix the bug that mutex conflict of encryption makes pd-worker deal with heartbeat slow

Encryption: reduce lock range of file_dict and background the key rotation (#8805)

---

components/engine_panic/src/db_options.rs
components/engine_rocks/src/db_options.rs
components/engine_traits/src/db_options.rs
src/config.rs

cherry-pick #8124
This PR is trying to support changing `rate-bytes-per-sec` dynamically. Related to tikv/rust-rocksdb#515
Tests 
- Unit test
- Support changing `rate-bytes-per-sec` dynamically

engine_rocks: support change rate limit dynamically

---

Cargo.lock
Cargo.toml
components/backup/src/endpoint.rs
components/engine_rocks/Cargo.toml
components/engine_rocks/src/lib.rs
components/engine_rocks/src/sst.rs
components/external_storage/Cargo.toml
components/external_storage/src/lib.rs
components/external_storage/src/metrics.rs
src/import/sst_service.rs
tests/failpoints/cases/mod.rs
tests/failpoints/cases/test_import_service.rs
tests/integrations/import/mod.rs
tests/integrations/import/test_sst_service.rs
tests/integrations/import/util.rs

Backup and restore involves some IO in gRPC threads. They should be moved to worker threads.
Remove io from grpc threads
Tests 
Side effects
- Stabilize backup and restore by removing IO operations from gRPC threads.

*: remove io from gRPC threads (#8886)

---

components/tidb_query_normal_expr/src/builtin_time.rs
components/tidb_query_normal_expr/src/scalar_function.rs

part of #3275
One of the tests is consistently failing on my system- `store::util::tests::test_lease`. I am on Ubuntu 20.04
Signed-off-by: Kunal Mohan <kunalmohan99@gmail.com>
What's Changed: push down builtin method NullTimeDiff
Tests 
- Unit test
No release notes

coprocessor/expression: push down builtin method NullTimeDiff

---

CONTRIBUTING.md

Signed-off-by: dvermd <315743+dvermd@users.noreply.github.com>
Problem Summary: There's a typo on the "Slack" link in CONTRIBUTING.md
Tests 
- No code

*: fix typo in CONTRIBUTING.md

---

src/storage/kv/rocksdb_engine.rs
src/storage/mvcc/txn.rs

Should check data constraint when no lock exists, otherwise it can report an error when there is a lock belonging to a committed transaction which deletes the key.
Cherry pick https://github.com/tikv/tikv/pull/8921 to release-4.0
Change the order between checking data constraint and lock.
Tests 
- Unit test
- Fix the issue that reports a key-exist error when a key is locked and deleted by a committed transaction.

txn: check data constraint after lock

---

components/tikv_util/src/logger/mod.rs
src/server/status_server/mod.rs

Signed-off-by: andrisak <andrisak@gmail.com>
A new endpoint was added to the StatusServer API that can be called using HTTP to change the log level during runtime. The new endpoint path is `/log-level`. Example invocation:
`curl -X PUT -H "Content-Type: application/json" -d '{"log-level":"debug"}' http://127.0.0.1:20180/log-level`
New feature.
The unit test `test_change_log_level` in `status_server` was extended to also test this endpoint.
Also ran basic integration tests by running pd-server, the updated tikv-server, and tidb-server and calling the endpoint. Monitored the tikv-server log to see if the entries had the expected level.
This change should be documented but it's not included in this PR.
No.

Support adjusting log level dynamically through HTTP API (#4033)

---

components/encryption/src/config.rs
components/encryption/src/encrypted_file/header.rs
components/encryption/src/encrypted_file/mod.rs
components/encryption/src/lib.rs
components/encryption/src/log_file.rs
components/encryption/src/manager/mod.rs
components/test_raftstore/src/cluster.rs
components/test_util/src/encryption.rs
tests/integrations/config/mod.rs
tests/integrations/server_encryption.rs

cherry-pick #8865 to release-4.0
Issue Number: close #8212
When file number is large, file dictionary size is large too, so TiKV needs more time to rewrite the file dictionary.
Add a new file format LogFile, it supports append writing.
- Turn file dictionary into log style.

encryption: Turn file dictionary into log style (#8865)

---

components/tikv_util/src/worker/pool.rs

Issue Number: close https://github.com/tikv/tikv/issues/8970
If the thread of `Worker` run too fast, the counter may call `sub` before scheduler call `add`,  so we will make the counter be `usize::MAX`.
Tests 
- Unit test
- No code
Side effects

*: fix counter overflow

---

components/sst_importer/src/sst_importer.rs
components/test_raftstore/src/server.rs
components/test_util/src/encryption.rs
components/test_util/src/lib.rs
tests/integrations/import/test_sst_service.rs
tests/integrations/import/util.rs

Fix ingest lightning written sst files failure with TDE enabled. 
In #8852, if tikv TDE is enabled, the sst file written by lightning will be encrypted, but the save action renames the encrypt file but not register this action in the key manager, thus, when ingesting this sst file, rocksdb will treat it as unencrypted and fail.
So this pr add an extra `DataKeyManager::rename_files` to the original file rename action and add an integration test to test write and ingest sst with TDE enabled.
Tests 
- Unit test
- No code
Side effects
- Fix the bug that lightning fails to ingest sst files to tikv with …

importer: rename sst file with key manager to fix ingest sst failure

---

tests/integrations/server_encryption.rs

Issue Number: close https://github.com/tikv/tikv/issues/8569
If the learner peer is added successfully, but learner has not got all data from leader, `must_get_equal` may fail.
promote the peer from learner to voter.
- N/A

Fix test `test_node_snapshot_encryption`

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
tests/integrations/raftstore/test_hibernate.rs

Issue Number: close #9022  
Prevent leader going to sleep when there are still peer catching up for logs to reduce corner cases.
Tests 
- Unit test
Side effects
- Prevent hibernation when there are still peers catching up logs

raftstore: keep wake on isolation

---

Cargo.lock
src/coprocessor/endpoint.rs
src/coprocessor/tracker.rs
src/server/service/batch.rs
src/server/service/kv.rs
tests/integrations/coprocessor/test_select.rs
tests/integrations/server/mod.rs

KvProto update https://github.com/pingcap/kvproto/pull/689 introduced some code changes, so that this PR adapts to it.
Update code to be compatible with latest KvProto https://github.com/pingcap/kvproto/pull/689
1. Renames are performed accordingly.
2. Use `ExecDetailsV2` instead of `ScanDetailV2` in Coprocessor response, KvGet response and KvBatchGet response.
ExecDetailsV2 = ScanDetailV2 + TimeDetail. This makes it possible to return TiKV side process time in future, as proposed in https://github.com/pingcap/kvproto/pull/689
Tests 
- Unit test

misc: Update KvProto

---

src/storage/mvcc/txn.rs
src/storage/txn/actions/acquire_pessimistic_lock.rs
src/storage/txn/actions/check_data_constraint.rs
src/storage/txn/actions/mod.rs
src/storage/txn/actions/prewrite.rs

As I proposed in #8513, we can move these "action" function and related tests to txn/actions.rs, and make the code cleaner.
Though `check_data_constraint` is not used by commands, its also a "high level" operation which is made up with multiple basic operations in MvccTxn, so it should be also an action
Move `MvccTxn::check_data_constraint` and related tests and test utils to `action` mod.
Tests 
- Unit test (I added a real unit test for it)
Side effects

txn: Move check_data_constraint to action module

---

components/raftstore/src/store/fsm/apply.rs

A simple code refactor. 
Notice that `wb` to be `None` only when constructing `ApplyContext`. We can remove the `Option` wrapping `WriteBatch` to make code clean (by eliminating `unwrap`s) and improve performance slightly.
Tests 
- Unit test
- Remove Option wrapper from WriteBatch

raftstore: Remove Option wrapper from WriteBatch

---

src/coprocessor/checksum.rs

Issue Number: close pingcap/br#611
Running the checksum coprocessor, even with concurrency = 1, affects the cluster performance since it never yields control.
Copied the "reschedule" mechanism from the "analyze" coprocessor to the checksum coprocessor.
- Need to cherry-pick to the release branch 
* 3.0, 4.0
Tests 
* Execute BR backup while a SELECT is running in background. The following shows the TiDB QPS measurement before and after applying this PR:
* Green = (Negation of) number of keys processed by the "checksum" coprocessor, non-zero means a checksum is running
* Yellow = QPS, higher means the background SELECT is less affected
* Left 3 = before this PR was applied, QPS is dropped to 30% of original …

copr: allow checksum request to be rescheduled

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

add vectorize substring_2_args, substring_3_args
Issue Number:  #9016
add push-down & test of substring_2_args, substring_3_args
Tests 
- Unit test
Side effects

copr: add vectorize substring_2_args, substring_3_args

---

components/tidb_query_expr/src/impl_time.rs

Signed-off-by: wangggong <793160615@qq.com>
Add check missed in https://github.com/tikv/tikv/pull/8999.
Tests 
- Unit test
Side effects

fix: add invalid time check for `add_datetime_and_duration` & `sub_datetime_and_duration`

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/worker/region.rs
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/transport_simulate.rs
tests/failpoints/cases/test_merge.rs
tests/failpoints/cases/test_snap.rs
tests/integrations/raftstore/test_merge.rs

Cherry-pick https://github.com/tikv/tikv/pull/7027, https://github.com/tikv/tikv/pull/8408
* Fix an issue that region merge may cause data loss during network partition.
* Fix a panic issue that may happen in region merge when TiKV crashes.

raftstore: make destroy overlapped regions and apply snapshot atomically

---

components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: jyz0309 <45495947@qq.com>
Issue Number: related to #9016
add vectorize sub_duration_and_duration
add vectorize sub_duration_and_duration
Tests 
- Unit test
- pr: add vectorize sub_duration_and_duration

copr: add vectorize sub_duration_and_duration

---

Cargo.lock
Cargo.toml
src/server/service/kv.rs
tests/failpoints/cases/test_kv_service.rs
tests/integrations/server/kv_service.rs

`KvScan` interface has a similar problem with https://github.com/tikv/tikv/pull/9077. TiDB requires all the KV pairs in the range to be returned (if the limit is not reached).
Although queries from TiDB users are transformed into coprocessor queries, the `KvScan` interface is still used in multiple cases like backfilling in DDLs.
Set memory lock to the newly added KeyError field in `ScanResponse`. The client will skip using pairs if the error is used.
Tests 
- Part of the async commit feature

storage: return memory locks as ScanResponse level error

---

src/server/gc_worker/gc_worker.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/backward.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/gc.rs
src/storage/txn/actions/mod.rs
src/storage/txn/mod.rs

As I proposed in #8513, we can move these "action" function and related tests to txn/actions.rs, and make the code cleaner.
Though `gc` is not used by commands, its also a "high level" operation which is made up with multiple basic operations in MvccTxn, so it should be also an action
Move `MvccTxn::gc` and related tests and test utils to `action` mod.
Tests 
- Unit test
Side effects

txn: move gc to action module

---

components/tidb_query_aggr/src/impl_sum.rs
components/tidb_query_datatype/src/codec/mysql/enums.rs

Signed-off-by: Xuanwo <github@xuanwo.io>
Implement ENUM support for aggr SUM
- Implement a new aggr for ENUM: AggrFnSumForEnum
Tests
- Unit test

copr: Implement ENUM support for aggr SUM

---

Cargo.lock

https://github.com/tikv/tikv/pull/9029 is intended to update rocksdb to include cache key collision fix and key order check. But the update is not included by mistake. So update rocksdb by this PR.
run `cargo update -p rocksdb`
Tests 
- No code
- None

rocksdb: Fix missing rocksdb update of #9029

---

components/tidb_query_aggr/src/impl_avg.rs

Implement ENUM/SET support for aggr AVG 
Should be merged after #9184 
Tests
- Unit test

copr: Implement ENUM/SET support for aggr AVG 

---

src/storage/txn/actions/commit.rs
src/storage/txn/actions/prewrite.rs

Adds a unit test to ensure that the min commit ts is properly computed.
PTAL @sticnarf @ekexium 

txn: test min commit ts properties

---

Cargo.lock
Cargo.toml

close #9217 
A lot of improvement on `pprof-rs`. A more detailed description can be found in the [release page](https://github.com/tikv/pprof-rs/releases).
The most important part is that after profiling, it doesn't restore the default behavior of `SIGPROF` after profiling. Maybe I should learn more about the signal handling mechanism in Linux, but ignoring the signal could be a simple solution for now.
Ref: `gperftools` doesn't restore the signal handler after profiling (source code in this [file](https://github.com/gperftools/gperftools/blob/master/src/profile-handler.cc)) as I know.
Tests 
- Manual test
```
curl …
```

status_server: upgrade pprof-rs to 0.3.19

---

src/server/server.rs

Issue Number: close #9221 
raft client will retry implicitly, so in tests, it's possible that the
test thread exits while raft client still tries to send messages, which
will result in panic. This PR solves the problem by just ignoring
the error.
Tests 
- Unit test
- No code
Side effects

server: ignore channel error in tests

---

components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_replica_read.rs

Issue Number: close https://github.com/tikv/tikv/issues/9208
The fast path of handling read index request in TiKV may give a stale index because we check the latest commit index, not the index which is used to reply to the response.
In most case, there is no problem. However, if this leader is a new one and the commit index of `PeerStorage` is too small and the log term of the latest commit index is equal to current term, this problem arises.
Check whether the log term of the commit index of `PeerStorage` is equal to current term.
Add a test to reproduce this bug.
At the end of this test, the read request gets a stale value in the previous implementation.
Tests 
- …

raftstore: fix the stale read index after transferring leader

---

src/storage/config.rs
src/storage/txn/latch.rs

The latches scheduler would prevent key writing ,if there has been one key in waiting queue. I changed this behavior to check the waiting if there has been a hash value repeat with it .
I set scheduler-concurrency to 512 * 1024 by default. If there are 1000K keys written at the same time, every key would be compared in the deque only twice. I think it is efficient enough.
Tests 
- Unit test

Optimize scheduler latches to avoid latch-wait (#6094)

---

src/storage/txn/commands/prewrite.rs

Problem Summary: We don't have unit tests for which stage in raft can we response to the user.
Write unit tests to check `response_policy` field on the result `Prewrite` and `PrewritePessimistic` command match the expected result.
Related prs waiting for reviewing: 
(Also PTAL) #9245 test whether the scheduler handle `response_policy` correctly
#9136 by NingLin-P has a test for stale callbacks (I'm also tring to add an integration test for this)
Tests 
- Unit test

txn: Unit test for response stage of prewrite

---

tests/failpoints/cases/test_early_apply.rs

Issue Number: close https://github.com/tikv/tikv/issues/9252
The test_multi_early_apply is not stable because the compact log may be proposed after adding the send filter and the `"raft_before_save_on_store_1"` failpoint is triggered, which makes leader not send append msg for `cluster.async_put(b"k4", b"v4").unwrap();`.
We can easily reproduce this test failure by adding a `sleep_ms(500)` before `cluster.async_put(b"k4", b"v4").unwrap();`.
Tests 
- No code
Side effects
- No
* No Release Note

test: stablize test_multi_early_apply test

---

cmd/src/server.rs
components/batch-system/src/router.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/server.rs
src/server/node.rs
tests/integrations/raftstore/test_bootstrap.rs

Issue Number: close https://github.com/tikv/tikv/issues/9151 
TiKV may crash if background worker stop before raftstore pool shutdown.
Tests 
- Unit test
Side effects

raftstore: stop background worker

---

tests/integrations/raftstore/test_replica_read.rs

Issue Number: close #6667  
Previously tiflash gets read-index through `read_index` RPC, now it has changed to use follower read.
With #9068, a region that has pending peers will not go to sleep, and with #6648 and #6348, the failed follower read will be retried.
So for now we can consider that #6667 has been addressed.
Add a test for covering the case.
Tests 
- Unit test
* N/A

tests: add test for replica read with split isolation

---

src/coprocessor/endpoint.rs
src/coprocessor/tracker.rs

Issue Number: close #9223
With a high read load, runtime schedules cop tasks heavily. To ensure fairness, every task will be executed for a while then yield out and wait for the next execution. Previously, the process time is recorded but not for the suspend time.
Record suspend time.
Tests 
- Unit test
- Record suspend time for coprocessor task

copr: add suspend time into tracker

---

components/tidb_query_datatype/src/codec/mysql/duration.rs
components/tidb_query_expr/src/impl_cast.rs

Issue Number: close https://github.com/pingcap/tidb/issues/21695 
The condition value is NULL, but TiKV return the result.
In the function Duration.from_i64, return a MaxDurationTime is meaningless.
When it throw an overflow error, the behavior should be the two situations:
1. If Flag::OVERFLOW_AS_WARNING is set, TiKV should handle the error, and return a NULL value.
2. If Flag::OVERFLOW_AS_WARNING is not set, TiKV should return the error. 
But now, the overflow number will be convert to MaxDurationTime, and make the condition ture. 
So I try to throw the error directly, can handle the error in `cast_int_as_duration`
Tests 
- Unit test
Side effects
- Fix the wrong behavior …

copr: fix the different behavior between tidb and tikv in convert function.

---

components/test_raftstore/src/pd.rs
tests/integrations/raftstore/test_conf_change.rs

Issue Number: close #3162 
`test_server_auto_adjust_replica` is not stable because of the replica count check.
Relax the check condition.
Tests 
- Unit test
* N/A

tests: try to stabilize test_server_auto_adjust_replica

---

src/storage/kv/mock_engine.rs
src/storage/kv/mod.rs
src/storage/mod.rs
src/storage/txn/commands/mod.rs

Currently we don't have a test to check whether the scheduler handle `response_policy` correctly.
Write tests for checking whether the correct stage the callback is called  according to `response_policy`. This is done by introducing a `MockEngine` which is a wrapper around `RocksEngine` but with the ability to assert the in comming writes, which should be also useful in other tests.
Tests 
- Unit test

txn: Unit test to check scheduler handle response_policy correctly

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/observer.rs
components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs
src/storage/mvcc/reader/scanner/mod.rs
tests/integrations/raftstore/test_conf_change.rs

Use `start_ts` to get old value maybe return a stale old value.
Replace with `max(for_update_ts, start_ts)`
Tests 
- Unit test
* cdc: fix stale old value with pessimistic lock.

cdc: use for_update_ts to get old value

---

src/storage/txn/commands/macros.rs
src/storage/txn/commands/mod.rs

Issue Number:  Addresses the need for code level documentation in transactions, as per https://github.com/tikv/sig-transaction/issues/25
Documentation added for `TypedCommand`, the `command` macro and a couple of other traits.
I found it hard to follow the flow of the Request -> Command handling and thought these comments might help others in future. My difficulty lay in putting 3-4 pieces together: the macros (and their enums), the `From` traits invoked via .into() and the usage of PhantomData. There's also the StorageCallback and some async code there that I haven't dug into much.
Let me know whether the documentation I have added is correct, and whether it is worth keeping around in the code. If not in the code, I'll keep it around somewhere at least for my own …

txn: Documentation for TypedCommand and command macro

---

components/pd_client/src/client.rs
components/pd_client/src/feature_gate.rs
components/pd_client/src/lib.rs
components/test_raftstore/src/pd.rs
src/server/gc_worker/compaction_filter.rs
tests/integrations/pd/test_rpc_client.rs

It's important to be able to adjust cluster version if we want to test
upgrading. This PR also moves feature gate into trait to make it
accessible in other module like raftstore.
Tests 
- Unit test
Side effects

tests: allow changing cluster version in tests

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This PR is used to bump TiKV version to v4.0.9
- No Release Note

*: Bump version v4.0.9

---

Cargo.lock
components/engine_rocks/Cargo.toml

Problem Summary: cut branch for 5.0-rc release. content of the rocksdb branch is identical to master at this point.
What's Changed: cut branch for 5.0-rc release.
N/A
Tests 
CI
- No release notes

rocksdb: update branch for 5.0-rc release

---

tests/failpoints/cases/test_stale_read.rs

Issue Number: close #9232 
Transferring leader can fail due to log gap, which is introduced by new
log compact proposal.
Tests 
- Unit test
Side effects

tests: stop log compact for transferring leader

---

src/server/gc_worker/compaction_filter.rs

When inserting data into a new constructed cluster, SST files will be flushed from memtables to L6(the bottommost level) directly. It's unnecessary to run GC for them because all data should be fresh instead of stale.
Update `check_need_gc` function for GC in compaction filter:
For a given SST file if its min ts is larger than safe point, skip GC for it.
Tests 
- Unit test
* gc: skip SSTs flushed to the bottommost level

gc : skip for flushing to the bottommost level

---

src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/gc_manager.rs

It's possible that users switch GC in Compaction Filter one during TiKV in a GC round. To save resource, the GC round can be broken.
Checking configuration changes in GC round. If GC manager finds that it's unnecessary to continue, return from the round.
Tests 
- No code
* gc: check configuration changes in a round

gc: check configuration changes in a round

---

cmd/src/server.rs
components/test_storage/src/sync_storage.rs
src/server/gc_worker/gc_worker.rs

Currently there is a bug that consistency checker can't be registered correctly, so that users can't enable consistency check at all.
In the PR we register consistency checker before starting batch system, so that it can work as expected.
Tests 
1. Start a tikv server with configuration `raftstore.consistency-check-interval = '5s'`
2. Wait 5 seconds, and then check the TiKV's log
3. Grep "consistency check pass", if we can see something it says the patch works
Side effects
* server: register consistency checker correctly

server: register consistency checker correctly

---

src/storage/txn/actions/check_txn_status.rs
src/storage/txn/commands/check_txn_status.rs

Issue Number: close https://github.com/pingcap/tidb/issues/21658
TiDB decides whether a transaction can bypass other transactions' locks during reading by `MinCommitTsPushed` action. Now only when the min_commit_ts is updated, TiKV returns the action. It results in unexpected blocking.
Return `MinCommitTsPushed` when lock.min_commit_ts > caller_start_ts even if the min_commit_ts isn't updated.
Tests 
- Unit test
* Fix the issue that locks block reading even if their min_commit_ts is pushed forward.

txn: return MinCommitTsPushed when lock.min_commit_ts > caller_start_ts

---

CHANGELOG.md
Cargo.lock
Cargo.toml

As is stated, release note: https://github.com/pingcap/docs/pull/4421

*: Bump version v3.0.20

---

components/tidb_query_datatype/src/def/field_type.rs

`utf8_unicode_ci` collation id is 192.
Tests 
- Unit test
- no

collation: fix incorrect utf8_unicode_ci collation id

---

tests/failpoints/cases/test_replica_read.rs

Stabilize the test case test_new_split_learner_can_not_find_leader.
Fix https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/38960/pipeline/ .
Stabilize the test case test_new_split_learner_can_not_find_leader.
Tests 
- Unit test
Side effects

stabilize test_new_split_learner_can_not_find_leader

---

Cargo.toml
components/cdc/src/delegate.rs
components/cdc/tests/failpoints/test_resolve.rs
components/test_coprocessor/src/dag.rs
components/tidb_query_common/src/error.rs
components/tidb_query_expr/src/impl_cast.rs
scripts/test
src/server/service/diagnostics/log.rs

Issue Number: close #9352
Problem Summary: `make build PROST=1` failed to compile.
* Changed TiKV's Cargo.toml to use "resolver = 2" so that `cmd` can recognize `feature = "prost-codec"`.
* In Prost, we have the `FieldType::tp()` inherent method which has name conflict with `FieldTypeAccessor::tp()` trait method. Use the FQN to disambiguate.
* Use `as _` to bridge enum-to-int conversion.
* Use `.into()` to bridge T-to-Box&lt;T&gt; conversion.
* release-5.0-rc
Tests 
* make build PROST=1
* make build
Side effects
No release notes

*: fix make build PROST=1

---

components/cdc/src/delegate.rs
components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs

Problem Summary: This PR filters out write cf's apply events that has the `gc_fence` field set, which means the applying is caused by rewriting while adding overlapped rollback flag.
What's Changed: Filter out apply events with gc fence set.
Tests 
- Unit test

cdc: Filter out apply events with GC Fence 

---

components/cdc/tests/integrations/test_cdc.rs

Fix unstable test.
Get ts from pd client instead of hardcode ts.
Tests 
- Unit test
* N/A

cdc: fix unstable old value test

---

tests/integrations/raftstore/test_merge.rs

`test_request_snapshot_after_propose_merge` is not stable by potential reasons:
1. merge proposal may be skipped by log gap limit
2. time between proposing premerge and requesting snapshot is uncertain
3. leader could be changed
1. increase log gap limit
2. use `proposed_cb` to ensure premerge proposed before requesting snapshot
3. increase election timeout
Tests 
- Unit test
* N/A

tests: stablize test_request_snapshot_after_propose_merge

---

Cargo.lock
tests/Cargo.toml
tests/integrations/storage/test_raft_storage.rs

The test case test_auto_gc is not stable.
It fails at `Storage::get(...).unwrap()`, which expects an `Ok` but `Err(StaleCommand)` is got. So retry the request can stabilize the case.
Issue Number: close https://github.com/tikv/tikv/issues/6400 .
Tests 
- No code

ci: stabilize case test_auto_gc

---

components/pd_client/src/client.rs
components/pd_client/src/lib.rs
components/pd_client/src/util.rs
components/test_raftstore/src/pd.rs
tests/failpoints/cases/test_pd_client.rs
tests/integrations/pd/test_rpc_client.rs

Prerequisite of tikv/importer#89. TiKV Importer relies on TiKV as a library, and uses various pd_client methods when processing the gRPC call. However, many pd_client methods are made synchronous using `block_on`. Since gRPC calls are async, this leads to [`EnterError`](https://docs.rs/futures-executor/0.3.8/futures_executor/struct.EnterError.html) panic due to recursive use of executors.
Added async methods for the following to avoid `block_on`:
* RpcClient::new_async
* PdClient::get_region_async
* PdClient::get_region_info_async
* PdClient::get_store_stats_async (the sync version is removed since it is not used anywhere else)
- Need to cherry-pick to the release branch (release-5.0-rc)
Tests 
- Unit test
Side effects

pd_client: introduce async versions of methods to avoid block_on

---

components/test_raftstore/src/transport_simulate.rs
tests/failpoints/cases/test_merge.rs
tests/integrations/raftstore/test_merge.rs

Some test cases about merge are not stable:
* test_node_merge_transfer_leader
* test_node_merge_reject_request_snapshot
* test_request_snapshot_after_propose_merge
Old failures:
* https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/39263/nodes/98/steps/589/log/?start=0
* https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/39287/nodes/203/steps/615/log/?start=0
* https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/39091/nodes/120/steps/924/log/?start=0
These cases fail because `merge` or `split` commands are rejected for "not applied to current term".
So this PR add some code to ensure it.
Tests …

ci: stabilize several test cases about merge

---

components/raftstore/src/store/fsm/mod.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_split_region.rs

Issue Number: close #9388 
This PR adds a new field batch_offset to ready collection, which
indicates the offset of origin peer in the batch.
Stores the ready inside Fsm is an alternative, but it can occupy
unnecessary memory.
Using memory address of Fsm is also an alternative, though seems a
little hacky.
Both of the alternatives require a loop, using offset only needs to
query once. It may have improvement in clusters that have a lot of
regions and ticking usually doesn't generate readiness.
Tests 
- Unit test
Side effects
- …

raftstore: match ready by batch_offset

---

components/concurrency_manager/src/key_handle.rs
components/concurrency_manager/src/lock_table.rs

Previously, if a reader holds an `Arc<KeyHandle>` which in the lock table and a prewrite calls `lock_key`, `lock_key` will upgrade a weak in the lock table. But it also creates a useless `KeyHandle` which drops when `lock_key` returns. When dropping `KeyHandle`, it removes the key from the table incorrectly.
Tests 
- Unit test
- Fix a bug that memory locks are removed incorrectly.

concurrency manager: fix incorrect key drop when weak succeeds to upgrade

---

components/tidb_query_datatype/src/codec/convert.rs
components/tidb_query_datatype/src/codec/mysql/json/mod.rs
components/tidb_query_expr/src/impl_cast.rs

Issue Number: for https://github.com/pingcap/tidb/issues/21362
Migrate TiDB json conversion logic modification from https://github.com/pingcap/tidb/pull/21826.
Return data truncate error when convert object/array to integer/float/decimal.
Tests 
- Unit test
- copr: refine JSON conversion, throw err when object/array convert to integer/float/decimal

copr: refine JSON conversion, throw err when object/array convert to integer/float/decimal

---

tests/integrations/raftstore/test_lease_read.rs

The test case `test_read_index_stale_in_suspect_lease` is not stable. It sometimes fails on transferring leadership.
Enlarge raft log compaction gap to ensure leader transferring success. Just like https://github.com/tikv/tikv/pull/9321 does.

ci: stabilize case test_read_index_stale_in_suspect_lease

---

components/batch-system/Cargo.toml
components/raftstore/Cargo.toml
components/tikv_util/Cargo.toml

Issue Number: close #5209
Fixing build error when building `batch_system` crate alone, i.e. want to run the bench under the crate by:
```
cargo bench -p batch-system --feature protobuf-codec
```
What's Changed: updating features flag in Cargo.toml.
N/A
Tests
- Manually run `cargo bench -p batch-system --feature protobuf-codec`
- No release notes.

batch_system: fix build when building the crate alone

---

scripts/check-bins.py

Signed-off-by: ichn-hu <zfhu16@gmail.com>
check-bins.py uses `time.clock` to estimate the running time, but it is deprecated since python 3.3 and is removed since python 3.8. Users with python 3.8+ can't run this script.
See https://docs.python.org/3.7/library/time.html?highlight=time%20clock#time.clock for details.
What's Changed: use time.time instead of `time.clock`
- N/A
Tests 
- No code
Side effects
- N/A
- no release note.

scripts: update check-bins to make it python3.8 compatible

---

components/test_util/src/logging.rs

When running one test case, for example:
```bash
cargo test --all test_node_merge_transfer_leader
```
Both `integrations-*` and `failpoints-` will be runned, which will open and truncate the target log file twice.
Add a new environment variable `LOG_APPEND`.
Setting it to any value will use append instead of truncate when opening log file.
Tests 
- No code
Side effects

ci: allow to not truncate log file

---

components/cdc/src/endpoint.rs
components/cdc/src/observer.rs
components/txn_types/src/lib.rs
components/txn_types/src/types.rs
components/txn_types/src/write.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/check_extra_op.rs
src/storage/txn/actions/get_old_value.rs
src/storage/txn/actions/mod.rs
src/storage/txn/actions/prewrite.rs
src/storage/txn/actions/tests.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/store.rs
tests/benches/hierarchy/mvcc/mod.rs
tests/benches/hierarchy/txn/mod.rs

`ExtraOp` is a very unatural thing to be handled in MvccTxn, in fact, the only situation we need it is for getting the old value for cdc during the prewrite process. So maybe we can move it to there.
Move `ExtraOp` and old_value getting staff to actions module, and change the prewrite part to adopt it
Tests 
- Unit test
Side effects
- No Release Note

txn: remove extra_op related things from MvccTxn

---

Cargo.lock
components/pd_client/Cargo.toml
components/pd_client/src/client.rs
components/pd_client/src/util.rs
tests/failpoints/cases/test_pd_client.rs

Issue Number: close #9463 
Problem Summary: the `update_loop` may take 10s or more, it may block gRPC threads.
What's Changed: move `update_loop` to anther thread.
Tests 
- Unit test
Side effects
- Fix gRPC keepalive issue caused by PD client.

pd_client: prevent RPC being blocked by PD client update leader

---

Cargo.lock
Cargo.toml
components/batch-system/src/batch.rs
components/file_system/src/file.rs
components/file_system/src/iosnoop/biosnoop.c
components/file_system/src/iosnoop/biosnoop.rs
components/file_system/src/iosnoop/metrics.rs
components/file_system/src/lib.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/worker/raftlog_gc.rs
components/raftstore/src/store/worker/region.rs
components/raftstore/src/store/worker/split_check.rs
src/coprocessor/readpool_impl.rs
src/read_pool.rs
src/server/snap.rs
src/storage/read_pool.rs
src/storage/txn/sched_pool.rs
tests/Cargo.toml
tests/integrations/raftstore/test_snap.rs

Signed-off-by: Connor <zbk602423539@gmail.com>
Issue Number: part of #9156 
Problem Summary: 
Tag io type for foreground read/write and snapshot of replication/loadbalance, so io rate limiter can use it to throttle different tasks
- tag `ForegroundRead` for storage/coprocessor readpool
- tag `ForegroundWrite` for scheduler worker and batch system of raftstore/apply
- Add a field `for_balance` for snapshot meta https://github.com/pingcap/kvproto/pull/707, so the receiver can know whether the snapshot is triggered by balance.
- use `matched_index==0` to decide whether the snapshot is triggered by balance or not, and tag `LoadBalance` or `Replication` on the generation and receiving of snapshots. 
https://github.com/pingcap/kvproto/pull/707
- Manual test (add detailed scripts …

*: Tag io type for foreground and snpashot

---

cmd/src/server.rs

There is a bug in the master branch that GC can't work at all. The reason is `0` is passed into the GC worker as `store_id`, which will cause all regions get skiped when doing GC.
Close https://github.com/tikv/tikv/issues/9466.
The bug is introduced in https://github.com/tikv/tikv/pull/9350.
Start gc worker after node. So that `node_id` passed into the GC worker will must be valid.
Tests 
a) starting a new tikv cluster
b) run a sysbench update_index workload, then check the gc worker cpu panel
c) check the result:

start gc after node to fetch node id

---

tests/failpoints/cases/test_merge.rs

Stabilize test_node_merge_crash_when_snapshot.
Replace `transfer_leader` with `must_transfer_leader`.
Tests 
- Unit test

stabilize test_node_merge_crash_when_snapshot

---

src/server/gc_worker/gc_worker.rs

Assertion on `self_store_id >  0` for GC worker. So that if component initialization order in `cmd/src/server.rs` is changed incorrectly, we can find that immediately.
Assertion on `self_store_id > 0` for GC worker. And adjust test code if necessary.
Tests 
Side effects

gc: assertion on zero `self_store_id`

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This PR is used to bump TiKV version to v4.0.10

*: Bump version v4.0.10

---

Cargo.lock
cmd/src/server.rs
components/encryption/examples/ecli.rs
components/encryption/src/config.rs
components/encryption/src/crypter.rs
components/encryption/src/encrypted_file/mod.rs
components/encryption/src/lib.rs
components/encryption/src/manager/mod.rs
components/encryption/src/master_key/file.rs
components/encryption/src/master_key/kms.rs
components/encryption/src/master_key/mem.rs
components/encryption/src/master_key/mod.rs
components/engine_traits/src/encryption.rs
components/external_storage/Cargo.toml
components/external_storage/src/s3.rs
components/rusoto_util/src/lib.rs
components/sst_importer/src/sst_importer.rs
components/sst_importer/src/util.rs
components/test_util/src/encryption.rs

Signed-off-by: Greg Weber <greg@pingcap.com>
TiKV needs to support different KMS encryption providers. For example, issue #8906 
The KMS backend now has a KmsProvider which defaults to AwsKms.
It is now straightforward to write a different backend.
Some associated refactorings were made:
* Simplify KmsBackend internal state management
* Creating a backend does not happen inside Arc::new()
* Reduce code pollution of testing where `#[cfg(test)]` was used
* Add a Debug trait to backends
* Add some newtypes for safety
* Make some error messages more detailed
* Fix KMS was marked as not send but can change how it uses the APIs instead
None, cherry-pick to a release branch may be needed in the future.
Tests 
- Unit test
- Integration test (tested manually with …

encryption: support multiple cloud providers

---

cmd/src/server.rs
components/file_system/src/lib.rs
components/raftstore/src/store/worker/pd.rs
etc/config-template.toml
src/storage/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Currently TiKV reserves 2GB disk space to ensure recovering from `no space left` error must success. It's not enough exactly.
And, `available_space` reported to PD is wrong.
Issue Number: close https://github.com/tikv/tikv/issues/9395.
TiKV reserve 5GB space at least and 20GB at most. The lower limit can be adjusted in config file.
Tests 
a. Start a TiKV instance without the patch
b. Stop it and switch to the branch, restart it
c. size of file `space_placeholder_file` increases larger
* server: reserve space with a better strategy

reserve space with a better strategy

---

src/storage/kv/rocksdb_engine.rs

Cleaning up the tikv::storage::kv module to make it eventually generic over engine_traits
- cc https://github.com/tikv/tikv/issues/9480
- cc https://github.com/tikv/tikv/issues/6402
This code is unused. Delete it.

kv: Remove unused impl of EngineIterator for DBIterator

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/test_raftstore/src/cluster.rs
tests/integrations/raftstore/test_hibernate.rs

Issue Number: close #9505
If leader is demoted and the region is hibernated, there can be no
leader for quite a long time. It's by design that client should try
other peer when leader is not available, but currently ticlient can't
handle the issue well. On the other hand, PD can still keep sending
scheduling command to the demoted leader, which will also timeout.
So this PR adds an additional check before sleeping to get around it.
This should fix the pd scheduling issue, but ticlient can still timeout
if demoted peer is restarted, client should still retry other peers when
necessary.
Tests 
- Unit test

raftstore: check valid leader before sleeping 

---

components/engine_panic/src/engine.rs
components/engine_panic/src/write_batch.rs
components/engine_rocks/src/engine.rs
components/engine_rocks/src/write_batch.rs
components/engine_traits/src/mutable.rs
components/engine_traits/src/write_batch.rs

The other two mutation methods, put and delete, have two versions each: one that takes a CF, and one that doesn't (it mutates CF_DEFAULT). The `delete_range_cf` method though has no corresponding `delete_range` method.
This PR adds the method.
This is not _actually_ needed by tikv - the one place it calls `delete_range_cf(CF_DEFAULT...)` makes sense to continue using the "cf" version of the method.
As a matter of API design though, these methods should exist.
But furthermore, the engine test suite I'm developing will be more self-consistent if the non-cf version of this method is available - various tests are parameterized over both the "cf" and "non-cf" versions of these mutation methods.
I've included no unit tests, but the …

engine_traits: Add delete_range (no cf) methods

---

components/pd_client/src/client.rs
components/pd_client/src/util.rs
components/test_pd/src/mocker/service.rs
components/test_pd/src/server.rs
tests/failpoints/cases/test_pd_client.rs

Issue Number: close https://github.com/tikv/tikv/issues/9470
`region_heartbeat` in the `test_pd_client_deadlock` case sometimes hangs forever.
`region_heartbeat` interface in the PD client creates a stream when reconnecting to the PD leader which means `block_on`ing it can't return until reconnection. It results in the unstable test. It's changed to return a future instead of a stream which is more intuitive.
Tests 
- Unit test

test: fix test_pd_client_deadlock

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/service.rs
components/cdc/tests/integrations/test_cdc.rs

When two TiCDC changefeeds connect to the same region, but one changefeed requires old value but the other doesn't, the one that doesn't need old value still receives old value.
What's Changed: Now we record the old value setting in each `Downstream` and filters the old value appropriately before sinking the events. 
Tests 
- Unit test
- Fix old value config glitch when changefeeds with different settings connect to one region

cdc: fix old value config glitch when changefeeds with different settings connect to one region

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
tests/integrations/raftstore/test_joint_consensus.rs

Issue Number: close #9445 #9332 #8789 #8775
Currently, TiKV doesn't check leave joint command. If the leader is `DemotingVoter`, it will step down after applying the leave joint command and lead to region unavailable until a new leader elect. Normally, this should not happened, because PD (with its acknowledge about the region) won't send such command to the leader,  and as such command can send to the leader with the right `RegionEpoch` meaning PD has up-to-date acknowledge. But we should add such check for robustness.
This PRs add checks to prevent leave joint while the leader is `DemotingVoter`, and also add checks to prevent split or merge region while the region is in joint state, again this also should not happen because of the epoch check.
This PRs …

raftstore: add more checks before proposing joint confchange

---

components/concurrency_manager/src/lib.rs

Remove stale comments. Since after #8608, `LockTable` is already a concurrency ordered structure. And it's no longer a `BtreeMap`.
#8608
No code
Side effects
None

Components/concurrency-manager: Remove stale comments

---

src/server/service/diagnostics/sys.rs

TiKV panics when the `server_info` gRPC method of the Diagnostic service is invoked, when there exists a NIC with no MAC address (e.g. PTP interfaces).
This PR reapplies #7942, which when the cherry-pick PR #8939 refactored this part of code causes the change to be lost.
Tests 
* See #7942.
Side effects
* Fixes a crash problem when running a TiKV on a machine with a network interface lacking MAC address since v4.0.9.

server: fix panic when a NIC doesn't have a mac address again

---

components/raftstore/src/store/worker/read.rs

Issue Number: close #9469 
Using `LruCache` instead of `HashMap` to store local `ReadDelegate`
- raftstore: use lru cache store local read delegate

raftstore: use lru cache store local read delegate

---

src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/reader/scanner/mod.rs

Issue Number: close #9551 
Problem Summary: When the DeltaScanner loads old value for a lock, it asserts all other write records has less `commit_ts` than the lock's `max(start_ts, for_update_ts)`. However there's a special case: a rollback record can be written at any time even the key is locked by a smaller ts.
What's Changed: Moves the panicking assertion statement so that rollback records will not be asserted.
- 4.0, 5.0-rc
Tests 
- Unit test
Side effects
-
- Fix the issue that when loading old value for CDC's incremental scan on a key where there's a rolled back transaction, in some cases TiKV may panic.

scanner: Fix the panic on loading old value when there's a rollback record with large ts

---

Cargo.lock
src/coprocessor/endpoint.rs
src/coprocessor/metrics.rs
src/coprocessor/tracker.rs
src/storage/kv/stats.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/backward.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/reader/scanner/mod.rs
tests/integrations/coprocessor/test_select.rs

This PR cherry picks https://github.com/tikv/tikv/pull/7563
What's more, some code in #7563 is refined later in https://github.com/tikv/tikv/pull/9008, so that this PR includes it as well.
This PR should be merged together with https://github.com/pingcap/kvproto/pull/699. Roadmaps:
Tests 
- Unit test
- Manual test:
Insert 300000 rows, randomly delete 111 rows, then query `select count(*)`:
```
[2021/01/26 15:52:23.754 +08:00] [INFO] [tracker.rs:241] [slow-query] [perf_stats.internal_delete_skipped_count=47424] [perf_stats.internal_key_skipped_count=347565] [perf_stats.block_read_byte=0] [perf_stats.block_read_count=0] [perf_stats.block_cache_hit_count=98] [scan.range.first="Some(start: 7480000000000000315F69800000000000000100 end: …
```

storage: Fix incorrect processed / total keys counter (#7563)

---

metrics/grafana/performance_read.json
metrics/grafana/performance_write.json
metrics/grafana/tikv_details.json
metrics/grafana/tikv_fast_tune.json
metrics/grafana/tikv_raw.json
metrics/grafana/tikv_summary.json
metrics/grafana/tikv_trouble_shooting.json

Signed-off-by: zhengjiajin <zhengjiajin@pingcap.com>
The latest version of tidb-operator will use the instance name as the cluster label. The previous expression uses the cluster label got the value of the tidb_cluster variable. It will cause Grafana can not to display the data.
https://github.com/tikv/pd/pull/3389#issuecomment-767977783
- no change
Tests 
- No code
Side effects

metrics: use tidb_cluster label get variable values

---

components/file_system/Cargo.toml

On Mac:
```
--> components/file_system/src/rate_limiter.rs:5:5
5 | use crossbeam_utils::CachePadded;
|     ^^^^^^^^^^^^^^^ use of undeclared crate or module `crossbeam_utils`
```
* None

fix: broken build on Mac

---

tests/integrations/import/test_sst_service.rs
tests/integrations/import/util.rs

Issue Number: close https://github.com/tikv/tikv/issues/9472
TiKV may cleanup sst which has been upload just, so the ingest-job will success because it can not found file in path before it starts proposing, and the error is checked only when applied this entries.
We do not need to check and cleanup sst very quickly in this tests, so I remove the configuration for `cleanup_import_sst_interval`.
Tests 
- Unit test
- No code
Side effects
- Breaking …

importer: fix test_ingest_sst

---

components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: Drumil Patel <drumilpatel720@gmail.com>
Issue Number: Partially fixes #9016 
Problem Summary: Added Vectorize version for AddDatetimeAndString
What's Changed: Implmented Vectorize vesion for AddDatetimeAndString
Tests 
- Unit test
- Partially fixes #9016

copr: Vectorize AddDatetimeAndString

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

Hi! I am dipping my toes slowly into contributing to TiKV by this small PR
Issue Number: part of https://github.com/tikv/tikv/issues/9016
Problem Summary: implement vectorized `Trim2Args`
I have just reused the implementation for `Trim3Args` to reduce chances of subtle differences in their behaviour in the future. My question is - do you want to go forward with a specialized implementation for `Trim1Arg`? All three could share the same implementation, but a specialized implementation  for `Trim1Arg` that does not bother with conversions to strings also makes sense.
Tests 
- Unit test: migrated from old non-vec implementation

copr: add vectorized Trim2Args

---

fuzz/fuzzer-afl/Cargo.toml
fuzz/fuzzer-honggfuzz/Cargo.toml

Issue Number: Supports #9103 
Disable fuzzer honggfuzz & afl on Windows because they do not support Windows.
Tests 
- Unit test
- No code
Side effects

build: disable fuzzer honggfuzz & afl on Windows

---

src/storage/mvcc/txn.rs
src/storage/txn/commands/rollback.rs

Issue Number: close #9654
This PR is to fix an incorrect assertion. See the unit test of this PR, the secondary lock of a pessimistic transaction may bypass rollback checks (e.g. an index key in TiDB). So the original assertion is not always true.
Tests 
- Unit test
- Fix a false assertion when rolling back locks with existing rollbacks.

txn: allow rollback a lock with an existing rollback

---

components/tidb_query_datatype/src/codec/mysql/json/serde.rs
components/tidb_query_expr/src/impl_json.rs

Issue Number: close https://github.com/pingcap/tidb/issues/22744 
Rust `serde_json` will yield JSON string as `{"population":100}`, while MySQL yields `{"population": 100}`. Note the missing space.
This PR adds the missing space after `:` and `,`.
Tests 
- Unit test
Side effects
* Fix missing space when casting json to string in TiKV coprocessor

copr: fix missing space in json format

---

Cargo.lock
tests/Cargo.toml
tests/benches/coprocessor_executors/mod.rs
tests/benches/deadlock_detector/mod.rs
tests/benches/hierarchy/engine/mod.rs
tests/benches/hierarchy/mvcc/mod.rs
tests/benches/hierarchy/storage/mod.rs
tests/benches/hierarchy/txn/mod.rs
tests/benches/raftstore/mod.rs

Remove `PAPI` dependency, which is really out of fashion now :face_with_head_bandage: , as the perf event document gets richer.
Use `criterion-perf-events` rather than `criterion-papi` to get instructions counts during the benchmark.
The only degradation is that the unit is displayed as `cycles`, which is hard coded in `criterion-perf-events` :crying_cat_face: . Don't mind it because it doesn't effect the correctness of the result.
```
table_scan_datum_absent_large_row/RocksDB/batch/with_dag/rows=5000                                                                            
time:   [117543777.9983 cycles 117816414.1483 cycles 118078450.0667 cycles]
table_scan_long_datum_all/Memory/batch/next=1024 …
```

copr: use criterion-perf-events to get instructions

---

components/pd_client/src/client.rs
components/pd_client/src/config.rs
components/pd_client/src/errors.rs
components/pd_client/src/lib.rs
components/pd_client/src/metrics.rs
components/pd_client/src/util.rs

Import macros from other crates with the `use` syntax. 
rust-lang/rust#50911
Tests 
- Unit test

pd_client: refine PD client codes

---

components/raftstore/src/store/config.rs

Change default merge-check-tick-interval from 10 to 2.
The admin cmd may be dropped when the leader has not applied to current term which is introduced by https://github.com/tikv/tikv/pull/8441.
If the `CommitMerge` is dropped, the merge process will get stuck and the data in source region can not be read or written until the later retry. The default of merge-check-tick-interval is 10(s) which is obviously too long so this PR change it to 2(s). 
Tests 
- No code
Side effects
* Change the default merge-check-tick-interval to 2 to speed up the retry of merge process

raftstore: reduce merge check tick interval

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/snap.rs

If there are too many stale snapshots, GC snapshot in raftstore thread could be very slow.
When GC snapshots, skip to examine checksum for them.
Tests 
No new cases are added, but all cases about snapshot GC cover this change.
* speed up snapshot GC

skip to examine snapshots when GC

---

src/server/service/diagnostics/sys.rs

Signed-off-by: Max-Cheng <aaron9shire@gmail.com>
This PR implements the Diagnostics service server information retrieving interface, which is used to retrieve server load / hardware / system wide information. And this PR includes the following information:
- Hardware
- CPU 
- Arch
Tests 
- Unit test
- Support display CPU arch

diagnostics:add cpu arch

---

Makefile

Signed-off-by: Akshat Agarwal <humancalico@disroot.org>
Fixes: #9015
Problem Summary: Some OS like NixOS don't follow the FHS so `make` fails because the Makefile sets the `SHELL` variable to `/bin/bash`.
What's Changed: This commit changes the variable used for `SHELL` in the Makefile to just `bash` so that it uses the `bash` present in the `PATH` instead of `/bin/bash`
Tests 
Tested on NixOS using `make build`
- Some OS like NixOS don't follow the FHS so `make` fails because the Makefile sets the `SHELL` variable to `/bin/bash`. This commit changes the variable used for `SHELL` in the Makefile to just `bash` so that it uses the `bash` present in the `PATH` instead of `/bin/bash`

use bash from the PATH instead of the absolute path

---

scripts/clippy
scripts/clippy-all
scripts/env

The official clippy configuration is in a shell script that runs against all targets.
Add a helper ./scripts/clippy to run clippy against individual targets. 
Tests
- Manual test `./scripts/clippy -p PACKAGE`
None

scripts: add scripts/clippy

---

src/storage/mod.rs

Reschedule when `raw_scan` a lot of data to avoid blocking other requests too long.
Tests 
- No code
Side effects

Add reschedule for raw scan

---

components/tidb_query_expr/src/impl_cast.rs

Signed-off-by: guo-shaoge <shaoge1994@163.com>
Issue Number: close #9704 
Problem Summary: 
drop table t;
create table t (a varchar(30));
insert into t values ('');
delete from t where a=10;
Delete statement should be ok. In MySQL, the result of empty stringcasting to float is zero. But in TiDB, it gives "Data Truncated" errors. Because cast expr got bug when cast empty string to float.
That was fixed in TiDB [here](https://github.com/pingcap/tidb/issues/10806), but we still need to fix it in copr. 
What's Changed:  Change function cast_string_as_signed_real(). When input string is empty, result will be 0.0
Tests 
- Unit test
Side effects: no side effects.
- fix cast expr when cast empty string to float in copr.

copr: fix cast expr when cast empty string to float (#9704)

---

cmd/src/server.rs
components/backup/src/endpoint.rs
components/encryption/src/lib.rs
components/error_code/src/lib.rs
components/pd_client/src/lib.rs
components/pd_client/src/util.rs
components/tikv_util/src/lib.rs
components/tikv_util/src/log.rs
src/import/sst_service.rs
src/server/raft_client.rs
src/storage/errors.rs

default <T> to unknown means the compiler cannot tell us if error codes
are working. It is easy to accidentally end up with the unknown code.
It also requires all implemntations to use specialization.
Remove defaulting to unknown
use an error_unknown macro if there is no error code to set it to
unknown.
None
Tests
Tested a case where the error code shows up after these changes. Previously wrappers were getting defaulted to unknown but are now properly dereferenced.
Side effects
Code may change from Unknown to a more specific code.
Fix error code propagation

error_code: remove default implementation

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This PR is used to bump TiKV version to v4.0.11

Bump version v4.0.11

---

Cargo.lock
Cargo.toml

grpcio-sys is updated to a new version that can detect compiler changes
correctly, so it will recompile from outdated caches.
openssl-src is replaced with an old version, because 1.1.1g to 1.1.1j
makes the check on self signed keys stricter, which can affect current
users. For example, upgrading an existing cluster can disconnect the
updated nodes due to certs error. So this PR downgrades openssl to wait
for a good solution to the problem and not blocking 5.0.0.
Tests 
- Unit test

*: fix build on CI

---

components/raftstore/src/store/config.rs
components/test_raftstore/src/common-test.toml
components/tikv_util/src/lib.rs

This PR adds a function to check if the binary is built on master
branch. Hibernate region is an experimental features that should
not be enabled on release branch, but it's enabled by accident on
5.0.0-rc. Checking branch name at build time can prevent such mistake
from happening again.
The side effect of the PR is binary built in PR will also have hibernate
regions disabled even it's checkout from master.
Tests 
- Unit test
- disable hibernate region by default as it's still unstable

raftstore: disable hibernate region except on master

---

src/storage/errors.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/cleanup.rs

I need to debug an issue of resolveing lock, but I can't get the start_ts and key from the `Committed` error:
```
resolveLocks failed: unexpected resolve err: abort:"Txn(Mvcc(Committed { commit_ts: TimeStamp(423311069165125656) }))" 
```
record key and start_ts in `Committed` error
Tests 
- No code
Side effects

storage: record key and start_ts in committed error

---

components/engine/src/iterable.rs
components/engine_traits/src/options.rs
src/server/raftkv.rs
src/storage/kv/btree_engine.rs
src/storage/kv/cursor.rs
src/storage/kv/mod.rs
src/storage/kv/rocksdb_engine.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/scanner/mod.rs
src/storage/txn/scheduler.rs
src/storage/txn/store.rs

Cherry-pick of #8514
optimize seek write when there are too many tombstones.
Fix https://github.com/tikv/tikv/issues/8486
Three optimizations:
- for batch-get and coprocessor(point-get), use prefix_seek and prefix_same_as_start to get seek every key for write cf, so it can skip tombstones of other keys.
- for prewrite, when calculating `has_data_in_range` use `max-skippable-internals-keys` to avoid seek too many tombstones.
- check key order before calling `near_seek` for `ScanMode::Mixed` which save one seek() and several prev() calls
(before has no tombstone statistics for seek, actually there are a lot) 
Tests 
- Unit test
- Optimize seek write for many …

storage: Optimize seek write for many tombstones (#8514)

---

Cargo.lock
components/concurrency_manager/Cargo.toml

When checking memory locks of a range, memory leaks happen.
It's due to a bug in crossbeam-skiplist. I fix it in [my own branch](https://github.com/sticnarf/crossbeam/commit/312812c95386bd3d949bb08ebee7b8950ce4aa38) and this PR will fix it.
Fixed in upstream: https://github.com/crossbeam-rs/crossbeam/pull/673
Tests 
Run long-running tests to see if memory leaks still exist manually.
- Fix memory leaks when checking a range for memory locks.

concurrency manager: fix a memory leak when iterating skiplist

---

src/server/config.rs

Issue Number: close #9699 
Problem Summary: Labels can be specified via TiKV's config file and it will be then reported to PD. However the format constraint of labels is not consistent between TiKV and PD. This PR changes TiKV's format constraint so that more formats are allowed, so that it's now consistent with PD.
What's Changed: Updated format constraint of labels in TiKV's config file.
- It depends
Tests 
- Unit test
Side effects
-
* Make the format constraint of labels consistent with PD's.

config: Make labels' format constaint consistent with PD

---

components/raftstore/src/store/fsm/peer.rs
tests/integrations/raftstore/test_split_region.rs

Close #9691.
More regions so that client can make decisions without PD, which should
reduce region miss in high load.
Tests 
- Unit test
- set more regions in EpochNotMatch to reduce region miss

raftstore: return more regions in EpochNotMatch

---

components/raftstore/src/lib.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/util.rs

Issue Number: close #9748 
See https://github.com/tikv/tikv/issues/9748
Use `VecDeque::binary_search_by_key` to find proposal
Tests 
- Unit test
- raftstore: fix find_propose_time may return older instant

raftstore: fix find_propose_time may return older instant

---

components/backup/src/endpoint.rs
components/cdc/src/observer.rs
components/engine_traits/src/options.rs
src/server/raftkv.rs
src/storage/kv/btree_engine.rs
src/storage/kv/cursor.rs
src/storage/kv/mod.rs
src/storage/kv/rocksdb_engine.rs
src/storage/mod.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/mod.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/store.rs
tests/integrations/storage/test_raftkv.rs

A prerequisite change of #9758, so TTLIterator can wrap RegionIterator directly
Change iter() of Snapshot trait from
```rust
fn iter(&self, iter_opt: IterOptions, mode: ScanMode) -> EngineResult<Cursor<Self::Iter>> 
```
to 
```rust
fn iter(&self, iter_opt: IterOptions) -> EngineResult<Self::Iter> 
```
Tests 
- No code
- None

storage: Make snapshot trait return iterator instead of cursor

---

components/raftstore/src/store/worker/split_controller.rs

Add end key as sample key in key range for load base split;
Ensure `sample` can collect enough keys.
Tests 
- Unit test
- No Release note

Add end key as sample key in key range for load base split

---

components/raftstore/src/store/metrics.rs
components/raftstore/src/store/worker/split_controller.rs
components/tidb_query_executors/src/index_scan_executor.rs
metrics/grafana/tikv_details.json

Add and imporve metrics for load base split
~~For `READ_QPS_TOPN`, in the past we only collected the qps of the top ten regions that exceeded the threshold, now we collect the qps of all regions that exceed the threshold, considering that there are some regions whose qps is no longer higher than the threshold after a period of time, so to avoid trailing, we set the qps of these regions to 0.~~
We also add `LOAD_BASE_SPLIT_EVENT` to confirm the status of load base split, and introduce four events: 
1. `prepare_to_split` means that a suitable split key has been selected and is ready to be sent to `ask_batch_split`. 
2. `no_fit_key` means that no suitable split key is selected
~~3. `size_or_keys_too_small` means that `approximate_size` or `approximate_keys` …

Add metrics for load base split

---

components/raftstore/src/store/worker/split_config.rs

Issue Number: close #9816
#9794 breaks backward compatibility. This PR will fix it.
Tests 
- Unit test
- No Release note

fix backward compatibility in load base split config

---

Cargo.lock
components/engine_rocks/Cargo.toml

Problem Summary: Cut branch in rocksdb/titan/rust-rocksdb repo for TiKV 5.0 release. Nothing is changed except for the branch name.
What's Changed: switch to `tikv-5.0` branch of rust-rocksdb. No code change.
No
Tests 
- CI
- No release notes.

cut rust-rocksdb branch for 5.0 release

---

etc/config-template.toml
src/server/gc_worker/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

enable GC in compaction filter by default.
Tests 
- No code
Side effects

enable GC in compaction filter by default

---

Cargo.lock
components/file_system/Cargo.toml
components/file_system/src/lib.rs
components/file_system/src/metrics_manager.rs
components/file_system/src/rate_limiter.rs

Problem Summary: replace outdated `varaint_count` dependency with `strum`.
- No
Tests 
- No code
Side effects
- No

file_system: replace variant_count with strum

---

src/storage/txn/actions/prewrite.rs
tests/failpoints/cases/test_transaction.rs

The `pessimistic_prewrite` failpoint is lost after some refactors, leading to some tests failure using the master branch.
Try to add back the failpoint. 
Maybe it's better to seperate the `pessimistic_prewrite` and `optimistic_prewrite` code path.
- Unit test
Side effects

txn: add the pessimistic prewrite failpoint

---

components/tidb_query_expr/src/impl_compare_in.rs
components/tidb_query_expr/src/lib.rs

Issue Number: close #9821
Problem Summary: IN expr didn't distinguish between unsigned int and signed int. So -1(bigint) equals 18446744073709551615(bigint unsigned), which is not compatible with MySQL. Here is [TiDB issue](https://github.com/pingcap/tidb/issues/23198).
What's Changed: Add a fn_meta for IN expr when first arg of IN expr is INT type. In this function, we use info which records arg's flag to tell whether two integer is really equal.
Tests 
- Unit test : impl_compare_in.rs: test_unsigned_signed_int()
Side effects:
- performance regression: To fix this issue, we need to check argument's signed/unsigned flag. Also we use HashMap instread HashSet. So maybe little performance regression.
- fix IN expr(coprocessor) didn't handle …

copr: fix IN expr didn't handle unsigned/signed int properly

---

Cargo.lock
components/tikv_kv/Cargo.toml
components/tikv_kv/src/btree_engine.rs
components/tikv_kv/src/lib.rs
src/server/raftkv.rs

Issue: https://github.com/tikv/tikv/issues/9609
tikv_kv uses engine_rocks directly and it should not.
- Remove the get_properties / get_properties_cf methods from tikv_kv::Engine trait. These are fortunately unused.
- Use PanicEngine instead of RocksEngine as an unimplemented placeholder in BTreeEngine
- Ultimately no concrete engine should be used here, but this is an easy way to get rid of RocksEngine, and PanicEngine is more semantically appropriate here.

Remove two uses of engine_rocks from tikv_kv

---

components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs
components/test_raftstore/src/server.rs
components/txn_types/src/types.rs
src/storage/txn/commands/prewrite.rs

Previously we refactored the logic about old-value in the transaction layer (see #9173). This introduces a bug that the old-value cache will be always missed because the key of the cache doesn't contains `start ts`.
* Append start ts to the key of the cache
* Make insert operations updating the cache
* Make the cache works in the tests
Tests 
- Unit test
* cdc: fix old value cache maybe always missed

cdc: fix old value cache may always missed

---

components/cdc/src/observer.rs
components/cdc/tests/integrations/test_cdc.rs

If an insert operation has an old value, tikv would be panic by an assertion.
Delete the assertion.
Tests 
- Unit test
* N/A

cdc: fix panic caused by insert

---

src/storage/txn/actions/prewrite.rs
src/storage/txn/commands/mod.rs
src/storage/txn/commands/prewrite.rs
tests/failpoints/cases/test_transaction.rs
tests/integrations/server/kv_service.rs

Issue Number: close https://github.com/pingcap/tidb/issues/23477
`Prewrite` is not idempotent when falling back to 2PC:
1. A async-commit prewrite request succeeded in writing a fallback lock. Its response is `min_commit_ts == 0`.
2. Following duplicated prewrite requests returns `min_commit_ts != 0` which makes clients think it can go on with async-commit protocol.
Make prewrite idempotent.
Tests 
- Unit test
Side effects

txn: make prewrite idempotent when falling back to 2PC

---

src/storage/txn/actions/prewrite.rs

TiKV always returns min_commit_ts=0 for `check_not_exists` operations. It may result in unnecessary falling back for async commit.
`check_not_exists` operations don't write locks or change data, so we needn't ask the concurrency manager for the max_ts. Its min_commit_ts is `max(start_ts + 1, req.min_commit_ts)`.
Tests 
- Unit test
Side effects

txn: return min_commit_ts for check_not_exists

---

components/pd_client/src/lib.rs
components/pd_client/src/metrics.rs
components/pd_client/src/util.rs
components/test_pd/src/mocker/leader_change.rs
components/test_pd/src/mocker/retry.rs
components/test_pd/src/mocker/service.rs
metrics/grafana/tikv_details.json
src/server/status_server/mod.rs
tests/failpoints/cases/test_pd_client.rs
tests/integrations/pd/test_rpc_client.rs

cherry-pick #9840 to release-4.0
cherry-pick #9880 to release-4.0
cherry-pick a part of #9501 to release-4.0 (related #9548)
Issue Number: related #9799
Too many uninterrupted reconnection.
* Cancel some unnecessary reconnection.
* Add reconnect metrics.
* Optimize the test.
* Need to cherry-pick to the release branch
Tests
* Unit test
* Manual test
* 3 PD / 3 TiKV / 1000 Region
* Manually make PD no leader
* Add metrics (will be in another PR)
* Before ![image](https://user-images.githubusercontent.com/19789302/111725356-e2bbc200-88a1-11eb-84d8-8a357ae88e69.png)
* After ![image](https://user-images.githubusercontent.com/19789302/111726549-24e60300-88a4-11eb-9dda-5c5f16e6f3f0.png)
* pd_client: prevent a large number of reconnections in a short time

pd_client: prevent a large number of reconnections in a short time (#9840)

---

Cargo.lock
components/test_storage/src/sync_storage.rs
src/server/metrics.rs
src/server/service/kv.rs
src/storage/metrics.rs
src/storage/mod.rs
src/storage/txn/commands/atomic_store.rs
src/storage/txn/commands/compare_and_swap.rs
src/storage/txn/commands/mod.rs
src/storage/txn/mod.rs
src/storage/types.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/server/kv_service.rs
tests/integrations/server/mod.rs
tests/integrations/storage/test_raft_storage.rs

When comparison failed, the previous RawCAS implementation can't distinguish the previous value between empty value and none value.
[kvproto changes](https://github.com/pingcap/kvproto/pull/742)
- Renamed `compare_and_set` to `compare_and_swap`
- In the `RawCASRespond`, return `succeed` instead `not_equal`
- Add `previous_not_exist` to `RawCASRespond`
Tests 
- Unit test

storage: implement proper sematic for RawCAS

---

components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/snap.rs
components/raftstore/src/store/worker/pd.rs

Issue Number: close #9896 .
Before the patch the snap directory size is tracked in memory. However it's hard to handle `mv *.sst.tmp *.sst` if the target path exists. Besides this maybe there are still other unknown bugs.
This PR calculates the snap directory size by scan. This operation is moved to the PD worker thread from raftstore threads. A benchmark in #9896 shows that the scan won't hurt performance too much.
Tests 
- Unit test
- Manual test
With the patch store-used-size is very close to engine-size:
Without the patch store-used-size becomes far from engine-size after about 6 hours:

calculate snap dir size by scan

---

cmd/src/server.rs
etc/config-template.toml
src/storage/config.rs

Remove the space reserving upper limit because the upper limit(20GB) is not enough.
Issue Number: close #9831 .
Tests 
- No code

remove the upper limit for space reserving

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/metrics.rs
components/cdc/src/observer.rs
components/cdc/src/service.rs
components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs
src/config.rs
src/storage/txn/store.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Problem Summary: Limit TiKV CDC scan speed to avoid OOM.
Tests 
- Unit test
TiKV keeps OOM on the left of the above graph. With this PR TiKV does not OOM and keeps in constant memory consumption. 
- Limit CDC scan speed to avoid OOM.

cdc: limit scan speed

---

components/encryption/src/errors.rs
components/encryption/src/file_dict_file.rs
components/encryption/src/lib.rs
components/error_code/src/encryption.rs
tests/failpoints/cases/mod.rs
tests/failpoints/cases/test_encryption.rs

Issue Number: close #9886 
When the file dict fails to be appended and written for some reason, we believe that this record can be safely discarded because the corresponding file has not been actually modified
Add a new error type and ignore these errors.
- Need to cherry-pick to the release-4.x
Tests 
- Unit test
- No code
Side effects
N/A
- Fix the bug that TiKV cannot startup when the end of file dict file is damaged.

encryption: Ignore log record parse error caused by write failure before

---

components/raftstore/src/store/snap.rs
components/raftstore/src/store/snap/io.rs

close https://github.com/tikv/tikv/issues/9945.
migrate region cause the compression ratio is difference in each TiKV. because the snapshot is used `lz4` and most of the data in rocksdb (lower layers) are used `zstd`.
Tests 
**Note** : size amplification = store_total_region_size / store_disk_usage
- Before:
- After:
-  use `zstd` to compress the snapshot

snap: use zstd to compress the snapshot

---

components/txn_types/src/lock.rs
src/storage/txn/actions/prewrite.rs

The log would be like
[WARN] [prewrite.rs:418] ["commit_ts is too large, fallback to normal 2PC"] [lock="Lock { lock_type: Put, primary_key: 7480000000000000CA5F69800000000000000103800000000000001E, start_ts: TimeStamp(423917153942241283), ttl: 3001, short_value: 000000000000005A, for_update_ts: TimeStamp(0), txn_size: 2, min_commit_ts: TimeStamp(423917153942241284), use_async_commit: true, secondaries: [], rollback_ts: [] }"] [max_commit_ts=423917154467053571] [min_commit_ts=423917154571124747] [start_ts=423917153942241283] [key=7480000000000000FFCA5F698000000000FF0000010380000000FF0000005A00000000FB]
Print more info when fallback happens:
- From the `key` info, we could know which prewrite batch it is, and from which key the …

txn: add more log info for fallback

---

Cargo.toml
components/server/Cargo.toml

From some time ago, build with `PROST=1` receives error like:
```
error[E0592]: duplicate definitions with name `generate_files`
--> /home/yilin/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-build-0.12.0/src/protobuf_impl.rs:63:5
|
63 |     pub fn generate_files(&self) {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ duplicate definitions for `generate_files`
|
::: /home/yilin/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-build-0.12.0/src/prost_impl.rs:5:5
|
5  |     pub fn generate_files(&self) {
|     ---------------------------- other definition for `generate_files`
error: aborting due to previous error
```
This is because some components depend on protobuf-codec unconditionally. https://github.com/tikv/tikv/pull/9969 should fix most of previous mistakes but my #8793 …

*: make PROST work again

---

components/tikv_util/src/lib.rs
src/server/status_server/mod.rs

I noticed that the panic message was missing from the output.
Adding a very small sleep fixed this. I did try some other approaches to flushing, but I couldn't get any of them to work.
Additionally TiKV will now print out the panic error message just by itself as the very last output: this avoids having to look up past the stacktrace.
I also added a status server API `/debug/fail_point`. It can be used like this to trigger a panic, but it requires setting the feature `failpoints`.
Tests
- Manual test before and after
```
curl localhost:20180/fail/debug_fail_point -X PUT -d 'panic'
curl localhost:20180/debug/fail_point
```
Side effects
Additional 2ms sleep before abort.
* Ensure panic output is flushed to the log

ensure the panic log is flushed

---

components/raftstore/src/store/peer.rs

Issue Number: close #9980 
The `raft-r`'s `pr.committed_index` may be inaccurate (see https://github.com/tikv/raft-rs/issues/426) and cause panic on `pre_propose_prepare_merge` check
Replace the assert with a warning log since the assert just for robustness and is not a fatal error if it fail
Tests 
- No code

raftstore: remove unnecessary assert on merge check

---

components/tidb_query_expr/src/impl_cast.rs

Issue Number: close #9970
The underlying bytes of a string may not be valid UTF-8 bytes. It is unsafe to convert it to a `str` without checking. In #9970, it causes a panic when calling `trim` on the `str`.
Tests 
- Unit test
- Fix potential panics when input of cast_string_as_time is invalid UTF-8 bytes

tidb_query: fix panic when input of cast_string_as_time is invalid UTF-8 bytes

---

metrics/grafana/tikv_details.json

Issue Number: close #10003 
Problem Summary: Fix the lack of backup & import CPU in `Thread CPU`.
copy backup & import CPU panels to Thread CPU.
Tests 

grafana: update backup & import CPU to Thread CPU panels.

---

Cargo.lock
Cargo.toml
src/coprocessor_v2/plugin_registry.rs

Implements hot-reloading for coprocessor plugins, similar to the PoC.
Also adds some more public methods for `PluginRegistry` to deal with loaded plugins, e.g. the ability to unload plugins.
Again, I added some questions in `TODO` comments.
Issue Number: #9747 
The coprocessor plugin framework should watch a "plugin directory" and automatically load/unload plugins that are created/deleted in the directory.
Proposal: [RFC](https://github.com/tikv/rfcs/pull/63) 
- based on PR #9912 
Tests 
- Unit test
* No release notes

coprv2: hot-reloading of plugins

---

src/storage/txn/commands/macros.rs
src/storage/txn/commands/mod.rs
src/storage/txn/latch.rs
src/storage/txn/scheduler.rs

`latches` is not used when `gen_lock()`
remove `latches` when `gen_lock()`

txn: don't pass latches in when gen_lock()

---

components/tikv_util/src/sys/cpu_time.rs

#10023 makes TiKV fail to build on macOS.
Fix the compile failure.
Tests 
Compile it on macOS.

tikv_util: fix compile errors on macOS

---

components/tidb_query_aggr/src/impl_avg.rs
components/tidb_query_aggr/src/impl_count.rs
components/tidb_query_aggr/src/impl_first.rs
components/tidb_query_aggr/src/impl_max_min.rs
components/tidb_query_aggr/src/impl_sum.rs
components/tidb_query_aggr/src/impl_variance.rs
components/tidb_query_datatype/src/codec/data_type/chunked_vec_enum.rs
components/tidb_query_datatype/src/codec/data_type/mod.rs
components/tidb_query_datatype/src/codec/mysql/enums.rs
components/tidb_query_expr/src/impl_cast.rs

Signed-off-by: Alex Chi <iskyzh@gmail.com>
As pointed out by @sticnarf https://github.com/tikv/tikv/pull/9648#pullrequestreview-643187256 , transmute of enum value is unsound. This PR intends to fix this.
<del>For the first step, we just let the compiler fail. I'll propose a fix soon.</del>
Now we have made all transmute sound by retaining lifetime `retain_lifetime_transmute`.
Tests 
- Unit test
Side effects

copr: fix unsound unsafe transmute

---

components/tidb_query_aggr/src/impl_max_min.rs
components/tidb_query_datatype/src/codec/batch/lazy_column.rs
components/tidb_query_datatype/src/codec/collation/collator/mod.rs
components/tidb_query_datatype/src/codec/collation/mod.rs
components/tidb_query_datatype/src/codec/data_type/mod.rs
components/tidb_query_datatype/src/codec/data_type/scalar.rs
components/tidb_query_datatype/src/codec/data_type/vector.rs
components/tidb_query_datatype/src/lib.rs
components/tidb_query_executors/src/fast_hash_aggr_executor.rs
components/tidb_query_executors/src/lib.rs
components/tidb_query_executors/src/selection_executor.rs
components/tidb_query_executors/src/simple_aggr_executor.rs
components/tidb_query_executors/src/stream_aggr_executor.rs
components/tidb_query_executors/src/util/hash_aggr_helper.rs
components/tidb_query_expr/src/lib.rs
components/tidb_query_expr/src/types/expr_builder.rs
src/coprocessor/statistics/analyze.rs

Now, we use declarative macros whose syntax looks like `macro xxx() {}`, and need to enable the unstable feature [`decl_macro`](https://doc.rust-lang.org/unstable-book/language-features/decl-macro.html).
The IDE support for declarative macros isn't provided well; it's hard to resolve and expand it on IDE, therefore, it brings poor dev experience.
Replace declarative macros with `macro_rules`.
Tests 
- No code
- Clean up declarative macros

tidb_query: use macro_rules instead of declarative macros

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/util.rs

`lazy_static` + `Hashmap` introduces much overhead.
Use `match` instead.
Benches:
```rust
lazy_static! {
pub static ref ADMIN_CMD_EPOCH_MAP: HashMap<AdminCmdType, AdminCmdEpochState> = [
(AdminCmdType::InvalidAdmin, AdminCmdEpochState::new(false, false, false, false)),
(AdminCmdType::CompactLog, AdminCmdEpochState::new(false, false, false, false)),
(AdminCmdType::ComputeHash, AdminCmdEpochState::new(false, false, false, false)),
(AdminCmdType::VerifyHash, AdminCmdEpochState::new(false, false, false, false)),
// Change peer
(AdminCmdType::ChangePeer, AdminCmdEpochState::new(false, true, false, true)),
(AdminCmdType::ChangePeerV2, AdminCmdEpochState::new(false, true, false, true)),
// Split …
```

raftstore: faster lookup for admin epoch checker

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/read_queue.rs

Make the code a little bit readable further.
Found that `renew_lease_time` is like in the perspective of a peer, however, it's occupied as a field of `Proposal`. I think `propose_time` is a suitable name since it's meaningful for a `Proposal`.
- Tiny refactor

raftstore: rename `renew_lease_time` to `propose_time`

---

Cargo.lock
components/coprocessor_plugin_api/Cargo.toml
components/coprocessor_plugin_api/build.rs
components/coprocessor_plugin_api/src/util.rs
src/coprocessor_v2/plugin_registry.rs

Introduces version checks for API version and rustc version of plugins.
Issue Number: #9747 
When loading a coprocessor plugin, we need to make sure that it actually runs. 
Thus, we need to make sure that the following things match up:
* the version of the `coprocessor_plugin_api` crate the plugin was compiled with.
* the rustc version the plugin was compiled with (has to be the same as the rustc version TiKV was compiled with because Rust does not guarantee a stable ABI)
* the `target` platform the plugin was compiled for and the target platform of TiKV
All in all, it is very similar to the [POC](https://github.com/andylokandy/plugin).
Proposal: [Coprocessor V2 RFC](https://github.com/andylokandy/rfcs/blob/plugin/text/2021-02-24-coprocessor-plugin.md) 
- …

coprv2: plugin version checks

---

Cargo.lock
Cargo.toml
components/coprocessor_plugin_api/src/plugin_api.rs
components/coprocessor_plugin_api/src/util.rs
components/test_coprocessor_plugin/example_plugin/src/lib.rs
src/coprocessor_v2/endpoint.rs
src/coprocessor_v2/plugin_registry.rs

This PR add the ability to check plugin version on coprocessor requests.
We now collect the plugin version in `declare_plugin!` macro (either passed explicitly or from Cargo.toml).
When calling the new coprocessor endpoint, we now check whether the loaded plugin does satisfy `copr_version_constraint`.
Issue Number: #9747  
Proposal: [RFC](https://github.com/andylokandy/rfcs/blob/plugin/text/2021-02-24-coprocessor-plugin.md) 
Tests 
- Unit test

coprv2: check plugin version on coprocessor requests

---

components/engine_traits/src/engine.rs
components/test_raftstore/src/server.rs
src/server/raft_client.rs
src/server/server.rs
src/server/transport.rs
tests/integrations/server/raft_client.rs

Making the tikv crate generic over storage engines.
Part of https://github.com/tikv/tikv/issues/6402
Just replacing instances of RocksEngine with KvEngine-bound type parameters in the tikv::server module.
I discovered that KvEngines need to be Unpin here, so I went ahead and made all KvEngines Unpin so engine authors can find that out early.

Replace some RocksEngine with KvEngine type parameters in tikv::server

---

components/encryption/src/errors.rs
components/encryption/src/file_dict_file.rs
components/encryption/src/lib.rs
components/error_code/src/encryption.rs
tests/failpoints/cases/mod.rs
tests/failpoints/cases/test_encryption.rs

git push --set-upstream origin xt/pick-9938
Signed-off-by: Xintao hunterlxt@live.com
Issue Number: close #9886
When the file dict fails to be appended and written for some reason, we believe that this record can be safely discarded because the corresponding file has not been actually modified
Add a new error type and ignore these errors.
Need to cherry-pick to the release-4.x
Tests
Unit test
Integration test
Manual test (add detailed scripts or steps below)
No code
Side effects
N/A
- Fix the bug that TiKV cannot startup when the end of file dict file is damaged.

encryption: Ignore log record parse error caused by write failure before (#9938)

---

Cargo.lock
Cargo.toml
build.rs
src/coprocessor_v2/plugin_registry.rs

Signed-off-by: Andreas Zimmerer <andreas.zimmerer@tum.de>
Issue Number: #9747  
**[do not merge yet; PR currently only for experimenting with the CI]**
Previously, we commented out the tests because they always failed in CI. Why? Because they require `libexample_plugin.so`, which is being built by Cargo, but then not uploaded as an "artifact" for when the tests are executed.
We came to the conclusion, that we should somehow use `include_bytes!()` to include the library into the tests. This PR tries to fix this.
Proposal: [RFC](https://github.com/tikv/rfcs/pull/63) 
Tests 
- Unit test

coprv2: enable tests for plugins

---

src/server/lock_manager/deadlock.rs
src/server/lock_manager/mod.rs

More work on making tikv generic over engines.
https://github.com/tikv/tikv/issues/6402
This replaces all uses of RocksEngine in tikv::server::lock_manager with either `impl KvEngine`, or, in test cases, KvTestEngine.

Replace RocksEngine with KvEngine in lock manager

---

components/resolved_ts/src/cmd.rs
components/resolved_ts/tests/integrations/mod.rs

For now `resolved_ts` worker can not work on rawkv mode.
A temporary solution that skips the default cf commands which do not has valid ts.
From @NingLin-P, in the next step, we could skip the default cf commands in apply worker if cdc doesn't need to observe the region. That will solve this problem fundamentally.
Tests 
- Unit test
* N/A

resolved_ts: skip default cf cmd with invalid ts

---

Cargo.lock
components/batch-system/benches/batch-system.rs
components/resolved_ts/Cargo.toml
components/resolved_ts/src/cmd.rs
components/resolved_ts/tests/integrations/mod.rs

Filter out invalid default cf value by delaying matching it with write or lock.
Tests 
- Unit test
* N/A

resolved_ts: delay matching default cf

---

components/tikv_util/src/config.rs

Normalize the path by lexical rules, then try iteratively canonicalize the result.
Tests 
- Unit test

properly canonicalize non-existing path

---

components/cdc/src/endpoint.rs

It's a cherry-pick of #10133.
---------
To avoid consume too much memory when there are many concurrent
scan tasks (peak memory = 1MB * N tasks), we reduce the size
to 16KB as a workaround.
Issue Number: #10114 
Tests 
To be added:
- Reduce memory usage of CDC initial scan.

cdc: reduce scan batch bytes

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/lib.rs
components/cdc/src/observer.rs
components/cdc/src/old_value.rs

Code related to old value exists in serval files.
Reorg them into one separate file.
Tests 
- Unit test
* N/A

cdc: move old value code to a separate file

---

components/cdc/tests/integrations/test_cdc.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/txn.rs

Issue Number: #9996 #9981
Reading old value costs too much CPU for CDC endpoint thread, leading to OOM. 
Always read old value in txn layer when cdc requires old value.
Tests 
- Unit test
Fix CDC OOM issue caused by reading old values.

cdc, mvcc: always read old value when cdc requires

---

Cargo.lock
components/cdc/Cargo.toml
components/cdc/src/endpoint.rs
components/raftstore/src/store/worker/read.rs

This is a cherry-pick of #10206.
------------
Issue Number: close #10118 
Remove panic, `compare_exchange` is expected to fail when downstream does not require old value.
Tests 
- Unit test
- No release note. (The bug is not released yet.)

cdc: fix deregister panic when old value is not enabled (#10206)

---

Cargo.lock
components/cdc/Cargo.toml
components/cdc/src/endpoint.rs
components/external_storage/export/src/export.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/worker/mod.rs
components/raftstore/src/store/worker/read.rs

Issue Number: close #10118 
Remove panic, `compare_exchange` is expected to fail when downstream does not require old value.
Tests 
- Unit test
- No release note. (The bug is not released yet.)

cdc: fix deregister panic when old value is not enabled

---

components/error_code/src/storage.rs
src/storage/errors.rs
src/storage/txn/scheduler.rs
tests/failpoints/cases/test_storage.rs

Part of #10166 
When `max_execution_duration_ms` in `Context` is set, we check whether the deadline is exceeded before acquiring the latches. So a scheduler command that waits in the scheduler for too long will not execute to waste resource.
Tests 
- Unit test
- Check deadline before executing scheduler command

storage: check deadline before executing scheduler command

---

components/server/src/setup.rs

If `log-file` isn't specified, info log of rocksdb and raftdb will be print into `stderr`, just like TiKV's log. It makes the output hard to read.
Always print two engines' info log into `*.info` in data directory. It's reasonable because the data directory is always available whatever `log-file` is specified or not.
Tests 
- No code

always put engine info log into data dir

---

components/tidb_query_datatype/src/def/field_type.rs
components/tidb_query_executors/src/index_scan_executor.rs

Issue Number: close https://github.com/pingcap/tidb/issues/24548
`Latin1Bin` didn't be  judged as Bin collation 
`Latin1Bin` should be judged as Bin collation 
- Need to cherry-pick to the release branch 5.0
Tests 
- Unit test
Side effects
- n/a
- Fix read empty value for the clustered primary key column in the secondary index when collation is latin1_bin.

tidb_query: fix read empty value for the clustered PK column in the 2nd index with latin1_bin

---

components/tikv_util/src/sys/mod.rs

Issue Number: close #10248 
Problem Summary: `#[cfg(target_os = "linux")]` is in wrong place which is introduced by #10231 
What's Changed: This PR puts it in the right place.
Tests 
- Manual test 

*: fix build when using MacOS

---

components/test_storage/src/assert_storage.rs
components/test_storage/src/sync_storage.rs
metrics/grafana/tikv_details.json
src/read_pool.rs
src/server/metrics.rs
src/server/server.rs
src/server/service/batch.rs
src/server/service/kv.rs
src/storage/mod.rs

cherry-pick #10098 to release-5.0
----
Issue Number:  close #10046
If the CPU load of TiKV read pool is not very high, batch get request together may cause latency increase. Because batchrequest process every sub request one by one in order, but if you put them into readpool, they can be processed in parallel.
I judge whether the readpool is busy by readpool queue length. If the queue length is very long, TiKV will batch request together, otherwise it will put them into readpool separately.
We can see that this PR fixes QPS regression and makes lower P99 latency in TiKV than master without batch.
- PR to update …

storage: optimize strategy of batch commands 

---

components/cloud/aws/src/s3.rs

#9706 miss the region config for s3 storage. will cause error `The bucket you are attempting to access must be addressed using the specified endpoint.` This PR fix it.
set region config.
- Need to cherry-pick to the release branch after #9706 pick to release.
Tests 
- Unit test
```
[root@CentOS76_VM s3_region]# AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxx./br restore table --db sysbench --table sbtest1 --pd 127.0.0.1:2379 -s s3://dbaas-benchmark/xxx/ --s3.region us-west-2 --check-requirements=false
Detail BR log in /tmp/br.log.2021-05-25T13.08.09+0800
Table restore <-----------------------------------------------------------/....................................................> 53.25%Table restore …
```

cloud: fix missing region config for aws

---

components/raftstore/src/store/config.rs

Turn on hibernate regions by default. Hibernate region is crucial to reduce raftstore heartbeat CPU usage, especially for clusters with high number of regions. Hibernate region was enabled by default only on master (i.e. nightly build). This PR enable it by default.
Hibernate region RFC: https://github.com/tikv/rfcs/blob/master/text/2019-03-04-hibernate-raft.md
What's Changed: Turn on hibernate regions by default. 
- Need to cherry-pick to the release branch: release-5.0, for 5.0.2 release.
Tests 
- See https://github.com/tikv/tikv/projects/48 for previous issues and improvements for hibernate regions.
Side effects
- Expected to reduce raftstore heartbeat CPU usage, especially for clusters with many regions.
- Enable hibernate …

raftstore: enable hibernate regions by default

---

tests/integrations/raftstore/test_replica_read.rs

https://github.com/tikv/tikv/pull/10273#issuecomment-851829389 reports that `test_read_index_retry_lock_checking` always fails.
The failure is on the first `async_read_index_on_peer`. Previously the election timeout is set to very short, then an election may happen before the read. So we receive a `Stale command` error instead of waiting.
This PR increases election timeout to solve the problem.
Tests 
- Unit test
```release-note
None
```

tests: fix flaky test_read_index_retry_lock_checking

---

components/cdc/src/endpoint.rs

cherry-pick #10285 to release-5.0 
----
The `ResolvedTs` name is not imported when using prost-codec, making the code fail to compile there.
Add back the import.
* release-5.0, release-4.0
Tests 
* make build with prost codec 🤷
Side effects
```release-note
None
```

cdc: fix missing ResolvedTs import in prost-codec (#10285)

---

components/file_system/src/rate_limiter.rs

Issue Number: close #10303 close #10306
test_rate_limited_hybrid_flow and test_rate_limited_light_flow sometimes failed in rush hours.
Reduce number of threads spawned in test (from 6 to 3), and tune up tolerance (from 10% to 15%).
Tests 
- Unit test
```release-note
None
```

tests: fix flaky test_rate_limited_*_flow

---

components/raftstore/src/store/fsm/apply.rs
components/sst_importer/src/metrics.rs
components/sst_importer/src/sst_importer.rs
components/test_sst_importer/src/lib.rs

cherry-pick #9686 to release-5.1
Ingest costs more time than other operations. It will cause high latency of apply-wait.
To reduce the impact on apply-wait latency, this PR collect multiple ingest requests and ingest them at a time.
Tests 
- Unit test
Side effects
- support batch ingest in raftstore

raftstore: support batch ingest

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/errors.rs
components/cdc/src/observer.rs
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

cherry-pick #10262 to release-5.1
-----------
Close https://github.com/tikv/tikv/issues/10114
Close https://github.com/pingcap/ticdc/issues/1844
Limit CDC scan concurrency.
Tests 
- Unit test
- Manual test
Tested with TiCDC v4.0.13
<b style="font-weight:normal;" ><div dir="ltr" style="margin-left:0pt;" align="left">
v5.0.2 | This PR
-- | --
</div></b>
```release-note
Fix OOM when TiCDC resumes a changefeed in a cluster that has lots of regions being captured. 
```

cdc: limit scan task concurrency (#10262)

---

components/resolved_ts/src/scanner.rs
tests/failpoints/cases/test_replica_stale_read.rs

The `resolved-ts` worker scan pessimistic lock and tracking them, which should be ignored (like how cdc behave), because the pessimistic lock just for blocking incoming write not incoming read, tracking these lock may cause `safe_ts` can't be updated.
Filter pessimistic lock  while scanning lock
```release-note
resolved_ts: ignore pessimistic lock while scanning locks
```

resolved_ts: ignore pessimistic lock while scanning locks

---

components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/local_metrics.rs
components/raftstore/src/store/metrics.rs
components/resolved_ts/src/advance.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/src/metrics.rs
components/resolved_ts/src/resolver.rs
metrics/grafana/tikv_details.json

This PR mainly change the `Resolved TS gap` from `Histogram` to `IntGaugeVec` and add the `Fail advance ts count` panel:
Tests 
- No code
Side effects
```release-note
resolved_ts: refine the `Resolved TS gap` panel and add the `Fail advance ts count` panel
```

resolved_ts: refine the resolved ts metric and panels

---

components/raftstore/src/store/peer_storage.rs

Fix a panic in `EntryCache::append`. The panic stack:
```
thread 'raftstore-1-1::test_node_leader_change_with_log_overlap' panicked at 'assertion failed: cached_last < truncate_to as u64', components/raftstore/src/store/peer_storage.rs:198:21
stack backtrace:
0: rust_begin_unwind
at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
1: core::panicking::panic_fmt
at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
2: core::panicking::panic
at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:50:5
3: raftstore::store::peer_storage::EntryCache::append_impl
at /home/jay/Documents/workspace/tikv/components/raftstore/src/store/peer_storage.rs:198:21
4: …
```

raftstore: fix a panic about EntryCache::append

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/msg.rs
tests/integrations/raftstore/test_stale_peer.rs

If a leader receives the message from a stale peer(follower or learner), it may not reply to this peer a tombstone msg which may cause a stale region can not be destroyed for a long time. 
Also, https://github.com/tikv/tikv/issues/10341 the problem described here can be alleviated.
Since the number of msg from stale peers should be small, this PR totally removes the condition of whether to send tombstone msg or not. 
Tests 
Side effects
- No
```release-note
None
```

raftstore: reply to stale peer with tombstone message everytime

---

components/batch-system/src/batch.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/pd.rs
components/server/src/server.rs
components/test_coprocessor/src/fixture.rs
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/pd.rs
components/test_raftstore/src/server.rs
components/tikv_util/src/callback.rs
components/tikv_util/src/lib.rs
components/tikv_util/src/thread_group.rs
components/tikv_util/src/time.rs
components/tikv_util/src/timer.rs
components/tikv_util/src/worker/future.rs
components/tikv_util/src/yatp_pool/mod.rs
src/import/sst_service.rs
src/server/debug.rs
src/server/gc_worker/gc_manager.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/server/gc_worker.rs

Issue Number:
close #10353 
close #10307 
If callbacks are cleared during shutdown, latch may not work as expected
as it expects deterministic result. So this PR drops all callbacks
instead of invoking.
Tests 
- Unit test
```release-note
skip clearing callback during gracefully shutdown to avoid breaking ACID in some cases
```

raftstore: skip clearing callback when shutdown

---

components/sst_importer/src/sst_importer.rs
components/test_sst_importer/src/lib.rs
src/import/sst_service.rs

Issue Number: close https://github.com/pingcap/br/issues/1179
After change `rename file` to `link file` in https://github.com/tikv/tikv/pull/9285/, TiKV will have an external [check](https://github.com/hunterlxt/tikv/blob/9d123f7b03c57679bbf410540ad05b1265ae441b/components/encryption/src/manager/mod.rs#L338-L344). which makes restore fail due to sst_importer will create an empty file in sst writer[#build](https://github.com/tikv/tikv/blob/bfc3c47d3ae6d34065892ddcd59f8599b7e59214/src/import/sst_service.rs#L309). 
This bug happenned when TDE enabled.
This PR tries to fix it by move sst_writer#buid into download after link_file. …

sst_importer: fix the file exists issue in link file

---

components/test_raftstore/src/util.rs
src/coprocessor/endpoint.rs
src/storage/mod.rs
tests/failpoints/cases/test_replica_stale_read.rs

Currently, if we use a future ts as the `start_ts` of stale read transaction, the stale read request will be rejected by TiKV with the `DataIsNotReady` error until the `resolved_ts` is catch up with the future ts. 
But before the request is rejected, we use its `starte_ts` to update the `max_ts`, because the `starte_ts` is a future ts which will result in the commit request reject by `commit_ts_expired` error and keep retrying, also 1pc transaction will fallback to 2pc.
Don't update the `max_ts` with the `start_ts` from a stale read transaction, it is okay because TiKV will reject stale read request with `starts_ts` < `resolved_ts`, and the `resolved_ts` have already used to update the `max_ts`.
- Need to …

*: the `start_ts` of stale read request should not used to update `max_ts`

---

Cargo.lock
components/raftstore/Cargo.toml
components/raftstore/src/coprocessor/split_observer.rs

The `SplitObserver.adjust_key()` is unclear. So renamed the function and move the checks of keys to the `on_split()`.
Tests 
- Unit test
```release-note
None
```

raftstore: Refactor SplitObserver.adjust_key()

---

components/cdc/src/channel.rs

Problem Summary: Freeing sink quota more than it actual allocated causes overflow, and blocks all messages from TiKV to TiCDC.
Tests 
- Unit test
This is not released yet.
```release-note
None
```

cdc: fix memory quota overflow

---

components/sst_importer/src/sst_importer.rs
components/test_sst_importer/src/lib.rs
src/import/sst_service.rs

* cherry pick #10416 to release-5.0
Signed-off-by: ti-srebot <ti-srebot@pingcap.com>
* Resolve conflicts
Co-authored-by: 3pointer <luancheng@pingcap.com>
Tests 
- Unit test
- No code
Side effects
- Fix the issue that br reports file already exists error when TDE enabled during restoration.

sst_importer: fix the file exists issue in link file (#10416) (#10421)

---

Cargo.lock
components/encryption/src/manager/mod.rs
components/raftstore/Cargo.toml
components/raftstore/src/store/mod.rs
components/raftstore/src/store/snap.rs
components/raftstore/src/store/worker/region.rs
src/server/snap.rs

Cherry pick #10454 , which fixes a panic bug when generating one snapshot twice.
Tests 
- Unit test
```release-note
None
```

allow to build one snapshot twice (#10454) (#10463)

---

components/raftstore/src/store/config.rs
etc/config-template.toml

Signed-off-by: yiwu <yiwu@pingcap.com>
Issue Number: close #10017
Problem Summary: Adjust `max_down_peer_duration` to be at least 2 * `peer_stale_state_check_interval`, so that peers in hibernated state would not be reported as down peer by mistake.
Adjust `max_down_peer_duration` to be at least 2 * `peer_stale_state_check_interval` when hibernated regions is enabled.
N/A
Tests 
CI
Side effects
```release-note
Adjust max_down_peer_duration to 10 minutes. This is to avoid hibernated peers being reported as down peer by mistake.
```

raftstore: adjust max_down_peer_duration based on hibernate timeout

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/store.rs

Drop `RaftRouter` shouldn't reset memtrace because it's clonable.
Tests 
Without the patch: 
with the patch: 
```release-note
None
```

drop router shoulnd't reset memtrace because it's clonable

---

components/resolved_ts/src/advance.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/tests/integrations/mod.rs
components/resolved_ts/tests/mod.rs

Issue Number: close #10426 
Online changing `resolved-ts.advance-ts-interval` can't take effect immediately
Register new advance ts event right after config change and add `cfg_version` to reject advance ts event that previous registered.
Tests 
```release-note
Fix online changing `resolved-ts.advance-ts-interval` can't take effect immediately
```

resolved_ts: fix online changing `resolved-ts.advance-ts-interval` can't take effect immediately

---

src/storage/txn/commands/acquire_pessimistic_lock.rs
src/storage/txn/commands/macros.rs
src/storage/txn/commands/mvcc_by_key.rs
src/storage/txn/commands/mvcc_by_start_ts.rs
src/storage/txn/commands/resolve_lock.rs
src/storage/txn/commands/resolve_lock_lite.rs
src/storage/txn/commands/resolve_lock_readphase.rs

Just a refactor.
The `command_method` macro makes less difference for human readability or simplicity.
- Remove `command_method`
- Add `property`
```release-note
None
```

txn: remove the `command_method` abstraction

---

components/cdc/Cargo.toml
components/cdc/src/endpoint.rs
components/cdc/src/observer.rs

One of the last crates needed to abstract over engines before tikv-server can be started with a non-rocks kv engine.
Part of https://github.com/tikv/tikv/issues/6402
Just replacing RocksEngine with KvEngine typarams.
```release-note
None
```

Abstract cdc crate over engines

---

components/server/src/server.rs
components/test_raftstore/src/server.rs
src/server/gc_worker/applied_lock_collector.rs
src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/gc_manager.rs
src/server/gc_worker/gc_worker.rs
src/server/node.rs
src/server/server.rs
src/server/service/kv.rs
src/storage/mvcc/consistency_check.rs
tests/integrations/config/dynamic/gc_worker.rs

Issue Number: https://github.com/tikv/tikv/issues/6402
tikv::server is one of the last modules that is still concretely using RocksEngine in a way that prevents tikv from being started with another engine.
Just replacing more uses of RocksEngine with KvEngine typarams in tikv::server.
This unfortunately requires type-parameterizing GcTask, which in turn forces some new type parameters elsewhere. But it's the only way I know to proceed.
```release-note
None
```

server: Replace RocksEngine with KvEngine typaram

---

components/cdc/src/endpoint.rs
components/resolved_ts/src/scanner.rs
src/storage/mvcc/reader/scanner/backward.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/reader/scanner/mod.rs
src/storage/txn/store.rs
tests/integrations/storage/test_titan.rs

Signed-off-by: Shashwat Jaiswal <shashwatjaiswal2001@gmail.com>
Issue Number: close #5531
Problem Summary: Improperly structured Builder pattern.
Proposal: Simple fix.
What's Changed: ```desc``` has been made optional (false by default) in ScannerConfig
Tests 
- Unit test
```release-note
None
```

Rewritten ScannerBuilder and ScannerConfig

---

components/external_storage/src/s3.rs

Since #10242 merged 2 days ago, the force-path-style flag is always ignored, and all S3 requests always use the virtual host addressing style.
In release-4.0, the `S3Storage` type has 2 constructors, `S3Storage::new` and `S3Storage::with_request_dispatcher`, which are independent from each other:
https://github.com/tikv/tikv/blob/72f119bcc5390dfc7a67fd37f34e579306998f3f/components/external_storage/src/s3.rs#L42-L66
This is not the case for 5.0 and up, where there are 3 constructors and all forward to the same underlying function `S3Storage::new_creds_dispatcher`:
https://github.com/tikv/tikv/blob/63b63edfbb9bbf8aeb875aad28c59f082eeb55d4/components/external_storage/src/s3.rs#L36-L83
The `force_path_style` configuration is done in the constructor. Because of the function …

external_storage: Fix force-style-path become useless

---

src/storage/txn/commands/prewrite.rs

https://github.com/tikv/tikv/issues/10468#issuecomment-869491061 mentioned that prewrite is not idempotent if the transaction has been committed.
If GC has not cleared the old commit record, it is possible for us to determine whether the prewrite request is a repeated one and needn't report an error.
This PR checks the commit records after we encounter a WriteConflict or PessimisticLockNotFound error,
Tests 
- Unit test
Side effects
- Consumes more CPU (on conflict or error cases)
```release-note
Make prewrite as idempotent as possible to reduce the chance of undetermined errors.
```
The most affected case should be conflicted optimistic case. (Though I think it's now not so common because pessimistic transactions are more suitable for high-conflict workloads).
I …

storage: do not report WriteConflict or PessimisticLockNotFound if txn is committed

---

tests/failpoints/cases/test_split_region.rs

Issue Number: close #10511 #10447 
The test failed because timeout of `cluster.batch_put`, before calling `cluster.batch_put`, the test setup the `failpoint` which sending msg to the sender of a `sync_channel(10)` but only receive the values after `cluster.batch_put`. If the `failpoint` trigger multiple times and call `send` more than 10 times, any incoming `failpoint` trigger will be blocking and cause `raftstore` stuck.
Replace `mpsc::sync_channel` with `mpsc::channel`
Tests 
```release-note
None
```

test: fix unstable test test_report_approximate_size_after_split_check

---

tests/integrations/server/kv_service.rs

Issue Number: close #10450
`server::kv_service::test_get_lock_wait_info_api` is unstable.
Use `kv_pessimistic_lock_with_ttl` instead of `must_kv_pessimistic_lock` to give the lock a larger ttl for the first lock acquired.
So the old lock won't exceed its ttl when doing the test process, which IMO cause the test unstable.
Tests 
```release-note
None.
```

test: try stabilize test case `test_get_lock_wait_info_api`

---

tests/failpoints/cases/test_pending_peers.rs

fix unstable test case test_pending_peers.
Close #10512 .
Tests 
- No code
Side effects
```release-note
None
```

fix unstable test case test_pending_peers

---

src/storage/txn/commands/prewrite.rs

Issue Number: #10552
The jepsen case append failed with incompatible oreder in the inner test environment:
```
2021-07-10 14:36:12,631{GMT}    INFO    [jepsen test runner] jepsen.core: {:perf
{:latency-graph {:valid? true},
:rate-graph {:valid? true},
:valid? true},
:workload
{:valid? false,
:anomaly-types (:incompatible-order),
:anomalies
{:incompatible-order ({:key 3, :values [[4 1 2 5 3] [4 1 2 5 6]]})}},
:valid? false}
Analysis invalid! (ﾉಥ益ಥ）ﾉ ┻━┻
```
In https://github.com/tikv/tikv/pull/10522, we do not return errors if the prewrite keys are already committed, the returned record type needes to be considered processing errors.
Check the write record type.
Tests 
- Unit test
Side effects
```release-note
NONE …
```

txn: considering the write type processing prewrite errors

---

cmd/src/server.rs

Issue Number: close https://github.com/pingcap/tidb/issues/25244
v4.0 TiDB introduced a mechanism that if a request sent to TiKV fails due to network problem, TiDB will check the liveness status of the TiKV through an HTTP API. If it's still reachable, TiDB will retry to send requests to it forever until backoff timeout.
However, TiKV may shut down slowly.
```
Jun 08 11:32:21 583d114d1e09 systemd[1]: Stopping tikv service...
Jun 08 11:33:51 583d114d1e09 systemd[1]: tikv-20160.service stop-sigterm timed out. Killing.
Jun 08 11:33:53 583d114d1e09 systemd[1]: tikv-20160.service: main process exited, code=killed, status=9/KILL
Jun 08 11:33:53 583d114d1e09 systemd[1]: Stopped tikv service.
Jun 08 11:33:53 583d114d1e09 …
```

server: stop status server early when gracefully shutdown

---

components/cloud/aws/src/s3.rs

Issue Number: close #10574 
Problem Summary: test_s3_storage is only available when failpoint is available. Fixing it.
What's Changed: run test_s3_storage only when failpoint is available
N/A
Tests 
run the test
```release-note
None
```

cloud: fix test_s3_storage

---

Cargo.lock
Cargo.toml
components/resolved_ts/src/cmd.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/commit.rs
src/storage/txn/actions/prewrite.rs
src/storage/txn/actions/tests.rs
src/storage/txn/commands/check_txn_status.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/store.rs
tests/benches/hierarchy/mvcc/mod.rs
tests/benches/hierarchy/txn/mod.rs

Issue Number: close https://github.com/pingcap/tidb/issues/26359
Considering a pessimistic async-commit transaction, both row keys and index keys are prewritten successfully but the prewrite responses of the index keys are lost. Then, some other transactions commit the transaction by resolving locks because all locks exist. After that, the original committer resends the prewrite request of the index keys.
In the previous implementation, prewriting index keys of a pessimistic transaction will just write the locks again. The committer receives success and starts committing the transaction. Now the commit TS is different from the commit TS used by resolving locks. So the index keys will be committed twice, making the transaction have two different commit TS.
This PR just adds an additional …

storage: prevent repeated non-pessimistic lock prewrite from writing locks

---

Cargo.lock
components/coprocessor_plugin_api/Cargo.toml
components/coprocessor_plugin_api/src/allocator.rs
components/coprocessor_plugin_api/src/lib.rs
src/coprocessor_v2/endpoint.rs

1. The current implementation causes a segmentation fault whenever an allocation/deallocation occurs.
2. The coprocessor plugin version check matches any version except the one requested.
`AtomicPtr<AllocFn>` stores a pointer to a function pointer, so the deref on line 50 and 53 is incorrect as the types don't match (`*mut AllocFn` vs `AllocFn`).
Also inverts the version check for the coprocessor plugins.
Tests 
*Unit test*
The unit tests unfortunately do not catch this issue, since the allocator function pointers are not used during the tests: https://github.com/tikv/tikv/blob/master/components/coprocessor_plugin_api/src/util.rs#L90
Since `example_plugin` gets included as a dev-dependency we cannot set `#[global_allocator]` since it would conflict with …

coprocessor_plugin_api: Use atomic for allocator functions

---

Cargo.lock
components/test_raftstore/src/pd.rs

Issue Number: close https://github.com/tikv/tikv/issues/10514 https://github.com/tikv/tikv/issues/10448 https://github.com/tikv/tikv/issues/10446
This test is failed because the two after-split regions' heartbeats are reported separately and there is a time that a hole in the PD's region cache. So if tests call `get_region` at that time exactly right, then it may find no region for the key.
Retry on `get_region()`, the hole in the PD's region cache will be filled up in the final.
- None
Tests 
- Unit test
```release-note
None
```

test: retry on get_region() to stable related test

---

components/txn_types/src/lock.rs
src/storage/mod.rs
src/storage/txn/commands/resolve_lock.rs

Issue Number: 
https://github.com/pingcap/tidb/issues/26404
The read query execution fails because the resolve lock reports error. In the situation the read and write conflicts with each other, there is possibility that the pessimistic locks are lefted, these lefted locks could be fetched by the resolve read phase but pessimistically rolled back before the resolve write phase by the async pessimistic lock rollback.
Do not report error if the resolve commit lock is a pessimistic lock type, then the read queries will not fail and report error to the client.
Tests 
- Unit test
Side effects
```release-note
Fix the resolve failures caused by the left pessimisic locks.
```

txn: skip resolve commit fail for left pessimistic locks

---

metrics/alertmanager/tikv.rules.yml

After TiDB 5.0, compaction filter is the default GC approach. If the cluster is idle thus no compaction is triggered, the GC compaction filter will not be triggered. Then, there will be a false "GC can not work" alert which is really annoying.
This PR modifies the alertmanager rule of "GC can not work". It raises the alert only if there are compaction operations while no GC compaction filter runs.
Tests 
```release-note
Avoid false "GC can not work" alert under low write flow.
```

alertmanager: no GC cannot work alert if no compaction happens

---

components/raftstore/src/store/peer_storage.rs

This PR is split from https://github.com/tikv/tikv/pull/10289.
Always enable entry cache and optimize `term` function a bit.
Tests 
- No code
Side effects
- No
```release-note
None
```

raftstore: always enable entry cache for async write io

---

Cargo.lock
components/raftstore/Cargo.toml
components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/worker/pd.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Address #10539.
* Add a tick to pd worker, inspect raftstore latency and calculate slow score periodically.
Tests 
- Unit test
```release-note
Introduce a mechanism to detect slow tikv store
```

raftstore: calculate slow score periodically

---

cmd/tikv-ctl/src/main.rs
components/raftstore/src/store/async_io/write_router.rs
src/storage/txn/flow_controller.rs

Issue Number: close #10697
Problem Summary: fix the warning during `make clippy`
Rust-clippy issues about the warning: [(== or !=) exact comparison to f32/f64 · Issue #46](https://github.com/rust-lang/rust-clippy/issues/46)
- Fixing the warning
- Replacing std::f64::INFINITY with f64::INFINITY
Tests
- Unit test
Side effects
```
None
```
```release-note
None
```

test: fix warning

---

components/raftstore/src/store/async_io/write_router.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/peer.rs
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/server.rs
tests/failpoints/cases/test_disk_full.rs

* Recalculate a commit quorum for configuration changes and role changes.
* Keep ticking if any followers are almost disk full.
* And add integration test cases for region majority peers disk full.
Tests 
```release-note
None
```

handle majority disk full peers correctly

---

Cargo.lock
components/tikv_util/Cargo.toml
components/tikv_util/src/sys/cgroup.rs
components/tikv_util/src/sys/mod.rs

#10536 introduces a critical bug about cgroup in containers. `mountinfo` is not considered correctly, which leads to get resource quota incorrectly.
Issue Number: close https://github.com/tikv/tikv/issues/10694.
Consider `mountinfo` correctly in cgroup code.
Tests 
The new log outputs:
```
[mod.rs:71] ["cgroup quota: memory=ReadableSize(8589934592), cpu=Some(3.0), cores={8, 12, 28}"]
```
/proc/self/cgroup:
```
11:devices:/kubepods.slice/kubepods-pod8982120b_bf8d_468e_806b_ef174e1e8f53.slice/docker-4c887edd435bd040df29998fc0b6487d8c8037da4d33f3e014c8a41370f880e7.scope …
```

fix cgroup for containers with mountinfo

---

components/test_storage/src/sync_storage.rs
src/server/service/batch.rs
src/server/service/kv.rs
src/server/service/mod.rs
src/storage/mod.rs

In the current implementation, "grpc request duration" only represents the time of handling the request, but the time of collecting responses in batch-channel is excluded.
Tests 
```release-note
None
```

record grpc duration correctly

---

components/file_system/src/lib.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/pd.rs
components/server/src/server.rs
components/tikv_kv/src/lib.rs
components/tikv_util/src/sys/disk.rs
src/storage/txn/commands/check_txn_status.rs
src/storage/txn/commands/commit.rs
src/storage/txn/commands/pessimistic_rollback.rs
src/storage/txn/commands/rollback.rs
src/storage/txn/commands/txn_heart_beat.rs
src/storage/txn/scheduler.rs
tests/failpoints/cases/test_disk_full.rs

Fix drop table failed when TiKV is almost disk full.
1. Push data until TiKV is disk full.
2. Exec Drop Table, then it will be blocked.
1. Proposal will be accepted by leader if TiKV is not disk full, except with special flag.
2. Newest PR change the judge condition only AllowedOnAlmostFull, but left deal with the AllowedOnAlreadyFull.
3. This PR unifies these differences.
```
None
```

*: fix one bug about drop table/truncate table failed when TiKV is almost disk full

---

ci-build/Makefile

This TODO is already fixed by e3349e122d6bc1ff0ecc08b6ebdfbe218f6f40cc.
Signed-off-by: tison <wander4096@gmail.com>
```release-note
None
```

Makefile: Remove outdated TODO

---

components/cdc/src/service.rs

Fix EventBatcher statistics (the total bytes of event and resolved ts are swapped by mistake).
Tests 
- Unit test
Not released yet, so none.
```release-note
None
```

cdc: fix EventBatcher statistics

---

components/server/src/server.rs
components/tikv_util/src/sys/cgroup.rs
scripts/clippy
tests/failpoints/cases/test_disk_full.rs

Signed-off-by: Alex Chi <iskyzh@gmail.com>
Re-enable clippy.
https://github.com/tikv/tikv/pull/10638, clippy errors are accidentally disabled in CI. This PR re-enabled it and fixed several clippy issues.
```release-note
None
```

*: re-enable clippy in CI checks

---

metrics/grafana/tikv_details.json

Previously data of different tikv nodes are mixed together, making the graph hard to read:
The tikv instance is added to the legend:
Tests 
```release-note
None
```

grafana: add instance to flow control metrics legend

---

src/storage/txn/flow_controller.rs

Issue Number: close #10752 
The throttle CF is not set when the throttle speed is initialized in the case of memtable accumulation.
- set throttle CF for memtable accumulation
- simplify spare tick logic
- fix unexpected behavior for memtable debt
Tests 
- No code
Side effects
```release-note
None
```

Fix flow controller for missing throttle cf

---

components/batch-system/src/batch.rs
components/batch-system/src/lib.rs
components/batch-system/src/test_runner.rs
components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/raft_engine.rs
components/raft_log_engine/src/engine.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/tikv_util/src/sys/cgroup.rs

Close #10475.
Read ready can be processed early to reduce read latency.
Tests 
- Unit test
- Manual test
Side effects
```release-note
- separate read write ready to reduce read latency
```

raftstore: separate read write ready (#10592)

---

components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/worker/pd.rs

Issue Number: close #10744
For now, we have serval unaddressed known issues about apply worker:
* The scan operations could hold the db mutex of rocksdb for a long time. https://github.com/tikv/rocksdb/pull/250
* `apply log duration` and `apply wait duration` could be large under some workloads with hotpots
With these issues the durations related to apply worker will introduce some uncertainty to the slow store detection. And the performance of the durations related to store worker is relatively stable in our tests. So this PR skips to inspect the durations related to apply worker.
* Skip to inspect apply latency
Tests 
- Unit test …

raftstore: skip to inspect apply latency

---

components/raftstore/src/store/fsm/peer.rs
components/server/src/server.rs
components/tikv_util/src/sys/disk.rs
tests/failpoints/cases/test_disk_full.rs

Signed-off-by: tier-cap <zhengxiaojin@pingcap.com>
Close cloud TiKV disk full feature in v5.2.
1. revert the disk place holder file size.
2. set the disk usage status normal and mock all update.
3. mock the disk stats worker.
4. mock handle_reported_disk_usage.
Tests
- Disable the integration test
Side effects
```
None
```

*: disable disk full checks and actions temporarily

---

Cargo.lock

Issue Number: close #10774 
Fix Titan upgrade issue by including https://github.com/tikv/titan/pull/221
What's Changed: see the linked issue and the titan fix.
N/A
Tests 
CI
```release-note
Fix TiKV panic when Titan is enabled and upgrade from < 5.0 versions to >= 5.0 versions. A cluster may hit the issue if it was upgraded from TiKV 3.x and enabled Titan before the upgrade in the past.
```

Fix TiKV panic when enable Titan and upgrade from pre-5.0 version

---

metrics/alertmanager/tikv.rules.yml

Coprocessor error type "lock" is renamed to "meet_lock" in #5155
Tests 
- No code
```release-note
None
```

fix wrong coprocessor alert rules

---

metrics/alertmanager/tikv.rules.yml

Apply snapshot counter was disabled in #4066 and removed in #10099, but `low_space_and_add_region` alert rule still uses it as a condition.
What's Changed: Unconditionally alert low space.
Tests
- No code
```release-note
None
```

Fix ineffective alert rule for low space

---

tests/integrations/raftstore/test_stats.rs

Issue Number: close #10584
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', tests/integrations/raftstore/test_stats.rs:628:45
```
Use a longer duration to avoid timeouts
Tests 
- Unit test
```release-note
None.
```

statistic: more stable test for query test

---

components/raftstore/src/store/fsm/peer.rs

the assign should be `peer_id`
Tests 
- Unit test
- No code
```release-note
raftstore: fix the wrong assign commit group
```

raftstore: fix the wrong assign commit group

---

components/raftstore/src/store/fsm/peer.rs
tests/integrations/raftstore/test_replication_mode.rs

Issue Number: close https://github.com/tikv/tikv/issues/10772 
Step:  ingest network isolation chaos -> wait 10m -> delete  network isolation chaos
**From the logs**:
1. assign the committed group
2. restore the snapshot (will clear commit group) https://github.com/tikv/raft-rs/blob/74d3bb58f19741cecc16698008103a446559837d/src/raft.rs#L2567-L2575
3. finished apply snapshot
4. transfer leader operator let the `tc2` peer (this peer) became leader
5. blocking on: `still not reach integrity over label`, and you can see all commit groups are 0.
```
[2021/08/23 12:24:14.766 +00:00] [Info] [raft.rs:1092] ["became follower at term 6"] [term=6] [raft_id=1332] [region_id=1108]
[2021/08/23 12:26:10.659 +00:00] [Info] [peer.rs:702] ["switch …
```

raftstore: fix the committed group not assign after apply snapshot

---

components/server/src/server.rs

Internal issue: https://internal.pingcap.net/jira/browse/TIDB-10490
When TiKV tries to reserve space for recovery, and encounters an IO error, the log message is confusing.
What's Changed: Print out which step is TiKV failing at.
Tests
- Unit test
```release-note
None
```

print log for space reserve failure

---

src/coprocessor/endpoint.rs

Issue Number: close #10852 
[`get_exec_details`](https://github.com/tikv/tikv/blob/19e4d00ad7965681b5139cd71c7eaf8290cc22ce/src/coprocessor/tracker.rs#L185-L192) expects to poll the tracked future at least once, or it will panic.
Poll the tracked future at least once.
Tests 
- Unit test
```release-note
None
```

copr: fix panic when exceeds deadline before polling

---

components/tikv_util/src/logger/mod.rs
src/coprocessor/tracker.rs

#10841 *:Logger thread can be bottleneck and slow down the whole TiKV instance 
Proposal: #10841
release-3.0
release-3.1
release-4.0
release-5.0
release-5.1
release-5.2
Tests 
- No code
Side effects
- Slow log will only consider time spent on processing the request. 
- Drop log instead of blocking threads when slogger thread is overloaded and queue is filled up. 
```release-note
- TiKV coprocessor slow log will only consider time spent on processing the request. 
- Drop log instead of blocking threads when slogger thread is overloaded and queue is filled up. 
```

coprocessor: reduce the slow log count by changing the req_lifetime to total_process_time

---

components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/snap.rs
tests/failpoints/cases/test_snap.rs

Issue Number: close #10813 
When snapshot GC runs into problem (such as file corrupted), today it stopped processing other GC-able snapshot files.
This PR will make it continue processing rest of the snapshot files.
Tests 
- Unit test
Side effects
No.
```release-note
RaftStore Snapshot GC fix: fix the issue that snapshot GC missed GC snapshot files when there's one snapshot file failed to be GC-ed. 
```
/cc @BusyJay

raftstore: continue GC  snapshot files when it encounters a corrupted snapshot

---

Cargo.lock

1. https://github.com/tikv/rocksdb/pull/252 introduced a new RocksDB configuration item to v5.2.0, making it unable to rollback to older versions.
The error message reads:
```
[lib.rs:466] ["failed to load_latest_options \"Invalid argument: Unable to parse the specified CF option disable_write_stall\""]
```
2. TiKV panic when enable Titan and upgrade from pre-5.0 version.
https://github.com/tikv/rocksdb/pull/258
https://github.com/tikv/titan/pull/223
Tests 
- Unit test
```release-note
- Fix TiKV panic when enable Titan and upgrade from pre-5.0 version
- Fix newer TiKV can't rollback to 5.0.x
```

engine: update rust-rocksdb for backward compatibility fixes

---

Cargo.lock
components/encryption/src/file_dict_file.rs
components/encryption/src/manager/mod.rs
components/engine_rocks/src/encryption.rs
components/engine_traits/src/encryption.rs
components/raftstore/src/store/snap.rs
components/sst_importer/src/sst_importer.rs

cherry-pick #9285 to release-4.0
Issue Number: close https://github.com/tikv/tikv/issues/9115
This PR is to solve the stale information encountered in the encryption dictionary
- Delete: When deleting a file but failing to execute `delete_file` on `file_dict`, the stale information leaves
- Rename: When a new `dst_fname` is added to the dictionary file, but the real `rename` is not successful or execute `rename` but failed to delete `src_fname`
- Link: When a new `dst_fname` is added to the dictionary file, the subsequent operations don't finish.
In the above situation, some stale file information will appear in the encrypted file dictionary. We need to deal with these errors instead of generating and returning errors.
Proposal: …

Check stale file information and remove Rename operation in encryption module

---

Cargo.lock
Cargo.toml
cmd/Cargo.toml
cmd/src/bin/tikv-ctl.rs
components/engine_traits/src/misc.rs
components/raftstore/src/store/worker/region.rs
scripts/check-redact-log
src/server/debug.rs
src/server/service/debug.rs

Signed-off-by: Andy Lok <andylokandy@hotmail.com>
1. Allow getting region info for all regions from the remote store:
`tikv-ctl --host 127.0.0.1:20160 raft region --all-regions`
2. Print region start key and end key with:
`tikv-ctl --host 127.0.0.1:20160 region-properties -r 1`
3. Added subcommand:
- `tikv-ctl unsafe-recover remove-failed-stores -s 1,2,3 -r 1,2,3 --promote-learner`: Promote the learner to leader if only one learner exists
- `tikv-ctl unsafe-recover drop-unapplied-raftlog -r 1,2,3`: regress the commit index to the apply index for the region
- https://github.com/pingcap/kvproto/pull/797
- PR to update `pingcap/docs`/`pingcap/docs-cn`: yes
Tests 
```release-note
1. Allow getting region info for all regions on the remote store:
`tikv-ctl --host 127.0.0.1:20160 raft region …
```

tikv-ctl: allow get_all_regions from remote, drop-unapplied-raftlog

---

components/sst_importer/src/import_file.rs

Issue Number: close https://github.com/tikv/tikv/issues/10902
Do not return error when found the file path is in 3.0 format
Tests 
- Unit test
Side effects
```release-note
None
```

import: fix upgrade bug for import_file 

---

README.md

Replaced by new CI service's badge.
```release-note
None.
```

docs: Fix build status CI badge in README

---

etc/config-template.toml
src/coprocessor_v2/endpoint.rs

Signed-off-by: Peng Guanwen <pg999w@outlook.com>
Issue Number: close #10855 
Disable plugin when `coprocessor-plugin-directory` is not presented.
coprocessor request will result an error when it  is disabled.
Tests 
- Unit test
```release-note
Adjust the behaviour of  `coprocessor-v2.coprocessor-plugin-directory` config item.
```

coprocessor: disable coproccesor when dir config is not presented.

---

src/coprocessor_v2/plugin_registry.rs

Issue Number: close #10854 
It solves the coprocessor hot reloading correctness issue by simply forbid reloading.
It [turns out](https://github.com/andylokandy/rfcs/blob/plugin/text/0063-coprocessor-plugin.md#auto-loading-1) that due to TLS related problems, the coprocessor plugin cannot hot reload correctly. The original plan is to prevent deletion and modification of the loaded plugin using file locks. But that's not possible because there's no reliable way to acquire a mandatory file lock. To solve this problem, this PR simply ~~unloads the  plugin whenever it removed or changed, and forbid future reloading from the same path~~ forbid unloading from loaded plugins regardless of file status.
Tests 
- Unit test
```release-note
None
```

coprocessor: Prevent reloading from unloaded plugins

---

Cargo.lock
cmd/tikv-ctl/Cargo.toml
cmd/tikv-ctl/src/main.rs

Issue Number: close #10793
Add `structopt` as a dependency, for parsing command line options of `tikv-ctl`.
Tests 
- I tried my best to ensure CLI behaviour keep the same after the migration. Most codes are transformed literally.
- The `--help` output for every subcommand is printed and compared between clap version and structopt version, so that we can ensure we have the same number of arguments/flags with flag types unchanged.
- I tested most command in the [`tikv-ctl` part of TiKV documention](https://tikv.org/docs/dev/reference/tools/tikv-ctl/) manually. But supported flags are too many. I am not able to test every possible flag/argument combination to ensure correctness.
```release-note
None
```

tikv-ctl: Migrate clap to structopt

---

Cargo.lock
components/error_code/src/sst_importer.rs
components/error_code/src/storage.rs
components/sst_importer/src/errors.rs
components/test_storage/src/sync_storage.rs
components/txn_types/src/lib.rs
components/txn_types/src/types.rs
src/coprocessor_v2/raw_storage_impl.rs
src/server/service/kv.rs
src/storage/errors.rs
src/storage/mod.rs
src/storage/txn/commands/atomic_store.rs
tests/integrations/storage/test_raft_storage.rs

my issue: https://github.com/pingcap/kvproto/issues/807
I add ttls param for BatchPut request so that it can set independent ttl for every key
```release-note
None
```

batchput set ttl to every key

---

src/server/raft_client.rs

The old implementation doesn't wait for receiver to finish, so the error
detail will be lost. One of the example is we can see a lot of
`RemoteStopped` send error in log with receiving error being `None`.
This PR joins two futures and print all errors in the end. So we can
know what's actually aborting connections.
Tests 
Setting `server.max-grpc-send-msg-len` to 10,240 and run tpcc prepare can see a lot of following logs:
```
[2021/09/13 21:38:51.804 +08:00] [ERROR] [raft_client.rs:407] ["connection aborted"] [addr=127.0.0.1:20161] [receiver_err=None] [sink_error=Some(RemoteStopped)] [store_id=5]
```
With this patch, the error report becomes:
```
[2021/09/13 21:36:13.538 …
```

raft_client: correctly report error

---

Cargo.lock
components/batch-system/Cargo.toml
components/batch-system/src/lib.rs
components/batch-system/src/metrics.rs
components/batch-system/src/router.rs

Signed-off-by: sampras lopes <sampraslop995@gmail.com>
Issue Number: close #10377
- Add `tikv_channel_full` metric for monitoring channel full events
Tests 
- Manual test
Monitor the `tikv_channel_full_total` metric on grafana
Side effects
No
```release-note
None
```

Add tikv_channel_full metric

---

Cargo.lock
Cargo.toml
src/server/service/kv.rs
src/server/service/mod.rs

Issue Number: close #9012
gRPC can't handle messages larger than 4GiB. This PR solves the issue by
checking response's binary length during serializing. Before the change,
TiKV will either coredump in grpc or panic in protobuf, after the
change, it will print a log in the TiKV side and call will be cancel in
the client side.
```
[2021/09/22 17:00:15.211 +08:00] [INFO] [kv.rs:1011] ["kv rpc failed"] [err="Codec(IoError(Custom { kind: Other, error: \"given slice is too small to serialize the message\" }))"] [request=batch_commands]
```
Tests 
- Manual test
Configure TiKV region size to 1TiB and load more than 10GiB data into TiKV. Run a full table scan.
```release-note
Fix panic in coprocessor when response size exceeds 4GiB
```

server: tolerate large response

---

components/tikv_util/src/sys/cgroup.rs
components/tikv_util/src/sys/mod.rs

Fix some panicks about cgroup on special platfoms(e.g. WSL, containers).
Issue Number: close #10897 and #10889 .
* allow `/sys/fs/cgroup` not exists
* handle relative path in the mountinfo file correctly
* all sub systems are not required to be supported for containers
Tests 
- Unit test
```release-note
None
```

fix panicks about cgroup on special platforms

---

Cargo.lock
components/test_raftstore/src/util.rs
components/test_util/Cargo.toml
components/test_util/src/lib.rs

TiKV uses backtrace to record suspicious problems in tests. But creating
a backtrace can take several seconds and lead to unexpected timeout for
cases.
This PR loads all symbols ahead of time to reduce the probability of
timeout. tikv-server binary also uses similar way to get around the
issue.
Tests 
- Unit test
```release-note
None
```

tests: cache symbols ahead of time

---

Cargo.lock
Cargo.toml
src/server/status_server/profile.rs

close #11108 
If the `pprof-rs` sample arrives and the current program is fetching a backtrace, the program will panic. The reason is that there is a lock inside the `dl_iterate_phdr`, which is called while unwinding the backtrace.
A more detailed description about this problem can be found in https://github.com/tikv/pprof-rs/pull/85#issuecomment-954446008 . In tikv, when an `Error` is generated, it's likely to get a backtrace and cause this problem.
After adding these libraries to the blocklist, it will also be able to turn on the heap profiling and `pprof-rs` cpu profiling at the same time, but I haven't modified (and tested) it yet.
Skip all samples inside the `glibc`, `pthread` and `libgcc`.
- PR to …

status_server: add glibc, pthread, libgcc to the blocklist

---

metrics/grafana/tikv_details.json
metrics/grafana/tikv_summary.json
metrics/grafana/tikv_trouble_shooting.json

Use process_cpu_seconds_total display process CPU usage, because it's faster than sum(tikv_thread_cpu).
tikv_thread_cpu is slow because it has a larger number of cardinality, eg., name and tid.
Tests 
- No code
```release-note
None
```

metrics: use process_cpu_seconds_total to display process CPU

---

components/encryption/src/encrypted_file/mod.rs
components/raftstore/src/store/async_io/write.rs
components/test_raftstore/src/cluster.rs
components/tikv_util/src/metrics/threads_linux.rs
tests/integrations/raftstore/test_single.rs
tests/integrations/raftstore/test_snap.rs
tests/integrations/raftstore/test_stats.rs
tests/integrations/server_encryption.rs

Issue Number: close #11186 
close #11182
- Too many operation can be very slow in limited environment, hence cause snapshot test fail.
- If there is no leader, split should be retried.
Tests 
- Unit test
```release-note
None
```

tests: fix slow snapshot tests and failed split operation

---

Cargo.lock
components/engine_rocks/Cargo.toml

Issue Number: #11226
Switch rust-rocksdb to branch tikv-5.2.
```release-note
None
```

engine_rocks: switch rust-rocksdb to branch tikv-5.2

---

components/server/src/server.rs
src/server/status_server/mod.rs
src/server/status_server/profile.rs
tests/integrations/server/status_server.rs

Issue Number: close #11265
Currently we generate heap profile to /tmp, then the files may be lost after pod restarting in docker environment.
* generate heap profile to data dir
Tests 
- Unit test
```release-note
None
```

generate heap profile to data dir

---

Cargo.lock
Cargo.toml
src/server/status_server/profile.rs

close #11108
close #11108 
If the `pprof-rs` sample arrives and the current program is fetching a backtrace, the program will panic. The reason is that there is a lock inside the `dl_iterate_phdr`, which is called while unwinding the backtrace.
A more detailed description about this problem can be found in https://github.com/tikv/pprof-rs/pull/85#issuecomment-954446008 . In tikv, when an `Error` is generated, it's likely to get a backtrace and cause this problem.
After adding these libraries to the blocklist, it will also be able to turn on the heap profiling and `pprof-rs` cpu profiling at the same time, but I haven't modified (and tested) it yet.
Skip all samples inside the `glibc`, `pthread` and `libgcc`. …

status_server: add glibc, pthread, libgcc to the blocklist (#11205)

---

components/raftstore/src/store/compaction_guard.rs

Issue Number: close https://github.com/tikv/tikv/issues/11290 
What's Changed: Check if it is a non-data key when calling `origin_key` in compaction guard.
- None
Tests 
- Unit test
```release-note
None
```

raftstore: Fix compaction guard panic on non-data key

---

components/cdc/src/endpoint.rs
components/cdc/src/observer.rs
components/keys/src/lib.rs
components/raftstore/src/coprocessor/dispatcher.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/raftlog_gc.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/src/observer.rs
components/test_raftstore/src/cluster.rs
src/server/raftkv.rs
tests/failpoints/cases/test_async_io.rs

Issue Number: close https://github.com/tikv/tikv/issues/11251
See https://github.com/tikv/tikv/issues/11251, this PR removes many useless `Response`.
Furthermore, this PR reduces some other waste.
1. the clone of `Region` in `prepare_for` function. This cloned `Region` is used for `post_apply_query` and `post_apply_admin` but for now no function really need this `Region`. I use a empty `Region` instead.
2. the clone of `RaftApplyState` when creating `ExecContext` in `apply_raft_cmd`. The `RaftApplyState` is cloned each time a raft cmd is applied. 
3. allocation for key in `handle_put` and `handle_delete`. Use a buffer instead of allocating every time. (Although the jemalloc is good enough to reduce most of the real allocation in this case, why not totally remove it? ) …

raftstore: reduce some cpu waste of apply thread

---

Cargo.lock
components/tikv_util/Cargo.toml
components/tikv_util/src/metrics/process_linux.rs

improve ProcessCollector performance
close #11306 
Tests
- Unit test
```release-note
None
```

tikv_util: ProcessCollector should use IntGauge to provide better performance

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/local_metrics.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/worker/metrics.rs
components/raftstore/src/store/worker/raftlog_gc.rs
metrics/grafana/tikv_details.json
src/server/metrics.rs
src/server/resolve.rs

Issue Number: close #11374
Currently we have a lack of metrics to observe the status of raft log gc tasks
Add more metrics for raft log gc.
Tests 
- Unit test
```release-note
None.
```

More metrics for raft log gc

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/local_metrics.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/worker/metrics.rs
components/raftstore/src/store/worker/raftlog_gc.rs
metrics/grafana/tikv_details.json
src/server/metrics.rs
src/server/resolve.rs

Issue Number: close #11374
Currently we have a lack of metrics to observe the status of raft log gc tasks
Add more metrics for raft log gc.
Cherry-pick from https://github.com/tikv/tikv/pull/11376
Tests 
- Unit test
```release-note
None.
```

More metrics for raft log gc (#11376)

---

components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: Jayice <1185430411@qq.com>
Hi,i participated in TiKV community for the first time
according to
(https://github.com/tikv/tikv/issues/5751#issuecomment-909765143)
migrating `duration_string_time_diff` from TiDB
implement ` duration_string_time_diff`
- No Related Changes
Tests 
- Unit test
```release-note
implement  duration_string_time_diff
```

copr: add duration_string_time_diff function

---

Cargo.lock
cmd/tikv-ctl/Cargo.toml
components/tikv_util/Cargo.toml
components/tikv_util/src/lib.rs

Issue Number: #11276 
The `gag` dependency was outdated. This PR updates `gag` to 1.0 which works on both Unix and Windows.
Tests 
- No code
Side effects
```release-note
None
```

tikv_util: upgrade `gag` from 0.1 to 1.0

---

components/codec/src/byte.rs

Issue Number: close #11356.
Tests 
- Unit test
```release-note
None
```

codec: add compile time assert to guarantee safety

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_early_apply.rs

Issue Number: close #11396
In the previous implementation, the commit state check uses the state of last committed entry and it relies on the guarantee that the commit index and term of the last committed entry must be monotonically increasing even between restarting.
However, this guarantee can be broken by
1. memory limitation of fetching committed entries
2. batching apply msg
Now the commit state uses the minimum of persist index and commit index from the peer to fix this issue. 
For simplicity, this test uses region merge to ensure that the apply state will be written to kv db before crash.
Mentioned before.
Tests 
Side effects
- No …

rafstore: fix commit state check in apply thread

---

components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/raft_engine.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/raftlog_gc.rs

Issue Number: close https://github.com/tikv/tikv/issues/11404
Batch more deleted keys together. As we all know ,the deleted key must be much small than the entry which has been put. So 256 is too small for every writebatch in raftlog-gc-worker.
And the gc tasks of most of regions are small. They are often smaller than 100. So I batch the keys of multiple regions and write them together.
Tests 
- Unit test
Side effects
```release-note
None
```

raftstore: increase batch for raftlog-gc-worker (release-5.1-20211115)

---

src/server/gc_worker/gc_worker.rs

Problem Summary: set pending capacity for gc worker which is forget to be set by https://github.com/tikv/tikv/pull/11416 by mistake 
Tests 
- No code
```release-note
None
```

gc: set pending capacity for gc worker

---

src/storage/mod.rs

Issue Number:close #11440 
Reverse scan's start_key is greater than end_key, but storage always uses [start_key, end_key) to check memory locks.
Swap start_key and end_key if is a reverse scan.
Tests 
- Unit test
Side effects
```release-note
Fix the issue that reverse scan can't detect memory locks and may read stale data.
```

storage: fix reverse scan check memory locks

---

components/raftstore/src/store/async_io/write.rs
metrics/grafana/tikv_details.json

Issue Number: close #11450
1. flush waterfall metrics and support online change when using synchronous write
2. remove the panel of `Write raft db duration` because it has already been included in `Append log duration`
3. fix a wrong PromQL in `Store commit but not persist duration`
Note that https://github.com/tikv/tikv/pull/11438 has fixed these issues so this PR does not need to cherry-pick to release-5.3.
- None
Tests 
Side effects
- No
```release-note
None
```

raftstore: flush waterfall metrics when using synchronous write

---

components/server/src/server.rs
src/server/status_server/mod.rs
tests/integrations/server/status_server.rs

For now, when TiKV starts, it will register its status address to PD which is useless because the component interface is not used.
Remove the register process.
Tests 
- Unit test
```release-note
None
```

server: remove register PD process

---

Cargo.lock
components/cdc/src/endpoint.rs
components/raftstore/Cargo.toml
components/raftstore/src/store/mod.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/region_snapshot.rs
components/raftstore/src/store/txn_ext.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/read.rs
components/tikv_kv/src/raftstore_impls.rs
components/txn_types/src/lib.rs
components/txn_types/src/lock.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/raftstore/test_merge.rs
tests/integrations/raftstore/test_transfer_leader.rs

Issue Number: #11452
This PR adds a region-level pessimistic lock table. And related transaction-related things of a region are refactored into a `TxnExt` struct.
Tests 
- Unit test
```release-note
None
```

raftstore: add pessimistic lock table to peer

---

Cargo.lock
Cargo.toml
src/config.rs

Issue Number: close #11489 
Update raft engine to include https://github.com/tikv/raft-engine/pull/159, also add a test case.
Tests
- Unit test
```release-note
None
```

engine: fix backward compatibility issue of raft-engine.recovery-mode

---

metrics/grafana/tikv_details.json

Close https://github.com/tikv/tikv/issues/11492
Problem Summary: 
It is not easy to diagnose the root cause of the latency jitter issue quickly for users, users may lost in the large amount of metrics which need high professional understanding of TiKV.
Add a "Duration Composition" panel to show the duration composition of write requests and coprocessor requests, it is easy to locate the biggest duration contributor in a glance.
Tests 
- No code
Side effects
- No
```release-note
None
```

metrics: add duration composition panel

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: guo-shaoge <shaoge1994@163.com>
Issue Number: close #11495 
Tests 
- Unit test
Side effects
```release-note
copr: enable pushdown of substring to tikv
```

copr: enable pushdown of substring to tikv

---

components/raftstore/src/store/region_snapshot.rs
components/tikv_kv/src/btree_engine.rs
components/tikv_kv/src/lib.rs
components/tikv_kv/src/raftstore_impls.rs
components/tikv_kv/src/rocksdb_engine.rs
src/coprocessor/cache.rs
src/coprocessor/endpoint.rs
src/lib.rs
src/server/gc_worker/gc_worker.rs
src/server/raftkv.rs
src/storage/mod.rs
src/storage/raw/encoded.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/scheduler.rs
src/storage/txn/store.rs
tests/benches/hierarchy/mvcc/mod.rs
tests/benches/misc/raftkv/mod.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/raftstore/test_merge.rs
tests/integrations/raftstore/test_transfer_leader.rs

Based on https://github.com/tikv/tikv/pull/11459
Issue Number: #11452
This PR is a refactoring about the snapshot interfaces.
It was messy as the raftstore related information is returned in two ways. Some are returned through `CbContext`, such as the term and the `txn_extra_op`. And some are through the `Snapshot` interface directly, like the `data_version` and the sync status.
This PR uniforms the interface returning information specialized for `RaftKv`, through `SnapshotExt`.
Tests 
Refactoring only.
```release-note
None
```

*: replace snapshot `CbContext` with `SnapshotExt`

---

Cargo.lock
components/backup/src/writer.rs
components/cdc/Cargo.toml
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/metrics.rs
components/cdc/src/old_value.rs
components/cdc/tests/mod.rs
components/engine_rocks/src/mvcc_properties.rs
components/server/src/server.rs
components/txn_types/src/types.rs
src/config.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/reader/scanner/mod.rs
src/storage/txn/commands/acquire_pessimistic_lock.rs
src/storage/txn/commands/prewrite.rs
src/storage/txn/store.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: close #11384.
* Add a new configuration `cdc.incremental-scan-use-ts-filter`, which indicates `TsFilter` can be used for incremental scan or not
* Only use TsFilter if it can filter more than 2/3 recoreds
* Use `OldValueReader` to re-fetch old values when `TsFilter` is used
Tests 
- Unit test
Side effects
```release-note
None
```

cdc: introduce TsFilter into incremental scan

---

src/storage/txn/scheduler.rs

Issue Number: closes #11500
This PR removes the engine from `Scheulder`. This should reduce some CPU usage of the scheduler threads.
And it also moves `control_mutex` into `SchedulerInner`, so we can avoid some clones when it is not used.
Tests 
- Existing tests.
```release-note
None
```

storage: make it cheaper to clone Scheduler

---

src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/reader/scanner/mod.rs

Close #11541
Forward scanner panics because it accesses a lock with delete type and the write cursor has moved to the next user key, but the forward scanner still handles the current write in `read_next()`, so move to next user key in this case to resolve it.
Tests 
- Unit test
Side effects
```release-note
None
```

scanner/forward: move to next key if accesses a lock with delete type

---

components/server/src/server.rs
components/test_raftstore/src/server.rs
src/server/lock_manager/config.rs
src/server/lock_manager/mod.rs
src/server/node.rs
src/storage/mod.rs
src/storage/txn/scheduler.rs
tests/integrations/config/dynamic/pessimistic_txn.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: #11452
This PR adds configuration and dynamic switches for the in-memory pessimistic lock feature.
The feature itself is not implemented yet, but it will help us develop the feature without interfere the current implementation by adding the switches first.
Docs are not updated yet. We will update doc after the feature is usable.
Tests 
- Unit test
```release-note
None
```

*: add configuration for in-memory pessimistic lock

---

components/tikv_util/src/future.rs

The current implementation is very easy to get deadlock if the future is
woken immediately during polling. This PR resolves the issue by
maintaining states instead.
Note, if the future is implemented in the wrong way that always
notifying the future without checking if it has readiness, the new
implementation can run into dead loop.
Close #11549.
Tests 
- Unit test
```release-note
Fix deadlock in some rare cases that futures get resolved too fast
```

tikv_util: reimplement poll_future_notify

---

src/server/service/diagnostics/sys.rs

Close #11552 
Skip the disk with filesystem as `rootfs` during the diskinfo extracting loop.
Tests 
- Unit test
Side effects
```release-note
None.
```

fix taking rootfs as filesystem by mistake

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/peer.rs
tests/failpoints/cases/test_merge.rs

Prepare merge may includes logs from different terms, which may be even
larger than the term of a follower that is lag behind. So when catching
up logs by commit merge, its term should also be set to get a correct
metadata.
Close #11526.
Tests 
- Unit test
```release-note
Fix metadata corruption in an unlikely condition that prepare merge is triggered after new election without informing an isolated peer
```

raftstore: set term when catch up logs for merge 

---

components/tikv_kv/src/btree_engine.rs
components/tikv_kv/src/lib.rs
src/server/gc_worker/gc_worker.rs
src/server/raftkv.rs
src/storage/mod.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/acquire_pessimistic_lock.rs
src/storage/txn/scheduler.rs

Ref #11452 
This PR supports reading and writing pessimistic locks in the transaction layer. 
Tests 
- Unit test
```release-note
None
```

storage: read and write in-memory pessimistic locks in the scheduler 

---

components/tikv_util/src/sys/cgroup.rs

Close #11569
Avoid unwrapping cgroup mountinfo
Tests
- Unit test
```release-note
Fix panic when cgroup controller is not mounted
```

tolerate unmounted cgroup controller

---

src/server/debug.rs
src/storage/mod.rs

Close https://github.com/tikv/tikv/issues/11583  
- print default cf as well for region-properties
- Fix https://github.com/tikv/tikv/issues/11571 by the way
None
Tests 
- No code
```release-note
Fix tikv-ctl region-properties doesn't work on rawkv
```

*: Fix tikv-ctl region-properties doesn't work on rawkv

---

src/storage/txn/flow_controller.rs

Close #11530
Consider time factor when evaluating the trending of pending compaction bytes or pending compaction memtable numbers.
- No
Tests 
- Unit test
Side effects
- No
```release-note
None
```

flow controller: consider the time factor when evaluating the trending

---

metrics/alertmanager/tikv.rules.yml

Close #11613 
Remove coprocessor meet lock alert because it is normal to meet lock when reading in percolator transaction model.
Tests 
- No code
Side effects
- No
```release-note
None
```

metrics: remove coprocessor meet lock alert

---

src/server/gc_worker/gc_worker.rs

close #11621
This PR adds a failpoint to unsafe_destroy_range.
This is intended to provide a way for testing the problem fixed by https://github.com/tikv/client-go/pull/270 and https://github.com/tikv/client-go/pull/278 .
Tests 
Side effects
```release-note
None
```

gc_worker: Add failpoint to unsafe_destroy_range

---

components/raftstore/src/store/peer.rs
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/transport_simulate.rs
components/test_raftstore/src/util.rs
tests/failpoints/cases/test_stale_peer.rs

Signed-off-by: p4tr1ck <patricknicholas@foxmail.com>
Issue Number: close #10533  
For an uninitialized peer, both epoch and peer list are empty, so a message target to a staled peer which override by an uninitialized peer will be create again. 
This PR will save the current peer into peer list if this region is uninitialized.
Tests 
Side effects
```release-note
Fix the problem that destroying an uninitialized replica may cause a stalled replica be created again.
```

raftstore: destroy uninitialized peer can make it possible to recreate old peer

---

metrics/grafana/tikv_details.json
metrics/grafana/tikv_summary.json
metrics/grafana/tikv_trouble_shooting.json

Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>
Close #11662 
TiKV dashboard on Grafana gets all memory usage jobs from Prometheus, which makes user confused.
Tests 
- No code
Side effects
```release-note
None
```

metrics: fix memory metrics

---

components/raftstore/src/store/worker/pd.rs
components/resource_metering/src/client.rs
components/resource_metering/src/lib.rs
components/resource_metering/src/localstorage.rs
components/resource_metering/src/model.rs
components/resource_metering/src/recorder/cpu.rs
components/resource_metering/src/recorder/mod.rs
components/resource_metering/src/recorder/summary.rs
components/resource_metering/src/reporter.rs
components/resource_metering/tests/summary_test.rs
components/test_raftstore/src/server.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/reader.rs
src/storage/mvcc/reader/scanner/backward.rs
src/storage/mvcc/reader/scanner/forward.rs
tests/integrations/resource_metering/mod.rs
tests/integrations/resource_metering/test_read_keys.rs
tests/integrations/resource_metering/test_suite/mod.rs

close https://github.com/tikv/tikv/issues/11690
Added support for the collection and reporting of the scanned keys.
- Added `SummaryRecorder` which implements `SubRecorder`.
- Three fields have been added to `LocalStorage` for statistics of scanned keys.
- Added the statistical logic of scanned keys in the context of ResourceMeteringTag.
- Added some fields related to scanned keys to the structure in `model.rs`.
- Handle extra fields in `client.rs`.
- [pingcap/kvproto#814](https://github.com/pingcap/kvproto/pull/814)
Tests
- Unit test
Side effects
```release-note
Support the statistics of scanned keys in resource metering.
```

resrc_mtr: introduce scanned keys statistics

---

components/resource_metering/src/model.rs
components/resource_metering/src/reporter/data_sink.rs
components/resource_metering/src/reporter/mod.rs
components/resource_metering/src/reporter/single_target.rs
components/resource_metering/tests/summary_test.rs
tests/integrations/resource_metering/test_read_keys.rs

ref #11691 
Many datasinks will be interested in report data. It's wasted to convert them from the original shape to the protobuf shape multiple times.
```release-note
None
```

rsmeter: add centralized place to construct protobuf data

---

metrics/grafana/tikv_details.json

Ref #11662 
After #11656, some metrics cannot be displayed correctly in K8s environment.
Tests 
- Manual test 
K8s environment:
TiUP:
```release-note
Fix the metrics in cluster panel cannot be displayed
```

metrics: fix the metrics cannot be displayed
