tikv/tikv

cmd/src/server.rs
components/configuration/src/lib.rs
components/tikv_util/src/config.rs
src/config.rs
src/storage/config.rs
tests/integrations/config/mod.rs

Support dynamically changing the shared block cache's capacity in the storage module.
Tests 
- Unit test
- Support dynamically changing the shared block cache's capacity

config: support change shared block cache

---

src/storage/txn/commands.rs
src/storage/txn/mod.rs
src/storage/txn/process.rs
src/storage/txn/scheduler.rs

A bunch of different refactorings (each commit can be reviewed alone). The overarching idea is to move most of the process module into the scheduler module and get rid of a bunch of data structures which IMO do not pull their weight.
PTAL @youjiali1995 @longfangsong

storage/txn: cleanup and refactoring

---

components/raftstore/src/coprocessor/config.rs
components/raftstore/src/coprocessor/mod.rs
etc/config-template.toml
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Add configuration for consistency check method.
Tests 
- Unit test
Side effects
* coprocessor: support to configure mvcc consistency check method

coprocessor: configure consistency check method

---

components/codec/src/convert.rs

Signed-off-by: abbccdda <boyang@confluent.io>
Issue Number: close #7186 
Enhance test coverage for codec module.
add test coverages for `convert.rs` and `byte.rs`
Tests
- Unit test
Side effects
- N/A

Test, codec: enhance test coverage for module codec

---

src/coprocessor/statistics/analyze.rs
tests/integrations/coprocessor/test_analyze.rs

Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
This pull request fixes a bug that `Analyze` encounter a single-primary-column table will panic because indexes out of range. We try to reserve all the table and shrink it only while the first column contains a `pk_handle` and only shrink once.
This pull request fixes a wrong index range while encountering a primary column as the first column in the table.
Tests 
- Unit test
* Fix index out of range in analyze column

copr: fix index out of range in analyze column

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Bump version v4.0.3

---

components/tidb_query_vec_expr/src/impl_json.rs

Signed-off-by: Phosphorus15 <steepout@qq.com>
Remove `Option`s from `json` signature
Tests 
- Unit test

copr: remove nullable signature for expression

---

components/tidb_query_vec_expr/src/impl_math.rs

Signed-off-by: xxchan <xxchan@sjtu.edu.cn>
remove nullable signature for math expressions
Tests 
- Unit test

copr: remove nullable signature for math expressions

---

src/server/server.rs

Remove the limit about received message size
Tests 
Side effects

server: remove the limit about received message size (#4992)

---

src/raftstore/store/fsm/apply.rs
src/raftstore/store/fsm/store.rs

Issue Number: close #8260
- Fix the bug that perf_context cannot be accessed.

Enable perf in store.fsm and apply.fsm for rocksdb

---

src/storage/txn/commands/acquire_pessimistic_lock.rs
src/storage/txn/commands/mod.rs
src/storage/txn/commands/pessimistic_rollback.rs
src/storage/txn/commands/prewrite_pessimistic.rs
tests/integrations/config/test-custom.toml

Remove useless codes because pessimistic transaction is always enabled since https://github.com/tikv/tikv/pull/8213.
Remove useless codes.
Tests 
- No code

storage: remove useless codes

---

Cargo.lock
Cargo.toml

Bump version v4.0.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml

*: Bump 3.0.17

---

cmd/src/server.rs
components/cdc/src/endpoint.rs
components/cdc/tests/mod.rs
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

The interval of advancing resolved ts is hard-coded.
Make it tunable through config file.
Tests 
- Unit test
* N/A

cdc: support config file

---

metrics/grafana/tikv_details.json

Problem Summary: Fix grafana perf context panel id duplicate issue
Just change a new id
Tests 
- No code
- Fix grafana perf context panel id duplicate bug

Fix grafana perf context panel id duplicate issue

---

Cargo.lock
components/cdc/tests/integrations/test_cdc.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/util.rs
components/test_raftstore/src/pd.rs
src/server/status_server/region_meta.rs
tests/integrations/raftstore/test_conf_change.rs

Update kvproto to https://github.com/pingcap/kvproto/commit/6157337686b1654f0bfb55920faf95b3d3e34d87
- *: update kvproto

*: update kvproto

---

Cargo.lock
cmd/src/bin/tikv-ctl.rs
cmd/src/server.rs
components/backup/tests/integrations/test_backup.rs
components/cdc/Cargo.toml
components/cdc/src/endpoint.rs
components/cdc/tests/failpoints/test_observe.rs
components/cdc/tests/failpoints/test_register.rs
components/cdc/tests/failpoints/test_resolve.rs
components/cdc/tests/integrations/test_cdc.rs
components/pd_client/Cargo.toml
components/pd_client/src/client.rs
components/pd_client/src/lib.rs
components/pd_client/src/util.rs
components/raftstore/Cargo.toml
components/raftstore/src/store/worker/pd.rs
components/test_raftstore/Cargo.toml
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/pd.rs
components/test_raftstore/src/server.rs
src/server/gc_worker/gc_worker.rs
src/storage/mvcc/txn.rs
tests/Cargo.toml
tests/failpoints/cases/test_conf_change.rs
tests/integrations/import/sst_service.rs
tests/integrations/pd/test_rpc_client.rs
tests/integrations/raftstore/test_conf_change.rs
tests/integrations/raftstore/test_hibernate.rs

Issue Number: https://github.com/tikv/tikv/issues/8095
This is one of the steps to upgrade future in tikv.
- upgrade future to 0.3 in pd_client
- compat the usage of the pd_client temporarily
Tests 
- Unit test
- Upgrade future for pd_client

Upgrade future for pd_client

---

components/raftstore/src/store/worker/read.rs

Fix unstable test test_destroy_local_reader
When remove peer, the `ReadDelegate` mark as invalid and will remove later, and `test_destroy_local_reader` check 
whether `ReadDelegate` exist after peer remove, but there is a race that `ReadDelegate` mark as invalid but still exist, so the fail point fire.
Fire fail point after checking `ReadDelegate` invalid.
Tests 
- Unit test

fix test_destroy_local_reader

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Bump version v4.0.5

---

components/tidb_query_vec_expr/src/impl_cast.rs

Issue Number: close https://github.com/pingcap/tidb/issues/19609
keep same impl as https://github.com/pingcap/tidb/pull/19485
Tests 
Side effects
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tikv/tikv/8551)

tidb_query: bug fix for vectorized casting real as time

---

components/txn_types/src/lock.rs

The first problem in https://github.com/tikv/tikv/issues/8589
Do not ignore the primary lock of an async commit transaction even if the read ts is u64::MAX. Then, before the lock is finally committed,  it should at least be read from the lock table or the lock CF. So we won't miss the latest modification.
Tests 
- Unit test
Part of async commit

txn: do not ignore the async commit lock when read ts is u64::MAX

---

components/tidb_query/src/rpn_expr/impl_cast.rs

cherry-pick #8551 to 4.0
---
Issue Number: close https://github.com/pingcap/tidb/issues/19609
keep same impl as https://github.com/pingcap/tidb/pull/19485
Tests 
Side effects
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tikv/tikv/8562)

tidb_query: bug fix for vectorized casting real as time (#8551)

---

src/storage/txn/commands/check_txn_status.rs

If a pessimistic lock is read and needs to be resolved, it doesn't have information whether this transaction uses async commit or not.
So it may call check_txn_status with non-zero `caller_start_ts` and `current_ts`. If the primary lock has been prewritten at this time, there will be an error.
As we don't support async commit fallback now, we can ensure that an async commit primary lock must be checked with zero `caller_start_ts` and `current_ts`. Therefore, as a temporary solution before we allow fallback, we can always set them to zero if the lock uses async commit.
Tests 
- Unit test
Part of async commit.

txn: allow non-zero caller_start_ts or current_ts

---

metrics/grafana/tikv_details.json

Add perf context panel for grafana template
- Add perf context panel for grafana template

Add perf context panel for grafana template

---

Cargo.lock
Cargo.toml
components/sst_importer/Cargo.toml
components/test_coprocessor/src/util.rs
components/test_raftstore/Cargo.toml
components/tikv_util/Cargo.toml
components/tikv_util/src/future.rs
src/coprocessor/endpoint.rs
src/server/lock_manager/client.rs
src/server/lock_manager/deadlock.rs
src/server/raft_client/legacy.rs
src/server/server.rs
src/server/service/batch.rs
src/server/service/debug.rs
src/server/service/diagnostics/log.rs
src/server/service/diagnostics/mod.rs
src/server/service/kv.rs
src/server/snap.rs
src/storage/txn/scheduler.rs
tests/integrations/server/raft_client.rs

Issue Number: #8095
This is the second of the steps to upgrade future for lib and cmd in TiKV. This is the last PR before upgrading grpc-rs.
1. service part.
2. raft client
- Upgrade future for lib and cmd (step 2).

Upgrade future for lib and cmd (step 2)

---

Makefile
components/cdc/Cargo.toml
components/cdc/src/endpoint.rs
components/cdc/tests/failpoints/mod.rs
components/cdc/tests/failpoints/test_register.rs
components/cdc/tests/integrations/mod.rs
components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs

Enable cdc failpoint tests in CI.
Tests 
- Unit test

cdc: enable failpoint tests

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Bump version v4.0.6

---

components/tikv_util/src/worker/future.rs

Deadlock detector may panic when calling a synchronous PD RPC. It is because futures `block_on` does not allow nested `block_on`.
Fix #8692 
Panic info is like:
```
[2020/09/17 06:26:19.113 +00:00] [FATAL] [lib.rs:482] ["cannot execute `LocalPool` executor from within another executor: EnterError"] [backtrace="stack backtrace:
0: tikv_util::set_panic_hook::{{closure}}
at components/tikv_util/src/lib.rs:481
1: std::panicking::rust_panic_with_hook
at src/libstd/panicking.rs:524
2: rust_begin_unwind
at src/libstd/panicking.rs:431
3: core::panicking::panic_fmt
at src/libcore/panicking.rs:85
4: core::option::expect_none_failed
at src/libcore/option.rs:1269
5: pd_client::client::RpcClient::get_region_and_leader::{{closure}}
at /rustc/16957bd4d3a5377263f76ed74c572aad8e4b7e59/src/libcore/result.rs …
```

tikv_util: use tokio runtime as FutureWorker runner

---

Cargo.lock
components/engine_panic/src/misc.rs
components/engine_rocks/src/misc.rs
components/engine_traits/src/misc.rs
components/engine_traits/tests/src/test_metrics_flusher.rs
components/engine_traits/tests/src/test_metrics_fluster.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/worker/region.rs
src/server/gc_worker/gc_worker.rs
tests/integrations/storage/test_titan.rs

Signed-off-by: Connor <zbk602423539@gmail.com>
Issue Number: close https://github.com/tikv/tikv/issues/8661 
Call `DeleteBlobFiles` after scan-delete
Tests 
- Unit test
Side effects
- None
- Fix possible missing blob file error of generating snap when doing UnsafeDestroyRange

titan: Fix possible panic of generating snap when doing UnsafeDestroyRange

---

Cargo.lock
components/engine_panic/src/misc.rs
components/engine_rocks/src/misc.rs
components/engine_traits/src/misc.rs
components/engine_traits/tests/src/test_metrics_flusher.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/worker/region.rs
src/server/gc_worker/gc_worker.rs
tests/integrations/storage/test_titan.rs

cherry-pick #8708 to release-4.0
---
Signed-off-by: Connor <zbk602423539@gmail.com>
Issue Number: close https://github.com/tikv/tikv/issues/8661 
Call `DeleteBlobFiles` after scan-delete and update rust-rocksdb to include https://github.com/tikv/rust-rocksdb/pull/542
Tests 
- Unit test
Side effects
- None
- Fix possible missing blob file error of generating snap when doing UnsafeDestroyRange

titan: Fix possible panic of generating snap when doing UnsafeDestroyRange (#8708)

---

src/server/lock_manager/deadlock.rs

The deadlock detector thread can use 100% cpu.
I haven't reproduced this problem but looking at the code I think it's due to the incorrect use of `filter_map`.
When the grpc stream disconnects with error, it always yields an error. In the previous code, the `filter_map` closure thansforms the error to a `None` but the `None` will be filtered by `filter_map` and the stream won't be terminated. So the stream will busy poll infinitely on grpc error.
Tests 
- Manual test
Run a workload that has conflicts. Then, kill a node which is not the leader of the deadlock detector.
With latest master, the cpu of the deadlock detector rises to 100%:
(172.16.4.28 is the deadlock detector leader)
With this PR:
(172.16.4.135 is the deadlock detector leader)
And now if it disconnects, there is a log now: …

lock_mgr: fix busy poll on grpc error in deadlock detector

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Bump version to v3.0.19
bump to v3.0.19
Tests 
- No code
* Bump version to v3.0.19

*: bump to v3.0.19

---

CHANGELOG.md
Cargo.lock
Cargo.toml

*: bump version v4.0.7

---

CONTRIBUTING.md

fix links to point to tikv instead of pingcap

---

Cargo.lock

Issue Number: close #8780 
What's Changed: update rust-rocksdb version
Tests 
- No code

*: update rust-rocksdb version to fix build failed

---

Cargo.lock
Cargo.toml
components/tikv_util/Cargo.toml

Signed-off-by: crazycs520 <crazycs520@gmail.com>
As title said.
Related issue: https://github.com/GuillaumeGomez/sysinfo/issues/295 
Related fix: https://github.com/GuillaumeGomez/sysinfo/pull/297
Tests 
- No code
Side effects
- No
- No.

*: update sysinfo version to fix undiscovered disk information

---

components/tidb_query_codegen/src/rpn_function.rs
components/tidb_query_vec_expr/src/impl_string.rs

Issue Number: #8491  
This PR adds writer support for vargs.
- Added writer support for varg rpn fn
- concat as an example and test has been changed to use writer
To be merged after merge of #8740

copr: add writer support for varg rpn fn

---

tests/integrations/raftstore/test_merge.rs

Signed-off-by: AilinKid <314806019@qq.com>
To fix the `isolate` type in some test files.
To fix the `isolate` type in some test files.
Tests 
- No code
- None

test: fix isolate typo

---

components/test_raftstore/src/pd.rs
tests/integrations/config/dynamic/pessimistic_txn.rs
tests/integrations/config/dynamic/raftstore.rs

Some unstable test fix did not cherry-pick into release-4.0 branch because the CI on release-4.0 unstable
cherry-pick https://github.com/tikv/tikv/pull/7873 and https://github.com/tikv/tikv/pull/8558

test: cherry-pick unstable test fix

---

components/raftstore/src/store/worker/split_controller.rs

Might as well.
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>
Tests 
- Unit test
- No code
Side effects

Refactored a default function into Default trait.

---

components/tikv_util/src/sys/mod.rs

Build on non-linux systems failed.
Remove nonexistent import.
Tests 
- No code
* N/A

tikv_util: fix build error on macos

---

components/backup/src/endpoint.rs
components/backup/src/service.rs
components/backup/tests/integrations/test_backup.rs

Handle create external storage error.
Close https://github.com/tikv/tikv/issues/8901
Tests 
- No release note. (This bug does not affect TiKV <= v4.0.7)

backup: handle create external storage error

---

components/backup/src/endpoint.rs
components/backup/src/service.rs
components/backup/tests/integrations/test_backup.rs

cherrypick #8899
Tests 
- No release note. (This bug does not affect TiKV <= v4.0.7)

backup: handle create external storage error (#8899)

---

CHANGELOG.md
Cargo.lock
Cargo.toml

What problem does this PR solve?
Bump version v4.0.8
Release note

Bump version v4.0.8

---

components/tidb_query_datatype/src/codec/data_type/mod.rs

Add comments as discuessed at  https://github.com/tikv/tikv/pull/8948#discussion_r516463693

copr: Add behavior comment for ChunkedVec

---

components/raftstore/src/store/fsm/store.rs

Issue Number: close #9044
Problem Summary: move sst cleanup task to its own thread. It fixes deadlock when compaction guard is enabled, and there are few thread in the background_worker pool.
What's Changed: Revert changes done in #8821 which move sst cleanup task to background_worker pool. The cleanup task will fire compact range, which is a blocking call and can take up to minutes. Meanwhile when compaction guard is enabled, the feature will schedule a task to fetch regions in the compaction range, which is also executed in the background_worker pool. When there's few background_worker pool thread (the pool size is `min(4, max(1, (#cpu +7)/8))`, so there could be only 1 thread when #cpu <= 8), it could cause a deadlock.
Despite the deadlock, …

raftstore: move sst cleanup (compact range) task to its own thread

---

components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: LiuYuHui <liuyuhui002@foxmail.com>
Issue Number: related to #9016 
- Coprocessor functions migration from non-vec framework
Tests 
- Unit test

copr: vectorize add_duration_and_duration

---

components/tidb_query_common/src/storage/scanner.rs

Issue Number: No correspond issue.
`alloation` -> `allocation`
None.
Tests 
- No code
Side effects
No side effect.

cop: fix typo in tidb_query_common/src/storage/scanner.rs

---

Cargo.lock

Addressing RUSTSEC-2020-0071.
Tests 
- Unit test
Side effects

*: update time to fix potential segfault

---

components/tidb_query_datatype/src/codec/mysql/duration.rs
components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: yuyuko1030@gmail.com
Issue Number: #5751 
Tests 
- Unit test

copr:add make_time

---

components/backup/src/endpoint.rs
components/backup/tests/integrations/test_backup.rs
components/external_storage/src/lib.rs
components/external_storage/src/local.rs

Issue Number: close https://github.com/tikv/tikv/issues/9051
stop create directory in local storage.
Tests 
- No code

storage: remove local storage create directory

---

components/tidb_query_datatype/src/codec/row/v2/row_slice.rs

Issue Number: close #9119 
Problem Summary: Coprocessor may return incorrect results due to wrapping a column id without checking.
Check whether column id overflows before wrapping it.
Tests 
- Unit test
- Manual test: Tested against test cases in #9119
```shell
$ mysql --host 127.0.0.1 --port 4000 -u root < test.sql
C260
260
```
- Fix a bug that Coprocessor may return wrong result when there are > 255 columns.

copr: Fix search_null incorrect result when scanning small rows for column id > 255

---

components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: wangggong <793160615@qq.com>
Issue Number: fix #9016 
What's Changed: add push-down & test for `DateDiff`
Tests 
- Unit test
Side effects

copr: add (non-)vectorized DateDiff

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

implement oct_string
Improvement
Unit test
No
No
#5751

copr: implement oct_string

---

components/tidb_query_aggr/src/impl_first.rs

Signed-off-by: Xuanwo <github@xuanwo.io>
Add unit test for enum/set support on First aggr
Tests
- Unit test

copr: Add test for enum/set support on First aggr

---

src/config.rs

Do not use unified pool for storage by default.
Due to https://github.com/tikv/tikv/issues/9188, setting the unified pool for storage by default can slow
down normal TP requests when there are TiSpark requests.
Tests 
- Unit test
- Revert part of https://github.com/tikv/tikv/pull/8887. Do not set the unified pool as storage default now.

config: revert setting unified pool as default for storage

---

Cargo.lock

resolve RUSTSEC-2020-0082.
Tests 
- Unit test
- No code
Side effects

*: update dep

---

src/storage/mvcc/txn.rs

We found ycsb performance drops a lot with https://github.com/tikv/tikv/pull/8921
Reorder check in prewrite to make txn fail or retry fast
Tests 
- Unit test
Side effects

txn: reorder check in prewrite to make txn fail or retry fast

---

Cargo.lock
components/tikv_util/src/metrics/threads_dummy.rs

Issue Number: close #9210
Problem Summary: Failed to build master under macOS
Just use `collections::HashMap` instead of `crate::collections::HashMap` in `threads_dummy.rs`.
Tests 
- No code

build: fix building under macos

---

src/coprocessor/endpoint.rs

Signed-off-by: Ruihang Xia <i@waynest.com>
None
derive `Clone` for `EndPoint` since `Engine` is `Clone` we need not manually impl it.

copr: derive clone for endpoint

---

Cargo.lock
Cargo.toml

Bump version v5.0.0-alpha to fix BR test failures.
Tests 
- No code

Cargo.toml: bump version v5.0.0-alpha

---

components/cdc/tests/integrations/test_cdc.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs

leader info was not updated after term changed.
update leader info after term changed.
Tests 
- Unit test
* N/A

cdc: fix resolved ts stoped after term changed

---

Cargo.lock
Cargo.toml

Cargo.toml: bump version v5.0.0-rc.x

---

components/test_raftstore/src/transport_simulate.rs

Issue Number: close #5628 
The atomic usage in `MessageNotifier` is racy in multi-threads environment.
Tests 
- Unit test
- No code
Side effects

tests: fix race in MessageNotifier

---

metrics/grafana/tikv_details.json
src/import/sst_service.rs

Add download wait duration metrics.

import: add download wait duration metrics

---

components/tidb_query_datatype/src/codec/mysql/time/mod.rs

Problem Summary: previously in TiDB https://github.com/pingcap/tidb/pull/20534 , we supported parsing time string in ISO 8601 format, but the change has not yet ported to TiKV, and this PR gets the job done.
- Need to cherry-pick to the release branch 4.0.
Tests 
- Unit test
- Integration test, see https://github.com/pingcap/tidb-test/pull/1149
Side effects
- port ISO8601 parsing from TiDB to TiKV's coprocessor.

copr: add ISO 8601 support for time parsing

---

components/tidb_query_datatype/src/codec/mysql/time/mod.rs

Revert "copr: add ISO 8601 support for time parsing"

---

tests/integrations/server/gc_worker.rs

Stabilize test case test_applied_lock_collector  by cherry pick #8369. 

test: stablize test_applied_lock_collector (#8369)

---

Cargo.lock
cmd/src/server.rs
components/engine_rocks/Cargo.toml
components/engine_rocks/src/encryption.rs
components/engine_rocks/src/event_listener.rs
components/engine_rocks/src/file_system.rs
components/engine_rocks/src/lib.rs
components/engine_traits/Cargo.toml
components/engine_traits/src/file_system.rs
components/engine_traits/src/lib.rs
components/engine_traits/src/metrics_flusher.rs
components/file_system/Cargo.toml
components/file_system/src/file.rs
components/file_system/src/lib.rs
components/file_system/src/rate_limiter.rs
components/test_raftstore/src/util.rs
components/tikv_util/Cargo.toml
components/tikv_util/src/lib.rs

Tag RocksDB compaction and flush IO flow with event listener.
Tests 
- Unit test

storage: tag RocksDB background IO

---

CHANGELOG.md
Cargo.lock
Cargo.toml

*: bump 5.0.0-rc

---

Cargo.lock

Update smallvec to resolve RUSTSEC-2021-0003.
Tests 
- Unit test
- No code

*: update smallvec

---

tests/failpoints/cases/test_cmd_epoch_checker.rs

https://github.com/tikv/tikv/pull/9136 only has unit tests. Need an integration test.
Add an integration test to cover https://github.com/tikv/tikv/issues/9070:
1. Partition the leader and followers.
2. Propose a write request on the leader.
3. A new leader is elected and commits a new entry.
4. Recover the network partition.
5. The old proposal should be dropped and the committed_cb shouldn't be invoked.
Tests 
- Unit test

test: shouldn't invoke committed callbacks when failing to commit

---

CONTRIBUTING.md

Document developing agains AWS (KMS) with localstack.
Add documentation to CONTRIBUTING.md. Maybe I should start a separate file for cloud development?
Tests
- No code
document how to test AWS with localstack

docs: developing against AWS

---

components/error_code/src/sst_importer.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/sst_importer/src/errors.rs
components/sst_importer/src/lib.rs
components/sst_importer/src/sst_importer.rs
src/import/sst_service.rs
src/storage/mod.rs
src/storage/txn/mod.rs
tests/failpoints/cases/test_import_service.rs

Issue Number: close https://github.com/tikv/tikv/issues/9496
If TiKV has applied one command of ingest but tidb-lightning(import-client) thinks this request has failed, it would send the same ingest-request to TiKV again, which may cause TiKV panic because the file has been ingested and could not be found.
There is many case which may cause request failed while it has been applied. Such as:
1. Network lost some packets of ingest-response.
2. The command had been copied to more than half of the members of raft-group but the original leader crashed before the entry of this command committed, then the new leader committed this entry but the client has received  fail messages by the response from the original leader.
We can propose one ingest-request when all the following …

importer: Check whether file exist before importing

---

components/test_raftstore/src/cluster.rs
tests/failpoints/cases/test_merge.rs
tests/failpoints/cases/test_pending_peers.rs
tests/failpoints/cases/test_replica_read.rs
tests/integrations/raftstore/test_hibernate.rs
tests/integrations/raftstore/test_merge.rs
tests/integrations/raftstore/test_replica_read.rs

There are a lot of duplicated code for waiting log truncation. So I add
a helper function to clean it up.
Tests 
- Unit test

*: add wait_log_truncated to simplify code

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

Issue Number: close #8986  
implement strcmp considering collation
Tests 
- Unit test
Side effects

copr: implement strcmp considering collation

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: Zijie Lu <wslzj40@gmail.com>
Issue Number: close #8986  
implement find_in_set considering collation
Tests 
- Unit test
Side effects

copr: implement find_in_set considering collation

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: Zijie Lu <wslzj40@gmail.com>
Issue Number: close #8986  
implement ord considering collation
Tests 
- Unit test
Side effects

copr: implement ord considering collation

---

components/tidb_query_common/src/error.rs
components/tidb_query_expr/src/impl_like.rs
components/tidb_query_expr/src/impl_string.rs

Signed-off-by: Xuanwo <github@xuanwo.io>
Code cleanup for utf-8 error handling.
Implement From<Utf8Error> for EvaluateError
Tests
- Unit test
Release note

copr: Implement From<Utf8Error> for EvaluateError

---

components/resolved_ts/src/advance.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/src/errors.rs
components/resolved_ts/src/lib.rs
components/resolved_ts/src/observer.rs
components/resolved_ts/src/sinker.rs

Separate from #9435
Introduce resolved ts advancer and event observer.
Tests 
- Unit test
* N/A

resolved_ts: add resolved ts advancer and event observer

---

src/server/gc_worker/compaction_filter.rs

Write CF's compaction filter utilizes too much CPU on `seek`. Here is a flame graph:
The reason is that there are lots of redundant `seek` when the range is cleared by `delete_files_in_range`.
Check the iterator position before `seek` or `next` in compaction filter.
Tests 
- Unit test

compaction filter: avoid redundant seeks

---

components/raftstore/src/store/worker/split_controller.rs

Issue Number: close https://github.com/pingcap/tidb/issues/22963 
Tests 
- Unit test
- No Release note

Fix unexpected panic when sampling in load base split

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Issue Number: #9016 
- Add `Quote` in lib.rs
- add `NullTimeDiff`
Tests 
- Unit test
Side effects

copr: activate quote & add null_time_diff

---

src/server/ttl/mod.rs
src/server/ttl/ttl_compaction_filter.rs

part of https://github.com/tikv/tikv/pull/9595
Add TTL compaction filter
Tests 
- Unit test
- None

server: Add ttl compaction filter

---

components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_config.rs
components/raftstore/src/store/worker/split_controller.rs

Add byte threshold and remove approximate threshold for load base split
Add byte threshold, because it will cover more case, such as there is a region with 1k qps and 30MB/s byte rate
Remove approximate threshold, because it is inaccurate
Tests 
- Unit test
- Manual test
```
set config tikv split.qps-threshold=50000;
drop database load_base_split;
create database load_base_split;
```
```
sysbench --rand-type=uniform --table_size=100000 --range_size=5000 --point_selects=0 --sum_ranges=0 --order_ranges=0 --distinct_ranges=0 --config-file=config oltp_read_only prepare
sysbench --rand-type=uniform --table_size=100000 --range_size=5000 --point_selects=0 --sum_ranges=0 --order_ranges=0 --distinct_ranges=0 --config-file=config oltp_read_only run
```
- No …

Add byte threshold and remove approximate threshold for load base split

---

Cargo.lock

Update rust-rocksdb with PR https://2github.com/tikv/rust-rocksdb/pull/618
What's Changed: update rust-rocksdb
No
Tests 
CI
- Improve crc32 performance on ARM

rust-rocksdb: Update rocksdb and titan with arm crc32 improvment etc

---

components/pd_client/src/metrics.rs
components/pd_client/src/util.rs
metrics/grafana/tikv_details.json
tests/failpoints/cases/test_pd_client.rs

Issue Number: related #9799
pd_client: add reconnect metrics
Tests 
- No code
Side effects

pd_client: add reconnect metrics

---

Dockerfile

Fix `make docker` failure
Switch to gcc8 in the builder container.
Tests 
- Unit test
* Dockerfile: fix build failure

Dockerfile: fix build failure

---

metrics/grafana/tikv_details.json

Signed-off-by: HunDunDM <hundundm@gmail.com>
* pd_client: fix monitoring unit typo
Tests 
- No code

pd_client: fix monitoring unit typo

---

components/tidb_query_expr/src/impl_time.rs
components/tidb_query_expr/src/lib.rs

Signed-off-by: zhuhaozhuhao notmyfault1996@gmail.com
Issue Number: #9016
what is changed: add vectorize add_date_and_string and related test.
Tests 
- Unit test
Side effects
- Vectorize add_date_and_string in tikv coprocessor functions

copr: add vectorize add_date_and_string

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects

*: Bump version v4.0.12

---

components/tikv_util/src/config.rs

I ran into this error and then manually tested that after this fix the error shows up properly
None

fix broken error display

---

components/encryption/export/examples/ecli.rs
components/encryption/export/src/lib.rs

Issue Number: supports #9678
Tests 
- Unit test

encryption: import macros with the use syntax

---

README.md
doc/deploy.md

Signed-off-by: tison <wander4096@gmail.com>
Issue Number: close #9937 
The quickstart section of README, "Try TiKV", is out of date.
Update quickstart section of README.
1. Mention & recommend TiUP
2. Mention running with binaries
3. Link to production-like cluster deployment and how to build from source.

*: rephrase quickstart section of README

---

components/batch-system/src/batch.rs
components/batch-system/src/config.rs
components/batch-system/src/lib.rs
components/batch-system/src/router.rs
components/batch-system/src/test_runner.rs

Issue Number: supports #9678
Tests 
- Unit test

batch-system: import macros with the use syntax

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/lib.rs
components/cdc/src/observer.rs
components/cdc/src/rate_limiter.rs
components/cdc/src/service.rs

Issue Number: supports #9678
Tests 
- Unit test

cdc: import macros with the use syntax

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Bump version to 5.0.0
Add change log
- No code
- None

bump 5.0.0

---

src/server/snap.rs

Abstracting tikv over alternate storage engines.
https://github.com/tikv/tikv/issues/6402
Add more type parameters to the snap module.

Make the server::snap module generic over engines

---

Cargo.lock
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/errors.rs
components/cdc/src/observer.rs
components/external_storage/src/lib.rs
components/resolved_ts/src/errors.rs
components/resolved_ts/src/scanner.rs
src/server/service/kv.rs
tests/integrations/server/mod.rs

Upgrade kvproto to https://github.com/pingcap/kvproto/commit/5a0d6e96603c0f9ee7fa09ae6a0750125ab757b5
Tests 
`make clippy`

*: upgrade kvproto

---

CONTRIBUTING.md

Clean up outdated information about bot

contribution: Clean up outdated information about bot

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects

*: Bump version v5.0.1

---

Cargo.lock
components/cdc/Cargo.toml
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/metrics.rs
components/cdc/src/observer.rs
components/cdc/src/service.rs
components/cdc/tests/integrations/test_cdc.rs
components/cdc/tests/mod.rs
src/config.rs
src/storage/txn/store.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

cherrypick #9948 
Tests 
- Unit test
- cdc: limit scan speed (128MB/s by default)

cdc: limit scan speed

---

Cargo.lock
components/encryption/Cargo.toml
components/encryption/src/manager/mod.rs

Issue Number: None
Remove todo.
None
Tests 
- Unit test
Side effects
None

Remove TODO of create_key_file

---

src/server/service/kv.rs

Print the error on "batch commands fail" error to help further investigation.
Print the error on "batch commands fail" error 
n/a
Tests 
CI
- No release notes.

server: log "batch commands fail" error

---

components/cdc/src/endpoint.rs

Deprecate verbose log.
Change info level to debug level.
Tests 
Run cdc v4.0.11+ on a nightly cluster.

cdc: deprecate verbose log

---

components/cdc/src/endpoint.rs

This is a cherry-pick of #10200.
----------------
Deprecate verbose log.
Change info level to debug level.
Tests 
Run cdc v4.0.11+ on a release-4.0-nightly cluster.

cdc: deprecate verbose log (#10200)

---

components/cloud/aws/src/s3.rs
components/cloud/gcp/src/gcs.rs

After #10132 #9706 merge into master, BR's integration test would be failed. This PR try to fix them.
1. Fix the error lost in s3 put object.
2. Keep the `changehost` logic as before.
Tests 
- Unit test

storage: fix the integration test of BR

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Bump 5.1.0-alpha on Master and sync changelog from other branch.
Tests 

*: bump 5.1.0-alpha

---

components/tikv_util/src/sys/mod.rs
etc/config-template.toml
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Add configurations for memory usage limitation.
Tests 
- Unit test

config: add memory-usage-limit

---

.github/pull_request_template.md

Signed-off-by: Cadmus <CadmusJiang@gmail.com>
Help Tichi to realize the information collection function of release note.
https://github.com/ti-community-infra/configs/pull/326
Add a release note reference to pull_ request_template.md
Tests 
- Unit test
- No code
Side effects
```release-note
```

github: add release-note description format to pull request template

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects

Bump v4.0.13

---

components/raftstore/src/store/fsm/peer.rs

raftstore: fix not register split when apply busy

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/error_code/src/raft.rs
components/raftstore/Cargo.toml
components/raftstore/src/lib.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/util.rs
src/server/debug.rs
src/server/raftkv.rs
tests/benches/misc/serialization/bench_serialization.rs
tests/integrations/raftstore/test_hibernate.rs
tests/integrations/server/kv_service.rs
tests/integrations/server/raft_client.rs

Update some dependencies.
Tests 
- No code

update protobuf and raft

---

components/cdc/src/delegate.rs
components/cdc/tests/integrations/test_cdc.rs

Issue Number: Fix #9460 
Problem Summary: Get tso from pd client.
Tests 
```release-note
None
```

cdc: stable cdc old value test

---

components/file_system/src/metrics_manager.rs
components/server/src/server.rs

Issue Number: close #10294 
What's Changed: Revert metrics flusher changes brought by #10223.
```release-note
None
```

engine: fix engine metrics not resetting

---

Cargo.lock

Problem Summary: Accidentally rollback rust-rocksdb version in #9197 
What's Changed: Update rust-rocksdb.
```release-note
None
```

rust-rocksdb: update to include important bugfix

---

components/cdc/src/endpoint.rs

Issue Number: close #10267 
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

cdc: stop CDC incremental scan from polluting rocksdb block cache

---

components/raftstore/src/store/mod.rs
components/server/src/lib.rs
components/server/src/memory.rs
components/server/src/server.rs
components/tikv_alloc/src/trace.rs
metrics/grafana/tikv_details.json
src/server/metrics.rs
src/server/mod.rs

Problem Summary: Add metrics for recording memory usage of each component.
What's Changed: Introduce MemoryTraceManager for registering components and flushing according to the specified time interval.
After this PR:
Tests 
- Unit test
- No code
```release-note
None
```

*: add a metrics for memory trace

---

metrics/grafana/tikv_details.json

Problem Summary: Some monitors have problems.
1. change the datasource from `playground` to `${DS_TEST-CLUSTER}` for memory trace
2. fix the duplicated ID
3. adjust the legend of `tikv_io_bytes`
Tests 
- No code
```release-note
None
```

*: fix some monitors in Grafana 

---

Cargo.lock
Cargo.toml
cmd/tikv-ctl/Cargo.toml
components/cdc/Cargo.toml
components/cloud/Cargo.toml
components/cloud/aws/Cargo.toml
components/cloud/gcp/Cargo.toml
components/encryption/Cargo.toml
components/encryption/export/Cargo.toml
components/engine_rocks/Cargo.toml
components/engine_traits/Cargo.toml
components/external_storage/Cargo.toml
components/external_storage/export/Cargo.toml
components/raft_log_engine/Cargo.toml
components/raftstore/Cargo.toml
components/resolved_ts/Cargo.toml
components/resource_metering/Cargo.toml
components/server/Cargo.toml
components/test_coprocessor/Cargo.toml
components/test_raftstore/Cargo.toml
components/tidb_query_datatype/Cargo.toml
components/tidb_query_executors/Cargo.toml
components/tidb_query_expr/Cargo.toml
components/tikv_util/Cargo.toml
fuzz/fuzzer-afl/Cargo.toml
fuzz/targets/Cargo.toml
tests/Cargo.toml

An individual package can't be compiled successfully without compiling the whole workspace.
Tests 
- No code
Side effects
```release-note
None
```

allow to compile an individual package

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
None.
```

Bump v5.0.2

---

components/test_backup/src/lib.rs

Tests 
- No code
Side effects
```release-note
NONE
```

test_backup: typo Extrat -> Extract

---

components/tidb_query_expr/src/impl_cast.rs

Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>
Issue Number: close https://github.com/pingcap/tidb/issues/25200
What's Changed: cast_real_to_signed_real and cast_real_to_unsigned_real is wrong.
Tests 
- Unit test
```release-note
fix wrong function cast double to double
```

copr: fix wrong function cast double to double

---

tests/integrations/raftstore/test_stats.rs

Issue Number: close #10380 
query test is unstable, for write request statistics it will be occasionally inaccurate
Add more detections while being compatible with occasional redundant qps statistics
Tests 
- Unit test
- Manual test
```
rm t.log
for i in {1..100}
do
cargo test --package tests --test integrations -- raftstore::test_stats::test_query_stats --exact --nocapture &>> t.log
sleep 1
done
cat t.log | grep panic
```
there is only panic with `No address added out of total 1 resolved`
```release-note
None
```

statistic: more stable test for query test

---

src/server/gc_worker/compaction_filter.rs

gc_worker: typo construcing -> constructing

---

Cargo.lock
Cargo.toml

remove unnecessary kvproto patch from #8157
Tests 
- Unit test
```release-note
None.
```

remove unnecessary kvproto patch

---

src/storage/txn/commands/check_txn_status.rs

The issue described in https://github.com/tikv/tikv/issues/7364 will no longer happen due to the change from https://github.com/pingcap/kvproto/pull/705
Tests 
- No code
```release-note
None
```

txn: Remove outdated comment for check_txn_status

---

components/cdc/src/channel.rs

Issue Number: close #10411 
Free quota if sending message fails.
Tests 
- Unit test
This bug does not affects existing releases. 
```release-note
None
```

cdc: fix sink quota leak on closed channel

---

components/cdc/src/channel.rs

This PR cherry-pick #10413.
----
Issue Number: close #10411 
Free quota if sending message fails.
Tests 
- Unit test
This bug does not affect existing releases. 
```release-note
None
```

cdc: fix sink quota leak on closed channel (#10411)

---

components/cdc/src/channel.rs

Stabilize the unstable case test_nonblocking_batch.
Tests 
- No code
```release-note
None
```

tests: stabilize test_nonblocking_batch

---

Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
```

*: Bump version v5.1.0

---

Cargo.lock
components/resource_metering/src/reporter.rs

update kvproto for https://github.com/pingcap/kvproto/pull/777
ditto
None
Tests 
- Unit test
Side effects
None
```release-note
None
```

update kvproto for PR kvproto#777

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Signed-off-by: purelind <purelind@gmail.com>
Tests 
- Unit test
- No code
Side effects
None.

Bump 5.0.3

---

components/raftstore/src/store/fsm/peer.rs
metrics/grafana/performance_read.json
metrics/grafana/performance_write.json
metrics/grafana/tikv_details.json
metrics/grafana/tikv_summary.json
metrics/grafana/tikv_trouble_shooting.json

Problem Summary: Fix typo "messge"
What's Changed: Replace it with "message"
Tests
- No code
```release-note
None
```

*: typo messge -> message

---

components/cdc/Cargo.toml
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/service.rs
components/cdc/tests/failpoints/test_resolve.rs

None
Fix typos.
None
Tests 
- No code
Side effects
None
```release-note
None
```

cdc: fix typos

---

README.md

Signed-off-by: hongrubb <hongru52@gmail.com>
Problem Summary: 
The previous roadmap URL is inaccessible. 
Remove the roadmap section in README.md
(The previous PR #10409  was unable to upadte, so I submit a new one)
Tests 
- No code
```release-note
None
```

docs: remove roadmap section in README.md

---

Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
```

*: bump 4.0.14

---

src/server/service/batch.rs
src/server/service/kv.rs

Tests 
- No code
Side effects
```release-note
None
```

record grpc duration more clear

---

Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
```

Bump v5.1.1

---

components/raftstore/src/store/async_io/mod.rs
components/raftstore/src/store/async_io/write_router.rs
components/raftstore/src/store/config.rs
components/raftstore/src/store/local_metrics.rs
components/raftstore/src/store/metrics.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

This PR is split from https://github.com/tikv/tikv/pull/10289.
Add write router for async write io.
Tests 
- Unit test
Side effects
- No
```release-note
None
```

raftstore: add write router for async write io

---

Cargo.toml

None
Remove useless features dependency parameters.
See: https://github.com/rust-lang/cargo/pull/9666
Tests 
- No code
Side effects
None
```release-note
None
```

Remove useless features dependency parameters

---

Cargo.lock
cmd/tikv-ctl/src/main.rs
components/raft_log_engine/src/engine.rs
components/raftstore/src/store/async_io/write_tests.rs
components/server/src/raft_engine_switch.rs
components/server/src/server.rs

Mainly to include metrics and interfaces: tikv/raft-engine#82, tikv/raft-engine#76.
Tests 
- Unit test
```release-note
None
```

Update raft engine

---

components/cdc/tests/mod.rs
components/server/src/server.rs

close https://github.com/tikv/tikv/pull/10692
Fix unstable test_joint_confchange test. Set correct min_ts_interval.
None
Tests 
- Unit test
- 
Side effects
None
```release-note
None
```

Fix unstable test_joint_confchange test

---

metrics/grafana/tikv_details.json

Add metric panels for slow score.
Add grafana panels to tikv-details pd.
Tests 
- Unit test
```release-note
None
```

metrics: add panels for slow score

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/pd.rs

Batch proposals correctly if disk full checks pass. Close https://github.com/tikv/tikv/issues/10716.
Tests 
- No code
Side effects
```release-note
None
```

batch proposals correctly if disk full checks pass

---

Cargo.lock

to resolve:
- RUSTSEC-2021-0072
- RUSTSEC-2021-0078
- RUSTSEC-2021-0079
- CVE-2021-32810
Tests 
- Unit test
```release-note
None
```

*: update several deps

---

components/tidb_query_expr/src/impl_string.rs

replace extend_from_slice with partial_write
```release-note
None
```

copr: replace extend_from_slice with partial_write

---

Cargo.lock
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/mod.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/query_stats.rs
components/raftstore/src/store/worker/split_controller.rs
components/server/src/server.rs
components/test_raftstore/src/server.rs
components/tikv_util/src/yatp_pool/mod.rs
src/read_pool.rs
src/server/node.rs
src/storage/mod.rs
src/storage/txn/sched_pool.rs
src/storage/txn/scheduler.rs
tests/integrations/raftstore/test_stats.rs

Issue Number: close #10507 
it collect quert stats in scheduler and flush them in tick to pd.rs
Tests 
- Unit test
insert 1200 tables
write test with Pessimistic
```release-note
None.
```

statistics: add more write query kind

---

src/coprocessor/endpoint.rs
src/coprocessor/metrics.rs
src/coprocessor/statistics/analyze.rs

TiKV makes a mistake to tag analyze requests.
Tests 
- No code
Side effects
```release-note
None
```

coprocessor: tag analyze requests correctly

---

src/coprocessor/endpoint.rs

The deadline test can fail unexcepted. Adjust it.
Tests 
- Unit test
```release-note
None
```

copr: fix unstable test

---

Cargo.lock

Cherry pick #10763.
Tests 
```release-note
None
```

update several deps (#10763)

---

Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
```

Bump v5.2.1

---

Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
```

Bump v4.0.15

---

components/cdc/Cargo.toml
components/cdc/src/endpoint.rs
components/raftstore/src/store/worker/check_leader.rs
components/resolved_ts/Cargo.toml
components/resolved_ts/src/advance.rs
components/resolved_ts/tests/failpoints/mod.rs

Issue Number: close #10965
See #10965
Add a timeout for the coroutine executing.
Tests 
- Unit test
```release-note
```
* resolved_ts: fix coroutine leaking

resolved_ts: fix coroutine leaking

---

components/cdc/Cargo.toml
components/cdc/src/endpoint.rs
components/raftstore/src/store/worker/check_leader.rs
components/resolved_ts/Cargo.toml
components/resolved_ts/src/advance.rs
components/resolved_ts/tests/failpoints/mod.rs

Pick from #10976
Tests 
- Unit test
```release-note
resolved_ts: fix coroutine leaking
```

resolved_ts: fix coroutine leaking (#10976)

---

src/config.rs

See: https://github.com/tikv/tikv/pull/10923#pullrequestreview-750038054
add from test for config.
Tests 
- Unit test
Side effects
None
```release-note
None
```

test: add from test for config

---

Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
```

Bump v5.1.2

---

src/storage/txn/flow_controller.rs

Issue Number: close #11218
This PR changes `tx` in `FlowController` to use an `Option`. The related code is not in critical paths, so no worries about performance regressions.
Tests 
- Existing tests.
```release-note
None.
```

storage: avoid leaking FlowController channel in tests

---

components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer_storage.rs
components/raftstore/src/store/worker/region.rs
etc/config-template.toml
tests/integrations/config/mod.rs

Issue Number: close #11247 
Tests 
- Unit test
Side effects
```release-note
make threads of snap-generator pool configurable
```

raftstore: make threads of snap-generator pool configurable

---

src/server/status_server/mod.rs

Signed-off-by: yuqi1129 <yuqi4733@gmail.com>
Issue Number: close #11279 
Tests 
- No code
Side effects
```release-note
None
```

Fix compile error in status server on MacOS

---

components/cdc/src/endpoint.rs

close #11313
Issue Number: close #11313 
Tests 
- No code
Side effects
```release-note
None
```

cdc: remove hint_min_ts for cdc incremental scanner

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/msg.rs

Tests 
- Unit test
- No code
Side effects
```release-note
```

raftstore: fix callback of cmd batch

---

metrics/grafana/tikv_details.json
src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/gc_worker.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/gc.rs

Issue Number: close https://github.com/tikv/tikv/issues/11410 
What's Changed: limit the pending task for gc worker to avoid OOM
Tests 
- Manual Test
```release-note
Fix GC scan effectiveness to avoid OOM
```

gc: Fix GC scan effectiveness to avoid OOM

---

src/server/gc_worker/gc_worker.rs

Problem Summary: cherry-pick #11429 to release-5.3
Tests 
- No code
```release-note
None
```

gc: set pending capacity for gc worker(#11429)

---

components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/coprocessor/region_info_accessor.rs
components/raftstore/src/store/compaction_guard.rs
components/tikv_util/src/worker/pool.rs
metrics/grafana/tikv_details.json
src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/gc_manager.rs
src/server/gc_worker/gc_worker.rs
src/server/gc_worker/mod.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/gc.rs
tests/failpoints/cases/test_gc_worker.rs
tests/integrations/config/dynamic/gc_worker.rs
tests/integrations/raftstore/test_region_info_accessor.rs
tests/integrations/storage/mod.rs
tests/integrations/storage/test_region_info_accessor.rs

Cherry pick https://github.com/tikv/tikv/pull/11416 https://github.com/tikv/tikv/pull/11284 #11294 #10649 #11429
Tests 
- Unit test
```release-note
None.
```

Cherry pick compaction filter bugfix

---

components/server/src/server.rs

This reverts commit df2e9216f2f0f497ff158276a0171f4293516d91 as #11461 explains.
Tests 
- Unit test
```release-note
None
```

Revert "Make tikv-server fully generic over kv engines (#10945)"

---

components/engine_panic/src/table_properties.rs
components/engine_rocks/src/properties.rs
components/engine_rocks/src/table_properties.rs
components/engine_traits/src/table_properties.rs

Issue Number: close #11464.
Extracted from #11385 .
Tests 
- No code
Side effects
```release-note
None
```

support to get approximate keys and size for a given range from UserCollectedProperties

---

Cargo.lock
cmd/tikv-ctl/src/main.rs
components/encryption/src/manager/mod.rs
components/raft_log_engine/Cargo.toml
components/raft_log_engine/src/engine.rs
components/raft_log_engine/src/lib.rs
components/server/src/raft_engine_switch.rs
components/server/src/server.rs
etc/config-template.toml
src/config.rs
tests/Cargo.toml
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: part of https://github.com/tikv/raft-engine/issues/95
Update raft engine and opt in new interface.
Stacked on https://github.com/tikv/tikv/pull/10929.
Tests
- Unit test
```release-note
None
```

engine: provide customized file builder to raft engine

---

Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
```

bump v5.3.0

---

.github/pull_request_template.md
CONTRIBUTING.md

We only needs to explain what's change. Problem description should be
traced as issue.
This PR also polishes contributing guide to explain the new flow.
Close #11503.
Tests 
- No code
```release-note
None
```

*: simplify pull request template

---

components/raftstore/src/store/peer_storage.rs
tests/integrations/raftstore/test_snap.rs

Ref #10225.
Tests 
- Unit test
```release-note
Fix panic in rare cases that split is not finished before being destroyed
```

raftstore: update applied_index_term after snapshot (#10476)

---

Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
```

Bump v5.0.5

---

Cargo.lock
Cargo.toml

Tests 
- Unit test
- No code
Side effects
```release-note
```

[DNM] Bump v5.1.3

---

components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/coprocessor/region_info_accessor.rs
components/raftstore/src/store/compaction_guard.rs
metrics/grafana/tikv_details.json
src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/gc_manager.rs
src/server/gc_worker/gc_worker.rs
src/server/gc_worker/mod.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/gc.rs
tests/integrations/raftstore/test_region_info_accessor.rs
tests/integrations/storage/mod.rs
tests/integrations/storage/test_region_info_accessor.rs

Close #xxx 
Tests 
- Unit test
- No code
Side effects
```release-note
```

Cherry-pick compaction filter GC fixes 

---

components/tikv_util/src/sys/cgroup.rs

cherry-pick #11029 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
git pr https://github.com/tikv/tikv/pull/11050
```
After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/11050:release-5.2-ba3a2e46cd70
```
---
Multiple controllers can share one mountinfo line. Without the patch only the first controller will be attached with the mountinfo, which is incorrect.
Close https://github.com/tikv/tikv/issues/11037.
Attach multiple controllers with one mountinfo correctly. …

cgroup: fix a bug about mountinfo of cpuset,cpu (#11029)

---

components/cdc/src/endpoint.rs
scripts/test

Close #11560 .
Tests 
- No code
Side effects
```release-note
None
```

stabilize  some cdc cases

---

src/coprocessor/endpoint.rs
src/server/service/kv.rs

Close #xxx 
Tests 
- Unit test
- No code
Side effects
```release-note
```

server: panic when read request met engine corruption error

---

components/raftstore/src/store/worker/mod.rs
components/raftstore/src/store/worker/refresh_config.rs

Issue Number: close #11159  
Proposal: #11159 
What's Changed: #11159 
- No
Tests 
- No code
Side effects
- No
```release-note
None.
```

raftstore: add a new worker to dynamically update pool size (#11159)

---

components/br-stream/src/endpoint.rs
components/br-stream/src/lib.rs
components/br-stream/src/observer.rs
components/br-stream/src/router.rs
src/config.rs

Part of  https://github.com/pingcap/tidb/issues/30446 
implement router for observer. to filter range if not want.
Tests 
- Unit test
Side effects
```release-note
None
```

br: implement router for backup stream

---

cmd/tikv-ctl/src/main.rs

Close https://github.com/tikv/tikv/issues/11514
Tests 
ref https://tikv.org/docs/dev/reference/tools/tikv-ctl/
and run some commands like
```
tikv-ctl consistency-check -r 2
tikv-ctl --host 127.0.0.1:20160 consistency-check -r 2
tikv-ctl --to-escaped 0xaaff
tikv-ctl compact-cluster 
tikv-ctl --pd 127.0.0.1:2379 compact-cluster
....
```
```release-note
None
```

ctl:add prompt for ctl when required param is not specified

---

src/config.rs

None
Add the missing from for cdc module.
None
Tests 
None
Side effects
None
```release-note
None
```

config(cdc): Add the missing from

---

components/cdc/src/old_value.rs

Close #11642 .
Tests 
- Unit test
Side effects
```release-note
None
```

cdc: load old value with prefix seek if possible

---

Cargo.lock
Cargo.toml

Close #xxx 
Tests 
- Unit test
- No code
Side effects
```release-note
```

Bump v4.0.16

---

Cargo.lock
components/resource_metering/Cargo.toml

Try fix the build issue on non-linux platform.
Close #11676
What's Changed: components/resource_metering/Cargo.toml
- None
```release-note
NONE
```

Fix build issues on non-linux platforms

---

Cargo.lock
components/tikv_util/Cargo.toml
components/tikv_util/src/sys/inspector.rs

Close #11702
update procfs to 0.12.0
Tests 
- Unit test
- No code
Side effects
```release-note
update procfs to 0.12.0
```

tikv_util: update procfs to 0.12.0

---

components/file_system/src/thread_io.rs

Signed-off-by: MuZhou233 <muzhou233@outlook.com>
Close #11698 
Caused by #11667
- `thread_io` only support on linux now
Tests 
- Unit test
```release-note
None
```

file_system: limit thread_io target os

---

Cargo.lock
components/br-stream/Cargo.toml
components/br-stream/src/endpoint.rs
components/br-stream/src/metadata/client.rs
components/br-stream/src/metadata/keys.rs
components/br-stream/src/observer.rs
components/br-stream/src/router.rs
components/server/src/server.rs

Close https://github.com/tikv/tikv/issues/11679
This pr is for test and debug for the backup-log flow
```release-note
None
```

br: backup-log: Test and debug for backup-log process

---

Cargo.lock
components/resource_metering/Cargo.toml
components/resource_metering/src/lib.rs
components/resource_metering/src/reporter/mod.rs
components/resource_metering/src/reporter/pubsub.rs
components/server/src/server.rs
tests/integrations/resource_metering/mod.rs
tests/integrations/resource_metering/test_dynamic_config.rs
tests/integrations/resource_metering/test_pubsub.rs
tests/integrations/resource_metering/test_suite/mock_pubsub.rs
tests/integrations/resource_metering/test_suite/mod.rs

close #11691 
* implement pubsub service
* implement pubsub datasink
Tests 
- Unit test
Side effects
```release-note
resource_metering: add pubsub mode
```

rsmeter: add pubsub datasink 

---

components/tikv_util/src/logger/mod.rs
etc/config-template.toml
src/config.rs
tests/integrations/config/mod.rs

ref #11651
Close #11651  
Tests 
- Unit test
Side effects
- None
```release-note
None
```

logger: fix config-template's log unit (#11651)

---

src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

ref #11651
Close #xxx 
Tests 
- Unit test
Side effects
- None
```release-note
None
```

logger: improve testcase (#11651)

---

cmd/tikv-server/src/main.rs
components/tikv_util/src/logger/mod.rs
etc/config-template.toml
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml
tests/integrations/config/test-log-compatible.toml

ref #11651
Close #11651  
Tests 
- Unit test
- No code
Side effects
- None
```release-note
None
```

logger: change critical to fatal (#11651)

---

cmd/tikv-server/src/main.rs
src/config.rs
tests/integrations/config/mod.rs

close #11789 
Close #11789  
Tests 
- Unit test
Side effects
- None
```release-note
None
```

logger: invoke logger_compatible_adjust before run_tikv (#11651)

---

cmd/tikv-ctl/src/main.rs
cmd/tikv-server/src/main.rs
components/server/src/server.rs
components/server/src/setup.rs
components/tikv_util/src/lib.rs
components/tikv_util/src/logger/file_log.rs
components/tikv_util/src/logger/mod.rs
etc/config-template.toml
src/config.rs
src/server/service/diagnostics/log.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-cache-compatible.toml
tests/integrations/config/test-custom.toml
tests/integrations/config/test-log-compatible.toml

close #11651
Close #11651
Tests 
- Unit test
Side effects
- None
```release-note
logger: support archiving and rotation (#11651)
```

logger: support archiving and rotation (#11651)

---

Cargo.lock
components/engine_rocks/Cargo.toml

rust-rocksdb branch.
Tests
- No code
```release-note
Reduce RocksDB lock contention under read/write hybrid workload: https://github.com/tikv/rocksdb/pull/250
```

rocksdb: update branch for 5.4 release

---

components/resource_metering/src/recorder/mod.rs
components/tikv_util/src/sys/thread.rs

Close #11823
Make it compile on macos
Tests 
- Manual test
```release-note
None
```

*: make it compile on macos

---

src/server/load_statistics/mod.rs

close #11772
Tests
- Manual test
```release-note
None
```

load_statis: fix compilation on macos

---

components/raftstore/src/store/fsm/store.rs
components/test_raftstore/src/common-test.toml

ref #11159
Close #11159  
Tests 
Side effects
- None
```release-note
None
```

raftstore: fix missing workers' stop on shutdown

---

Cargo.lock
Cargo.toml

Close #xxx 
Tests 
- Unit test
- No code
Side effects
```release-note
```

Thix/bump v5.4.0

---

metrics/grafana/tikv_details.json
src/server/gc_worker/compaction_filter.rs
src/server/gc_worker/gc_worker.rs
src/server/metrics.rs
src/storage/mvcc/txn.rs

```commit-message
correct a metric about compaction filter
```
Tests 
- No code
Side effects
```release-note
None
```

correct a metric about compaction filter

---

Cargo.lock

Issue Number: Close #11951 
Update `raft-rs` to include https://github.com/tikv/raft-rs/pull/462
- None
Tests 
- No code
```release-note
None
```

raft: Fix possible panic on entries fetched callback

---

components/raftstore/src/store/worker/split_controller.rs

* Simplify the `sample` function.
* Extract the `Samples` type and its methods.
* Refine some code.
* Add some comments.
Tests 
- Unit test
- Manual test
After this PR:
```shell
test store::worker::split_controller::tests::hub_flush                        ... bench:  20,941,049 ns/iter (+/- 4,691,236)
test store::worker::split_controller::tests::qps_add                          ... bench:         108 ns/iter (+/- 26)
test store::worker::split_controller::tests::qps_scan                         ... bench:         188 ns/iter (+/- 18)
test store::worker::split_controller::tests::samples_evaluate                 ... bench:           5 ns/iter (+/- 0)
test store::worker::split_controller::tests::hub_flush …
```

split_controller: refine the sample function and add some comments

---

components/raftstore/src/store/worker/split_controller.rs

```commit-message
Reorganize the structs and add more comments.
```
Tests 
- Unit test
```release-note
None.
```

split_controller: reorganize the structs and add more comments

---

components/tidb_query_expr/src/types/expr_builder.rs

Issue Number: close https://github.com/tikv/tikv/issues/11893
In https://github.com/tikv/tikv/pull/11968 ,  we supported push bit cloumn down but we forgot to support mysqlBit during extract scalar value.
This pr fixes it.
```commit-message
```
Tests 
- Unit test
```release-note
None
```

copr: support extract scalar value from bit

---

components/resource_metering/src/lib.rs
components/resource_metering/src/model.rs
components/resource_metering/src/recorder/sub_recorder/cpu.rs
components/resource_metering/src/reporter/mod.rs
components/txn_types/src/types.rs
src/coprocessor/endpoint.rs
src/storage/mod.rs

Issue Number: Close https://github.com/tikv/tikv/issues/11988.
```commit-message
*: collect key ranges for the read request in ResourceMeteringTag
```
Tests 
- Unit test
```release-note
None.
```

*: collect key ranges for the read request in ResourceMeteringTag

---

components/tidb_query_datatype/src/codec/chunk/column.rs

Issue Number: Close https://github.com/pingcap/tidb/issues/32506
For `MysqlBit` type column datum, it will carry `uint_flag` or `var_uint_flag` according to 
https://github.com/pingcap/tidb/blob/e42f26c3f8f9bfb3a0cbc903b4204fac13ac4eb6/util/codec/codec.go#L120-L121
in tidb
Also, the we should directly `append_bytes` for datum into column according to https://github.com/pingcap/tidb/blob/e42f26c3f8f9bfb3a0cbc903b4204fac13ac4eb6/util/chunk/chunk.go#L567-L568
in tidb
The previous implementation does not match the tidb, this request fixed it.
```commit-message
```
Tests 
- Unit test
I manually tested this requests with https://github.com/pingcap/tidb/pull/32497 which enabled push bit column down,  here is the test result: …

copr: fix missing flag solvement for bit column in decoding

---

components/tidb_query_aggr/src/util.rs
components/tidb_query_datatype/src/codec/chunk/column.rs
components/tidb_query_datatype/src/def/eval_type.rs
components/tidb_query_expr/src/impl_cast.rs
components/tidb_query_expr/src/types/expr_builder.rs

Signed-off-by: yisaer <disxiaofei@163.com>
Issue Number: Ref https://github.com/pingcap/tidb/issues/32506
revert #11968 #11980 #12016 for now due to solving bugs and with little testcases. We will support bit column down later with fully tested in future.
```release-note
None
```

copr: revert 11968/11980/12016

---

components/file_system/src/io_stats/mod.rs

Issue Number: Ref #10867 
Introduced by #11873 
Tests 
- No code
```release-note
None
```

build: fix a Mac build issue

---

Makefile

Signed-off-by: Jin Dong <djdongjin95@gmail.com>
Add one more `arm` check related to SSE.
Issue Number: close #12034
```commit-message
```
Tests 
- No code
Side effects
```release-note
```

build: add arm64 check on SSE in makefile

---

components/raftstore/src/store/worker/split_controller.rs

```commit-message
split_controller: add more sample function test cases
```
Tests 
- Unit test
```release-note
None.
```

split_controller: add more sample function test cases

---

Cargo.lock
Cargo.toml

Issue Number: Close #12075 
Features that should be only enabled in the next release may depend on this change.
```release-note
None
```

*: bump master branch version to v6.0.0-alpha

---

CONTRIBUTING.md
README.md

Issue Number: Close #12100
remove doc about wechat
- None
- No code
Side effects
None
```release-note
None
```

*: remove part about wechat in doc

---

Cargo.lock
Cargo.toml
components/concurrency_manager/Cargo.toml
components/encryption/src/io.rs
components/file_system/Cargo.toml
components/raft_log_engine/src/engine.rs
components/raftstore/Cargo.toml

Signed-off-by: Randy <ztelur@gmail.com>
What is changed and how it works?
Issue Number: ref https://github.com/tikv/tikv/issues/11119
- upgrade raft-engine dependency and other library version related to raft-engine
- replace old `ManagedFileBuilder ` with `ManagedFileSystem`, more detail in raft-engine [#165](https://github.com/tikv/raft-engine/issues/165)
Also refer to  https://github.com/tikv/tikv/pull/12051
Check List
Unit test
```release-note
None
```

engine: upgrade raft engine

---

Cargo.lock
components/concurrency_manager/Cargo.toml
components/concurrency_manager/src/lib.rs
components/tikv_util/src/lib.rs
components/tikv_util/src/memory.rs
components/txn_types/src/lib.rs
components/txn_types/src/timestamp.rs

Issue Number: Close #12070
Recreate a vec from raw parts instead of transmuting memory directly.
Tests 
- No code
```release-note
Fix possible undefined behavior for transmuting vec
```

*: Fix possible undefined behavior for transmuting vec

---

.github/pull_request_template.md

Issue Number: close https://github.com/tikv/tikv/issues/12103
Remove the pingcap/tidb-ansible from the PR template. It has been archived.
None
Tests 
- No code
Side effects
None
```release-note
None
```

github: Remove the pingcap/tidb-ansible from the PR template

---

components/raftstore/src/store/peer.rs
components/test_raftstore/src/server.rs
tests/failpoints/cases/test_merge.rs
tests/failpoints/cases/test_replica_read.rs

Issue Number: Close #12120
```commit-message
A new fail point "after_propose" is added to insert callback from the test.
Then we can ensure we release other key fail points after they take effect.
The other change is to retry request automatically to avoid stale command
errors.
```
Tests 
```release-note
None
```

tests: make raftstore tests about transactions more stable

---

CONTRIBUTING.md

Signed-off-by: jackwener <jakevingoo@gmail.com>
Issue Number: Close #12142
```commit-message
polish contributing.md
```
None
- No code
Side effects
None
```release-note
None
```

*: add tip in contributing.md

---

components/cdc/src/endpoint.rs
components/cdc/src/metrics.rs
components/tikv_util/src/worker/pool.rs

Add a metrics for count of pending CDC tasks.
```commit-message
cdc: add a metrics for count of pending tasks
```
Tests 
- No code
Side effects
```release-note
None
```

cdc: add a metrics for count of pending tasks

---

Cargo.lock
components/cdc/Cargo.toml
components/cdc/src/endpoint.rs

Issue Number:    close https://github.com/tikv/tikv/issues/12183
```commit-message
Remove usless deps and fix typos
```
None
Tests 
- No code
Side effects
None
```release-note
None
```

cdc: remove useless deps and fix typos

---

components/raftstore/src/store/worker/split_controller.rs

Issue Number: ref https://github.com/tikv/tikv/issues/12185.
* Add some test cases and comments.
* Optimizing the probability of sampling.
* Do not record the empty sampling result.
Run 10000 times with a different random range.
```shell
Prefix sum: [1, 2, 3, 4]
Random range: [0, 4]
counter: [3892, 2067, 1974, 2067]
Random range: [1, 4]
counter: [2480, 2445, 2566, 2509]
```
```commit-message
split_controller: refine and add some test cases for sample function
```
Tests 
- Unit test
```release-note
None.
```

split_controller: refine and add some test cases for sample function

---

components/resolved_ts/src/advance.rs
components/resolved_ts/src/metrics.rs

Issue Number: Close #12159
```commit-message
* Do not hold mutex during calling `get_store_async`
* Add more metrics
```
Tests 
- Unit test
```release-note
None
```

resolved_ts: fix oom and add more metrics

---

components/resolved_ts/src/endpoint.rs

Issue Number: Close #12231 
replace `unwrap` with warning log
```commit-message
resolved_ts: fix shutdown panic
```
Tests 
- Unit test
- No code
Side effects
```release-note
resolved_ts: fix shutdown panic
```

resolved_ts: fix shutdown panic

---

components/tikv_util/src/quota_limiter.rs

```commit-message
Quota limiter: increase refill duration to avoid much context switch cost.
```
- Need to cherry-pick to the release 6.0 branch
Tests 
- Unit test
- No code
Side effects
- None
```release-note
None
```

Quota limiter: increase refill duration to avoid much context switch cost

---

Cargo.lock
components/tikv_util/src/timer.rs
tests/failpoints/cases/test_storage.rs

Issue Number: Close #12202, Close #12198
Checkout https://github.com/tikv/grpc-rs/pull/566 for more details.
Tracing timer abnormal behavior.
```commit-message
update grpcio to fix UAF
```
Tests 
- Unit test
```release-note
None
```

*: update grpcio

---

Cargo.lock
Cargo.toml

Signed-off-by: purelind <purelind@gmail.com>
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

*: Bump version v6.0.0

---

components/engine_rocks/src/flow_listener.rs
components/engine_traits/src/engine.rs
components/server/src/server.rs
components/test_raftstore/src/cluster.rs
components/test_raftstore/src/util.rs
src/server/engine_factory.rs
src/server/mod.rs
tests/failpoints/cases/test_conf_change.rs

Issue Number: Close #12322
```commit-message
Use generic to reduce duplicated code and extract KvEngineFactory
for reuse in tests and future usage.
```
Tests 
- Unit test
```release-note
None
```

*: simplify setup

---

components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/lib.rs
components/engine_traits/src/raft_engine.rs
components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/local_metrics.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/metrics.rs
components/raftstore/src/store/worker/raftlog_gc.rs
etc/config-template.toml
metrics/grafana/tikv_details.json
src/server/metrics.rs
src/server/resolve.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Close #11404 
Cherry-pick https://github.com/tikv/tikv/pull/11405, https://github.com/tikv/tikv/pull/11376, https://github.com/tikv/tikv/pull/10599
Tests 
- Unit test
```release-note
Increase the size of write batch for raftlog GC to speed up GC.
```

[5.2] raftstore: increase batch for raftlog-gc-worker (#11405)

---

Cargo.toml
src/coprocessor_v2/plugin_registry.rs
src/server/service/diagnostics/sys.rs

Issue Number: Close #12390
```commit-message
1. Relax the IO load info assertion from "assert_eq" to assert "starts with".
So the test won't fail on Linux 4.19+ because of the extra fields.
2. Enable the `testexport` feature of `api_version` in the `dev-dependencies`
of `tikv`. Then, it is not necessary to specify the `testexport` feature manually
to compile tikv tests.
3.  For `plugin_registry` tests, search the dynamic library under the same
directory with the test binary. This avoids failures when people are running the
tests not under the cargo root or the default target directory path is changed. 
```
Tests 
- Unit test
```release-note
None
```

*: fix multiple unit test errors in local environments

---

Cargo.lock
Cargo.toml

Signed-off-by: purelind <purelind@gmail.com>
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

bump version v5.2.4

---

components/encryption/src/manager/mod.rs

Issue Number: Close #12462
when encryption enabled, many logs about new file, delete file logged in the logs. But we don't need these, because IV and method info recorded in rocksdb.
Only remove new file, delete file but not link file. log about link appear less so seem that keeping that looks acceptable.
```commit-message
encryption: reduce redundant log
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

encryption: reduce redundant log

---

Cargo.lock

Issue Number: ref #11119
Update Raft Engine to revert data format change (https://github.com/tikv/raft-engine/pull/218)
```commit-message
None
```
Tests 
- Unit test
```release-note
None
```

engine: update raft engine

---

components/kvengine/src/table/sstable/builder.rs
components/kvengine/src/table/sstable/iterator.rs
components/kvengine/src/table/sstable/sstable.rs
components/rfstore/src/mvcc.rs

```commit-message
Make the table format more extensible for future change.
```

kvengine: refine table format

---

components/backup-stream/src/router.rs

Issue Number: Close https://github.com/tikv/tikv/issues/12474
- Move v1_backupmeta_XXXX.meta to v1/backupmeta/XXX.meta
```commit-message
```
Tests 
Side effects
```release-note
None
```

br: move the file v1_backupmeta_xxxx.meta to v1/backupmeta/xxxx.meta

---

Cargo.lock
Cargo.toml

Issue Number:ref  #11966
```commit-message
bump version to 6.1-alpha
```
Tests 
- No code
Side effects
```release-note
None
```

bump master version to 6.1-alpha

---

Cargo.lock
Cargo.toml

Signed-off-by: lvhongmeng [hongmeng.lv@pingcap.com](mailto:hongmeng.lv@pingcap.com)
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
If this PR will be picked to release branch, then a …
```

bump version v5.4.1

---

tests/integrations/resource_metering/test_dynamic_config.rs

Issue Number: close #12541
```commit-message
stabilize some integration test
```
Tests 
```release-note
None
```

test: stabilize resouce_metering::test_dynamic_config::test_report_interval

---

components/cloud_server/src/signal_handler.rs
components/cloud_server/src/status_server/mod.rs
components/cloud_server/src/tikv_server.rs
components/rfengine/src/engine.rs
components/rfengine/src/lib.rs
components/rfengine/src/load.rs
components/rfengine/src/traits.rs
components/rfengine/src/worker.rs
components/rfstore/src/errors.rs
components/rfstore/src/lib.rs
components/rfstore/src/store/engine.rs
components/rfstore/src/store/peer_storage.rs
components/rfstore/src/store/peer_worker.rs
components/rfstore/src/store/recover.rs

- [rename RFEngine to RfEngine to follow rust naming [convention](](https://github.com/tikv/tikv/commit/f3d0bb14852de35a7df55018642f064e99138d5a)[https:…](https://rust-lang.github.io/api-guidelines/naming.html)
- [fix unused lint](https://github.com/tikv/tikv/commit/4514c4ad8a23c5a90eff420982534ce8b7120289)
- [rfengine: add tests for RaftLogs](https://github.com/tikv/tikv/commit/079b4f45ee0b2952e07b0bad237b1d5c0ba71496)
```commit-message
rfengine: refactor and add tests for RaftLog*
```
Tests 
- Unit test
Side effects
```release-note
None
```

rfengine: refactor and add tests for RaftLog*

---

components/rfengine/src/engine.rs
components/rfengine/src/worker.rs
components/rfengine/src/writer.rs

```commit-message
`fsync` the directory whenever creates or removes a file.
```
Tests 
- No code
Side effects
```release-note
None
```

rfengine: add missing sync_dir

---

components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_controller.rs

```commit-message
raftstore: refine some code of the PD and SplitController
```
Tests 
- Unit test
```release-note
None.
```

raftstore: refine some code of the PD and SplitController

---

components/raftstore/src/store/fsm/store.rs

Issue Number: Ref #12664 
```commit-message
...So we can know what is actually happening.
```
Tests 
- Unit test
```release-note
None
```

add logs for entry missing

---

Cargo.lock
cmd/tikv-ctl/Cargo.toml
components/external_storage/export/Cargo.toml
components/external_storage/export/src/bin/tikv-cloud-storage.rs
components/file_system/Cargo.toml
components/keys/Cargo.toml
components/resource_metering/Cargo.toml
components/server/Cargo.toml
components/server/src/signal_handler.rs
components/tidb_query_datatype/Cargo.toml
components/tidb_query_executors/src/simple_aggr_executor.rs
components/tidb_query_expr/src/impl_cast.rs
components/tidb_query_expr/src/impl_math.rs
components/tidb_query_expr/src/impl_miscellaneous.rs
components/tidb_query_expr/src/impl_op.rs
components/tikv_util/Cargo.toml

Issue Number: Close #12773.
```commit-message
replace signal with signal-hook and update other deps by depbot.
```
Tests 
- Unit test
```release-note
None
```

update several deps

---

Cargo.lock
Cargo.toml

Signed-off-by: lvhongmeng [hongmeng.lv@pingcap.com](mailto:hongmeng.lv@pingcap.com)
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
If this PR will be picked to release branch, then a …
```

bump version v6.1.0

---

metrics/grafana/tikv_details.json

Issue Number: Close #12787
```commit-message
Add missing metrics for async io code path
```
Tests 
- No code
Side effects
- None
```release-note
None
```

metrics: Add missing metrics for async io code path

---

Cargo.lock
Cargo.toml

Issue Number: close https://github.com/tikv/tikv/issues/12859
```
bump version to 6.1-alpha
```
Tests 
- No code
```release-note
None
```

bump master version to 6.2-alpha

---

Cargo.lock
Cargo.toml
components/server/src/signal_handler.rs
components/tikv_util/src/metrics/mod.rs
etc/config-template.toml
src/server/config.rs
src/server/service/debug.rs
src/server/status_server/mod.rs
src/storage/config.rs
tests/integrations/backup/mod.rs
tests/integrations/config/mod.rs

Issue Number: ref #12355
Cherry pick #12356 #12417 #12671
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

server: support return simplified metrics and gzip compression

---

Cargo.lock
components/backup-stream/Cargo.toml
components/backup-stream/src/endpoint.rs
components/backup-stream/src/errors.rs
components/backup-stream/src/event_loader.rs
components/backup-stream/src/lib.rs
components/backup-stream/src/metadata/client.rs
components/backup-stream/src/metadata/keys.rs
components/backup-stream/src/metadata/metrics.rs
components/backup-stream/src/metadata/mod.rs
components/backup-stream/src/metadata/store/etcd.rs
components/backup-stream/src/metadata/store/lazy_etcd.rs
components/backup-stream/src/metadata/store/mod.rs
components/backup-stream/src/metadata/store/slash_etc.rs
components/backup-stream/src/metadata/test.rs
components/backup-stream/src/metrics.rs
components/backup-stream/src/observer.rs
components/backup-stream/src/router.rs
components/backup-stream/src/subscription_manager.rs
components/backup-stream/src/subscription_track.rs
components/backup-stream/src/utils.rs
components/backup-stream/tests/mod.rs
components/external_storage/src/lib.rs
components/security/Cargo.toml
components/security/src/lib.rs
components/server/Cargo.toml
components/server/src/server.rs
components/sst_importer/src/sst_importer.rs

Issue Number: Close #12895
1. [log-backup: adapt user-defined TLS config](https://github.com/tikv/tikv/pull/12640)
2. [log backup: disable test log by default](https://github.com/tikv/tikv/pull/12710)
3. [log-backup: fix bug about restoring point at TiCloud with KMS](https://github.com/tikv/tikv/pull/12757)
4. [security, server: fix running local test](https://github.com/tikv/tikv/pull/12712)
5. [log_backup: adapt the enhanced checkpoint model](https://github.com/tikv/tikv/pull/12770)
6. [log-backup: update flush time if succeeding in do_flush](https://github.com/joccau/tikv/pull/6)
7. [remove metrics after task stopped](https://github.com/joccau/tikv/pull/7)
8. [log_backup: update max ts](https://github.com/joccau/tikv/pull/8)
9. [log-backup: limit concurrent fluent when …

log-backup: support pitr feature for PoC test

---

Cargo.lock
Cargo.toml

Signed-off-by: lvhongmeng <hongmeng.lv@pingcap.com>
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note …
```

bump version v5.3.2

---

components/raftstore/src/store/worker/mod.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_config.rs
components/raftstore/src/store/worker/split_controller.rs

Issue Number: ref #12063. This is a sub-PR of #12593.
```commit-message
Introduce the new split config and CPU collector registration mechanism.
```
Tests 
- Unit test
```release-note
None.
```

pd_worker, split_controller: introduce the new config and CPU collector registration mechanism

---

components/backup-stream/src/endpoint.rs
components/cdc/src/endpoint.rs
components/cdc/src/metrics.rs

Issue Number: Close #12967
```commit-message
cdc: add min_resolved_ts_lag metrics
```
Tests 
Just run TiKV and TiCDC.
```release-note
None
```

cdc: add min_resolved_ts_lag metrics

---

components/raftstore/src/store/worker/split_controller.rs

```commit-message
Add some test cases for the CPU-based Load Base Split strategy.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: add some test cases for the CPU-based Load Base Split strategy

---

Cargo.lock
Cargo.toml

Signed-off-by: lvhongmeng <hongmeng.lv@pingcap.com>
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note …
```

bump version v5.4.2

---

src/server/service/debug.rs

Signed-off-by: CalvinNeo <calvinneo1995@gmail.com>
Issue Number: ref #12849
```commit-message
Parameterize debug service
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

debug: Parameterize debug service

---

Cargo.lock
components/engine_panic/src/raft_engine.rs
components/engine_rocks/src/raft_engine.rs
components/engine_traits/src/raft_engine.rs
components/raft_log_engine/src/engine.rs
components/raftstore-v2/Cargo.toml
components/raftstore-v2/src/batch/apply.rs
components/raftstore-v2/src/batch/mod.rs
components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/fsm/mod.rs
components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/fsm/store.rs
components/raftstore-v2/src/lib.rs
components/raftstore-v2/src/raft/peer.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/tests/failpoints/test_bootstrap.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/tikv_util/src/lib.rs
src/coprocessor/endpoint.rs

Currently, it's hard to test the change without supporting building dyn TabletFactory from engine_test. I will add the test case after such support is added.
```commit-message
```
Tests 
- Unit test
```release-note
None
```

raftstorev2: support building store batch system

---

components/raftstore/src/store/worker/split_controller.rs

```commit-message
Update the Load Base Split metrics event to distinguish more cases.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: update the Load Base Split metrics event

---

components/raftstore/src/store/worker/split_controller.rs

```commit-message
Fix the building warning caused by the feature cfg.
```
Tests 
- Unit test
```release-note
None.
```

raftstore: fix the building warning caused by the feature cfg

---

metrics/grafana/tikv_details.json

Signed-off-by: Yu Juncen <yujuncen@pingcap.com>
Issue Number: Ref #12534
Added some new metrics about advancer (for easier to use, even those series are provided by TiDB, we still added them to TiKV, maybe we'd better make an standalone board like CDC?) 
```commit-message
Added the advancer metrics.
```
Tests 
- No code
```release-note
Added metrics about advancer of log backup.
```

log-backup: added some new metrics for log backup

---

components/engine_rocks/src/perf_context_metrics.rs
components/external_storage/src/metrics.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/worker/metrics.rs
src/coprocessor/metrics.rs
src/server/lock_manager/metrics.rs
src/server/metrics.rs
src/storage/metrics.rs
src/storage/txn/scheduler.rs

Signed-off-by: ekexium <eke@fastmail.com>
Issue Number: Close #13036
```commit-message
Change the smallest bucket size from 500us to 10 us for many metrics
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

make the smallest bucket size 10 us for many metrics

---

Cargo.lock
components/engine_rocks/src/write_batch.rs
tests/integrations/raftstore/test_compact_after_delete.rs
tests/integrations/raftstore/test_merge.rs
tests/integrations/raftstore/test_snap.rs

Issue Number: close tikv/tikv#13038
Tests 
- Manual test 
- sysbench prepare 
Side effects
- None
- None 
```release-note
None
```

Fix panic when enable titan

---

Cargo.lock
src/config.rs

Issue Number: Close #13145
```commit-message
Make max_subcompactions dynamically changeable
```
Tests 
- No code
Side effects
- None
```release-note
Make max_subcompactions dynamically changeable
```

Make max_subcompactions dynamically changeable

---

components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/worker/check_leader.rs
components/tikv_util/src/mpsc/mod.rs
tests/failpoints/cases/test_split_region.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

```commit-message
Cherry pick #13168 and #13193 to release-5.4 hotfix
```
Tests 
- Unit test
```release-note
None
```

Cherry pick #13168 and #13193 to release-5.4 hotfix

---

src/server/service/diagnostics/sys.rs

Signed-off-by: Lloyd-Pottiger <yan1579196623@gamil.com>
Issue Number: Close #13217
https://github.com/tikv/tikv/issues/13217#issuecomment-1204785017
```commit-message
support cgroup limit memory in diagnostics service
```
Tests 
```release-note
None
```

diagnostics: support cgroup limit memory

---

metrics/grafana/tikv_details.json

Issue Number: Close #13274 
```commit-message
fix the panel description for gc compaction filter
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

metric: fix the panel description for gc compaction filter

---

components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore/src/store/async_io/write.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/local_metrics.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/metrics.rs

Issue Number: Ref #12876
```commit-message
Simplify raft local metrics by using local counter provided by rust-prometheus
```
Tests 
- No code
```release-note
None
```

raftstore: Simplify raft local metrics

---

Cargo.lock
Cargo.toml

What's Changed: bump version to 6.2.0
Tests 
Side effects

bump version to 6.2.0

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

bump version to 6.1.1

---

Cargo.lock
Cargo.toml
components/error_code/src/raftstore.rs
components/raftstore/src/errors.rs
etc/error_code.toml
tests/integrations/raftstore/test_flashback.rs
tests/integrations/server/kv_service.rs

Issue Number: Close #13397. Should merge https://github.com/pingcap/kvproto/pull/982 before this PR.
```commit-message
Introduce the non-retryable error `FlashbackInProgress` for the region in the flashback progress to reject any read or write.
```
Tests 
- Unit test
```release-note
None.
```

*: introduce the non-retryable error FlashbackInProgress

---

Cargo.lock
components/cloud/aws/Cargo.toml
components/cloud/aws/src/s3.rs
components/cloud/aws/src/util.rs
components/cloud/src/metrics.rs
components/tikv_util/src/stream.rs

cherry-pick #13343 to release-5.4-20220824
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

cloud: add retry on web identity credentials (#13343)

---

Cargo.lock
Cargo.toml

bump version to 5.3.3

---

Cargo.lock
Cargo.toml
components/engine_tirocks/Cargo.toml
components/engine_tirocks/src/lib.rs
components/engine_tirocks/src/status.rs

Issue Number: Ref #13058 
```commit-message
Only make it in the codebase, will not compile it. It will replace
engine_rocks once it's finished.
```
Tests 
- Manual test
Uncomment the member list and `make dev`.
```release-note
None
```

components: introduce tirocks module

---

Cargo.lock
Cargo.toml
components/txn_types/src/lib.rs
components/txn_types/src/lock.rs
src/server/lock_manager/waiter_manager.rs
src/storage/errors.rs
src/storage/mvcc/mod.rs
src/storage/mvcc/reader/point_getter.rs
src/storage/mvcc/reader/scanner/backward.rs
src/storage/mvcc/reader/scanner/forward.rs
src/storage/mvcc/txn.rs
src/storage/txn/actions/acquire_pessimistic_lock.rs
src/storage/txn/actions/prewrite.rs

Signed-off-by: ekexium <eke@fastmail.com>
Issue Number: Close #13423 
Related kvproto change is in 
- https://github.com/pingcap/kvproto/pull/983
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

txn: distinguish different types of write conflicts

---

Cargo.lock
components/file_system/src/rate_limiter.rs
components/raftstore/src/store/util.rs
components/resolved_ts/Cargo.toml
components/resolved_ts/src/cmd.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/tests/integrations/mod.rs
components/resolved_ts/tests/mod.rs

Signed-off-by: hehechen <awd123456sss@gmail.com>
Issue Number: Ref #13353
```
Update tracked_index in `CmdType::IngestSst` scenario.
```
Tests 
- Unit test
Add log in TiFlash proxy to see whether tracked_index is updated.
```release-note
None
```

resolved_ts: track ingest sst

---

components/raftstore/src/store/util.rs
components/raftstore/src/store/worker/pd.rs
components/resolved_ts/tests/mod.rs

Issue Number: Close #13437.
```commit-message
Clarify the use of term `safe_ts` and `resolved_ts`.
```
Tests 
- Unit test
```release-note
None.
```

raftstore, resolved_ts: clarify the use of term safe_ts and resolved_ts

---

components/backup-stream/src/subscription_track.rs
components/backup/src/endpoint.rs
components/causal_ts/src/lib.rs
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/initializer.rs
components/cdc/src/observer.rs
components/cdc/tests/failpoints/test_endpoint.rs
components/cdc/tests/mod.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/src/resolver.rs
components/server/src/server.rs
components/test_raftstore/src/server.rs
src/config.rs
src/server/node.rs
src/storage/kv/test_engine_builder.rs
src/storage/mod.rs

Issue Number: Ref #13284 
```
Rawkv resolved_ts is now implemented by ConcurrencyManager in https://github.com/tikv/tikv/pull/13326. remove the old implementation code.
This PR is mainly revert the change of PR https://github.com/tikv/tikv/pull/12866
```
Tests 
- Unit test
Side effects
```release-note
None
```

cdc: Clean rawkv resolved ts code

---

components/engine_rocks/src/write_batch.rs
components/engine_tirocks/Cargo.toml
components/engine_tirocks/src/engine.rs
components/engine_tirocks/src/lib.rs
components/engine_tirocks/src/logger.rs
components/engine_tirocks/src/perf_context.rs
components/engine_tirocks/src/write_batch.rs
components/raftstore/src/store/metrics.rs

Issue Number: Ref #13058 
```commit-message
`PerfContext` is almost the same as rocks except reference type name
changes. `WriteBatch` is simplified by removing unnecessary fields
and optimized for merge batches.
```
Tests 
- Unit test
```release-note
None
```

engine_tirocks: add write batch and perf context

---

metrics/grafana/tikv_details.json

Issue Number: Close #13537
```commit-message
fix error grafana expr for `tikv_gc_compaction_filtered `
```
Tests 
No error in grafana.
```release-note
None
```

metrics: fix grafana expr for `tikv_gc_compaction_filtered`

---

Cargo.lock
components/engine_rocks/Cargo.toml

Issue Number: Close https://github.com/tikv/tikv/issues/13534
Update rocksdb to include regression fix https://github.com/tikv/rocksdb/pull/316
```commit-message
```
- Update master branch
Tests 
- Unit test
```release-note
None
```

engine: update rocksdb

---

Cargo.lock

Issue Number: Close #13543
```commit-message
upgrade jemalloc for release-5.4
```
- Need to cherry-pick the release branch
Tests 
Side effects
```release-note
upgrade jemalloc for release-5.4
```

*: upgrade jemalloc for release-5.4

---

components/tikv_util/src/lru.rs

Issue Number: Close #13551
```commit-message
It's error-prone to use reference/`Box` and raw pointer/`NonNull` at the same time. 
This PR replaces `Box` by `NonNull` and always use it as parameter.
```
For example, `following.prev` at L32 immediately invalidates the `NonNull::new_unchecked(following)` at L31.
https://github.com/tikv/tikv/blob/a68a44e09dd4ef7de59db22b11593e7abd4e94df/components/tikv_util/src/lru.rs#L30-L33
Tests 
- Unit test
Side effects
```release-note
None
```

tikv_util: make LruCache sound

---

Cargo.lock
components/engine_rocks/src/misc.rs

Issue Number: Close #13534
Synchronize the changes that are already in release-6.3.
```commit-message
```
https://github.com/tikv/tikv/pull/13538
https://github.com/tikv/tikv/pull/13531
Tests 
- Unit test
```release-note
None
```

engine: fix performance issue of deleting files in ranges

---

Cargo.lock
Cargo.toml

Issue Number: close https://github.com/tikv/tikv/issues/13563
```commit-message
bump master version to v6.4.0-alpha
```
Tests 
Side effects
```release-note
```

bump master version to v6.4.0-alpha

---

Cargo.lock
Cargo.toml

Issue Number: None
bump version to 5.4.3
Tests 
Side effects

bump version to 5.4.3

---

Cargo.lock
components/batch-system/Cargo.toml
components/batch-system/src/lib.rs
components/batch-system/src/metrics.rs
components/batch-system/src/router.rs
components/raftstore/Cargo.toml
components/raftstore/src/lib.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/msg.rs
etc/error_code.toml

```commit-message
Add more details to help the diagnosis of slow ready handle.
```
[code changes](https://github.com/you06/tikv/compare/v4.0.6...v4.0.6-patch)
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore: add metrics for slow ready handle diagnosis

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

bump version to 6.1.2

---

components/test_raftstore/src/cluster.rs
etc/error_code.toml
tests/integrations/raftstore/test_flashback.rs

Issue Number: ref #13303.
```commit-message
Refine the flashback raftstore test.
```
Tests 
- Unit test
```release-note
None.
```

tests: refine the flashback raftstore test

---

src/storage/mod.rs

Issue Number: Close #13635 
```
Add rawkv empty key/value test
```
Tests 
- Unit test
Side effects
```release-note
None.
```

test: Add rawkv empty key/value test

---

tests/integrations/raftstore/test_snap_recovery.rs

Signed-off-by: cosven <yinshaowen241@gmail.com>
Issue Number: Close https://github.com/tikv/tikv/issues/13603
```commit-message
fix one flaky testcase
```
```release-note
```

tests: fix one flaky testcase

---

components/cdc/Cargo.toml
components/cdc/src/endpoint.rs
components/cdc/tests/failpoints/test_endpoint.rs
components/raftstore/src/store/util.rs
components/resolved_ts/src/advance.rs
components/resolved_ts/src/endpoint.rs
components/test_raftstore/src/server.rs

Issue Number: Close #13656
Reuse map and set in check leader to save CPU, and helps to reduce TiCDC latency.
```commit-message
cdc, resolved_ts: add leadership resolver
```
Tests 
- Unit test
```release-note
None
```

cdc, resolved_ts: add leadership resolver 

---

Cargo.lock

close tikv/tikv#13543
upgrade jemalloc for release-5.4
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
```commit-message
*: upgrade jemalloc for release-5.4 (#13545)
```
Tests 
- Unit test
- No code
Side effects
```release-note
Upgrade jemalloc to fix the heap profiling empty issues
```

*: upgrade jemalloc for release-5.4 (#13545)

---

components/raftstore/src/store/fsm/apply.rs

Issue Number: Close #13726 
```commit-message
avoid unnecessary clone
```
Tests 
- No code
```release-note
None
```

apply: avoid unnecessary clone

---

Cargo.lock
Cargo.toml

Signed-off-by: mornyx <mornyx.z@gmail.com>
Issue Number: Close #13732
- Upgrade `pprof-rs` to v0.11
For details on the reasons for this upgrade, please refer to:
- https://github.com/tikv/tikv/issues/13732
- https://github.com/tikv/pprof-rs/pull/172
```release-note
None
```

*: upgrade pprof-rs to v0.11

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

bump version to 6.4.0

---

Cargo.lock
Cargo.toml

Issue Number: close https://github.com/tikv/tikv/issues/13763
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
If this PR will be picked to …
```

bump version to 6.5.0-alpha

---

Cargo.lock
Cargo.toml

Issue: bump version to 5.3.4
What's Changed: version in cargo.toml bump to 5.3.4
```commit-message
```
Tests 
Side effects

bump version to v5.3.4

---

Cargo.lock
Cargo.toml

Revert "bump version to v5.3.4"

---

tests/integrations/raftstore/test_flashback.rs

Issue Number: ref #13303.
```commit-message
Refine the raftstore flashback tests.
```
Tests 
- Unit test
```release-note
None.
```

tests: refine the raftstore flashback tests

---

components/test_raftstore/src/cluster.rs

Issue Number: Close #13816
```commit-message
fix flaky witness test
```
Tests 
- No code
```release-note
None
```

test: fix flaky witness test

---

components/tikv_kv/src/btree_engine.rs
components/tikv_kv/src/lib.rs
components/tikv_kv/src/mock_engine.rs
components/tikv_kv/src/rocksdb_engine.rs
src/lib.rs
src/server/gc_worker/gc_worker.rs
src/server/raftkv.rs
src/storage/mod.rs
tests/benches/misc/raftkv/mod.rs
tests/failpoints/cases/test_coprocessor.rs

Issue Number: Ref #13827.
```commit-message
so we can reduce allocation and keep compatible with both v1 and v2.
```
Tests 
- Unit test
```release-note
None
```

tikv_kv: make async_snapshot return future

---

src/storage/mvcc/reader/reader.rs

Issue Number: Close #13839
```commit-message
The mvcc get_write methods should return None if the found record is a Delete.
This constraint is broken after the introduction of skipping locks, causing
panic when reading values.
Now, it's changed to use the same logic in the loop (just like the PointGetter and
the ForwardScanner) to avoid the problem.
```
Tests 
- Unit test
```release-note
None
```

mvcc: fix get_write may return Delete when skipping versions

---

Cargo.lock
Cargo.toml

Bump version to 6.1.3
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 6.1.3

---

src/storage/mvcc/reader/reader.rs

Issue Number: Close #13844.
```commit-message
Fix the bug that when a key's last write record is `WriteType::Lock` or `WriteType::Rollback`,
the `scan_writes` will return the invisible write record as the result, which will affect the flashback correctness.
```
Tests 
- Unit test
```release-note
None.
```

reader: fix the invisible write record flashback bug

---

src/import/sst_service.rs

Issue Number: 
Close https://github.com/tikv/tikv/issues/13853
Ref https://github.com/pingcap/tidb/issues/39398
- filter out invalid k-v events when applying kv-file on PiTR
```commit-message
```
Tests 
Side effects
```release-note
Filter out invalid k-v events when applying kv-file on PiTR
```

filter out invalid k-v events when applying kv-file on PiTR

---

Cargo.lock
Cargo.toml
src/coprocessor/endpoint.rs
tests/integrations/coprocessor/test_select.rs

Issue Number: Close #13849 
The proto change is https://github.com/pingcap/kvproto/pull/1018.
```commit-message
Support batch coprocessor task processing in tikv. All the tasks would be passed to tikv in a single RPC
request, they would be executed concurrently and all the results would be sent back in one response.
More tests and investigations are needed together  with the coprocessor client changes.
```
Tests 
- Unit test
Side effects
```release-note
None
```

cop: support batch coprocessor processing in tikv

---

Cargo.lock
components/tikv_kv/src/btree_engine.rs
components/tikv_kv/src/lib.rs
components/tikv_kv/src/mock_engine.rs
components/tikv_kv/src/rocksdb_engine.rs
components/tikv_util/src/future.rs
components/tikv_util/src/mpsc/future.rs
src/server/gc_worker/gc_worker.rs
src/server/raftkv.rs
src/storage/mod.rs
src/storage/raw/raw_mvcc.rs
src/storage/txn/scheduler.rs
tests/Cargo.toml
tests/benches/hierarchy/mvcc/mod.rs
tests/benches/misc/raftkv/mod.rs

Issue Number: Ref #13827
```commit-message
This PR abstracts write interface with Stream trait so that we can keep compatible with
both v1 and v2.
```
Tests 
- Unit test
```release-note
None
```

tikv_kv: make async_write return stream

---

src/import/sst_service.rs

Issue Number: Close https://github.com/tikv/tikv/issues/13862
Fix the issue that tikv-server starts failed.
```commit-message
```
Tests 
- Patch the tikv-server and the TiKV boost normally.
- Restore data into down-stream cluster successfully with PiTR operation.
Side effects
```release-note
None
```

fix the issue that TiKV starts failed.

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to v6.5.0

---

src/storage/mod.rs
src/storage/txn/actions/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs
src/storage/txn/commands/mod.rs
tests/integrations/server/kv_service.rs

Issue Number: Close #13879 
```commit-message
Resolve EBS flashback unlimit range.
```
Tests 
- Unit test
```release-note
None
```

storage: Resolve EBS flashback unlimit range

---

components/pd_client/src/client_v2.rs

Issue Number: ref #13673
```commit-message
remove `unused_imports` when make release.
```
```release-note
None
```

pd_client: move ReadableDuration to failpoint

---

Cargo.lock
Cargo.toml
components/tikv_util/Cargo.toml
components/tikv_util/src/sys/mod.rs
src/server/service/diagnostics/mod.rs
src/server/service/diagnostics/sys.rs

Issue Number: ref #11276
Update [sysinfo](https://crates.io/crates/sysinfo) dependency from 0.16.4 to 0.26.5
Tests 
- No code
```release-note
None
```

*: Update sysinfo dependency

---

components/raftstore/src/store/util.rs

Signed-off-by: hehechen <awd123456sss@gmail.com>
Issue Number: Close #13896
```
Pass full safe_ts timestamp to observer.
```
Tests 
- Unit test
```release-note
None
```

resolved_ts: pass full safe_ts timestamp to observer

---

components/raftstore/src/store/fsm/peer.rs

Signed-off-by: Yang Zhang <yang.zhang@pingcap.com>
Issue Number: Ref #13908
```commit-message
Nit: use lib API to improve readability
```
Tests 
- Unit test
- No code
Side effects
N/A
```release-note
None
```

Improve readability through syntax sugar

---

Cargo.lock
cmd/tikv-ctl/src/executor.rs
cmd/tikv-ctl/src/main.rs
components/engine_rocks/src/options.rs
components/engine_rocks/src/raw.rs
components/engine_rocks/src/util.rs
components/engine_test/src/lib.rs
components/engine_traits/Cargo.toml
components/engine_traits/src/tablet.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/query/local.rs
components/raftstore-v2/src/operation/ready/snapshot.rs
components/raftstore-v2/src/raft/peer.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore-v2/tests/integrations/cluster.rs
components/raftstore-v2/tests/integrations/test_basic_write.rs
components/raftstore-v2/tests/integrations/test_conf_change.rs
components/server/src/server.rs
components/snap_recovery/src/init_cluster.rs
src/config/mod.rs
src/server/engine_factory.rs
src/storage/config.rs
src/storage/kv/test_engine_builder.rs
src/storage/mod.rs
src/storage/txn/flow_controller/tablet_flow_controller.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml
tests/integrations/storage/test_titan.rs

```commit-message
- No WAL should be written
- raftcf is dropped
- No concurrent write
- No multi batch write
- Use smaller bloomfilter ratio to reduce memory footprint
```
Tests 
- Unit test
```release-note
None
```

*: add raftstore v2 only tablet optimization

---

README.md
SECURITY.md

1. Rename `security/SECURITY.md` to `SECURITY.md` to match what GitHub expects.
2. Add version 5.x and 6.x to the list of versions
Issue Number: Close #13928 
Tests 
- No code
```release-note
None
```

*: Update security policy

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to v6.6.0-alpha

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump nightly to v5.1.5

---

Makefile

Issue Number: Close #13950
```commit-message
cargo sort will somehow modify Cargo.toml even there is nothing to change.
This PR avoid cache being invalidated by check first.
```
Tests 
See #13950.
```release-note
None
```

Makefile: check before sort deps

---

components/raftstore-v2/src/router/response_channel.rs

Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
Issue Number: Close #13970 
```commit-message
Fix compilation errors.
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore-v2: fix compilation errors.

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/pd.rs
components/raftstore-v2/src/router/imp.rs
components/raftstore-v2/src/router/message.rs

```commit-message
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: update region size after split check

---

components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/operation/pd.rs
components/raftstore-v2/src/worker/pd/mod.rs
components/raftstore-v2/src/worker/pd/store_heartbeat.rs
components/raftstore-v2/tests/integrations/test_pd_heartbeat.rs

Signed-off-by: bufferflies <1045931706@qq.com>
Issue Number: Ref https://github.com/tikv/tikv/issues/12842
```commit-message
1. store heartbeat should add snapshot and kv engine used size 
```
Tests 
- Unit test
Side effects
```release-note
None.
```

raftstore-v2: store heartbeat add kv size and snap size

---

components/raftstore-v2/src/fsm/apply.rs
components/raftstore-v2/src/operation/command/admin/compact_log.rs
components/raftstore-v2/src/operation/command/admin/conf_change.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/life.rs
components/raftstore-v2/src/operation/mod.rs
components/raftstore-v2/src/operation/ready/apply_trace.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/operation/ready/snapshot.rs
components/raftstore-v2/src/raft/apply.rs
components/raftstore-v2/src/raft/storage.rs

```commit-message
Make apply adaptive to reduce high tail latency.
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: adaptive apply

---

Cargo.lock
components/pd_client/src/client.rs
components/pd_client/src/client_v2.rs
components/pd_client/src/lib.rs
components/test_pd/src/mocker/mod.rs
tests/failpoints/cases/test_pd_client.rs
tests/failpoints/cases/test_pd_client_legacy.rs

Issue Number: close #14042 
```commit-message
Due to operation error, the kvproto was updated in advance https://github.com/pingcap/kvproto/pull/1035
so this pr  is just for make sure compatibility
No one is currently using this interface and there is already a corresponding pr https://github.com/tikv/tikv/pull/14022
```
Tests 
- Unit test
```release-note
None
```

pd_client:  fix the kvproto compatibility for global config

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/admin/conf_change.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/command/admin/transfer_leader.rs
components/raftstore-v2/src/operation/mod.rs
components/raftstore-v2/src/operation/pd.rs
components/raftstore-v2/src/operation/query/local.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/operation/txn_ext.rs
components/raftstore-v2/src/raft/peer.rs
src/storage/txn/scheduler.rs

```commit-message
Move transaction related code to txn_ext.rs.
Fix the bug that snapshot doesn't set term and extra_op.
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: cleanup txn_ext

---

components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/operation/ready/snapshot.rs
components/raftstore/src/store/mod.rs
src/config/mod.rs

```commit-message
1) add snapshot apply metrics
2) disable bloomfilter for raftkv-v2 for now until a proper ratio is found 
3) disable rocksdb write stall for raftkv-v2 until the tablet flow control is fully verified.
```
Tests 
- No code
```release-note
```

raftstore-v2: a few small fixes

---

Cargo.lock
Cargo.toml

Signed-off-by: purelind <purelind@gmail.com>
bump version to 6.1.4
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 6.1.4

---

Cargo.lock
components/batch-system/src/router.rs
components/pd_client/Cargo.toml
components/pd_client/src/client.rs
components/pd_client/src/client_v2.rs
components/pd_client/src/metrics.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/fsm/store.rs

Issue Number: Close #14086
```commit-message
PD_REQUEST_HISTOGRAM_VEC can be changed to use static metrics to improve performance.
```
```release-note
None
```

pd_client: replace PD_REQUEST_HISTOGRAM_VEC with static metrics

---

src/config/mod.rs
src/storage/config.rs
tests/integrations/config/test-custom.toml

```commit-message
add an alias partitioned-raft-kv for RaftKv2
```
Tests 
- Unit test
```release-note
None
```

storage: add an alias partitioned-raft-kv for RaftKv2

---

Cargo.lock
components/resource_control/src/resource_group.rs
components/resource_control/src/service.rs

Issue Number: Close https://github.com/tikv/tikv/issues/14120
```commit-message
resource_control: unify wru/rru to ru
```
Tests 
- Unit test
```release-note
None
```

resource_control: unify wru/rru to ru

---

Cargo.lock
Cargo.toml
components/resource_control/Cargo.toml
components/resource_control/src/resource_group.rs
components/resource_control/src/service.rs
components/test_pd/src/mocker/mod.rs
components/test_pd/src/server.rs
tests/failpoints/cases/test_pd_client_legacy.rs

Issue Number: Close #14104 Should merge after https://github.com/pingcap/kvproto/pull/1051
```commit-message
We need to use the new field to support item value as bytes to avoid proto string check failures.
```
Tests 
- Unit test
```release-note
None
```

pd_client: fix item value type

---

tests/failpoints/cases/test_rawkv.rs

Signed-off-by: Ping Yu <yuping@pingcap.com>
Issue Number: Close #14141 
```commit-message
rawkv: fix flaky integration test case `test_raw_put_key_guard`.
```
The original `2s` seems to be not enough occasionally in the CI environment.
So I prolong this timeout to `5s` and retry every `200ms` to speed up in most cases.
- No.
Tests 
- Unit test
Side effects
- No.
```release-note
rawkv: fix flaky integration test case `test_raw_put_key_guard`.
```

rawkv: fix flaky integration test case `test_raw_put_key_guard`

---

components/snap_recovery/src/init_cluster.rs

Signed-off-by: fengou1 <feng.ou@pingcap.com>
Issue Number: Close #14017 
ebs volume snapshot support tikv node equipped with 2 cpu or less configuration.
To prevent mistakenly inputting too large values, the rocksdb max background limit is made according to the cpu quota * 10. Notice 10 is only an estimate, not an empirical value.
snapshot recovery mode has rocksdb max background job configured as 32 in recovery mode, which requires min CPU is 4. we change this value as min[32, cpu quota*10] 
Tests 
- Unit test
1. make a docker image
2. create cluster with 2 cpu tikv node
3. backup and restore
- No code
Side …

fix: ebs volume snapshot support tikv node equipped with 2 cpu or less configuration

---

components/tidb_query_expr/src/types/expr_builder.rs

Issue Number: Close https://github.com/tikv/tikv/issues/14156
Close https://github.com/pingcap/tidb/issues/40341
Make `is_expr_eval_to_scalar` can identifie const Enum.
```commit-message
copr: fix error when cast const Enum to any type
```
Tests 
- Unit test
- No code
Side effects
```release-note
If you don't …
```

copr: fix error when cast const Enum to any type

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to v6.6.0

---

Cargo.lock
components/server/src/server.rs
components/server/src/server2.rs
src/coprocessor/endpoint.rs
src/read_pool.rs
src/storage/mod.rs
tests/failpoints/cases/test_storage.rs

This reverts commit d083fc92d5228fb4bfc74a98e5ae7982d8fef22a from release-6.6.
Issue Number: Ref #14200
```commit-message
We don't intend to release this feature on 6.6.
```
Tests 
- Manual test
```release-note
None
```

Revert #14077 from release-6.6

---

src/read_pool.rs

Issue Number: Close #14200
```commit-message
We may get inconsistent state when calling `get_sample_sum` and
`get_sample_count` in a non-atomic fashion. This may cause unexpected
calculation result.
This PR calls `Histogram::metric` which uses a lock inside to guarantee
consistency. And the PR also adds protective checks to avoid dividing by zero.
```
Tests 
It's hard for a unit test to reproduce inconsistent state of histograms.
```release-note
None.
```

read_pool: avoid get inconsistent sample sum and count from histogram

---

Cargo.lock
Cargo.toml
cmd/tikv-server/Cargo.toml
components/engine_rocks/Cargo.toml
components/engine_rocks/src/engine.rs
components/engine_traits/Cargo.toml
components/engine_traits/src/tablet.rs
src/server/status_server/mod.rs
src/storage/txn/flow_controller/singleton_flow_controller.rs
src/storage/txn/flow_controller/tablet_flow_controller.rs

Issue Number: Close #14196
```commit-message
Also add a tool to trace tablet leak.
```
Tests 
- Unit test
```
env ENABLE_FEATURES=trace-tablet-lifetime make release
curl tikv_host:status_port/region/id?trace-tablet=1
```
```release-note
None
```

*: fix tablet leak in flow control

---

Cargo.lock
Cargo.toml

bump version to 6.7.0-alpha
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to v6.7.0-alpha

---

components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/tests/integrations/test_conf_change.rs

Issue Number: Close #14211 
```commit-message
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: fix wrong peer cache

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 6.5.1

---

components/engine_rocks/src/engine.rs
components/raftstore-v2/src/operation/bucket.rs
components/raftstore-v2/tests/integrations/test_pd_heartbeat.rs
components/raftstore/src/coprocessor/config.rs
components/raftstore/src/coprocessor/split_check/half.rs
components/raftstore/src/coprocessor/split_check/keys.rs
components/raftstore/src/coprocessor/split_check/mod.rs
components/raftstore/src/coprocessor/split_check/size.rs
components/raftstore/src/store/config.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/split_check.rs
components/server/src/server.rs
components/server/src/server2.rs
components/test_raftstore-v2/src/node.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/server.rs
src/config/mod.rs
tests/failpoints/cases/test_stats.rs
tests/integrations/config/mod.rs
tests/integrations/raftstore/test_split_region.rs

```commit-message
So that it's easier to use v2.
```
Tests 
- Unit test
```release-note
None
```

*: enable bucket automatically if region size is large enough

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to v6.1.5

---

components/test_raftstore-v2/src/node.rs
components/test_raftstore-v2/src/transport_simulate.rs
tests/integrations/raftstore/test_snap.rs

```commit-message
report snapshot status after sending
```
Tests 
- Unit test
```release-note
None
```

integration test v2: report snapshot status after sending

---

components/raftstore-v2/src/operation/ready/snapshot.rs

```commit-message
update region state in apply_snapshot
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: update region state in apply_snapshot

---

components/pd_client/src/client_v2.rs

Issue Number: Close #14309
```commit-message
Version should be updated before broadcast updates, otherwise the
update will be just ignore.
```
Tests 
- Unit test
```release-note
None
```

pd_client_v2: fix version race

---

components/test_raftstore-v2/src/cluster.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore-v2/src/transport_simulate.rs
components/test_raftstore-v2/src/util.rs
components/test_raftstore/src/cluster.rs
src/server/mod.rs
src/server/raftkv2/mod.rs
tests/failpoints/cases/test_conf_change.rs
tests/failpoints/cases/test_snap.rs
tests/integrations/raftstore/test_snap.rs

```commit-message
introduce TestRaftKv2
```
This PR mainly introduces TestRaftKv2 which wraps up RaftKv2 with filters so that it can mock various network conditions.
The PR also implements some relevant methods used by some tests. 
After that, some v1's tests can be reused by v2.
Tests 
- Unit test
```release-note
None
```

integration test v2: introduce TestRaftKv2

---

Cargo.lock

Issue Number: Close #14338
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

sync raft-engine

---

components/resource_control/src/lib.rs

Issue Number: Close https://github.com/tikv/tikv/issues/14353
plan GA in 7.0
```commit-message
resource_control: enable resource control by default
```
Tests 
- Unit test
- No code
Side effects
- performance may regression, <3%
```release-note
None
```

resource_control: enable by default

---

components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/command/write/ingest.rs
components/raftstore-v2/src/operation/command/write/simple_write.rs

```commit-message
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: fix ingest codec

---

src/storage/txn/flow_controller/singleton_flow_controller.rs

Issue Number: Close #14392
```commit-message
Fix the issue that flow control may not work when pending compaction bytes is high.
If the pending compaction bytes is 0, then 0.log2() is -INF which would cause the later
average always be zero even if the pending compaction bytes is already high.
```
Tests 
- Unit test
```release-note
Fix the issue that flow control may not work when pending compaction bytes is high
```

storage: Fix flow controller pending compaction bytes always be zero

---

components/raftstore-v2/src/operation/command/admin/compact_log.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore/src/store/async_io/write.rs
components/raftstore/src/store/entry_storage.rs

Issue Number: Ref #14386
```commit-message
None
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: add some logs and fix possible race between clean and tick

---

etc/config-template.toml
src/config/mod.rs
tests/integrations/config/test-custom.toml
tests/integrations/config/test-default.toml

Issue Number: Close #14379 
```commit-message
Enable log recycling in `RaftLogEngine` by default
```
- docs-cn: https://github.com/pingcap/docs-cn/pull/13381
- docs: https://github.com/pingcap/docs/pull/12869
Tests 
- Unit test
- No code
Side effects
```release-note
Enable log recycling in `RaftLogEngine` by default.
```

engine: enable log recycling by default

---

components/raftstore-v2/src/operation/command/admin/split.rs
tests/failpoints/cases/test_split_region.rs

Issue Number: Close #14389
```commit-message
split init may be out of dated
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: split init may be out of dated when conf change ocurred

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

feat: bump version to 7.0.0

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

feat: bump version to 7.1.0-alpha

---

components/tracker/src/lib.rs

Issue Number: ref #12362
```commit-message
Fix the returned apply write wal tracking time.
```
Tests 
Side effects
```release-note
None
```

storage: fix the apply write wal tracking time

---

components/backup/src/endpoint.rs
components/backup/src/service.rs
components/backup/src/writer.rs
components/engine_traits/src/sst.rs
components/server/src/server.rs
components/server/src/server2.rs
components/test_backup/src/lib.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
components/tikv_kv/src/lib.rs
components/tikv_util/src/lib.rs
src/import/mod.rs
src/import/sst_service.rs

Issue Number: ref https://github.com/tikv/tikv/issues/12842
This PR tried to adapt backup for raft store v2 logic.
```commit-message
```
Tests 
- Unit test
Try backup manually without checksum
Try restore manually without checksum but it cost time to split region.
- No code
Side effects
```release-note
None
```

raftstore-v2: implement snapshot backup for raftstore v2

---

src/server/config.rs
tests/integrations/config/mod.rs

Issue Number: Close #14455.
```commit-message
```
Tests 
- Unit test
```release-note
None
```

config: fix alias name snap-max-write-bytes-per-sec

---

components/raftstore/src/store/async_io/write.rs

```commit-message
async io thread's write should be foreground write
```
Tests 
Side effects
```release-note
None
```

fix io breakdown for foreground write

---

components/raftstore-v2/src/operation/command/mod.rs

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore-v2: change log level

---

Cargo.lock
components/raft_log_engine/src/engine.rs
metrics/grafana/tikv_details.json

Issue Number: Close #14468 
```commit-message
Update the dependency to `raft-engine` lib, to fix the bug that the size of `prefill-for-recycle` is not adaptive to dynamic regions.
```
Tests 
- Unit test
- No code
Side effects
```release-note
None.
```

engine: update raft-engine

---

components/causal_ts/src/tso.rs
components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/worker/tablet_flush.rs
components/server/src/server.rs
components/server/src/server2.rs

```commit-message
```
Tests 
- Unit test
- No code
```release-note
None
```

raftstore-v2: thread name fix

---

components/tikv_util/src/sys/cgroup.rs

Issue Number: Close https://github.com/tikv/tikv/issues/14538
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

fix cgroup parse problem

---

components/server/src/server2.rs

Issue Number: ref #14542 
```commit-message
Disable cdc and resolved_ts as they are not fully implemented
```
Tests 
- Unit test
```release-note
None
```

server2: disable cdc and resolved_ts as they are not fully implemented

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to v6.5.2

---

components/raftstore/src/store/snap.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/14579
```commit-message
fix snap manager init
```
Tests 
- Unit test
```release-note
None
```

raftstore: fix snap manager init

---

components/cdc/src/endpoint.rs
components/cdc/tests/mod.rs
components/raftstore-v2/src/fsm/apply.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/command/write/simple_write.rs
components/raftstore-v2/src/operation/query/capture.rs
components/raftstore-v2/src/raft/apply.rs
components/raftstore-v2/src/raft/storage.rs
components/raftstore/src/coprocessor/mod.rs
components/raftstore/src/store/region_snapshot.rs
components/server/src/server.rs
components/server/src/server2.rs
src/config/mod.rs

Issue Number: ref #14542 
```commit-message
*: support observe apply in raftstore v2 
```
Tests 
- Unit test
```release-note
None
```

*: support observe apply in raftstore v2 

---

components/file_system/src/lib.rs
components/file_system/src/rate_limiter.rs
components/raft_log_engine/src/engine.rs
components/raftstore-v2/src/batch/store.rs
components/raftstore/src/store/async_io/read.rs
components/raftstore/src/store/fsm/store.rs
components/server/src/common.rs
src/storage/config.rs

Issue Number: Ref #14462
```commit-message
so background purge can be rate limited.
```
Tests 
- Unit test
```release-note
None
```

*: correct io type for raft engine write and purge

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to v7.1.0

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to v7.2.0-alpha

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 7.1.0-rc.0

---

components/raftstore/src/store/snap.rs
tests/integrations/raftstore/test_snap.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/14579
```commit-message
delete tablet snap if exists
```
Tests 
- Unit test
```release-note
None
```

raftstore: delete tablet snap if exists

---

components/cdc/src/delegate.rs
components/cdc/src/initializer.rs
components/cdc/src/lib.rs
components/cdc/src/txn_source.rs
components/raftstore-v2/src/operation/ready/apply_trace.rs

Issue Number: Close https://github.com/tikv/tikv/issues/14630
```commit-message
cdc: support filter lossy DDL changes. We don't need to send those changes downstream.
```
None
Tests 
- Unit test
Side effects
None
```release-note
None
```

cdc: support filter lossy DDL changes

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/util.rs
tests/integrations/raftstore/mod.rs
tests/integrations/raftstore/test_snap.rs
tests/integrations/raftstore/test_v1_v2_mixed.rs

Issue Number: Ref #14575 
```commit-message
Support decode simple write request in v1
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore: support decode simple write request in v1

---

components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/util.rs
tests/integrations/raftstore/mod.rs
tests/integrations/raftstore/test_snap.rs
tests/integrations/raftstore/test_v1_v2_mixed.rs

Issue Number: Ref tikv/tikv#14575
cherry pick of #14638 
```commit-message
Support decode simple write request in v1
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore: support decode simple write request in v1 (#14638)

---

components/raftstore/src/store/snap.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/14575
```commit-message
Make snapshot_meta accessible
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore: pub snapshot_meta

---

components/raftstore-v2/src/raft/peer.rs
tests/integrations/raftstore/test_split_region.rs

Issue Number: Close #14689
```commit-message
raftstore-v2: fix split removes records unexpectedly
```
Tests 
```release-note
None
```

raftstore-v2: fix split removes records unexpectedly

---

components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/src/fsm/apply.rs
components/raftstore-v2/src/operation/command/admin/split.rs
components/raftstore-v2/src/raft/apply.rs
components/raftstore-v2/src/worker/checkpoint.rs

Issue Number: Close #14711
```commit-message
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: send tablet when offload checkpoint

---

CHANGELOG.md
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/worker/pd.rs
src/storage/mvcc/txn.rs
tests/failpoints/cases/test_disk_full.rs

Issue Number: ref #5456.
```commit-message
Fix some typos.
```
Tests 
- Unit test
```release-note
None.
```

*: fix some typos

---

Cargo.lock

Issue Number: Close https://github.com/tikv/tikv/issues/14950
```
*: Update rust-rocksdb to fix build with clang 16
```
- No
Tests 
- No code
Side effects
- No
```release-note
None
```

*: Update rust-rocksdb to fix build with clang 16

---

src/import/duplicate_detect.rs

Issue Number: Close #14961
```commit-message
```
Tests 
- Unit test
Side effects
```release-note
None
```

sst_importer: duplicate detection skip rest KV when meet delete

---

Cargo.lock

Update raft-engine to fix data loss issue #14743
Issue Number: Close #14743
```commit-message
Update raft-engine to fix data loss issue #14743
```
See details: https://github.com/tikv/raft-engine/issues/315
Tests 
```release-note
Fix an issue that may cause TiKV metadata data loss.
```

*: update raft-engine

---

components/tikv_util/src/config.rs
components/tikv_util/src/sys/cpu_time.rs

Issue Number: Close #15015 
```commit-message
Building tikv_util is now possible on FreeBSD
```
Tests 
```release-note
None
```

tikv_util: Allow building on FreeBSD

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 6.1.7

---

components/raftstore-v2/src/worker/pd/misc.rs
components/raftstore/src/store/worker/pd.rs

Issue Number: Close #15041
```commit-message
```
```release-note
None
```

pd: reduce frequent redundant log output

---

components/resolved_ts/src/scanner.rs

Issue Number: Close #15112
```commit-message
Make the scan task retry wait time exponential, so that less logs will be produced.
```
Tests 
- Unit test
Side effects
N/A
```release-note
None
```

cdc: Exponentialize resolved ts scan backoff

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 7.1.1

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md

Issue Number: Close #15139
```commit-message
```
Tests 
- No code
Side effects
```release-note
None
```

fix issue template

---

components/raftstore/src/store/fsm/peer.rs

Issue Number: Close #15151
```commit-message
Set availability_context in raftstore v1
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore: set availability_context

---

components/raftstore/src/store/peer.rs

Issue Number: Ref #10483
```commit-message
Comment only change.
```
N/A
Tests 
- No code
Side effects
N/A
```release-note
None
```

unsafe recovery: Clarify the benefits of using InvokeClosureOnDrop.

---

components/cdc/src/old_value.rs
components/tikv_util/src/lru.rs

Issue Number: Close #14815
This PR tries to evict entries until the size is fit for the lru cache.
So while using size based (against to count based) cache policy, the actual size won't exceed the capacity when inserting small values and then inserting large values.
```commit-message
LRU cache now will try to make its size strictly less than the capacity.
```
Tests 
- Unit test
Side effects
- Lower cache hit rate.
```release-note
Fixed a bug that may cause TiKV use more memory than excepted when TiCDC and old value enabled.
```

util: evict until fit when inserting (#14847)

---

components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/ready/apply_trace.rs
tests/integrations/raftstore/test_bootstrap.rs

Issue Number: Close #14390
```commit-message
fix potential data loss during server close
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: fix potential data loss during server close

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/life.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/operation/unsafe_recovery/report.rs
components/raftstore-v2/src/raft/apply.rs
components/raftstore-v2/src/raft/peer.rs
components/raftstore-v2/src/worker/pd/store.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/unsafe_recovery.rs
components/raftstore/src/store/worker/pd.rs
components/test_raftstore-v2/src/cluster.rs
tests/failpoints/cases/test_unsafe_recovery.rs

Issue Number: ref #15108
```commit-message
raftstore-v2: implement unsafe recovery wait apply
raftstore: move unsafe recovery structs to mod unsafe_recovery
```
Tests 
```release-note
None
```

raftstore-v2: implement unsafe recovery wait apply

---

components/raftstore-v2/src/batch/store.rs
components/raftstore-v2/tests/integrations/cluster.rs
components/server/src/server2.rs
components/test_raftstore-v2/src/node.rs
components/test_raftstore-v2/src/server.rs
src/server/raftkv2/node.rs

Issue Number: ref #13730
This PR is an enhancement of #14103
```
enable resource control for raft-v2
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

resource_control: enable resource control for raft-v2

---

components/resolved_ts/src/advance.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/src/metrics.rs
components/resolved_ts/src/resolver.rs
metrics/grafana/tikv_details.json

Issue Number: ref #15082 
Cherry pick #15118 
```commit-message
metrics: add min_safe_ts, min_safe_ts_region and min_safe_ts_gap
```
Tests 
Side effects
```release-note
None
```

metrics: Cherry pick #15118 to release-6.5: add min_safe_ts, min_safe_ts_region and min_safe_ts_gap

---

Cargo.lock
Cargo.toml
cmd/tikv-ctl/src/cmd.rs
cmd/tikv-ctl/src/executor.rs
cmd/tikv-ctl/src/main.rs
components/raftstore/src/store/util.rs
components/resolved_ts/src/endpoint.rs
components/resolved_ts/src/resolver.rs
components/server/src/server.rs
components/test_raftstore/src/server.rs
src/server/service/debug.rs
src/server/service/mod.rs

Issue Number: ref #15082 
Cherry pick #15099 
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

ctl: add get_region_read_progress (release-6.5)

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 7.3.0

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 7.4.0-alpha

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/admin/conf_change.rs
components/raftstore-v2/src/operation/command/mod.rs
components/raftstore-v2/src/operation/ready/mod.rs
components/raftstore-v2/src/operation/unsafe_recovery/demote.rs
components/raftstore-v2/src/operation/unsafe_recovery/mod.rs
components/raftstore-v2/src/operation/unsafe_recovery/report.rs
components/raftstore-v2/src/router/imp.rs
components/raftstore-v2/src/router/message.rs
components/raftstore-v2/src/router/response_channel.rs
components/raftstore-v2/src/worker/pd/store.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/mod.rs
components/raftstore/src/store/unsafe_recovery.rs
components/raftstore/src/store/worker/pd.rs
tests/failpoints/cases/test_unsafe_recovery.rs
tests/integrations/raftstore/test_unsafe_recovery.rs

Issue Number: ref #15108 
```commit-message
* raftstore-v2: support unsafe recovery demote
* raftstore-v2: do not step force leader on confchange
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: support unsafe recovery demote

---

components/raftstore/src/coprocessor/split_observer.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/compact.rs
components/server/src/server.rs
components/test_raftstore/src/node.rs
components/test_raftstore/src/server.rs
src/server/node.rs
tests/failpoints/cases/test_split_region.rs
tests/integrations/config/dynamic/raftstore.rs
tests/integrations/raftstore/test_bootstrap.rs
tests/integrations/server/kv_service.rs

Issue Number: Close https://github.com/tikv/tikv/issues/15282
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore: trigger compaction when no valid split key can be found

---

src/server/raftkv/mod.rs
src/server/raftkv2/mod.rs

Issue Number: ref #15258
raftkv: add admin command failed log
```commit-message
```
Tests 
```release-note
None
```

raftkv: add admin command failed log

---

Cargo.toml
components/error_code/src/raftstore.rs
components/raftstore/src/errors.rs
components/raftstore/src/store/util.rs

Issue Number: Close #15288
```commit-message
Add error type for "mismatch peer id".
```
Tests 
Side effects
```release-note
None
```

add error type MismatchPeerId

---

Cargo.lock
components/engine_rocks/src/event_listener.rs
components/engine_rocks/src/misc.rs
etc/config-template.toml
src/config/mod.rs
src/server/gc_worker/gc_worker.rs
tests/failpoints/cases/test_gc_metrics.rs
tests/integrations/config/mod.rs

ref tikv/tikv#14873
Expose the configuration settings on CF.ttl and CF.periodic_compaction_seconds.
Issue Number: Ref #14873
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
If this PR will be picked to release …
```

[7.1-cherry-pick]rocksdb: support setting `ttl` and `periodic_compaction_seconds`.

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 6.5.4

---

etc/config-template.toml
src/config/mod.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Issue Number: Close #15355 
```commit-message
Disable `periodic-compaction` and `ttl` features as default.
```
Tests 
- Unit test
- No code
Side effects
```release-note
Disable `periodic-compaction` and `ttl` features as default.
```

compaction: disable periodic-compaction and ttl as default.

---

components/cloud/azure/src/azblob.rs

Issue Number: Close #15384 
output the debug information of the error to show the details
```commit-message
```
v6.5, v.7.1
Tests 
see the issue
```release-note
None
```

br: show the details of the error occurred when get the azure ad token

---

Cargo.lock
src/storage/mod.rs
tests/Cargo.toml
tests/failpoints/cases/test_storage.rs

close tikv/tikv#15306
add deadline check in get and batch_get request handler.
Issue Number: Close #15306
What's Changed: cherry-pick 15307
Tests 
- Unit test
Side effects
```release-note
None.
```

storage: add deadline check in get and batch_get request handler (#15307)

---

Cargo.lock
components/batch-system/Cargo.toml
components/batch-system/src/router.rs
components/batch-system/tests/cases/router.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/store.rs
components/server/src/memory.rs
components/tikv_util/src/mpsc/mod.rs

Cherry-pick:
- https://github.com/tikv/tikv/pull/15431
- https://github.com/tikv/tikv/pull/15372
- https://github.com/tikv/tikv/pull/15353
```commit-message
Cherry pick #15421, #15372 and #15353 to 6.1
```
Tests 
- Unit test
```release-note
None
```

Cherry pick #15421, #15372 and #15353 to 6.5.1

---

components/raftstore/src/store/fsm/apply.rs
src/coprocessor/metrics.rs
src/coprocessor/tracker.rs

Issue Number: Close #15405
```commit-message
```
Tests 
- Unit test
Side effects
```release-note
None
```

coprocessor: skip transient read request

---

Cargo.lock

Issue Number: Close https://github.com/tikv/tikv/issues/15454
What's Changed: To include https://github.com/tikv/titan/pull/284
```commit-message
Update titan to fix possible delete blob file twice error
```
Tests 
- No code
```release-note
None
```

Update titan to fix possible delete blob file twice error

---

src/storage/mod.rs

Issue Number: Close #15490
```commit-message
avoid duplicated Instant:now
```
Tests 
- Unit test
- No code
```release-note
None
```

storage: avoid duplicated Instant:now

---

components/server/src/server.rs
components/server/src/server2.rs

Issue Number: ref #8235
As title, so that we can see gRPC memory usage in tikv dashboard.
```commit-message
```
Tests 
Just run TiKV cluster.
```release-note
None
```

server: track grpc threads memory throughput

---

components/cdc/src/endpoint.rs
components/cdc/src/service.rs

Issue Number: Close #15487 
When deregister regions from TiKV, emit a "region not found" event, which can make clients more robust.
```commit-message
```
Tests 
- Unit test
Side effects
```release-note
None
```

cdc: enhance deregister protocol

---

src/coprocessor/tracker.rs

Issue Number: Close #15513
```commit-message
coprocessor: add SQL statement tracing in tikv slow log
```
new entries `connection_id` and `session_alias` will be added to slow log:
```
[2023/09/05 15:09:24.768 +08:00] [INFO] [tracker.rs:269] [slow-query] [perf_stats.internal_delete_skipped_count=0] [perf_stats.internal_key_skipped_count=9184] [perf_stats.block_read_byte=28635] [perf_stats.block_read_count=39] [perf_stats.block_cache_hit_count=5] [scan.range.first="Some(start: 7480000000000000F35F728000000000002E4000 end: 7480000000000000F35F7280000000000C4979)"] [scan.ranges=1] [scan.total=9185] [scan.processed_size=1175552] [scan.processed=9184] [scan.is_desc=false] [tag=select] [table_id=243] [txn_start_ts=444045135633973251] [total_suspend_time=2.459µs] [total_process_time=3.577208ms] …
```

coprocessor: add SQL statement tracing in tikv slow log

---

components/engine_rocks/src/rocks_metrics.rs
components/engine_rocks/src/rocks_metrics_defs.rs
metrics/grafana/tikv_details.json

Issue Number: Close #15546
engine_rocks: trace all memtables including pinned
```commit-message
```
Tests 
```release-note
None
```

engine_rocks: trace all memtables including pinned

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/query/local.rs
components/tracker/src/slab.rs
tests/failpoints/cases/test_read_execution_tracker.rs

Issue Number: Ref #15409
```commit-message
supplement read track metrics
```
Tests 
- Unit test
```release-note
None
```

raftstore-v2: supplement read track metrics

---

tests/failpoints/cases/test_gc_worker.rs
tests/failpoints/cases/test_storage.rs
tests/integrations/server/gc_worker.rs

Issue Number: ref #15409 
```commit-message
Supply extra test cases, including integration tests and unit tests for raftstore-v2 on `gc`.
```
Tests 
- Unit test
- No code
Side effects
```release-note
None.
```

[Dynamic Region] Supply extra test cases for `gc`.

---

Cargo.lock

Issue Number: Close #15579
```commit-message
update cargo.lock
```
```release-note
None
```

*: update cargo.lock

---

components/tidb_query_datatype/src/def/field_type.rs

Issue Number: Close #15571
1. The collation `utf8mb4_0900_bin` is excluded from `need_restored_data`.
2. Fix the `is_bin_collation` for `utf8mb4_0900_bin`.
Ref https://github.com/pingcap/tidb/pull/46781
Tests 
- No code
This bug doesn't have a release note, because it's a new feature in https://github.com/tikv/tikv/pull/15398 and haven't been released

tidb_query_datatype,collation: remove utf8mb4_0900_bin from need_restored_data

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 6.5.5

---

Cargo.lock
Cargo.toml
components/tikv_util/Cargo.toml

Issue Number: Ref #15621
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

raftstore: upgrade tokio timer to fix insecure issues.

---

Cargo.lock

Issue Number: Ref #15621
```commit-message
```
Tests 
- Unit test
- No code
```release-note
None
```

upgrade lz4-sys to 1.9.4 to tackle security issue

---

tests/Cargo.toml
tests/integrations/raftstore/test_stats.rs

Issue Number: Close https://github.com/tikv/tikv/issues/15656
```commit-message
tests: fix unstable test_query_stats test
```
Tests 
- Unit test
```release-note
None
```

tests: fix unstable test_query_stats test

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 7.4.0

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 7.5.0-alpha

---

components/raftstore-v2/src/fsm/peer.rs
components/raftstore-v2/src/operation/command/write/mod.rs
components/raftstore-v2/src/operation/txn_ext.rs
components/raftstore-v2/src/router/message.rs
components/test_raftstore-v2/src/cluster.rs
src/server/raftkv2/mod.rs
tests/failpoints/cases/test_storage.rs

Issue Number: ref #15409 
```commit-message
This pr contains several necessary uts and some enhancements for `raftstore-v2`:
- Supply extra test cases, including integration tests and unit tests for raftstore-v2 on `storage`.
- Transplant the necessary options on setting `deadline` for `SimpleWrite` in raftstore-v2.
```
Tests 
- Unit test
- No code
Side effects
```release-note
None.
```

[Dynamic Regions] Supplement extra uts for test_storage.rs.

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 7.5.0

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 7.1.2

---

Makefile
components/raftstore-v2/src/operation/command/write/ingest.rs
components/raftstore/src/store/fsm/store.rs
components/raftstore/src/store/msg.rs
components/raftstore/src/store/worker/cleanup.rs
components/raftstore/src/store/worker/cleanup_sst.rs
components/server/src/server.rs
components/server/src/server2.rs
components/sst_importer/src/import_file.rs
components/sst_importer/src/lib.rs
components/sst_importer/src/sst_importer.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
src/import/sst_service.rs

Issue Number: close https://github.com/tikv/tikv/issues/15791
Reverts tikv/tikv#15013
lightning integration tests failed because of this. See the CI of https://github.com/pingcap/tidb/pull/47712
```release-note
None
```

Revert "import: write RPC will check region epoch before continue"

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 7.6.0-alpha

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/peer.rs
components/test_pd_client/src/pd.rs
tests/failpoints/cases/test_unsafe_recovery.rs
tests/integrations/raftstore/test_replication_mode.rs
tests/integrations/raftstore/test_unsafe_recovery.rs

Cherry-pick:
- https://github.com/tikv/tikv/pull/15594
- https://github.com/tikv/tikv/pull/15635
- https://github.com/tikv/tikv/pull/15785
- https://github.com/tikv/tikv/pull/15830
```commit-message
```
Tests 
- Unit test
```release-note
None
```

Cherry-pick online recovery and dr auto sync releated related PRs

---

metrics/alertmanager/tikv.rules.yml

Issue Number: Close #15796
Tackle the false-postive case by extending the checking interval of the `Gc can not work` alerting.
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

alert: tackle the false-postive case where alerting `gc not work`.

---

components/resolved_ts/src/advance.rs
components/resolved_ts/src/endpoint.rs

Issue Number: ref #15835
cherry-pick #15836
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

*: fix issue of modify resolved-ts.advance-ts-interval from 5s to 2s is not work

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/initializer.rs
components/cdc/src/observer.rs
components/cdc/tests/failpoints/test_endpoint.rs
components/cdc/tests/failpoints/test_register.rs
src/config.rs
tests/integrations/config/mod.rs
tests/integrations/config/test-custom.toml

Cherry picks #15849, #15865 and #15947.

cdc: limit incremental scan fetching speed

---

components/engine_rocks/src/config.rs
src/config/mod.rs

Issue Number: Close #15987, Close #15978
```commit-message
Fix titan config blob-run-mode's from<ConfigValue> implementation.  
```
Tests 
- Unit test
```release-note
None
```

config: Fix titan blob-run-mode setting

---

components/tidb_query_expr/src/impl_string.rs
components/tidb_query_expr/src/lib.rs

Issue Number: Close https://github.com/tikv/tikv/issues/16009
```commit-message
Copr: do not change expression type for `Lower`
```
- No
Tests 
- No code
Side effects
- No
```release-note
None
```

Copr: do not change expression type for `Lower`

---

src/read_pool.rs

Issue Number: ref #16026
```
Decrease pending tasks counter when spawn return "Full" error
```
Tests 
- Unit test
Side effects
```release-note
Fix the bug that read-pool running tasks count maybe incorrect when the queue is near full
```

readpool: fix pending tasks counter

---

components/resolved_ts/src/advance.rs
components/resolved_ts/tests/integrations/mod.rs

Issue Number: ref #15567
What's Changed: pick #15567 to the standalone branch
```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
None
```

resolved-ts: speed up advancing when stores get partitioned (#15567)

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
- Unit test
- No code
Side effects
```release-note
```

chore: bump version to 6.5.6

---

Cargo.lock
Cargo.toml

Issue Number: Close #16091
What's Changed: include https://github.com/tikv/rust-rocksdb/pull/776
```commit-message
update titan to fix compaction filter
```
Tests 
- Unit test
```release-note
None
```

titan: update titan to fix compaction filter

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
Set shared crosshair tooltip for tikv_detail dashboard
```
Tests 
```release-note
None
```

metrics/grafana: set shared crosshair tooltip

---

Cargo.toml
components/tidb_query_datatype/src/codec/collation/encoding/gbk.rs
components/tidb_query_datatype/src/codec/collation/encoding/mod.rs
components/tidb_query_datatype/src/codec/collation/encoding/unicode_letter.rs
components/tidb_query_datatype/src/codec/collation/mod.rs
components/tidb_query_expr/src/impl_string.rs

Issue Number: Close https://github.com/tikv/tikv/issues/16159
```commit-message
rewrite `Upper` and `Lower` functions by porting the implementation from Go library
```
Tests 
Side effects
```release-note
None
```

coprocessor: rewrite `Upper` and `Lower` functions by porting the implementation from Go library

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
Side effects
```release-note
```

chore: bump version to 7.1.3

---

Cargo.lock
Cargo.toml

Issue Number: Close #16097
```commit-message
update cloud sdk
```
Tests 
Side effects
```release-note
None
```

cloud: update gcs sdk to support fips 140

---

Dockerfile.FIPS

Issue Number: ref #15943
Install protoc for release-6.5 FIPS docker image.
Tests 
`ENABLE_FIPS=1 make docker`
```release-note
None
```

Dockerfile: fix release-6.5 FIPS build

---

Dockerfile.FIPS

Issue Number: ref https://github.com/tikv/tikv/issues/15943
```commit-message
Install protoc for release-6.5 FIPS docker image for multi-arch build
```
Tests 
ENABLE_FIPS=1 make docker
```release-note
None
```

Dockerfile: support multi-arch build

---

Cargo.lock
Cargo.toml
src/lib.rs

Issue Number: Close #16200
set version to 6.5.6-fips
```commit-message
```
Tests 
```release-note
None
```

*: set version to 6.5.6-fips

---

metrics/grafana/common.py
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256
src/server/status_server/metrics.rs
src/server/status_server/mod.rs

Issue Number: Close #16197
```commit-message
This commit add histograms for status server APIs, so that we can inspect
the duration for each API request.
It helps us to identify any correlations between specific API requests and
potential incidents.
```
Tests 
```release-note
None
```

server: add metrics for status server API

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256
scripts/gen-tikv-details-dashboard
src/read_pool.rs

Issue Number: Close https://github.com/tikv/tikv/issues/16248
```commit-message
readpool: add priority label for running tasks
```
Tests 
```release-note
none
```

readpool: add priority label for running tasks metrics

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
Side effects
```release-note
```

chore: bump version to 6.5.7

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

Issue Number: ref #16265
```commit-message
Fix typo errors in the Raft IO panel.
```
Tests 
Side effects
```release-note
None
```

metrics: fix typo errors in the Raft IO panel.

---

components/cdc/src/channel.rs
components/cdc/src/initializer.rs
components/cdc/src/metrics.rs

Issue Number: Close #16282
```commit-message
```
Tests 
Side effects
```release-note
```

cdc: add more metrics about output events queue time (#16281)

---

components/raftstore/src/store/fsm/apply.rs

Issue Number: ref https://github.com/tikv/tikv/issues/16267
```commit-message
raftstore: real batch ingest sst files in different region
```
Tests 
Side effects
```release-note
raftstore: batch apply ingest sst files with different regions.
```

raftstore: real batch ingest sst files in different region

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
Side effects
```release-note
```

chore: bump version to 7.6.0

---

src/storage/mvcc/reader/reader.rs

Issue Number: Ref #16340 
Cherry-pick https://github.com/tikv/tikv/pull/16342 to the release-7.6 branch.
```commit-message
Try to fix the possible deadlock caused by scan lock.
```
Tests 
- See the original PR.
Side effects
```release-note
None
```

txn: try to fix the deadlock caused by scan lock(#16342)

---

Makefile
components/cloud/aws/src/s3.rs
components/raftstore/src/store/fsm/apply.rs
components/raftstore/src/store/fsm/peer.rs
deny.toml
scripts/check-log-style
scripts/deny

Issue Number: ref #16328
```commit-message
To comply with FIPS 140-2, we should not use crypto algorithms implemented
in rust, instead we should delegate these operation to OpenSSL, including
symmetric encryption, asymmetric encryption, hash functions,
key establishment, digital signatures and random number generators.
```
* Ban unwanted crypto crates
* Suppress advisories, licenses and sources warnings
* Check cargo deny on make clippy
Tests 
```release-note
None
```

*: ban unwanted crypto crates

---

Cargo.lock
Cargo.toml

Issue Number: Close https://github.com/tikv/tikv/issues/16365
```commit-message
```
Tests 
Side effects
```release-note
None
```

chore: bump version to v8.0.0-alpha

---

Cargo.lock
Cargo.toml
clippy.toml
cmd/tikv-ctl/Cargo.toml
cmd/tikv-server/Cargo.toml
components/backup-stream/Cargo.toml
components/backup-stream/src/router.rs
components/backup-stream/src/utils.rs
components/backup-stream/tests/suite.rs
components/engine_rocks/Cargo.toml
components/online_config/Cargo.toml
components/raft_log_engine/Cargo.toml
components/raftstore-v2/Cargo.toml
components/raftstore/Cargo.toml
components/server/Cargo.toml
components/snap_recovery/Cargo.toml
components/test_util/Cargo.toml
components/test_util/src/logging.rs
components/tidb_query_common/Cargo.toml
components/tidb_query_datatype/Cargo.toml
components/tidb_query_expr/Cargo.toml
components/tikv_util/Cargo.toml
deny.toml
tests/Cargo.toml

Issue Number: ref #16328 
```commit-message
* Fix RUSTSEC-2023-0044 and RUSTSEC-2023-0072 by upgrading rust-openssl.
* Fix RUSTSEC-2023-0034 by upgrade h2.
* Fix RUSTSEC-2023-0001 by upgrading tokio.
* Fix RUSTSEC-2020-0159 by upgrading chrono.
* Fix RUSTSEC-2023-0018 by removing `remove_dir_all` in non-test code.
* Mitigate RUSTSEC-2020-0071 by banning unsound time 0.1 APIs.
```
Tests 
```release-note
None
```

*: deny vulnerable crates

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/peer.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_controller.rs
tests/integrations/raftstore/test_split_region.rs

This reverts commit defc9338fd9e0539db86e0998e4e889334cc94d4.
Issue Number: Ref https://github.com/tikv/tikv/issues/16314
```commit-message
```
Tests 
Side effects
```release-note
None
```

[Pick-to-7.6]Revert "raftstore: fix load base split cannot works in pure follower read scenario 

---

Cargo.lock
Cargo.toml
cmd/tikv-ctl/Cargo.toml
components/raft_log_engine/Cargo.toml

This is a manual cherry-pick of https://github.com/tikv/tikv/pull/16294
Issue Number: close https://github.com/tikv/tikv/issues/16324 ref https://github.com/tikv/raft-engine/pull/346
```commit-message
Update `raft_log_engine` lib to the latest version, to fix some issues, including:
- rewrite: optimize the interval of sync when rewriting memtables #347.
```
Tests 
Side effects
```release-note
None.
```

[cherry-pick-7.1] raft_log_engine: update to latest version. (#16294)

---

Cargo.lock
cmd/tikv-ctl/Cargo.toml
components/raft_log_engine/Cargo.toml

This is a manual cherry-pick of https://github.com/tikv/tikv/pull/16294
Issue Number: close https://github.com/tikv/tikv/issues/16324 ref https://github.com/tikv/raft-engine/pull/346
```commit-message
Update `raft_log_engine` lib to the latest version, to fix some issues, including:
- rewrite: optimize the interval of sync when rewriting memtables #347.
```
Tests 
Side effects
```release-note
None
```

[cherry-pick-6.5] raft_log_engine: update to latest version. (#16294)

---

components/test_coprocessor/src/store.rs

Issue Number: Ref #16371 
```commit-message
Fix lint
```
Tests 
Side effects
```release-note
None
```

test: fix lint

---

Cargo.lock

Issue Number: Close #16405 
```commit-message
Fix h2 vulnerability caught by `make clippy`.
```
Tests 
Side effects
```release-note
None
```

Cargo.toml: fix h2 vulnerability

---

scripts/deny

Issue Number: ref #16328 
scripts: update RustSec advisory db before checking cargo deny
Tests 
```release-note
None
```

scripts: update RustSec advisory db before checking cargo deny

---

components/tikv_util/src/logger/mod.rs

Issue Number: Close #16410
```commit-message
```
Tests 
```release-note
None
```

logger: fix missing log fields

---

src/storage/config.rs
src/storage/txn/commands/acquire_pessimistic_lock.rs
src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs
src/storage/txn/commands/atomic_store.rs
src/storage/txn/commands/check_secondary_locks.rs
src/storage/txn/commands/check_txn_status.rs
src/storage/txn/commands/cleanup.rs
src/storage/txn/commands/commit.rs
src/storage/txn/commands/compare_and_swap.rs
src/storage/txn/commands/flashback_to_version.rs
src/storage/txn/commands/flashback_to_version_read_phase.rs
src/storage/txn/commands/macros.rs
src/storage/txn/commands/mod.rs
src/storage/txn/commands/mvcc_by_key.rs
src/storage/txn/commands/mvcc_by_start_ts.rs
src/storage/txn/commands/pause.rs
src/storage/txn/commands/pessimistic_rollback.rs
src/storage/txn/commands/pessimistic_rollback_read_phase.rs
src/storage/txn/commands/resolve_lock.rs
src/storage/txn/commands/resolve_lock_lite.rs
src/storage/txn/commands/resolve_lock_readphase.rs
src/storage/txn/commands/rollback.rs
src/storage/txn/commands/txn_heart_beat.rs
src/storage/txn/mod.rs
src/storage/txn/scheduler.rs
src/storage/txn/task.rs

Issue Number: ref #16234 
This is a refactor PR, extracted from #16437.
```commit-message
* txn: refactor task into a module
* storage: refactor commands marco
```
Tests 
- Unit test
```release-note
None
```

storage: refactor command marco and task

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
Side effects
```release-note
```

chore: bump version to v6.5.8

---

Cargo.lock

Issue Number: Close #16445
Cargo: fix cargo vendor by upgrading encoding_rs
Tests 
`cargo vendor`
```release-note
None
```

Cargo: fix cargo vendor by upgrading encoding_rs

---

components/raftstore/src/store/util.rs

Issue Number: Ref #16465
```commit-message
Improve readability
```
https://github.com/tikv/tikv/pull/16467
Tests 
Side effects
N/A
```release-note
None
```

raftstore: Improve readability

---

Cargo.lock
components/engine_traits/src/cf_defs.rs
components/hybrid_engine/src/misc.rs
components/hybrid_engine/src/write_batch.rs
components/region_cache_memory_engine/Cargo.toml
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/range_manager.rs
components/server/src/common.rs
components/test_raftstore/src/cluster.rs
tests/integrations/mod.rs
tests/integrations/range_cache_engine.rs

```commit-message
make integration test of in-memory engine work
```
This PR make integration test of HybridEngine with RocksDB and CacheRangeMemoryEngine work. So that we can test it end to end.
This PR also gives a basic example: `test_basic_put_get`.
Tests 
Side effects
```release-note
None
```

In-memory Engine: make integration test work

---

components/raftstore/src/errors.rs
components/tikv_util/src/deadline.rs
src/coprocessor/endpoint.rs
src/storage/errors.rs
tests/failpoints/cases/test_coprocessor.rs

Cherry-pick #16155
Issue Number: Close #16154
```commit-message
```
Tests 
Side effects
```release-note
None.
```

*: uniform deadline exceeded error in cop response (#16155)

---

Cargo.toml
components/causal_ts/Cargo.toml
components/raftstore/Cargo.toml
components/resource_control/Cargo.toml
components/tikv_kv/Cargo.toml

Issue Number: Close #16501
Ref: https://github.com/rust-lang/cargo/issues/6915.
This pr is used to format relevant `cargo.toml` files and tidy the
test crates in the `[dependencies]` section, by moving them to
`[dev-dependencies]`.
```commit-message
By introducing this pr, the unnecessary compilation on test crates when
building the release output can be ignored.
```
Tests 
Side effects
```release-note
None.
```

*: tidy the dependencies on test crates.

---

Cargo.lock
Cargo.toml

```commit-message
bump version to v7.5.1
```
Tests 
Side effects
```release-note
```

chore: bump version to v7.5.1

---

Cargo.lock

Issue Number: Ref #15990
```commit-message
update skiplist-rs to make make dist_release compile fail
```
Tests 
Side effects
```release-note
None
```

*: fix make dist_release compile fail

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
Side effects
```release-note
```

chore: bump version to v7.1.4

---

src/import/ingest.rs
src/import/mod.rs
src/import/sst_service.rs
tests/failpoints/cases/test_import_service.rs

Issue Number: ref #16533
Move ingest and its checks to the ingest mod.
This is a prerequisite change of implementation sst lease check.
Tests 
- Unit test
```release-note
None
```

import: move ingest and its checks to the ingest mod

---

Cargo.lock
src/server/server.rs
src/server/service/kv.rs
tests/integrations/server/kv_service.rs

Issue Number: Ref #16545 
```commit-message
Add cluster id check for unary request.
```
Tests 
Side effects
```release-note
None
```

server: add cluster id check for unary request

---

Cargo.toml
Makefile
cmd/tikv-ctl/Cargo.toml
cmd/tikv-server/Cargo.toml
components/encryption/export/Cargo.toml
components/encryption/export/examples/ecli.rs
components/encryption/export/src/lib.rs
components/server/Cargo.toml
components/test_raftstore-v2/Cargo.toml
components/test_raftstore/Cargo.toml
components/test_util/Cargo.toml

```commit-message
Remove unnecessary "cloud-aws", "cloud-gcp", and "cloud-azure"
features that are always enabled in the build. No build disables
them, rendering them as useless features.
```
Tests 
- No code
```release-note
None
```

*: remove cloud aws gcp azure features

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
Side effects
```release-note
```

chore: bump version to v8.0.0

---

components/engine_rocks/src/engine.rs

Issue Number: Close #16681
```commit-message
Limit proptest test count
```
Tests 
```release-note
None
```

limit proptest test count

---

Cargo.lock
Cargo.toml

Issue Number: Close https://github.com/tikv/tikv/issues/16730
```commit-message
```
Tests 
Side effects
```release-note
None
```

chore: bump nightly version to 8.1.0-alpha

---

Cargo.lock
Cargo.toml

```commit-message
```
Tests 
Side effects
```release-note
None
```

chore: bump patch version to v6.5.9

---

components/engine_test/src/lib.rs

Issue Number: Close #16759
Note: it does not fix the broken feature propagation but workarounds compilation failure.
```commit-message
Fix compilation failure in cargo test with error message "cannot find type
KvTestEngine in this scope". This is resolved by activating
"test-engine-raft-raft-engine" and "test-engine-kv-rocksdb" features when
no features are explicitly specified.
```
Tests 
- Unit test
```release-note
None
```

engine_test: fix cannot find types error in cargo test

---

components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/metrics.rs
components/raftstore/src/store/peer.rs
components/region_cache_memory_engine/src/range_manager.rs
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256
tests/integrations/raftstore/test_merge.rs

Issue Number: Close #16820, ref #16717
```commit-message
- Change `RAFT_DISABLE_UNPERSISTED_APPLY_GAUGE` to `RAFT_ENABLE_UNPERSISTED_APPLY_GAUGE` because it's hard to calculate the previous correctly.
- Add two new grafana panels for "Apply unpersisted raft logs"
```
New panels snapshot:
Tests 
Side effects
```release-note
None
```

add grafana panel for applying unpersisted log

---

components/engine_traits/src/range_cache_engine.rs
components/region_cache_memory_engine/src/background.rs
components/region_cache_memory_engine/src/metrics.rs
components/region_cache_memory_engine/src/write_batch.rs
components/server/src/server.rs
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
add metrics for gc duration, range load duration, and write duration
```
Tests 
Side effects
```release-note
None
```

In-memory engine: add metrics for gc duration, range load duration, and write duration

---

components/tidb_query_datatype/src/codec/mysql/json/json_merge.rs
components/tidb_query_expr/src/impl_json.rs
components/tidb_query_expr/src/lib.rs

Issue Number: Close #16770
```commit-message
```
Tests 
Side effects
```release-note
support json_merge_patch pushdown to tikv
```

expr: Support json_merge_patch pushdown

---

Cargo.lock
Cargo.toml

Issue Number: ref https://github.com/tikv/tikv/issues/16890
```commit-message
```
Tests 
Side effects
```release-note
None
```

chore: bump nightly version to 8.2.0-alpha

---

deny.toml

Issue Number: Close https://github.com/tikv/tikv/issues/16797
- Correct hamc to [hmac](https://docs.rs/hmac/latest/hmac/).
Tests 
Side effects
- None
```release-note
None
```

cargo deny: fix hmac

---

README.md

Issue Number: Close https://github.com/tikv/tikv/issues/16884 
- Update the binary version in README.md example.
```commit-message
```
Tests 
Side effects
```release-note
None
```

readme: update exmaple binary version

---

src/coprocessor/statistics/fmsketch.rs

Issue Number: Ref https://github.com/tikv/tikv/issues/16463
```commit-message
Add more comments for FmSketch.
```
Tests 
Side effects
```release-note
None
```

statistics: add comments for FmSketch

---

Cargo.lock
components/tidb_query_expr/Cargo.toml
components/tidb_query_expr/src/impl_cast.rs

Reverts tikv/tikv#17003
What is changed and how it works?
Issue Number: Close #16974
```release-note
None
```

expression: revert tikv#17003 (release-8.1)

---

components/backup-stream/src/subscription_manager.rs

Issue Number: Ref #16554
This PR partially fix the problem of #16554 by increasing the retry number of getting initial snapshot to the same as `start_observe`.
This fix is special for release 7.5 because we may not pick #15541 to 7.5.x (because the change is somehow huge and not stable enough.)
```commit-message
```
Tests 
```release-note
Now, log backup can tolerance longer merge.
```

log_backup: make the retry rule unify with master (#16608)

---

src/coprocessor/statistics/fmsketch.rs

Issue Number: Close None
ref https://github.com/pingcap/tidb/pull/53601
I have made the necessary corrections to the comments for FMSketch. Although we refer to it as FMSketch, it is actually a variant of FMSketch. The concept is quite similar, but the implementation differs significantly. Therefore, we need to update the comment to avoid confusion.
Some more links:
1. [dsf.berkeley.edu/cs286/papers/synopses-fntdb2012.pdf](https://dsf.berkeley.edu/cs286/papers/synopses-fntdb2012.pdf) (chapter 5.4.3)
2. [users.cs.utah.edu/~lifeifei/cs6931/lecture5](https://users.cs.utah.edu/~lifeifei/cs6931/lecture5) (page 3)
3. [vldb.org/conf/2001/P541.pdf](https://www.vldb.org/conf/2001/P541.pdf) (section 3.2)
```commit-message
Update comments for FMSketch
```
Tests 
Side effects …

statistics: update comments for FMSketch

---

OWNERS_ALIASES
components/batch-system/src/OWNERS
components/cdc/src/OWNERS
components/encryption/src/OWNERS
components/pd_client/src/OWNERS
components/raftstore/src/coprocessor/OWNERS
components/raftstore/src/store/worker/OWNERS
components/sst_importer/src/OWNERS
etc/OWNERS
src/config/OWNERS
src/coprocessor_v2/OWNERS
src/server/OWNERS
src/server/gc_worker/OWNERS
src/server/lock_manager/OWNERS
src/storage/OWNERS
tests/integrations/config/OWNERS

Issue Number: Close #17004
```commit-message
```
Tests 
Side effects
- None
```release-note
None
```

chore: add prow OWNERS files for critial configuration files

---

Cargo.lock
components/hybrid_engine/Cargo.toml
components/hybrid_engine/src/util.rs
components/hybrid_engine/tests/failpoints/mod.rs
components/hybrid_engine/tests/failpoints/test_write_batch.rs
components/region_cache_memory_engine/src/engine.rs
components/region_cache_memory_engine/src/lib.rs
components/region_cache_memory_engine/src/write_batch.rs

Issue Number: Close #17114 Ref #16141
```commit-message
sequence number should be increased for each key
```
Tests 
Side effects
```release-note
None
```

In-memory Engine: sequence number should be increased for each key

---

components/backup-stream/src/endpoint.rs
components/backup-stream/src/subscription_manager.rs
components/backup-stream/tests/suite.rs
components/cdc/src/endpoint.rs
components/cdc/tests/mod.rs
components/server/src/server.rs
components/server/src/server2.rs

Issue Number: Close #17107
Ref #16698
```commit-message
Fix the problem that CDC and log-backup didn't use advance-ts-interval to limit the timeout of check_leader
```
Tests 
Side effects
```release-note
Fix the problem that CDC and log-backup didn't use advance-ts-interval to limit the timeout of check_leader.
```

Fix the problem that CDC and log-backup didn't use advance-ts-interval to limit the timeout of check_leader

---

components/hybrid_engine/src/write_batch.rs
components/raftstore/src/store/worker/region.rs

```commit-message
support delete range
```
Tests 
Side effects
```release-note
None
```

In-memory engine: support delete range

---

Cargo.lock

Issue Number: ref https://github.com/tikv/tikv/issues/17178
```commit-message
Fix memory leak in crossbeam-channel's unbounded channel.
```
Tests 
- No code
```release-note
None
```

*: upgrade crossbeam-channel

---

components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/initializer.rs
components/cdc/src/service.rs

Issue Number: Close #17214
```commit-message
cdc introduce a new type named `RequesetId` to specify each request id.
```
Tests 
Side effects
```release-note
None
```

cdc: introduce `RequesetId` type to make the code more clear

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
Fix display of ingest SST and compaction size
```
Tests 
Side effects
```release-note
None
```

grafana: Fix display of ingest SST and compaction size

---

src/server/status_server/profile.rs

Issue Number: Close https://github.com/tikv/tikv/issues/17234
```commit-message
Fix cpu profiling flag may not reset when meeting errors
```
Tests 
Side effects
```release-note
Fix the issue that CPU Profiling doesn't work reporting `Already in CPU Profiling`
```

profiling: Fix cpu profiling flag may not reset when meeting errors

---

Cargo.lock
components/range_cache_memory_engine/Cargo.toml
components/range_cache_memory_engine/src/engine.rs
components/range_cache_memory_engine/src/lib.rs
components/range_cache_memory_engine/src/prop_test.rs

```commit-message
Add property test for skiplist map vs. RocksDB. This test validates
basic key-value operations including put, get, delete, scan, and
delete_range.
```
Tests 
- Unit test
```release-note
None
```

In-memory Engine: add prop test for skiplist

---

components/hybrid_engine/src/observer.rs

```commit-message
Do not evict the cache when applying a snapshot because the peer
must be in the follower role during this process. The cache is
already evicted when the leader steps down.
```
Tests 
```release-note
None
```

In-memory Engine: do not evict range on applying snapshot

---

src/import/sst_service.rs
tests/failpoints/cases/test_import_service.rs
tests/integrations/import/test_apply_log.rs

Issue Number: Close https://github.com/tikv/tikv/issues/17224
```commit-message
Add a disk usage check when execute `download` and `apply` RPC from br.
When the disk is not `Normal`, the request would be rejected.
```
Tests 
Side effects
```release-note
Add a disk usage check when execute `download` and `apply` RPC from br.
When the disk is not `Normal`, the request would be rejected.
```

br: pre-check TiKV disk space before download

---

components/cdc/src/channel.rs
components/cdc/src/delegate.rs
components/cdc/src/endpoint.rs
components/cdc/src/initializer.rs
components/cdc/src/service.rs
components/cdc/tests/failpoints/test_endpoint.rs

Issue Number: Close #17233 
```commit-message
cdc: skip incremental scaned events after region fails
```
Tests 
Side effects
```release-note
None
```

cdc: skip incremental scaned events after region fails

---

Cargo.lock
components/range_cache_memory_engine/src/background.rs
components/range_cache_memory_engine/src/range_manager.rs

Issue Number: Close https://github.com/tikv/tikv/issues/17282
```commit-message
fix gc may filter keys of onging snapshot
```
Tests 
Side effects
```release-note
None
```

In-memory engine: fix gc may filter keys of onging snapshot

---

Cargo.lock
components/range_cache_memory_engine/src/background.rs
components/range_cache_memory_engine/src/engine.rs
components/range_cache_memory_engine/src/range_manager.rs
components/range_cache_memory_engine/src/read.rs
components/range_cache_memory_engine/src/write_batch.rs
components/range_cache_memory_engine/tests/failpoints/test_memory_engine.rs

Issue Number: Close #17259
```commit-message
fix repeatable schedule delete-range for the same range
```
Tests 
Side effects
```release-note
None
```

In-memory engine: fix repeatable schedule delete-range for the same range

---

Cargo.lock
Cargo.toml

Issue Number: ref https://github.com/tikv/tikv/issues/16890
```commit-message
```
Tests 
Side effects
```release-note
None
```

chore: bump nightly version to  8.3.0-alpha

---

components/range_cache_memory_engine/src/background.rs
components/range_cache_memory_engine/src/metrics.rs
components/range_cache_memory_engine/src/range_manager.rs
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
add eviction duration metrics
```
This PR:
1. Add eviction duration metrics
2. Use a separate panel to show count for range eviction and range load
Tests 
Side effects
```release-note
None
```

In-memory engine: add eviction duration metrics

---

components/hybrid_engine/src/observer.rs
components/range_cache_memory_engine/src/background.rs
components/range_cache_memory_engine/src/config.rs
components/range_cache_memory_engine/src/engine.rs
components/range_cache_memory_engine/src/range_manager.rs
components/range_cache_memory_engine/src/range_stats.rs
components/range_cache_memory_engine/src/read.rs
components/range_cache_memory_engine/src/region_label.rs
components/range_cache_memory_engine/src/write_batch.rs

```commit-message
This commit adds the prefix "ime" to all In-Memory Engine log entries,
making it easier to identify and debug related issues.
```
Tests 
- No code
```release-note
None
```

In-memory Engine: add "ime" log prefix

---

components/encryption/src/master_key/kms.rs

Issue Number: close #17410 
```commit-message
This PR fixes a bug encountered in the GCP KMS master-key rotation
scenario. When decryption fails using the current master-key, the
`KsmBackend` is expected to return a `WrongMasterKey` error rather
than any other error type. The higher-level caller will only retry
with the previous master-key if a `WrongMasterKey` error is received.
```
Tests 
- Tested using the reproduction steps from #17410, and everything is working correctly.
Side effects
```release-note
Fix a bug that cannot rotate encryption master key when master key is stored in KMS
```

encryption: fix unexpected error code for wrong master-key(tikv#17410)

---

components/backup/src/endpoint.rs
components/pd_client/src/lib.rs
components/raftstore-v2/src/worker/pd/region.rs
components/raftstore/src/coprocessor/region_info_accessor.rs
components/raftstore/src/store/worker/pd.rs
components/raftstore/src/store/worker/split_controller.rs
components/range_cache_memory_engine/src/engine.rs
components/range_cache_memory_engine/src/lib.rs
components/range_cache_memory_engine/src/memory_controller.rs
components/server/src/server.rs
components/server/src/server2.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
src/coprocessor/metrics.rs
src/server/gc_worker/gc_worker.rs
src/storage/metrics.rs
tests/failpoints/cases/test_gc_metrics.rs
tests/integrations/raftstore/test_region_info_accessor.rs
tests/integrations/storage/test_region_info_accessor.rs

```commit-message
collect cop detail and use it to determine top regions
```
Tests 
Side effects
```release-note
None
```

In-memory engine: collect cop detail and use it to determine top regions

---

Cargo.lock

Issue Number: Close #16443 
```commit-message
Update rusoto to support IMDSv2.
```
Related rusoto PR: https://github.com/tikv/rusoto/pull/8.
Tests 
Side effects
```release-note
Update rusoto to support IMDSv2.
```

dep: Update rusoto to support IMDSv2

---

components/range_cache_memory_engine/src/background.rs
components/range_cache_memory_engine/src/region_label.rs

In-memory Engine: unify thread names
```commit-message
```
Tests 
- Unit test
```release-note
None
```

In-memory Engine: unify thread names

---

Cargo.lock
components/pd_client/src/util.rs

Issue Number: Close https://github.com/tikv/tikv/issues/17513
```commit-message
```
Tests 
```release-note
None
```

util: bump kvproto version

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
```
Tests 
- No code
```release-note
None
```

metrics: add IME thread cpu panel

---

etc/config-template.toml
src/server/lock_manager/config.rs

Issue Number: Ref #17542
```commit-message
Fix the comment of newly added config variable.
```
Tests 
Side effects
```release-note
None
```

txn: fix the config comment

---

components/range_cache_memory_engine/src/range_stats.rs

```commit-message
fix wrong set in complete checking
```
Tests 
Side effects
```release-note
None
```

In-memory engine: fix wrong set in complete checking

---

Cargo.lock

Issue Number: Close #15990 
```commit-message
Fixing yanked futures-util 0.3.15
```
Tests 
Side effects
```release-note
None
```

chore: Fix yanked futures-util 0.3.15

---

metrics/grafana/common.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

Issue Number: Close #17586
```commit-message
* Show heatmap tooltip. Cherry-picked from broxus/grafana-builder#5c9e8965
* Replace `rate` with `increase` in heatmap query expression.
Cherry-picked from https://github.com/broxus/grafana-builder/pull/1
```
These two fixes are cherry-picked from the [broxus/grafana-builder](https://github.com/broxus/grafana-builder) project, thank you @0xdeafbeef and @Rexagon!
Tests 
- Manual test
Tooltip and count are correctly displayed.
```release-note
None
```

metrics/grafana: fix two heatmap panel issues

---

src/config/mod.rs

Issue Number: Close https://github.com/tikv/tikv/issues/17627
```commit-message
```
Tests 
- Unit test
```release-note
None
```

config: disable IME when API v2 or TTL is enabled

---

components/hybrid_engine/src/engine.rs
components/in_memory_engine/src/background.rs
components/in_memory_engine/src/config.rs
components/in_memory_engine/src/engine.rs
components/in_memory_engine/src/lib.rs
components/in_memory_engine/src/memory_controller.rs
components/in_memory_engine/src/prop_test.rs
components/in_memory_engine/src/region_stats.rs
components/in_memory_engine/src/write_batch.rs
components/in_memory_engine/tests/failpoints/test_memory_engine.rs
components/server/src/common.rs
components/server/src/server.rs
components/test_raftstore/src/server.rs
src/config/mod.rs
tests/integrations/config/test_config_client.rs

```commit-message
* Fix IME online config change not taking effect.
* Rename `enabled` to `enable`.
* Rename `gc_interval` to `gc_run_interval`.
* Rename `hard_limit_threshold` to `capacity`.
* Rename `soft_limit_threshold` to `evict_threshold`.
* Rename `stop_load_limit_threshold` to `stop_load_threshold`.
```
Tests 
- Unit test
```release-note
None
```

In-memory Engine: align config names with spec

---

Cargo.lock
components/backup-stream/tests/suite.rs
components/cdc/tests/mod.rs
components/hybrid_engine/Cargo.toml
components/hybrid_engine/src/observer/load_eviction.rs
components/raftstore/src/coprocessor/dispatcher.rs
components/server/src/server.rs
components/server/src/server2.rs
components/test_backup/src/disk_snap.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
components/test_storage/src/sync_storage.rs
src/server/gc_worker/gc_worker.rs
src/server/server.rs
tests/failpoints/cases/test_gc_metrics.rs
tests/failpoints/cases/test_region_cache_engine.rs
tests/integrations/config/dynamic/gc_worker.rs

Issue Number: Close #17644 Ref #16141
```commit-message
fix unsafe-destroy-range/delete-range does not trigger eviction
```
Tests 
Side effects
```release-note
None
```

In-memory engine: fix unsafe-destroy-range/delete-range does not trigger eviction

---

Cargo.lock
Cargo.toml

Issue Number: Close #17671
```commit-message
Supply necessary dependencies on `coprocessor_plugin` crates to make the CI normal.
```
Tests 
Side effects
```release-note
None.
```

build: fix unexpected CI errors as missing necessary dependencies.

---

components/hybrid_engine/src/engine.rs
components/hybrid_engine/src/lib.rs
components/hybrid_engine/src/metrics.rs
components/hybrid_engine/src/observer/snapshot.rs
components/hybrid_engine/src/snapshot.rs
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
display region cache hit related metrics
```
This PR polishes grafana panel name by changing snapshot type * to region cache *. 
Besides rename, this PR modifies the metrics collection so that now it only count when the snapshot is acquired from coprorcessor request.
Tests 
Side effects
```release-note
None
```

In-memory engine: display region cache hit related metrics

---

components/in_memory_engine/src/metrics.rs
components/in_memory_engine/src/write_batch.rs
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
display put/delete operations per second
```
Tests 
Side effects
```release-note
None
```

In-memory engine: display put/delete operations per second

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
copy read throughput and latency panels to in-memory engine
```
Tests 
Side effects
```release-note
None
```

In-memory engine: copy read throughput and latency panels to in-memory engine

---

components/hybrid_engine/Cargo.toml
components/raftstore/src/store/fsm/peer.rs

Issue Number: Close #17707
```commit-message
fix compile fail for test
```
Tests 
Side effects
```release-note
None
```

*: fix compile fail for test

---

Cargo.lock
Cargo.toml

Issue Number: ref https://github.com/tikv/tikv/issues/16890
```commit-message
```
Tests 
Side effects
```release-note
None
```

chore: bump master version to 8.5.0-alpha

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
rearrange parts of metrics panel
```
Some panels are too compact which is read frendly. This PR rearranges it.
Before the PR:
After the PR:
Tests 
Side effects
```release-note
None
```

In-memory engine: rearrange parts of metrics panel

---

components/engine_traits/src/region_cache_engine.rs
components/in_memory_engine/src/background.rs
components/in_memory_engine/src/engine.rs
components/in_memory_engine/src/write_batch.rs

```commit-message
```
Tests 
- Unit test
```release-note
None
```

In-memory Engine: remove dead code and fix typos

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

```commit-message
Raft waterfall metrics track the duration of individual requests, all 
beginning from the same starting point (when the async write request is 
scheduled) but ending at various stages of the write process. Previous 
descriptions did not make that clear and may confuse the readers. This 
commit improves the grafana descriptions for clarity. 
```
Tests 
Side effects
```release-note
None
```

grafana: clarify raft waterfall metrics descriptions

---

components/in_memory_engine/src/write_batch.rs

Issue Number: Close #17797
```commit-message
If the last call `prepare_for_region` returns `NotInCache`,
`clear_written_regions` can be called twice in both `write_impl` and
`clear`, which will cause panic. This pr changes `clear_written_regions`
to consume `self.written_regions`to avoid this kind of duplicate clear.
```
Tests 
Side effects
```release-note
None
```

test: fix the test failure that clear_regions_in_written may be called twice

---

components/in_memory_engine/src/region_stats.rs

Issue Number: ref #16141
```commit-message
handle error when getting regions info
```
Tests 
Side effects
```release-note
None
```

In-memory engine: handle error when getting regions info

---

Cargo.lock
Cargo.toml
components/compact-log-backup/Cargo.toml

Issue Number: ref https://github.com/tikv/tikv/issues/15990, close https://github.com/rusticata/pcap-parser/issues/46.
```commit-message
upgrade pprof to 0.14 to fix https://github.com/rusticata/pcap-parser/issues/46.
```
Tests 
Side effects
```release-note
None.
```

*: upgrade pprof to 0.14 to fix https://github.com/rusticata/pcap-parser/issues/46

---

scripts/deny

Issue Number: Ref https://github.com/tikv/tikv/issues/17928, Ref https://github.com/tikv/tikv/pull/17987
Fix the `cargo deny` check error by version 0.14.3 after introducing the new license `Unicode-3.0`.
```commit-message
Fix the `cargo deny` check error by version 0.14.3 after introducing the new license `Unicode-3.0`.
```
Tests 
Side effects
```release-note
Fix the `cargo deny` check error by version 0.14.3 after introducing the new license `Unicode-3.0`.
```

clippy: fix unknown license error reported by cargo-deny@0.14.3

---

components/raftstore/src/store/metrics.rs
components/raftstore/src/store/snap.rs
components/raftstore/src/store/snap/io.rs
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

This pull request enhances metrics for the raft snapshot workflow, includes:
1.Use generate-kv, generate-sst and generate-plain metrics to measure snapshot generation speed. These metrics offer better visibility, allowing for a clearer comparison between snapshot generation throughput and send/receive throughput, making it easier to identify bottlenecks.
2.Add metrics for various snapshot tasks to the Snapshot Actions, including send, recv, recv_droppedn and others, providing better visibility for snapshot actions.
Issue Number: Ref #15990
```commit-message
This pull request refines metrics for the raft snapshot workflow, includes:
1. Use generate-kv, generate-sst and generate-plain metrics to measure snapshot generation speed. These metrics offer better visibility, …
```

raftstore: enhance raft snapshot metrics

---

components/tidb_query_expr/src/impl_math.rs
components/tidb_query_expr/src/lib.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18010
What's Changed: Follow https://dev.mysql.com/doc/refman/5.7/en/precision-math-rounding.html, let `round` function works like MySQL.
Tests 
Side effects
```release-note
fix round function works with real type to make it behave more like MySQL and TiDB.
```

tidb_query_expr: fix round function with real type

---

components/cdc/src/delegate.rs

Issue Number: Close #18016 
```commit-message
cdc: fix an consistency issue introduced by #17818
```
Tests 
Side effects
```release-note
None
```

cdc: fix an consistency issue introduced by #17818

---

src/server/gc_worker/gc_worker.rs

Issue Number: Close #18091
```commit-message
gc_worker: Do not do delete_files_in_range on lock cf which has potential risk to affect data correctness
```
Tests 
Side effects
```release-note
None
```

gc_worker: Do not do delete_files_in_range on lock cf which has potential risk to affect data correctness

---

components/server/src/server.rs
components/server/src/server2.rs
components/test_raftstore-v2/src/server.rs
components/test_raftstore/src/server.rs
src/server/metrics.rs
src/server/server.rs
src/server/service/kv.rs
src/server/service/mod.rs
tests/failpoints/cases/test_server.rs

Issue Number: Close #18113
Introduced a `RaftGrpcMessageObserver` trait, which hooks before handling message of raft append message and raft snapshot message.
```commit-message
Support customized raft message rejection logic
```
Tests 
Side effects
```release-note
None
```

Support customized raft message rejection logic

---

metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256

Currently, the "Snapshot transport speed" metric is somewhat complex, as it includes more than five observed items per TiKV instance, such as `*-generate-io`, `*-generate-kv`, etc. However, in most cases, we are only interested in two key items: `*-generate-io` and `*-recv`, since their combined throughput is limited by the I/O limiter, making them the primary indicators for diagnosing performance issues. 
This PR simplifies the metric by omitting the other observed items by default. If user want to view the other items, then can modify the query statement in Grafana.
Before this PR:
After this PR:
```commit-message
Simplify the "Snapshot Transport Speed" metric.
```
Tests 
Side effects
```release-note
none
```

chore: simplify snapshot metrics

---

components/hybrid_engine/src/metrics.rs
components/hybrid_engine/src/observer/load_eviction.rs
components/in_memory_engine/src/background.rs
components/in_memory_engine/src/engine.rs
components/in_memory_engine/src/metrics.rs
components/in_memory_engine/src/region_manager.rs
components/in_memory_engine/src/region_stats.rs
components/raftstore/src/store/config.rs
metrics/grafana/tikv_details.dashboard.py
metrics/grafana/tikv_details.json
metrics/grafana/tikv_details.json.sha256
tests/failpoints/cases/test_transfer_leader.rs

Issue Number: ref https://github.com/tikv/tikv/issues/17782
```commit-message
Reduce IME verbose logs and add metrics to export auto load/evict and
transfer leader warmup statistics. 
```
Tests 
```release-note
None
```

In-memory Engine: reduce verbose logs and add metrics

---

components/concurrency_manager/src/lib.rs

Issue Number: ref #17916 
```commit-message
```
Tests 
Side effects
```release-note
None
```

concurrency-manager: (release-8.5) do not assert in max ts checker

---

Cargo.lock
cmd/tikv-ctl/src/main.rs
components/cloud/gcp/src/gcs.rs
components/compact-log-backup/Cargo.toml
components/compact-log-backup/src/compaction/exec.rs
components/compact-log-backup/src/exec_hooks/observability.rs
components/compact-log-backup/src/test_util.rs

Issue Number: Close https://github.com/tikv/tikv/issues/18308
1.	GCS Atomic Write: Removed the content length=0 check to support atomic writes, aligning with S3 behavior.
2.     Assertion Fix: Fixed assertion failures caused by unexpected rollback transactions. see details(https://github.com/tikv/tikv/issues/18300)
3.	Duplicate File Fix: Resolved issues with duplicate output files causing compacted restore failures.
4.	Enhanced logging to reduce noise.
```commit-message
log backup compact: fix several issues during compact a log backup
```
Tests 
Side effects
```release-note
None
```

log backup: fix several issues during compact log backup. 

---

Cargo.lock
clippy.toml
components/cloud/aws/src/kms.rs
components/cloud/aws/src/s3.rs
components/cloud/aws/src/util.rs
deny.toml

This is a cherry-pick of https://github.com/tikv/tikv/pull/18158
Issue Number: Close https://github.com/tikv/tikv/issues/18159
At an earlier stage, TiKV implemented region name validation to prevent errors caused by users setting random or incorrect region names. While this safeguard was effective in avoiding user mistakes, it also introduced limitations for the system itself.
Specifically, this check can cause backups to fail if new regions are added but the validation logic is not promptly updated to reflect the changes. To ensure greater flexibility and reduce the risk of backup disruptions, it is better to move this check to a more appropriate stage in the process.
Tests 
Side effects
```release-note
None
```

aws: remove region check when create s3 storage (#18158)

---

Cargo.lock
Makefile
clippy.toml
deny.toml

Issue Number: Close #18398
```commit-message
This is a manual cherry-pick of #18356, #18362, #18367 to fix build 
issues on the release-8.5 branch.
```
Tests 
Side effects
```release-note
None
```

CP #18356, #18362, #18367 to fix build issues

---

Cargo.lock
Makefile

Issue Number: Close #18353
```commit-message
Fixing compile error when using modern toolchain, like Apple Clang 17.0+
```
Tests 
Side effects
```release-note
None
```

RocksDB: Upgrade RocksDB

---

Cargo.lock
Makefile
clippy.toml
deny.toml

Issue Number: Close #18398
```commit-message
This is a manual cherry-pick of #18356, #18362, #18367 to fix build 
issues on the release-8.1 branch.
Also ran `cargo update -p rgb` to fix yanked version.
```
Tests 
Side effects
```release-note
None
```

CP #18356, #18362, #18367 to fix build issues (#18397)

---

Cargo.toml
tests/Cargo.toml

Issue Number: Close #18383
related PR: #18394
#18394 introduced `docker_test` feature, but it is not propagated to all rust workspaces. This PR add  `docker_test`  feature to `tests` package to cover test placed there as well. 
```commit-message
```
Tests 
Side effects
```release-note
None
```

tests: add docker_test feature to tests cargo

---

Cargo.lock
components/tidb_query_datatype/Cargo.toml
components/tidb_query_datatype/benches/bench_vector_distance.rs
components/tidb_query_datatype/src/codec/data_type/chunked_vec_vector_float32.rs
components/tidb_query_datatype/src/codec/datum.rs
components/tidb_query_datatype/src/codec/mysql/vector.rs
components/tidb_query_expr/src/impl_vec.rs

Issue Number: ref #17290
revert #17802 
Unfortunately, in my previous local test, I mistakenly verified the compatibility of linux/arm64 gcc8 with this pr in the x86 environment😢. This pr still needs to be upgraded to gcc9 in linux/arm64 to pass, and this compatibility issue is currently being resolved.
Tests 
Side effects
```release-note
None
```

Revert pr "copr: add simd for vector distance functions"

---

Cargo.lock

Issue Number: Close #18469
```commit-message
```
Tests 
Side effects
```release-note
None
```

*: update kvproto version

---

components/pd_client/src/util.rs
components/raftstore/src/store/worker/pd.rs

Issue Number: Close #18506
```commit-message
```
Tests 
Side effects
```release-note
None
```

pd: degrade useless log

---

components/engine_panic/src/import.rs
components/engine_rocks/src/import.rs
components/engine_rocks/src/misc.rs
components/engine_traits/src/import.rs
components/raftstore/src/store/snap/io.rs
components/sst_importer/src/import_file.rs
components/sst_importer/src/util.rs

Issue Number: ref #18081
```commit-message
```
Tests 
```release-note
Optimize tail request latency during TiDB add index
```

sst_importer: allow write during ingesting sst

---

Cargo.lock
Cargo.toml
components/raftstore/src/store/worker/region.rs
tests/failpoints/cases/test_titan.rs

Issue Number: Close #18434
```commit-message
Fixing Titan blob indices causing snapshot apply failures after Titan is turned off bug.
```
Tests 
Side effects
```release-note
Fixing Titan blob indices causing snapshot apply failures after Titan is turned off bug.
```

Titan: Fix turning off compatibility issue

---

components/raftstore/src/store/config.rs
src/config/mod.rs
src/import/sst_service.rs
src/server/metrics.rs
src/server/mod.rs
src/storage/config.rs
src/storage/config_manager.rs

Issue Number: Close #10047 
```commit-message
Register Missing TiKV Configs to Prometheus
Due to recent iterations and refactoring in TiKV, some important module configurations were not reported via metrics. 
This PR registers the configuration metrics for these key modules
```
Tests 
Side effects
```release-note
Register Missing TiKV Configs to Prometheus
```

metrics: Register Missing TiKV Configs to Prometheus

---

components/tidb_query_datatype/src/codec/collation/collator/gb18030_collation.rs
components/tidb_query_datatype/src/codec/collation/collator/gbk_collation.rs
components/tidb_query_datatype/src/codec/collation/collator/mod.rs
components/tidb_query_datatype/src/codec/collation/collator/utf8mb4_binary.rs
components/tidb_query_datatype/src/codec/collation/collator/utf8mb4_general_ci.rs
components/tidb_query_datatype/src/codec/collation/collator/utf8mb4_uca/data_0400.rs
components/tidb_query_datatype/src/codec/collation/collator/utf8mb4_uca/data_0900.rs
components/tidb_query_datatype/src/codec/collation/collator/utf8mb4_uca/mod.rs

Issue Number: Close #18633, Close https://github.com/pingcap/tidb/issues/47521
```commit-message
Fix process string contains invalid utf8 characters.
```
Tests 
Side effects
```release-note
Fix process string contains invalid utf8 characters.
```

collation: fix process non-utf8 characters

---

src/server/gc_worker/compaction_runner.rs

Issue Number: Ref #18727
```commit-message
Re-evaluate all regions when check interval is reached, even if it has not finished compacting all candidates 
```
Tests 
Side effects
```release-note
None
```

GC: Skip rest candidates if reaches check interval

---

components/tidb_query_datatype/src/codec/collation/collator/mod.rs
components/tidb_query_datatype/src/codec/collation/collator/utf8mb4_uca/mod.rs

Issue Number: Close #18784
```commit-message
Follow tidb code, see https://github.com/pingcap/tidb/blob/2a522358ceb60095eea898503682595dd3612492/pkg/util/collate/ucaimpl/unicode_ci.go.tpl#L50 to get more informations.
```
Tests 
Side effects
```release-note
None
```

collation: fix wrong compare result for unicode collate

---

Cargo.lock

Include rocksdb PR https://github.com/tikv/rocksdb/pull/417
Issue Number: Close #18743 
```commit-message
Optimize async snapshot and write tail latency with many SSTs
```
Tests 
Side effects
```release-note
Optimize async snapshot and write tail latency with many SSTs
```

rocksdb: Optimize async snapshot and write tail latency with many SSTs

---

README.md

If you don't use a list, you get the following error:
```
$ python3 ./main.py
Traceback (most recent call last):
File "/Users/bkane/Apps/2025-08-28-run-tikv/./main.py", line 3, in <module>
client = RawClient.connect("127.0.0.1:2379")
File "/Users/bkane/Apps/2025-08-28-run-tikv/venv/lib/python3.13/site-packages/tikv_client/__init__.py", line 14, in connect
inner = event_loop.run_until_complete(
asynchronous.RawClient.connect(pd_endpoints))
File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
return future.result()
~~~~~~~~~~~~~^^
File "/Users/bkane/Apps/2025-08-28-run-tikv/venv/lib/python3.13/site-packages/tikv_client/asynchronous/__init__.py", line 13, in connect
raise …
```

README: Python API update

---

src/import/sst_service.rs

Issue Number: ref #18865
A panic is found in the lightning test with raftstore-v2, see: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_lightning_integration_test/detail/pull_lightning_integration_test/11890/pipeline
```commit-message
When raftstore-v2 is enabled, each region ownes a separate kv engine, so the "force partition" mechanism is not needed. Because we can't get a kvengine instance with raft-v2, the current implementation will panic. This pr solve this bug by directly return if it's can't get the kvengine.
```
Tests 
Side effects
```release-note
None
```

sst_service: fix the panic on add_force_partition_range when raft-v2 is enabled

---

components/txn_types/src/lib.rs
tests/failpoints/cases/test_kv_service.rs

Issue Number: ref #18498
```commit-message
Disable ENABLE_DUP_KEY_DEBUG by default
```
Tests 
Side effects
```release-note
None
```

*: Disable ENABLE_DUP_KEY_DEBUG by default
